import { phrase, q, reading, sentence, vocab, type ChapterExtra } from "@/content/helpers";

export const a1Expand: Record<string, ChapterExtra> = {
  "alphabet-sounds": {
    vocab: [
      vocab("die Tafel", "the blackboard", undefined, "Tafeln"),
      vocab("der Stift", "the pen", undefined, "Stifte"),
      vocab("das Heft", "the notebook", undefined, "Hefte"),
      vocab("die Kreide", "the chalk"),
      vocab("buchstabieren", "to spell"),
      vocab("der Lehrer", "the teacher (m)", undefined, "Lehrer"),
      vocab("die Lehrerin", "the teacher (f)", undefined, "Lehrerinnen"),
      vocab("der Schüler", "the pupil (m)", undefined, "Schüler"),
      vocab("die Schülerin", "the pupil (f)", undefined, "Schülerinnen"),
      vocab("das Klassenzimmer", "the classroom", undefined, "Klassenzimmer"),
      vocab("die Hausaufgabe", "the homework", undefined, "Hausaufgaben"),
      vocab("die Aussprache", "the pronunciation"),
      vocab("die Silbe", "the syllable", undefined, "Silben"),
      vocab("der Vokal", "the vowel", undefined, "Vokale"),
      vocab("der Konsonant", "the consonant", undefined, "Konsonanten"),
      vocab("der Umlaut", "the umlaut", undefined, "Umlaute"),
      vocab("das Eszett", "the ß"),
      vocab("laut", "loud"),
      vocab("leise", "quiet"),
      vocab("merken", "to remember / notice"),
      vocab("deutlich", "clear"),
      vocab("der Unterricht", "the class / lesson"),
      vocab("die Note", "the grade / mark", undefined, "Noten"),
      vocab("die Klasse", "the class", undefined, "Klassen"),
      vocab("das Papier", "the paper"),
      vocab("der Radiergummi", "the eraser", undefined, "Radiergummis"),
      vocab("die Seite", "the page", undefined, "Seiten"),
      vocab("der Kurs", "the course", undefined, "Kurse"),
    ],
    phrases: [
      phrase("Bitte buchstabieren Sie.", "Please spell it."),
      phrase("Wie schreibt man das?", "How do you write that?"),
      phrase("Sprechen Sie laut.", "Speak loudly."),
      phrase("Bitte leise!", "Please be quiet!"),
      phrase("Noch eine Silbe.", "One more syllable."),
      phrase("Die Hausaufgabe ist auf Seite zehn.", "The homework is on page ten."),
    ],
    sentences: [
      sentence("Der Lehrer schreibt an die Tafel.", "The teacher writes on the blackboard."),
      sentence("Die Schülerin hat ein Heft und einen Stift.", "The pupil has a notebook and a pen."),
      sentence("Die Aussprache ist deutlich.", "The pronunciation is clear."),
      sentence("Im Klassenzimmer ist es leise.", "It is quiet in the classroom."),
      sentence("Ich merke den Umlaut.", "I notice the umlaut."),
      sentence("Der Kurs beginnt heute.", "The course starts today."),
    ],
    readings: [
      reading(
        "Classroom note",
        "Zettel im Klassenzimmer",
        "Liebe Klasse, bitte bringt ein Heft, einen Stift und einen Radiergummi. Die Hausaufgabe ist auf Seite acht. Sprechen Sie laut und deutlich. Der Unterricht beginnt um neun. Eure Lehrerin",
        "Dear class, please bring a notebook, a pen and an eraser. The homework is on page eight. Speak loudly and clearly. Class starts at nine. Your teacher",
        [
          q("What should they bring?", "A notebook, a pen and an eraser", ["Only a book", "A notebook, a pen and an eraser", "Food", "A phone"]),
          q("Where is the homework?", "On page eight", ["On the board", "On page eight", "At home", "In the bag"]),
          q("How should they speak?", "Loudly and clearly", ["Quietly", "Fast", "Loudly and clearly", "In English"]),
        ],
      ),
    ],
  },
  greetings: {
    vocab: [
      vocab("schütteln", "to shake"),
      vocab("der Gruß", "the greeting", undefined, "Grüße"),
      vocab("sich vorstellen", "to introduce oneself"),
      vocab("angenehm", "pleased / pleasant"),
      vocab("gleichfalls", "likewise"),
      vocab("bis bald", "see you soon"),
      vocab("bis später", "see you later"),
      vocab("ciao", "ciao / bye"),
      vocab("servus", "hi / bye (south)"),
      vocab("grüß Gott", "hello (south / Austria)"),
      vocab("moin", "hi (north)"),
      vocab("na", "well / hey"),
      vocab("alles klar", "all good / okay"),
      vocab("super", "great"),
      vocab("prima", "great / fine"),
      vocab("schade", "too bad"),
      vocab("natürlich", "of course"),
      vocab("genau", "exactly"),
      vocab("stimmt", "that's right"),
      vocab("okay", "okay"),
      vocab("tschö", "bye (casual)"),
      vocab("ade", "goodbye (regional)"),
      vocab("kennenlernen", "to get to know"),
      vocab("die Bekanntschaft", "the acquaintance"),
      vocab("herzlich", "warm / hearty"),
      vocab("der Händedruck", "the handshake", undefined, "Händedrücke"),
      vocab("nicken", "to nod"),
      vocab("lächeln", "to smile"),
    ],
    phrases: [
      phrase("Freut mich, Sie kennenzulernen.", "Pleased to meet you."),
      phrase("Gleichfalls!", "Likewise!"),
      phrase("Bis bald!", "See you soon!"),
      phrase("Alles klar bei dir?", "Everything okay with you?"),
      phrase("Das ist schade.", "That is too bad."),
      phrase("Natürlich, gerne.", "Of course, gladly."),
    ],
    sentences: [
      sentence("Wir schütteln uns die Hände.", "We shake hands."),
      sentence("Bis später im Café.", "See you later at the café."),
      sentence("Moin, alles klar?", "Hi, all good?"),
      sentence("Das ist schade.", "That is too bad."),
      sentence("Genau, das stimmt.", "Exactly, that's right."),
      sentence("Sie lächelt und sagt servus.", "She smiles and says servus."),
    ],
  },
  "numbers-time": {
    vocab: [
      vocab("dreizehn", "thirteen"),
      vocab("vierzehn", "fourteen"),
      vocab("fünfzehn", "fifteen"),
      vocab("sechzehn", "sixteen"),
      vocab("siebzehn", "seventeen"),
      vocab("achtzehn", "eighteen"),
      vocab("neunzehn", "nineteen"),
      vocab("dreißig", "thirty"),
      vocab("vierzig", "forty"),
      vocab("fünfzig", "fifty"),
      vocab("sechzig", "sixty"),
      vocab("siebzig", "seventy"),
      vocab("achtzig", "eighty"),
      vocab("neunzig", "ninety"),
      vocab("tausend", "thousand"),
      vocab("halb", "half"),
      vocab("das Viertel", "the quarter", undefined, "Viertel"),
      vocab("die Sekunde", "the second", undefined, "Sekunden"),
      vocab("Dienstag", "Tuesday"),
      vocab("Mittwoch", "Wednesday"),
      vocab("Donnerstag", "Thursday"),
      vocab("Samstag", "Saturday"),
      vocab("Sonntag", "Sunday"),
      vocab("der Januar", "January"),
      vocab("der Juli", "July"),
      vocab("der Dezember", "December"),
      vocab("ungefähr", "approximately"),
      vocab("die Uhrzeit", "the time of day"),
    ],
    phrases: [
      phrase("Es ist halb drei.", "It is half past two."),
      phrase("Es ist Viertel nach vier.", "It is a quarter past four."),
      phrase("Ungefähr fünfzig Minuten.", "About fifty minutes."),
      phrase("Am Dienstag um acht.", "On Tuesday at eight."),
      phrase("Heute ist Mittwoch.", "Today is Wednesday."),
      phrase("Welche Uhrzeit?", "What time?"),
    ],
    sentences: [
      sentence("Ich habe am Donnerstag Zeit.", "I have time on Thursday."),
      sentence("Samstag und Sonntag sind frei.", "Saturday and Sunday are free."),
      sentence("Im Januar ist es kalt.", "It is cold in January."),
      sentence("Tausend Euro sind viel.", "A thousand euros is a lot."),
      sentence("Wir treffen uns um halb acht.", "We meet at half past seven."),
      sentence("Im Juli haben wir Urlaub.", "In July we have holiday."),
    ],
  },
  "personal-info": {
    vocab: [
      vocab("der Pass", "the passport", undefined, "Pässe"),
      vocab("geschieden", "divorced"),
      vocab("verwitwet", "widowed"),
      vocab("der Geburtsort", "the place of birth", undefined, "Geburtsorte"),
      vocab("der Wohnort", "the place of residence", undefined, "Wohnorte"),
      vocab("die Postleitzahl", "the postcode", undefined, "Postleitzahlen"),
      vocab("anrufen", "to call"),
      vocab("weiblich", "female"),
      vocab("männlich", "male"),
      vocab("divers", "non-binary / diverse"),
      vocab("der Familienstand", "marital status"),
      vocab("die Staatsangehörigkeit", "citizenship"),
      vocab("Italien", "Italy"),
      vocab("Frankreich", "France"),
      vocab("Spanien", "Spain"),
      vocab("Polen", "Poland"),
      vocab("die Türkei", "Turkey"),
      vocab("die Niederlande", "the Netherlands"),
      vocab("ausfüllen", "to fill in"),
      vocab("das Feld", "the field / box", undefined, "Felder"),
      vocab("ankreuzen", "to tick"),
      vocab("drucken", "to print"),
      vocab("die Kopie", "the copy", undefined, "Kopien"),
      vocab("gültig", "valid"),
      vocab("ungültig", "invalid"),
      vocab("der Stempel", "the stamp / seal", undefined, "Stempel"),
      vocab("die Unterlage", "the document", undefined, "Unterlagen"),
      vocab("persönlich", "personal / in person"),
    ],
    phrases: [
      phrase("Bitte den Pass zeigen.", "Please show the passport."),
      phrase("Wie ist Ihre Postleitzahl?", "What is your postcode?"),
      phrase("Ich rufe später an.", "I will call later."),
      phrase("Bitte das Formular ausfüllen.", "Please fill in the form."),
      phrase("Familienstand: geschieden.", "Marital status: divorced."),
      phrase("Die Kopie ist gültig.", "The copy is valid."),
    ],
    sentences: [
      sentence("Mein Geburtsort ist Rom.", "My place of birth is Rome."),
      sentence("Ich komme aus Polen.", "I come from Poland."),
      sentence("Die Staatsangehörigkeit ist italienisch.", "The citizenship is Italian."),
      sentence("Bitte kreuzen Sie weiblich oder männlich an.", "Please tick female or male."),
      sentence("Ich brauche eine Kopie.", "I need a copy."),
      sentence("Die Unterlagen sind persönlich.", "The documents are personal."),
    ],
  },
  family: {
    vocab: [
      vocab("das Baby", "the baby", undefined, "Babys"),
      vocab("der Enkel", "the grandson", undefined, "Enkel"),
      vocab("die Enkelin", "the granddaughter", undefined, "Enkelinnen"),
      vocab("der Neffe", "the nephew", undefined, "Neffen"),
      vocab("die Nichte", "the niece", undefined, "Nichten"),
      vocab("Oma", "grandma"),
      vocab("Opa", "grandpa"),
      vocab("die Geschwister", "siblings"),
      vocab("das Paar", "the couple", undefined, "Paare"),
      vocab("die Hochzeit", "the wedding", undefined, "Hochzeiten"),
      vocab("das Haustier", "the pet", undefined, "Haustiere"),
      vocab("älter", "older"),
      vocab("jünger", "younger"),
      vocab("der Stiefvater", "the stepfather", undefined, "Stiefväter"),
      vocab("die Stiefmutter", "the stepmother", undefined, "Stiefmütter"),
      vocab("die Generation", "the generation", undefined, "Generationen"),
      vocab("sich kümmern", "to look after"),
      vocab("der Besuch", "the visit", undefined, "Besuche"),
      vocab("der Familientag", "the family day", undefined, "Familientage"),
      vocab("die Liebe", "love"),
      vocab("der Spitzname", "the nickname", undefined, "Spitznamen"),
      vocab("die Kindheit", "childhood"),
      vocab("verwandt", "related"),
      vocab("die Verwandtschaft", "the relatives"),
      vocab("das Patenkind", "the godchild", undefined, "Patenkinder"),
      vocab("der Schwager", "the brother-in-law", undefined, "Schwäger"),
      vocab("die Schwägerin", "the sister-in-law", undefined, "Schwägerinnen"),
      vocab("die Schwiegereltern", "parents-in-law"),
    ],
    phrases: [
      phrase("Das ist meine Oma.", "That is my grandma."),
      phrase("Wir haben zwei Geschwister.", "We have two siblings."),
      phrase("Sie ist älter als ich.", "She is older than I am."),
      phrase("Wir besuchen Opa am Sonntag.", "We visit grandpa on Sunday."),
      phrase("Hast du ein Haustier?", "Do you have a pet?"),
      phrase("Herzlichen Glückwunsch zur Hochzeit!", "Congratulations on the wedding!"),
    ],
    sentences: [
      sentence("Das Baby schläft.", "The baby is sleeping."),
      sentence("Meine Nichte ist jünger als mein Neffe.", "My niece is younger than my nephew."),
      sentence("Die Schwiegereltern kommen zu Besuch.", "The parents-in-law are coming to visit."),
      sentence("Oma und Opa wohnen zusammen.", "Grandma and grandpa live together."),
      sentence("Wir kümmern uns um das Haustier.", "We look after the pet."),
      sentence("Die Verwandtschaft ist groß.", "The family is large."),
    ],
  },
  "articles-nouns": {
    vocab: [
      vocab("der Löffel", "the spoon", undefined, "Löffel"),
      vocab("die Gabel", "the fork", undefined, "Gabeln"),
      vocab("das Messer", "the knife", undefined, "Messer"),
      vocab("der Teller", "the plate", undefined, "Teller"),
      vocab("die Tasse", "the cup", undefined, "Tassen"),
      vocab("das Glas", "the glass", undefined, "Gläser"),
      vocab("der Computer", "the computer", undefined, "Computer"),
      vocab("die Maus", "the mouse", undefined, "Mäuse"),
      vocab("die Tastatur", "the keyboard", undefined, "Tastaturen"),
      vocab("der Bildschirm", "the screen", undefined, "Bildschirme"),
      vocab("das Bild", "the picture", undefined, "Bilder"),
      vocab("der Spiegel", "the mirror", undefined, "Spiegel"),
      vocab("die Seife", "the soap", undefined, "Seifen"),
      vocab("das Handtuch", "the towel", undefined, "Handtücher"),
      vocab("der Kamm", "the comb", undefined, "Kämme"),
      vocab("die Bürste", "the brush", undefined, "Bürsten"),
      vocab("das Regal", "the shelf", undefined, "Regale"),
      vocab("der Teppich", "the carpet", undefined, "Teppiche"),
      vocab("die Decke", "the blanket / ceiling", undefined, "Decken"),
      vocab("das Kissen", "the pillow", undefined, "Kissen"),
      vocab("der Mülleimer", "the bin", undefined, "Mülleimer"),
      vocab("die Schublade", "the drawer", undefined, "Schubladen"),
      vocab("der Knopf", "the button", undefined, "Knöpfe"),
      vocab("die Schachtel", "the box", undefined, "Schachteln"),
      vocab("das Besteck", "the cutlery"),
      vocab("die Spüle", "the sink", undefined, "Spülen"),
      vocab("der Hahn", "the tap", undefined, "Hähne"),
      vocab("das Licht", "the light", undefined, "Lichter"),
    ],
    phrases: [
      phrase("Wo ist der Löffel?", "Where is the spoon?"),
      phrase("Das Glas steht auf dem Tisch.", "The glass is on the table."),
      phrase("Die Tastatur ist neu.", "The keyboard is new."),
      phrase("Mach das Licht an.", "Turn the light on."),
      phrase("In der Schublade liegt ein Kamm.", "A comb is in the drawer."),
      phrase("Das Besteck ist in der Spüle.", "The cutlery is in the sink."),
    ],
    sentences: [
      sentence("Ein Teller, eine Tasse und ein Glas.", "A plate, a cup and a glass."),
      sentence("Der Computer hat eine Maus.", "The computer has a mouse."),
      sentence("Das Bild hängt über dem Teppich.", "The picture hangs above the carpet."),
      sentence("Die Seife liegt neben dem Handtuch.", "The soap is next to the towel."),
      sentence("Die Schachtel ist in der Schublade.", "The box is in the drawer."),
      sentence("Der Knopf am Schrank ist klein.", "The button on the cupboard is small."),
    ],
  },
  "colors-adjectives": {
    vocab: [
      vocab("orange", "orange"),
      vocab("lila", "purple"),
      vocab("rosa", "pink"),
      vocab("beige", "beige"),
      vocab("golden", "golden"),
      vocab("silber", "silver"),
      vocab("bunt", "colorful"),
      vocab("einfarbig", "plain / one-colored"),
      vocab("hellblau", "light blue"),
      vocab("dunkelrot", "dark red"),
      vocab("kariert", "checked"),
      vocab("gestreift", "striped"),
      vocab("rund", "round"),
      vocab("eckig", "square / angular"),
      vocab("breit", "wide"),
      vocab("schmal", "narrow"),
      vocab("dick", "thick / fat"),
      vocab("dünn", "thin"),
      vocab("schwer", "heavy / difficult"),
      vocab("leicht", "light / easy"),
      vocab("sauber", "clean"),
      vocab("schmutzig", "dirty"),
      vocab("weich", "soft"),
      vocab("hart", "hard"),
      vocab("glatt", "smooth"),
      vocab("rau", "rough"),
      vocab("das Muster", "the pattern", undefined, "Muster"),
      vocab("der Stoff", "the fabric", undefined, "Stoffe"),
    ],
    phrases: [
      phrase("Das Kleid ist rosa und kariert.", "The dress is pink and checked."),
      phrase("Ein runder, orangefarbener Teller.", "A round orange plate."),
      phrase("Der Stoff ist weich.", "The fabric is soft."),
      phrase("Die Straße ist schmal.", "The street is narrow."),
      phrase("Das Hemd ist gestreift.", "The shirt is striped."),
      phrase("Es ist nicht schwer, nur bunt.", "It is not hard, just colorful."),
    ],
    sentences: [
      sentence("Der Stuhl ist beige und leicht.", "The chair is beige and light."),
      sentence("Ein dunkelrotes Kissen liegt da.", "A dark-red pillow is lying there."),
      sentence("Die Tasche ist schmutzig, nicht sauber.", "The bag is dirty, not clean."),
      sentence("Lila und orange sind bunt.", "Purple and orange are colorful."),
      sentence("Der Tisch ist hart und glatt.", "The table is hard and smooth."),
      sentence("Ein schmales, silbernes Band.", "A narrow silver ribbon."),
    ],
  },
  "food-drinks": {
    vocab: [
      vocab("die Tomate", "the tomato", undefined, "Tomaten"),
      vocab("die Gurke", "the cucumber", undefined, "Gurken"),
      vocab("die Kartoffel", "the potato", undefined, "Kartoffeln"),
      vocab("die Zwiebel", "the onion", undefined, "Zwiebeln"),
      vocab("der Reis", "the rice"),
      vocab("die Nudel", "the noodle", undefined, "Nudeln"),
      vocab("das Ei", "the egg", undefined, "Eier"),
      vocab("das Hähnchen", "the chicken"),
      vocab("die Wurst", "the sausage", undefined, "Würste"),
      vocab("der Schinken", "the ham"),
      vocab("der Joghurt", "the yoghurt", undefined, "Joghurts"),
      vocab("das Eis", "the ice cream / ice"),
      vocab("der Kuchen", "the cake", undefined, "Kuchen"),
      vocab("die Schokolade", "the chocolate"),
      vocab("der Zucker", "the sugar"),
      vocab("das Salz", "the salt"),
      vocab("der Pfeffer", "the pepper"),
      vocab("das Öl", "the oil"),
      vocab("der Essig", "the vinegar"),
      vocab("die Marmelade", "the jam", undefined, "Marmeladen"),
      vocab("das Müsli", "the muesli"),
      vocab("vegan", "vegan"),
      vocab("scharf", "spicy / hot"),
      vocab("süß", "sweet"),
      vocab("sauer", "sour"),
      vocab("salzig", "salty"),
      vocab("der Nachtisch", "the dessert", undefined, "Nachtische"),
      vocab("die Bestellung", "the order", undefined, "Bestellungen"),
    ],
    phrases: [
      phrase("Ich möchte Reis und Hähnchen.", "I would like rice and chicken."),
      phrase("Ist das scharf?", "Is that spicy?"),
      phrase("Zum Nachtisch Eis.", "Ice cream for dessert."),
      phrase("Mit Salz und Pfeffer, bitte.", "With salt and pepper, please."),
      phrase("Die Bestellung ist vegan.", "The order is vegan."),
      phrase("Tomate, Gurke und Zwiebel.", "Tomato, cucumber and onion."),
    ],
    sentences: [
      sentence("Die Kartoffeln sind nicht süß.", "The potatoes are not sweet."),
      sentence("Ich esse Nudeln mit Öl.", "I eat noodles with oil."),
      sentence("Der Joghurt ist sauer.", "The yoghurt is sour."),
      sentence("Wir kaufen Wurst und Schinken.", "We buy sausage and ham."),
      sentence("Der Kuchen hat Schokolade.", "The cake has chocolate."),
      sentence("Müsli mit Marmelade zum Frühstück.", "Muesli with jam for breakfast."),
    ],
  },
  "first-reading": {
    vocab: [
      vocab("der Pfeil", "the arrow", undefined, "Pfeile"),
      vocab("der Notausgang", "the emergency exit", undefined, "Notausgänge"),
      vocab("die Treppe", "the stairs", undefined, "Treppen"),
      vocab("der Aufzug", "the lift", undefined, "Aufzüge"),
      vocab("die Etage", "the floor / storey", undefined, "Etagen"),
      vocab("der Empfang", "the reception"),
      vocab("die Rezeption", "the reception desk", undefined, "Rezeptionen"),
      vocab("der Automat", "the machine", undefined, "Automaten"),
      vocab("die Linie", "the line / route", undefined, "Linien"),
      vocab("die Kirche", "the church", undefined, "Kirchen"),
      vocab("die Moschee", "the mosque", undefined, "Moscheen"),
      vocab("die Synagoge", "the synagogue", undefined, "Synagogen"),
      vocab("das Denkmal", "the monument", undefined, "Denkmäler"),
      vocab("der Brunnen", "the fountain", undefined, "Brunnen"),
      vocab("die Sehenswürdigkeit", "the sight", undefined, "Sehenswürdigkeiten"),
      vocab("das Stockwerk", "the floor", undefined, "Stockwerke"),
      vocab("der Hinweis", "the notice", undefined, "Hinweise"),
      vocab("die Warnung", "the warning", undefined, "Warnungen"),
      vocab("privat", "private"),
      vocab("öffentlich", "public"),
      vocab("der Eingangsbereich", "the entrance area"),
      vocab("die Durchsage", "the announcement", undefined, "Durchsagen"),
      vocab("steigen", "to climb / get on"),
      vocab("halten", "to stop / hold"),
      vocab("das Hinweisschild", "the information sign", undefined, "Hinweisschilder"),
      vocab("der Wegweiser", "the signpost", undefined, "Wegweiser"),
      vocab("die Orientierung", "orientation"),
      vocab("folgen", "to follow"),
    ],
    phrases: [
      phrase("Folgen Sie dem Pfeil.", "Follow the arrow."),
      phrase("Notausgang links.", "Emergency exit on the left."),
      phrase("Aufzug außer Betrieb.", "Lift out of order."),
      phrase("Zweite Etage: Empfang.", "Second floor: reception."),
      phrase("Öffentlich, nicht privat.", "Public, not private."),
      phrase("Bitte an der Rezeption halten.", "Please stop at reception."),
    ],
    sentences: [
      sentence("Die Kirche ist eine Sehenswürdigkeit.", "The church is a sight."),
      sentence("Wir steigen in den Aufzug.", "We get into the lift."),
      sentence("Die Durchsage kommt vom Automat.", "The announcement comes from the machine."),
      sentence("Das Denkmal steht am Brunnen.", "The monument stands by the fountain."),
      sentence("Die Warnung ist wichtig.", "The warning is important."),
      sentence("Die Linie hält hier.", "The line stops here."),
    ],
  },
  "first-writing": {
    vocab: [
      vocab("der Brief", "the letter", undefined, "Briefe"),
      vocab("die Post", "the post / mail"),
      vocab("der Umschlag", "the envelope", undefined, "Umschläge"),
      vocab("die Briefmarke", "the stamp", undefined, "Briefmarken"),
      vocab("das Porto", "the postage"),
      vocab("die Anschrift", "the postal address", undefined, "Anschriften"),
      vocab("die Zeile", "the line", undefined, "Zeilen"),
      vocab("der Absatz", "the paragraph", undefined, "Absätze"),
      vocab("das Komma", "the comma", undefined, "Kommas"),
      vocab("das Fragezeichen", "the question mark", undefined, "Fragezeichen"),
      vocab("das Ausrufezeichen", "the exclamation mark", undefined, "Ausrufezeichen"),
      vocab("die Großschreibung", "capitalization"),
      vocab("tippen", "to type"),
      vocab("speichern", "to save"),
      vocab("das Passwort", "the password", undefined, "Passwörter"),
      vocab("anmelden", "to log in / register"),
      vocab("der Benutzer", "the user", undefined, "Benutzer"),
      vocab("der Entwurf", "the draft", undefined, "Entwürfe"),
      vocab("abschicken", "to send off"),
      vocab("die Anredezeile", "the greeting line", undefined, "Anredezeilen"),
      vocab("der Schlussgruß", "the closing greeting", undefined, "Schlussgrüße"),
      vocab("blockschrift", "block capitals"),
      vocab("leserlich", "legible"),
      vocab("unleserlich", "illegible"),
      vocab("ergänzen", "to complete / add"),
      vocab("streichen", "to cross out"),
      vocab("das Leerzeichen", "the space", undefined, "Leerzeichen"),
      vocab("die Tastaturtaste", "the key", undefined, "Tastaturtasten"),
    ],
    phrases: [
      phrase("Bitte in Blockschrift.", "Please in block capitals."),
      phrase("Die Anschrift auf den Umschlag.", "The address on the envelope."),
      phrase("Passwort nicht vergessen.", "Do not forget the password."),
      phrase("Eine Zeile ergänzen.", "Complete one line."),
      phrase("Mit Komma und Punkt.", "With comma and full stop."),
      phrase("Die Nachricht speichern.", "Save the message."),
    ],
    sentences: [
      sentence("Der Brief braucht eine Briefmarke.", "The letter needs a stamp."),
      sentence("Ich tippe die Anrede.", "I type the salutation."),
      sentence("Die Schrift ist leserlich.", "The writing is legible."),
      sentence("Streiche den Fehler.", "Cross out the mistake."),
      sentence("Der Entwurf ist kurz.", "The draft is short."),
      sentence("Wir schicken die Post ab.", "We send the mail off."),
    ],
  },
  home: {
    vocab: [
      vocab("das Esszimmer", "the dining room", undefined, "Esszimmer"),
      vocab("der Keller", "the cellar", undefined, "Keller"),
      vocab("der Dachboden", "the attic", undefined, "Dachböden"),
      vocab("die Garage", "the garage", undefined, "Garagen"),
      vocab("die Terrasse", "the terrace", undefined, "Terrassen"),
      vocab("das Dach", "the roof", undefined, "Dächer"),
      vocab("die Heizung", "the heating", undefined, "Heizungen"),
      vocab("die Steckdose", "the socket", undefined, "Steckdosen"),
      vocab("der Stecker", "the plug", undefined, "Stecker"),
      vocab("die Dusche", "the shower", undefined, "Duschen"),
      vocab("die Badewanne", "the bathtub", undefined, "Badewannen"),
      vocab("der Müll", "the rubbish"),
      vocab("die Möbel", "the furniture"),
      vocab("gemütlich", "cosy"),
      vocab("die Pflanze", "the plant", undefined, "Pflanzen"),
      vocab("der Vorhang", "the curtain", undefined, "Vorhänge"),
      vocab("die Garderobe", "the wardrobe / coat rack", undefined, "Garderoben"),
      vocab("einziehen", "to move in"),
      vocab("umziehen", "to move house"),
      vocab("die Nachbarschaft", "the neighbourhood"),
      vocab("die Etagenwohnung", "the flat on a floor", undefined, "Etagenwohnungen"),
      vocab("das Einfamilienhaus", "the detached house", undefined, "Einfamilienhäuser"),
      vocab("die WG", "the shared flat", undefined, "WGs"),
      vocab("der Mitbewohner", "the flatmate (m)", undefined, "Mitbewohner"),
      vocab("die Mitbewohnerin", "the flatmate (f)", undefined, "Mitbewohnerinnen"),
      vocab("heizen", "to heat"),
      vocab("lüften", "to air / ventilate"),
      vocab("putzen", "to clean"),
    ],
    phrases: [
      phrase("Die WG ist gemütlich.", "The shared flat is cosy."),
      phrase("Bitte lüften und heizen.", "Please air and heat."),
      phrase("Der Müll steht im Keller.", "The rubbish is in the cellar."),
      phrase("Steckdose hinter dem Vorhang.", "Socket behind the curtain."),
      phrase("Wir ziehen nächsten Monat ein.", "We move in next month."),
      phrase("Dusche oder Badewanne?", "Shower or bathtub?"),
    ],
    sentences: [
      sentence("Das Esszimmer liegt neben der Terrasse.", "The dining room is next to the terrace."),
      sentence("Auf dem Dachboden sind alte Möbel.", "There is old furniture in the attic."),
      sentence("Die Pflanze braucht Licht.", "The plant needs light."),
      sentence("Mein Mitbewohner putzt das Bad.", "My flatmate cleans the bathroom."),
      sentence("Die Garage gehört zum Einfamilienhaus.", "The garage belongs to the detached house."),
      sentence("Die Heizung ist im Winter wichtig.", "The heating is important in winter."),
    ],
  },
  "daily-routine": {
    vocab: [
      vocab("sich waschen", "to wash oneself"),
      vocab("die Zähne putzen", "to brush one's teeth"),
      vocab("die Schule", "the school", undefined, "Schulen"),
      vocab("die Universität", "the university", undefined, "Universitäten"),
      vocab("einkaufen", "to shop"),
      vocab("spazieren", "to go for a walk"),
      vocab("fernsehen", "to watch TV"),
      vocab("die Hausarbeit", "the housework"),
      vocab("das Bett machen", "to make the bed"),
      vocab("der Feierabend", "the end of the workday"),
      vocab("unterwegs", "on the way"),
      vocab("rechtzeitig", "in time"),
      vocab("die S-Bahn", "the suburban train", undefined, "S-Bahnen"),
      vocab("die U-Bahn", "the underground", undefined, "U-Bahnen"),
      vocab("die Straßenbahn", "the tram", undefined, "Straßenbahnen"),
      vocab("das Taxi", "the taxi", undefined, "Taxis"),
      vocab("der Fahrplan", "the timetable", undefined, "Fahrpläne"),
      vocab("gähnen", "to yawn"),
      vocab("sich beeilen", "to hurry"),
      vocab("verschlafen", "to oversleep"),
      vocab("der Feiertag", "the public holiday", undefined, "Feiertage"),
      vocab("werktags", "on weekdays"),
      vocab("am Wochenende", "at the weekend"),
      vocab("die Mittagspause", "the lunch break", undefined, "Mittagspausen"),
      vocab("zurückkommen", "to come back"),
      vocab("einschlafen", "to fall asleep"),
      vocab("aufbleiben", "to stay up"),
      vocab("die Gewohnheit", "the habit", undefined, "Gewohnheiten"),
    ],
    phrases: [
      phrase("Ich putze mir die Zähne.", "I brush my teeth."),
      phrase("Rechtzeitig zur S-Bahn.", "In time for the suburban train."),
      phrase("Nach dem Feierabend fernsehen.", "Watch TV after work."),
      phrase("Werktags zur Universität.", "To university on weekdays."),
      phrase("Nicht verschlafen!", "Don't oversleep!"),
      phrase("Am Wochenende spazieren.", "Go for a walk at the weekend."),
    ],
    sentences: [
      sentence("Ich wasche mich und mache das Bett.", "I wash and make the bed."),
      sentence("Die U-Bahn ist unterwegs voll.", "The underground is full on the way."),
      sentence("Nach der Mittagspause komme ich zurück.", "After the lunch break I come back."),
      sentence("Die Straßenbahn hat einen Fahrplan.", "The tram has a timetable."),
      sentence("Abends schlafe ich ein.", "In the evening I fall asleep."),
      sentence("Hausarbeit ist eine Gewohnheit.", "Housework is a habit."),
    ],
  },
};
