import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const a1ChaptersPart2: ChapterSource[] = [
  chapter(
    "colors-adjectives",
    "Colors, Size & Simple Adjectives",
    "Farben, Größe und einfache Adjektive",
    "Read descriptions of objects and people, then write short, clear portraits.",
    "vocab",
    [
      "Predicative adjectives do not add endings: Der Hund ist groß.",
      "After der/die/das, attributive adjectives take -e in the nominative singular: der große Hund.",
      "Nicht stands before the adjective it negates: Das Auto ist nicht teuer.",
    ],
    {
      vocab: [
        vocab("rot", "red"),
        vocab("blau", "blue"),
        vocab("grün", "green"),
        vocab("gelb", "yellow"),
        vocab("schwarz", "black"),
        vocab("weiß", "white"),
        vocab("braun", "brown"),
        vocab("grau", "grey"),
        vocab("die Farbe", "the color", undefined, "Farben"),
        vocab("groß", "big / tall"),
        vocab("klein", "small"),
        vocab("lang", "long"),
        vocab("kurz", "short"),
        vocab("schön", "beautiful"),
        vocab("hässlich", "ugly"),
        vocab("neu", "new"),
        vocab("alt", "old"),
        vocab("jung", "young"),
        vocab("schnell", "fast"),
        vocab("langsam", "slow"),
        vocab("warm", "warm"),
        vocab("kalt", "cold"),
        vocab("hell", "bright"),
        vocab("dunkel", "dark"),
        vocab("das Auto", "the car", undefined, "Autos"),
        vocab("der Hund", "the dog", undefined, "Hunde"),
        vocab("die Katze", "the cat", undefined, "Katzen"),
        vocab("das Haus", "the house", undefined, "Häuser"),
        vocab("sehr", "very"),
        vocab("zu", "too"),
        vocab("nicht", "not"),
        vocab("beschreiben", "to describe"),
      ],
      phrases: [
        phrase("Welche Farbe hat das Auto?", "What color is the car?"),
        phrase("Es ist rot.", "It is red."),
        phrase("Der Hund ist groß und braun.", "The dog is big and brown."),
        phrase("Die Katze ist klein und weiß.", "The cat is small and white."),
        phrase("Das Haus ist nicht alt.", "The house is not old."),
        phrase("Es ist zu kalt.", "It is too cold."),
        phrase("Ein schönes Bild.", "A beautiful picture."),
        phrase("Der Pullover ist zu lang.", "The sweater is too long."),
        phrase("Heute ist es hell.", "It is bright today."),
        phrase("Das neue Auto ist schnell.", "The new car is fast."),
        phrase("Ich mag Grün.", "I like green."),
        phrase("Beschreib den Hund.", "Describe the dog."),
      ],
      sentences: [
        sentence("Das Auto ist blau.", "The car is blue."),
        sentence("Der Hund ist nicht klein.", "The dog is not small."),
        sentence("Die Katze ist sehr schön.", "The cat is very beautiful."),
        sentence("Das Haus ist alt und grau.", "The house is old and grey."),
        sentence("Mein Pullover ist gelb.", "My sweater is yellow."),
        sentence("Die Tür ist dunkelbraun.", "The door is dark brown."),
        sentence("Es ist zu warm hier.", "It is too warm here."),
        sentence("Der junge Mann ist schnell.", "The young man is fast."),
        sentence("Ein kurzer Satz ist gut.", "A short sentence is good."),
        sentence("Die lange Straße ist hell.", "The long street is bright."),
        sentence("Schwarz und weiß sind Farben.", "Black and white are colors."),
        sentence("Das Bild ist nicht hässlich.", "The picture is not ugly."),
        sentence("Ein kleines Haus steht da.", "A small house stands there."),
        sentence("Die neue Lampe ist grün.", "The new lamp is green."),
        sentence("Der alte Tisch ist braun.", "The old table is brown."),
        sentence("Ich sehe einen großen Hund.", "I see a big dog."),
        sentence("Die Katze ist nicht schnell.", "The cat is not fast."),
        sentence("Heute ist der Himmel blau.", "Today the sky is blue."),
      ],
      readings: [
        reading(
          "Lost pet notice",
          "Vermisst",
          "Hund vermisst. Name: Bruno. Farbe: braun und schwarz. Er ist groß, nicht klein. Ein altes, freundliches Tier. Bitte anrufen. Danke!",
          "Dog missing. Name: Bruno. Color: brown and black. He is big, not small. An old, friendly animal. Please call. Thank you!",
          [
            q("What color is Bruno?", "Brown and black", ["White", "Blue", "Brown and black", "Yellow"]),
            q("Is Bruno small?", "No", ["Yes", "No", "Sometimes", "Unknown"]),
            q("What kind of animal is he?", "A dog", ["A cat", "A dog", "A bird", "A horse"]),
          ],
        ),
        reading(
          "Apartment listing",
          "Wohnungsanzeige",
          "Kleines Haus, nicht teuer. Farbe: weiß. Ein schönes, helles Fenster. Die Tür ist grün. Zu alt? Nein. Warm im Winter, nicht zu kalt.",
          "Small house, not expensive. Color: white. A beautiful, bright window. The door is green. Too old? No. Warm in winter, not too cold.",
          [
            q("What color is the door?", "Green", ["White", "Green", "Red", "Black"]),
            q("Is the house expensive?", "No", ["Yes", "No", "Very", "Unknown"]),
            q("How is the window described?", "Beautiful and bright", ["Dark", "Broken", "Beautiful and bright", "Small only"]),
          ],
        ),
        reading(
          "A postcard",
          "Eine Postkarte",
          "Liebe Anna, das Auto ist neu und rot. Die Stadt ist nicht grau, sondern bunt. Ein großer Park ist grün. Es ist warm. Bis bald, Felix.",
          "Dear Anna, the car is new and red. The city is not grey but colorful. A big park is green. It is warm. See you soon, Felix.",
          [
            q("What is new?", "The car", ["The park", "The car", "Anna", "Winter"]),
            q("How is the city?", "Colorful", ["Grey", "Colorful", "Cold", "Empty"]),
            q("Who wrote the card?", "Felix", ["Anna", "Bruno", "Felix", "Greta"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe an object with two colors and one size word.",
          "Beschreib ein Objekt.",
          "Das Auto ist klein und rot. Es ist nicht alt.",
          ["Use ist + adjective", "Add nicht if you want a contrast"],
        ),
        writing(
          "Write four sentences about a pet or a house.",
          "Schreib vier Sätze über ein Tier oder Haus.",
          "Der Hund ist groß. Er ist braun. Er ist nicht schnell. Er ist nett.",
          ["Keep adjectives predicative (no extra ending) at A1"],
        ),
      ],
    },
  ),
  chapter(
    "food-drinks",
    "Food, Drinks & Meals",
    "Essen, Trinken und Mahlzeiten",
    "Read menus and shopping notes, then order and write a simple food list.",
    "mixed",
    [
      "ich möchte + noun is a polite way to order.",
      "essen (eat) vs trinken (drink). Möchten you use for wishes.",
      "Accusative appears after many verbs: Ich esse einen Apfel.",
    ],
    {
      vocab: [
        vocab("das Brot", "the bread"),
        vocab("das Brötchen", "the roll", undefined, "Brötchen"),
        vocab("der Käse", "the cheese"),
        vocab("die Butter", "the butter"),
        vocab("der Apfel", "the apple", undefined, "Äpfel"),
        vocab("die Banane", "the banana", undefined, "Bananen"),
        vocab("das Wasser", "the water"),
        vocab("der Kaffee", "the coffee"),
        vocab("der Tee", "the tea"),
        vocab("die Milch", "the milk"),
        vocab("der Saft", "the juice", undefined, "Säfte"),
        vocab("das Bier", "the beer"),
        vocab("der Wein", "the wine"),
        vocab("die Suppe", "the soup", undefined, "Suppen"),
        vocab("der Salat", "the salad"),
        vocab("das Fleisch", "the meat"),
        vocab("der Fisch", "the fish"),
        vocab("vegetarisch", "vegetarian"),
        vocab("lecker", "tasty"),
        vocab("hungrig", "hungry"),
        vocab("durstig", "thirsty"),
        vocab("das Frühstück", "breakfast"),
        vocab("das Mittagessen", "lunch"),
        vocab("das Abendessen", "dinner"),
        vocab("die Speisekarte", "the menu", undefined, "Speisekarten"),
        vocab("bestellen", "to order"),
        vocab("essen", "to eat"),
        vocab("trinken", "to drink"),
        vocab("möchten", "would like"),
        vocab("der Hunger", "hunger"),
        vocab("der Durst", "thirst"),
        vocab("die Rechnung", "the bill", undefined, "Rechnungen"),
      ],
      phrases: [
        phrase("Ich hätte gern einen Kaffee.", "I would like a coffee."),
        phrase("Ich möchte das Menü bitte.", "I would like the menu, please."),
        phrase("Bin ich hier richtig für vegetarisch?", "Is this right for vegetarian?"),
        phrase("Die Speisekarte bitte.", "The menu, please."),
        phrase("Ich bin hungrig.", "I am hungry."),
        phrase("Haben Sie Wasser?", "Do you have water?"),
        phrase("Das schmeckt lecker.", "That tastes delicious."),
        phrase("Zum Frühstück esse ich Brot.", "For breakfast I eat bread."),
        phrase("Die Rechnung bitte.", "The bill, please."),
        phrase("Ohne Fleisch, bitte.", "Without meat, please."),
        phrase("Noch ein Glas Wasser.", "Another glass of water."),
        phrase("Guten Appetit!", "Enjoy your meal!"),
      ],
      sentences: [
        sentence("Ich esse ein Brötchen.", "I eat a roll."),
        sentence("Sie trinkt Tee.", "She drinks tea."),
        sentence("Wir möchten zwei Äpfel.", "We would like two apples."),
        sentence("Der Käse ist lecker.", "The cheese is tasty."),
        sentence("Ich bin nicht durstig.", "I am not thirsty."),
        sentence("Das Mittagessen ist um eins.", "Lunch is at one."),
        sentence("Er bestellt die Suppe.", "He orders the soup."),
        sentence("Kein Bier für mich.", "No beer for me."),
        sentence("Die Milch ist kalt.", "The milk is cold."),
        sentence("Ich möchte einen Salat.", "I would like a salad."),
        sentence("Zum Abendessen gibt es Fisch.", "There is fish for dinner."),
        sentence("Das Brot und die Butter bitte.", "The bread and the butter, please."),
        sentence("Vegetarisch ist kein Problem.", "Vegetarian is no problem."),
        sentence("Der Saft ist süß.", "The juice is sweet."),
        sentence("Wir essen zusammen.", "We eat together."),
        sentence("Hast du Hunger?", "Are you hungry?"),
        sentence("Ja, ich möchte Pizza.", "Yes, I would like pizza."),
        sentence("Die Rechnung ist teuer.", "The bill is expensive."),
      ],
      readings: [
        reading(
          "Café menu",
          "Speisekarte",
          "Frühstück: Brot, Käse, Ei, Kaffee oder Tee. Mittag: Suppe, Salat, Fisch. Getränke: Wasser, Saft, Milch. Vegetarisch: ja. Rechnung an der Theke.",
          "Breakfast: bread, cheese, egg, coffee or tea. Lunch: soup, salad, fish. Drinks: water, juice, milk. Vegetarian: yes. Bill at the counter.",
          [
            q("Where do you pay?", "At the counter", ["At the table only", "At the counter", "Online", "Never"]),
            q("Is vegetarian food available?", "Yes", ["No", "Yes", "Only on Monday", "Unknown"]),
            q("Which drink is listed first?", "Water", ["Beer", "Wine", "Water", "Coffee"]),
          ],
        ),
        reading(
          "Shopping note",
          "Einkaufszettel",
          "Bitte kaufen: Milch, Brot, Äpfel, Käse, Tee. Kein Bier. Die Banane ist schon da. Ich bin hungrig, also auch ein Brötchen. Danke, Mama.",
          "Please buy: milk, bread, apples, cheese, tea. No beer. The banana is already there. I am hungry, so a roll too. Thanks, Mom.",
          [
            q("What should not be bought?", "Beer", ["Milk", "Tea", "Beer", "Cheese"]),
            q("What is already at home?", "Banana", ["Bread", "Banana", "Fish", "Soup"]),
            q("Who is the note for?", "Mom", ["A waiter", "Mom", "A teacher", "A doctor"]),
          ],
        ),
        reading(
          "A restaurant text message",
          "SMS vom Restaurant",
          "Tisch für zwei um sieben. Wir möchten vegetarisch essen. Wasser und Wein sind da. Die Suppe ist lecker. Bis später am Marktplatz.",
          "Table for two at seven. We would like to eat vegetarian. Water and wine are there. The soup is tasty. See you later at the market square.",
          [
            q("How many people?", "Two", ["One", "Two", "Seven", "Four"]),
            q("What kind of food do they want?", "Vegetarian", ["Fish only", "Meat", "Vegetarian", "Breakfast"]),
            q("When is the table?", "At seven", ["At noon", "At seven", "In the morning", "Never"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 5-item shopping list in German.",
          "Schreib einen Einkaufszettel.",
          "Brot, Milch, Äpfel, Käse, Tee",
          ["Nouns are capitalized", "Articles optional on lists"],
        ),
        writing(
          "Order food in three polite sentences.",
          "Bestelle in drei Sätzen.",
          "Ich möchte einen Salat. Und Wasser bitte. Die Rechnung später.",
          ["Use ich möchte", "Add bitte"],
        ),
      ],
    },
  ),
  chapter(
    "first-reading",
    "First Reading: Signs, Menus & Messages",
    "Erstes Lesen: Schilder, Speisekarten, Nachrichten",
    "Train the core A1 skill: scan short real-world German and catch the meaning.",
    "reading",
    [
      "You do not need every word. Names, numbers, and verbs often carry the message.",
      "Signs drop articles and verbs: Ausgang, geöffnet, Zug nach Hamburg.",
      "Read the title first, then the numbers, then the rest.",
    ],
    {
      vocab: [
        vocab("das Schild", "the sign", undefined, "Schilder"),
        vocab("der Ausgang", "the exit", undefined, "Ausgänge"),
        vocab("der Eingang", "the entrance", undefined, "Eingänge"),
        vocab("geöffnet", "open"),
        vocab("geschlossen", "closed"),
        vocab("frei", "free / vacant"),
        vocab("besetzt", "occupied"),
        vocab("die Information", "the information", undefined, "Informationen"),
        vocab("der Plan", "the map / plan", undefined, "Pläne"),
        vocab("die Nachricht", "the message", undefined, "Nachrichten"),
        vocab("dringend", "urgent"),
        vocab("heute", "today"),
        vocab("morgen", "tomorrow"),
        vocab("der Zug", "the train", undefined, "Züge"),
        vocab("der Bus", "the bus", undefined, "Busse"),
        vocab("die Haltestelle", "the stop", undefined, "Haltestellen"),
        vocab("der Park", "the park", undefined, "Parks"),
        vocab("das Museum", "the museum", undefined, "Museen"),
        vocab("die Öffnungszeit", "the opening hour", undefined, "Öffnungszeiten"),
        vocab("verboten", "forbidden"),
        vocab("erlaubt", "allowed"),
        vocab("Achtung", "attention / caution"),
        vocab("Hilfe", "help"),
        vocab("links", "left"),
        vocab("rechts", "right"),
        vocab("geradeaus", "straight ahead"),
        vocab("der Text", "the text", undefined, "Texte"),
        vocab("verstehen", "to understand"),
        vocab("suchen", "to look for"),
        vocab("finden", "to find"),
        vocab("wichtig", "important"),
        vocab("einfach", "simple"),
      ],
      phrases: [
        phrase("Eingang links.", "Entrance on the left."),
        phrase("Ausgang geradeaus.", "Exit straight ahead."),
        phrase("Heute geschlossen.", "Closed today."),
        phrase("Geöffnet von 9 bis 18 Uhr.", "Open from 9 to 6."),
        phrase("Achtung, nasser Boden!", "Caution, wet floor!"),
        phrase("Rauchen verboten.", "No smoking."),
        phrase("Hunde erlaubt.", "Dogs allowed."),
        phrase("Zug nach Hamburg, Gleis 4.", "Train to Hamburg, platform 4."),
        phrase("Bitte warten.", "Please wait."),
        phrase("Hilfe suchen am Schalter.", "Look for help at the counter."),
        phrase("Die Nachricht ist wichtig.", "The message is important."),
        phrase("Ich verstehe den Text.", "I understand the text."),
      ],
      sentences: [
        sentence("Das Museum ist heute geöffnet.", "The museum is open today."),
        sentence("Der Park ist rechts.", "The park is on the right."),
        sentence("Die Haltestelle ist nicht weit.", "The stop is not far."),
        sentence("Der Bus kommt um zehn.", "The bus comes at ten."),
        sentence("Das Schild ist rot.", "The sign is red."),
        sentence("Eingang und Ausgang sind da.", "Entrance and exit are there."),
        sentence("Die Information ist einfach.", "The information is simple."),
        sentence("Ich suche den Zug nach Köln.", "I am looking for the train to Cologne."),
        sentence("Wir finden den Plan.", "We find the map."),
        sentence("Die Nachricht ist dringend.", "The message is urgent."),
        sentence("Hunde sind hier verboten.", "Dogs are forbidden here."),
        sentence("Fotos sind erlaubt.", "Photos are allowed."),
        sentence("Bitte links gehen.", "Please go left."),
        sentence("Der Text ist kurz.", "The text is short."),
        sentence("Hilfe ist am Ausgang.", "Help is at the exit."),
        sentence("Morgen ist das Café geschlossen.", "Tomorrow the café is closed."),
        sentence("Achtung, der Boden ist nass.", "Caution, the floor is wet."),
        sentence("Das ist wichtig für dich.", "That is important for you."),
      ],
      readings: [
        reading(
          "Station board",
          "Anzeigetafel",
          "Zug nach Hamburg 12:40 Gleis 2. Zug nach München 13:10 Gleis 5. Bus 8 nach Zentrum: Haltestelle rechts. Achtung: Gleis 3 geschlossen. Hilfe am Schalter.",
          "Train to Hamburg 12:40 platform 2. Train to Munich 13:10 platform 5. Bus 8 to the center: stop on the right. Caution: platform 3 closed. Help at the counter.",
          [
            q("Which platform for Hamburg?", "2", ["3", "5", "2", "8"]),
            q("What is closed?", "Platform 3", ["The bus", "Platform 3", "The counter", "Munich"]),
            q("Where is the bus stop?", "On the right", ["On the left", "On the right", "Gleis 2", "Outside the city"]),
          ],
        ),
        reading(
          "Museum door",
          "Museumstür",
          "Geöffnet: Dienstag bis Sonntag, 10–18 Uhr. Montag geschlossen. Eingang links, Ausgang rechts. Hunde nicht erlaubt. Der Plan ist kostenlos. Wichtige Information an der Kasse.",
          "Open: Tuesday to Sunday, 10–18. Monday closed. Entrance left, exit right. Dogs not allowed. The map is free. Important information at the ticket desk.",
          [
            q("Which day is the museum closed?", "Monday", ["Sunday", "Monday", "Tuesday", "Friday"]),
            q("Are dogs allowed?", "No", ["Yes", "No", "Only small dogs", "On Monday"]),
            q("Where is the entrance?", "Left", ["Right", "Left", "Gleis 2", "Upstairs"]),
          ],
        ),
        reading(
          "A hallway notice",
          "Aushang im Flur",
          "Heute: Yoga im Park, 17 Uhr. Morgen: Kurs fällt aus. Bitte die Nachricht lesen. Ausgang zum Hof ist frei. Der Aufzug ist besetzt. Danke!",
          "Today: yoga in the park, 5 p.m. Tomorrow: class is cancelled. Please read the message. Exit to the courtyard is free. The lift is occupied. Thank you!",
          [
            q("What happens tomorrow?", "The class is cancelled", ["Yoga", "A party", "The class is cancelled", "A train"]),
            q("When is yoga?", "17:00", ["10:00", "17:00", "Monday", "Never"]),
            q("Is the courtyard exit free?", "Yes", ["No", "Yes", "Besetzt", "Unknown"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a three-line door sign for a shop.",
          "Schreib ein Türschild.",
          "Geöffnet 9–18 Uhr. Montag geschlossen. Eingang links.",
          ["Use geöffnet/geschlossen", "Add a time or a direction"],
        ),
        writing(
          "Copy a station message in your own words.",
          "Schreib eine Bahnhofsnachricht.",
          "Zug nach Berlin, Gleis 4, 15 Uhr. Achtung: bitte warten.",
          ["Include destination, place, time"],
        ),
      ],
    },
  ),
  chapter(
    "first-writing",
    "First Writing: Forms, Lists & Mini Sentences",
    "Erstes Schreiben: Formulare, Listen, Minisätze",
    "Move from reading models to writing: names, lists, and three-word sentences that are actually correct.",
    "writing",
    [
      "German punctuation is light at A1: capital letters on nouns matter more than commas.",
      "A full sentence needs a conjugated verb: Ich wohne in Berlin.",
      "On forms, write clearly; lists can drop articles, sentences cannot.",
    ],
    {
      vocab: [
        vocab("schreiben", "to write"),
        vocab("die Liste", "the list", undefined, "Listen"),
        vocab("das Formular", "the form", undefined, "Formulare"),
        vocab("der Satz", "the sentence", undefined, "Sätze"),
        vocab("die Lücke", "the blank / gap", undefined, "Lücken"),
        vocab("richtig", "correct"),
        vocab("falsch", "wrong"),
        vocab("bitte", "please"),
        vocab("in Druckbuchstaben", "in block letters"),
        vocab("die Unterschrift", "the signature", undefined, "Unterschriften"),
        vocab("das Datum", "the date", undefined, "Daten"),
        vocab("die Notiz", "the note", undefined, "Notizen"),
        vocab("kurz", "short"),
        vocab("klar", "clear"),
        vocab("noch einmal", "once more"),
        vocab("korrigieren", "to correct"),
        vocab("der Fehler", "the mistake", undefined, "Fehler"),
        vocab("die E-Mail", "the email"),
        vocab("die Karte", "the card", undefined, "Karten"),
        vocab("lieben Grüße", "kind regards"),
        vocab("viele Grüße", "best wishes"),
        vocab("an", "to / at"),
        vocab("von", "from"),
        vocab("für", "for"),
        vocab("mit", "with"),
        vocab("ohne", "without"),
        vocab("hier", "here"),
        vocab("Name", "name"),
        vocab("Adresse", "address"),
        vocab("fertig", "finished"),
        vocab("anfangen", "to begin"),
        vocab("üben", "to practice"),
      ],
      phrases: [
        phrase("Bitte in Druckbuchstaben schreiben.", "Please write in block letters."),
        phrase("Datum und Unterschrift nicht vergessen.", "Do not forget date and signature."),
        phrase("Ist der Satz richtig?", "Is the sentence correct?"),
        phrase("Das ist falsch. Noch einmal.", "That is wrong. Once more."),
        phrase("Eine kurze Notiz reicht.", "A short note is enough."),
        phrase("Liebe Grüße, Anna.", "Kind regards, Anna."),
        phrase("An: Kursbüro. Von: Ben.", "To: course office. From: Ben."),
        phrase("Ich schreibe eine Liste.", "I am writing a list."),
        phrase("Die Lücke bitte füllen.", "Please fill the blank."),
        phrase("Ohne Fehler, bitte.", "Without mistakes, please."),
        phrase("Der Text ist fertig.", "The text is finished."),
        phrase("Wir üben das Schreiben.", "We practice writing."),
      ],
      sentences: [
        sentence("Ich schreibe meinen Namen.", "I write my name."),
        sentence("Die Liste ist kurz.", "The list is short."),
        sentence("Bitte das Formular ausfüllen.", "Please fill out the form."),
        sentence("Das Datum ist der 24. August.", "The date is August 24."),
        sentence("Hier ist meine Unterschrift.", "Here is my signature."),
        sentence("Der Satz ist richtig.", "The sentence is correct."),
        sentence("Dieser Fehler ist klein.", "This mistake is small."),
        sentence("Ich schreibe eine E-Mail an Frau Klein.", "I write an email to Ms. Klein."),
        sentence("Viele Grüße aus Berlin.", "Best wishes from Berlin."),
        sentence("Die Notiz ist für Mama.", "The note is for Mom."),
        sentence("Wir fangen ohne Stress an.", "We begin without stress."),
        sentence("Schreib klar und kurz.", "Write clearly and briefly."),
        sentence("Ich korrigiere den Satz.", "I correct the sentence."),
        sentence("Die Karte ist für Ben.", "The card is for Ben."),
        sentence("Mit einem Stift schreiben.", "Write with a pen."),
        sentence("Die Übung ist fertig.", "The exercise is finished."),
        sentence("Bitte noch einmal lesen.", "Please read it once more."),
        sentence("Ich übe jeden Tag.", "I practice every day."),
      ],
      readings: [
        reading(
          "Form instructions",
          "Hinweise zum Formular",
          "Bitte in Druckbuchstaben schreiben. Name, Adresse, Datum. Die Lücken nicht leer lassen. Unterschrift am Ende. Ein kurzer Satz reicht: Ich lerne Deutsch.",
          "Please write in block letters. Name, address, date. Do not leave the blanks empty. Signature at the end. A short sentence is enough: I am learning German.",
          [
            q("How should you write?", "In block letters", ["In pencil only", "In block letters", "In English", "In red"]),
            q("What must not stay empty?", "The blanks", ["The street", "The blanks", "The café", "The train"]),
            q("Where is the signature?", "At the end", ["At the top", "At the end", "On the back only", "Nowhere"]),
          ],
        ),
        reading(
          "A model postcard",
          "Eine Modellpostkarte",
          "Liebe Greta, Berlin ist schön. Ich wohne in einer kleinen Wohnung. Heute schreibe ich viele Sätze. Viele Grüße, Jonas. P.S. Die Karte ist kurz, aber klar.",
          "Dear Greta, Berlin is beautiful. I live in a small apartment. Today I am writing many sentences. Best wishes, Jonas. P.S. The card is short but clear.",
          [
            q("Who is the card to?", "Greta", ["Jonas", "Greta", "Berlin", "Mama"]),
            q("Where does Jonas live?", "In a small apartment", ["In a hotel", "In a small apartment", "In Graz", "At school"]),
            q("How is the card described?", "Short but clear", ["Long and hard", "Short but clear", "Wrong", "Empty"]),
          ],
        ),
        reading(
          "Correction note",
          "Korrektur",
          "Satz 1: richtig. Satz 2: falsch — bitte das Verb. Satz 3: der Fehler ist das Nomen ohne Großbuchstaben. Noch einmal üben. Dann ist der Text fertig.",
          "Sentence 1: correct. Sentence 2: wrong — please the verb. Sentence 3: the mistake is the noun without a capital letter. Practice once more. Then the text is finished.",
          [
            q("What is wrong in sentence 2?", "The verb", ["The date", "The verb", "The stamp", "The color"]),
            q("What is wrong in sentence 3?", "A noun is not capitalized", ["Too long", "A noun is not capitalized", "English", "No name"]),
            q("What should the student do?", "Practice once more", ["Stop", "Practice once more", "Call home", "Buy a book"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a four-line postcard.",
          "Schreib eine Postkarte.",
          "Liebe Anna, Berlin ist gut. Ich lerne Deutsch. Viele Grüße, Ben.",
          ["Greeting, two facts, closing", "Capitalize nouns"],
        ),
        writing(
          "Fill a tiny form in sentences.",
          "Fülle ein Mini-Formular in Sätzen.",
          "Mein Name ist Emma. Meine Adresse ist Parkstraße 2. Das Datum ist der 24. August.",
          ["Full sentences, not only boxes"],
        ),
      ],
    },
  ),
  chapter(
    "home",
    "At Home: Rooms & Objects",
    "Zuhause: Zimmer und Dinge",
    "Read apartment ads and room labels, then describe where things are.",
    "vocab",
    [
      "in + dative for location: in der Küche, im Wohnzimmer (in + dem).",
      "auf dem Tisch = on the table. an der Wand = on the wall.",
      "es gibt + accusative: Es gibt ein Bett.",
    ],
    {
      vocab: [
        vocab("das Haus", "the house", undefined, "Häuser"),
        vocab("die Wohnung", "the apartment", undefined, "Wohnungen"),
        vocab("das Zimmer", "the room", undefined, "Zimmer"),
        vocab("das Wohnzimmer", "the living room", undefined, "Wohnzimmer"),
        vocab("das Schlafzimmer", "the bedroom", undefined, "Schlafzimmer"),
        vocab("die Küche", "the kitchen", undefined, "Küchen"),
        vocab("das Bad", "the bathroom", undefined, "Bäder"),
        vocab("die Toilette", "the toilet", undefined, "Toiletten"),
        vocab("der Flur", "the hallway", undefined, "Flure"),
        vocab("der Balkon", "the balcony", undefined, "Balkone"),
        vocab("der Garten", "the garden", undefined, "Gärten"),
        vocab("das Sofa", "the sofa", undefined, "Sofas"),
        vocab("der Tisch", "the table", undefined, "Tische"),
        vocab("der Stuhl", "the chair", undefined, "Stühle"),
        vocab("das Bett", "the bed", undefined, "Betten"),
        vocab("der Schrank", "the wardrobe", undefined, "Schränke"),
        vocab("der Kühlschrank", "the fridge", undefined, "Kühlschränke"),
        vocab("die Lampe", "the lamp", undefined, "Lampen"),
        vocab("das Fenster", "the window", undefined, "Fenster"),
        vocab("die Wand", "the wall", undefined, "Wände"),
        vocab("der Boden", "the floor", undefined, "Böden"),
        vocab("die Miete", "the rent"),
        vocab("möbliert", "furnished"),
        vocab("unmöbliert", "unfurnished"),
        vocab("ruhig", "quiet"),
        vocab("laut", "loud"),
        vocab("oben", "upstairs / above"),
        vocab("unten", "downstairs / below"),
        vocab("es gibt", "there is / there are"),
        vocab("wohnen", "to live"),
        vocab("aufräumen", "to tidy up"),
        vocab("die Schlüssel", "the keys"),
      ],
      phrases: [
        phrase("Ich wohne in einer Wohnung.", "I live in an apartment."),
        phrase("Es gibt zwei Zimmer.", "There are two rooms."),
        phrase("Die Küche ist klein, aber hell.", "The kitchen is small but bright."),
        phrase("Das Bad ist neben dem Flur.", "The bathroom is next to the hallway."),
        phrase("Auf dem Tisch liegt ein Buch.", "A book is lying on the table."),
        phrase("Die Schlüssel sind in der Küche.", "The keys are in the kitchen."),
        phrase("Die Miete ist 700 Euro.", "The rent is 700 euros."),
        phrase("Die Wohnung ist möbliert.", "The apartment is furnished."),
        phrase("Wir sitzen im Wohnzimmer.", "We are sitting in the living room."),
        phrase("Der Balkon ist oben.", "The balcony is upstairs."),
        phrase("Bitte aufräumen!", "Please tidy up!"),
        phrase("Wo ist das Bad?", "Where is the bathroom?"),
      ],
      sentences: [
        sentence("Das Schlafzimmer ist ruhig.", "The bedroom is quiet."),
        sentence("Im Garten ist ein Tisch.", "There is a table in the garden."),
        sentence("Der Kühlschrank ist in der Küche.", "The fridge is in the kitchen."),
        sentence("Ein Sofa steht an der Wand.", "A sofa stands against the wall."),
        sentence("Die Lampe ist über dem Tisch.", "The lamp is above the table."),
        sentence("Wir wohnen unten.", "We live downstairs."),
        sentence("Das Fenster ist offen.", "The window is open."),
        sentence("Die Toilette ist im Bad.", "The toilet is in the bathroom."),
        sentence("Es gibt keinen Balkon.", "There is no balcony."),
        sentence("Die Wohnung ist nicht laut.", "The apartment is not loud."),
        sentence("Mein Bett ist neu.", "My bed is new."),
        sentence("Die Stühle sind im Flur.", "The chairs are in the hallway."),
        sentence("Ich suche die Schlüssel.", "I am looking for the keys."),
        sentence("Das Haus hat einen Garten.", "The house has a garden."),
        sentence("Die Miete ist nicht teuer.", "The rent is not expensive."),
        sentence("Im Wohnzimmer hören wir Musik.", "In the living room we listen to music."),
        sentence("Bitte das Bad aufräumen.", "Please tidy the bathroom."),
        sentence("Die Tür zum Balkon ist links.", "The door to the balcony is on the left."),
      ],
      readings: [
        reading(
          "Apartment ad",
          "Wohnungsanzeige",
          "2-Zimmer-Wohnung in Leipzig. Küche, Bad, Balkon. Möbliert. Ruhig, nicht laut. Miete: 650 Euro. Es gibt einen Keller. Schlüssel beim Hausmeister.",
          "2-room apartment in Leipzig. Kitchen, bathroom, balcony. Furnished. Quiet, not loud. Rent: 650 euros. There is a cellar. Keys with the caretaker.",
          [
            q("How many rooms?", "Two", ["One", "Two", "Three", "Five"]),
            q("Is it furnished?", "Yes", ["No", "Yes", "Only the kitchen", "Unknown"]),
            q("Where are the keys?", "With the caretaker", ["In the fridge", "With the caretaker", "In Berlin", "Lost"]),
          ],
        ),
        reading(
          "Flatshare note",
          "WG-Zettel",
          "Bitte aufräumen. Der Kühlschrank ist voll. Das Bad ist frei um acht. Die Schlüssel hängen im Flur. Heute essen wir im Wohnzimmer. Danke!",
          "Please tidy up. The fridge is full. The bathroom is free at eight. The keys hang in the hallway. Today we eat in the living room. Thanks!",
          [
            q("When is the bathroom free?", "At eight", ["At noon", "At eight", "Never", "At night only"]),
            q("Where do the keys hang?", "In the hallway", ["In the garden", "In the hallway", "On the bed", "Outside"]),
            q("Where do they eat today?", "In the living room", ["In the park", "In the living room", "In a café", "In the cellar"]),
          ],
        ),
        reading(
          "Room tour",
          "Rundgang",
          "Links das Schlafzimmer, rechts die Küche. Geradeaus das Wohnzimmer mit Sofa und Lampe. Oben gibt es noch ein Bad. Der Garten ist unten und klein, aber schön.",
          "Left the bedroom, right the kitchen. Straight ahead the living room with sofa and lamp. Upstairs there is another bathroom. The garden is downstairs and small but lovely.",
          [
            q("What is on the left?", "The bedroom", ["The kitchen", "The bedroom", "The garden", "The sofa"]),
            q("Where is the extra bathroom?", "Upstairs", ["In the kitchen", "Upstairs", "In the garden", "Outside"]),
            q("How is the garden?", "Small but lovely", ["Huge", "Loud", "Small but lovely", "Missing"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe your home in five short sentences.",
          "Beschreib dein Zuhause.",
          "Ich wohne in einer Wohnung. Es gibt eine Küche. Das Bad ist klein. Ein Sofa steht im Wohnzimmer. Die Wohnung ist ruhig.",
          ["Use es gibt", "Name rooms", "Add one adjective"],
        ),
        writing(
          "Write where three objects are.",
          "Schreib, wo drei Dinge sind.",
          "Das Buch ist auf dem Tisch. Die Schlüssel sind im Flur. Die Lampe ist im Wohnzimmer.",
          ["in der Küche / im Wohnzimmer", "auf dem Tisch"],
        ),
      ],
    },
  ),
  chapter(
    "daily-routine",
    "Daily Routines",
    "Der Tagesablauf",
    "Read someone's day, then write your own routine with times and simple verbs.",
    "mixed",
    [
      "Separable verbs split in the present: Ich stehe um sieben auf.",
      "um + time, am + weekday, morgens / abends for habits.",
      "dann and danach help you sequence a routine.",
    ],
    {
      vocab: [
        vocab("aufstehen", "to get up"),
        vocab("frühstücken", "to have breakfast"),
        vocab("arbeiten", "to work"),
        vocab("lernen", "to learn / study"),
        vocab("essen", "to eat"),
        vocab("trinken", "to drink"),
        vocab("schlafen", "to sleep"),
        vocab("duschen", "to shower"),
        vocab("anziehen", "to get dressed"),
        vocab("gehen", "to go"),
        vocab("kommen", "to come"),
        vocab("fahren", "to go (by vehicle)"),
        vocab("der Morgen", "the morning", undefined, "Morgen"),
        vocab("der Mittag", "noon"),
        vocab("der Abend", "the evening", undefined, "Abende"),
        vocab("die Nacht", "the night", undefined, "Nächte"),
        vocab("immer", "always"),
        vocab("oft", "often"),
        vocab("manchmal", "sometimes"),
        vocab("nie", "never"),
        vocab("dann", "then"),
        vocab("danach", "after that"),
        vocab("zuerst", "first"),
        vocab("später", "later"),
        vocab("die Arbeit", "work / the job"),
        vocab("die Pause", "the break", undefined, "Pausen"),
        vocab("müde", "tired"),
        vocab("wach", "awake"),
        vocab("der Wecker", "the alarm clock", undefined, "Wecker"),
        vocab("zu Fuß", "on foot"),
        vocab("mit dem Bus", "by bus"),
        vocab("der Tagesablauf", "the daily routine", undefined, "Tagesabläufe"),
      ],
      phrases: [
        phrase("Ich stehe um sieben auf.", "I get up at seven."),
        phrase("Zuerst dusche ich.", "First I shower."),
        phrase("Dann frühstücke ich.", "Then I have breakfast."),
        phrase("Ich fahre mit dem Bus zur Arbeit.", "I take the bus to work."),
        phrase("Um eins esse ich zu Mittag.", "At one I have lunch."),
        phrase("Am Abend lerne ich Deutsch.", "In the evening I study German."),
        phrase("Ich gehe um elf schlafen.", "I go to sleep at eleven."),
        phrase("Manchmal mache ich eine Pause.", "Sometimes I take a break."),
        phrase("Ich arbeite nie am Sonntag.", "I never work on Sunday."),
        phrase("Der Wecker klingelt früh.", "The alarm rings early."),
        phrase("Danach gehe ich zu Fuß.", "After that I walk."),
        phrase("So sieht mein Tag aus.", "That is what my day looks like."),
      ],
      sentences: [
        sentence("Ich stehe spät auf.", "I get up late."),
        sentence("Sie frühstückt um acht.", "She has breakfast at eight."),
        sentence("Wir arbeiten von neun bis fünf.", "We work from nine to five."),
        sentence("Er lernt am Abend.", "He studies in the evening."),
        sentence("Ich esse nie Fleisch am Morgen.", "I never eat meat in the morning."),
        sentence("Zuerst trinke ich Kaffee.", "First I drink coffee."),
        sentence("Dann ziehe ich mich an.", "Then I get dressed."),
        sentence("Die Pause ist um zehn.", "The break is at ten."),
        sentence("Ich komme um sechs nach Hause.", "I come home at six."),
        sentence("Manchmal bin ich müde.", "Sometimes I am tired."),
        sentence("Der Bus fährt um 7:15.", "The bus leaves at 7:15."),
        sentence("Ich gehe oft zu Fuß.", "I often walk."),
        sentence("Am Freitag arbeite ich nicht.", "I do not work on Friday."),
        sentence("Danach schlafe ich lange.", "After that I sleep a long time."),
        sentence("Mein Tagesablauf ist einfach.", "My daily routine is simple."),
        sentence("Wir duschen am Morgen.", "We shower in the morning."),
        sentence("Ich bin um Mitternacht noch wach.", "I am still awake at midnight."),
        sentence("So lerne ich jeden Tag.", "That is how I study every day."),
      ],
      readings: [
        reading(
          "Lea's day",
          "Leas Tag",
          "Lea steht um sechs auf. Zuerst duscht sie, dann frühstückt sie. Sie fährt mit dem Bus zur Arbeit. Um eins isst sie. Am Abend lernt sie Deutsch. Um elf geht sie schlafen.",
          "Lea gets up at six. First she showers, then she has breakfast. She takes the bus to work. At one she eats. In the evening she studies German. At eleven she goes to sleep.",
          [
            q("When does Lea get up?", "At six", ["At eight", "At six", "At eleven", "At one"]),
            q("How does she go to work?", "By bus", ["On foot", "By bus", "By train", "By car"]),
            q("When does she study German?", "In the evening", ["In the morning", "At noon", "In the evening", "Never"]),
          ],
        ),
        reading(
          "Shift note",
          "Schichtzettel",
          "Heute: Arbeit von 14 bis 22 Uhr. Pause um 18 Uhr, 20 Minuten. Danach nach Hause zu Fuß. Der Wecker für morgen: 8 Uhr. Nicht spät aufstehen!",
          "Today: work from 14:00 to 22:00. Break at 18:00, 20 minutes. After that home on foot. Alarm for tomorrow: 8:00. Don't get up late!",
          [
            q("When does work end?", "22:00", ["14:00", "18:00", "22:00", "08:00"]),
            q("How long is the break?", "20 minutes", ["Two hours", "20 minutes", "All evening", "None"]),
            q("How does the person go home?", "On foot", ["By bus", "On foot", "By taxi", "Stays"]),
          ],
        ),
        reading(
          "Weekend contrast",
          "Wochenende",
          "Unter der Woche stehe ich früh auf. Am Samstag stehe ich nie vor zehn auf. Zuerst Kaffee, dann ein langer Spaziergang. Danach lerne ich, aber langsam. So bin ich nicht müde.",
          "On weekdays I get up early. On Saturday I never get up before ten. First coffee, then a long walk. After that I study, but slowly. That way I am not tired.",
          [
            q("When does this person get up on Saturday?", "Not before ten", ["At six", "Not before ten", "At midnight", "Never"]),
            q("What comes after coffee?", "A long walk", ["Work", "A long walk", "A bus", "Sleep"]),
            q("How do they study on Saturday?", "Slowly", ["Never", "In a rush", "Slowly", "At work"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write your weekday morning in five sentences.",
          "Schreib deinen Morgen.",
          "Ich stehe um sieben auf. Zuerst dusche ich. Dann frühstücke ich. Danach fahre ich mit dem Bus. Um neun beginne ich zu arbeiten.",
          ["Use zuerst / dann / danach", "Split separable verbs"],
        ),
        writing(
          "Write three habits with always / sometimes / never.",
          "Schreib drei Gewohnheiten.",
          "Ich frühstücke immer. Ich arbeite manchmal am Samstag. Ich lerne nie in der Nacht.",
          ["immer / oft / manchmal / nie before the verb or after the subject"],
        ),
      ],
    },
  ),
];
