import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const a1Chapters: ChapterSource[] = [
  chapter(
    "alphabet-sounds",
    "Alphabet, Sounds & First Words",
    "Alphabet, Laute und erste Wörter",
    "Learn how German looks and sounds, then read tiny texts before you write a word.",
    "reading",
    [
      "German spelling is mostly regular: ä, ö, ü and ß are distinct sounds, not decorations.",
      "Nouns are capitalized in German, even in the middle of a sentence.",
      "Read aloud first: seeing and hearing together makes new words stick.",
    ],
    {
      vocab: [
        vocab("Hallo", "hello"),
        vocab("Tschüss", "bye", "informal"),
        vocab("ja", "yes"),
        vocab("nein", "no"),
        vocab("bitte", "please / you're welcome"),
        vocab("danke", "thank you"),
        vocab("und", "and"),
        vocab("oder", "or"),
        vocab("ich", "I"),
        vocab("du", "you (informal)"),
        vocab("Sie", "you (formal)"),
        vocab("der Name", "the name", undefined, "Namen"),
        vocab("heißen", "to be called"),
        vocab("Deutschland", "Germany"),
        vocab("Deutsch", "German"),
        vocab("das Buch", "the book", undefined, "Bücher"),
        vocab("der Buchstabe", "the letter", undefined, "Buchstaben"),
        vocab("die Sprache", "the language", undefined, "Sprachen"),
        vocab("das Alphabet", "the alphabet"),
        vocab("der Laut", "the sound", undefined, "Laute"),
        vocab("sprechen", "to speak"),
        vocab("lesen", "to read"),
        vocab("schreiben", "to write"),
        vocab("hören", "to hear / listen"),
        vocab("wiederholen", "to repeat"),
        vocab("die Übung", "the exercise", undefined, "Übungen"),
        vocab("das Wort", "the word", undefined, "Wörter"),
        vocab("der Satz", "the sentence", undefined, "Sätze"),
        vocab("die Frage", "the question", undefined, "Fragen"),
        vocab("die Antwort", "the answer", undefined, "Antworten"),
        vocab("gut", "good"),
        vocab("langsam", "slowly"),
      ],
      phrases: [
        phrase("Guten Tag!", "Good day!", "safe greeting from late morning"),
        phrase("Wie heißt du?", "What is your name? (informal)"),
        phrase("Ich heiße Anna.", "My name is Anna."),
        phrase("Wie bitte?", "Pardon?"),
        phrase("Können Sie das wiederholen?", "Can you repeat that? (formal)"),
        phrase("Bitte langsam.", "Please (speak) slowly."),
        phrase("Was bedeutet das?", "What does that mean?"),
        phrase("Ich verstehe nicht.", "I don't understand."),
        phrase("Buchstabieren Sie bitte.", "Please spell it."),
        phrase("Das Alphabet hat 26 Buchstaben.", "The alphabet has 26 letters."),
        phrase("A, B, C …", "A, B, C …"),
        phrase("Das ist ein Wort.", "That is a word."),
      ],
      sentences: [
        sentence("Hallo, ich heiße Ben.", "Hello, my name is Ben."),
        sentence("Deutsch ist eine Sprache.", "German is a language."),
        sentence("Bitte lesen Sie den Satz.", "Please read the sentence."),
        sentence("Ich spreche langsam.", "I speak slowly."),
        sentence("Das Buch ist gut.", "The book is good."),
        sentence("Wie heißt das Wort?", "What is the word called?"),
        sentence("Wiederholen Sie die Frage.", "Repeat the question."),
        sentence("Die Antwort ist ja.", "The answer is yes."),
        sentence("Die Antwort ist nein.", "The answer is no."),
        sentence("Ich höre den Laut.", "I hear the sound."),
        sentence("Bitte schreiben Sie den Namen.", "Please write the name."),
        sentence("Das Alphabet ist wichtig.", "The alphabet is important."),
        sentence("Ich lese das Buch.", "I am reading the book."),
        sentence("Danke, das ist gut.", "Thanks, that is good."),
        sentence("Was bedeutet dieses Wort?", "What does this word mean?"),
        sentence("Ich verstehe die Übung.", "I understand the exercise."),
        sentence("Sprechen Sie Deutsch?", "Do you speak German?"),
        sentence("Ja, ein bisschen.", "Yes, a little."),
      ],
      readings: [
        reading(
          "A first classroom note",
          "Eine erste Notiz",
          "Hallo! Ich heiße Clara. Ich lerne Deutsch. Bitte langsam sprechen. Das Alphabet ist neu, aber die Übung ist gut. Danke!",
          "Hello! My name is Clara. I am learning German. Please speak slowly. The alphabet is new, but the exercise is good. Thank you!",
          [
            q("Who is learning German?", "Clara", ["Ben", "Clara", "Anna", "Hans"], "The note says: Ich heiße Clara."),
            q("What does Clara ask for?", "Slow speech", ["A book", "Slow speech", "A name", "A test"], "Bitte langsam sprechen."),
            q("How does she feel about the exercise?", "It is good", ["It is hard", "It is long", "It is good", "It is loud"], "die Übung ist gut"),
          ],
        ),
        reading(
          "On the classroom wall",
          "An der Wand",
          "Lesen. Schreiben. Hören. Sprechen. Das sind vier Schritte. Erst lesen wir das Wort. Dann wiederholen wir den Laut. Der Satz ist kurz: Deutsch macht Spaß.",
          "Reading. Writing. Listening. Speaking. Those are four steps. First we read the word. Then we repeat the sound. The sentence is short: German is fun.",
          [
            q("How many steps are named?", "Four", ["Two", "Three", "Four", "Five"]),
            q("What comes first?", "Reading the word", ["A test", "Writing a book", "Reading the word", "Going home"]),
            q("What is the short sentence?", "Deutsch macht Spaß.", ["Hallo!", "Danke!", "Deutsch macht Spaß.", "Wie bitte?"]),
          ],
        ),
        reading(
          "A name card",
          "Eine Namenskarte",
          "Name: Jonas Weber. Sprache: Deutsch und Englisch. Bitte: Buchstabieren Sie Weber: W-E-B-E-R. Frage: Wie heißt du? Antwort: Ich heiße Jonas.",
          "Name: Jonas Weber. Language: German and English. Please: Spell Weber: W-E-B-E-R. Question: What is your name? Answer: My name is Jonas.",
          [
            q("What is the family name?", "Weber", ["Jonas", "Weber", "Deutsch", "Clara"]),
            q("Which languages are listed?", "German and English", ["Only German", "Only English", "German and English", "French"]),
            q("How is Weber spelled?", "W-E-B-E-R", ["V-E-B-E-R", "W-E-B-E-R", "W-Ä-B-E-R", "U-E-B-E-R"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a three-line introduction.",
          "Schreib eine kurze Vorstellung.",
          "Hallo, ich heiße Anna. Ich lerne Deutsch. Bitte langsam.",
          ["Start with Hallo", "Use Ich heiße + name", "Add Bitte langsam or Danke"],
        ),
        writing(
          "Copy and complete a name card.",
          "Ergänze eine Namenskarte.",
          "Name: Ben. Sprache: Deutsch. Ich heiße Ben.",
          ["Capitalize nouns", "Keep sentences short", "Use heißen, not sein, for names"],
        ),
      ],
    },
  ),
  chapter(
    "pronouns-sein",
    "Pronouns & sein",
    "Pronomen und sein",
    "Learn who is speaking, then build real sentences with ich bin, du bist and er ist.",
    "grammar",
    [
      "Personal pronouns: ich, du, er, sie, es, wir, ihr, sie/Sie.",
      "sein: ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.",
      "Capital Sie is formal you and takes sind — the same form as they: sie sind.",
    ],
    {
      vocab: [
        vocab("ich", "I"),
        vocab("du", "you (informal)"),
        vocab("er", "he"),
        vocab("sie", "she / they", "lowercase"),
        vocab("es", "it"),
        vocab("wir", "we"),
        vocab("ihr", "you (plural informal)"),
        vocab("Sie", "you (formal)", "always capital"),
        vocab("sein", "to be"),
        vocab("bin", "am"),
        vocab("bist", "are (with du)"),
        vocab("ist", "is"),
        vocab("sind", "are (wir / sie / Sie)"),
        vocab("seid", "are (with ihr)"),
        vocab("wer", "who"),
        vocab("was", "what"),
        vocab("wo", "where"),
        vocab("hier", "here"),
        vocab("da", "there"),
        vocab("nicht", "not"),
        vocab("müde", "tired"),
        vocab("neu", "new"),
        vocab("Herr", "Mr."),
        vocab("Frau", "Ms. / Mrs."),
        vocab("der Lehrer", "the teacher (m)", undefined, "Lehrer"),
        vocab("die Lehrerin", "the teacher (f)", undefined, "Lehrerinnen"),
        vocab("Student", "student (m)"),
        vocab("Studentin", "student (f)"),
        vocab("jetzt", "now"),
        vocab("auch", "also"),
        vocab("richtig", "right / correct"),
        vocab("falsch", "wrong"),
      ],
      phrases: [
        phrase("Ich bin Lea.", "I am Lea."),
        phrase("Du bist hier.", "You are here."),
        phrase("Er ist müde.", "He is tired."),
        phrase("Sie ist Lehrerin.", "She is a teacher."),
        phrase("Es ist neu.", "It is new."),
        phrase("Wir sind hier.", "We are here."),
        phrase("Ihr seid müde.", "You (plural) are tired."),
        phrase("Sie sind Herr Braun.", "You are Mr. Braun. (formal)"),
        phrase("Wer ist das?", "Who is that?"),
        phrase("Das ist Mia.", "That is Mia."),
        phrase("Wo bist du?", "Where are you?"),
        phrase("Ich bin nicht müde.", "I am not tired."),
      ],
      sentences: [
        sentence("Ich bin Student.", "I am a student."),
        sentence("Du bist neu.", "You are new."),
        sentence("Er ist Lehrer.", "He is a teacher."),
        sentence("Sie ist Studentin.", "She is a student."),
        sentence("Es ist gut.", "It is good."),
        sentence("Wir sind Studenten.", "We are students."),
        sentence("Ihr seid hier.", "You (plural) are here."),
        sentence("Sie sind Frau Klein.", "You are Ms. Klein. (formal)"),
        sentence("Wer ist der Lehrer?", "Who is the teacher?"),
        sentence("Das ist Ben.", "That is Ben."),
        sentence("Wo ist Mia?", "Where is Mia?"),
        sentence("Ich bin nicht da.", "I am not there."),
        sentence("Er heißt Ben. Er ist Student.", "He is called Ben. He is a student."),
        sentence("Sie ist nicht müde.", "She is not tired."),
        sentence("Das ist richtig.", "That is correct."),
        sentence("Das ist falsch.", "That is wrong."),
        sentence("Sind Sie Herr Braun?", "Are you Mr. Braun? (formal)"),
        sentence("Bist du Lea?", "Are you Lea?"),
      ],
      readings: [
        reading(
          "Photo captions",
          "Bildunterschriften",
          "Das bin ich: Lea. Ich bin Studentin. Das ist Ben. Er ist auch Student. Das ist Frau Klein. Sie ist Lehrerin. Wir sind hier. Das ist richtig.",
          "This is me: Lea. I am a student. That is Ben. He is also a student. That is Ms. Klein. She is a teacher. We are here. That is correct.",
          [
            q("Who is the teacher?", "Ms. Klein", ["Lea", "Ben", "Ms. Klein", "Herr Braun"]),
            q("What is Lea?", "A student", ["A teacher", "A student", "New", "Tired"]),
            q("Where are they?", "Here", ["There", "Here", "Away", "At home"]),
          ],
        ),
        reading(
          "Who is not here?",
          "Wer ist nicht da?",
          "Ben ist nicht hier. Er ist müde. Mia ist da. Sie ist Studentin. Herr Braun ist auch nicht da. Wo ist er? Er ist nicht hier. Das ist falsch? Nein, das ist richtig.",
          "Ben is not here. He is tired. Mia is there. She is a student. Mr. Braun is also not there. Where is he? He is not here. Is that wrong? No, that is correct.",
          [
            q("Why is Ben not here?", "He is tired", ["He is new", "He is tired", "He is the teacher", "He is Frau Klein"]),
            q("Who is present?", "Mia", ["Ben", "Herr Braun", "Mia", "Lea"]),
            q("Where is Mr. Braun?", "Not here", ["Here", "With Mia", "Not here", "He is the student"]),
          ],
        ),
        reading(
          "Name badges",
          "Namensschilder",
          "Ich bin Omar. Du bist Lea. Wir sind neu. Sie sind Herr Weber — Sie sind Lehrer. Das Buch? Es ist hier. Wer ist das? Das ist Mia. Sie ist nicht müde. Jetzt sind wir da.",
          "I am Omar. You are Lea. We are new. You are Mr. Weber — you are a teacher. The book? It is here. Who is that? That is Mia. She is not tired. Now we are there.",
          [
            q("Who is new?", "Omar and Lea", ["Only Mia", "Omar and Lea", "Herr Weber", "The child"]),
            q("What is Mr. Weber?", "A teacher", ["A student", "A child", "A teacher", "Müde"]),
            q("Is Mia tired?", "No", ["Yes", "No", "Unknown", "She is Herr Weber"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write four sein sentences: ich, du, er or sie, and wir.",
          "Schreib vier Sätze mit sein.",
          "Ich bin Student. Du bist hier. Sie ist Lehrerin. Wir sind neu.",
          ["Match the verb to the pronoun", "ich bin, du bist, er/sie ist, wir sind"],
        ),
        writing(
          "Say who you are, then name two other people.",
          "Sag wer du bist und nenne zwei andere Personen.",
          "Ich bin Lea. Das ist Ben. Er ist Student. Das ist Frau Klein. Sie ist Lehrerin.",
          ["Use Ich bin for yourself", "Use Das ist / Er ist / Sie ist for others"],
        ),
      ],
    },
  ),
  chapter(
    "numbers-time",
    "Numbers, Time & Calendar",
    "Zahlen, Zeit und Kalender",
    "Read clocks, tickets, and dates, then write times you will actually use.",
    "mixed",
    [
      "German counts 21 as einundzwanzig — ones before tens.",
      "Uhr marks clock time: Es ist drei Uhr.",
      "Dates often appear as Tag.Monat.Jahr — 24.08.2026.",
    ],
    {
      vocab: [
        vocab("null", "zero"),
        vocab("eins", "one"),
        vocab("zwei", "two"),
        vocab("drei", "three"),
        vocab("vier", "four"),
        vocab("fünf", "five"),
        vocab("sechs", "six"),
        vocab("sieben", "seven"),
        vocab("acht", "eight"),
        vocab("neun", "nine"),
        vocab("zehn", "ten"),
        vocab("elf", "eleven"),
        vocab("zwölf", "twelve"),
        vocab("zwanzig", "twenty"),
        vocab("hundert", "hundred"),
        vocab("die Zahl", "the number", undefined, "Zahlen"),
        vocab("die Uhr", "the clock / o'clock", undefined, "Uhren"),
        vocab("die Minute", "the minute", undefined, "Minuten"),
        vocab("die Stunde", "the hour", undefined, "Stunden"),
        vocab("der Tag", "the day", undefined, "Tage"),
        vocab("die Woche", "the week", undefined, "Wochen"),
        vocab("der Monat", "the month", undefined, "Monate"),
        vocab("das Jahr", "the year", undefined, "Jahre"),
        vocab("heute", "today"),
        vocab("gestern", "yesterday"),
        vocab("morgen", "tomorrow"),
        vocab("Montag", "Monday"),
        vocab("Freitag", "Friday"),
        vocab("der Kalender", "the calendar", undefined, "Kalender"),
        vocab("der Termin", "the appointment", undefined, "Termine"),
        vocab("früh", "early"),
        vocab("spät", "late"),
      ],
      phrases: [
        phrase("Wie spät ist es?", "What time is it?"),
        phrase("Es ist drei Uhr.", "It is three o'clock."),
        phrase("Es ist halb vier.", "It is half past three.", "halb vier = 3:30"),
        phrase("Am Montag um zehn.", "On Monday at ten."),
        phrase("Ich habe um acht einen Termin.", "I have an appointment at eight."),
        phrase("Heute ist Freitag.", "Today is Friday."),
        phrase("Der Kurs dauert zwei Stunden.", "The course lasts two hours."),
        phrase("Fünf Minuten bitte.", "Five minutes, please."),
        phrase("Von eins bis zwölf.", "From one to twelve."),
        phrase("Das Jahr hat zwölf Monate.", "The year has twelve months."),
        phrase("Die Woche hat sieben Tage.", "The week has seven days."),
        phrase("Es ist schon spät.", "It is already late."),
      ],
      sentences: [
        sentence("Ich habe zwei Bücher.", "I have two books."),
        sentence("Der Kurs beginnt um neun Uhr.", "The course starts at nine o'clock."),
        sentence("Wir treffen uns um halb acht.", "We meet at half past seven."),
        sentence("Heute ist der erste Tag.", "Today is the first day."),
        sentence("Gestern war Montag.", "Yesterday was Monday."),
        sentence("Morgen ist Freitag.", "Tomorrow is Friday."),
        sentence("Zehn Minuten sind kurz.", "Ten minutes are short."),
        sentence("Das Jahr 2026 ist neu.", "The year 2026 is new."),
        sentence("Ich komme früh.", "I arrive early."),
        sentence("Der Termin ist um zwölf.", "The appointment is at twelve."),
        sentence("Vier plus zwei ist sechs.", "Four plus two is six."),
        sentence("Zwanzig ist mehr als zehn.", "Twenty is more than ten."),
        sentence("Die Uhr ist kaputt.", "The clock is broken."),
        sentence("Eine Stunde hat sechzig Minuten.", "An hour has sixty minutes."),
        sentence("Am Wochenende habe ich Zeit.", "I have time on the weekend."),
        sentence("Drei Tage in Berlin.", "Three days in Berlin."),
        sentence("Es ist fünf Uhr.", "It is five o'clock."),
        sentence("Bitte um acht kommen.", "Please come at eight."),
      ],
      readings: [
        reading(
          "Course timetable",
          "Stundenplan",
          "Deutsch A1. Montag: 9 Uhr. Mittwoch: 18 Uhr. Freitag: 10 Uhr. Der Kurs dauert zwei Stunden. Bitte nicht spät kommen.",
          "German A1. Monday: 9 o'clock. Wednesday: 6 p.m. Friday: 10 o'clock. The course lasts two hours. Please do not arrive late.",
          [
            q("When is the Monday class?", "9 o'clock", ["8 o'clock", "9 o'clock", "12 o'clock", "18 o'clock"]),
            q("How long is the course session?", "Two hours", ["Ten minutes", "One hour", "Two hours", "All day"]),
            q("What should you not do?", "Arrive late", ["Read", "Arrive late", "Write", "Count"]),
          ],
        ),
        reading(
          "Ticket stub",
          "Fahrkarte",
          "Berlin Hbf. Datum: 24.08.2026. Abfahrt: 14:05. Gleis 8. Wagen 3, Platz 12. Bitte zehn Minuten früh da sein.",
          "Berlin central station. Date: 24 Aug 2026. Departure: 14:05. Platform 8. Coach 3, seat 12. Please be there ten minutes early.",
          [
            q("What time does the train leave?", "14:05", ["12:00", "14:05", "08:00", "18:30"]),
            q("Which platform?", "8", ["3", "12", "8", "24"]),
            q("How early should you arrive?", "Ten minutes", ["One hour", "Ten minutes", "Two days", "Never"]),
          ],
        ),
        reading(
          "Calendar note",
          "Kalendernotiz",
          "Termin: Arzt. Tag: Dienstag. Zeit: halb vier. Adresse: Sonnenweg 5. Rückruf um zwei Uhr. Nicht vergessen!",
          "Appointment: doctor. Day: Tuesday. Time: 3:30. Address: Sonnenweg 5. Call back at two o'clock. Don't forget!",
          [
            q("What is halb vier?", "3:30", ["4:30", "3:30", "4:00", "2:00"]),
            q("Who is the appointment with?", "A doctor", ["A teacher", "A doctor", "A chef", "A driver"]),
            q("When is the callback?", "At two", ["At night", "At two", "On Friday", "Never"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write your weekly class times.",
          "Schreib deine Kurszeiten.",
          "Montag um zehn Uhr. Freitag um fünf Uhr.",
          ["Use um + Uhr", "Capitalize weekdays", "Keep it to two lines"],
        ),
        writing(
          "Write a reminder for a meeting.",
          "Schreib eine Terminerinnerung.",
          "Termin morgen um acht. Bitte nicht spät.",
          ["Include day or morgen", "Include a clock time"],
        ),
      ],
    },
  ),
  chapter(
    "personal-info",
    "Personal Details",
    "Persönliche Angaben",
    "Read forms and ID lines, then fill in who you are, where you live, and what you speak.",
    "writing",
    [
      "Ich komme aus + country. Ich wohne in + city.",
      "Languages: Ich spreche Deutsch, Englisch und ein bisschen Spanisch.",
      "On forms, Nachname is family name and Vorname is given name.",
    ],
    {
      vocab: [
        vocab("der Vorname", "the first name", undefined, "Vornamen"),
        vocab("der Nachname", "the last name", undefined, "Nachnamen"),
        vocab("das Alter", "the age"),
        vocab("alt", "old / years old"),
        vocab("das Land", "the country", undefined, "Länder"),
        vocab("die Stadt", "the city", undefined, "Städte"),
        vocab("die Adresse", "the address", undefined, "Adressen"),
        vocab("die Straße", "the street", undefined, "Straßen"),
        vocab("die Nummer", "the number", undefined, "Nummern"),
        vocab("die Telefonnummer", "the phone number", undefined, "Telefonnummern"),
        vocab("die E-Mail", "the email", undefined, "E-Mails"),
        vocab("wohnen", "to live"),
        vocab("kommen", "to come"),
        vocab("aus", "from"),
        vocab("in", "in"),
        vocab("ledig", "single"),
        vocab("verheiratet", "married"),
        vocab("der Beruf", "the job", undefined, "Berufe"),
        vocab("Student", "student (m)"),
        vocab("Studentin", "student (f)"),
        vocab("Deutschland", "Germany"),
        vocab("Österreich", "Austria"),
        vocab("die Schweiz", "Switzerland"),
        vocab("England", "England"),
        vocab("die Nationalität", "the nationality", undefined, "Nationalitäten"),
        vocab("die Muttersprache", "the native language", undefined, "Muttersprachen"),
        vocab("ein bisschen", "a little"),
        vocab("noch nicht", "not yet"),
        vocab("das Formular", "the form", undefined, "Formulare"),
        vocab("unterschreiben", "to sign"),
        vocab("das Geburtsdatum", "the date of birth"),
        vocab("geboren", "born"),
      ],
      phrases: [
        phrase("Wie heißt du?", "What is your name?"),
        phrase("Ich heiße Emma Rossi.", "My name is Emma Rossi."),
        phrase("Woher kommst du?", "Where are you from?"),
        phrase("Ich komme aus Italien.", "I come from Italy."),
        phrase("Wo wohnst du?", "Where do you live?"),
        phrase("Ich wohne in München.", "I live in Munich."),
        phrase("Wie alt bist du?", "How old are you?"),
        phrase("Ich bin 24 Jahre alt.", "I am 24 years old."),
        phrase("Was bist du von Beruf?", "What is your job?"),
        phrase("Ich bin Studentin.", "I am a student."),
        phrase("Meine Nummer ist …", "My number is …"),
        phrase("Bitte das Formular unterschreiben.", "Please sign the form."),
      ],
      sentences: [
        sentence("Mein Vorname ist Felix.", "My first name is Felix."),
        sentence("Mein Nachname ist Weber.", "My last name is Weber."),
        sentence("Ich komme aus Österreich.", "I come from Austria."),
        sentence("Ich wohne in Hamburg.", "I live in Hamburg."),
        sentence("Ich bin 19 Jahre alt.", "I am 19 years old."),
        sentence("Ich spreche Englisch und Deutsch.", "I speak English and German."),
        sentence("Meine Adresse ist Sonnenweg 5.", "My address is Sonnenweg 5."),
        sentence("Meine E-Mail ist felix@mail.de.", "My email is felix@mail.de."),
        sentence("Ich bin noch nicht verheiratet.", "I am not married yet."),
        sentence("Das Geburtsdatum ist der 3. Mai.", "The date of birth is May 3."),
        sentence("Bitte die Telefonnummer schreiben.", "Please write the phone number."),
        sentence("Sie ist Studentin aus der Schweiz.", "She is a student from Switzerland."),
        sentence("Er ist Lehrer in Berlin.", "He is a teacher in Berlin."),
        sentence("Wir wohnen in einer kleinen Stadt.", "We live in a small city."),
        sentence("Meine Muttersprache ist Englisch.", "My native language is English."),
        sentence("Ich lerne Deutsch in einem Kurs.", "I am learning German in a course."),
        sentence("Das Formular ist kurz.", "The form is short."),
        sentence("Hier bitte unterschreiben.", "Please sign here."),
      ],
      readings: [
        reading(
          "Registration form",
          "Anmeldeformular",
          "Vorname: Maya. Nachname: Singh. Alter: 28. Land: Indien. Stadt: Köln. Beruf: Designerin. Sprachen: Hindi, Englisch, ein bisschen Deutsch. Unterschrift: ______",
          "First name: Maya. Last name: Singh. Age: 28. Country: India. City: Cologne. Job: designer. Languages: Hindi, English, a little German. Signature: ______",
          [
            q("Where does Maya live?", "Cologne", ["Berlin", "Cologne", "Vienna", "Rome"]),
            q("How many languages are listed?", "Three", ["One", "Two", "Three", "Five"]),
            q("What is missing?", "The signature", ["The city", "The name", "The signature", "The age"]),
          ],
        ),
        reading(
          "ID card lines",
          "Ausweiszeilen",
          "Name: Luca Moretti. Geboren: 12.04.1999. Nationalität: italienisch. Wohnort: Leipzig. Adresse: Parkstraße 10. Gültig bis 2029.",
          "Name: Luca Moretti. Born: 12 April 1999. Nationality: Italian. Place of residence: Leipzig. Address: Parkstraße 10. Valid until 2029.",
          [
            q("Where does Luca live?", "Leipzig", ["Rome", "Leipzig", "Park", "Italy"]),
            q("What is the street?", "Parkstraße", ["Köln", "Parkstraße", "Berliner Platz", "Hauptbahnhof"]),
            q("Until when is the ID valid?", "2029", ["1999", "2012", "2029", "10"]),
          ],
        ),
        reading(
          "A course intro",
          "Eine Kursvorstellung",
          "Hallo, ich heiße Omar. Ich komme aus Ägypten und wohne in Mainz. Ich bin 31 Jahre alt und Programmierer. Ich spreche Arabisch und Englisch. Deutsch lerne ich erst seit drei Wochen.",
          "Hello, my name is Omar. I come from Egypt and live in Mainz. I am 31 years old and a programmer. I speak Arabic and English. I have only been learning German for three weeks.",
          [
            q("What is Omar's job?", "Programmer", ["Teacher", "Programmer", "Chef", "Student"]),
            q("How long has he learned German?", "Three weeks", ["Three years", "Three days", "Three weeks", "Never"]),
            q("Which city is home now?", "Mainz", ["Cairo", "Mainz", "Hamburg", "Vienna"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Fill a mini form about yourself.",
          "Fülle ein Mini-Formular aus.",
          "Vorname: Anna. Nachname: Berg. Ich wohne in Berlin. Ich komme aus Schweden.",
          ["Vorname then Nachname", "Use kommen aus and wohnen in"],
        ),
        writing(
          "Write four sentences to introduce yourself.",
          "Stell dich in vier Sätzen vor.",
          "Ich heiße Ben. Ich bin 22 Jahre alt. Ich komme aus England. Ich spreche ein bisschen Deutsch.",
          ["Name, age, origin, languages"],
        ),
      ],
    },
  ),
  chapter(
    "family",
    "Family & People",
    "Familie und Personen",
    "Read family trees and messages, then describe who is who.",
    "vocab",
    [
      "Possessives: mein, meine — mein Vater, meine Mutter.",
      "Plural people often take die: die Eltern, die Kinder, die Freunde.",
      "Er / sie / es must match the grammatical gender of the noun, not always the person.",
    ],
    {
      vocab: [
        vocab("die Familie", "the family", undefined, "Familien"),
        vocab("der Vater", "the father", undefined, "Väter"),
        vocab("die Mutter", "the mother", undefined, "Mütter"),
        vocab("die Eltern", "the parents"),
        vocab("der Sohn", "the son", undefined, "Söhne"),
        vocab("die Tochter", "the daughter", undefined, "Töchter"),
        vocab("der Bruder", "the brother", undefined, "Brüder"),
        vocab("die Schwester", "the sister", undefined, "Schwestern"),
        vocab("das Kind", "the child", undefined, "Kinder"),
        vocab("der Mann", "the man / husband", undefined, "Männer"),
        vocab("die Frau", "the woman / wife", undefined, "Frauen"),
        vocab("der Freund", "the friend / boyfriend", undefined, "Freunde"),
        vocab("die Freundin", "the friend / girlfriend", undefined, "Freundinnen"),
        vocab("der Großvater", "the grandfather", undefined, "Großväter"),
        vocab("die Großmutter", "the grandmother", undefined, "Großmütter"),
        vocab("der Onkel", "the uncle", undefined, "Onkel"),
        vocab("die Tante", "the aunt", undefined, "Tanten"),
        vocab("der Cousin", "the cousin (m)", undefined, "Cousins"),
        vocab("die Cousine", "the cousin (f)", undefined, "Cousinen"),
        vocab("jung", "young"),
        vocab("nett", "nice"),
        vocab("groß", "tall / big"),
        vocab("klein", "small / short"),
        vocab("haben", "to have"),
        vocab("lieben", "to love"),
        vocab("zusammen", "together"),
        vocab("allein", "alone"),
        vocab("das Foto", "the photo", undefined, "Fotos"),
        vocab("die Person", "the person", undefined, "Personen"),
        vocab("wer", "who"),
        vocab("mein", "my (m/n)"),
        vocab("meine", "my (f/pl)"),
      ],
      phrases: [
        phrase("Das ist meine Mutter.", "This is my mother."),
        phrase("Ich habe zwei Brüder.", "I have two brothers."),
        phrase("Hast du Geschwister?", "Do you have siblings?"),
        phrase("Wir wohnen zusammen.", "We live together."),
        phrase("Meine Familie ist klein.", "My family is small."),
        phrase("Er ist mein Vater.", "He is my father."),
        phrase("Sie ist sehr nett.", "She is very nice."),
        phrase("Die Kinder sind jung.", "The children are young."),
        phrase("Mein Onkel lebt in Wien.", "My uncle lives in Vienna."),
        phrase("Wir lieben unsere Großeltern.", "We love our grandparents."),
        phrase("Wer ist das auf dem Foto?", "Who is that in the photo?"),
        phrase("Das ist meine Freundin Lea.", "That is my friend Lea."),
      ],
      sentences: [
        sentence("Ich habe eine Schwester.", "I have a sister."),
        sentence("Mein Bruder ist groß.", "My brother is tall."),
        sentence("Meine Mutter heißt Greta.", "My mother is called Greta."),
        sentence("Die Eltern sind freundlich.", "The parents are friendly."),
        sentence("Das Kind ist klein.", "The child is small."),
        sentence("Wir sind eine Familie.", "We are a family."),
        sentence("Mein Großvater ist alt.", "My grandfather is old."),
        sentence("Die Tante kommt heute.", "The aunt is coming today."),
        sentence("Ich wohne nicht allein.", "I do not live alone."),
        sentence("Meine Freundin ist Studentin.", "My friend is a student."),
        sentence("Hast du Kinder?", "Do you have children?"),
        sentence("Nein, noch nicht.", "No, not yet."),
        sentence("Der Mann auf dem Foto ist mein Vater.", "The man in the photo is my father."),
        sentence("Die Frau ist meine Schwester.", "The woman is my sister."),
        sentence("Unsere Familie isst zusammen.", "Our family eats together."),
        sentence("Der Cousin spricht Deutsch.", "The cousin speaks German."),
        sentence("Ich liebe meine Eltern.", "I love my parents."),
        sentence("Wer ist dein Freund?", "Who is your friend?"),
      ],
      readings: [
        reading(
          "A family tree note",
          "Stammbaum-Notiz",
          "Das ist die Familie Berger. Der Vater heißt Paul, die Mutter heißt Ines. Sie haben einen Sohn, Jonas, und eine Tochter, Mia. Die Großeltern wohnen in Graz. Alle sind nett.",
          "This is the Berger family. The father is called Paul, the mother is called Ines. They have a son, Jonas, and a daughter, Mia. The grandparents live in Graz. Everyone is nice.",
          [
            q("How many children are there?", "Two", ["One", "Two", "Three", "Four"]),
            q("Where do the grandparents live?", "Graz", ["Berlin", "Graz", "Hamburg", "Rome"]),
            q("What is the daughter's name?", "Mia", ["Ines", "Mia", "Greta", "Lea"]),
          ],
        ),
        reading(
          "WhatsApp from home",
          "Nachricht von zu Hause",
          "Hallo! Tante Rita kommt am Sonntag. Onkel Karl auch. Bitte das Foto von den Kindern schicken. Oma ist müde, aber gut. Wir essen um sechs zusammen.",
          "Hello! Aunt Rita is coming on Sunday. Uncle Karl too. Please send the photo of the children. Grandma is tired but well. We eat together at six.",
          [
            q("Who is coming on Sunday?", "Aunt Rita", ["Only Jonas", "Aunt Rita", "A teacher", "Nobody"]),
            q("How is grandma?", "Tired but well", ["Angry", "Lost", "Tired but well", "Away"]),
            q("When is the meal?", "At six", ["At noon", "At six", "At night only", "On Monday"]),
          ],
        ),
        reading(
          "Photo caption",
          "Bildunterschrift",
          "Links: mein Bruder. Rechts: meine Schwester. In der Mitte: die Eltern. Das kleine Kind ist mein Cousin. Wir sind in München, nicht allein, sondern zusammen.",
          "Left: my brother. Right: my sister. In the middle: the parents. The small child is my cousin. We are in Munich, not alone, but together.",
          [
            q("Who is in the middle?", "The parents", ["The cousin", "The parents", "The sister", "A friend"]),
            q("Where was the photo taken?", "Munich", ["Graz", "Berlin", "Munich", "Vienna"]),
            q("Who is the small child?", "The cousin", ["The father", "The cousin", "The teacher", "The uncle"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe three people in your family.",
          "Beschreib drei Personen in deiner Familie.",
          "Das ist meine Mutter. Sie ist nett. Mein Bruder ist jung.",
          ["Use mein/meine", "Name the relation", "Add one adjective"],
        ),
        writing(
          "Caption a family photo in four short sentences.",
          "Schreib eine Bildunterschrift.",
          "Das ist meine Familie. Links ist mein Vater. Wir sind zusammen in Berlin.",
          ["Point with links/rechts if you can", "Keep nouns capitalized"],
        ),
      ],
    },
  ),
  chapter(
    "articles-nouns",
    "Articles, Gender & Everyday Nouns",
    "Artikel, Genus und Alltagsnomen",
    "Train der, die, das until they feel visible on the page, then write noun lists that stay correct.",
    "grammar",
    [
      "Every German noun has a gender: der (m), die (f), das (n).",
      "Plural nouns take die in the nominative: die Bücher.",
      "Learn nouns with their article — never as a bare word.",
    ],
    {
      vocab: [
        vocab("der Tisch", "the table", undefined, "Tische"),
        vocab("der Stuhl", "the chair", undefined, "Stühle"),
        vocab("der Schrank", "the cupboard", undefined, "Schränke"),
        vocab("der Apfel", "the apple", undefined, "Äpfel"),
        vocab("der Bahnhof", "the station", undefined, "Bahnhöfe"),
        vocab("die Lampe", "the lamp", undefined, "Lampen"),
        vocab("die Tasche", "the bag", undefined, "Taschen"),
        vocab("die Tür", "the door", undefined, "Türen"),
        vocab("die Zeitung", "the newspaper", undefined, "Zeitungen"),
        vocab("die Stadt", "the city", undefined, "Städte"),
        vocab("das Fenster", "the window", undefined, "Fenster"),
        vocab("das Bett", "the bed", undefined, "Betten"),
        vocab("das Handy", "the mobile phone", undefined, "Handys"),
        vocab("das Wasser", "the water"),
        vocab("das Kind", "the child", undefined, "Kinder"),
        vocab("ein", "a (m/n)"),
        vocab("eine", "a (f)"),
        vocab("kein", "no / not a (m/n)"),
        vocab("keine", "no / not a (f/pl)"),
        vocab("der Artikel", "the article", undefined, "Artikel"),
        vocab("das Ding", "the thing", undefined, "Dinge"),
        vocab("die Sache", "the thing / matter", undefined, "Sachen"),
        vocab("hier", "here"),
        vocab("da", "there"),
        vocab("neu", "new"),
        vocab("alt", "old"),
        vocab("teuer", "expensive"),
        vocab("billig", "cheap"),
        vocab("das Beispiel", "the example", undefined, "Beispiele"),
        vocab("der Plural", "the plural"),
        vocab("singular", "singular"),
        vocab("zeigen", "to show"),
      ],
      phrases: [
        phrase("Das ist der Tisch.", "That is the table."),
        phrase("Das ist die Lampe.", "That is the lamp."),
        phrase("Das ist das Fenster.", "That is the window."),
        phrase("Ich habe eine Tasche.", "I have a bag."),
        phrase("Ich habe kein Handy.", "I don't have a mobile phone."),
        phrase("Die Bücher sind neu.", "The books are new."),
        phrase("Ein Stuhl ist da.", "A chair is there."),
        phrase("Keine Zeitung heute.", "No newspaper today."),
        phrase("Was ist das?", "What is that?"),
        phrase("Das ist ein Beispiel.", "That is an example."),
        phrase("Der Apfel ist billig.", "The apple is cheap."),
        phrase("Die Tür ist alt.", "The door is old."),
      ],
      sentences: [
        sentence("Der Tisch ist groß.", "The table is big."),
        sentence("Die Lampe ist klein.", "The lamp is small."),
        sentence("Das Bett ist neu.", "The bed is new."),
        sentence("Ich sehe ein Fenster.", "I see a window."),
        sentence("Sie hat eine Tasche.", "She has a bag."),
        sentence("Wir haben keine Stühle.", "We have no chairs."),
        sentence("Der Bahnhof ist hier.", "The station is here."),
        sentence("Das Wasser ist gut.", "The water is good."),
        sentence("Die Zeitung liegt da.", "The newspaper is lying there."),
        sentence("Ein Kind spielt.", "A child is playing."),
        sentence("Kein Schrank ist im Zimmer.", "There is no cupboard in the room."),
        sentence("Die Türen sind alt.", "The doors are old."),
        sentence("Das Handy ist teuer.", "The mobile phone is expensive."),
        sentence("Bitte den Artikel lernen.", "Please learn the article."),
        sentence("Zeigen Sie das Beispiel.", "Show the example."),
        sentence("Das Ding ist blau.", "The thing is blue."),
        sentence("Die Sache ist einfach.", "The matter is simple."),
        sentence("Äpfel sind billig heute.", "Apples are cheap today."),
      ],
      readings: [
        reading(
          "Classroom labels",
          "Schilder im Kursraum",
          "der Tisch · die Tür · das Fenster. Bitte die Artikel mitlernen. Ein Stuhl ist frei. Keine Tasche auf den Tisch. Das ist ein einfaches Beispiel.",
          "the table · the door · the window. Please learn the articles with the nouns. A chair is free. No bag on the table. That is a simple example.",
          [
            q("Which article goes with Fenster?", "das", ["der", "die", "das", "ein"]),
            q("What should you not put on the table?", "A bag", ["A book", "A bag", "A lamp", "Water"]),
            q("Is there a free chair?", "Yes", ["No", "Yes", "Unknown", "Never"]),
          ],
        ),
        reading(
          "Lost and found list",
          "Fundsachen",
          "Heute gefunden: eine Tasche, ein Handy, eine Zeitung, ein Apfel. Der Schrank ist voll. Bitte beim Bahnhof fragen. Keine alten Dinge nach 18 Uhr.",
          "Found today: a bag, a mobile phone, a newspaper, an apple. The cupboard is full. Please ask at the station. No old things after 6 p.m.",
          [
            q("Where should you ask?", "At the station", ["At home", "At the station", "Online only", "In class"]),
            q("What is full?", "The cupboard", ["The bag", "The cupboard", "The apple", "The city"]),
            q("Which of these is feminine?", "Tasche", ["Handy", "Apfel", "Tasche", "Schrank"]),
          ],
        ),
        reading(
          "A shop window",
          "Ein Schaufenster",
          "Lampen: 20 Euro. Stühle: 40 Euro. Tische: teuer. Wasser: billig. Ein Bett ist nicht da. Die Stadt hat viele Dinge. Was kaufst du?",
          "Lamps: 20 euros. Chairs: 40 euros. Tables: expensive. Water: cheap. A bed is not there. The city has many things. What are you buying?",
          [
            q("What is cheap?", "Water", ["Tables", "Chairs", "Water", "Beds"]),
            q("Is there a bed?", "No", ["Yes", "No", "Two", "Maybe"]),
            q("How much are the lamps?", "20 euros", ["40 euros", "20 euros", "Free", "Unknown"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a six-noun list with articles.",
          "Schreib eine Liste mit Artikeln.",
          "der Tisch, die Tür, das Fenster, der Stuhl, die Lampe, das Bett",
          ["Never drop the article", "Mix der/die/das"],
        ),
        writing(
          "Write three Das ist … sentences.",
          "Schreib drei Das-ist-Sätze.",
          "Das ist der Tisch. Das ist die Tasche. Das ist das Handy.",
          ["Das ist stays the same", "Change only the noun phrase"],
        ),
      ],
    },
  ),
];
