import { packChapter } from "@/content/levels/pack";
import type { ChapterSource } from "@/content/types";

export const a1ChaptersPart3: ChapterSource[] = [
  packChapter({
    slug: "school-classroom",
    title: "School & Classroom",
    titleDe: "Schule und Klassenzimmer",
    blurb: "Name subjects, bag items and school places, then read a short school day.",
    skill: "vocab",
    grammar: [
      "School subjects are nouns: Ich habe Mathe und Englisch.",
      "fehlen means to be away: Ich fehle heute.",
      "sich melden: Ich melde mich. The verb splits: Lea meldet sich.",
    ],
    vocab: [
      ["die Schultasche", "the school bag", "Schultaschen"],
      ["der Schulranzen", "the satchel", "Schulranzen"],
      ["das Mäppchen", "the pencil case", "Mäppchen"],
      ["der Bleistift", "the pencil", "Bleistifte"],
      ["der Kugelschreiber", "the ballpoint pen", "Kugelschreiber"],
      ["der Füller", "the fountain pen", "Füller"],
      ["das Lineal", "the ruler", "Lineale"],
      ["der Spitzer", "the sharpener", "Spitzer"],
      ["die Schere", "the scissors", "Scheren"],
      ["der Kleber", "the glue", "Kleber"],
      ["das Geodreieck", "the set square", "Geodreiecke"],
      ["der Taschenrechner", "the calculator", "Taschenrechner"],
      ["das Schulbuch", "the schoolbook", "Schulbücher"],
      ["das Arbeitsblatt", "the worksheet", "Arbeitsblätter"],
      ["der Ordner", "the folder / binder", "Ordner"],
      ["die Mappe", "the document folder", "Mappen"],
      ["der Stundenplan", "the timetable", "Stundenpläne"],
      ["das Fach", "the school subject", "Fächer"],
      ["Mathe", "maths"],
      ["Englisch", "English"],
      ["die Biologie", "biology"],
      ["die Physik", "physics"],
      ["die Chemie", "chemistry"],
      ["die Erdkunde", "geography"],
      ["die Kunst", "art"],
      ["die Religion", "religion (school subject)"],
      ["die Turnhalle", "the gym hall", "Turnhallen"],
      ["der Sportplatz", "the sports field", "Sportplätze"],
      ["der Schulhof", "the schoolyard", "Schulhöfe"],
      ["die Aula", "the assembly hall", "Aulen"],
      ["die Kantine", "the canteen", "Kantinen"],
      ["die Mensa", "the cafeteria", "Mensen"],
      ["das Lehrerzimmer", "the staff room", "Lehrerzimmer"],
      ["das Sekretariat", "the school office", "Sekretariate"],
      ["der Schulleiter", "the headteacher (m)", "Schulleiter"],
      ["die Schulleiterin", "the headteacher (f)", "Schulleiterinnen"],
      ["der Hausmeister", "the caretaker", "Hausmeister"],
      ["die Grundschule", "the primary school", "Grundschulen"],
      ["das Gymnasium", "the grammar school", "Gymnasien"],
      ["die Realschule", "the secondary school", "Realschulen"],
      ["der Kindergarten", "the kindergarten", "Kindergärten"],
      ["die Kita", "the nursery", "Kitas"],
      ["das Schuljahr", "the school year", "Schuljahre"],
      ["die Ferien", "the holidays"],
      ["die Sommerferien", "the summer holidays"],
      ["rechnen", "to do maths"],
      ["fehlen", "to be absent"],
      ["aufpassen", "to pay attention"],
      ["stören", "to disturb"],
      ["sich melden", "to put one's hand up"],
      ["die Prüfung", "the exam", "Prüfungen"],
      ["der Test", "the test", "Tests"],
      ["die Klassenarbeit", "the class test", "Klassenarbeiten"],
      ["bestehen", "to pass (an exam)"],
      ["das Wörterbuch", "the dictionary", "Wörterbücher"],
      ["der Aufsatz", "the essay", "Aufsätze"],
      ["das Diktat", "the dictation", "Diktate"],
      ["die Nachhilfe", "tutoring"],
    ],
    phrases: [
      ["Was hast du in der Schultasche?", "What do you have in your school bag?"],
      ["Ich habe Mathe und Englisch.", "I have maths and English."],
      ["Der Stundenplan ist neu.", "The timetable is new."],
      ["Bitte das Lineal und die Schere.", "The ruler and the scissors, please."],
      ["Lea meldet sich.", "Lea puts her hand up."],
      ["Bitte nicht stören!", "Please do not disturb!"],
      ["Tom fehlt heute.", "Tom is absent today."],
      ["Wir gehen in die Turnhalle.", "We are going to the gym hall."],
      ["Hast du das Arbeitsblatt?", "Do you have the worksheet?"],
      ["Die Klassenarbeit ist am Freitag.", "The class test is on Friday."],
      ["Ich möchte die Prüfung bestehen.", "I want to pass the exam."],
      ["In den Sommerferien bin ich frei.", "I am free in the summer holidays."],
    ],
    sentences: [
      ["Im Mäppchen sind ein Bleistift und ein Spitzer.", "In the pencil case there are a pencil and a sharpener."],
      ["Der Schulranzen ist schwer.", "The satchel is heavy."],
      ["Wir rechnen mit dem Taschenrechner.", "We do maths with the calculator."],
      ["Erdkunde und Biologie sind meine Fächer.", "Geography and biology are my subjects."],
      ["Die Kinder essen in der Kantine.", "The children eat in the canteen."],
      ["Das Sekretariat ist neben dem Lehrerzimmer.", "The school office is next to the staff room."],
      ["Die Schulleiterin kommt in die Aula.", "The headteacher comes into the assembly hall."],
      ["Mein Bruder geht in den Kindergarten.", "My brother goes to kindergarten."],
      ["Später kommt das Gymnasium.", "Later comes grammar school."],
      ["Bitte aufpassen und nicht stören.", "Please pay attention and do not disturb."],
      ["Sie schreibt einen Aufsatz und ein Diktat.", "She is writing an essay and a dictation."],
      ["Das Wörterbuch hilft in Englisch.", "The dictionary helps in English."],
      ["Nach der Schule habe ich Nachhilfe.", "After school I have tutoring."],
      ["Der Hausmeister öffnet die Turnhalle.", "The caretaker opens the gym hall."],
      ["Das Schuljahr beginnt im August.", "The school year starts in August."],
      ["In den Ferien bleibt die Grundschule zu.", "In the holidays the primary school stays closed."],
    ],
    readings: [
      {
        title: "Lea's school bag",
        titleDe: "Leas Schultasche",
        text: "Lea geht in die Grundschule. In der Schultasche sind ein Schulbuch, ein Lineal und ein Mäppchen. Der Stundenplan zeigt Mathe, Englisch und Kunst. Um zehn gehen die Kinder auf den Schulhof. Nach der Schule hat Lea Nachhilfe. Am Freitag schreibt sie eine Klassenarbeit. Sie möchte die Prüfung bestehen.",
        translation: "Lea goes to primary school. In the school bag there are a schoolbook, a ruler and a pencil case. The timetable shows maths, English and art. At ten the children go into the schoolyard. After school Lea has tutoring. On Friday she writes a class test. She wants to pass the exam.",
        questions: [
          ["Which school does Lea go to?", "Primary school", ["Grammar school", "Primary school", "Nursery", "University"]],
          ["What is on the timetable?", "Maths, English and art", ["Only sport", "Maths, English and art", "Only music", "Only religion"]],
          ["When is the class test?", "Friday", ["Monday", "Today", "Friday", "In the holidays"]],
        ],
      },
      {
        title: "A note from the office",
        titleDe: "Ein Zettel vom Sekretariat",
        text: "Liebe Klasse, morgen fehlt Frau Berg. Bitte bringt das Arbeitsblatt, den Ordner und den Kleber mit. Um acht Uhr bitte in die Aula kommen. Der Hausmeister öffnet die Tür. Nachher geht ihr in die Turnhalle, nicht auf den Sportplatz. Rechnet leise und stört nicht. Eure Schulleiterin",
        translation: "Dear class, tomorrow Mrs Berg is absent. Please bring the worksheet, the folder and the glue. Please come to the assembly hall at eight. The caretaker opens the door. Afterwards you go to the gym hall, not to the sports field. Do maths quietly and do not disturb. Your headteacher",
        questions: [
          ["Who is absent tomorrow?", "Mrs Berg", ["The caretaker", "Mrs Berg", "The class", "Lea"]],
          ["Where should they go at eight?", "The assembly hall", ["The sports field", "The canteen", "The assembly hall", "The nursery"]],
          ["Where do they go afterwards?", "The gym hall", ["The sports field", "The gym hall", "Home", "The office"]],
        ],
      },
      {
        title: "After the test",
        titleDe: "Nach dem Test",
        text: "Omar ist in der Realschule. Heute schreibt er einen Test in Physik und Chemie. Er benutzt das Wörterbuch nur in Englisch, nicht in Mathe. Der Kugelschreiber ist leer, also nimmt er den Füller. Die Ferien kommen bald, die Sommerferien. Omar möchte den Test bestehen. Am Nachmittag hat er Nachhilfe in Erdkunde.",
        translation: "Omar is at secondary school. Today he writes a test in physics and chemistry. He uses the dictionary only in English, not in maths. The ballpoint pen is empty, so he takes the fountain pen. The holidays are coming soon, the summer holidays. Omar wants to pass the test. In the afternoon he has tutoring in geography.",
        questions: [
          ["Which school is Omar at?", "Secondary school", ["Primary school", "Nursery", "Secondary school", "Kindergarten"]],
          ["When does he use the dictionary?", "In English", ["In maths", "In physics", "In English", "Never"]],
          ["What does he have in the afternoon?", "Tutoring in geography", ["A class test", "Art", "Tutoring in geography", "Sport"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about your school bag and timetable.",
        "Schreib vier Sätze über deine Schultasche und den Stundenplan.",
        "In meiner Schultasche sind ein Mäppchen und ein Lineal. Ich habe Mathe und Englisch. Der Stundenplan ist am Montag lang. Ich möchte die Prüfung bestehen.",
        ["Name two bag items", "Name two subjects", "Use bestehen or fehlen once"],
      ],
      [
        "Write a short note to the class about tomorrow.",
        "Schreib einen kurzen Zettel an die Klasse für morgen.",
        "Morgen fehlt Tom. Bitte das Arbeitsblatt mitbringen. Wir gehen in die Aula. Nicht stören!",
        ["Start with Morgen", "Use fehlen or bitte", "Name one school place"],
      ],
    ],
  }),
  packChapter({
    slug: "animals-nature",
    title: "Animals & Nature",
    titleDe: "Tiere und Natur",
    blurb: "Name farm and wild animals, simple plants and places in nature.",
    skill: "vocab",
    grammar: [
      "Animal nouns need articles: der Vogel, die Kuh, das Pferd.",
      "Many plurals take an umlaut: der Baum — die Bäume, der Fuchs — die Füchse.",
      "wild and zahm are adjectives after sein: Der Wolf ist wild. Das Schaf ist zahm.",
    ],
    vocab: [
      ["das Tier", "the animal", "Tiere"],
      ["der Vogel", "the bird", "Vögel"],
      ["das Pferd", "the horse", "Pferde"],
      ["die Kuh", "the cow", "Kühe"],
      ["das Schaf", "the sheep", "Schafe"],
      ["das Schwein", "the pig", "Schweine"],
      ["die Ziege", "the goat", "Ziegen"],
      ["das Huhn", "the chicken", "Hühner"],
      ["die Ente", "the duck", "Enten"],
      ["das Kaninchen", "the rabbit", "Kaninchen"],
      ["der Hase", "the hare", "Hasen"],
      ["der Fuchs", "the fox", "Füchse"],
      ["der Bär", "the bear", "Bären"],
      ["der Löwe", "the lion", "Löwen"],
      ["der Elefant", "the elephant", "Elefanten"],
      ["der Affe", "the monkey", "Affen"],
      ["der Wolf", "the wolf", "Wölfe"],
      ["der Schmetterling", "the butterfly", "Schmetterlinge"],
      ["die Biene", "the bee", "Bienen"],
      ["die Spinne", "the spider", "Spinnen"],
      ["der Frosch", "the frog", "Frösche"],
      ["der Igel", "the hedgehog", "Igel"],
      ["das Reh", "the deer", "Rehe"],
      ["der Hamster", "the hamster", "Hamster"],
      ["die Schildkröte", "the tortoise", "Schildkröten"],
      ["der Baum", "the tree", "Bäume"],
      ["die Blume", "the flower", "Blumen"],
      ["das Blatt", "the leaf", "Blätter"],
      ["der Wald", "the forest", "Wälder"],
      ["die Wiese", "the meadow", "Wiesen"],
      ["der See", "the lake", "Seen"],
      ["der Bach", "the stream", "Bäche"],
      ["der Stein", "the stone", "Steine"],
      ["das Gras", "the grass"],
      ["der Bauer", "the farmer (m)", "Bauern"],
      ["die Bäuerin", "the farmer (f)", "Bäuerinnen"],
      ["der Bauernhof", "the farm", "Bauernhöfe"],
      ["der Zoo", "the zoo", "Zoos"],
      ["der Stall", "the stable / stall", "Ställe"],
      ["das Nest", "the nest", "Nester"],
      ["füttern", "to feed"],
      ["hüpfen", "to hop"],
      ["der Käfig", "the cage", "Käfige"],
      ["das Fell", "the fur / coat"],
      ["die Pfote", "the paw", "Pfoten"],
      ["der Schwanz", "the tail", "Schwänze"],
      ["wild", "wild"],
      ["zahm", "tame"],
      ["der Berg", "the mountain", "Berge"],
      ["das Tal", "the valley", "Täler"],
      ["der Hügel", "the hill", "Hügel"],
      ["die Erde", "the earth / soil"],
      ["der Sand", "the sand"],
      ["der Pilz", "the mushroom", "Pilze"],
      ["die Rose", "the rose", "Rosen"],
      ["die Eiche", "the oak", "Eichen"],
      ["die Tanne", "the fir", "Tannen"],
      ["das Eichhörnchen", "the squirrel", "Eichhörnchen"],
    ],
    phrases: [
      ["Das ist ein Vogel auf dem Baum.", "That is a bird on the tree."],
      ["Die Kuh ist auf dem Bauernhof.", "The cow is on the farm."],
      ["Der Wolf ist wild, das Schaf ist zahm.", "The wolf is wild, the sheep is tame."],
      ["Wir füttern die Pferde.", "We feed the horses."],
      ["Der Frosch hüpft in den Bach.", "The frog hops into the stream."],
      ["Im Zoo sehe ich einen Löwen.", "In the zoo I see a lion."],
      ["Die Biene fliegt zur Blume.", "The bee flies to the flower."],
      ["Das Reh steht im Wald.", "The deer stands in the forest."],
      ["Die Ente schwimmt auf dem See.", "The duck swims on the lake."],
      ["Der Igel hat ein Nest unter dem Blatt.", "The hedgehog has a nest under the leaf."],
      ["Die Rose ist eine Blume.", "The rose is a flower."],
      ["Am Berg ist ein Tal.", "At the mountain there is a valley."],
    ],
    sentences: [
      ["Der Bauer hat Kühe, Schafe und Ziegen.", "The farmer has cows, sheep and goats."],
      ["Die Bäuerin füttert die Hühner im Stall.", "The farmer feeds the chickens in the stall."],
      ["Das Schwein liegt im Gras auf der Wiese.", "The pig lies in the grass in the meadow."],
      ["Ein Eichhörnchen sitzt in der Eiche.", "A squirrel sits in the oak."],
      ["Die Tanne steht auf dem Hügel.", "The fir stands on the hill."],
      ["Der Hase und das Kaninchen hüpfen.", "The hare and the rabbit hop."],
      ["Der Fuchs hat einen langen Schwanz.", "The fox has a long tail."],
      ["Die Schildkröte ist langsam und zahm.", "The tortoise is slow and tame."],
      ["Der Bär und der Elefant sind groß.", "The bear and the elephant are big."],
      ["Der Affe sitzt nicht im Käfig.", "The monkey is not sitting in the cage."],
      ["Die Spinne ist klein, der Schmetterling ist bunt.", "The spider is small, the butterfly is colourful."],
      ["Im Sand am See liegen Steine.", "In the sand at the lake there are stones."],
      ["Ein Pilz wächst in der Erde unter dem Baum.", "A mushroom grows in the soil under the tree."],
      ["Der Hamster hat weiches Fell und kleine Pfoten.", "The hamster has soft fur and small paws."],
      ["Viele Tiere leben im Wald.", "Many animals live in the forest."],
      ["Der Zoo zeigt wilde Tiere und zahme Tiere.", "The zoo shows wild animals and tame animals."],
    ],
    readings: [
      {
        title: "On the farm",
        titleDe: "Auf dem Bauernhof",
        text: "Anna ist auf dem Bauernhof. Der Bauer füttert die Pferde. Die Bäuerin holt Eier von den Hühnern. Eine Kuh steht im Stall, zwei Schafe sind auf der Wiese. Das Schwein liegt im Gras. Ein Hund ist nicht hier, nur ein zahmes Kaninchen. Anna sieht eine Ente am Bach. Die Tiere sind ruhig.",
        translation: "Anna is on the farm. The farmer feeds the horses. The farmer collects eggs from the chickens. A cow stands in the stall, two sheep are in the meadow. The pig lies in the grass. A dog is not here, only a tame rabbit. Anna sees a duck at the stream. The animals are quiet.",
        questions: [
          ["Where is Anna?", "On the farm", ["In the zoo", "On the farm", "In the forest", "At the lake"]],
          ["What does the farmer feed?", "The horses", ["The lions", "The horses", "The bees", "The foxes"]],
          ["Which animal is tame here?", "A rabbit", ["A wolf", "A bear", "A rabbit", "A lion"]],
        ],
      },
      {
        title: "A walk in the forest",
        titleDe: "Ein Gang im Wald",
        text: "Wir gehen in den Wald. Unter der Eiche sitzt ein Eichhörnchen. Ein Reh steht still. Der Igel hat ein Nest aus Blättern. Am Bach hüpft ein Frosch. Ein Fuchs läuft über die Erde. Die Tanne ist hoch, die Rose wächst nicht hier. Ein Pilz steht neben einem Stein. Es ist still und schön.",
        translation: "We go into the forest. Under the oak sits a squirrel. A deer stands still. The hedgehog has a nest of leaves. At the stream a frog hops. A fox runs across the soil. The fir is tall, the rose does not grow here. A mushroom stands next to a stone. It is quiet and beautiful.",
        questions: [
          ["What sits under the oak?", "A squirrel", ["A lion", "A squirrel", "A cow", "A duck"]],
          ["Where does the frog hop?", "At the stream", ["In the zoo", "On the farm", "At the stream", "On the mountain"]],
          ["What does not grow here?", "The rose", ["The fir", "The mushroom", "The oak", "The rose"]],
        ],
      },
      {
        title: "A day at the zoo",
        titleDe: "Ein Tag im Zoo",
        text: "Im Zoo sieht Ben einen Löwen, einen Elefanten und einen Affen. Der Wolf ist wild. Die Schildkröte ist zahm und langsam. Ein Vogel sitzt nicht im Käfig, er sitzt auf einem Baum. Der Bär hat dickes Fell und große Pfoten. Ben füttert die Tiere nicht. Er schaut nur. Am Berg hinter dem Zoo liegt ein Tal.",
        translation: "At the zoo Ben sees a lion, an elephant and a monkey. The wolf is wild. The tortoise is tame and slow. A bird is not in a cage; it sits on a tree. The bear has thick fur and big paws. Ben does not feed the animals. He only looks. On the mountain behind the zoo there is a valley.",
        questions: [
          ["Which animal is wild?", "The wolf", ["The tortoise", "The sheep", "The wolf", "The chicken"]],
          ["Where does the bird sit?", "On a tree", ["In a cage", "On a tree", "In the stall", "In the sand"]],
          ["What does Ben do?", "He only looks", ["He feeds the lion", "He only looks", "He opens the cage", "He takes a horse"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about animals on a farm or in a forest.",
        "Schreib vier Sätze über Tiere auf einem Bauernhof oder im Wald.",
        "Auf dem Bauernhof sind Kühe und Schafe. Der Bauer füttert die Pferde. Im Wald sitzt ein Eichhörnchen. Der Wolf ist wild.",
        ["Use at least two animals", "Use füttern or hüpfen", "Use wild or zahm"],
      ],
      [
        "Describe a short visit to the zoo.",
        "Beschreibe einen kurzen Besuch im Zoo.",
        "Im Zoo sehe ich einen Löwen und einen Elefanten. Der Affe sitzt nicht im Käfig. Ich füttere die Tiere nicht. Der Bär hat großes Fell.",
        ["Name two zoo animals", "Say what you do not do", "Keep sentences short"],
      ],
    ],
  }),
  packChapter({
    slug: "places-town",
    title: "Places in Town",
    titleDe: "Orte in der Stadt",
    blurb: "Name everyday places: baker, bank, station surroundings and local shops.",
    skill: "mixed",
    grammar: [
      "in + dative for being inside a place: in der Buchhandlung, im Restaurant.",
      "zu + person or shop: zum Bäcker, zur Sparkasse.",
      "These words are places, not shopping verbs: Ich bin in der Drogerie.",
    ],
    vocab: [
      ["die Sparkasse", "the savings bank", "Sparkassen"],
      ["die Konditorei", "the cake shop", "Konditoreien"],
      ["der Kiosk", "the kiosk", "Kioske"],
      ["die Buchhandlung", "the bookshop", "Buchhandlungen"],
      ["die Drogerie", "the drugstore", "Drogerien"],
      ["der Friseur", "the hairdresser", "Friseure"],
      ["der Friseursalon", "the hair salon", "Friseursalons"],
      ["der Blumenladen", "the flower shop", "Blumenläden"],
      ["das Kaufhaus", "the department store", "Kaufhäuser"],
      ["das Einkaufszentrum", "the shopping centre", "Einkaufszentren"],
      ["die Tankstelle", "the petrol station", "Tankstellen"],
      ["das Restaurant", "the restaurant", "Restaurants"],
      ["die Pizzeria", "the pizzeria", "Pizzerien"],
      ["der Imbiss", "the snack bar", "Imbisse"],
      ["die Eisdiele", "the ice-cream shop", "Eisdielen"],
      ["die Kneipe", "the pub", "Kneipen"],
      ["das Polizeirevier", "the police station", "Polizeireviere"],
      ["die Polizei", "the police"],
      ["die Feuerwehr", "the fire brigade"],
      ["das Bürgeramt", "the citizens' office", "Bürgerämter"],
      ["die Stadtverwaltung", "the city administration"],
      ["das Schwimmbad", "the swimming pool", "Schwimmbäder"],
      ["das Hallenbad", "the indoor pool", "Hallenbäder"],
      ["das Freibad", "the outdoor pool", "Freibäder"],
      ["der Spielplatz", "the playground", "Spielplätze"],
      ["das Stadion", "the stadium", "Stadien"],
      ["der Marktplatz", "the market square", "Marktplätze"],
      ["die Hauptstraße", "the high street", "Hauptstraßen"],
      ["die Gasse", "the alley", "Gassen"],
      ["der Bahnhofsvorplatz", "the station forecourt", "Bahnhofsvorplätze"],
      ["die Bahnhofshalle", "the station concourse", "Bahnhofshallen"],
      ["der Taxistand", "the taxi rank", "Taxistände"],
      ["der Busbahnhof", "the bus station", "Busbahnhöfe"],
      ["das Parkhaus", "the car park (building)", "Parkhäuser"],
      ["die Tiefgarage", "the underground car park", "Tiefgaragen"],
      ["der Stadtpark", "the city park", "Stadtparks"],
      ["die Klinik", "the clinic", "Kliniken"],
      ["die Bücherei", "the public library", "Büchereien"],
      ["die Burg", "the castle", "Burgen"],
      ["der Turm", "the tower", "Türme"],
      ["die Kapelle", "the chapel", "Kapellen"],
      ["das Fitnessstudio", "the gym", "Fitnessstudios"],
      ["die Volkshochschule", "the adult education centre", "Volkshochschulen"],
      ["das Jugendzentrum", "the youth centre", "Jugendzentren"],
      ["der Friedhof", "the cemetery", "Friedhöfe"],
      ["die Passage", "the arcade", "Passagen"],
      ["die Oper", "the opera house", "Opern"],
      ["die Galerie", "the gallery", "Galerien"],
      ["der Flohmarkt", "the flea market", "Flohmärkte"],
      ["die Gärtnerei", "the garden centre", "Gärtnereien"],
      ["das Postamt", "the post office building", "Postämter"],
      ["die Bushaltestelle", "the bus stop", "Bushaltestellen"],
      ["der Bäcker", "the baker / baker's", "Bäcker"],
      ["die Bäckerin", "the baker (f)", "Bäckerinnen"],
      ["das Amt", "the office / authority", "Ämter"],
      ["die Behörde", "the public authority", "Behörden"],
      ["der Gehweg", "the pavement", "Gehwege"],
      ["das Stadttor", "the town gate", "Stadttore"],
    ],
    phrases: [
      ["Wo ist die Sparkasse?", "Where is the savings bank?"],
      ["Ich gehe zum Bäcker.", "I am going to the baker's."],
      ["Die Konditorei ist in der Hauptstraße.", "The cake shop is on the high street."],
      ["Der Taxistand ist am Bahnhofsvorplatz.", "The taxi rank is on the station forecourt."],
      ["Wir treffen uns in der Bahnhofshalle.", "We meet in the station concourse."],
      ["Das Restaurant ist neben der Pizzeria.", "The restaurant is next to the pizzeria."],
      ["Die Polizei ist im Polizeirevier.", "The police are in the police station."],
      ["Kinder spielen auf dem Spielplatz.", "Children play on the playground."],
      ["Das Auto steht im Parkhaus.", "The car is in the multi-storey car park."],
      ["Die Bushaltestelle ist vor dem Kaufhaus.", "The bus stop is in front of the department store."],
      ["Im Sommer gehe ich ins Freibad.", "In summer I go to the outdoor pool."],
      ["Das Bürgeramt ist in der Stadtverwaltung.", "The citizens' office is in the city administration."],
    ],
    sentences: [
      ["Die Bäckerin arbeitet in der Konditorei.", "The baker works in the cake shop."],
      ["In der Buchhandlung und in der Bücherei gibt es Bücher.", "In the bookshop and in the library there are books."],
      ["Die Drogerie liegt in der Passage.", "The drugstore is in the arcade."],
      ["Der Friseur hat einen Friseursalon in der Gasse.", "The hairdresser has a salon in the alley."],
      ["Am Marktplatz ist ein Blumenladen und ein Kiosk.", "On the market square there is a flower shop and a kiosk."],
      ["Das Einkaufszentrum hat eine Tankstelle.", "The shopping centre has a petrol station."],
      ["Wir essen im Imbiss, nicht in der Kneipe.", "We eat at the snack bar, not in the pub."],
      ["Die Feuerwehr und die Klinik sind nah.", "The fire brigade and the clinic are close."],
      ["Das Stadion ist hinter dem Stadtpark.", "The stadium is behind the city park."],
      ["Die Burg und der Turm sind alt.", "The castle and the tower are old."],
      ["Das Postamt ist neben dem Amt.", "The post office is next to the office."],
      ["Der Flohmarkt ist am Stadttor.", "The flea market is at the town gate."],
      ["Die Volkshochschule und das Jugendzentrum sind neu.", "The adult education centre and the youth centre are new."],
      ["Bitte auf dem Gehweg bleiben, nicht auf der Straße.", "Please stay on the pavement, not on the street."],
      ["Die Oper und die Galerie sind in der Stadt.", "The opera house and the gallery are in the city."],
      ["Die Tiefgarage ist unter dem Busbahnhof.", "The underground car park is under the bus station."],
    ],
    readings: [
      {
        title: "Around the station",
        titleDe: "Rund um den Bahnhof",
        text: "Am Bahnhofsvorplatz stehen Taxis am Taxistand. In der Bahnhofshalle gibt es einen Kiosk und einen Imbiss. Der Busbahnhof ist links. Die Bushaltestelle für die Stadt ist vor dem Eingang. Mira wartet auf dem Gehweg. Die Sparkasse ist in der Hauptstraße, fünf Minuten zu Fuß. Ein Parkhaus steht neben der Tiefgarage.",
        translation: "On the station forecourt taxis stand at the taxi rank. In the station concourse there is a kiosk and a snack bar. The bus station is on the left. The city bus stop is in front of the entrance. Mira waits on the pavement. The savings bank is on the high street, five minutes on foot. A multi-storey car park stands next to the underground car park.",
        questions: [
          ["Where are the taxis?", "At the taxi rank", ["In the cake shop", "At the taxi rank", "In the chapel", "At the cemetery"]],
          ["What is in the concourse?", "A kiosk and a snack bar", ["A stadium", "A kiosk and a snack bar", "A castle", "A swimming pool"]],
          ["Where is the savings bank?", "On the high street", ["In the park", "Under the bus station", "On the high street", "At the town gate"]],
        ],
      },
      {
        title: "Saturday in town",
        titleDe: "Samstag in der Stadt",
        text: "Samstag geht die Familie in die Stadt. Zuerst zum Bäcker, dann in die Konditorei. Die Kinder wollen in die Eisdiele. Papa braucht die Drogerie und die Buchhandlung. Mama geht zum Friseur. Später essen sie in der Pizzeria am Marktplatz. Der Blumenladen hat noch auf. Der Flohmarkt ist am Stadttor nur bis vier.",
        translation: "On Saturday the family goes into town. First to the baker's, then to the cake shop. The children want to go to the ice-cream shop. Dad needs the drugstore and the bookshop. Mum goes to the hairdresser. Later they eat at the pizzeria on the market square. The flower shop is still open. The flea market at the town gate is only until four.",
        questions: [
          ["Where do they go first?", "To the baker's", ["To the opera", "To the baker's", "To the clinic", "To the cemetery"]],
          ["Where do they eat later?", "At the pizzeria", ["At the kiosk", "At the pizzeria", "At the snack bar", "At the pub"]],
          ["Until when is the flea market open?", "Until four", ["Until eight", "Until four", "All night", "Until Monday"]],
        ],
      },
      {
        title: "A map for guests",
        titleDe: "Ein Plan für Gäste",
        text: "Liebe Gäste, das Bürgeramt und die Stadtverwaltung sind im Amt am Marktplatz. Die Polizei sitzt im Polizeirevier neben der Feuerwehr. Das Schwimmbad hat ein Hallenbad und im Sommer ein Freibad. Die Bücherei ist in der Passage. Die Burg, der Turm und die Kapelle sind oben in der Altstadt. Das Fitnessstudio liegt am Stadtpark.",
        translation: "Dear guests, the citizens' office and the city administration are in the office on the market square. The police sit in the police station next to the fire brigade. The swimming pool has an indoor pool and in summer an outdoor pool. The library is in the arcade. The castle, the tower and the chapel are up in the old town. The gym is by the city park.",
        questions: [
          ["Where is the citizens' office?", "On the market square", ["At the stadium", "On the market square", "At the taxi rank", "At the petrol station"]],
          ["What does the swimming pool have in summer?", "An outdoor pool", ["A castle", "An outdoor pool", "A gallery", "A kiosk"]],
          ["Where is the gym?", "By the city park", ["In the chapel", "By the city park", "In the cemetery", "At the town gate"]],
        ],
      },
    ],
    writings: [
      [
        "Write where four places in your town are.",
        "Schreib, wo vier Orte in deiner Stadt sind.",
        "Die Sparkasse ist in der Hauptstraße. Der Bäcker ist am Marktplatz. Das Restaurant ist neben der Pizzeria. Der Spielplatz ist im Stadtpark.",
        ["Use in or am / neben", "Name four places", "Keep articles with the nouns"],
      ],
      [
        "Write a short meeting note at the station.",
        "Schreib eine kurze Treff-Notiz am Bahnhof.",
        "Treffpunkt: Bahnhofshalle, neben dem Kiosk. Der Taxistand ist draußen. Ich warte auf dem Gehweg.",
        ["Name the concourse or forecourt", "Name one more place", "Use warten or gehen"],
      ],
    ],
  }),
  packChapter({
    slug: "body-feelings",
    title: "Body & Feelings",
    titleDe: "Körper und Gefühle",
    blurb: "Name more body parts and everyday feelings, then say how you feel.",
    skill: "vocab",
    grammar: [
      "Body parts take articles: der Arm, die Schulter, das Knie.",
      "Feelings often follow sein: Ich bin froh. Sie ist traurig.",
      "sich fühlen + adjective: Ich fühle mich munter.",
    ],
    vocab: [
      ["der Arm", "the arm", "Arme"],
      ["das Bein", "the leg", "Beine"],
      ["der Finger", "the finger", "Finger"],
      ["der Daumen", "the thumb", "Daumen"],
      ["der Zeh", "the toe", "Zehen"],
      ["das Knie", "the knee", "Knie"],
      ["die Schulter", "the shoulder", "Schultern"],
      ["der Ellenbogen", "the elbow", "Ellenbogen"],
      ["der Nacken", "the nape / back of the neck"],
      ["die Hüfte", "the hip", "Hüften"],
      ["der Knöchel", "the ankle", "Knöchel"],
      ["die Brust", "the chest", "Brüste"],
      ["das Herz", "the heart", "Herzen"],
      ["der Magen", "the stomach", "Mägen"],
      ["der Zahn", "the tooth", "Zähne"],
      ["der Mund", "the mouth", "Münder"],
      ["die Lippe", "the lip", "Lippen"],
      ["die Zunge", "the tongue", "Zungen"],
      ["die Stirn", "the forehead", "Stirnen"],
      ["die Wange", "the cheek", "Wangen"],
      ["das Kinn", "the chin", "Kinne"],
      ["die Haut", "the skin"],
      ["der Knochen", "the bone", "Knochen"],
      ["der Muskel", "the muscle", "Muskeln"],
      ["atmen", "to breathe"],
      ["der Atem", "the breath"],
      ["fühlen", "to feel / sense"],
      ["das Gefühl", "the feeling", "Gefühle"],
      ["glücklich", "happy"],
      ["traurig", "sad"],
      ["wütend", "angry"],
      ["nervös", "nervous"],
      ["zufrieden", "content"],
      ["froh", "glad"],
      ["stolz", "proud"],
      ["einsam", "lonely"],
      ["aufgeregt", "excited / agitated"],
      ["schüchtern", "shy"],
      ["verliebt", "in love"],
      ["weinen", "to cry"],
      ["lachen", "to laugh"],
      ["die Freude", "the joy"],
      ["die Angst", "the fear"],
      ["die Wut", "the anger"],
      ["das Glück", "the happiness / luck"],
      ["das Pech", "the bad luck"],
      ["die Stimmung", "the mood", "Stimmungen"],
      ["sich fühlen", "to feel (how you are)"],
      ["munter", "cheerful / lively"],
      ["schläfrig", "sleepy"],
      ["kräftig", "strong"],
      ["erschöpft", "exhausted"],
      ["unsicher", "unsure"],
      ["schmecken", "to taste"],
      ["riechen", "to smell"],
      ["niesen", "to sneeze"],
      ["zittern", "to tremble"],
      ["die Träne", "the tear", "Tränen"],
    ],
    phrases: [
      ["Wie fühlst du dich?", "How do you feel?"],
      ["Ich bin glücklich und froh.", "I am happy and glad."],
      ["Sie ist traurig und weint.", "She is sad and is crying."],
      ["Mein Arm und mein Bein sind kräftig.", "My arm and my leg are strong."],
      ["Der Zahn tut nicht weh.", "The tooth does not hurt."],
      ["Bitte den Mund öffnen.", "Please open your mouth."],
      ["Ich bin nervös und unsicher.", "I am nervous and unsure."],
      ["Er ist stolz und zufrieden.", "He is proud and content."],
      ["Das Herz schlägt schnell.", "The heart beats fast."],
      ["Ich muss niesen.", "I have to sneeze."],
      ["Die Stimmung ist gut.", "The mood is good."],
      ["Kein Pech, nur Glück!", "No bad luck, only luck!"],
    ],
    sentences: [
      ["Der Finger und der Daumen sind an der Hand.", "The finger and the thumb are on the hand."],
      ["Der Zeh und der Knöchel sind am Fuß.", "The toe and the ankle are on the foot."],
      ["Die Schulter und der Ellenbogen tun weh nach dem Sport.", "The shoulder and the elbow hurt after sport."],
      ["Das Knie und die Hüfte sind steif.", "The knee and the hip are stiff."],
      ["Die Stirn, die Wange und das Kinn sind im Gesicht.", "The forehead, the cheek and the chin are on the face."],
      ["Die Lippe und die Zunge schmecken den Tee.", "The lip and the tongue taste the tea."],
      ["Die Haut ist warm, der Atem ist ruhig.", "The skin is warm, the breath is calm."],
      ["Atme langsam. Nicht zittern.", "Breathe slowly. Do not tremble."],
      ["Das Kind ist schüchtern und einsam.", "The child is shy and lonely."],
      ["Sie ist verliebt und lacht.", "She is in love and laughs."],
      ["Er ist wütend. Die Wut ist groß.", "He is angry. The anger is big."],
      ["Eine Träne fällt, aber die Freude kommt wieder.", "A tear falls, but the joy comes back."],
      ["Ich fühle mich munter, nicht schläfrig.", "I feel lively, not sleepy."],
      ["Nach der Arbeit bin ich erschöpft.", "After work I am exhausted."],
      ["Der Magen ist voll. Das ist ein gutes Gefühl.", "The stomach is full. That is a good feeling."],
      ["Die Blume riecht gut. Ich bin aufgeregt und froh.", "The flower smells good. I am excited and glad."],
    ],
    readings: [
      {
        title: "After sport",
        titleDe: "Nach dem Sport",
        text: "Ben kommt nach Hause. Der Arm und das Bein sind kräftig, aber das Knie und der Knöchel tun weh. Die Schulter ist steif, der Nacken auch. Ben atmet langsam. Er ist erschöpft, nicht munter. Die Stimmung ist trotzdem gut. Er ist stolz. Kein Pech heute, ein bisschen Glück. Er lacht und trinkt Wasser.",
        translation: "Ben comes home. The arm and the leg are strong, but the knee and the ankle hurt. The shoulder is stiff, the nape too. Ben breathes slowly. He is exhausted, not lively. The mood is still good. He is proud. No bad luck today, a bit of luck. He laughs and drinks water.",
        questions: [
          ["What hurts?", "The knee and the ankle", ["The tooth", "The knee and the ankle", "The lip", "The chin"]],
          ["How does Ben feel?", "Exhausted", ["Shy", "In love", "Exhausted", "Angry"]],
          ["Is he proud?", "Yes", ["No", "Yes", "He is sad", "He is lonely"]],
        ],
      },
      {
        title: "A shy morning",
        titleDe: "Ein schüchterner Morgen",
        text: "Mira ist schüchtern und unsicher. Die Wange ist rot, die Stirn ist warm. Sie hat ein bisschen Angst. Der Mund ist trocken, die Zunge auch. Mira möchte nicht weinen. Eine Träne kommt trotzdem. Dann kommt Tom. Er ist froh und munter. Mira lacht. Die Freude ist da. Sie fühlt sich nicht mehr einsam.",
        translation: "Mira is shy and unsure. The cheek is red, the forehead is warm. She has a little fear. The mouth is dry, the tongue too. Mira does not want to cry. A tear comes anyway. Then Tom comes. He is glad and lively. Mira laughs. The joy is there. She no longer feels lonely.",
        questions: [
          ["How is Mira at first?", "Shy and unsure", ["Proud and strong", "Shy and unsure", "Angry", "Sleepy only"]],
          ["What comes anyway?", "A tear", ["A tooth", "A tear", "A muscle", "A knee"]],
          ["How does she feel at the end?", "Not lonely", ["Angry", "Exhausted", "Not lonely", "Sleepy"]],
        ],
      },
      {
        title: "Taste and smell",
        titleDe: "Schmecken und riechen",
        text: "Oma macht Tee. Nils riecht den Tee und schmeckt ihn mit der Zunge. Der Magen ist leer, also ist er froh. Plötzlich muss er niesen. Der Finger hält die Lippe, das Kinn zittert kurz. Oma lacht. Nils ist nicht wütend, nur aufgeregt. Das Herz ist ruhig. Er ist zufrieden und glücklich. Das ist ein schönes Gefühl.",
        translation: "Grandma makes tea. Nils smells the tea and tastes it with his tongue. The stomach is empty, so he is glad. Suddenly he has to sneeze. The finger holds the lip, the chin trembles briefly. Grandma laughs. Nils is not angry, only excited. The heart is calm. He is content and happy. That is a nice feeling.",
        questions: [
          ["What does Nils do with the tea?", "He smells and tastes it", ["He throws it", "He smells and tastes it", "He is angry", "He cries"]],
          ["What must he do suddenly?", "Sneeze", ["Run", "Sneeze", "Sleep", "Swim"]],
          ["How is he at the end?", "Content and happy", ["Lonely", "Content and happy", "Shy", "Exhausted only"]],
        ],
      },
    ],
    writings: [
      [
        "Write how you feel today and name three body parts.",
        "Schreib, wie du dich heute fühlst, und nenne drei Körperteile.",
        "Ich fühle mich munter. Der Arm und das Bein sind kräftig. Das Knie tut nicht weh. Ich bin froh.",
        ["Use sich fühlen or sein + adjective", "Name three body parts", "Keep it in the present"],
      ],
      [
        "Write four sentences about a sad or happy moment.",
        "Schreib vier Sätze über einen traurigen oder glücklichen Moment.",
        "Tom ist traurig und weint. Eine Träne fällt. Dann kommt Lea. Tom lacht. Die Freude ist da.",
        ["Use traurig or glücklich", "Use weinen or lachen", "End with a feeling noun or adjective"],
      ],
    ],
  }),
  packChapter({
    slug: "countries-nationalities",
    title: "Countries & Nationalities",
    titleDe: "Länder und Nationalitäten",
    blurb: "Add new countries, cities and nationality words beyond Germany, Austria and Switzerland.",
    skill: "writing",
    grammar: [
      "Ich komme aus + country: aus Schweden, aus Japan. aus den USA needs die.",
      "Ich wohne in + city: in Berlin, in Wien, in Paris.",
      "Nationality adjectives stay lowercase: Ich bin französisch. Ich bin türkisch.",
    ],
    vocab: [
      ["Belgien", "Belgium"],
      ["Luxemburg", "Luxembourg"],
      ["Dänemark", "Denmark"],
      ["Schweden", "Sweden"],
      ["Norwegen", "Norway"],
      ["Finnland", "Finland"],
      ["Griechenland", "Greece"],
      ["Portugal", "Portugal"],
      ["Irland", "Ireland"],
      ["Großbritannien", "Great Britain"],
      ["die USA", "the USA"],
      ["Kanada", "Canada"],
      ["Mexiko", "Mexico"],
      ["Brasilien", "Brazil"],
      ["China", "China"],
      ["Japan", "Japan"],
      ["Indien", "India"],
      ["Ägypten", "Egypt"],
      ["Marokko", "Morocco"],
      ["Australien", "Australia"],
      ["Russland", "Russia"],
      ["Tschechien", "Czechia"],
      ["Ungarn", "Hungary"],
      ["Kroatien", "Croatia"],
      ["Berlin", "Berlin"],
      ["München", "Munich"],
      ["Hamburg", "Hamburg"],
      ["Wien", "Vienna"],
      ["Zürich", "Zurich"],
      ["Paris", "Paris"],
      ["London", "London"],
      ["Rom", "Rome"],
      ["Madrid", "Madrid"],
      ["Amsterdam", "Amsterdam"],
      ["die Hauptstadt", "the capital", "Hauptstädte"],
      ["Europa", "Europe"],
      ["Asien", "Asia"],
      ["Afrika", "Africa"],
      ["die Flagge", "the flag", "Flaggen"],
      ["die Grenze", "the border", "Grenzen"],
      ["das Ausland", "abroad / foreign countries"],
      ["die Heimat", "the home country / home"],
      ["der Tourist", "the tourist (m)", "Touristen"],
      ["die Touristin", "the tourist (f)", "Touristinnen"],
      ["europäisch", "European"],
      ["amerikanisch", "American"],
      ["chinesisch", "Chinese"],
      ["japanisch", "Japanese"],
      ["griechisch", "Greek"],
      ["portugiesisch", "Portuguese"],
      ["russisch", "Russian"],
      ["arabisch", "Arabic"],
      ["indisch", "Indian"],
      ["schwedisch", "Swedish"],
      ["türkisch", "Turkish"],
      ["polnisch", "Polish"],
      ["französisch", "French"],
      ["britisch", "British"],
    ],
    phrases: [
      ["Woher kommst du?", "Where are you from?"],
      ["Ich komme aus Schweden.", "I come from Sweden."],
      ["Ich wohne in Berlin.", "I live in Berlin."],
      ["Paris ist die Hauptstadt.", "Paris is the capital."],
      ["Die Flagge ist rot und weiß.", "The flag is red and white."],
      ["Ist das in Europa oder in Asien?", "Is that in Europe or in Asia?"],
      ["Ich bin im Ausland.", "I am abroad."],
      ["Das ist meine Heimat.", "That is my home country."],
      ["Sie ist Touristin aus Japan.", "She is a tourist from Japan."],
      ["Die Grenze ist nah.", "The border is close."],
      ["Er spricht französisch und arabisch.", "He speaks French and Arabic."],
      ["Kommt ihr aus den USA?", "Are you from the USA?"],
    ],
    sentences: [
      ["Belgien, Luxemburg und die Niederlande sind in Europa.", "Belgium, Luxembourg and the Netherlands are in Europe."],
      ["Dänemark, Schweden, Norwegen und Finnland sind im Norden.", "Denmark, Sweden, Norway and Finland are in the north."],
      ["Griechenland und Kroatien liegen am Meer.", "Greece and Croatia lie by the sea."],
      ["Portugal und Irland sind in Europa, nicht in Asien.", "Portugal and Ireland are in Europe, not in Asia."],
      ["London ist in Großbritannien. Die Flagge ist britisch.", "London is in Great Britain. The flag is British."],
      ["New York ist in den USA. Er ist amerikanisch.", "New York is in the USA. He is American."],
      ["Kanada und Mexiko sind nicht in Europa.", "Canada and Mexico are not in Europe."],
      ["Brasilien ist groß. Die Hauptstadt ist nicht Rio.", "Brazil is big. The capital is not Rio."],
      ["China und Japan sind in Asien. Sie spricht chinesisch und japanisch.", "China and Japan are in Asia. She speaks Chinese and Japanese."],
      ["Indien ist in Asien. Das Essen ist indisch.", "India is in Asia. The food is Indian."],
      ["Ägypten und Marokko sind in Afrika. Er spricht arabisch.", "Egypt and Morocco are in Africa. He speaks Arabic."],
      ["Australien ist weit. Die Touristen kommen gern.", "Australia is far. The tourists like to come."],
      ["Moskau ist in Russland. Die Sprache ist russisch.", "Moscow is in Russia. The language is Russian."],
      ["Prag ist in Tschechien, Budapest in Ungarn.", "Prague is in Czechia, Budapest in Hungary."],
      ["Berlin, München und Hamburg sind in Deutschland.", "Berlin, Munich and Hamburg are in Germany."],
      ["Wien und Zürich sind nah an der Grenze.", "Vienna and Zurich are close to the border."],
    ],
    readings: [
      {
        title: "A class list",
        titleDe: "Eine Klassenliste",
        text: "In der Klasse sind viele Länder. Amir kommt aus Ägypten und spricht arabisch. Ines kommt aus Portugal und wohnt jetzt in Hamburg. Ken kommt aus Japan. Sofia kommt aus Griechenland. Tom kommt aus den USA und ist amerikanisch. Die Lehrerin kommt aus Schweden. Europa, Asien, Afrika und Amerika sitzen in einem Raum. Die Heimat ist anders, der Kurs ist gleich.",
        translation: "In the class there are many countries. Amir comes from Egypt and speaks Arabic. Ines comes from Portugal and now lives in Hamburg. Ken comes from Japan. Sofia comes from Greece. Tom comes from the USA and is American. The teacher comes from Sweden. Europe, Asia, Africa and America sit in one room. Home is different, the course is the same.",
        questions: [
          ["Where does Amir come from?", "Egypt", ["Japan", "Egypt", "Sweden", "Canada"]],
          ["Who is American?", "Tom", ["Ken", "Sofia", "Tom", "Ines"]],
          ["Where does Ines live now?", "Hamburg", ["Lisbon", "Berlin", "Hamburg", "Paris"]],
        ],
      },
      {
        title: "Capital cities",
        titleDe: "Hauptstädte",
        text: "Paris ist die Hauptstadt von Frankreich. Die Flagge ist französisch. London ist die Hauptstadt von Großbritannien. Rom ist in Italien, Madrid in Spanien, Amsterdam in den Niederlanden. Wien ist die Hauptstadt von Österreich, Zürich ist nicht die Hauptstadt der Schweiz. Berlin ist die Hauptstadt von Deutschland. Viele Touristen und Touristinnen kommen. Die Grenze ist nur ein Wort auf der Karte.",
        translation: "Paris is the capital of France. The flag is French. London is the capital of Great Britain. Rome is in Italy, Madrid in Spain, Amsterdam in the Netherlands. Vienna is the capital of Austria, Zurich is not the capital of Switzerland. Berlin is the capital of Germany. Many tourists come. The border is only a word on the map.",
        questions: [
          ["What is the capital of Great Britain?", "London", ["Paris", "London", "Berlin", "Wien"]],
          ["Is Zurich a capital?", "No", ["Yes", "No", "Only in summer", "Only for tourists"]],
          ["Who comes to these cities?", "Tourists", ["Only farmers", "Tourists", "Only children", "Nobody"]],
        ],
      },
      {
        title: "A form from abroad",
        titleDe: "Ein Formular aus dem Ausland",
        text: "Name: Lara Costa. Heimat: Brasilien. Jetzt: München. Sprachen: portugiesisch, ein bisschen deutsch. Davor: ein Jahr in Kanada, dann Indien und China. Die Flagge von Brasilien ist grün und gelb. Lara ist Touristin, nicht lange im Ausland. Nächste Woche fährt sie nach Marokko und nach Kroatien. Die Grenze zu Österreich ist nah. Sie ist froh.",
        translation: "Name: Lara Costa. Home country: Brazil. Now: Munich. Languages: Portuguese, a little German. Before: a year in Canada, then India and China. The flag of Brazil is green and yellow. Lara is a tourist, not abroad for long. Next week she goes to Morocco and to Croatia. The border with Austria is close. She is glad.",
        questions: [
          ["What is Lara's home country?", "Brazil", ["Canada", "China", "Brazil", "Morocco"]],
          ["Where is she now?", "Munich", ["Berlin", "Paris", "Munich", "London"]],
          ["Where does she go next week?", "Morocco and Croatia", ["Japan and Finland", "Morocco and Croatia", "Only Ireland", "Only Luxembourg"]],
        ],
      },
    ],
    writings: [
      [
        "Fill four lines: country, city, language, capital.",
        "Fülle vier Zeilen: Land, Stadt, Sprache, Hauptstadt.",
        "Ich komme aus Schweden. Ich wohne in Berlin. Ich spreche schwedisch. Die Hauptstadt von Frankreich ist Paris.",
        ["Use kommen aus", "Use wohnen in", "Name one Hauptstadt"],
      ],
      [
        "Write a four-sentence introduction with a new country.",
        "Schreib eine Vorstellung in vier Sätzen mit einem neuen Land.",
        "Ich heiße Ken. Ich komme aus Japan. Ich bin in München, nicht in Tokio. Meine Heimat ist Japan, jetzt bin ich im Ausland.",
        ["Name a country from this chapter", "Use Heimat or Ausland", "Keep short A1 sentences"],
      ],
    ],
  }),
  packChapter({
    slug: "transport-basics",
    title: "Getting Around",
    titleDe: "Unterwegs",
    blurb: "Simple ways to get around: boats, bikes paths, tickets and getting on and off.",
    skill: "mixed",
    grammar: [
      "einsteigen and aussteigen split: Ich steige in den Bus ein. Ich steige aus.",
      "losfahren and anhalten also split: Wann fährst du los? Bitte nicht anhalten.",
      "Use mit + vehicle you already know, and name new ones: mit der Fähre, mit dem Motorrad.",
    ],
    vocab: [
      ["das Motorrad", "the motorbike", "Motorräder"],
      ["der Roller", "the scooter", "Roller"],
      ["das Boot", "the boat", "Boote"],
      ["das Schiff", "the ship", "Schiffe"],
      ["die Fähre", "the ferry", "Fähren"],
      ["der Lastwagen", "the lorry", "Lastwagen"],
      ["der Kleinbus", "the minibus", "Kleinbusse"],
      ["der Traktor", "the tractor", "Traktoren"],
      ["die Autobahn", "the motorway", "Autobahnen"],
      ["die Landstraße", "the country road", "Landstraßen"],
      ["der Radweg", "the cycle path", "Radwege"],
      ["der Fußgänger", "the pedestrian", "Fußgänger"],
      ["der Fahrer", "the driver (m)", "Fahrer"],
      ["die Fahrerin", "the driver (f)", "Fahrerinnen"],
      ["der Fahrgast", "the passenger", "Fahrgäste"],
      ["der Führerschein", "the driving licence", "Führerscheine"],
      ["einsteigen", "to get on / in"],
      ["aussteigen", "to get off / out"],
      ["der Stau", "the traffic jam", "Staus"],
      ["das Benzin", "petrol"],
      ["der Diesel", "diesel"],
      ["tanken", "to fill up"],
      ["die Rolltreppe", "the escalator", "Rolltreppen"],
      ["der Bahnsteig", "the platform", "Bahnsteige"],
      ["der Fahrschein", "the ticket (travel)", "Fahrscheine"],
      ["die Monatskarte", "the monthly pass", "Monatskarten"],
      ["entwerten", "to validate (a ticket)"],
      ["die Verbindung", "the connection", "Verbindungen"],
      ["die Fahrt", "the ride / journey", "Fahrten"],
      ["dauern", "to last / take (time)"],
      ["der Helm", "the helmet", "Helme"],
      ["der Gurt", "the seatbelt", "Gurte"],
      ["anschnallen", "to buckle up"],
      ["die Fahrbahn", "the roadway", "Fahrbahnen"],
      ["die Baustelle", "the roadworks", "Baustellen"],
      ["losfahren", "to set off"],
      ["anhalten", "to stop (a vehicle)"],
      ["mitfahren", "to ride along"],
      ["der Pendler", "the commuter", "Pendler"],
      ["pendeln", "to commute"],
      ["die Raststätte", "the service station", "Raststätten"],
      ["die Ausfahrt", "the exit (motorway)", "Ausfahrten"],
      ["der Tunnel", "the tunnel", "Tunnel"],
      ["die Seilbahn", "the cable car", "Seilbahnen"],
      ["das Elektroauto", "the electric car", "Elektroautos"],
      ["die Ladestation", "the charging point", "Ladestationen"],
      ["hupen", "to honk"],
      ["der Blinker", "the indicator", "Blinker"],
      ["blinken", "to indicate / flash"],
      ["die Panne", "the breakdown", "Pannen"],
      ["reparieren", "to repair"],
      ["die Werkstatt", "the garage / workshop", "Werkstätten"],
      ["der Kindersitz", "the child seat", "Kindersitze"],
      ["kostenlos", "free of charge"],
      ["die Maut", "the toll"],
      ["der Regionalzug", "the regional train", "Regionalzüge"],
      ["der Reisebus", "the coach", "Reisebusse"],
      ["der Schulbus", "the school bus", "Schulbusse"],
    ],
    phrases: [
      ["Bitte einsteigen!", "Please get on!"],
      ["Hier aussteigen.", "Get off here."],
      ["Hast du einen Fahrschein?", "Do you have a ticket?"],
      ["Bitte den Fahrschein entwerten.", "Please validate the ticket."],
      ["Die Fahrt dauert eine Stunde.", "The journey takes one hour."],
      ["Es gibt Stau auf der Autobahn.", "There is a traffic jam on the motorway."],
      ["Bitte anschnallen.", "Please buckle up."],
      ["Wo ist der Bahnsteig?", "Where is the platform?"],
      ["Ich fahre mit der Fähre.", "I am going by ferry."],
      ["Der Radweg ist frei.", "The cycle path is clear."],
      ["Tanken wir Benzin oder Diesel?", "Are we filling up with petrol or diesel?"],
      ["Die Monatskarte ist nicht kostenlos.", "The monthly pass is not free."],
    ],
    sentences: [
      ["Der Fahrer hat einen Führerschein, die Fahrerin auch.", "The driver has a driving licence, the female driver too."],
      ["Die Fahrgäste steigen in den Reisebus ein.", "The passengers get on the coach."],
      ["Kinder fahren mit dem Schulbus, nicht mit dem Lastwagen.", "Children go by school bus, not by lorry."],
      ["Der Pendler pendelt mit dem Regionalzug.", "The commuter commutes on the regional train."],
      ["Das Motorrad und der Roller brauchen einen Helm.", "The motorbike and the scooter need a helmet."],
      ["Das Boot und das Schiff liegen am Wasser.", "The boat and the ship lie on the water."],
      ["Der Traktor fährt auf der Landstraße, nicht auf der Autobahn.", "The tractor drives on the country road, not on the motorway."],
      ["Fußgänger bleiben nicht auf der Fahrbahn.", "Pedestrians do not stay on the roadway."],
      ["Bei der Baustelle bitte anhalten.", "Please stop at the roadworks."],
      ["Wir fahren los. Bitte nicht hupen.", "We are setting off. Please do not honk."],
      ["Der Blinker muss blinken vor der Ausfahrt.", "The indicator must flash before the exit."],
      ["Das Elektroauto braucht eine Ladestation.", "The electric car needs a charging point."],
      ["Nach der Panne repariert die Werkstatt das Auto.", "After the breakdown the garage repairs the car."],
      ["Im Kindersitz anschnallen. Der Gurt ist wichtig.", "Buckle up in the child seat. The belt is important."],
      ["Die Seilbahn fährt über den Tunnel auf den Berg.", "The cable car goes over the tunnel up the mountain."],
      ["An der Raststätte tanken wir. Die Maut kommt später.", "At the service station we fill up. The toll comes later."],
    ],
    readings: [
      {
        title: "Morning commute",
        titleDe: "Der Morgenweg",
        text: "Nora ist Pendlerin. Sie hat eine Monatskarte. Am Bahnsteig entwertet sie den Fahrschein nicht, die Karte gilt. Die Verbindung mit dem Regionalzug dauert vierzig Minuten. Heute ist Stau auf der Autobahn, also nicht mit dem Kleinbus. Nora steigt ein und sitzt. Ein Fahrgast fragt: Steigen wir an der nächsten Station aus? Ja. Die Fahrt ist ruhig.",
        translation: "Nora is a commuter. She has a monthly pass. On the platform she does not validate the ticket; the pass is valid. The connection with the regional train takes forty minutes. Today there is a jam on the motorway, so not by minibus. Nora gets on and sits. A passenger asks: Do we get off at the next station? Yes. The journey is quiet.",
        questions: [
          ["What ticket does Nora have?", "A monthly pass", ["A ferry ticket", "A monthly pass", "A toll", "A helmet"]],
          ["How long does the connection take?", "Forty minutes", ["Ten minutes", "Forty minutes", "A day", "Two hours"]],
          ["Why not the minibus?", "There is a jam on the motorway", ["No petrol", "There is a jam on the motorway", "No driver", "The ferry is full"]],
        ],
      },
      {
        title: "By water and by road",
        titleDe: "Über Wasser und Straße",
        text: "Wir fahren zuerst mit der Fähre. Das Schiff ist groß, unser Boot ist klein. Dann geht es mit dem Reisebus weiter. Der Fahrer hat den Führerschein dabei. Auf der Landstraße kommt eine Baustelle. Bitte anhalten, dann langsam losfahren. Fußgänger kreuzen. Der Radweg ist frei. Kinder sitzen im Schulbus hinter uns. Keine Panne heute.",
        translation: "We go first by ferry. The ship is big, our boat is small. Then we continue by coach. The driver has the driving licence with him. On the country road there are roadworks. Please stop, then set off slowly. Pedestrians cross. The cycle path is clear. Children sit in the school bus behind us. No breakdown today.",
        questions: [
          ["What do they take first?", "The ferry", ["The tractor", "The ferry", "The cable car", "The lorry"]],
          ["What is on the country road?", "Roadworks", ["A tunnel", "Roadworks", "A charging point", "A toll"]],
          ["Is there a breakdown?", "No", ["Yes", "No", "Only at night", "Only for bikes"]],
        ],
      },
      {
        title: "A short drive",
        titleDe: "Eine kurze Fahrt",
        text: "Papa tankt Benzin, nicht Diesel. Das Elektroauto der Nachbarin steht an der Ladestation. Wir schnallen uns an. Der Kindersitz ist fest, der Gurt auch. Der Helm ist für den Roller, nicht für das Auto. Auf der Autobahn kommt die Raststätte, dann die Ausfahrt. Nicht hupen. Der Blinker blinkt. Die Maut ist nicht kostenlos. In der Werkstatt war gestern eine Panne.",
        translation: "Dad fills up with petrol, not diesel. The neighbour's electric car stands at the charging point. We buckle up. The child seat is firm, the belt too. The helmet is for the scooter, not for the car. On the motorway comes the service station, then the exit. Do not honk. The indicator flashes. The toll is not free. Yesterday there was a breakdown in the garage.",
        questions: [
          ["What does Dad fill up with?", "Petrol", ["Diesel", "Petrol", "Water", "Sand"]],
          ["What is the helmet for?", "The scooter", ["The ship", "The scooter", "The ferry", "The train"]],
          ["Is the toll free?", "No", ["Yes", "No", "Only on Sunday", "Only for children"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about a short journey.",
        "Schreib vier Sätze über eine kurze Fahrt.",
        "Ich steige in den Regionalzug ein. Die Fahrt dauert zwanzig Minuten. Ich habe einen Fahrschein. Am Bahnsteig steige ich aus.",
        ["Use einsteigen or aussteigen", "Name a vehicle from this chapter", "Say how long it lasts"],
      ],
      [
        "Write a safety note for a car ride.",
        "Schreib einen Sicherheitshinweis für eine Autofahrt.",
        "Bitte anschnallen. Der Kindersitz muss fest sein. Nicht hupen. Bei der Baustelle anhalten.",
        ["Use anschnallen", "Name Gurt, Kindersitz or Helm", "Keep commands short"],
      ],
    ],
  }),
  packChapter({
    slug: "free-time-a1",
    title: "Light Free Time",
    titleDe: "Leichte Freizeit",
    blurb: "Simple free-time words: baking, parties, games and seasonal festivals — not the A2 hobby list.",
    skill: "vocab",
    grammar: [
      "gern with new verbs: Ich backe gern. Wir grillen gern.",
      "Festival names often have no article: Weihnachten, Ostern, Silvester.",
      "feiern + occasion: Wir feiern Geburtstag. Sie feiert Fasching.",
    ],
    vocab: [
      ["backen", "to bake"],
      ["grillen", "to barbecue"],
      ["das Picknick", "the picnic", "Picknicks"],
      ["picknicken", "to picnic"],
      ["feiern", "to celebrate"],
      ["die Feier", "the celebration", "Feiern"],
      ["die Party", "the party", "Partys"],
      ["der Geburtstag", "the birthday", "Geburtstage"],
      ["das Geschenk", "the present", "Geschenke"],
      ["schenken", "to give (a present)"],
      ["bummeln", "to stroll / window-shop"],
      ["der Film", "the film", "Filme"],
      ["die Serie", "the series", "Serien"],
      ["schauen", "to watch"],
      ["das Radio", "the radio", "Radios"],
      ["das Lied", "the song", "Lieder"],
      ["zeichnen", "to draw"],
      ["das Brettspiel", "the board game", "Brettspiele"],
      ["das Schach", "chess"],
      ["das Tennis", "tennis"],
      ["der Handball", "handball"],
      ["der Volleyball", "volleyball"],
      ["das Tischtennis", "table tennis"],
      ["die Gymnastik", "keep-fit / gymnastics"],
      ["turnen", "to do gymnastics"],
      ["die Schaukel", "the swing", "Schaukeln"],
      ["die Rutsche", "the slide", "Rutschen"],
      ["das Karussell", "the roundabout (fair)", "Karussells"],
      ["der Jahrmarkt", "the funfair", "Jahrmärkte"],
      ["das Fest", "the festival / party", "Feste"],
      ["der Karneval", "carnival"],
      ["Weihnachten", "Christmas"],
      ["Ostern", "Easter"],
      ["Silvester", "New Year's Eve"],
      ["lustig", "funny"],
      ["der Witz", "the joke", "Witze"],
      ["der Spaß", "the fun"],
      ["die Zeitschrift", "the magazine", "Zeitschriften"],
      ["das Märchen", "the fairy tale", "Märchen"],
      ["das Tagebuch", "the diary", "Tagebücher"],
      ["ausleihen", "to borrow"],
      ["häkeln", "to crochet"],
      ["nähen", "to sew"],
      ["der Grill", "the barbecue", "Grills"],
      ["einladen", "to invite"],
      ["der Stadtbummel", "the stroll through town", "Stadtbummel"],
      ["der Biergarten", "the beer garden", "Biergärten"],
      ["der Weihnachtsmarkt", "the Christmas market", "Weihnachtsmärkte"],
      ["Fastnacht", "carnival (regional)"],
      ["Fasching", "carnival (southern)"],
      ["der Nikolaus", "Saint Nicholas"],
      ["das Hörbuch", "the audiobook", "Hörbücher"],
      ["zuhören", "to listen (to someone)"],
      ["der Kopfhörer", "the headphone", "Kopfhörer"],
      ["das Bilderbuch", "the picture book", "Bilderbücher"],
      ["würfeln", "to roll the dice"],
      ["der Würfel", "the die / cube", "Würfel"],
      ["die Runde", "the round / turn", "Runden"],
    ],
    phrases: [
      ["Hast du am Samstag Zeit?", "Do you have time on Saturday?"],
      ["Wir grillen im Garten.", "We are barbecuing in the garden."],
      ["Ich backe gern Kuchen.", "I like baking cake."],
      ["Komm, wir machen ein Picknick.", "Come on, let's have a picnic."],
      ["Alles Gute zum Geburtstag!", "Happy birthday!"],
      ["Das Geschenk ist für dich.", "The present is for you."],
      ["Wir schauen einen Film.", "We are watching a film."],
      ["Das Lied ist lustig.", "The song is funny."],
      ["Spielen wir eine Runde Schach?", "Shall we play a round of chess?"],
      ["Weihnachten ist im Dezember.", "Christmas is in December."],
      ["Ich lade dich zur Party ein.", "I invite you to the party."],
      ["Der Jahrmarkt macht Spaß.", "The funfair is fun."],
    ],
    sentences: [
      ["Lea backt und näht am Sonntag.", "Lea bakes and sews on Sunday."],
      ["Oma häkelt und hört ein Hörbuch mit Kopfhörern.", "Grandma crochets and listens to an audiobook with headphones."],
      ["Die Kinder sitzen auf der Schaukel und auf der Rutsche.", "The children sit on the swing and on the slide."],
      ["Auf dem Jahrmarkt ist ein Karussell.", "At the funfair there is a roundabout."],
      ["Wir picknicken und bummeln durch die Stadt.", "We picnic and stroll through town."],
      ["Der Stadtbummel endet im Biergarten.", "The stroll through town ends in the beer garden."],
      ["Tom zeichnet in ein Tagebuch, nicht in eine Zeitschrift.", "Tom draws in a diary, not in a magazine."],
      ["Das Märchen und das Bilderbuch sind für Kinder.", "The fairy tale and the picture book are for children."],
      ["Wir leihen das Brettspiel aus und würfeln.", "We borrow the board game and roll the dice."],
      ["Eine Runde Tischtennis, dann Volleyball oder Handball.", "One round of table tennis, then volleyball or handball."],
      ["Tennis und Gymnastik sind am Mittwoch. Danach turnen wir.", "Tennis and keep-fit are on Wednesday. After that we do gymnastics."],
      ["Zu Weihnachten gehen wir auf den Weihnachtsmarkt.", "At Christmas we go to the Christmas market."],
      ["Ostern, Silvester und der Nikolaus sind Feste im Jahr.", "Easter, New Year's Eve and Saint Nicholas are festivals in the year."],
      ["Karneval, Fastnacht und Fasching sind lustig.", "Carnival, Fastnacht and Fasching are funny."],
      ["Sie schenkt ihm ein Radio. Er schaut eine Serie.", "She gives him a radio. He watches a series."],
      ["Die Feier ist eine kleine Party. Der Witz macht Spaß.", "The celebration is a small party. The joke is fun."],
    ],
    readings: [
      {
        title: "A birthday at home",
        titleDe: "Ein Geburtstag zu Hause",
        text: "Heute ist Leas Geburtstag. Die Familie feiert. Papa grillt am Grill. Mama backt einen Kuchen. Mira schenkt ein Bilderbuch und ein Brettspiel. Die Kinder würfeln und spielen eine Runde. Tom erzählt einen Witz. Alle lachen. Der Spaß ist groß. Am Abend schauen sie einen Film. Lea schreibt in ihr Tagebuch: Das war eine schöne Feier.",
        translation: "Today is Lea's birthday. The family is celebrating. Dad barbecues at the grill. Mum bakes a cake. Mira gives a picture book and a board game. The children roll the dice and play a round. Tom tells a joke. Everyone laughs. The fun is great. In the evening they watch a film. Lea writes in her diary: That was a nice celebration.",
        questions: [
          ["What is today?", "Lea's birthday", ["Christmas", "Lea's birthday", "Easter", "New Year's Eve"]],
          ["What does Mira give?", "A picture book and a board game", ["A radio", "A picture book and a board game", "A helmet", "A ticket"]],
          ["What do they watch in the evening?", "A film", ["Tennis", "A film", "Handball", "The news only"]],
        ],
      },
      {
        title: "Sunday outside",
        titleDe: "Sonntag draußen",
        text: "Sonntag machen wir ein Picknick und picknicken im Park. Die Kinder wollen zur Schaukel, zur Rutsche und zum Karussell. Später ist ein kleiner Jahrmarkt. Wir bummeln, dann ein Stadtbummel in den Biergarten. Oma häkelt und hört mit Kopfhörern ein Hörbuch. Opa zeichnet. Es ist lustig. Kein Tennis heute, nur Spaß und ein Lied im Radio.",
        translation: "On Sunday we make a picnic and picnic in the park. The children want the swing, the slide and the roundabout. Later there is a small funfair. We stroll, then a stroll through town to the beer garden. Grandma crochets and listens to an audiobook with headphones. Grandpa draws. It is funny. No tennis today, only fun and a song on the radio.",
        questions: [
          ["What do they do in the park?", "A picnic", ["Chess only", "A picnic", "Sewing", "Handball"]],
          ["What does Grandma listen to?", "An audiobook", ["A series", "An audiobook", "Volleyball", "A joke only"]],
          ["Is there tennis today?", "No", ["Yes", "No", "Only at night", "Only at Christmas"]],
        ],
      },
      {
        title: "The year in festivals",
        titleDe: "Das Jahr in Festen",
        text: "Im Winter kommt der Nikolaus, dann Weihnachten und der Weihnachtsmarkt. An Silvester feiern wir eine Party. Im Frühling ist Ostern. Karneval, Fastnacht und Fasching sind auch Feste. Ben lädt Freunde ein. Sie schauen eine Serie, leihen ein Märchen aus und nähen kleine Geschenke. Gymnastik und turnen sind für die Woche. Das Fest soll lustig sein.",
        translation: "In winter Saint Nicholas comes, then Christmas and the Christmas market. On New Year's Eve we have a party. In spring it is Easter. Carnival, Fastnacht and Fasching are festivals too. Ben invites friends. They watch a series, borrow a fairy tale and sew small presents. Keep-fit and gymnastics are for the week. The festival should be funny.",
        questions: [
          ["When is the Christmas market?", "In winter, at Christmas", ["At Easter", "In winter, at Christmas", "Only in summer", "At tennis"]],
          ["What does Ben do?", "He invites friends", ["He sells tickets", "He invites friends", "He repairs a car", "He tanks petrol"]],
          ["What do they sew?", "Small presents", ["A cake", "Small presents", "A helmet", "A flag"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about a birthday or a picnic.",
        "Schreib vier Sätze über einen Geburtstag oder ein Picknick.",
        "Heute ist mein Geburtstag. Wir grillen und backen. Ich bekomme ein Geschenk. Am Abend schauen wir einen Film.",
        ["Use feiern, backen or grillen", "Name a Geschenk or Party", "Keep the present tense"],
      ],
      [
        "Write which festivals you like in the year.",
        "Schreib, welche Feste du im Jahr magst.",
        "Ich mag Weihnachten und den Weihnachtsmarkt. Ostern ist auch schön. An Silvester feiern wir. Karneval ist lustig.",
        ["Name two festivals", "Use feiern or lustig", "No long sentences"],
      ],
    ],
  }),
  packChapter({
    slug: "question-words-verbs",
    title: "Question Words & Everyday Verbs",
    titleDe: "Fragewörter und Alltagsverben",
    blurb: "Ask with was, wo, wann and wie, and use high-frequency verbs you still need at A1.",
    skill: "grammar",
    grammar: [
      "Question words take position 1: Wo wohnst du? Wann beginnt der Kurs?",
      "The verb stays in position 2: Was sagst du? Wie lange dauert das?",
      "woher = from where, wohin = to where. warum you already know; wieso is close in meaning.",
    ],
    vocab: [
      ["was", "what"],
      ["wo", "where"],
      ["wann", "when"],
      ["wie", "how"],
      ["woher", "where from"],
      ["wohin", "where to"],
      ["wen", "whom (accusative)"],
      ["wem", "to whom (dative)"],
      ["welcher", "which (m)"],
      ["welche", "which (f/pl)"],
      ["welches", "which (n)"],
      ["wieso", "why"],
      ["wozu", "what for"],
      ["wie viel", "how much"],
      ["wie viele", "how many"],
      ["wie oft", "how often"],
      ["wie lange", "how long"],
      ["wie spät", "how late / what time"],
      ["wessen", "whose"],
      ["was für", "what kind of"],
      ["sagen", "to say"],
      ["glauben", "to believe"],
      ["meinen", "to think / mean"],
      ["wissen", "to know (a fact)"],
      ["kennen", "to know (a person/place)"],
      ["sitzen", "to sit"],
      ["liegen", "to lie / be lying"],
      ["stehen", "to stand"],
      ["öffnen", "to open"],
      ["schließen", "to close"],
      ["legen", "to put (lying)"],
      ["stellen", "to put (standing)"],
      ["holen", "to fetch"],
      ["geben", "to give"],
      ["beginnen", "to begin"],
      ["aufhören", "to stop"],
      ["ansehen", "to look at"],
      ["anschauen", "to look at / watch"],
      ["rufen", "to call / shout"],
      ["winken", "to wave"],
      ["heben", "to lift"],
      ["fallen", "to fall"],
      ["rennen", "to run"],
      ["springen", "to jump"],
      ["schneiden", "to cut"],
      ["drücken", "to press"],
      ["drehen", "to turn"],
      ["einschalten", "to switch on"],
      ["ausschalten", "to switch off"],
      ["aufmachen", "to open (colloquial)"],
      ["zumachen", "to close (colloquial)"],
      ["gratulieren", "to congratulate"],
      ["wünschen", "to wish"],
      ["träumen", "to dream"],
      ["übersetzen", "to translate"],
      ["studieren", "to study (at university)"],
      ["benutzen", "to use"],
      ["verlassen", "to leave"],
    ],
    phrases: [
      ["Was ist das?", "What is that?"],
      ["Wo liegt das Buch?", "Where is the book lying?"],
      ["Wann beginnt der Kurs?", "When does the course begin?"],
      ["Wie spät ist es?", "What time is it?"],
      ["Woher kommst du, wohin gehst du?", "Where are you from, where are you going?"],
      ["Wen kennst du hier?", "Whom do you know here?"],
      ["Wem gibst du das?", "Whom are you giving that to?"],
      ["Welcher Tag ist heute?", "Which day is it today?"],
      ["Wie viel kostet das, wie viele Personen?", "How much does that cost, how many people?"],
      ["Wie oft und wie lange lernst du?", "How often and how long do you study?"],
      ["Wieso sagst du das?", "Why are you saying that?"],
      ["Was für ein Stift ist das?", "What kind of pen is that?"],
    ],
    sentences: [
      ["Was meinst du? Ich glaube, das ist richtig.", "What do you think? I believe that is right."],
      ["Ich weiß den Namen nicht. Kennst du ihn?", "I do not know the name. Do you know him?"],
      ["Sie sitzt, er steht, das Heft liegt auf dem Tisch.", "She is sitting, he is standing, the notebook is lying on the table."],
      ["Bitte öffnen Sie die Tür. Danach schließen Sie das Fenster.", "Please open the door. After that close the window."],
      ["Leg das Buch hin und stell die Tasse auf den Tisch.", "Put the book down and put the cup on the table."],
      ["Hol bitte Wasser und gib es Mira.", "Please fetch water and give it to Mira."],
      ["Der Film beginnt um acht. Wann hört er auf?", "The film begins at eight. When does it stop?"],
      ["Wir sehen uns die Karte an und schauen den Plan an.", "We look at the map and look at the plan."],
      ["Ruf laut und winke an der Tür.", "Call loudly and wave at the door."],
      ["Heb die Tasche. Fall nicht. Renn nicht. Spring nicht.", "Lift the bag. Do not fall. Do not run. Do not jump."],
      ["Schneide das Brot. Drücke den Knopf. Drehe den Schlüssel.", "Cut the bread. Press the button. Turn the key."],
      ["Schalt das Licht ein. Schalt das Radio aus.", "Switch the light on. Switch the radio off."],
      ["Mach das Fenster auf. Mach die Tür zu.", "Open the window. Close the door."],
      ["Wir gratulieren dir und wünschen dir Glück.", "We congratulate you and wish you luck."],
      ["Ich träume von der Prüfung. Übersetze den Satz.", "I dream about the exam. Translate the sentence."],
      ["Sie studiert in Berlin. Benutz das Wörterbuch. Verlass den Raum nicht.", "She studies in Berlin. Use the dictionary. Do not leave the room."],
    ],
    readings: [
      {
        title: "Questions on the board",
        titleDe: "Fragen an der Tafel",
        text: "Die Lehrerin schreibt Fragen. Was ist das? Wo liegt der Schlüssel? Wann beginnt die Stunde? Wie spät ist es? Woher kommt Omar, wohin geht Lea? Wen rufst du? Wem gibst du das Heft? Welcher Stift, welche Tasche, welches Buch? Die Klasse antwortet. Tom meint: Ich weiß es nicht. Mira sagt: Ich kenne die Antwort. Wieso ist das leicht? Weil die Fragen kurz sind.",
        translation: "The teacher writes questions. What is that? Where is the key lying? When does the lesson begin? What time is it? Where is Omar from, where is Lea going? Whom are you calling? Whom are you giving the notebook to? Which pen, which bag, which book? The class answers. Tom thinks: I do not know. Mira says: I know the answer. Why is that easy? Because the questions are short.",
        questions: [
          ["What does the teacher write?", "Questions", ["Tickets", "Questions", "Flags", "Songs"]],
          ["Who knows the answer?", "Mira", ["Tom", "Omar", "Mira", "Nobody"]],
          ["Why is it easy?", "The questions are short", ["It is a film", "The questions are short", "They leave the room", "They run"]],
        ],
      },
      {
        title: "In the kitchen",
        titleDe: "In der Küche",
        text: "Papa öffnet den Kühlschrank und macht die Tür auf. Er holt Käse und legt ihn auf den Teller. Mama stellt das Glas hin und gibt Wasser. Wie viel Wasser? Ein bisschen. Wie lange dauert das Essen? Zwanzig Minuten. Die Kinder sitzen. Das Brot liegt da. Bitte nicht rennen und nicht springen. Schalt das Radio ein. Nach dem Essen schaltet Papa es aus und schließt das Fenster.",
        translation: "Dad opens the fridge and opens the door. He fetches cheese and puts it on the plate. Mum puts the glass down and gives water. How much water? A little. How long does the meal take? Twenty minutes. The children sit. The bread is lying there. Please do not run and do not jump. Switch the radio on. After the meal Dad switches it off and closes the window.",
        questions: [
          ["What does Dad fetch?", "Cheese", ["A helmet", "Cheese", "A ticket", "A flag"]],
          ["How long does the meal take?", "Twenty minutes", ["Two days", "Twenty minutes", "One second", "All night"]],
          ["What happens to the radio after the meal?", "Dad switches it off", ["The children jump", "Dad switches it off", "They leave the city", "They study"]],
        ],
      },
      {
        title: "A short goodbye",
        titleDe: "Ein kurzer Abschied",
        text: "Wie oft kommst du? Einmal in der Woche. Wessen Tasche ist das? Meine. Was für ein Kurs ist das? Ein Deutschkurs. Wozu lernst du? Ich möchte studieren. Ben winkt und ruft: Bis bald! Nora übersetzt den Satz für Ken. Sie gratuliert ihm zum Test und wünscht ihm Glück. Dann verlassen sie den Raum. Draußen beginnt der Regen. Sie hören auf zu reden und rennen nicht. Sie gehen.",
        translation: "How often do you come? Once a week. Whose bag is that? Mine. What kind of course is that? A German course. What do you learn for? I want to study. Ben waves and calls: See you soon! Nora translates the sentence for Ken. She congratulates him on the test and wishes him luck. Then they leave the room. Outside the rain begins. They stop talking and do not run. They walk.",
        questions: [
          ["How often does the person come?", "Once a week", ["Every hour", "Once a week", "Never", "Only at Christmas"]],
          ["What does Nora do with the sentence?", "She translates it", ["She cuts it", "She translates it", "She switches it off", "She bakes it"]],
          ["What do they do at the end?", "They leave the room", ["They jump", "They leave the room", "They open a shop", "They honk"]],
        ],
      },
    ],
    writings: [
      [
        "Write five short questions with different question words.",
        "Schreib fünf kurze Fragen mit verschiedenen Fragewörtern.",
        "Was ist das? Wo wohnst du? Wann beginnt der Kurs? Wie spät ist es? Woher kommst du?",
        ["Start every line with a question word", "Use was, wo, wann or wie at least once", "Keep the verb in position 2"],
      ],
      [
        "Write four commands or sentences with new verbs.",
        "Schreib vier Aufforderungen oder Sätze mit neuen Verben.",
        "Bitte öffne die Tür. Hol das Buch. Sag den Namen. Schalt das Licht ein.",
        ["Use two verbs from this chapter", "Keep sentences short", "You can use bitte"],
      ],
    ],
  }),
];
