import { phrase, sentence, vocab, type ChapterExtra } from "@/content/helpers";

export const a2Expand: Record<string, ChapterExtra> = {
  shopping: {
    vocab: [
      vocab("die Bäckerei", "the bakery", undefined, "Bäckereien"),
      vocab("die Metzgerei", "the butcher's", undefined, "Metzgereien"),
      vocab("der Discounter", "the discount supermarket", undefined, "Discounter"),
      vocab("das Schaufenster", "the shop window", undefined, "Schaufenster"),
      vocab("die Ware", "the goods", undefined, "Waren"),
      vocab("der Rabatt", "the discount", undefined, "Rabatte"),
      vocab("der Gutschein", "the voucher", undefined, "Gutscheine"),
      vocab("die Mehrwertsteuer", "VAT"),
      vocab("das Wechselgeld", "the change"),
      vocab("der Cent", "the cent", undefined, "Cents"),
      vocab("wiegen", "to weigh"),
      vocab("das Kilo", "the kilo", undefined, "Kilos"),
      vocab("das Gramm", "the gram", undefined, "Gramm"),
      vocab("die Packung", "the pack", undefined, "Packungen"),
      vocab("die Dose", "the tin", undefined, "Dosen"),
      vocab("die Flasche", "the bottle", undefined, "Flaschen"),
      vocab("frisch", "fresh"),
      vocab("abgelaufen", "expired"),
      vocab("bio", "organic"),
      vocab("regional", "local / regional"),
      vocab("der Korb", "the basket", undefined, "Körbe"),
      vocab("einpacken", "to wrap / pack"),
      vocab("ausverkauft", "sold out"),
      vocab("der Online-Shop", "the online shop", undefined, "Online-Shops"),
      vocab("der Lieferdienst", "the delivery service", undefined, "Lieferdienste"),
      vocab("die Lieferung", "the delivery", undefined, "Lieferungen"),
      vocab("abholen", "to pick up"),
      vocab("der Einkaufszettel", "the shopping list", undefined, "Einkaufszettel"),
      vocab("die Theke", "the counter", undefined, "Theken"),
      vocab("der Pfand", "the deposit"),
      vocab("die Selbstbedienung", "self-service"),
      vocab("scannen", "to scan"),
    ],
    phrases: [
      phrase("Gibt es Rabatt mit dem Gutschein?", "Is there a discount with the voucher?"),
      phrase("Das Brot ist frisch aus der Bäckerei.", "The bread is fresh from the bakery."),
      phrase("Bitte ein Kilo an der Theke.", "One kilo at the counter, please."),
      phrase("Die Ware ist ausverkauft.", "The item is sold out."),
      phrase("Pfand für die Flasche.", "Deposit for the bottle."),
      phrase("Lieferung oder abholen?", "Delivery or pick up?"),
    ],
    sentences: [
      sentence("Ich wiege das Obst in Gramm.", "I weigh the fruit in grams."),
      sentence("Der Discounter hat Selbstbedienung.", "The discounter has self-service."),
      sentence("Der Einkaufszettel liegt im Korb.", "The shopping list is in the basket."),
      sentence("Bio und regional ist teurer.", "Organic and local is more expensive."),
      sentence("Das Mindesthaltbarkeitsdatum ist abgelaufen.", "The best-before date has expired."),
      sentence("Im Online-Shop scannen wir den Code.", "In the online shop we scan the code."),
    ],
  },
  "city-directions": {
    vocab: [
      vocab("der Kreisverkehr", "the roundabout", undefined, "Kreisverkehre"),
      vocab("die Einbahnstraße", "the one-way street", undefined, "Einbahnstraßen"),
      vocab("die Unterführung", "the underpass", undefined, "Unterführungen"),
      vocab("der Zebrastreifen", "the zebra crossing", undefined, "Zebrastreifen"),
      vocab("der Hafen", "the harbour", undefined, "Häfen"),
      vocab("der Fluss", "the river", undefined, "Flüsse"),
      vocab("die Insel", "the island", undefined, "Inseln"),
      vocab("das Viertel", "the district", undefined, "Viertel"),
      vocab("der Vorort", "the suburb", undefined, "Vororte"),
      vocab("die Innenstadt", "the city centre"),
      vocab("nördlich", "north of / northern"),
      vocab("südlich", "south of / southern"),
      vocab("östlich", "east of / eastern"),
      vocab("westlich", "west of / western"),
      vocab("die Entfernung", "the distance", undefined, "Entfernungen"),
      vocab("der Kilometer", "the kilometre", undefined, "Kilometer"),
      vocab("der Meter", "the metre", undefined, "Meter"),
      vocab("der Block", "the block", undefined, "Blöcke"),
      vocab("vorbeifahren", "to drive past"),
      vocab("stehen bleiben", "to stop / stay standing"),
      vocab("sich verlaufen", "to get lost"),
      vocab("der Treffpunkt", "the meeting point", undefined, "Treffpunkte"),
      vocab("das Wahrzeichen", "the landmark", undefined, "Wahrzeichen"),
      vocab("die Touristeninformation", "tourist information"),
      vocab("der Stadtführer", "the city guide", undefined, "Stadtführer"),
      vocab("der Dom", "the cathedral", undefined, "Dome"),
      vocab("das Schloss", "the palace / castle", undefined, "Schlösser"),
      vocab("die Altstadt", "the old town", undefined, "Altstädte"),
      vocab("die Fußgängerbrücke", "the pedestrian bridge", undefined, "Fußgängerbrücken"),
      vocab("abkürzen", "to take a shortcut"),
      vocab("die Umleitung", "the diversion", undefined, "Umleitungen"),
      vocab("das Navi", "the satnav", undefined, "Navis"),
    ],
    phrases: [
      phrase("Am Kreisverkehr zweite Ausfahrt.", "At the roundabout, second exit."),
      phrase("Die Altstadt ist fußläufig.", "The old town is within walking distance."),
      phrase("Nicht in die Einbahnstraße.", "Do not enter the one-way street."),
      phrase("Treffpunkt am Dom.", "Meeting point at the cathedral."),
      phrase("Zwei Kilometer südlich vom Hafen.", "Two kilometres south of the harbour."),
      phrase("Bei Umleitung der Umleitung folgen.", "If diverted, follow the diversion."),
    ],
    sentences: [
      sentence("Das Schloss ist das Wahrzeichen.", "The palace is the landmark."),
      sentence("Wir laufen über den Zebrastreifen.", "We walk across the zebra crossing."),
      sentence("Im Vorort ist die Entfernung größer.", "In the suburb the distance is greater."),
      sentence("Die Touristeninformation gibt Stadtpläne.", "Tourist information gives out city maps."),
      sentence("Ich habe mich in der Unterführung verlaufen.", "I got lost in the underpass."),
      sentence("Die Insel liegt östlich vom Fluss.", "The island lies east of the river."),
    ],
  },
  weather: {
    vocab: [
      vocab("das Gewitter", "the thunderstorm", undefined, "Gewitter"),
      vocab("der Blitz", "the lightning", undefined, "Blitze"),
      vocab("der Donner", "the thunder"),
      vocab("der Nebel", "the fog"),
      vocab("der Hagel", "the hail"),
      vocab("der Sturm", "the storm", undefined, "Stürme"),
      vocab("die Hitze", "the heat"),
      vocab("die Kälte", "the cold"),
      vocab("schwül", "humid / muggy"),
      vocab("neblig", "foggy"),
      vocab("stürmisch", "stormy"),
      vocab("bewölkt", "cloudy"),
      vocab("heiter", "fair / bright"),
      vocab("der Grad Celsius", "degrees Celsius"),
      vocab("der Niederschlag", "the precipitation"),
      vocab("die Wettervorhersage", "the weather forecast", undefined, "Wettervorhersagen"),
      vocab("der Wetterbericht", "the weather report", undefined, "Wetterberichte"),
      vocab("blitzen", "to flash (lightning)"),
      vocab("donnern", "to thunder"),
      vocab("wehen", "to blow (wind)"),
      vocab("tauen", "to thaw"),
      vocab("frieren", "to freeze / feel cold"),
      vocab("schwitzen", "to sweat"),
      vocab("der Frost", "the frost"),
      vocab("die Eisglätte", "black ice"),
      vocab("die Unwetterwarnung", "the severe weather warning", undefined, "Unwetterwarnungen"),
      vocab("das Hoch", "the high (pressure)"),
      vocab("das Tief", "the low (pressure)"),
      vocab("der Sonnenuntergang", "the sunset", undefined, "Sonnenuntergänge"),
      vocab("der Sonnenaufgang", "the sunrise", undefined, "Sonnenaufgänge"),
      vocab("die Jahreszeit", "the season", undefined, "Jahreszeiten"),
      vocab("unbeständig", "changeable"),
    ],
    phrases: [
      phrase("Heute ist ein Tief über der Stadt.", "Today there is a low over the city."),
      phrase("Achtung, Unwetterwarnung!", "Warning, severe weather alert!"),
      phrase("Es blitzt und donnert.", "There is lightning and thunder."),
      phrase("Bei Eisglätte langsam fahren.", "Drive slowly on black ice."),
      phrase("Die Vorhersage sagt Gewitter.", "The forecast says thunderstorms."),
      phrase("Morgens Nebel, mittags heiter.", "Fog in the morning, fair at midday."),
    ],
    sentences: [
      sentence("Im Sturm weht der Wind stark.", "In the storm the wind blows hard."),
      sentence("Bei Hitze schwitzen wir.", "In the heat we sweat."),
      sentence("Der Frost kommt im Winter.", "The frost comes in winter."),
      sentence("Die Jahreszeit ist unbeständig.", "The season is changeable."),
      sentence("Nach dem Regen taut der Schnee.", "After the rain the snow thaws."),
      sentence("Der Sonnenuntergang ist schön.", "The sunset is beautiful."),
    ],
  },
  clothes: {
    vocab: [
      vocab("die Unterwäsche", "the underwear"),
      vocab("der Schal", "the scarf", undefined, "Schals"),
      vocab("die Handschuhe", "the gloves"),
      vocab("der Gürtel", "the belt", undefined, "Gürtel"),
      vocab("die Krawatte", "the tie", undefined, "Krawatten"),
      vocab("das Kostüm", "the suit (women's) / costume", undefined, "Kostüme"),
      vocab("der Anzug", "the suit", undefined, "Anzüge"),
      vocab("die Jeans", "the jeans"),
      vocab("der Pyjama", "the pyjamas", undefined, "Pyjamas"),
      vocab("die Sandalen", "the sandals"),
      vocab("die Stiefel", "the boots"),
      vocab("die Turnschuhe", "the trainers"),
      vocab("der Slipper", "the slip-on", undefined, "Slipper"),
      vocab("anprobieren", "to try on"),
      vocab("die Umkleide", "the changing room", undefined, "Umkleiden"),
      vocab("der Kleiderbügel", "the hanger", undefined, "Kleiderbügel"),
      vocab("bügeln", "to iron"),
      vocab("waschen", "to wash"),
      vocab("die Wäsche", "the laundry"),
      vocab("die Baumwolle", "cotton"),
      vocab("die Wolle", "wool"),
      vocab("das Leder", "leather"),
      vocab("der Reißverschluss", "the zip", undefined, "Reißverschlüsse"),
      vocab("das Muster", "the pattern", undefined, "Muster"),
      vocab("flicken", "to mend"),
      vocab("wechseln", "to change (clothes)"),
      vocab("schick", "smart / chic"),
      vocab("lässig", "casual"),
      vocab("die Kombination", "the outfit combination", undefined, "Kombinationen"),
      vocab("der Kapuzenpullover", "the hoodie", undefined, "Kapuzenpullover"),
      vocab("die Leggings", "the leggings"),
    ],
    phrases: [
      phrase("Darf ich das anprobieren?", "May I try that on?"),
      phrase("Die Umkleide ist hinten.", "The changing room is at the back."),
      phrase("Wolle nicht bei Hitze tragen.", "Do not wear wool in the heat."),
      phrase("Bitte die Wäsche bügeln.", "Please iron the laundry."),
      phrase("Schal und Handschuhe im Winter.", "Scarf and gloves in winter."),
      phrase("Ein lässiger Anzug.", "A casual suit."),
    ],
    sentences: [
      sentence("Die Jeans hat einen Reißverschluss.", "The jeans have a zip."),
      sentence("Ich ziehe den Pyjama an.", "I put on the pyjamas."),
      sentence("Die Stiefel sind aus Leder.", "The boots are leather."),
      sentence("Das Kostüm hängt am Kleiderbügel.", "The suit is on the hanger."),
      sentence("Turnschuhe sind bequem.", "Trainers are comfortable."),
      sentence("Die Krawatte ist schick.", "The tie is smart."),
    ],
  },
  hobbies: {
    vocab: [
      vocab("sammeln", "to collect"),
      vocab("stricken", "to knit"),
      vocab("basteln", "to do crafts"),
      vocab("joggen", "to jog"),
      vocab("radfahren", "to cycle"),
      vocab("skifahren", "to ski"),
      vocab("klettern", "to climb"),
      vocab("angeln", "to fish"),
      vocab("der Chor", "the choir", undefined, "Chöre"),
      vocab("das Instrument", "the instrument", undefined, "Instrumente"),
      vocab("die Gitarre", "the guitar", undefined, "Gitarren"),
      vocab("das Klavier", "the piano", undefined, "Klaviere"),
      vocab("die Ausstellung", "the exhibition", undefined, "Ausstellungen"),
      vocab("das Theater", "the theatre", undefined, "Theater"),
      vocab("das Festival", "the festival", undefined, "Festivals"),
      vocab("die Mitgliedschaft", "the membership", undefined, "Mitgliedschaften"),
      vocab("das Abonnement", "the subscription", undefined, "Abonnements"),
      vocab("reservieren", "to reserve"),
      vocab("die Reihe", "the row", undefined, "Reihen"),
      vocab("die Leidenschaft", "the passion", undefined, "Leidenschaften"),
      vocab("das Interesse", "the interest", undefined, "Interessen"),
      vocab("talentiert", "talented"),
      vocab("ungeübt", "unpractised"),
      vocab("die Anfängerin", "the beginner (f)", undefined, "Anfängerinnen"),
      vocab("der Anfänger", "the beginner (m)", undefined, "Anfänger"),
      vocab("das Training", "the training", undefined, "Trainings"),
      vocab("die Mannschaft", "the team", undefined, "Mannschaften"),
      vocab("gewinnen", "to win"),
      vocab("das Unentschieden", "the draw", undefined, "Unentschieden"),
      vocab("die Bühne", "the stage", undefined, "Bühnen"),
      vocab("applaudieren", "to applaud"),
    ],
    phrases: [
      phrase("Ich spiele Gitarre, nicht im Chor.", "I play guitar, not in the choir."),
      phrase("Hast du ein Abonnement fürs Theater?", "Do you have a theatre subscription?"),
      phrase("Das Training ist dienstags.", "Training is on Tuesdays."),
      phrase("Wir haben unentschieden gespielt.", "We played a draw."),
      phrase("Reservieren Sie Reihe drei.", "Reserve row three."),
      phrase("Klettern ist meine Leidenschaft.", "Climbing is my passion."),
    ],
    sentences: [
      sentence("Sie strickt und sammelt Briefmarken.", "She knits and collects stamps."),
      sentence("Am Festival spielt die Mannschaft nicht, die Band.", "At the festival the team does not play, the band does."),
      sentence("Der Anfänger ist noch ungeübt.", "The beginner is still unpractised."),
      sentence("Joggen und radfahren machen Spaß.", "Jogging and cycling are fun."),
      sentence("Die Ausstellung ist spannend.", "The exhibition is exciting."),
      sentence("Skifahren im Winter, angeln im Sommer.", "Skiing in winter, fishing in summer."),
    ],
  },
  travel: {
    vocab: [
      vocab("der Reisepass", "the passport", undefined, "Reisepässe"),
      vocab("das Visum", "the visa", undefined, "Visa"),
      vocab("die Kontrolle", "the check", undefined, "Kontrollen"),
      vocab("das Gate", "the gate", undefined, "Gates"),
      vocab("das Terminal", "the terminal", undefined, "Terminals"),
      vocab("einchecken", "to check in"),
      vocab("das Gepäck", "the luggage"),
      vocab("aufgeben", "to check in (bags)"),
      vocab("das Handgepäck", "the hand luggage"),
      vocab("die Sitzplatzreservierung", "the seat reservation", undefined, "Sitzplatzreservierungen"),
      vocab("der Abflug", "the departure (flight)", undefined, "Abflüge"),
      vocab("die Landung", "the landing", undefined, "Landungen"),
      vocab("der Anschluss", "the connection", undefined, "Anschlüsse"),
      vocab("die Übernachtung", "the overnight stay", undefined, "Übernachtungen"),
      vocab("die Frühstückspension", "the B&B", undefined, "Frühstückspensionen"),
      vocab("die Ferienwohnung", "the holiday apartment", undefined, "Ferienwohnungen"),
      vocab("der Campingplatz", "the campsite", undefined, "Campingplätze"),
      vocab("das Zelt", "the tent", undefined, "Zelte"),
      vocab("auschecken", "to check out"),
      vocab("die Halbpension", "half board"),
      vocab("die Vollpension", "full board"),
      vocab("der Reiseführer", "the guidebook / guide", undefined, "Reiseführer"),
      vocab("die Sonnencreme", "the sun cream"),
      vocab("der Adapter", "the adapter", undefined, "Adapter"),
      vocab("die Zeitzone", "the time zone", undefined, "Zeitzonen"),
      vocab("der Jetlag", "jet lag"),
      vocab("stornieren", "to cancel"),
      vocab("die Bordkarte", "the boarding pass", undefined, "Bordkarten"),
      vocab("der Zoll", "customs"),
      vocab("duty-free", "duty-free"),
      vocab("die Sicherheitskontrolle", "security check", undefined, "Sicherheitskontrollen"),
      vocab("die Verspätungsmeldung", "the delay announcement", undefined, "Verspätungsmeldungen"),
    ],
    phrases: [
      phrase("Einchecken am Terminal zwei.", "Check in at terminal two."),
      phrase("Handgepäck unter den Sitz.", "Hand luggage under the seat."),
      phrase("Haben Sie eine Sitzplatzreservierung?", "Do you have a seat reservation?"),
      phrase("Wir stornieren die Übernachtung.", "We cancel the overnight stay."),
      phrase("Vollpension oder Halbpension?", "Full board or half board?"),
      phrase("Der Anschluss ist knapp.", "The connection is tight."),
    ],
    sentences: [
      sentence("Das Visum steht im Reisepass.", "The visa is in the passport."),
      sentence("Nach der Landung holen wir das Gepäck.", "After landing we collect the luggage."),
      sentence("Die Ferienwohnung liegt in der Stadt.", "The holiday apartment is in town."),
      sentence("Der Adapter passt, der Stecker auch.", "The adapter fits, and so does the plug."),
      sentence("Sonnencreme nicht im Handgepäck vergessen.", "Do not forget sun cream in the hand luggage."),
      sentence("Wir zelten zwei Nächte.", "We camp for two nights."),
    ],
  },
  health: {
    vocab: [
      vocab("die Erkältung", "the cold", undefined, "Erkältungen"),
      vocab("die Grippe", "the flu"),
      vocab("die Allergie", "the allergy", undefined, "Allergien"),
      vocab("der Ausschlag", "the rash", undefined, "Ausschläge"),
      vocab("der Verband", "the bandage", undefined, "Verbände"),
      vocab("das Pflaster", "the plaster", undefined, "Pflaster"),
      vocab("die Spritze", "the injection", undefined, "Spritzen"),
      vocab("impfen", "to vaccinate"),
      vocab("die Impfung", "the vaccination", undefined, "Impfungen"),
      vocab("die Untersuchung", "the examination", undefined, "Untersuchungen"),
      vocab("die Diagnose", "the diagnosis", undefined, "Diagnosen"),
      vocab("die Behandlung", "the treatment", undefined, "Behandlungen"),
      vocab("die Praxis", "the surgery / practice", undefined, "Praxen"),
      vocab("die Sprechstunde", "the consulting hour", undefined, "Sprechstunden"),
      vocab("die Notaufnahme", "A&E / ER"),
      vocab("der Krankenwagen", "the ambulance", undefined, "Krankenwagen"),
      vocab("die Krankmeldung", "the sick note", undefined, "Krankmeldungen"),
      vocab("sich krankmelden", "to call in sick"),
      vocab("fieberhaft", "feverish"),
      vocab("schwindelig", "dizzy"),
      vocab("übel", "nauseous"),
      vocab("die Tropfen", "the drops"),
      vocab("die Salbe", "the ointment", undefined, "Salben"),
      vocab("das Thermometer", "the thermometer", undefined, "Thermometer"),
      vocab("der Blutdruck", "the blood pressure"),
      vocab("die Diät", "the diet", undefined, "Diäten"),
      vocab("sich ausruhen", "to rest"),
      vocab("genesen", "to recover"),
      vocab("die Vorsorge", "prevention / check-up"),
      vocab("das Symptom", "the symptom", undefined, "Symptome"),
      vocab("die Verletzung", "the injury", undefined, "Verletzungen"),
      vocab("brechen", "to break / vomit"),
    ],
    phrases: [
      phrase("Ich möchte eine Sprechstunde.", "I would like an appointment at the surgery."),
      phrase("Haben Sie Fieber oder Ausschlag?", "Do you have a fever or a rash?"),
      phrase("Die Krankmeldung gilt drei Tage.", "The sick note is valid for three days."),
      phrase("Bitte den Blutdruck messen.", "Please measure the blood pressure."),
      phrase("Nach der Impfung ausruhen.", "Rest after the vaccination."),
      phrase("Bei Übelkeit in die Notaufnahme.", "If nauseous, go to A&E."),
    ],
    sentences: [
      sentence("Die Erkältung ist nicht die Grippe.", "The cold is not the flu."),
      sentence("Ein Pflaster reicht, kein Verband.", "A plaster is enough, no bandage."),
      sentence("Die Diagnose kommt nach der Untersuchung.", "The diagnosis comes after the examination."),
      sentence("Der Krankenwagen fährt zur Notaufnahme.", "The ambulance drives to A&E."),
      sentence("Salbe und Tropfen aus der Apotheke.", "Ointment and drops from the pharmacy."),
      sentence("Die Vorsorge ist wichtig.", "Prevention is important."),
    ],
  },
  work: {
    vocab: [
      vocab("die Abteilung", "the department", undefined, "Abteilungen"),
      vocab("die Besprechung", "the meeting", undefined, "Besprechungen"),
      vocab("der Terminplan", "the schedule", undefined, "Terminpläne"),
      vocab("die Frist", "the deadline", undefined, "Fristen"),
      vocab("das Projekt", "the project", undefined, "Projekte"),
      vocab("die Verantwortung", "the responsibility"),
      vocab("die Beförderung", "the promotion", undefined, "Beförderungen"),
      vocab("das Praktikum", "the internship", undefined, "Praktika"),
      vocab("der Azubi", "the apprentice", undefined, "Azubis"),
      vocab("die Ausbildung", "the vocational training", undefined, "Ausbildungen"),
      vocab("der Vertrag", "the contract", undefined, "Verträge"),
      vocab("die Probezeit", "the probation period", undefined, "Probezeiten"),
      vocab("die Kündigung", "the notice / dismissal", undefined, "Kündigungen"),
      vocab("das Zeugnis", "the reference / report", undefined, "Zeugnisse"),
      vocab("die Weiterbildung", "further training"),
      vocab("das Homeoffice", "working from home"),
      vocab("die Kernzeit", "core working hours"),
      vocab("die Gleitzeit", "flexitime"),
      vocab("das Meeting", "the meeting", undefined, "Meetings"),
      vocab("die To-do-Liste", "the to-do list", undefined, "To-do-Listen"),
      vocab("erledigen", "to get done"),
      vocab("vertreten", "to cover / represent"),
      vocab("die Vertretung", "the cover / deputy", undefined, "Vertretungen"),
      vocab("die Steuer", "the tax", undefined, "Steuern"),
      vocab("die Sozialversicherung", "social insurance"),
      vocab("der Betriebsrat", "the works council"),
      vocab("kollegial", "collegial"),
      vocab("zuverlässig", "reliable"),
      vocab("belastbar", "resilient"),
      vocab("die Überstunde", "the overtime hour", undefined, "Überstunden"),
      vocab("das Bruttogehalt", "gross salary", undefined, "Bruttogehälter"),
      vocab("das Nettogehalt", "net salary", undefined, "Nettogehälter"),
    ],
    phrases: [
      phrase("Die Frist für das Projekt ist Freitag.", "The deadline for the project is Friday."),
      phrase("Im Homeoffice während der Kernzeit erreichbar.", "Reachable in core hours when working from home."),
      phrase("Der Azubi macht eine Ausbildung.", "The apprentice is doing vocational training."),
      phrase("Bitte die Vertretung informieren.", "Please inform the cover."),
      phrase("Nach der Probezeit der Vertrag.", "After probation, the contract."),
      phrase("Erledigen Sie die To-do-Liste.", "Get the to-do list done."),
    ],
    sentences: [
      sentence("Die Abteilung hat eine Besprechung.", "The department has a meeting."),
      sentence("Gleitzeit endet am Nachmittag.", "Flexitime ends in the afternoon."),
      sentence("Das Zeugnis ist wichtig für die Bewerbung.", "The reference is important for the application."),
      sentence("Steuern gehen vom Bruttogehalt ab.", "Taxes come off gross salary."),
      sentence("Sie ist zuverlässig und belastbar.", "She is reliable and resilient."),
      sentence("Die Beförderung kommt nach der Weiterbildung.", "The promotion comes after further training."),
    ],
  },
  "perfect-tense": {
    vocab: [
      vocab("angerufen", "called"),
      vocab("besucht", "visited"),
      vocab("erzählt", "told"),
      vocab("geholfen", "helped"),
      vocab("genommen", "taken"),
      vocab("gesprochen", "spoken"),
      vocab("verstanden", "understood"),
      vocab("gefunden", "found"),
      vocab("gedacht", "thought"),
      vocab("gebracht", "brought"),
      vocab("gekannt", "known (a person)"),
      vocab("gewusst", "known (a fact)"),
      vocab("gelaufen", "run / walked"),
      vocab("geschwommen", "swum"),
      vocab("geflogen", "flown"),
      vocab("eingeschlafen", "fallen asleep"),
      vocab("aufgewacht", "woken up"),
      vocab("eingekauft", "shopped"),
      vocab("gekocht", "cooked"),
      vocab("geputzt", "cleaned"),
      vocab("gewartet", "waited"),
      vocab("versucht", "tried"),
      vocab("verpasst", "missed"),
      vocab("erreicht", "reached"),
      vocab("passiert", "happened"),
      vocab("damals", "back then"),
      vocab("vorhin", "a little while ago"),
      vocab("neulich", "recently"),
      vocab("inzwischen", "in the meantime"),
      vocab("vorher", "beforehand"),
      vocab("nachher", "afterwards"),
      vocab("seither", "since then"),
    ],
    phrases: [
      phrase("Ich habe gestern angerufen.", "I called yesterday."),
      phrase("Hast du das verstanden?", "Did you understand that?"),
      phrase("Vorhin ist etwas passiert.", "Something happened a little while ago."),
      phrase("Inzwischen hat sie gekocht.", "In the meantime she has cooked."),
      phrase("Damals sind wir geflogen.", "Back then we flew."),
      phrase("Seither hat er gewartet.", "Since then he has waited."),
    ],
    sentences: [
      sentence("Er hat den Anschluss verpasst.", "He missed the connection."),
      sentence("Sie ist eingeschlafen und aufgewacht.", "She fell asleep and woke up."),
      sentence("Wir haben Hilfe gefunden.", "We found help."),
      sentence("Ich habe nicht gewusst, dass er gekommen ist.", "I did not know that he had come."),
      sentence("Neulich haben sie uns besucht.", "Recently they visited us."),
      sentence("Nachher hat er geholfen.", "Afterwards he helped."),
    ],
  },
  "short-stories": {
    vocab: [
      vocab("die Figur", "the character", undefined, "Figuren"),
      vocab("der Erzähler", "the narrator", undefined, "Erzähler"),
      vocab("die Erzählerin", "the narrator (f)", undefined, "Erzählerinnen"),
      vocab("die Spannung", "the suspense"),
      vocab("das Ende", "the ending", undefined, "Enden"),
      vocab("der Anfang", "the beginning", undefined, "Anfänge"),
      vocab("die Szene", "the scene", undefined, "Szenen"),
      vocab("der Dialog", "the dialogue", undefined, "Dialoge"),
      vocab("heimlich", "secretly"),
      vocab("überrascht", "surprised"),
      vocab("enttäuscht", "disappointed"),
      vocab("neugierig", "curious"),
      vocab("ängstlich", "anxious / fearful"),
      vocab("mutig", "brave"),
      vocab("der Zufall", "chance / coincidence", undefined, "Zufälle"),
      vocab("die Ursache", "the cause", undefined, "Ursachen"),
      vocab("die Folge", "the consequence", undefined, "Folgen"),
      vocab("schließlich", "finally"),
      vocab("obwohl", "although"),
      vocab("während", "while / during"),
      vocab("bevor", "before"),
      vocab("als", "when (past)"),
      vocab("wenn", "if / when"),
      vocab("dass", "that"),
      vocab("ob", "whether"),
      vocab("außerdem", "besides / also"),
      vocab("nämlich", "namely / you see"),
      vocab("sobald", "as soon as"),
      vocab("seitdem", "since then"),
      vocab("damit", "so that"),
      vocab("jedoch", "however"),
      vocab("stattdessen", "instead"),
    ],
    phrases: [
      phrase("Zuerst war sie neugierig, dann ängstlich.", "At first she was curious, then anxious."),
      phrase("Obwohl es spät war, ist er geblieben.", "Although it was late, he stayed."),
      phrase("Die Folge war eine Überraschung.", "The consequence was a surprise."),
      phrase("Ob das Ende gut ist, wissen wir nicht.", "Whether the ending is good, we do not know."),
      phrase("Während des Dialogs lacht die Figur.", "During the dialogue the character laughs."),
      phrase("Stattdessen bleibt sie mutig.", "Instead she stays brave."),
    ],
    sentences: [
      sentence("Der Erzähler beginnt am Anfang.", "The narrator starts at the beginning."),
      sentence("Als er ankam, war sie enttäuscht.", "When he arrived, she was disappointed."),
      sentence("Bevor wir gehen, kommt der Zufall.", "Before we leave, chance arrives."),
      sentence("Ich weiß nicht, ob das wahr ist.", "I do not know whether that is true."),
      sentence("Jedoch hat sie heimlich erzählt.", "However, she told it secretly."),
      sentence("Außerdem ist die Szene kurz.", "Besides, the scene is short."),
    ],
  },
  "emails-notes": {
    vocab: [
      vocab("die Durchwahl", "the extension", undefined, "Durchwahlen"),
      vocab("die Signatur", "the signature", undefined, "Signaturen"),
      vocab("das Postfach", "the mailbox / PO box", undefined, "Postfächer"),
      vocab("der Verteiler", "the mailing list", undefined, "Verteiler"),
      vocab("vertraulich", "confidential"),
      vocab("die Rückmeldung", "the reply / feedback", undefined, "Rückmeldungen"),
      vocab("nachhaken", "to follow up"),
      vocab("erinnern", "to remind"),
      vocab("die Erinnerung", "the reminder", undefined, "Erinnerungen"),
      vocab("verschieben", "to postpone"),
      vocab("absagen", "to cancel"),
      vocab("zusagen", "to accept"),
      vocab("die Zusage", "the acceptance", undefined, "Zusagen"),
      vocab("die Absage", "the refusal", undefined, "Absagen"),
      vocab("der Vermerk", "the note / memo", undefined, "Vermerke"),
      vocab("stichpunktartig", "in bullet points"),
      vocab("ausführlich", "detailed"),
      vocab("knapp", "brief / tight"),
      vocab("die Anlage", "the attachment", undefined, "Anlagen"),
      vocab("das Betreffsfeld", "the subject field", undefined, "Betreffsfelder"),
      vocab("baldmöglichst", "as soon as possible"),
      vocab("hiermit", "hereby"),
      vocab("bezüglich", "regarding"),
      vocab("erledigt", "done"),
      vocab("unbearbeitet", "untouched / outstanding"),
      vocab("die Durchschrift", "the carbon copy", undefined, "Durchschriften"),
      vocab("der Entwurf", "the draft", undefined, "Entwürfe"),
      vocab("die Zustellung", "the delivery", undefined, "Zustellungen"),
      vocab("die Lesebestätigung", "the read receipt", undefined, "Lesebestätigungen"),
      vocab("priorisieren", "to prioritise"),
      vocab("die Kopiervorlage", "the template to copy", undefined, "Kopiervorlagen"),
      vocab("die Wiedervorlage", "the follow-up file", undefined, "Wiedervorlagen"),
    ],
    phrases: [
      phrase("Hiermit eine kurze Rückmeldung.", "Hereby a short reply."),
      phrase("Bitte um Rückruf unter der Durchwahl.", "Please call back on the extension."),
      phrase("Die Anlage ist vertraulich.", "The attachment is confidential."),
      phrase("Können wir den Termin verschieben?", "Can we postpone the appointment?"),
      phrase("Stichpunktartig im Vermerk.", "In bullet points in the memo."),
      phrase("Bezüglich Ihrer Absage danke ich.", "Regarding your refusal, thank you."),
    ],
    sentences: [
      sentence("Ich setze die Chefin auf den Verteiler.", "I put the boss on the mailing list."),
      sentence("Die Zusage steht im Text, nicht in der Signatur.", "The acceptance is in the text, not in the signature."),
      sentence("Baldmöglichst nachhaken, wenn nichts kommt.", "Follow up as soon as possible if nothing comes."),
      sentence("Das Postfach ist voll.", "The mailbox is full."),
      sentence("Die Erinnerung war knapp, nicht ausführlich.", "The reminder was brief, not detailed."),
      sentence("Die Lesebestätigung ist erledigt.", "The read receipt is done."),
    ],
  },
  "modal-verbs": {
    vocab: [
      vocab("fähig", "able / capable"),
      vocab("unfähig", "unable"),
      vocab("bereit", "ready / willing"),
      vocab("verpflichtet", "obliged"),
      vocab("berechtigt", "entitled"),
      vocab("notwendig", "necessary"),
      vocab("überflüssig", "unnecessary / superfluous"),
      vocab("freiwillig", "voluntary"),
      vocab("zwingend", "compulsory"),
      vocab("die Möglichkeit", "the possibility", undefined, "Möglichkeiten"),
      vocab("die Unmöglichkeit", "the impossibility"),
      vocab("die Notwendigkeit", "the necessity"),
      vocab("die Freiheit", "freedom"),
      vocab("die Wahl", "the choice", undefined, "Wahlen"),
      vocab("entscheiden", "to decide"),
      vocab("die Entscheidung", "the decision", undefined, "Entscheidungen"),
      vocab("riskieren", "to risk"),
      vocab("vermeiden", "to avoid"),
      vocab("schaffen", "to manage / create"),
      vocab("scheitern", "to fail"),
      vocab("versuchen", "to try"),
      vocab("lassen", "to let / leave"),
      vocab("die Bedingung", "the condition", undefined, "Bedingungen"),
      vocab("die Ausnahme", "the exception", undefined, "Ausnahmen"),
      vocab("verpflichten", "to oblige"),
      vocab("gestatten", "to permit"),
      vocab("untersagen", "to prohibit"),
      vocab("empfehlen", "to recommend"),
      vocab("raten", "to advise"),
      vocab("warnen", "to warn"),
      vocab("zwingen", "to force"),
      vocab("ermöglichen", "to make possible"),
    ],
    phrases: [
      phrase("Du darfst das nicht riskieren.", "You must not risk that."),
      phrase("Wir müssen eine Entscheidung treffen.", "We have to make a decision."),
      phrase("Freiwillig, nicht zwingend.", "Voluntary, not compulsory."),
      phrase("Ich schaffe das allein.", "I can manage that alone."),
      phrase("Bitte vermeiden Sie Lärm.", "Please avoid noise."),
      phrase("Sie ist berechtigt zu entscheiden.", "She is entitled to decide."),
    ],
    sentences: [
      sentence("Es ist notwendig, pünktlich zu sein.", "It is necessary to be on time."),
      sentence("Ohne Möglichkeit scheitern wir.", "Without a possibility we fail."),
      sentence("Die Wahl ist nicht überflüssig.", "The choice is not superfluous."),
      sentence("Unter dieser Bedingung gestatte ich es.", "Under this condition I permit it."),
      sentence("Lass uns versuchen, leise zu sein.", "Let us try to be quiet."),
      sentence("Unfähig? Nein, nur nicht bereit.", "Unable? No, just not willing."),
    ],
  },
};
