import { packChapter } from "@/content/levels/pack";
import type { ChapterSource } from "@/content/types";

export const a2ChaptersPart3: ChapterSource[] = [
  packChapter({
    slug: "house-chores",
    title: "Housework & Chores",
    titleDe: "Haushalt und Putzen",
    blurb: "Name cleaning tools and chores, then describe who does what at home.",
    skill: "vocab",
    grammar: [
      "Separable verbs go to the end: Ich sauge heute staub. Ich mache die Küche sauber.",
      "Accusative for the thing you clean: Ich wische den Boden. Tim räumt den Abstellraum ein.",
      "müssen + infinitive for duty: Ich muss die Waschmaschine anmachen.",
    ],
    vocab: [
      ["der Staubsauger", "the vacuum cleaner", "Staubsauger"],
      ["staubsaugen", "to vacuum"],
      ["wischen", "to wipe / mop"],
      ["der Wischmopp", "the mop", "Wischmopps"],
      ["der Besen", "the broom", "Besen"],
      ["kehren", "to sweep"],
      ["der Eimer", "the bucket", "Eimer"],
      ["das Spülmittel", "the washing-up liquid"],
      ["das Waschmittel", "the detergent"],
      ["der Lappen", "the cloth", "Lappen"],
      ["der Schwamm", "the sponge", "Schwämme"],
      ["der Staub", "the dust"],
      ["staubig", "dusty"],
      ["der Fleck", "the stain", "Flecken"],
      ["der Abfall", "the waste"],
      ["die Mülltonne", "the wheelie bin", "Mülltonnen"],
      ["das Geschirr", "the dishes"],
      ["abwaschen", "to wash up"],
      ["abtrocknen", "to dry (dishes)"],
      ["das Geschirrtuch", "the tea towel", "Geschirrtücher"],
      ["der Wasserhahn", "the tap", "Wasserhähne"],
      ["die Spülmaschine", "the dishwasher", "Spülmaschinen"],
      ["die Waschmaschine", "the washing machine", "Waschmaschinen"],
      ["der Trockner", "the tumble dryer", "Trockner"],
      ["aufhängen", "to hang up"],
      ["die Wäscheleine", "the washing line", "Wäscheleinen"],
      ["falten", "to fold"],
      ["das Reinigungsmittel", "the cleaning product", "Reinigungsmittel"],
      ["der Schmutz", "the dirt"],
      ["die Ordnung", "tidiness / order"],
      ["unordentlich", "messy / untidy"],
      ["ordentlich", "tidy"],
      ["der Putzplan", "the cleaning rota", "Putzpläne"],
      ["das Waschbecken", "the washbasin", "Waschbecken"],
      ["der Abfluss", "the drain", "Abflüsse"],
      ["verstopft", "blocked"],
      ["der Staubwedel", "the duster", "Staubwedel"],
      ["polieren", "to polish"],
      ["scheuern", "to scrub"],
      ["ausleeren", "to empty"],
      ["nachfüllen", "to refill"],
      ["der Müllbeutel", "the bin bag", "Müllbeutel"],
      ["das Waschpulver", "the washing powder"],
      ["der Weichspüler", "the fabric softener"],
      ["einweichen", "to soak"],
      ["die Haushaltshilfe", "the domestic help", "Haushaltshilfen"],
      ["der Haushalt", "the household", "Haushalte"],
      ["entkalken", "to descale"],
      ["der Kalk", "the limescale"],
      ["die Schürze", "the apron", "Schürzen"],
      ["die Gummihandschuhe", "the rubber gloves"],
      ["saubermachen", "to clean up"],
      ["einräumen", "to put away / load"],
      ["ausräumen", "to empty out / unload"],
      ["der Wäschekorb", "the laundry basket", "Wäschekörbe"],
      ["die Wäscheklammer", "the clothes peg", "Wäscheklammern"],
      ["die Kehrschaufel", "the dustpan", "Kehrschaufeln"],
      ["sprühen", "to spray"],
      ["die Sprühflasche", "the spray bottle", "Sprühflaschen"],
      ["die Fußmatte", "the doormat", "Fußmatten"],
      ["der Abstellraum", "the storage room", "Abstellräume"],
      ["trocknen", "to dry"],
      ["die Reinigung", "the cleaning / dry cleaner", "Reinigungen"],
      ["der Putzlappen", "the cleaning rag", "Putzlappen"],
    ],
    phrases: [
      ["Kannst du bitte staubsaugen?", "Can you vacuum, please?"],
      ["Der Abfluss ist verstopft.", "The drain is blocked."],
      ["Ich hänge die Wäsche auf die Wäscheleine.", "I hang the laundry on the washing line."],
      ["Wo ist der Wischmopp?", "Where is the mop?"],
      ["Bitte den Eimer nachfüllen.", "Please refill the bucket."],
      ["Das Geschirr kommt in die Spülmaschine.", "The dishes go in the dishwasher."],
      ["Der Putzplan hängt in der Küche.", "The cleaning rota is on the kitchen wall."],
      ["Zieh die Gummihandschuhe an.", "Put on the rubber gloves."],
      ["Der Fleck geht mit Reinigungsmittel raus.", "The stain comes out with cleaning product."],
      ["Leer die Mülltonne aus.", "Empty the wheelie bin."],
      ["Die Schürze ist im Abstellraum.", "The apron is in the storage room."],
      ["Heute mache ich den Haushalt.", "Today I do the housework."],
    ],
    sentences: [
      ["Ich kehre den Staub auf die Kehrschaufel.", "I sweep the dust onto the dustpan."],
      ["Lea wäscht das Geschirr ab und trocknet es ab.", "Lea washes the dishes and dries them."],
      ["Der Wasserhahn tropft, und der Kalk ist stark.", "The tap drips, and the limescale is heavy."],
      ["Wir falten die Wäsche aus dem Trockner.", "We fold the laundry from the dryer."],
      ["Tim räumt die Spülmaschine aus.", "Tim unloads the dishwasher."],
      ["Sprüh den Lappen und wische den Tisch.", "Spray the cloth and wipe the table."],
      ["Die Fußmatte ist nass und schmutzig.", "The doormat is wet and dirty."],
      ["Ich weiche den Putzlappen ein.", "I soak the cleaning rag."],
      ["Die Haushaltshilfe poliert am Freitag.", "The domestic help polishes on Friday."],
      ["Das Waschpulver und der Weichspüler sind leer.", "The washing powder and the fabric softener are empty."],
      ["Scheuer das Waschbecken mit dem Schwamm.", "Scrub the washbasin with the sponge."],
      ["Der Staubwedel liegt neben dem Besen.", "The duster is next to the broom."],
      ["Räum den Wäschekorb ordentlich ein.", "Load the laundry basket tidily."],
      ["Ohne Ordnung ist die Wohnung unordentlich.", "Without tidiness the flat is messy."],
      ["Wir entkalken die Maschine einmal im Monat.", "We descale the machine once a month."],
      ["Häng die Wäscheklammern an die Wäscheleine.", "Clip the pegs onto the washing line."],
    ],
    readings: [
      {
        title: "The cleaning rota",
        titleDe: "Der Putzplan",
        text: "In unserer WG gibt es einen Putzplan. Montags staubsauge ich. Der Staubsauger steht im Abstellraum neben dem Besen und der Kehrschaufel. Dienstags wischt Tim den Boden mit dem Wischmopp und einem Eimer. Das Geschirr machen wir in der Spülmaschine. Freitags hängt Lea die Wäsche auf die Wäscheleine. Der Wäschekorb ist oft voll. Wer den Müllbeutel nicht in die Mülltonne bringt, muss am Wochenende die Küche saubermachen.",
        translation: "In our shared flat there is a cleaning rota. On Mondays I vacuum. The vacuum cleaner is in the storage room next to the broom and the dustpan. On Tuesdays Tim mops the floor with the mop and a bucket. We do the dishes in the dishwasher. On Fridays Lea hangs the laundry on the washing line. The laundry basket is often full. Anyone who does not put the bin bag in the wheelie bin has to clean the kitchen at the weekend.",
        questions: [
          ["Who vacuums on Monday?", "The narrator", ["Tim", "Lea", "The narrator", "Nobody"]],
          ["Where is the vacuum cleaner?", "In the storage room", ["On the balcony", "In the storage room", "Under the sofa", "At work"]],
          ["What happens if you forget the bin bag?", "You clean the kitchen at the weekend", ["You pay a fine", "You cook dinner", "You clean the kitchen at the weekend", "Nothing"]],
        ],
      },
      {
        title: "A blocked tap",
        titleDe: "Der Wasserhahn",
        text: "Liebe Haushaltshilfe, der Wasserhahn im Bad tropft, und der Abfluss ist verstopft. Bitte Gummihandschuhe anziehen und mit der Sprühflasche und dem Schwamm scheuern. Der Kalk am Waschbecken ist stark. Entkalken Sie auch die Maschine. Spülmittel und Reinigungsmittel stehen unter der Spüle. Die Schürze hängt an der Tür. Danke und bis Freitag, Nora.",
        translation: "Dear domestic help, the bathroom tap is dripping and the drain is blocked. Please put on rubber gloves and scrub with the spray bottle and the sponge. The limescale on the washbasin is heavy. Please also descale the machine. Washing-up liquid and cleaning product are under the sink. The apron is hanging on the door. Thank you and see you Friday, Nora.",
        questions: [
          ["What is blocked?", "The drain", ["The door", "The drain", "The fridge", "The window"]],
          ["Where are the cleaning products?", "Under the sink", ["In the cellar", "Under the sink", "On the roof", "At the shop"]],
          ["When will Nora see the helper?", "Friday", ["Monday", "Tonight", "Friday", "Never"]],
        ],
      },
      {
        title: "Laundry day",
        titleDe: "Waschtag",
        text: "Heute ist Waschtag. Ich räume den Wäschekorb aus und fülle Waschpulver und Weichspüler nach. Ein Fleck auf dem Hemd muss einweichen. Dann kommt alles in die Waschmaschine. Der Trockner ist kaputt, also hänge ich die Wäsche an die Wäscheleine. Die Wäscheklammern sind im Eimer. Später falte ich alles und mache den Haushalt ordentlich. Der Staubwedel und der Putzlappen warten schon.",
        translation: "Today is laundry day. I empty the laundry basket and refill washing powder and fabric softener. A stain on the shirt has to soak. Then everything goes in the washing machine. The dryer is broken, so I hang the laundry on the washing line. The pegs are in the bucket. Later I fold everything and tidy the household. The duster and the cleaning rag are already waiting.",
        questions: [
          ["Why not use the dryer?", "It is broken", ["It is raining", "It is broken", "There is no power", "It is too small"]],
          ["Where are the pegs?", "In the bucket", ["In the fridge", "In the bucket", "On the bed", "At the shop"]],
          ["What must soak?", "A stain on the shirt", ["The dishes", "The mop", "A stain on the shirt", "The doormat"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about your cleaning rota at home.",
        "Schreib vier Sätze über den Putzplan zu Hause.",
        "Montags staubsauge ich. Tim wischt den Boden. Wir räumen die Spülmaschine aus. Der Müllbeutel kommt in die Mülltonne.",
        ["Name two chores and two people", "Use a weekday"],
      ],
      [
        "Write a short note asking someone to clean the bathroom.",
        "Schreib eine kurze Notiz: Bitte das Bad saubermachen.",
        "Bitte das Waschbecken scheuern. Der Abfluss ist verstopft. Gummihandschuhe und Schwamm sind im Abstellraum.",
        ["Name two tools", "Mention one problem"],
      ],
    ],
  }),
  packChapter({
    slug: "bank-post-services",
    title: "Bank & Post Office",
    titleDe: "Bank und Postdienste",
    blurb: "Open an account, send a parcel, and follow a transfer or tracking number.",
    skill: "vocab",
    grammar: [
      "Amounts in the accusative: Ich überweise fünfzig Euro. Heben Sie das Geld ab.",
      "Separable verbs: einzahlen, abheben, abbuchen, auspacken, zustellen.",
      "zur Filiale / zum Schalter / zur Packstation: zu + dem/der.",
    ],
    vocab: [
      ["das Konto", "the account", "Konten"],
      ["das Girokonto", "the current account", "Girokonten"],
      ["das Sparkonto", "the savings account", "Sparkonten"],
      ["überweisen", "to transfer (money)"],
      ["die Überweisung", "the transfer", "Überweisungen"],
      ["abheben", "to withdraw"],
      ["einzahlen", "to pay in / deposit"],
      ["der Betrag", "the amount", "Beträge"],
      ["die Gebühr", "the fee", "Gebühren"],
      ["der Geldautomat", "the cash machine", "Geldautomaten"],
      ["der Kontostand", "the account balance"],
      ["der Kontoauszug", "the bank statement", "Kontoauszüge"],
      ["die Bankkarte", "the bank card", "Bankkarten"],
      ["die PIN", "the PIN", "PINs"],
      ["die IBAN", "the IBAN", "IBANs"],
      ["sparen", "to save (money)"],
      ["das Kleingeld", "the coins / small change"],
      ["die Filiale", "the branch", "Filialen"],
      ["der Schalter", "the counter", "Schalter"],
      ["das Paket", "the parcel", "Pakete"],
      ["das Päckchen", "the small parcel", "Päckchen"],
      ["die Sendung", "the consignment / item", "Sendungen"],
      ["die Sendungsverfolgung", "parcel tracking"],
      ["der Zusteller", "the delivery person", "Zusteller"],
      ["die Packstation", "the parcel locker", "Packstationen"],
      ["das Einschreiben", "the registered letter", "Einschreiben"],
      ["der Abholschein", "the collection slip", "Abholscheine"],
      ["die Wartenummer", "the queue number", "Wartenummern"],
      ["der Kredit", "the loan / credit", "Kredite"],
      ["der Zins", "the interest", "Zinsen"],
      ["die Kontoeröffnung", "the account opening", "Kontoeröffnungen"],
      ["bargeldlos", "cashless"],
      ["das Sparbuch", "the savings book", "Sparbücher"],
      ["die TAN", "the transaction number", "TANs"],
      ["das Online-Banking", "online banking"],
      ["zustellen", "to deliver"],
      ["der Paketdienst", "the parcel service", "Paketdienste"],
      ["die Lastschrift", "the direct debit", "Lastschriften"],
      ["abbuchen", "to debit"],
      ["der Dauerauftrag", "the standing order", "Daueraufträge"],
      ["das Guthaben", "the credit balance"],
      ["der Briefkasten", "the letterbox", "Briefkästen"],
      ["die Sendungsnummer", "the tracking number", "Sendungsnummern"],
      ["sperren", "to block (a card)"],
      ["der Paketshop", "the parcel shop", "Paketshops"],
      ["verpacken", "to pack / wrap"],
      ["auspacken", "to unpack"],
      ["der Expressdienst", "the express service", "Expressdienste"],
      ["benachrichtigen", "to notify"],
      ["die Benachrichtigung", "the notification", "Benachrichtigungen"],
      ["überzogen", "overdrawn"],
      ["der Dispokredit", "the overdraft", "Dispokredite"],
      ["auszahlen", "to pay out"],
      ["das Limit", "the limit", "Limits"],
      ["der Zustellversuch", "the delivery attempt", "Zustellversuche"],
      ["eingeschrieben", "registered (mail)"],
      ["der BIC", "the BIC code", "BICs"],
      ["die Nachnahme", "cash on delivery"],
      ["das Wertpaket", "the insured parcel", "Wertpakete"],
      ["die Laufzeit", "the transit time", "Laufzeiten"],
      ["der Einzahlungsbeleg", "the deposit slip", "Einzahlungsbelege"],
      ["entsperren", "to unblock"],
      ["der Beleg", "the slip / proof", "Belege"],
      ["die Zustelladresse", "the delivery address", "Zustelladressen"],
    ],
    phrases: [
      ["Ich möchte eine Kontoeröffnung.", "I would like to open an account."],
      ["Kann ich hier Geld abheben?", "Can I withdraw money here?"],
      ["Die IBAN steht auf dem Kontoauszug.", "The IBAN is on the statement."],
      ["Bitte die PIN nicht laut sagen.", "Please do not say the PIN out loud."],
      ["Wo ist die nächste Packstation?", "Where is the nearest parcel locker?"],
      ["Die Sendungsnummer ist in der Benachrichtigung.", "The tracking number is in the notification."],
      ["Ich zahle bargeldlos.", "I pay cashless."],
      ["Sperren Sie bitte die Bankkarte.", "Please block the bank card."],
      ["Der Zusteller war nicht da.", "The delivery person was not there."],
      ["Ein Päckchen als Einschreiben, bitte.", "A small parcel as registered mail, please."],
      ["Der Betrag ist zu hoch für das Limit.", "The amount is too high for the limit."],
      ["Haben Sie den Abholschein?", "Do you have the collection slip?"],
    ],
    sentences: [
      ["Ich überweise den Betrag auf das Sparkonto.", "I transfer the amount to the savings account."],
      ["Am Geldautomaten hebe ich nur Kleingeld und Scheine ab.", "At the cash machine I only withdraw coins and notes."],
      ["Die Sparkasse bucht die Lastschrift jeden Monat ab.", "The savings bank debits the direct debit every month."],
      ["Das Konto ist überzogen, der Dispokredit ist teuer.", "The account is overdrawn; the overdraft is expensive."],
      ["Im Online-Banking brauche ich eine TAN.", "In online banking I need a TAN."],
      ["Der Paketdienst stellt das Wertpaket an der Zustelladresse zu.", "The parcel service delivers the insured parcel to the delivery address."],
      ["Nach dem Zustellversuch liegt ein Zettel im Briefkasten.", "After the delivery attempt a note is in the letterbox."],
      ["Die Laufzeit beim Expressdienst ist ein Tag.", "Transit time with the express service is one day."],
      ["Ich packe das Paket im Paketshop aus.", "I unpack the parcel at the parcel shop."],
      ["Bitte die Karte entsperren und einen neuen Beleg drucken.", "Please unblock the card and print a new slip."],
      ["Der Schalter in der Filiale gibt Wartenummern.", "The counter in the branch gives out queue numbers."],
      ["Mit IBAN und BIC geht die Überweisung ins Ausland.", "With IBAN and BIC the transfer goes abroad."],
      ["Das Guthaben auf dem Sparbuch bringt wenig Zins.", "The balance in the savings book earns little interest."],
      ["Die Sendung kommt per Nachnahme.", "The item comes cash on delivery."],
      ["Ich zahle am Schalter ein und nehme den Einzahlungsbeleg.", "I pay in at the counter and take the deposit slip."],
      ["Ein Dauerauftrag spart Zeit, eine Gebühr kommt trotzdem.", "A standing order saves time; a fee still applies."],
    ],
    readings: [
      {
        title: "New account",
        titleDe: "Neues Konto",
        text: "Guten Tag, ich möchte eine Kontoeröffnung: ein Girokonto. Ich habe schon ein Sparkonto und ein Sparbuch, aber ich will bargeldlos zahlen. Die Beraterin erklärt IBAN, BIC und das Limit am Geldautomaten. Fürs Online-Banking brauche ich eine PIN und eine TAN. Ein Dauerauftrag für die Miete ist möglich. Die Gebühr für das Konto ist fünf Euro im Monat. Den ersten Kontoauszug hole ich an der Filiale.",
        translation: "Hello, I would like a current account at the savings bank. I already have a savings account and a savings book, but I want to pay cashless. The adviser explains IBAN, BIC and the cash-machine limit. For online banking I need a PIN and a TAN. A standing order for the rent is possible. The fee for the account is five euros a month. I will collect the first statement at the branch.",
        questions: [
          ["What kind of account does the customer want?", "A current account", ["Only a savings book", "A current account", "A loan", "A parcel box"]],
          ["How much is the monthly fee?", "Five euros", ["Free", "Fifty euros", "Five euros", "One euro"]],
          ["Where will the first statement be collected?", "At the branch", ["At the airport", "At the branch", "At school", "Online only"]],
        ],
      },
      {
        title: "Parcel not in",
        titleDe: "Paket nicht da",
        text: "Ihre Sendung. Zustellversuch heute um 11 Uhr. Der Zusteller konnte das Paket nicht zustellen. Bitte holen Sie es mit dem Abholschein und der Sendungsnummer im Paketshop oder an der Packstation. Die Laufzeit war zwei Tage. Das Päckchen ist kein Wertpaket und nicht eingeschrieben. Nachnahme ist nicht nötig. Bei Fragen benachrichtigen Sie den Paketdienst.",
        translation: "Your consignment. Delivery attempt today at 11 a.m. The delivery person could not deliver the parcel. Please collect it with the collection slip and the tracking number at the parcel shop or the parcel locker. Transit time was two days. The small parcel is not an insured parcel and is not registered. Cash on delivery is not needed. If you have questions, notify the parcel service.",
        questions: [
          ["When was the delivery attempt?", "11:00", ["09:00", "11:00", "18:00", "Midnight"]],
          ["What do you need to collect the parcel?", "Collection slip and tracking number", ["Only a PIN", "A passport photo", "Collection slip and tracking number", "Cash on delivery"]],
          ["Is it registered mail?", "No", ["Yes", "No", "Only the box", "Unknown"]],
        ],
      },
      {
        title: "Card blocked",
        titleDe: "Karte gesperrt",
        text: "Hallo, mein Konto ist überzogen und die Bankkarte ist gesperrt. Der Dispokredit ist voll. Kann die Filiale die Karte entsperren? Ich möchte am Schalter Geld einzahlen und einen Beleg. Dann überweise ich einen Betrag auf das Girokonto. Bitte keine Lastschrift heute abbuchen. Den Kontostand sehe ich im Online-Banking. Viele Grüße, Amir.",
        translation: "Hello, my account is overdrawn and the bank card is blocked. The overdraft is maxed out. Can the branch unblock the card? I would like to pay in money at the counter and get a slip. Then I will transfer an amount to the current account. Please do not debit a direct debit today. I can see the balance in online banking. Kind regards, Amir.",
        questions: [
          ["Why is the card blocked?", "The account is overdrawn", ["He lost the PIN", "The account is overdrawn", "He is on holiday", "The bank is closed"]],
          ["What does Amir want at the counter?", "To pay in money and get a slip", ["A new parcel", "To pay in money and get a slip", "A loan only", "A savings book"]],
          ["What should not happen today?", "A direct debit", ["A transfer", "A direct debit", "Online banking", "A statement"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences: open an account and pay cashless.",
        "Schreib vier Sätze: Konto eröffnen und bargeldlos zahlen.",
        "Ich eröffne ein Girokonto. Die IBAN steht auf dem Kontoauszug. Ich zahle bargeldlos. Am Geldautomaten hebe ich nur wenig ab.",
        ["Name the account type", "Mention IBAN or PIN"],
      ],
      [
        "Write a note about a missed parcel delivery.",
        "Schreib eine Notiz über einen Zustellversuch.",
        "Der Zusteller war nicht da. Die Benachrichtigung liegt im Briefkasten. Ich hole das Paket an der Packstation mit der Sendungsnummer.",
        ["Say what happened", "Say where you will collect it"],
      ],
    ],
  }),
  packChapter({
    slug: "media-internet",
    title: "Phone, Internet & Media",
    titleDe: "Handy, Internet und Medien",
    blurb: "Talk about Wi-Fi, apps, films and a weak battery at A2 level.",
    skill: "vocab",
    grammar: [
      "Separable verbs: laden Sie die Datei herunter, laden Sie den Akku auf, schalten Sie um.",
      "online and offline are adverbs: Ich bin online. Der Router ist offline.",
      "weil / dass send the verb to the end: Ich streame, weil der Hotspot gut ist.",
    ],
    vocab: [
      ["das Internet", "the internet"],
      ["das WLAN", "the Wi-Fi"],
      ["die App", "the app", "Apps"],
      ["der Laptop", "the laptop", "Laptops"],
      ["surfen", "to surf (the web)"],
      ["chatten", "to chat (online)"],
      ["die Website", "the website", "Websites"],
      ["der Link", "the link", "Links"],
      ["die Datei", "the file", "Dateien"],
      ["herunterladen", "to download"],
      ["hochladen", "to upload"],
      ["streamen", "to stream"],
      ["der Podcast", "the podcast", "Podcasts"],
      ["das Video", "the video", "Videos"],
      ["die Dokumentation", "the documentary", "Dokumentationen"],
      ["das Radioprogramm", "the radio programme", "Radioprogramme"],
      ["der Lautsprecher", "the speaker", "Lautsprecher"],
      ["das Headset", "the headset", "Headsets"],
      ["aufladen", "to charge"],
      ["der Akku", "the battery (rechargeable)", "Akkus"],
      ["die SIM-Karte", "the SIM card", "SIM-Karten"],
      ["das Netz", "the network / signal", "Netze"],
      ["die Flatrate", "the unlimited plan", "Flatrates"],
      ["der Tarif", "the tariff / plan", "Tarife"],
      ["online", "online"],
      ["offline", "offline"],
      ["der Hotspot", "the hotspot", "Hotspots"],
      ["verbinden", "to connect"],
      ["der Router", "the router", "Router"],
      ["das Kabel", "the cable", "Kabel"],
      ["der USB-Stick", "the USB stick", "USB-Sticks"],
      ["die Cloud", "the cloud"],
      ["installieren", "to install"],
      ["das Update", "the update", "Updates"],
      ["aktualisieren", "to update"],
      ["der Browser", "the browser", "Browser"],
      ["die Suchmaschine", "the search engine", "Suchmaschinen"],
      ["die Fernbedienung", "the remote control", "Fernbedienungen"],
      ["die Lautstärke", "the volume"],
      ["stumm", "mute"],
      ["die Werbung", "the advert / advertising"],
      ["der Kanal", "the channel", "Kanäle"],
      ["umschalten", "to switch over (channel)"],
      ["die Fernsehsendung", "the TV programme", "Fernsehsendungen"],
      ["das soziale Netzwerk", "the social network", "sozialen Netzwerke"],
      ["posten", "to post (online)"],
      ["teilen", "to share"],
      ["der Kommentar", "the comment", "Kommentare"],
      ["der Account", "the account", "Accounts"],
      ["das Profil", "the profile", "Profile"],
      ["die Privatsphäre", "privacy"],
      ["der Virus", "the virus", "Viren"],
      ["die Kamera", "the camera", "Kameras"],
      ["das Mikrofon", "the microphone", "Mikrofone"],
      ["die Videokonferenz", "the video conference", "Videokonferenzen"],
      ["der Videoanruf", "the video call", "Videoanrufe"],
      ["die Mailbox", "the voicemail"],
      ["der Klingelton", "the ringtone", "Klingeltöne"],
      ["lautlos", "silent (mode)"],
      ["vibrieren", "to vibrate"],
      ["das Ladekabel", "the charging cable", "Ladekabel"],
      ["der Akkustand", "the battery level"],
      ["der Screenshot", "the screenshot", "Screenshots"],
      ["zoomen", "to zoom"],
    ],
    phrases: [
      ["Ist das WLAN frei?", "Is the Wi-Fi open / free?"],
      ["Der Hotspot ist schlecht.", "The hotspot is bad."],
      ["Bitte den Akku aufladen.", "Please charge the battery."],
      ["Kannst du den Link teilen?", "Can you share the link?"],
      ["Ich bin offline, kein Netz.", "I am offline, no signal."],
      ["Installier die App auf dem Laptop.", "Install the app on the laptop."],
      ["Die Lautstärke ist zu hoch. Mach stumm.", "The volume is too high. Mute it."],
      ["Wir machen einen Videoanruf.", "We are making a video call."],
      ["Der Router braucht ein Update.", "The router needs an update."],
      ["Post nicht mein Profil.", "Do not post my profile."],
      ["Die Mailbox ist voll.", "Voicemail is full."],
      ["Stream die Dokumentation mit dem Headset.", "Stream the documentary with the headset."],
    ],
    sentences: [
      ["Ich surfe mit der Suchmaschine im Browser.", "I surf with the search engine in the browser."],
      ["Lade die Datei in die Cloud hoch, nicht auf den USB-Stick.", "Upload the file to the cloud, not onto the USB stick."],
      ["Der Podcast läuft im Radioprogramm und auf dem Laptop.", "The podcast is on the radio programme and on the laptop."],
      ["Ohne SIM-Karte gibt es keine Flatrate.", "Without a SIM card there is no unlimited plan."],
      ["Verbinde das Kabel mit dem Router.", "Connect the cable to the router."],
      ["Die Werbung kommt vor der Fernsehsendung.", "The advert comes before the TV programme."],
      ["Schalt den Kanal mit der Fernbedienung um.", "Switch the channel with the remote."],
      ["Im sozialen Netzwerk schreibe ich einen Kommentar.", "On the social network I write a comment."],
      ["Der Virus kommt oft per Link.", "The virus often comes via a link."],
      ["Kamera und Mikrofon sind für die Videokonferenz an.", "Camera and microphone are on for the video conference."],
      ["Das Handy ist lautlos, aber es vibriert.", "The phone is silent but it vibrates."],
      ["Der Akkustand ist leer, wo ist das Ladekabel?", "The battery level is empty; where is the charging cable?"],
      ["Mach einen Screenshot und zoome das Video.", "Take a screenshot and zoom the video."],
      ["Der Tarif ohne Netz ist teuer und nutzlos.", "The plan with no signal is expensive and useless."],
      ["Aktualisier den Account und die Privatsphäre.", "Update the account and the privacy settings."],
      ["Der Klingelton ist neu, der Lautsprecher ist laut.", "The ringtone is new; the speaker is loud."],
    ],
    readings: [
      {
        title: "Wi-Fi at home",
        titleDe: "WLAN zu Hause",
        text: "Unser Router ist oft offline. Dann gibt es kein WLAN und keinen Hotspot zum Internet. Ich verbinde den Laptop mit einem Kabel. Die Flatrate im Netz vom Handy ist teuer, aber ich kann chatten und eine Datei herunterladen. Bitte aktualisier das Update auf dem Router. Die App vom Anbieter zeigt den Tarif. Ohne Ladekabel bleibt der Akkustand bei zehn Prozent.",
        translation: "Our router is often offline. Then there is no Wi-Fi and no hotspot to the internet. I connect the laptop with a cable. The unlimited plan on the phone network is expensive, but I can chat and download a file. Please install the update on the router. The provider's app shows the plan. Without a charging cable the battery level stays at ten percent.",
        questions: [
          ["Why is there no Wi-Fi?", "The router is offline", ["There is no laptop", "The router is offline", "The SIM is new", "The film is long"]],
          ["How does the narrator use the laptop then?", "With a cable", ["Only with Wi-Fi", "With a cable", "With the radio", "With headphones"]],
          ["What is at ten percent?", "The battery level", ["The volume", "The battery level", "The tariff", "The cloud"]],
        ],
      },
      {
        title: "Film night",
        titleDe: "Filmabend",
        text: "Wir streamen eine Dokumentation. Die Lautstärke am Lautsprecher ist hoch, also nehmen wir das Headset. Vor dem Video kommt Werbung. Mit der Fernbedienung schalten wir den Kanal um, aber die Fernsehsendung ist langweilig. Besser den Podcast im Radioprogramm. Jemand postet einen Screenshot im sozialen Netzwerk. Das ist schlecht für die Privatsphäre. Bitte nicht teilen und keinen Kommentar unter mein Profil.",
        translation: "We stream a documentary. The volume on the speaker is high, so we take the headset. Before the video there are adverts. With the remote we switch channel, but the TV programme is boring. Better the podcast on the radio programme. Someone posts a screenshot on the social network. That is bad for privacy. Please do not share it and do not put a comment under my profile.",
        questions: [
          ["Why headphones?", "The speaker volume is high", ["There is no film", "The speaker volume is high", "The router is new", "The SIM is full"]],
          ["What is boring?", "The TV programme", ["The podcast", "The TV programme", "The screenshot", "The remote"]],
          ["What is bad for privacy?", "Posting the screenshot", ["Using headphones", "Posting the screenshot", "Streaming", "Charging"]],
        ],
      },
      {
        title: "Video call",
        titleDe: "Videoanruf",
        text: "Um drei ist eine Videokonferenz. Installier die App, öffne den Browser und klick auf den Link. Kamera und Mikrofon müssen an sein. Der Account braucht ein Passwort, aber die Privatsphäre-Einstellungen sind schon da. Wenn du offline bist, geht ein Videoanruf auf die Mailbox. Das Handy soll lautlos vibrieren, nicht mit Klingelton. Zoom nicht zu stark, sonst sieht man jeden Virus-Warnhinweis auf dem Screenshot.",
        translation: "At three there is a video conference. Install the app, open the browser and click the link. Camera and microphone must be on. The account needs a password, but the privacy settings are already there. If you are offline, a video call goes to voicemail. The phone should vibrate silently, not with a ringtone. Do not zoom too much, or you will see every virus warning on the screenshot.",
        questions: [
          ["When is the video conference?", "At three", ["At noon", "At three", "At midnight", "On Sunday only"]],
          ["What happens if you are offline?", "The call goes to voicemail", ["The film starts", "The call goes to voicemail", "The router burns", "Nothing"]],
          ["How should the phone behave?", "Silent vibrate", ["Loud ringtone", "Silent vibrate", "Always online radio", "No battery"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about your Wi-Fi and phone battery.",
        "Schreib vier Sätze über WLAN und Akku.",
        "Das WLAN ist schwach. Ich verbinde den Laptop mit einem Kabel. Der Akkustand ist niedrig. Ich lade mit dem Ladekabel auf.",
        ["Name a device", "Name a problem"],
      ],
      [
        "Write a short message: you cannot join a video call.",
        "Schreib eine kurze Nachricht: Du schaffst den Videoanruf nicht.",
        "Ich bin offline, die Verbindung ist schlecht. Bitte den Link in die Cloud legen. Ich höre später den Podcast.",
        ["Give a reason", "Suggest an alternative"],
      ],
    ],
  }),
  packChapter({
    slug: "celebrations",
    title: "Birthdays, Holidays & Parties",
    titleDe: "Geburtstage, Feste und Feiern",
    blurb: "Invite someone, talk about gifts, and describe a German holiday at A2.",
    skill: "vocab",
    grammar: [
      "ausrichten: Wir richten eine Gartenparty aus. mitfeiern: Komm mitfeiern!",
      "Time: zur Geburtstagsfeier, zum Weihnachtsfest, auf der Silvesterparty, um Mitternacht.",
      "überreichen + dative + accusative: Ich überreiche dir ein Mitbringsel.",
    ],
    vocab: [
      ["die Geburtstagsfeier", "the birthday party", "Geburtstagsfeiern"],
      ["das Mitbringsel", "the small gift to bring", "Mitbringsel"],
      ["mitfeiern", "to join in celebrating"],
      ["die Gartenparty", "the garden party", "Gartenpartys"],
      ["das Straßenfest", "the street festival", "Straßenfeste"],
      ["die Tanzparty", "the dance party", "Tanzpartys"],
      ["der Gast", "the guest", "Gäste"],
      ["bewirten", "to host / serve guests"],
      ["der Glückwunsch", "the congratulations", "Glückwünsche"],
      ["überreichen", "to hand over (a gift)"],
      ["die Kerze", "the candle", "Kerzen"],
      ["der Luftballon", "the balloon", "Luftballons"],
      ["die Dekoration", "the decoration", "Dekorationen"],
      ["das Weihnachtsfest", "Christmas (the festival)", "Weihnachtsfeste"],
      ["das Osterfest", "Easter (the festival)", "Osterfeste"],
      ["die Silvesterparty", "the New Year's Eve party", "Silvesterpartys"],
      ["die Karnevalszeit", "the carnival season"],
      ["das Feuerwerk", "the fireworks", "Feuerwerke"],
      ["der Nikolaustag", "St Nicholas' Day", "Nikolaustage"],
      ["die Geburtstagstorte", "the birthday cake", "Geburtstagstorten"],
      ["ausrichten", "to put on (an event)"],
      ["der Gastgeber", "the host (m)", "Gastgeber"],
      ["die Gastgeberin", "the host (f)", "Gastgeberinnen"],
      ["schmücken", "to decorate"],
      ["der Tannenbaum", "the Christmas tree", "Tannenbäume"],
      ["der Osterhase", "the Easter bunny", "Osterhasen"],
      ["das Osterei", "the Easter egg", "Ostereier"],
      ["der Sekt", "the sparkling wine"],
      ["anstoßen", "to toast / clink glasses"],
      ["Prost", "cheers"],
      ["der Festtag", "the feast day", "Festtage"],
      ["der Jahrestag", "the anniversary", "Jahrestage"],
      ["veranstalten", "to put on / organise"],
      ["die Veranstaltung", "the event", "Veranstaltungen"],
      ["der Anlass", "the occasion", "Anlässe"],
      ["Heiligabend", "Christmas Eve"],
      ["Neujahr", "New Year's Day"],
      ["der Muttertag", "Mother's Day"],
      ["der Vatertag", "Father's Day"],
      ["der Rosenmontag", "Rose Monday (carnival)"],
      ["der Karnevalsumzug", "the carnival parade", "Karnevalsumzüge"],
      ["die Tradition", "the tradition", "Traditionen"],
      ["traditionell", "traditional"],
      ["klatschen", "to clap"],
      ["das Festessen", "the festive meal", "Festessen"],
      ["der Ehrengast", "the guest of honour", "Ehrengäste"],
      ["mitbringen", "to bring along"],
      ["das Geschenkpapier", "the wrapping paper"],
      ["einwickeln", "to wrap"],
      ["die Schleife", "the ribbon / bow", "Schleifen"],
      ["die Glückwunschkarte", "the greetings card", "Glückwunschkarten"],
      ["der Strauß", "the bunch of flowers", "Sträuße"],
      ["die Einladungskarte", "the invitation card", "Einladungskarten"],
      ["der Festsaal", "the banqueting hall", "Festsäle"],
      ["ausgelassen", "lively / high-spirited"],
      ["fröhlich", "cheerful"],
      ["festlich", "festive"],
      ["Mitternacht", "midnight"],
      ["der Countdown", "the countdown", "Countdowns"],
      ["die Gratulation", "the congratulation", "Gratulationen"],
      ["sich wünschen", "to wish for"],
      ["der Wunsch", "the wish", "Wünsche"],
      ["das Buffet", "the buffet", "Buffets"],
      ["erscheinen", "to appear / turn up"],
    ],
    phrases: [
      ["Herzlichen Glückwunsch zur Geburtstagsfeier!", "Congratulations on the birthday party!"],
      ["Wir richten eine Gartenparty aus. Komm mitfeiern!", "We are putting on a garden party. Come join in!"],
      ["Was wünschst du dir als Mitbringsel?", "What would you like as a little gift?"],
      ["Kannst du einen Strauß mitbringen?", "Can you bring a bunch of flowers?"],
      ["Wir stoßen mit Sekt an. Prost!", "We toast with sparkling wine. Cheers!"],
      ["Die Tanzparty ist im Festsaal.", "The dance party is in the banqueting hall."],
      ["Zum Weihnachtsfest schmücken wir den Tannenbaum.", "For Christmas we decorate the tree."],
      ["Auf der Silvesterparty gibt es Feuerwerk um Mitternacht.", "At the New Year's Eve party there are fireworks at midnight."],
      ["Zum Osterfest bringt der Osterhase Ostereier.", "At Easter the Easter bunny brings Easter eggs."],
      ["Bitte die Einladungskarte nicht vergessen.", "Please do not forget the invitation card."],
      ["Die Gäste sind ausgelassen und fröhlich.", "The guests are high-spirited and cheerful."],
      ["Wer ist der Ehrengast?", "Who is the guest of honour?"],
    ],
    sentences: [
      ["Lea überreicht Tim eine Kerze und eine Glückwunschkarte.", "Lea hands Tim a candle and a greetings card."],
      ["Der Gastgeber wickelt das Mitbringsel in Geschenkpapier und eine Schleife.", "The host wraps the little gift in wrapping paper and a ribbon."],
      ["Luftballons und Dekoration hängen über dem Buffet.", "Balloons and decoration hang above the buffet."],
      ["Am Muttertag und am Vatertag gibt es ein Festessen.", "On Mother's Day and Father's Day there is a festive meal."],
      ["Der Nikolaustag kommt vor Heiligabend.", "St Nicholas' Day comes before Christmas Eve."],
      ["In der Karnevalszeit sehen wir den Karnevalsumzug, am Rosenmontag auch.", "In carnival season we watch the parade, and on Rose Monday too."],
      ["Die Veranstaltung hat einen klaren Anlass: der Jahrestag.", "The event has a clear occasion: the anniversary."],
      ["Wir richten die Gartenparty traditionell in der Familie aus.", "We traditionally put on the garden party in the family."],
      ["Die Gäste klatschen, die Gastgeberin sagt eine Gratulation.", "The guests clap; the host says a congratulation."],
      ["An Neujahr erscheinen nicht alle Gäste pünktlich.", "On New Year's Day not all guests turn up on time."],
      ["Der Countdown beginnt vor Mitternacht.", "The countdown starts before midnight."],
      ["Das Osterfest ist ein Festtag mit alter Tradition.", "Easter is a feast day with old tradition."],
      ["Ich wünsche mir keine Geburtstagstorte, nur Sekt.", "I do not wish for a birthday cake, only sparkling wine."],
      ["Bitte die Einladungskarte zum Straßenfest mitbringen.", "Please bring the invitation card to the street festival."],
      ["Die Silvesterparty ohne Feuerwerk ist trotzdem ausgelassen.", "The New Year's Eve party without fireworks is still high-spirited."],
      ["Der Wunsch auf der Karte ist kurz und fröhlich.", "The wish on the card is short and cheerful."],
    ],
    readings: [
      {
        title: "Birthday invitation",
        titleDe: "Einladung zum Geburtstag",
        text: "Liebe Mira, komm zur Geburtstagsfeier mitfeiern! Der Anlass ist am Samstag um sieben im Festsaal. Es gibt Buffet, Geburtstagstorte und Sekt. Bitte kein großes Paket, nur ein Mitbringsel oder eine Glückwunschkarte. Die Gastgeberin bin ich, Tim hilft mit der Dekoration und den Luftballons. Kerzen nicht vergessen. Die Gäste sollen ausgelassen sein. Erscheinst du? Viele Grüße, Sara.",
        translation: "Dear Mira, come join the birthday party! The occasion is Saturday at seven in the banqueting hall. There will be a buffet, birthday cake and sparkling wine. Please no big parcel, only a little gift or a greetings card. I am the host; Tim is helping with the decoration and the balloons. Do not forget candles. The guests should be high-spirited. Will you come? Best wishes, Sara.",
        questions: [
          ["What is the occasion?", "Sara's birthday", ["A wedding", "Sara's birthday", "New Year", "Easter"]],
          ["What should Mira bring?", "A greetings card", ["A tree", "Fireworks", "A greetings card", "A parade"]],
          ["Where is the party?", "In the banqueting hall", ["At the beach", "In the banqueting hall", "At school", "At the bank"]],
        ],
      },
      {
        title: "Christmas Eve",
        titleDe: "Heiligabend",
        text: "An Heiligabend ist das Weihnachtsfest traditionell. Wir schmücken den Tannenbaum und wickeln Mitbringsel in Geschenkpapier mit einer Schleife. Der Nikolaustag war schon da. Es gibt ein Festessen, dann überreichen wir Karten. Die Kinder haben einen Wunsch. Zum Weihnachtsfest kommen Gäste, an Neujahr feiern wir noch einmal mit. Die Silvesterparty ist später: Countdown, Prost, Sekt und Feuerwerk um Mitternacht. Die Veranstaltung zu Hause ist klein, aber festlich.",
        translation: "On Christmas Eve the Christmas festival is traditional. We decorate the Christmas tree and wrap little gifts in wrapping paper with a ribbon. St Nicholas' Day has already been. There is a festive meal, then we hand over cards. The children have a wish. For Christmas guests come; on New Year's Day we join in celebrating again. The New Year's Eve party is later: countdown, cheers, sparkling wine and fireworks at midnight. The event at home is small but festive.",
        questions: [
          ["When do they decorate the tree?", "On Christmas Eve", ["In July", "On Christmas Eve", "Only at carnival", "At midnight on Monday"]],
          ["What happens at midnight on New Year's Eve?", "Fireworks", ["A parade only", "Fireworks", "Easter eggs", "A bank visit"]],
          ["Is the home event large?", "No, it is small", ["Yes, a stadium", "No, it is small", "Only online", "Unknown"]],
        ],
      },
      {
        title: "Carnival Monday",
        titleDe: "Karneval",
        text: "In der Karnevalszeit und am Rosenmontag veranstaltet die Stadt einen Karnevalsumzug. Viele Gäste klatschen. Der Ehrengast fährt vorne. Es ist ein Festtag und eine alte Tradition. Kinder bekommen Süßes, nicht Ostereier — das ist das Osterfest und der Osterhase. Muttertag und Vatertag sind andere Anlässe, mit Strauß und Gratulation. Heute ist die Tanzparty laut. Anstoßen wir später. Der Jahrestag des Vereins ist nächste Woche im Festsaal, ein Straßenfest vor der Tür.",
        translation: "In carnival season and on Rose Monday the town puts on a carnival parade. Many guests clap. The guest of honour rides at the front. It is a feast day and an old tradition. Children get sweets, not Easter eggs — that is Easter and the Easter bunny. Mother's Day and Father's Day are other occasions, with a bunch of flowers and congratulations. Today the dance party is loud. We will toast later. The club anniversary is next week in the banqueting hall, a street festival outside.",
        questions: [
          ["What does the town organise?", "A carnival parade", ["A silent dinner", "A carnival parade", "A bank opening", "A football match only"]],
          ["When are Easter eggs?", "At Easter", ["At carnival", "At Easter", "At midnight only", "On Father's Day"]],
          ["Where is the club anniversary?", "In the banqueting hall", ["At the beach", "In the banqueting hall", "In the forest", "Online"]],
        ],
      },
    ],
    writings: [
      [
        "Invite a friend to your birthday in four sentences.",
        "Lade eine Freundin zu deinem Geburtstag ein.",
        "Ich lade dich zu meiner Geburtstagsfeier ein. Wir richten sie am Samstag im Festsaal aus. Es gibt Torte und Sekt. Bitte ein Mitbringsel und eine Glückwunschkarte.",
        ["Name day and place", "Say what to bring"],
      ],
      [
        "Describe one German holiday in four sentences.",
        "Beschreib einen Festtag in vier Sätzen.",
        "Zum Weihnachtsfest schmücken wir den Tannenbaum. An Heiligabend gibt es ein Festessen. Wir überreichen Mitbringsel. Die Gäste sind festlich und ausgelassen.",
        ["Name the holiday", "Name one tradition"],
      ],
    ],
  }),
  packChapter({
    slug: "comparisons-opinions",
    title: "Comparisons & Opinions",
    titleDe: "Vergleiche und Meinungen",
    blurb: "Compare two things, give an opinion, and agree or disagree politely.",
    skill: "vocab",
    grammar: [
      "Comparative: adjective + -er + als. Superlative: am + -sten. Equality: so + adjective + wie.",
      "meiner Meinung nach + statement. Ich bin einverstanden / nicht einverstanden.",
      "einerseits … andererseits. dafür / dagegen after the verb: Ich bin dafür.",
    ],
    vocab: [
      ["der Vergleich", "the comparison", "Vergleiche"],
      ["vergleichen", "to compare"],
      ["die Meinung", "the opinion", "Meinungen"],
      ["meiner Meinung nach", "in my opinion"],
      ["einverstanden", "agreed / in agreement"],
      ["der Unterschied", "the difference", "Unterschiede"],
      ["unterschiedlich", "different"],
      ["ähnlich", "similar"],
      ["ungleich", "unequal / unlike"],
      ["mehr", "more"],
      ["weniger", "less / fewer"],
      ["am meisten", "the most"],
      ["am wenigsten", "the least"],
      ["so wie", "as … as / like"],
      ["je desto", "the … the … (je … desto)"],
      ["ziemlich", "quite / rather"],
      ["besonders", "especially"],
      ["total", "totally"],
      ["eher", "rather / more likely"],
      ["dagegen", "against that"],
      ["dafür", "for that / in favour"],
      ["überzeugt", "convinced"],
      ["praktisch", "practical"],
      ["unpraktisch", "impractical"],
      ["nützlich", "useful"],
      ["nutzlos", "useless"],
      ["vernünftig", "sensible"],
      ["wunderbar", "wonderful"],
      ["fantastisch", "fantastic"],
      ["furchtbar", "awful"],
      ["schrecklich", "terrible"],
      ["unhöflich", "impolite"],
      ["geduldig", "patient"],
      ["ungeduldig", "impatient"],
      ["ehrlich", "honest"],
      ["unehrlich", "dishonest"],
      ["fair", "fair"],
      ["unfair", "unfair"],
      ["übertrieben", "exaggerated"],
      ["sinnvoll", "sensible / meaningful"],
      ["sinnlos", "pointless"],
      ["der Vorteil", "the advantage", "Vorteile"],
      ["der Nachteil", "the disadvantage", "Nachteile"],
      ["allerdings", "however / though"],
      ["einerseits", "on the one hand"],
      ["andererseits", "on the other hand"],
      ["zustimmen", "to agree"],
      ["widersprechen", "to contradict / disagree"],
      ["der Standpunkt", "the point of view", "Standpunkte"],
      ["äußern", "to express (an opinion)"],
      ["unentschlossen", "undecided"],
      ["unbekannt", "unknown"],
      ["berühmt", "famous"],
      ["beliebt", "popular"],
      ["modern", "modern"],
      ["altmodisch", "old-fashioned"],
      ["mindestens", "at least"],
      ["höchstens", "at most"],
      ["genauso", "just as / exactly as"],
      ["insgesamt", "overall / in total"],
      ["der Gegensatz", "the opposite / contrast", "Gegensätze"],
      ["unbequem", "uncomfortable"],
      ["typisch", "typical"],
      ["ungewöhnlich", "unusual"],
    ],
    phrases: [
      ["Meiner Meinung nach ist das fair.", "In my opinion that is fair."],
      ["Ich bin nicht einverstanden.", "I do not agree."],
      ["Kannst du die zwei Angebote vergleichen?", "Can you compare the two offers?"],
      ["Der Unterschied ist ziemlich klein.", "The difference is quite small."],
      ["Einerseits praktisch, andererseits teuer.", "On the one hand practical, on the other expensive."],
      ["Ich bin dafür.", "I am in favour."],
      ["Ich bin dagegen.", "I am against it."],
      ["Das ist so gut wie das andere.", "That is as good as the other one."],
      ["Je mehr Zeit, desto besser.", "The more time, the better."],
      ["Insgesamt finde ich es sinnvoll.", "Overall I think it is worthwhile."],
      ["Äußerst du deinen Standpunkt?", "Are you expressing your point of view?"],
      ["Das ist übertrieben.", "That is exaggerated."],
    ],
    sentences: [
      ["Wir vergleichen die Vorteile und die Nachteile.", "We compare the advantages and the disadvantages."],
      ["Die zwei Filme sind ähnlich, nicht ungleich.", "The two films are similar, not unlike."],
      ["Ich äußere meinen Standpunkt: der Plan ist vernünftig.", "I express my point of view: the plan is sensible."],
      ["Sie widerspricht höflich, er stimmt zu.", "She disagrees politely; he agrees."],
      ["Am meisten mag ich den modernen Stuhl, am wenigsten den altmodischen.", "I like the modern chair most, the old-fashioned one least."],
      ["Mehr Geld, weniger Zeit: der Gegensatz ist klar.", "More money, less time: the contrast is clear."],
      ["Das Sofa ist unbequem, der Sessel ist genauso hart.", "The sofa is uncomfortable; the armchair is just as hard."],
      ["Ein unhöflicher Kommentar ist furchtbar.", "An impolite comment is awful."],
      ["Sei ehrlich, nicht unehrlich.", "Be honest, not dishonest."],
      ["Der berühmte Koch ist beliebt, der neue ist unbekannt.", "The famous cook is popular; the new one is unknown."],
      ["Ich bin unentschlossen: ist das nützlich oder nutzlos?", "I am undecided: is that useful or useless?"],
      ["Mindestens drei Gründe, höchstens fünf.", "At least three reasons, at most five."],
      ["Ein ungeduldiger Gast ist schrecklich, ein geduldiger ist wunderbar.", "An impatient guest is terrible; a patient one is wonderful."],
      ["Typisch A2: kurz und klar. Ungewöhnlich lang ist unpraktisch.", "Typical A2: short and clear. Unusually long is impractical."],
      ["Besonders der Preis ist unfair, allerdings nicht sinnlos.", "Especially the price is unfair, though not pointless."],
      ["Ich bin total überzeugt, eher für den günstigen Tarif.", "I am totally convinced, rather for the cheaper plan."],
    ],
    readings: [
      {
        title: "Two phones",
        titleDe: "Zwei Handys",
        text: "Meiner Meinung nach ist Handy A praktischer als Handy B. Der Unterschied ist der Preis: A kostet mehr, B weniger. Einerseits hat A einen Vorteil, andererseits hat B weniger Nachteile. Tim ist dafür, Lea ist dagegen. Sie äußert: A ist übertrieben und unpraktisch. Ich bin einverstanden mit Lea. Insgesamt ist B genauso gut, nur weniger berühmt. Ein fairer Vergleich hilft.",
        translation: "In my opinion phone A is more practical than phone B. The difference is the price: A costs more, B less. On the one hand A has an advantage, on the other B has fewer disadvantages. Tim is in favour, Lea is against. She thinks A is exaggerated and impractical. I agree with Lea. Overall B is just as good, only less famous. A fair comparison helps.",
        questions: [
          ["Who is against phone A?", "Lea", ["Tim", "Lea", "Nobody", "The shop"]],
          ["What is the main difference?", "The price", ["The colour only", "The price", "The name", "The box"]],
          ["Does the narrator agree with Lea?", "Yes", ["No", "Yes", "Only on Monday", "Unknown"]],
        ],
      },
      {
        title: "A group chat",
        titleDe: "Gruppenchat",
        text: "Omar: Der Kurs ist total langweilig. Mira: Das ist unfair und unhöflich. Ich widerspreche. Der Kurs ist sinnvoll, nicht sinnlos. Omar: Ich bin unentschlossen. Mira: Sei ehrlich. Je mehr du übst, desto besser. Omar: Okay, ich stimme zu. Allerdings ist die Uhrzeit unbequem. Mira: Eher ungewöhnlich, nicht schrecklich. Mindestens komm dienstags. Höchstens einmal fehlen.",
        translation: "Omar: The course is totally boring. Mira: That is unfair and impolite. I disagree. The course is worthwhile, not pointless. Omar: I am undecided. Mira: Be honest. The more you practise, the better. Omar: Okay, I agree. However the time is uncomfortable. Mira: Rather unusual, not terrible. At least come on Tuesdays. Miss at most once.",
        questions: [
          ["What does Mira say about Omar's first comment?", "It is unfair and impolite", ["It is wonderful", "It is unfair and impolite", "She is silent", "She leaves"]],
          ["What does Omar agree about in the end?", "The course is worthwhile", ["The time is perfect", "The course is worthwhile", "He will never come", "The teacher is famous"]],
          ["How often may he miss?", "At most once", ["Every day", "At most once", "Never mentioned", "Ten times"]],
        ],
      },
      {
        title: "Old or modern?",
        titleDe: "Alt oder modern?",
        text: "Wir vergleichen zwei Hotels. Das moderne Haus ist beliebt und fantastisch, aber ziemlich teuer. Das altmodische Haus ist unbekannt und unbequem, aber vernünftig im Preis. Der Gegensatz ist groß. Typisch Touristen nehmen das berühmte Hotel. Mein Standpunkt: das kleine Haus ist nützlich und nicht nutzlos. Besonders das Frühstück ist wunderbar. Furchtbar ist nur der Lärm. So wie immer: Vorteile und Nachteile.",
        translation: "We compare two hotels. The modern house is popular and fantastic, but quite expensive. The old-fashioned house is unknown and uncomfortable, but sensible in price. The contrast is big. Typical tourists take the famous hotel. My point of view: the small house is useful and not useless. Especially breakfast is wonderful. Only the noise is awful. As always: advantages and disadvantages.",
        questions: [
          ["Which hotel is cheaper?", "The old-fashioned one", ["The modern one", "The old-fashioned one", "Both the same", "Neither exists"]],
          ["What is awful?", "The noise", ["Breakfast", "The noise", "The comparison", "The tourists"]],
          ["What do typical tourists choose?", "The famous hotel", ["The unknown house", "The famous hotel", "No hotel", "Only camping"]],
        ],
      },
    ],
    writings: [
      [
        "Compare two things in four sentences. Use a comparative.",
        "Vergleiche zwei Dinge in vier Sätzen.",
        "Meiner Meinung nach ist der Bus praktischer als das Auto. Er kostet weniger. Allerdings ist er unbequem. Insgesamt bin ich dafür.",
        ["Use als or so wie", "Give one advantage or disadvantage"],
      ],
      [
        "Agree or disagree with a friend in four sentences.",
        "Stimme zu oder widersprich in vier Sätzen.",
        "Ich bin nicht einverstanden. Der Plan ist unfair. Einerseits schnell, andererseits sinnlos. Lass uns ehrlich vergleichen.",
        ["Say einverstanden or not", "Give one reason"],
      ],
    ],
  }),
  packChapter({
    slug: "food-cooking",
    title: "Cooking & the Kitchen",
    titleDe: "Kochen und Küche",
    blurb: "Follow a simple recipe: tools, actions, and the parts of a meal.",
    skill: "vocab",
    grammar: [
      "Recipe steps: zuerst, dann, danach. Separable: braten Sie an, kochen Sie auf, rühren Sie um.",
      "Accusative for food you prepare: Ich schäle die Karotten. Wir würzen die Soße.",
      "The oven: den Backofen auf 180 Grad vorheizen.",
    ],
    vocab: [
      ["der Topf", "the pot", "Töpfe"],
      ["die Pfanne", "the pan", "Pfannen"],
      ["der Herd", "the cooker / hob", "Herde"],
      ["der Backofen", "the oven", "Backöfen"],
      ["aufbacken", "to bake (from frozen) / finish baking"],
      ["braten", "to fry / roast"],
      ["zerkleinern", "to chop up / cut small"],
      ["schälen", "to peel"],
      ["rühren", "to stir"],
      ["die Zutat", "the ingredient", "Zutaten"],
      ["der Teig", "the dough / batter"],
      ["das Mehl", "the flour"],
      ["die Sahne", "the cream"],
      ["der Knoblauch", "the garlic"],
      ["das Gewürz", "the spice", "Gewürze"],
      ["die Kräuter", "the herbs"],
      ["umrühren", "to stir (in)"],
      ["reiben", "to grate"],
      ["der Mixer", "the mixer / blender", "Mixer"],
      ["der Deckel", "the lid", "Deckel"],
      ["die Schüssel", "the bowl", "Schüsseln"],
      ["das Schneidebrett", "the chopping board", "Schneidebretter"],
      ["anbraten", "to fry briefly / sear"],
      ["garen", "to cook until done"],
      ["roh", "raw"],
      ["die Portion", "the portion", "Portionen"],
      ["der Geschmack", "the taste / flavour", "Geschmäcker"],
      ["probieren", "to try / taste"],
      ["vorheizen", "to preheat"],
      ["die Backform", "the baking tin", "Backformen"],
      ["das Backblech", "the baking tray", "Backbleche"],
      ["die Serviette", "the napkin", "Servietten"],
      ["der Topflappen", "the oven glove", "Topflappen"],
      ["anrichten", "to plate / serve up"],
      ["abschmecken", "to season to taste"],
      ["die Beilage", "the side dish", "Beilagen"],
      ["die Vorspeise", "the starter", "Vorspeisen"],
      ["die Hauptspeise", "the main course", "Hauptspeisen"],
      ["würzen", "to season"],
      ["zubereiten", "to prepare (food)"],
      ["die Zubereitung", "the preparation"],
      ["der Messbecher", "the measuring jug", "Messbecher"],
      ["köcheln", "to simmer"],
      ["aufkochen", "to bring to the boil"],
      ["die Soße", "the sauce", "Soßen"],
      ["das Gericht", "the dish", "Gerichte"],
      ["das Menü", "the set menu", "Menüs"],
      ["das Gemüse", "the vegetables"],
      ["das Obst", "the fruit"],
      ["die Karotte", "the carrot", "Karotten"],
      ["der Paprika", "the pepper (vegetable)", "Paprikas"],
      ["der Champignon", "the mushroom (cultivated)", "Champignons"],
      ["die Mikrowelle", "the microwave", "Mikrowellen"],
      ["der Wasserkocher", "the kettle", "Wasserkocher"],
      ["auftauen", "to thaw / defrost"],
      ["einfrieren", "to freeze"],
      ["kneten", "to knead"],
      ["der Schneebesen", "the whisk", "Schneebesen"],
      ["der Pfannenwender", "the spatula", "Pfannenwender"],
      ["das Backpapier", "the baking paper"],
      ["knusprig", "crispy"],
      ["saftig", "juicy"],
      ["anbrennen", "to burn (food)"],
      ["das Rezeptbuch", "the recipe book", "Rezeptbücher"],
    ],
    phrases: [
      ["Heiz den Backofen vor.", "Preheat the oven."],
      ["Zuerst das Gemüse schälen und zerkleinern.", "First peel and chop the vegetables."],
      ["Rühr den Teig in der Schüssel um.", "Stir the dough in the bowl."],
      ["Nicht anbrennen lassen!", "Do not let it burn!"],
      ["Probier die Soße!", "Try the sauce!"],
      ["Eine Portion Hauptspeise, bitte.", "One portion of the main course, please."],
      ["Die Zutaten stehen im Rezeptbuch.", "The ingredients are in the recipe book."],
      ["Deckel auf den Topf.", "Lid on the pot."],
      ["Mit dem Topflappen anfassen.", "Use the oven glove to hold it."],
      ["Vorspeise, dann Hauptspeise, Beilage extra.", "Starter, then main course, side dish extra."],
      ["Tauen Sie die Champignons auf.", "Defrost the mushrooms."],
      ["Würzen und abschmecken.", "Season and adjust the taste."],
    ],
    sentences: [
      ["Ich brate Knoblauch und Paprika in der Pfanne an.", "I fry garlic and pepper in the pan."],
      ["Der Teig braucht Mehl, Sahne und den Mixer.", "The dough needs flour, cream and the blender."],
      ["Zerkleinere die Karotten auf dem Schneidebrett, nicht roh essen.", "Chop the carrots on the chopping board; do not eat them raw."],
      ["Die Soße köchelt auf dem Herd, dann kocht sie auf.", "The sauce simmers on the hob, then it comes to the boil."],
      ["Reib das Gewürz, rühr die Kräuter unter.", "Grate the spice, stir in the herbs."],
      ["Das Gericht gart im Backofen auf dem Backblech mit Backpapier.", "The dish cooks in the oven on the tray with baking paper."],
      ["Knete den Teig und füll die Backform.", "Knead the dough and fill the baking tin."],
      ["Mit dem Schneebesen die Sahne schlagen, mit dem Messbecher messen.", "Whisk the cream with the whisk; measure with the measuring jug."],
      ["Der Pfannenwender liegt neben der Mikrowelle.", "The spatula is next to the microwave."],
      ["Friere das Obst ein, tauen Sie es vor der Zubereitung auf.", "Freeze the fruit; defrost it before preparation."],
      ["Das Menü hat drei Gänge: Vorspeise, Hauptspeise, Beilage.", "The set menu has three courses: starter, main, side."],
      ["Die Champignons sollen saftig sein, das Brot knusprig.", "The mushrooms should be juicy, the bread crispy."],
      ["Ohne Geschmack ist die Zubereitung langweilig.", "Without flavour the preparation is boring."],
      ["Der Wasserkocher ist schnell, der Topf ist groß.", "The kettle is quick; the pot is large."],
      ["Richte das Gericht an und leg eine Serviette dazu.", "Plate the dish and put a napkin with it."],
      ["Zwei Portionen reichen, nicht anbrennen.", "Two portions are enough; do not burn it."],
    ],
    readings: [
      {
        title: "A simple recipe",
        titleDe: "Ein einfaches Gericht",
        text: "Zuerst den Backofen vorheizen. Schäl Karotten und Paprika, zerkleinere sie auf dem Schneidebrett. Brat Knoblauch in der Pfanne an. Die Zutaten kommen in den Topf mit Deckel. Rühr die Soße um und lass sie köcheln, nicht anbrennen. Würz mit Kräutern und Gewürz, dann abschmecken. Die Beilage ist knuspriges Brot — aufbacken. Richt zwei Portionen an. Das Rezeptbuch sagt: zwanzig Minuten Zubereitung.",
        translation: "First preheat the oven. Peel carrots and peppers, cut them on the chopping board. Fry garlic in the pan. The ingredients go in the pot with the lid. Stir the sauce and let it simmer; do not burn it. Season with herbs and spice, then adjust the taste. The side dish is crispy bread. Plate two portions. The recipe book says: twenty minutes' preparation.",
        questions: [
          ["What do you do first?", "Preheat the oven", ["Eat raw carrots", "Preheat the oven", "Freeze the bread", "Open the microwave"]],
          ["Where do you chop the vegetables?", "On the chopping board", ["On the sofa", "On the chopping board", "In the kettle", "In the napkins"]],
          ["How many portions?", "Two", ["One", "Two", "Ten", "None"]],
        ],
      },
      {
        title: "Dinner for guests",
        titleDe: "Essen für Gäste",
        text: "Heute gibt es ein Menü. Vorspeise: Obst und Sahne. Hauptspeise: ein saftiges Gericht mit Champignons vom Herd. Ich messe Mehl mit dem Messbecher und knete den Teig. Der Mixer und der Schneebesen sind schon da. Die Backform liegt auf dem Backblech mit Backpapier. Nimm den Topflappen, der Ofen ist heiß. Gäste bekommen eine Serviette. Roh darf nur der Salat sein, nicht das Gemüse in der Soße.",
        translation: "Today there is a set menu. Starter: fruit and cream. Main course: a juicy dish with mushrooms from the hob. I measure flour with the measuring jug and knead the dough. The blender and the whisk are already there. The baking tin is on the tray with baking paper. Take the oven glove; the oven is hot. Guests get a napkin. Only the salad may be raw, not the vegetables in the sauce.",
        questions: [
          ["What is the starter?", "Fruit and cream", ["Only mushrooms", "Fruit and cream", "Burnt bread", "The kettle"]],
          ["Why the oven glove?", "The oven is hot", ["The fruit is cold", "The oven is hot", "There is no lid", "The mixer is loud"]],
          ["What may stay raw?", "The salad", ["The sauce", "The salad", "The dough", "The mushrooms in the pan"]],
        ],
      },
      {
        title: "Leftovers",
        titleDe: "Reste",
        text: "Das Essen vom Sonntag ist im Topf. Friere eine Portion ein. Vor dem Essen in der Mikrowelle auftauen, dann auf dem Herd aufkochen. Mit dem Pfannenwender in der Pfanne kurz braten, dann probier es wieder. Der Wasserkocher ist für Tee, nicht für die Soße. Der Geschmack ist gut, wenn du Kräuter nachschüttest. Ohne Rezeptbuch geht es auch: rühren, garen, anrichten.",
        translation: "Sunday's food is in the pot. Freeze one portion. Before eating, defrost it in the microwave, then bring it to the boil on the hob. Fry it briefly in the pan with the spatula, then it tastes good again. The kettle is for tea, not for the sauce. The flavour is good if you add more herbs. It works without the recipe book too: stir, cook through, plate up.",
        questions: [
          ["What should you do with one portion?", "Freeze it", ["Throw it away", "Freeze it", "Give it to the bank", "Bake it as a cake only"]],
          ["What is the kettle for?", "Tea", ["The sauce", "Tea", "The dough", "The napkins"]],
          ["What makes the flavour good again?", "Adding herbs", ["The kettle", "Adding herbs", "Eating raw flour", "No lid"]],
        ],
      },
    ],
    writings: [
      [
        "Write a four-step recipe with kitchen tools.",
        "Schreib ein Rezept in vier Schritten.",
        "Zuerst den Backofen vorheizen. Dann Gemüse schälen und zerkleinern. In der Pfanne anbraten. Mit Kräutern würzen und anrichten.",
        ["Use zuerst / dann", "Name two tools or actions"],
      ],
      [
        "Describe a meal with starter and main course.",
        "Beschreib ein Essen mit Vorspeise und Hauptspeise.",
        "Als Vorspeise gibt es Obst. Die Hauptspeise ist ein Gericht mit Soße. Die Beilage ist knusprig. Es schmeckt saftig.",
        ["Name Vorspeise and Hauptspeise", "Use probieren or eine Portion"],
      ],
    ],
  }),
  packChapter({
    slug: "nature-environment",
    title: "Nature & the Environment",
    titleDe: "Natur und Umwelt",
    blurb: "Name animals and landscapes, then sort rubbish and save energy at A2.",
    skill: "vocab",
    grammar: [
      "man + verb for rules: Man trennt den Müll. Man schaltet das Licht aus.",
      "Location: im Mischwald, am Strand, auf der Weide, an der Höhle, am Ufer.",
      "Accusative: Wir schützen die Umwelt. Wir recyceln den Plastikmüll.",
    ],
    vocab: [
      ["der Mischwald", "the mixed forest", "Mischwälder"],
      ["der Laubbaum", "the deciduous tree", "Laubbäume"],
      ["das Ufer", "the shore / bank", "Ufer"],
      ["das Wildtier", "the wild animal", "Wildtiere"],
      ["der Zugvogel", "the migratory bird", "Zugvögel"],
      ["die Wildblume", "the wildflower", "Wildblumen"],
      ["der Felsen", "the rock / cliff", "Felsen"],
      ["der Hang", "the slope", "Hänge"],
      ["die Quelle", "the spring (water)", "Quellen"],
      ["der Teich", "the pond", "Teiche"],
      ["die Weide", "the pasture", "Weiden"],
      ["die Umwelt", "the environment"],
      ["der Umweltschutz", "environmental protection"],
      ["recyceln", "to recycle"],
      ["trennen", "to separate (waste)"],
      ["der Biomüll", "the organic waste"],
      ["der Restmüll", "the residual waste"],
      ["der Papiermüll", "the paper waste"],
      ["der Glascontainer", "the bottle bank", "Glascontainer"],
      ["die Tonne", "the bin", "Tonnen"],
      ["die Wertstofftonne", "the recyclables bin", "Wertstofftonnen"],
      ["der Lärm", "the noise"],
      ["die Luft", "the air"],
      ["die Energie", "energy"],
      ["der Strom", "the electricity"],
      ["der Stromverbrauch", "the electricity use"],
      ["verschmutzen", "to pollute"],
      ["die Verschmutzung", "the pollution"],
      ["schützen", "to protect"],
      ["der Lebensraum", "the habitat", "Lebensräume"],
      ["der Waldweg", "the forest path", "Waldwege"],
      ["der Pfad", "the path", "Pfade"],
      ["wachsen", "to grow"],
      ["blühen", "to bloom"],
      ["das Laub", "the foliage / leaves"],
      ["der Zweig", "the branch / twig", "Zweige"],
      ["das Insekt", "the insect", "Insekten"],
      ["die Ameise", "the ant", "Ameisen"],
      ["die Mülltrennung", "waste separation"],
      ["wiederverwenden", "to reuse"],
      ["der Plastikmüll", "the plastic waste"],
      ["umweltfreundlich", "environmentally friendly"],
      ["schädlich", "harmful"],
      ["kompostieren", "to compost"],
      ["der Kompost", "the compost"],
      ["das Naturschutzgebiet", "the nature reserve", "Naturschutzgebiete"],
      ["der Strand", "the beach", "Strände"],
      ["die Welle", "the wave", "Wellen"],
      ["die Düne", "the dune", "Dünen"],
      ["der Schatten", "the shade / shadow"],
      ["die Umweltgruppe", "the environmental group", "Umweltgruppen"],
      ["müllsammeln", "to collect litter"],
      ["das Verkehrsmittel", "the means of transport", "Verkehrsmittel"],
      ["energiesparen", "to save energy"],
      ["stromsparend", "energy-saving"],
      ["der Wertstoff", "the recyclable material", "Wertstoffe"],
      ["sortieren", "to sort"],
      ["der gelbe Sack", "the yellow recycling bag", "gelben Säcke"],
      ["der Sondermüll", "hazardous waste"],
      ["die Batterie", "the battery", "Batterien"],
      ["die Pfandflasche", "the deposit bottle", "Pfandflaschen"],
      ["der Wasserfall", "the waterfall", "Wasserfälle"],
      ["die Höhle", "the cave", "Höhlen"],
      ["der Dachs", "the badger", "Dachse"],
    ],
    phrases: [
      ["Bitte den Müll trennen.", "Please separate the rubbish."],
      ["Der gelbe Sack ist für Plastikmüll.", "The yellow bag is for plastic waste."],
      ["Batterien gehören nicht in den Restmüll.", "Batteries do not go in residual waste."],
      ["Die Umweltgruppe sammelt Müll im Schatten unter dem Laubbaum.", "The environmental group collects litter in the shade under the deciduous tree."],
      ["Die Luft am See ist gut, der Lärm ist wenig.", "The air at the lake is good; there is little noise."],
      ["Schalt das Licht aus und spar Energie.", "Switch the light off and save energy."],
      ["Ist das umweltfreundlich?", "Is that environmentally friendly?"],
      ["Der Dachs läuft über die Weide.", "The badger runs across the pasture."],
      ["Pfandflaschen zum Container.", "Deposit bottles to the bottle bank."],
      ["Im Naturschutzgebiet keine Wildblumen pflücken.", "Do not pick wildflowers in the nature reserve."],
      ["Kompostier den Biomüll.", "Compost the organic waste."],
      ["Der Pfad führt zum Wasserfall.", "The path leads to the waterfall."],
    ],
    sentences: [
      ["Im Mischwald wachsen Laubbäume, Laub und Zweige.", "In the mixed forest deciduous trees, foliage and twigs grow."],
      ["Insekten und Ameisen leben zwischen den Wildblumen.", "Insects and ants live among the wildflowers."],
      ["Die Quelle fließt in den Teich, das Ufer ist nah.", "The spring flows into the pond; the shore is near."],
      ["Am Strand ist die Düne, die Wellen sind stark.", "At the beach there is the dune; the waves are strong."],
      ["Wir sortieren Wertstoffe in die Wertstofftonne.", "We sort recyclables into the recyclables bin."],
      ["Papiermüll und Glascontainer stehen nebeneinander.", "Paper waste and the bottle bank stand next to each other."],
      ["Sondermüll ist schädlich für den Lebensraum.", "Hazardous waste is harmful to the habitat."],
      ["Ein umweltfreundliches Verkehrsmittel spart Strom.", "An environmentally friendly means of transport saves electricity."],
      ["Die Verschmutzung der Luft kommt auch vom Lärm der Stadt.", "Air pollution also comes from the noise of the city."],
      ["Wildtiere im Naturschutzgebiet müssen wir schützen.", "We must protect wild animals in the nature reserve."],
      ["Der Waldweg ist nass, der Hang ist steil, die Höhle ist dunkel.", "The forest path is wet, the slope is steep, the cave is dark."],
      ["Felsen am Wasserfall nicht werfen.", "Do not throw rocks at the waterfall."],
      ["Wiederverwende die Tüte, recycel den Plastikmüll.", "Reuse the bag; recycle the plastic waste."],
      ["Der Kompost ist für Biomüll, die Tonne für Restmüll.", "The compost is for organic waste; the bin is for residual waste."],
      ["Der Stromverbrauch sinkt, wenn wir energiesparen.", "Electricity use falls when we save energy."],
      ["Ein stromsparendes Verkehrsmittel hilft beim Energiesparen.", "An energy-saving means of transport helps with saving energy."],
    ],
    readings: [
      {
        title: "A walk in the forest",
        titleDe: "Spaziergang im Wald",
        text: "Am Sonntag geht die Umweltgruppe in den Mischwald. Der Waldweg ist ruhig, nur Zugvögel und ein Dachs. Am Teich sitzen wir im Schatten. Wildblumen blühen auf der Weide, Insekten fliegen. Die Quelle ist klar, keine Verschmutzung. Bitte keinen Lärm, das ist ein Naturschutzgebiet. Wir sammeln Müll, der Abfall kommt in die Tasche, nicht in den Lebensraum. Der Pfad führt später zum Ufer und zu einem kleinen Wasserfall.",
        translation: "On Sunday the environmental group goes into the mixed forest. The forest path is quiet, only migratory birds and a badger. At the pond we sit in the shade. Wildflowers bloom on the pasture; insects fly. The spring is clear, no pollution. Please no noise; this is a nature reserve. We collect litter; the waste goes in the bag, not into the habitat. The path later leads to the shore and a small waterfall.",
        questions: [
          ["Which animal do they see?", "A badger", ["A whale", "A badger", "A horse in a bank", "A cat at home only"]],
          ["Why no noise?", "It is a nature reserve", ["It is night", "It is a nature reserve", "There is no path", "The lake is closed"]],
          ["Where does the waste go?", "In the bag", ["On the earth", "In the bag", "In the stream", "In the cave"]],
        ],
      },
      {
        title: "Sorting rubbish",
        titleDe: "Mülltrennung",
        text: "In unserem Haus gibt es Mülltrennung. Biomüll in den Kompost, Papiermüll in eine Tonne, Glas in den Glascontainer, Plastikmüll in den gelben Sack. Batterien und Sondermüll sind schädlich: nicht in den Restmüll. Pfandflaschen kann man wiederverwenden. Wertstoffe sortieren ist Umweltschutz. Man schützt die Umwelt, wenn man recycelt. Das ist umweltfreundlich und nicht schwer.",
        translation: "In our building there is waste separation. Organic waste in the compost, paper waste in a bin, glass in the bottle bank, plastic waste in the yellow bag. Batteries and hazardous waste are harmful: not in residual waste. Deposit bottles can be reused. Sorting recyclables is environmental protection. You protect the environment if you recycle. That is environmentally friendly and not hard.",
        questions: [
          ["Where do batteries go?", "Not in residual waste", ["In the compost", "Not in residual waste", "In the yellow bag with food", "In the lake"]],
          ["What is the yellow bag for?", "Plastic waste", ["Only paper", "Plastic waste", "Only stones", "Bees"]],
          ["What can you reuse?", "Deposit bottles", ["Hazardous waste", "Deposit bottles", "The cave", "The waterfall"]],
        ],
      },
      {
        title: "Save energy",
        titleDe: "Energie sparen",
        text: "Unser Stromverbrauch ist zu hoch. Bitte stromsparend leben und Geräte nicht den ganzen Tag an. Energiesparen hilft dem Lebensraum und der Luft. Ein umweltfreundliches Verkehrsmittel ist besser als das Auto. Am Strand an der Düne und am Hang brauchen wir keinen Strom. Felsen und Wellen sind gratis. Ameisen und Laub brauchen keine Batterie. Schädlich ist die Verschmutzung, nicht der Schatten unter dem Laubbaum. Der Zweig fällt, der Laubbaum wächst weiter.",
        translation: "Our electricity use is too high. Please live in an energy-saving way and do not leave devices on all day. Saving energy helps the habitat and the air. An environmentally friendly means of transport is better than the car. At the beach on the dune and on the slope we need no electricity. Rocks and waves are free. Ants and foliage need no battery. Pollution is harmful, not the shade under the deciduous tree. The twig falls; the deciduous tree keeps growing.",
        questions: [
          ["What is too high?", "Electricity use", ["The hill", "Electricity use", "The picnic", "The fox"]],
          ["How should people live?", "In an energy-saving way", ["Only at night", "In an energy-saving way", "Without air", "In the cave"]],
          ["What is harmful?", "Pollution", ["Shade", "Pollution", "Waves", "Leaves"]],
        ],
      },
    ],
    writings: [
      [
        "Write four sentences about a walk in nature.",
        "Schreib vier Sätze über einen Spaziergang in der Natur.",
        "Wir gehen durch den Mischwald zum Ufer. Ein Dachs läuft über die Weide. An der Düne müllsammeln wir. Die Umweltgruppe trifft sich im Schatten.",
        ["Name two places", "Name one animal or plant"],
      ],
      [
        "Explain how you sort rubbish at home in four sentences.",
        "Erklär die Mülltrennung zu Hause.",
        "Wir trennen den Müll. Biomüll kommt auf den Kompost. Plastikmüll in den gelben Sack. Batterien sind Sondermüll.",
        ["Name two bins or bags", "Say what is schädlich or umweltfreundlich"],
      ],
    ],
  }),
  packChapter({
    slug: "appointments-services",
    title: "Appointments & Local Services",
    titleDe: "Termine und Dienstleistungen",
    blurb: "Book a haircut, a repair or a specialist, and complain if something is broken.",
    skill: "vocab",
    grammar: [
      "vereinbaren + accusative: Ich vereinbare einen Haarschnitt. Können wir die Abholung vereinbaren?",
      "Separable: rufen Sie mich auf, schleppen Sie das Auto ab, tauschen Sie das Teil aus.",
      "Modal at the service desk: Können Sie das heute ausbessern? Das Gerät muss funktionieren.",
    ],
    vocab: [
      ["die Kosmetikerin", "the beautician", "Kosmetikerinnen"],
      ["die Friseurin", "the hairdresser (f)", "Friseurinnen"],
      ["der Haarschnitt", "the haircut", "Haarschnitte"],
      ["föhnen", "to blow-dry"],
      ["die Haarwäsche", "the hair wash", "Haarwäschen"],
      ["der Klempner", "the plumber", "Klempner"],
      ["der Elektriker", "the electrician", "Elektriker"],
      ["der Mechaniker", "the mechanic", "Mechaniker"],
      ["die Reparatur", "the repair", "Reparaturen"],
      ["ausbessern", "to mend / patch up"],
      ["kaputt", "broken"],
      ["defekt", "defective"],
      ["der Handwerker", "the tradesperson", "Handwerker"],
      ["die Reparaturannahme", "the repair reception desk", "Reparaturannahmen"],
      ["der Notdienst", "the emergency service", "Notdienste"],
      ["der Schlüsseldienst", "the locksmith service"],
      ["vereinbaren", "to arrange / agree (an appointment)"],
      ["die Reservierung", "the reservation", "Reservierungen"],
      ["der Warteraum", "the waiting room", "Warteräume"],
      ["aufrufen", "to call (a name / number)"],
      ["die Kundennummer", "the customer number", "Kundennummern"],
      ["der Auftrag", "the job / order", "Aufträge"],
      ["die Wartezeit", "the waiting time", "Wartezeiten"],
      ["der Techniker", "the technician", "Techniker"],
      ["die Garantie", "the guarantee / warranty", "Garantien"],
      ["die Reklamation", "the complaint (about goods)", "Reklamationen"],
      ["reklamieren", "to make a complaint (goods)"],
      ["sich beschweren", "to complain"],
      ["die Beschwerde", "the complaint", "Beschwerden"],
      ["der Kundenservice", "customer service"],
      ["die Hotline", "the hotline", "Hotlines"],
      ["der Zahnarzt", "the dentist (m)", "Zahnärzte"],
      ["die Zahnärztin", "the dentist (f)", "Zahnärztinnen"],
      ["der Optiker", "the optician", "Optiker"],
      ["die Autowerkstatt", "the garage (cars)", "Autowerkstätten"],
      ["die Inspektion", "the inspection / service", "Inspektionen"],
      ["der Kostenvoranschlag", "the quote / estimate", "Kostenvoranschläge"],
      ["funktionieren", "to work / function"],
      ["die Störung", "the fault / disruption", "Störungen"],
      ["austauschen", "to replace / exchange"],
      ["der Bereitschaftsdienst", "the on-call service"],
      ["die Warteliste", "the waiting list", "Wartelisten"],
      ["der Installateur", "the installer / plumber", "Installateure"],
      ["die Hausverwaltung", "the property management", "Hausverwaltungen"],
      ["der Vermieter", "the landlord", "Vermieter"],
      ["die Abholung", "the collection / pickup", "Abholungen"],
      ["liefern", "to deliver"],
      ["das Ersatzteil", "the spare part", "Ersatzteile"],
      ["verfügbar", "available"],
      ["ausgebucht", "fully booked"],
      ["der Facharzt", "the specialist doctor", "Fachärzte"],
      ["der Überweisungsschein", "the referral form", "Überweisungsscheine"],
      ["telefonisch", "by phone"],
      ["der Ersatztermin", "the replacement appointment", "Ersatztermine"],
      ["die Wartung", "the maintenance"],
      ["der TÜV", "the vehicle inspection (TÜV)"],
      ["der Motorschaden", "the engine damage", "Motorschäden"],
      ["abschleppen", "to tow"],
      ["undicht", "leaking"],
      ["der Rohrbruch", "the burst pipe", "Rohrbrüche"],
      ["der Stromausfall", "the power cut", "Stromausfälle"],
      ["die Sicherung", "the fuse", "Sicherungen"],
      ["die Glühbirne", "the light bulb", "Glühbirnen"],
      ["der Augenarzt", "the eye doctor", "Augenärzte"],
    ],
    phrases: [
      ["Ich möchte einen Haarschnitt vereinbaren.", "I would like to arrange a haircut."],
      ["Sind Sie heute ausgebucht?", "Are you fully booked today?"],
      ["Das Gerät ist kaputt. Können Sie es ausbessern?", "The device is broken. Can you mend it?"],
      ["Bitte einen Kostenvoranschlag.", "A quote, please."],
      ["Die Wartezeit ist zu lang.", "The waiting time is too long."],
      ["Rufen Sie meine Kundennummer auf.", "Call out my customer number."],
      ["Ich beschwere mich beim Kundenservice.", "I am complaining to customer service."],
      ["Haben Sie ein Ersatzteil verfügbar?", "Do you have a spare part available?"],
      ["Der Klempner kommt wegen des Rohrbruchs.", "The plumber is coming because of the burst pipe."],
      ["Nach dem Motorschaden bitte abschleppen.", "After the engine damage, please tow it."],
      ["Die Reservierung war telefonisch.", "The reservation was by phone."],
      ["Ist die Reparatur noch in der Garantie?", "Is the repair still under warranty?"],
    ],
    sentences: [
      ["Die Kosmetikerin und die Friseurin machen Haarwäsche, Haarschnitt und föhnen.", "The beautician and the hairdresser wash, cut and blow-dry."],
      ["Der Elektriker tauscht die Sicherung und die Glühbirne aus.", "The electrician replaces the fuse and the bulb."],
      ["Beim Zahnarzt und beim Augenarzt sitzen wir im Warteraum.", "At the dentist and the eye doctor we sit in the waiting room."],
      ["Der Facharzt braucht einen Überweisungsschein.", "The specialist needs a referral form."],
      ["Die Autowerkstatt macht die Inspektion und den TÜV.", "The garage does the service and the TÜV."],
      ["Der Mechaniker liefert das Ersatzteil nach der Abholung.", "The mechanic delivers the spare part after collection."],
      ["Der Notdienst und der Bereitschaftsdienst sind nachts da.", "The emergency service and the on-call service are there at night."],
      ["Der Schlüsseldienst öffnet die Tür, die Hausverwaltung hat keinen Schlüssel.", "The locksmith opens the door; property management has no key."],
      ["Der Vermieter schickt einen Installateur, weil das Rohr undicht ist.", "The landlord sends an installer because the pipe is leaking."],
      ["Die Hotline nimmt die Reklamation und die Beschwerde.", "The hotline takes the complaint about the goods and the complaint."],
      ["Der Auftrag notiert die Störung: das Gerät ist defekt und funktioniert nicht.", "The job notes the fault: the device is defective and does not work."],
      ["Ohne Wartung gibt es bald einen Motorschaden.", "Without maintenance there will soon be engine damage."],
      ["Die Warteliste für den Optiker ist lang, ein Ersatztermin ist verfügbar.", "The waiting list for the optician is long; a replacement appointment is available."],
      ["Bei Stromausfall kommt der Techniker, nicht die Kosmetikerin.", "In a power cut the technician comes, not the beautician."],
      ["Reklamieren Sie an der Reparaturannahme, nicht beim Zahnarzt.", "Complain at the repair desk, not at the dentist."],
      ["Der Handwerker ist ausgebucht, die Reservierung geht nächste Woche.", "The tradesperson is fully booked; the reservation is next week."],
    ],
    readings: [
      {
        title: "Haircut booking",
        titleDe: "Termin beim Friseur",
        text: "Guten Tag, ich möchte telefonisch einen Haarschnitt bei der Friseurin vereinbaren. Haarwäsche und föhnen auch. Sind Sie am Freitag ausgebucht? Sonst komme ich auf die Warteliste. Meine Kundennummer habe ich. Im Warteraum ist die Wartezeit oft kurz. Eine Reservierung für 15 Uhr wäre gut. Falls der Termin ausfällt, bitte einen Ersatztermin. Viele Grüße, Nina.",
        translation: "Hello, I would like to arrange a haircut with the hairdresser by phone. Hair wash and blow-dry as well. Are you fully booked on Friday? Otherwise I will go on the waiting list. I have my customer number. In the waiting room the waiting time is often short. A reservation for 3 p.m. would be good. If the appointment is cancelled, please give a replacement appointment. Kind regards, Nina.",
        questions: [
          ["How does Nina book?", "By phone", ["Only by letter", "By phone", "At the garage", "At the lake"]],
          ["What extra does she want?", "Wash and blow-dry", ["A TÜV", "Wash and blow-dry", "A tow", "A fuse"]],
          ["What if Friday is full?", "Waiting list", ["She buys a car", "Waiting list", "She calls the dentist only", "She tows the bus"]],
        ],
      },
      {
        title: "Something is leaking",
        titleDe: "Es ist undicht",
        text: "Hallo Hausverwaltung, das Rohr ist undicht, vielleicht ein Rohrbruch. Der Vermieter sagt, ein Klempner oder Installateur soll kommen. Der Notdienst ist teuer, der Bereitschaftsdienst auch. Bitte einen Kostenvoranschlag vor der Reparatur. Die Sicherung und die Glühbirne im Bad sind defekt; da brauchen wir den Elektriker. Das Gerät in der Küche funktioniert nicht. Auftrag: heute, wenn verfügbar.",
        translation: "Hello property management, the pipe is leaking, perhaps a burst pipe. The landlord says a plumber or installer should come. The emergency service is expensive, the on-call service too. Please a quote before the repair. The fuse and the bulb in the bathroom are defective; we need the electrician for that. The kitchen device does not work. Job: today, if available.",
        questions: [
          ["What is leaking?", "A pipe", ["The car", "A pipe", "The hairdryer", "The referral"]],
          ["What should come before the repair?", "A quote", ["A haircut", "A quote", "The TÜV", "Fireworks"]],
          ["Who is needed for the fuse?", "The electrician", ["The dentist", "The electrician", "The optician", "The fox"]],
        ],
      },
      {
        title: "Car and complaint",
        titleDe: "Auto und Reklamation",
        text: "Nach dem Motorschaden schleppt die Autowerkstatt das Auto ab. Der Mechaniker macht Wartung, Inspektion und TÜV an der Reparaturannahme. Ein Ersatzteil ist verfügbar, die Garantie gilt noch. Trotzdem reklamieren wir: die Störung kommt wieder. Der Kundenservice an der Hotline nimmt die Beschwerde. Der Techniker tauscht das Teil aus. Der Facharzt ist heute unwichtig — nur der Augenarzt-Ersatztermin steht noch. Der Schlüsseldienst war gestern, nicht der Zahnarzt.",
        translation: "After the engine damage the garage tows the car. The mechanic does maintenance, service and TÜV at the repair desk. A spare part is available; the warranty still applies. Still we complain: the fault comes back. Customer service on the hotline takes the complaint. The technician replaces the part. The specialist is not important today — only the replacement eye-doctor appointment is still there. The locksmith was yesterday, not the dentist.",
        questions: [
          ["What happens after the engine damage?", "The garage tows the car", ["They bake a cake", "The garage tows the car", "They go to the forest", "They open a bank account"]],
          ["Does the warranty still apply?", "Yes", ["No", "Yes", "Only for hair", "Unknown"]],
          ["Who takes the complaint?", "Customer service on the hotline", ["The fox", "Customer service on the hotline", "The Easter bunny", "The landlord only"]],
        ],
      },
    ],
    writings: [
      [
        "Book a hairdresser appointment in four sentences.",
        "Vereinbare einen Friseurtermin in vier Sätzen.",
        "Ich möchte einen Haarschnitt vereinbaren. Bitte auch Haarwäsche. Sind Sie am Samstag ausgebucht? Meine Kundennummer ist 442.",
        ["Use vereinbaren", "Ask if they are ausgebucht"],
      ],
      [
        "Write a complaint about a broken device or a leak.",
        "Schreib eine Beschwerde: etwas ist kaputt oder undicht.",
        "Das Rohr ist undicht. Bitte einen Klempner schicken. Ich brauche einen Kostenvoranschlag. Der Notdienst soll heute kommen, wenn verfügbar.",
        ["Name the problem", "Name the person or service you need"],
      ],
    ],
  }),
];
