import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const a2ChaptersPart1: ChapterSource[] = [
  chapter(
    "shopping",
    "Shopping & Prices",
    "Einkaufen und Preise",
    "Read receipts and shop signs, then ask for sizes, prices, and bags.",
    "mixed",
    [
      "This/these: der hier, die hier. Was kostet das? / Was kosten die?",
      "zu + adjective: zu teuer. nicht so teuer is a softer alternative.",
      "Accusative after ich möchte / ich kaufe: ich kaufe einen Pullover.",
    ],
    {
      vocab: [
        vocab("das Geschäft", "the shop", undefined, "Geschäfte"),
        vocab("der Markt", "the market", undefined, "Märkte"),
        vocab("der Supermarkt", "the supermarket", undefined, "Supermärkte"),
        vocab("der Preis", "the price", undefined, "Preise"),
        vocab("teuer", "expensive"),
        vocab("billig", "cheap"),
        vocab("reduziert", "reduced"),
        vocab("bar", "in cash"),
        vocab("die Karte", "the card", undefined, "Karten"),
        vocab("die Tüte", "the bag", undefined, "Tüten"),
        vocab("die Größe", "the size", undefined, "Größen"),
        vocab("die Probe", "the sample", undefined, "Proben"),
        vocab("kaufen", "to buy"),
        vocab("verkaufen", "to sell"),
        vocab("zahlen", "to pay"),
        vocab("kosten", "to cost"),
        vocab("brauchen", "to need"),
        vocab("die Schlange", "the queue", undefined, "Schlangen"),
        vocab("die Kasse", "the checkout", undefined, "Kassen"),
        vocab("der Verkäufer", "the salesperson (m)", undefined, "Verkäufer"),
        vocab("die Verkäuferin", "the salesperson (f)", undefined, "Verkäuferinnen"),
        vocab("das Angebot", "the offer", undefined, "Angebote"),
        vocab("das Sonderangebot", "the special offer"),
        vocab("die Quittung", "the receipt", undefined, "Quittungen"),
        vocab("zurückgeben", "to return (goods)"),
        vocab("umtauschen", "to exchange"),
        vocab("passen", "to fit"),
        vocab("gefallen", "to like (appearance)"),
        vocab("anderes", "something else"),
        vocab("nur", "only"),
        vocab("noch", "still / another"),
        vocab("der Euro", "the euro", undefined, "Euro"),
      ],
      phrases: [
        phrase("Was kostet das?", "How much is that?"),
        phrase("Das ist zu teuer.", "That is too expensive."),
        phrase("Haben Sie das in Größe M?", "Do you have that in size M?"),
        phrase("Ich zahle bar.", "I'll pay in cash."),
        phrase("Kann ich mit Karte zahlen?", "Can I pay by card?"),
        phrase("Eine Tüte bitte.", "A bag, please."),
        phrase("Wo ist die Kasse?", "Where is the checkout?"),
        phrase("Es gibt ein Sonderangebot.", "There is a special offer."),
        phrase("Das passt nicht.", "That doesn't fit."),
        phrase("Kann ich das umtauschen?", "Can I exchange this?"),
        phrase("Die Quittung bitte.", "The receipt, please."),
        phrase("Mir gefällt das Blau.", "I like the blue one."),
      ],
      sentences: [
        sentence("Ich kaufe Brot auf dem Markt.", "I buy bread at the market."),
        sentence("Der Pullover kostet 40 Euro.", "The sweater costs 40 euros."),
        sentence("Die Schuhe sind reduziert.", "The shoes are reduced."),
        sentence("Wir stehen in der Schlange.", "We are standing in the queue."),
        sentence("Die Verkäuferin ist freundlich.", "The saleswoman is friendly."),
        sentence("Ich brauche eine größere Größe.", "I need a bigger size."),
        sentence("Das Angebot gilt nur heute.", "The offer is only valid today."),
        sentence("Ich möchte das umtauschen.", "I would like to exchange this."),
        sentence("Bar oder Karte?", "Cash or card?"),
        sentence("Die Tüte ist kostenlos.", "The bag is free."),
        sentence("Das Hemd gefällt mir.", "I like the shirt."),
        sentence("Es passt nicht gut.", "It does not fit well."),
        sentence("Ich zahle an der Kasse.", "I pay at the checkout."),
        sentence("Haben Sie etwas Billigeres?", "Do you have something cheaper?"),
        sentence("Ich gebe die Jacke zurück.", "I am returning the jacket."),
        sentence("Zwei Kilo Äpfel bitte.", "Two kilos of apples, please."),
        sentence("Der Markt schließt um vier.", "The market closes at four."),
        sentence("Ich brauche noch Milch.", "I still need milk."),
      ],
      readings: [
        reading(
          "Till receipt",
          "Kassenbon",
          "Markt am Fluss. Brot 2,40 €. Käse 3,10 €. Äpfel 2,00 €. Tüte 0,20 €. Summe 7,70 €. Bar 10,00 €. Rückgeld 2,30 €. Danke und auf Wiedersehen!",
          "Market by the river. Bread €2.40. Cheese €3.10. Apples €2.00. Bag €0.20. Total €7.70. Cash €10.00. Change €2.30. Thank you and goodbye!",
          [
            q("What is the total?", "€7.70", ["€2.40", "€10.00", "€7.70", "€2.30"]),
            q("How did the customer pay?", "Cash", ["Card", "Cash", "Voucher", "Phone"]),
            q("How much was the bag?", "€0.20", ["Free", "€2.00", "€0.20", "€3.10"]),
          ],
        ),
        reading(
          "Shop window",
          "Schaufenster",
          "Sale! Jacken -30%. Schuhe ab 25 Euro. Größe 38–44. Umtausch in 14 Tagen mit Quittung. Heute geöffnet bis 20 Uhr. Karte ja, aber nicht unter 5 Euro.",
          "Sale! Jackets -30%. Shoes from 25 euros. Sizes 38–44. Exchange within 14 days with receipt. Open today until 8 p.m. Card yes, but not under 5 euros.",
          [
            q("How long can you exchange?", "14 days", ["One day", "14 days", "A year", "Never"]),
            q("Until when is the shop open?", "20:00", ["14:00", "20:00", "Midnight", "09:00"]),
            q("Can you pay €3 by card?", "No", ["Yes", "No", "Only cashback", "Unknown"]),
          ],
        ),
        reading(
          "Customer chat",
          "Kundengespräch",
          "Kundin: Haben Sie das in Blau? Verkäufer: Ja, in M und L. Kundin: L bitte. Es ist nicht zu teuer. Verkäufer: An der Kasse können Sie mit Karte zahlen. Eine Tüte?",
          "Customer: Do you have that in blue? Seller: Yes, in M and L. Customer: L please. It is not too expensive. Seller: At the checkout you can pay by card. A bag?",
          [
            q("Which size does she take?", "L", ["S", "M", "L", "XL"]),
            q("Which color does she want?", "Blue", ["Red", "Blue", "Black", "Green"]),
            q("How can she pay?", "By card", ["Only cash", "By card", "Not at all", "Stamps"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 6-item shopping list with one price.",
          "Schreib einen Einkaufszettel.",
          "Milch, Brot, Äpfel. Der Käse kostet 3 Euro. Keine Tüte.",
          ["Mix items and one full sentence"],
        ),
        writing(
          "Write a polite shop question and answer.",
          "Schreib Frage und Antwort im Geschäft.",
          "Was kostet die Jacke? Sie kostet 40 Euro. Das ist nicht zu teuer.",
          ["Use Was kostet", "Comment with teuer/billig"],
        ),
      ],
    },
  ),
  chapter(
    "city-directions",
    "The City & Directions",
    "Die Stadt und der Weg",
    "Read maps and street signs, then give a route that a stranger could follow.",
    "mixed",
    [
      "Wo ist …? vs Wie komme ich zum/zur …?",
      "the way: geradeaus, links, rechts, die erste Straße, an der Ampel.",
      "zum + masculine/neuter (zu dem), zur + feminine (zu der).",
    ],
    {
      vocab: [
        vocab("die Stadt", "the city", undefined, "Städte"),
        vocab("der Weg", "the way / path", undefined, "Wege"),
        vocab("die Straße", "the street", undefined, "Straßen"),
        vocab("die Ampel", "the traffic light", undefined, "Ampeln"),
        vocab("die Kreuzung", "the intersection", undefined, "Kreuzungen"),
        vocab("die Brücke", "the bridge", undefined, "Brücken"),
        vocab("der Platz", "the square", undefined, "Plätze"),
        vocab("das Zentrum", "the center"),
        vocab("die Ecke", "the corner", undefined, "Ecken"),
        vocab("nah", "near"),
        vocab("weit", "far"),
        vocab("links", "left"),
        vocab("rechts", "right"),
        vocab("geradeaus", "straight on"),
        vocab("gegenüber", "opposite"),
        vocab("neben", "next to"),
        vocab("zwischen", "between"),
        vocab("das Rathaus", "the town hall", undefined, "Rathäuser"),
        vocab("die Post", "the post office"),
        vocab("die Bank", "the bank", undefined, "Banken"),
        vocab("die Apotheke", "the pharmacy", undefined, "Apotheken"),
        vocab("das Krankenhaus", "the hospital", undefined, "Krankenhäuser"),
        vocab("die Bibliothek", "the library", undefined, "Bibliotheken"),
        vocab("der Parkplatz", "the parking space", undefined, "Parkplätze"),
        vocab("der Stadtplan", "the city map", undefined, "Stadtpläne"),
        vocab("fragen", "to ask"),
        vocab("erklären", "to explain"),
        vocab("abbiegen", "to turn"),
        vocab("überqueren", "to cross"),
        vocab("verlieren", "to lose"),
        vocab("finden", "to find"),
        vocab("die Fußgängerzone", "the pedestrian zone"),
      ],
      phrases: [
        phrase("Wie komme ich zum Bahnhof?", "How do I get to the station?"),
        phrase("Gehen Sie geradeaus bis zur Ampel.", "Go straight on to the lights."),
        phrase("Biegen Sie dort links ab.", "Turn left there."),
        phrase("Es ist nicht weit.", "It is not far."),
        phrase("Die Post ist gegenüber der Bank.", "The post office is opposite the bank."),
        phrase("Nehmen Sie die zweite Straße rechts.", "Take the second street on the right."),
        phrase("Ich habe mich verlaufen.", "I have got lost."),
        phrase("Können Sie das auf dem Plan zeigen?", "Can you show that on the map?"),
        phrase("Die Apotheke ist an der Ecke.", "The pharmacy is on the corner."),
        phrase("Überqueren Sie die Brücke.", "Cross the bridge."),
        phrase("Im Zentrum ist eine Fußgängerzone.", "In the center there is a pedestrian zone."),
        phrase("Danke, jetzt finde ich es.", "Thanks, now I can find it."),
      ],
      sentences: [
        sentence("Das Rathaus liegt am Marktplatz.", "The town hall is on the market square."),
        sentence("Die Bibliothek ist neben dem Park.", "The library is next to the park."),
        sentence("Zwischen Bank und Post ist ein Café.", "Between the bank and the post office is a café."),
        sentence("Wir gehen zu Fuß ins Zentrum.", "We walk into the center."),
        sentence("An der Kreuzung biegen Sie rechts ab.", "At the intersection you turn right."),
        sentence("Das Krankenhaus ist etwas weit.", "The hospital is a bit far."),
        sentence("Der Parkplatz ist hinter dem Museum.", "The parking is behind the museum."),
        sentence("Ich frage eine Frau nach dem Weg.", "I ask a woman for the way."),
        sentence("Die Ampel ist rot.", "The traffic light is red."),
        sentence("Gehen Sie die Straße entlang.", "Go along the street."),
        sentence("Die erste Straße links ist ruhig.", "The first street on the left is quiet."),
        sentence("Das Hotel ist nicht schwer zu finden.", "The hotel is not hard to find."),
        sentence("Wir überqueren den Platz.", "We cross the square."),
        sentence("Gegenüber seht ihr die Apotheke.", "Opposite you see the pharmacy."),
        sentence("Der Weg zum Fluss ist schön.", "The way to the river is beautiful."),
        sentence("Ich erkläre dir den Weg.", "I will explain the way to you."),
        sentence("Links vom Bahnhof ist ein Kiosk.", "To the left of the station is a kiosk."),
        sentence("Bleiben Sie auf dieser Seite.", "Stay on this side."),
      ],
      readings: [
        reading(
          "Tourist leaflet",
          "Stadtplan-Text",
          "Vom Bahnhof geradeaus bis zur Ampel, dann links. Das Rathaus steht am Platz. Die Fußgängerzone beginnt an der Brücke. Die Tourist-Info ist im Zentrum, nicht weit. Ein Plan liegt am Schalter.",
          "From the station straight on to the lights, then left. The town hall stands on the square. The pedestrian zone starts at the bridge. Tourist info is in the center, not far. A map is at the counter.",
          [
            q("What do you do at the lights?", "Turn left", ["Stop forever", "Turn left", "Take a bus", "Go home"]),
            q("Where does the pedestrian zone start?", "At the bridge", ["At the airport", "At the bridge", "In another city", "At night"]),
            q("Where can you get a map?", "At the counter", ["On the train", "At the counter", "In the river", "Nowhere"]),
          ],
        ),
        reading(
          "Text from a friend",
          "Nachricht von einem Freund",
          "Komm zur Bibliothek. Sie ist gegenüber vom Park, neben der Post. Nicht die Straße am Krankenhaus — zu weit. Nimm den Bus 5 bis Markt und dann fünf Minuten zu Fuß.",
          "Come to the library. It is opposite the park, next to the post office. Not the street by the hospital — too far. Take bus 5 to Markt and then five minutes on foot.",
          [
            q("What is opposite the library?", "The park", ["The hospital", "The park", "The airport", "A river"]),
            q("Which bus?", "5", ["1", "5", "12", "None"]),
            q("Why not the hospital street?", "It is too far", ["It is closed", "It is too far", "It is a secret", "No library"]),
          ],
        ),
        reading(
          "Lost at a crossing",
          "An der Kreuzung",
          "Achtung: Baustelle. Bitte rechts abbiegen und die Brücke überqueren. Die Apotheke bleibt offen. Das Zentrum liegt dann vor Ihnen. Fragen Sie an der Ecke, wenn der Weg unklar ist.",
          "Caution: roadworks. Please turn right and cross the bridge. The pharmacy stays open. The center is then in front of you. Ask at the corner if the way is unclear.",
          [
            q("Why the detour?", "Roadworks", ["A festival", "Roadworks", "Snow", "A parade"]),
            q("Is the pharmacy open?", "Yes", ["No", "Yes", "Only Mondays", "Unknown"]),
            q("What should you do if you are unsure?", "Ask at the corner", ["Call the police", "Ask at the corner", "Go home", "Wait all night"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Give directions from the station to a café in four steps.",
          "Beschreib den Weg in vier Schritten.",
          "Gehen Sie geradeaus. An der Ampel links. Dann die Brücke überqueren. Das Café ist auf der rechten Seite.",
          ["Use imperative or Sie-form", "Include one landmark"],
        ),
        writing(
          "Write where three city places are.",
          "Schreib, wo drei Orte sind.",
          "Die Post ist gegenüber der Bank. Die Apotheke ist an der Ecke. Das Rathaus liegt am Platz.",
          ["gegenüber / neben / an"],
        ),
      ],
    },
  ),
  chapter(
    "weather",
    "Weather, Seasons & Plans",
    "Wetter, Jahreszeiten und Pläne",
    "Read forecasts, then write weekend plans that match the weather.",
    "mixed",
    [
      "Weather often uses es: Es regnet. Es ist kalt. Es scheint die Sonne.",
      "werden for future plans: Morgen wird es warm.",
      "Bei + weather: Bei Regen bleiben wir zu Hause.",
    ],
    {
      vocab: [
        vocab("das Wetter", "the weather"),
        vocab("die Sonne", "the sun"),
        vocab("der Regen", "the rain"),
        vocab("der Schnee", "the snow"),
        vocab("der Wind", "the wind"),
        vocab("die Wolke", "the cloud", undefined, "Wolken"),
        vocab("der Himmel", "the sky", undefined, "Himmel"),
        vocab("warm", "warm"),
        vocab("heiß", "hot"),
        vocab("kühl", "cool"),
        vocab("kalt", "cold"),
        vocab("nass", "wet"),
        vocab("trocken", "dry"),
        vocab("schön", "nice"),
        vocab("schlecht", "bad"),
        vocab("der Frühling", "spring"),
        vocab("der Sommer", "summer"),
        vocab("der Herbst", "autumn"),
        vocab("der Winter", "winter"),
        vocab("die Temperatur", "the temperature", undefined, "Temperaturen"),
        vocab("Grad", "degrees"),
        vocab("der Schirm", "the umbrella", undefined, "Schirme"),
        vocab("die Jacke", "the jacket", undefined, "Jacken"),
        vocab("scheinen", "to shine"),
        vocab("regnen", "to rain"),
        vocab("schneien", "to snow"),
        vocab("werden", "to become / will"),
        vocab("der Ausflug", "the trip", undefined, "Ausflüge"),
        vocab("das Wochenende", "the weekend", undefined, "Wochenenden"),
        vocab("draußen", "outside"),
        vocab("drin", "inside"),
        vocab("die Vorhersage", "the forecast", undefined, "Vorhersagen"),
      ],
      phrases: [
        phrase("Wie ist das Wetter?", "What's the weather like?"),
        phrase("Es ist sonnig und warm.", "It is sunny and warm."),
        phrase("Es wird Regen geben.", "There will be rain."),
        phrase("Nimm den Schirm mit.", "Take the umbrella with you."),
        phrase("Im Winter schneit es oft.", "In winter it often snows."),
        phrase("Bei diesem Wetter bleiben wir drin.", "In this weather we stay inside."),
        phrase("Morgen machen wir einen Ausflug.", "Tomorrow we will go on a trip."),
        phrase("Es sind 12 Grad.", "It is 12 degrees."),
        phrase("Der Himmel ist grau.", "The sky is grey."),
        phrase("Im Sommer schwimme ich gern.", "In summer I like to swim."),
        phrase("Die Vorhersage sagt Wind.", "The forecast says wind."),
        phrase("Hoffentlich scheint die Sonne.", "Hopefully the sun will shine."),
      ],
      sentences: [
        sentence("Heute regnet es den ganzen Tag.", "Today it is raining all day."),
        sentence("Gestern war es zu heiß.", "Yesterday it was too hot."),
        sentence("Im Herbst sind die Tage kürzer.", "In autumn the days are shorter."),
        sentence("Wir brauchen eine warme Jacke.", "We need a warm jacket."),
        sentence("Es schneit in den Bergen.", "It is snowing in the mountains."),
        sentence("Das Wochenende wird schön.", "The weekend will be nice."),
        sentence("Draußen ist es kühl.", "Outside it is cool."),
        sentence("Die Wolken kommen schnell.", "The clouds come quickly."),
        sentence("Bei Schnee fährt der Bus langsam.", "In snow the bus drives slowly."),
        sentence("Ich mag trockenes Wetter.", "I like dry weather."),
        sentence("Im Frühling ist der Park grün.", "In spring the park is green."),
        sentence("Es weht ein starker Wind.", "A strong wind is blowing."),
        sentence("Nimm Wasser mit, es wird heiß.", "Take water with you, it will be hot."),
        sentence("Wir bleiben bei Regen zu Hause.", "We stay at home if it rains."),
        sentence("Die Temperatur fällt auf null Grad.", "The temperature falls to zero degrees."),
        sentence("Ein Ausflug ans Meer ist geplant.", "A trip to the sea is planned."),
        sentence("Das Wetter ist nicht so schlecht.", "The weather is not that bad."),
        sentence("Abends wird es nass.", "In the evening it will get wet."),
      ],
      readings: [
        reading(
          "App forecast",
          "Wetter-App",
          "Freitag: Sonne, 24 Grad. Samstag: Wolken und Wind, 18 Grad. Sonntag: Regen am Morgen, später trocken. Tipp: Am Samstag den Schirm einpacken. Gutes Wochenende!",
          "Friday: sun, 24 degrees. Saturday: clouds and wind, 18 degrees. Sunday: rain in the morning, later dry. Tip: Pack the umbrella on Saturday. Have a good weekend!",
          [
            q("Which day is warmest?", "Friday", ["Saturday", "Friday", "Sunday", "Monday"]),
            q("When should you pack an umbrella?", "Saturday", ["Friday", "Saturday", "Never", "In winter only"]),
            q("How is Sunday afternoon?", "Dry", ["Snowy", "Dry", "24 degrees", "Windy only"]),
          ],
        ),
        reading(
          "Hiking club note",
          "Wandergruppe",
          "Ausflug nur bei gutem Wetter. Treffpunkt 9 Uhr am Bahnhof. Wenn es stark regnet, bleibt der Ausflug aus. Im Winter brauchen alle warme Jacken. Bitte die Vorhersage am Abend lesen.",
          "Trip only in good weather. Meeting point 9 a.m. at the station. If it rains heavily, the trip is cancelled. In winter everyone needs warm jackets. Please read the forecast in the evening.",
          [
            q("When is the meeting?", "9 a.m. at the station", ["At the park at noon", "9 a.m. at the station", "Sunday night", "Online"]),
            q("What cancels the trip?", "Heavy rain", ["Wind", "Heavy rain", "Sunshine", "A jacket"]),
            q("What should people do in the evening?", "Read the forecast", ["Buy tickets", "Read the forecast", "Swim", "Stay silent"]),
          ],
        ),
        reading(
          "A diary line",
          "Tagebuch",
          "Heute war der Himmel endlich blau. Draußen haben Kinder gespielt. Ich war ohne Schirm unterwegs. Abends wurde es kühl, aber nicht nass. So mag ich den Frühling.",
          "Today the sky was finally blue. Outside, children played. I was out without an umbrella. In the evening it got cool, but not wet. That is how I like spring.",
          [
            q("Did the writer take an umbrella?", "No", ["Yes", "No", "Two", "Only at night"]),
            q("How was the evening?", "Cool but dry", ["Stormy", "Hot", "Cool but dry", "Snowy"]),
            q("Which season is mentioned?", "Spring", ["Winter", "Autumn", "Spring", "None"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a weekend plan that depends on the weather.",
          "Schreib einen Wetterplan.",
          "Am Samstag scheint die Sonne. Dann machen wir einen Ausflug. Bei Regen bleiben wir zu Hause und lernen Deutsch.",
          ["Name a day", "Give a plan and a backup"],
        ),
        writing(
          "Describe today and tomorrow in four sentences.",
          "Beschreib heute und morgen.",
          "Heute ist es kalt. Es weht Wind. Morgen wird es wärmer. Ich nehme trotzdem eine Jacke mit.",
          ["Use Es ist / Es wird"],
        ),
      ],
    },
  ),
  chapter(
    "clothes",
    "Clothes & Appearance",
    "Kleidung und Aussehen",
    "Read size labels and dress codes, then describe what someone is wearing.",
    "vocab",
    [
      "tragen = to wear. anhaben is common in speech: Ich habe eine Jacke an.",
      "Size: Größe 38, zu weit, zu eng, die richtige Größe.",
      "Colors plus clothes: eine rote Jacke (adjective ending after eine: -e).",
    ],
    {
      vocab: [
        vocab("die Kleidung", "the clothes"),
        vocab("das T-Shirt", "the T-shirt", undefined, "T-Shirts"),
        vocab("das Hemd", "the shirt", undefined, "Hemden"),
        vocab("die Bluse", "the blouse", undefined, "Blusen"),
        vocab("der Pullover", "the sweater", undefined, "Pullover"),
        vocab("die Jacke", "the jacket", undefined, "Jacken"),
        vocab("der Mantel", "the coat", undefined, "Mäntel"),
        vocab("die Hose", "the trousers", undefined, "Hosen"),
        vocab("der Rock", "the skirt", undefined, "Röcke"),
        vocab("das Kleid", "the dress", undefined, "Kleider"),
        vocab("die Schuhe", "the shoes"),
        vocab("die Socken", "the socks"),
        vocab("die Mütze", "the cap", undefined, "Mützen"),
        vocab("der Hut", "the hat", undefined, "Hüte"),
        vocab("die Brille", "the glasses"),
        vocab("die Tasche", "the bag", undefined, "Taschen"),
        vocab("tragen", "to wear"),
        vocab("weit", "loose / wide"),
        vocab("eng", "tight"),
        vocab("bequem", "comfortable"),
        vocab("elegant", "elegant"),
        vocab("sportlich", "sporty"),
        vocab("die Mode", "fashion"),
        vocab("das Aussehen", "the appearance"),
        vocab("die Haare", "the hair"),
        vocab("lang", "long"),
        vocab("kurz", "short"),
        vocab("die Sonnenbrille", "the sunglasses"),
        vocab("anziehen", "to put on"),
        vocab("ausziehen", "to take off"),
        vocab("die Größe", "the size"),
        vocab("passen", "to fit"),
      ],
      phrases: [
        phrase("Was ziehst du an?", "What are you putting on?"),
        phrase("Ich trage eine schwarze Jacke.", "I am wearing a black jacket."),
        phrase("Die Hose ist zu eng.", "The trousers are too tight."),
        phrase("Die Schuhe sind bequem.", "The shoes are comfortable."),
        phrase("Das steht dir gut.", "That suits you."),
        phrase("Hast du eine größere Größe?", "Do you have a larger size?"),
        phrase("Im Büro ist die Kleidung eher elegant.", "At the office the clothes are rather elegant."),
        phrase("Zieh die nassen Schuhe aus.", "Take off the wet shoes."),
        phrase("Er hat kurze Haare und eine Brille.", "He has short hair and glasses."),
        phrase("Sie sieht sportlich aus.", "She looks sporty."),
        phrase("Der Mantel ist zu weit.", "The coat is too loose."),
        phrase("Eine Mütze bei Kälte ist wichtig.", "A cap in the cold is important."),
      ],
      sentences: [
        sentence("Ich ziehe ein warmes Hemd an.", "I put on a warm shirt."),
        sentence("Die Bluse ist weiß und neu.", "The blouse is white and new."),
        sentence("Mein Pullover ist zu groß.", "My sweater is too big."),
        sentence("Wir tragen heute feste Schuhe.", "We are wearing sturdy shoes today."),
        sentence("Der Rock gefällt mir.", "I like the skirt."),
        sentence("Das Kleid ist elegant, aber nicht bequem.", "The dress is elegant but not comfortable."),
        sentence("Die Socken sind bunt.", "The socks are colorful."),
        sentence("Ohne Brille sehe ich schlecht.", "Without glasses I see badly."),
        sentence("Die Tasche passt nicht zur Hose.", "The bag does not go with the trousers."),
        sentence("Im Sommer trage ich T-Shirts.", "In summer I wear T-shirts."),
        sentence("Bitte den Hut abnehmen.", "Please take the hat off."),
        sentence("Sie hat lange Haare.", "She has long hair."),
        sentence("Die Mode ändert sich schnell.", "Fashion changes quickly."),
        sentence("Ein sportlicher Look ist okay.", "A sporty look is okay."),
        sentence("Die Jacke steht dir.", "The jacket suits you."),
        sentence("Ich kaufe Größe 42.", "I am buying size 42."),
        sentence("Zieh dich warm an.", "Dress warmly."),
        sentence("Die Schuhe sind nicht zu teuer.", "The shoes are not too expensive."),
      ],
      readings: [
        reading(
          "Dress code email",
          "E-Mail zur Kleidung",
          "Für die Prüfung bitte ruhige Kleidung: Hemd oder Bluse, keine Sportschuhe. Ein Pullover ist okay, ein Hut nicht. Größe spielt keine Rolle, Sauberkeit schon. Danke, Kursbüro.",
          "For the exam please wear calm clothes: shirt or blouse, no trainers. A sweater is okay, a hat is not. Size does not matter, cleanliness does. Thanks, course office.",
          [
            q("Are trainers allowed?", "No", ["Yes", "No", "Only red ones", "In summer"]),
            q("Is a sweater okay?", "Yes", ["No", "Yes", "Only black", "Hats yes"]),
            q("What matters besides clothes?", "Cleanliness", ["Hair color", "Cleanliness", "A bag brand", "A watch"]),
          ],
        ),
        reading(
          "Changing-room chat",
          "Umkleide",
          "Die Hose ist eng in der Taille. Probier die weite. Die Schuhe sind bequem, Größe 40. Der Mantel ist elegant, aber zu lang. Ich nehme die Jacke in Blau.",
          "The trousers are tight at the waist. Try the loose ones. The shoes are comfortable, size 40. The coat is elegant but too long. I'll take the jacket in blue.",
          [
            q("What is wrong with the trousers?", "They are tight", ["They are wet", "They are tight", "No size", "Too blue"]),
            q("What size are the shoes?", "40", ["38", "40", "42", "M"]),
            q("What will the person buy?", "The blue jacket", ["The coat", "The blue jacket", "Nothing", "A hat"]),
          ],
        ),
        reading(
          "Description for a meetup",
          "Beschreibung",
          "Ich stehe vor dem Café. Lange braune Haare, schwarze Jacke, rote Tasche. Keine Brille heute. Sportliche Schuhe, weil wir danach laufen. Bis gleich!",
          "I am standing in front of the café. Long brown hair, black jacket, red bag. No glasses today. Sporty shoes because we will run afterwards. See you in a bit!",
          [
            q("What color is the bag?", "Red", ["Black", "Brown", "Red", "Blue"]),
            q("Is the person wearing glasses?", "No", ["Yes", "No", "A hat", "Unknown"]),
            q("Why sporty shoes?", "They will run later", ["Fashion", "They will run later", "Rain", "Work"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe what you are wearing today.",
          "Beschreib deine Kleidung.",
          "Ich trage eine blaue Jacke und eine schwarze Hose. Die Schuhe sind bequem. Keine Mütze.",
          ["tragen / anhaben", "Color + clothing noun"],
        ),
        writing(
          "Describe a person so a friend can find them.",
          "Beschreib eine Person.",
          "Er hat kurze Haare und eine Brille. Er trägt einen grauen Pullover. Die Tasche ist groß.",
          ["Hair, one clothing item, one extra detail"],
        ),
      ],
    },
  ),
  chapter(
    "hobbies",
    "Hobbies & Free Time",
    "Hobbys und Freizeit",
    "Read club notices, then talk and write about what you like doing.",
    "vocab",
    [
      "gern / lieber / am liebsten with verbs: Ich tanze gern.",
      "Hobby as noun: Mein Hobby ist Schwimmen. Or: Ich schwimme gern.",
      "Zeitform present for habits: Am Wochenende spiele ich Fußball.",
    ],
    {
      vocab: [
        vocab("das Hobby", "the hobby", undefined, "Hobbys"),
        vocab("die Freizeit", "free time"),
        vocab("spielen", "to play"),
        vocab("lesen", "to read"),
        vocab("kochen", "to cook"),
        vocab("wandern", "to hike"),
        vocab("schwimmen", "to swim"),
        vocab("tanzen", "to dance"),
        vocab("singen", "to sing"),
        vocab("malen", "to paint"),
        vocab("fotografieren", "to take photos"),
        vocab("der Sport", "sport"),
        vocab("der Fußball", "football / soccer"),
        vocab("das Kino", "the cinema", undefined, "Kinos"),
        vocab("das Konzert", "the concert", undefined, "Konzerte"),
        vocab("die Musik", "music"),
        vocab("das Spiel", "the game", undefined, "Spiele"),
        vocab("das Buch", "the book", undefined, "Bücher"),
        vocab("der Verein", "the club", undefined, "Vereine"),
        vocab("das Team", "the team", undefined, "Teams"),
        vocab("langweilig", "boring"),
        vocab("spannend", "exciting"),
        vocab("entspannen", "to relax"),
        vocab("treffen", "to meet"),
        vocab("gern", "gladly / like to"),
        vocab("lieber", "rather / prefer to"),
        vocab("am liebsten", "most of all"),
        vocab("oft", "often"),
        vocab("selten", "rarely"),
        vocab("die Freunde", "the friends"),
        vocab("die Natur", "nature"),
        vocab("die Pause", "the break"),
      ],
      phrases: [
        phrase("Was machst du in der Freizeit?", "What do you do in your free time?"),
        phrase("Ich lese gern Krimis.", "I like reading crime novels."),
        phrase("Am liebsten koche ich mit Freunden.", "Most of all I cook with friends."),
        phrase("Ich spiele lieber Tennis als Fußball.", "I prefer playing tennis to football."),
        phrase("Kommst du mit ins Kino?", "Are you coming to the cinema?"),
        phrase("Das Konzert war spannend.", "The concert was exciting."),
        phrase("Mein Verein trifft sich am Dienstag.", "My club meets on Tuesday."),
        phrase("Sport ist nie langweilig.", "Sport is never boring."),
        phrase("Wir wandern in der Natur.", "We hike in nature."),
        phrase("Ich fotografiere oft am Wochenende.", "I often take photos at the weekend."),
        phrase("Nach der Arbeit entspanne ich.", "After work I relax."),
        phrase("Singen ist mein Hobby.", "Singing is my hobby."),
      ],
      sentences: [
        sentence("Ich schwimme zweimal die Woche.", "I swim twice a week."),
        sentence("Sie tanzt in einem Verein.", "She dances in a club."),
        sentence("Wir malen am Sonntag.", "We paint on Sunday."),
        sentence("Das Spiel beginnt um acht.", "The game starts at eight."),
        sentence("Er liest selten Zeitung.", "He rarely reads the newspaper."),
        sentence("Musik macht mich froh.", "Music makes me happy."),
        sentence("Die Freunde treffen sich im Park.", "The friends meet in the park."),
        sentence("Fußball ist in meiner Stadt wichtig.", "Football is important in my city."),
        sentence("Ich koche lieber als backen.", "I prefer cooking to baking."),
        sentence("Das Team braucht noch Spieler.", "The team still needs players."),
        sentence("Ein langes Buch ist nicht langweilig.", "A long book is not boring."),
        sentence("Wir gehen oft ins Kino.", "We often go to the cinema."),
        sentence("In der Pause höre ich Musik.", "In the break I listen to music."),
        sentence("Wandern ist gut für den Kopf.", "Hiking is good for the head."),
        sentence("Sie fotografiert Menschen gern.", "She likes photographing people."),
        sentence("Ich habe wenig Freizeit.", "I have little free time."),
        sentence("Trotzdem spiele ich Gitarre.", "Still I play guitar."),
        sentence("Das Hobby kostet nicht viel.", "The hobby does not cost much."),
      ],
      readings: [
        reading(
          "Club noticeboard",
          "Vereinsbrett",
          "Chor: Mittwoch 19 Uhr. Wandergruppe: Samstag 8 Uhr, Bahnhof. Fußball: Sonntag, Sportplatz. Neu: Fotokurs für Anfänger. Bitte Name an die Liste. Freizeit soll Spaß machen!",
          "Choir: Wednesday 7 p.m. Hiking group: Saturday 8 a.m., station. Football: Sunday, sports field. New: photography course for beginners. Please add your name to the list. Free time should be fun!",
          [
            q("When is choir?", "Wednesday 19:00", ["Saturday 8:00", "Wednesday 19:00", "Sunday", "Never"]),
            q("Where does the hiking group meet?", "At the station", ["Sports field", "At the station", "Cinema", "Home"]),
            q("Who is the photo course for?", "Beginners", ["Pros only", "Beginners", "Children only", "Teachers"]),
          ],
        ),
        reading(
          "Forum post",
          "Forumsbeitrag",
          "Ich suche Leute zum Schwimmen. Ich bin nicht schnell, aber gern draußen. Am liebsten am Samstagmorgen. Kino mag ich auch, aber Sport ist besser nach der Arbeit. Wer hat Lust?",
          "I am looking for people to swim with. I am not fast, but I like being outside. Most of all Saturday morning. I also like cinema, but sport is better after work. Who is up for it?",
          [
            q("When does this person prefer to swim?", "Saturday morning", ["Sunday night", "Saturday morning", "Only in winter", "Never"]),
            q("Are they a fast swimmer?", "No", ["Yes", "No", "Professional", "Unknown"]),
            q("What is better after work, for them?", "Sport", ["TV only", "Sport", "Sleep", "Shopping"]),
          ],
        ),
        reading(
          "A short profile",
          "Kurzprofil",
          "Name: Sam. Hobbys: kochen, lesen, Gitarre. Selten fernsehen. Oft Freunde treffen. Am Wochenende Natur statt Shopping. Ein spannendes Buch liegt immer in der Tasche.",
          "Name: Sam. Hobbies: cooking, reading, guitar. Rarely watch TV. Often meet friends. At the weekend nature instead of shopping. An exciting book is always in the bag.",
          [
            q("What does Sam rarely do?", "Watch TV", ["Cook", "Watch TV", "Read", "Meet friends"]),
            q("Weekend preference?", "Nature over shopping", ["Malls", "Nature over shopping", "Office", "Sleep all day"]),
            q("What is always in the bag?", "A book", ["A ball", "A book", "A camera", "Nothing"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write about three hobbies with gern / lieber / am liebsten.",
          "Schreib über drei Hobbys.",
          "Ich lese gern. Ich schwimme lieber als joggen. Am liebsten koche ich mit Freunden.",
          ["One gern, one lieber, one am liebsten"],
        ),
        writing(
          "Invite someone to a free-time plan.",
          "Lade jemanden ein.",
          "Hast du am Samstag Zeit? Wir gehen ins Kino und danach essen. Das wird nicht langweilig.",
          ["Question + plan + a comment"],
        ),
      ],
    },
  ),
  chapter(
    "travel",
    "Travel & Transport",
    "Reisen und Verkehr",
    "Read tickets and platform boards, then book and describe a simple journey.",
    "mixed",
    [
      "fahren (car, train, bus) vs gehen (on foot) vs fliegen (plane).",
      "eine Fahrkarte nach + city. umsteigen = to change trains.",
      "Perfekt preview: Ich bin nach Berlin gefahren (sein + movement).",
    ],
    {
      vocab: [
        vocab("die Reise", "the trip", undefined, "Reisen"),
        vocab("der Urlaub", "the holiday", undefined, "Urlaube"),
        vocab("der Zug", "the train", undefined, "Züge"),
        vocab("der Bus", "the bus", undefined, "Busse"),
        vocab("das Flugzeug", "the plane", undefined, "Flugzeuge"),
        vocab("das Auto", "the car", undefined, "Autos"),
        vocab("das Fahrrad", "the bicycle", undefined, "Fahrräder"),
        vocab("der Flughafen", "the airport", undefined, "Flughäfen"),
        vocab("der Bahnhof", "the station", undefined, "Bahnhöfe"),
        vocab("das Gleis", "the platform / track", undefined, "Gleise"),
        vocab("die Fahrkarte", "the ticket", undefined, "Fahrkarten"),
        vocab("die Verspätung", "the delay", undefined, "Verspätungen"),
        vocab("umsteigen", "to change (trains)"),
        vocab("ankommen", "to arrive"),
        vocab("abfahren", "to depart"),
        vocab("buchen", "to book"),
        vocab("der Koffer", "the suitcase", undefined, "Koffer"),
        vocab("der Rucksack", "the backpack", undefined, "Rucksäcke"),
        vocab("das Hotel", "the hotel", undefined, "Hotels"),
        vocab("die Jugendherberge", "the youth hostel", undefined, "Jugendherbergen"),
        vocab("die Landschaft", "the landscape", undefined, "Landschaften"),
        vocab("das Meer", "the sea"),
        vocab("die Berge", "the mountains"),
        vocab("einfach", "one-way / simple"),
        vocab("hin und zurück", "return (ticket)"),
        vocab("direkt", "direct"),
        vocab("bequem", "comfortable"),
        vocab("stressig", "stressful"),
        vocab("pünktlich", "on time"),
        vocab("verpassen", "to miss"),
        vocab("reisen", "to travel"),
        vocab("der Ausweis", "the ID card", undefined, "Ausweise"),
      ],
      phrases: [
        phrase("Ich möchte eine Fahrkarte nach Wien.", "I would like a ticket to Vienna."),
        phrase("Muss ich umsteigen?", "Do I have to change?"),
        phrase("Der Zug hat zehn Minuten Verspätung.", "The train is ten minutes delayed."),
        phrase("Von welchem Gleis fährt der Zug?", "Which platform does the train leave from?"),
        phrase("Wir kommen um 16 Uhr an.", "We arrive at 4 p.m."),
        phrase("Ist das ein direkter Zug?", "Is that a direct train?"),
        phrase("Ich habe den Bus verpasst.", "I missed the bus."),
        phrase("Zwei Nächte im Hotel bitte.", "Two nights in the hotel, please."),
        phrase("Hin und zurück ist günstiger.", "A return is cheaper."),
        phrase("Bitte den Ausweis zeigen.", "Please show ID."),
        phrase("Der Flug ist pünktlich.", "The flight is on time."),
        phrase("Urlaub am Meer oder in den Bergen?", "Holiday by the sea or in the mountains?"),
      ],
      sentences: [
        sentence("Wir reisen mit dem Zug, nicht mit dem Auto.", "We travel by train, not by car."),
        sentence("Der Flughafen ist weit von der Stadt.", "The airport is far from the city."),
        sentence("Ich buche ein Zimmer in der Jugendherberge.", "I am booking a room in the youth hostel."),
        sentence("Der Koffer ist zu schwer.", "The suitcase is too heavy."),
        sentence("Umsteigen in Frankfurt ist stressig.", "Changing in Frankfurt is stressful."),
        sentence("Das Fahrrad nehme ich in den Urlaub mit.", "I am taking the bike on holiday."),
        sentence("Die Landschaft ist wunderschön.", "The landscape is gorgeous."),
        sentence("Eine einfache Fahrkarte reicht.", "A one-way ticket is enough."),
        sentence("Der Bus fährt ab Hauptbahnhof.", "The bus leaves from the main station."),
        sentence("Wir sind pünktlich angekommen.", "We arrived on time."),
        sentence("Ich fliege nicht gern.", "I don't like flying."),
        sentence("Das Gleis steht noch nicht fest.", "The platform is not fixed yet."),
        sentence("Im Rucksack ist nur das Wichtige.", "Only the important things are in the backpack."),
        sentence("Die Reise dauert vier Stunden.", "The journey takes four hours."),
        sentence("Bei Verspätung gibt es eine Durchsage.", "If there is a delay there is an announcement."),
        sentence("Das Hotel liegt nah am Meer.", "The hotel is close to the sea."),
        sentence("Wir wandern in den Bergen.", "We hike in the mountains."),
        sentence("Ohne Ausweis kommst du nicht ins Flugzeug.", "Without ID you will not get on the plane."),
      ],
      readings: [
        reading(
          "Booking confirmation",
          "Buchungsbestätigung",
          "Zug ICE 512. Berlin Hbf 08:46 → München Hbf 13:14. Gleis 12. Sitzplatz 21, Wagen 7. Kein Umsteigen. Verspätung aktuell: 0 Minuten. Ausweis bitte mitnehmen.",
          "Train ICE 512. Berlin Hbf 08:46 → Munich Hbf 13:14. Platform 12. Seat 21, coach 7. No change. Current delay: 0 minutes. Please bring ID.",
          [
            q("Is there a change of trains?", "No", ["Yes, in Frankfurt", "No", "Two changes", "Unknown"]),
            q("When does it leave Berlin?", "08:46", ["13:14", "08:46", "12:00", "21:07"]),
            q("Which platform?", "12", ["7", "21", "12", "512"]),
          ],
        ),
        reading(
          "Hostel info",
          "Herbergsinfo",
          "Check-in ab 15 Uhr. Frühstück 7–9 Uhr. Der Bahnhof ist 10 Minuten zu Fuß. Bus 3 zum Meer. Berge mit dem Fahrrad in 40 Minuten. Bei Verspätung bitte anrufen.",
          "Check-in from 3 p.m. Breakfast 7–9 a.m. The station is 10 minutes on foot. Bus 3 to the sea. Mountains by bike in 40 minutes. If delayed, please call.",
          [
            q("Earliest check-in?", "15:00", ["07:00", "15:00", "09:00", "Midnight"]),
            q("How do you reach the sea?", "Bus 3", ["Train ICE", "Bus 3", "Plane", "Not possible"]),
            q("What if you are late?", "Call", ["Do nothing", "Call", "Go to the mountains", "Wait at Gleis 12"]),
          ],
        ),
        reading(
          "Travel diary",
          "Reisetagebuch",
          "Der Flug war pünktlich, aber der Koffer kam spät. Dann der Bus in die Stadt — bequem, nicht stressig. Das Hotel ist klein und nah am Markt. Morgen fahren wir an die Küste. Ich habe den Zug nicht verpasst. Gut!",
          "The flight was on time, but the suitcase came late. Then the bus into the city — comfortable, not stressful. The hotel is small and close to the market. Tomorrow we go to the coast. I did not miss the train. Good!",
          [
            q("What was late?", "The suitcase", ["The flight", "The suitcase", "The hotel", "The coast"]),
            q("How was the bus?", "Comfortable", ["Stressful", "Comfortable", "Cancelled", "Full of snow"]),
            q("Where are they going tomorrow?", "To the coast", ["Home", "To the coast", "To the airport only", "To work"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe a journey in six short sentences.",
          "Beschreib eine Reise.",
          "Ich fahre mit dem Zug nach Hamburg. Der Zug ist pünktlich. Ich muss nicht umsteigen. Das Hotel ist nah. Die Reise ist nicht stressig. Morgen ans Meer.",
          ["Mode of transport, time/punctuality, destination"],
        ),
        writing(
          "Write a booking request.",
          "Schreib eine Buchungsanfrage.",
          "Guten Tag, ich möchte eine Fahrkarte nach Köln, hin und zurück, am Freitag. Welches Gleis bitte? Viele Grüße.",
          ["Polite opening", "Destination + date"],
        ),
      ],
    },
  ),
];
