import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const a2ChaptersPart2: ChapterSource[] = [
  chapter(
    "health",
    "Health & the Body",
    "Gesundheit und Körper",
    "Read pharmacy labels and appointment notes, then describe symptoms clearly.",
    "mixed",
    [
      "Schmerz: Ich habe Kopfschmerzen. Weh tun: Der Rücken tut weh.",
      "Body parts usually take articles: der Arm, die Hand, das Bein.",
      "At the doctor, present tense + seit: Ich bin seit drei Tagen krank.",
    ],
    {
      vocab: [
        vocab("der Körper", "the body", undefined, "Körper"),
        vocab("der Kopf", "the head", undefined, "Köpfe"),
        vocab("der Rücken", "the back"),
        vocab("der Bauch", "the stomach", undefined, "Bäuche"),
        vocab("der Hals", "the throat / neck", undefined, "Hälse"),
        vocab("die Hand", "the hand", undefined, "Hände"),
        vocab("der Fuß", "the foot", undefined, "Füße"),
        vocab("das Auge", "the eye", undefined, "Augen"),
        vocab("das Ohr", "the ear", undefined, "Ohren"),
        vocab("die Nase", "the nose", undefined, "Nasen"),
        vocab("krank", "ill"),
        vocab("gesund", "healthy"),
        vocab("das Fieber", "the fever"),
        vocab("der Husten", "the cough"),
        vocab("der Schnupfen", "the cold (runny nose)"),
        vocab("müde", "tired"),
        vocab("der Schmerz", "the pain", undefined, "Schmerzen"),
        vocab("weh tun", "to hurt"),
        vocab("der Arzt", "the doctor (m)", undefined, "Ärzte"),
        vocab("die Ärztin", "the doctor (f)", undefined, "Ärztinnen"),
        vocab("die Apotheke", "the pharmacy", undefined, "Apotheken"),
        vocab("die Tablette", "the tablet", undefined, "Tabletten"),
        vocab("das Rezept", "the prescription", undefined, "Rezepte"),
        vocab("die Versicherung", "the insurance", undefined, "Versicherungen"),
        vocab("der Termin", "the appointment", undefined, "Termine"),
        vocab("untersuchen", "to examine"),
        vocab("helfen", "to help"),
        vocab("bleiben", "to stay"),
        vocab("das Bett", "the bed"),
        vocab("die Gesundheit", "health"),
        vocab("dringend", "urgent"),
        vocab("besser", "better"),
      ],
      phrases: [
        phrase("Mir ist schlecht.", "I feel sick."),
        phrase("Ich habe Kopfschmerzen.", "I have a headache."),
        phrase("Der Rücken tut weh.", "My back hurts."),
        phrase("Ich bin erkältet.", "I have a cold."),
        phrase("Seit wann haben Sie Fieber?", "How long have you had a fever?"),
        phrase("Nehmen Sie zweimal täglich eine Tablette.", "Take one tablet twice a day."),
        phrase("Haben Sie ein Rezept?", "Do you have a prescription?"),
        phrase("Es ist nicht dringend, aber unangenehm.", "It is not urgent but unpleasant."),
        phrase("Bleiben Sie im Bett.", "Stay in bed."),
        phrase("Ich brauche einen Termin beim Arzt.", "I need a doctor's appointment."),
        phrase("Geht es Ihnen besser?", "Are you feeling better?"),
        phrase("Die Apotheke ist um die Ecke.", "The pharmacy is around the corner."),
      ],
      sentences: [
        sentence("Ich bin seit Montag krank.", "I have been ill since Monday."),
        sentence("Sie hat Husten und Schnupfen.", "She has a cough and a cold."),
        sentence("Die Füße tun weh nach dem Laufen.", "The feet hurt after running."),
        sentence("Der Arzt untersucht das Ohr.", "The doctor examines the ear."),
        sentence("Ohne Versicherung ist es teuer.", "Without insurance it is expensive."),
        sentence("Trinken Sie viel Wasser.", "Drink a lot of water."),
        sentence("Mein Hals ist rot.", "My throat is red."),
        sentence("Die Tabletten helfen schnell.", "The tablets help quickly."),
        sentence("Wir bleiben heute zu Hause.", "We are staying at home today."),
        sentence("Das Auge tränt.", "The eye is watering."),
        sentence("Ich fühle mich nicht gesund.", "I do not feel healthy."),
        sentence("Der Termin ist um halb drei.", "The appointment is at half past two."),
        sentence("Bitte den Bauch nicht belasten.", "Please do not strain the stomach."),
        sentence("Die Ärztin ist sehr ruhig.", "The doctor is very calm."),
        sentence("Fieber über 39 ist ernst.", "Fever over 39 is serious."),
        sentence("Schlaf ist gut für die Gesundheit.", "Sleep is good for health."),
        sentence("Die Nase ist zu.", "The nose is blocked."),
        sentence("Morgen geht es mir besser.", "Tomorrow I will feel better."),
      ],
      readings: [
        reading(
          "Pharmacy leaflet",
          "Beipackzettel kurz",
          "Bei Kopfschmerzen: eine Tablette, nicht mehr als drei am Tag. Mit Wasser, nicht mit Alkohol. Bei Fieber über 39 bitte zum Arzt. Für Kinder anderes Mittel. Fragen Sie in der Apotheke.",
          "For headaches: one tablet, no more than three a day. With water, not with alcohol. If fever over 39, please see a doctor. For children a different medicine. Ask at the pharmacy.",
          [
            q("Maximum tablets per day?", "Three", ["One", "Three", "Ten", "None"]),
            q("When must you see a doctor?", "Fever over 39", ["A cough", "Fever over 39", "Tiredness", "A blocked nose"]),
            q("Can children take this?", "No, they need another medicine", ["Yes always", "No, they need another medicine", "Only with alcohol", "Never drink water"]),
          ],
        ),
        reading(
          "GP reception note",
          "Zettel an der Anmeldung",
          "Heute nur akute Fälle. Termin online oder telefonisch. Versichertenkarte mitbringen. Die Ärztin hat Verspätung, bitte warten. Notfälle: Krankenhaus, nicht hier.",
          "Today acute cases only. Appointment online or by phone. Bring insurance card. The doctor is delayed, please wait. Emergencies: hospital, not here.",
          [
            q("What should you bring?", "Insurance card", ["A suitcase", "Insurance card", "A cake", "Nothing"]),
            q("Where do emergencies go?", "Hospital", ["Pharmacy only", "Hospital", "Home", "Online"]),
            q("Why wait?", "The doctor is delayed", ["The shop is closed", "The doctor is delayed", "No chairs", "Night shift"]),
          ],
        ),
        reading(
          "Message to a boss",
          "Nachricht an den Chef",
          "Guten Morgen, ich bin krank: Fieber und Husten. Ich bleibe im Bett und gehe nicht zur Arbeit. Einen Arzttermin habe ich um elf. Hoffentlich geht es morgen besser. Viele Grüße, Lena.",
          "Good morning, I am ill: fever and cough. I am staying in bed and not going to work. I have a doctor's appointment at eleven. Hopefully I will be better tomorrow. Best wishes, Lena.",
          [
            q("Why is Lena off work?", "Fever and cough", ["Holiday", "Fever and cough", "A train", "A meeting"]),
            q("When is the doctor?", "At eleven", ["At night", "At eleven", "On Friday only", "Never"]),
            q("Where is she staying?", "In bed", ["At the office", "In bed", "At the airport", "In a café"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe three symptoms and one request.",
          "Beschreib Symptome.",
          "Ich habe Kopfschmerzen. Der Hals tut weh. Ich bin müde. Ich brauche einen Termin.",
          ["haben + symptom", "weh tun"],
        ),
        writing(
          "Write a short sick note to a teacher.",
          "Schreib eine Krankmeldung.",
          "Guten Tag, ich bin heute krank und komme nicht zum Kurs. Ich habe Fieber. Viele Grüße.",
          ["Polite opening", "Reason + closing"],
        ),
      ],
    },
  ),
  chapter(
    "work",
    "Work & Occupations",
    "Arbeit und Berufe",
    "Read job ads at A2 level, then describe what you do and when you work.",
    "mixed",
    [
      "von Beruf: Ich bin von Beruf Köchin. Was bist du von Beruf?",
      "arbeiten bei + company, arbeiten als + job, arbeiten in + place.",
      "Arbeitszeiten: Vollzeit, Teilzeit, Schicht, von … bis …",
    ],
    {
      vocab: [
        vocab("die Arbeit", "work / the job"),
        vocab("der Beruf", "the occupation", undefined, "Berufe"),
        vocab("der Job", "the job", undefined, "Jobs"),
        vocab("die Stelle", "the position", undefined, "Stellen"),
        vocab("der Chef", "the boss (m)", undefined, "Chefs"),
        vocab("die Chefin", "the boss (f)", undefined, "Chefinnen"),
        vocab("der Kollege", "the colleague (m)", undefined, "Kollegen"),
        vocab("die Kollegin", "the colleague (f)", undefined, "Kolleginnen"),
        vocab("das Büro", "the office", undefined, "Büros"),
        vocab("die Firma", "the company", undefined, "Firmen"),
        vocab("die Pause", "the break", undefined, "Pausen"),
        vocab("das Gehalt", "the salary", undefined, "Gehälter"),
        vocab("die Schicht", "the shift", undefined, "Schichten"),
        vocab("Vollzeit", "full time"),
        vocab("Teilzeit", "part time"),
        vocab("arbeitslos", "unemployed"),
        vocab("gesucht", "wanted (in ads)"),
        vocab("die Erfahrung", "experience"),
        vocab("die Bewerbung", "the application", undefined, "Bewerbungen"),
        vocab("der Lebenslauf", "the CV", undefined, "Lebensläufe"),
        vocab("das Vorstellungsgespräch", "the interview", undefined, "Vorstellungsgespräche"),
        vocab("pünktlich", "punctual"),
        vocab("stressig", "stressful"),
        vocab("interessant", "interesting"),
        vocab("verdienen", "to earn"),
        vocab("überstunden", "overtime"),
        vocab("kündigen", "to resign / fire"),
        vocab("anfangen", "to start"),
        vocab("die Aufgabe", "the task", undefined, "Aufgaben"),
        vocab("telefonieren", "to make phone calls"),
        vocab("der Kunde", "the customer (m)", undefined, "Kunden"),
        vocab("die Kundin", "the customer (f)", undefined, "Kundinnen"),
      ],
      phrases: [
        phrase("Was bist du von Beruf?", "What do you do for a living?"),
        phrase("Ich arbeite als Mechaniker.", "I work as a mechanic."),
        phrase("Ich arbeite bei einer kleinen Firma.", "I work at a small company."),
        phrase("Die Stelle ist in Teilzeit.", "The position is part time."),
        phrase("Bitte den Lebenslauf per E-Mail senden.", "Please send the CV by email."),
        phrase("Das Vorstellungsgespräch ist am Donnerstag.", "The interview is on Thursday."),
        phrase("Die Arbeit beginnt um acht.", "Work starts at eight."),
        phrase("Heute habe ich Überstunden.", "I have overtime today."),
        phrase("Die Kollegen sind nett.", "The colleagues are nice."),
        phrase("Ich verdiene nicht viel, aber die Arbeit gefällt mir.", "I don't earn much, but I like the work."),
        phrase("Wir suchen eine Verkäuferin.", "We are looking for a saleswoman."),
        phrase("Pünktlichkeit ist wichtig.", "Punctuality is important."),
      ],
      sentences: [
        sentence("Sie ist Krankenschwester im Krankenhaus.", "She is a nurse at the hospital."),
        sentence("Er sucht eine neue Stelle.", "He is looking for a new position."),
        sentence("Das Büro ist im Zentrum.", "The office is in the center."),
        sentence("Die Chefin erklärt die Aufgaben.", "The boss explains the tasks."),
        sentence("Am Telefon bin ich freundlich.", "I am friendly on the phone."),
        sentence("Die Schicht endet um 22 Uhr.", "The shift ends at 10 p.m."),
        sentence("Ohne Erfahrung ist der Job schwer.", "Without experience the job is hard."),
        sentence("Ich schreibe eine Bewerbung.", "I am writing an application."),
        sentence("Kundenfragen kommen den ganzen Tag.", "Customer questions come all day."),
        sentence("Vollzeit bedeutet 40 Stunden.", "Full time means 40 hours."),
        sentence("Die Pause dauert 30 Minuten.", "The break lasts 30 minutes."),
        sentence("Morgen fange ich in der Firma an.", "Tomorrow I start at the company."),
        sentence("Die Arbeit ist interessant, nicht nur stressig.", "The work is interesting, not only stressful."),
        sentence("Ich bin nicht arbeitslos.", "I am not unemployed."),
        sentence("Bitte pünktlich zum Gespräch kommen.", "Please arrive on time for the interview."),
        sentence("Das Gehalt steht in der Anzeige.", "The salary is in the advert."),
        sentence("Wir helfen den Kunden gern.", "We are happy to help the customers."),
        sentence("Ich kündige nicht ohne Plan.", "I do not resign without a plan."),
      ],
      readings: [
        reading(
          "Job advert",
          "Stellenanzeige",
          "Café Mitte sucht Servicekraft, Teilzeit, ab sofort. Erfahrung gern, aber nicht Pflicht. Deutsch A2. Arbeitszeiten: 11–15 Uhr. Bewerbung mit Lebenslauf an jobs@cafemitte.de. Pünktliche Menschen gesucht.",
          "Café Mitte is looking for waiting staff, part time, immediately. Experience welcome but not required. German A2. Hours: 11 a.m.–3 p.m. Application with CV to jobs@cafemitte.de. Punctual people wanted.",
          [
            q("Is experience required?", "No", ["Yes, five years", "No", "Only in hotels", "Must be A1"]),
            q("What German level?", "A2", ["C1", "A2", "None", "B2 only"]),
            q("When are the working hours?", "11–15", ["Night shift", "11–15", "Full time 40h", "Weekends only"]),
          ],
        ),
        reading(
          "After an interview",
          "Nach dem Gespräch",
          "Das Vorstellungsgespräch war kurz. Die Chefin hat nach Schicht und Gehalt gefragt. Die Kollegen wirken nett. Die Firma ist klein. Nächste Woche kommt die Antwort. Ich bin nervös, aber hoffnungsvoll.",
          "The interview was short. The boss asked about shifts and salary. The colleagues seem nice. The company is small. Next week the answer comes. I am nervous but hopeful.",
          [
            q("What was asked about?", "Shifts and salary", ["Holidays only", "Shifts and salary", "Pets", "Football"]),
            q("When is the answer?", "Next week", ["Today", "Next week", "Never", "In a year"]),
            q("How does the writer feel?", "Nervous but hopeful", ["Angry", "Bored", "Nervous but hopeful", "Ill"]),
          ],
        ),
        reading(
          "Office chat",
          "Im Büro",
          "Die Pause ist um zwölf. Bitte die Kunden nicht warten lassen. Überstunden nur mit der Chefin absprechen. Neue Aufgabe: Telefon von 9 bis 11. Der Job ist stressig, aber das Team hilft.",
          "The break is at twelve. Please do not leave customers waiting. Overtime only after agreeing with the boss. New task: phone from 9 to 11. The job is stressful, but the team helps.",
          [
            q("When is the break?", "At twelve", ["At nine", "At twelve", "At 22:00", "Never"]),
            q("Who must agree overtime?", "The boss", ["Customers", "The boss", "Nobody", "The bus driver"]),
            q("What is the new task?", "Phone duty 9–11", ["Cooking", "Phone duty 9–11", "Travel", "Cleaning only"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe your job or a job you want in five sentences.",
          "Beschreib einen Beruf.",
          "Ich arbeite als Student in einem Café. Die Arbeit ist Teilzeit. Die Kollegen sind nett. Manchmal ist es stressig. Das Gehalt ist okay.",
          ["arbeiten als / bei", "One plus, one minus"],
        ),
        writing(
          "Write a two-line application opener.",
          "Schreib den Anfang einer Bewerbung.",
          "Guten Tag, ich bewerbe mich um die Stelle im Café. Ich habe etwas Erfahrung und bin pünktlich.",
          ["Name the position", "Give one strength"],
        ),
      ],
    },
  ),
  chapter(
    "perfect-tense",
    "Talking about the Past (Perfekt)",
    "Über die Vergangenheit sprechen (Perfekt)",
    "Read short past notes, then write what you did yesterday with haben and sein.",
    "grammar",
    [
      "Perfekt: haben/sein in the present + past participle at the end.",
      "Most verbs take haben. Movement and change of state often take sein: gegangen, gefahren, gewesen.",
      "ge- + stem + -t for weak verbs (gemacht); strong verbs often -en (gesehen).",
    ],
    {
      vocab: [
        vocab("gestern", "yesterday"),
        vocab("letzte Woche", "last week"),
        vocab("gemacht", "done / made"),
        vocab("gesehen", "seen"),
        vocab("gegangen", "gone"),
        vocab("gefahren", "travelled / driven"),
        vocab("gewesen", "been"),
        vocab("gehabt", "had"),
        vocab("gegessen", "eaten"),
        vocab("getrunken", "drunk"),
        vocab("geschlafen", "slept"),
        vocab("getroffen", "met"),
        vocab("gekauft", "bought"),
        vocab("gelernt", "learned / studied"),
        vocab("geschrieben", "written"),
        vocab("gelesen", "read"),
        vocab("geblieben", "stayed"),
        vocab("angekommen", "arrived"),
        vocab("aufgestanden", "got up"),
        vocab("das Partizip", "the participle", undefined, "Partizipien"),
        vocab("die Vergangenheit", "the past"),
        vocab("schon", "already"),
        vocab("noch nicht", "not yet"),
        vocab("nie", "never"),
        vocab("einmal", "once"),
        vocab("zweimal", "twice"),
        vocab("warum", "why"),
        vocab("weil", "because"),
        vocab("das Wochenende", "the weekend"),
        vocab("der Ausflug", "the trip"),
        vocab("endlich", "finally"),
        vocab("plötzlich", "suddenly"),
      ],
      phrases: [
        phrase("Was hast du gestern gemacht?", "What did you do yesterday?"),
        phrase("Ich habe bis zehn geschlafen.", "I slept until ten."),
        phrase("Wir sind ins Kino gegangen.", "We went to the cinema."),
        phrase("Sie ist mit dem Zug gefahren.", "She went by train."),
        phrase("Hast du schon gegessen?", "Have you already eaten?"),
        phrase("Ich habe Deutsch gelernt.", "I studied German."),
        phrase("Er hat seine Freunde getroffen.", "He met his friends."),
        phrase("Wir sind zu Hause geblieben.", "We stayed at home."),
        phrase("Ich bin um acht angekommen.", "I arrived at eight."),
        phrase("Warum bist du nicht gekommen?", "Why didn't you come?"),
        phrase("Weil ich krank gewesen bin.", "Because I was ill."),
        phrase("Das habe ich noch nicht gemacht.", "I haven't done that yet."),
      ],
      sentences: [
        sentence("Gestern habe ich Pizza gegessen.", "Yesterday I ate pizza."),
        sentence("Ich bin früh aufgestanden.", "I got up early."),
        sentence("Sie hat einen Brief geschrieben.", "She wrote a letter."),
        sentence("Wir haben einen Film gesehen.", "We watched a film."),
        sentence("Er ist nach Hause gegangen.", "He went home."),
        sentence("Ihr habt Kaffee getrunken.", "You (pl) drank coffee."),
        sentence("Ich habe das Buch gelesen.", "I read the book."),
        sentence("Sie sind pünktlich angekommen.", "They arrived on time."),
        sentence("Ich habe keine Zeit gehabt.", "I did not have time."),
        sentence("Wir sind nicht gefahren.", "We did not go (by vehicle)."),
        sentence("Hast du die E-Mails geschrieben?", "Did you write the emails?"),
        sentence("Ich habe zweimal angerufen.", "I called twice."),
        sentence("Letzte Woche sind wir gewandert.", "Last week we went hiking."),
        sentence("Plötzlich hat es geregnet.", "Suddenly it rained."),
        sentence("Endlich habe ich den Termin bekommen.", "I finally got the appointment."),
        sentence("Er hat nie Fußball gespielt.", "He has never played football."),
        sentence("Wo seid ihr gewesen?", "Where have you been?"),
        sentence("Ich bin im Park gewesen.", "I was in the park."),
      ],
      readings: [
        reading(
          "Weekend recap",
          "Wochenendbericht",
          "Am Samstag bin ich spät aufgestanden. Dann habe ich gefrühstückt und Freunde getroffen. Wir sind ins Museum gegangen. Es hat nicht geregnet. Am Abend haben wir zusammen gekocht. Ein schönes Wochenende!",
          "On Saturday I got up late. Then I had breakfast and met friends. We went to the museum. It did not rain. In the evening we cooked together. A lovely weekend!",
          [
            q("Did they go to a museum?", "Yes", ["No", "Yes", "Only a café", "Unknown"]),
            q("Did it rain?", "No", ["Yes", "No", "Snowed", "All day"]),
            q("What did they do in the evening?", "Cooked together", ["Slept", "Cooked together", "Flew", "Worked overtime"]),
          ],
        ),
        reading(
          "Missed meeting",
          "Verpasstes Treffen",
          "Warum bist du nicht gekommen? Ich habe eine Stunde gewartet. Der Bus ist zu spät gefahren. Ich bin dann nach Hause gegangen. Schreib bitte, was passiert ist. Ich habe mir Sorgen gemacht.",
          "Why didn't you come? I waited an hour. The bus left too late. I then went home. Please write what happened. I was worried.",
          [
            q("How long did the writer wait?", "An hour", ["A minute", "An hour", "All night", "Never"]),
            q("What was late?", "The bus", ["The museum", "The bus", "The food", "The film"]),
            q("How did the writer feel?", "Worried", ["Happy", "Worried", "Bored only", "Angry at rain"]),
          ],
        ),
        reading(
          "Learning log",
          "Lerntagebuch",
          "Heute habe ich 20 Wörter gelernt. Ich habe den Text zweimal gelesen. Die Übung habe ich noch nicht gemacht. Gestern bin ich zu müde gewesen. Morgen habe ich mehr Zeit. Das Partizip ist noch schwer.",
          "Today I learned 20 words. I read the text twice. I have not done the exercise yet. Yesterday I was too tired. Tomorrow I will have more time. The participle is still hard.",
          [
            q("How many words today?", "20", ["2", "20", "100", "None"]),
            q("Is the exercise done?", "Not yet", ["Yes", "Not yet", "Twice", "Never assigned"]),
            q("Why not yesterday?", "Too tired", ["A party", "Too tired", "No book", "Travel"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write six Perfekt sentences about yesterday.",
          "Schreib sechs Sätze im Perfekt.",
          "Gestern bin ich früh aufgestanden. Ich habe Kaffee getrunken. Dann bin ich zur Arbeit gefahren. Ich habe Kollegen getroffen. Am Abend habe ich Deutsch gelernt. Ich bin um zehn schlafen gegangen.",
          ["Mix haben and sein", "Participle at the end"],
        ),
        writing(
          "Answer: Was hast du letztes Wochenende gemacht?",
          "Antworte auf die Frage.",
          "Ich bin im Park gewesen. Ich habe ein Buch gelesen. Wir haben Pizza gegessen.",
          ["Three different verbs"],
        ),
      ],
    },
  ),
  chapter(
    "short-stories",
    "Reading Short Stories & Emails",
    "Kurze Geschichten und E-Mails lesen",
    "Follow a narrative across paragraphs and catch who did what.",
    "reading",
    [
      "Read names and time markers first (gestern, dann, plötzlich).",
      "weil and dass send the verb to the end of the clause.",
      "Guess unknown words from the rest of the sentence before you look them up.",
    ],
    {
      vocab: [
        vocab("die Geschichte", "the story", undefined, "Geschichten"),
        vocab("die E-Mail", "the email", undefined, "E-Mails"),
        vocab("der Absender", "the sender", undefined, "Absender"),
        vocab("der Empfänger", "the recipient", undefined, "Empfänger"),
        vocab("plötzlich", "suddenly"),
        vocab("danach", "afterwards"),
        vocab("deshalb", "therefore"),
        vocab("trotzdem", "nevertheless"),
        vocab("die Überraschung", "the surprise", undefined, "Überraschungen"),
        vocab("das Problem", "the problem", undefined, "Probleme"),
        vocab("die Lösung", "the solution", undefined, "Lösungen"),
        vocab("sich erinnern", "to remember"),
        vocab("vergessen", "to forget"),
        vocab("erzählen", "to tell"),
        vocab("erklären", "to explain"),
        vocab("hoffen", "to hope"),
        vocab("sich freuen", "to be glad"),
        vocab("sich ärgern", "to be annoyed"),
        vocab("der Nachbar", "the neighbour (m)", undefined, "Nachbarn"),
        vocab("die Nachbarin", "the neighbour (f)", undefined, "Nachbarinnen"),
        vocab("der Schlüssel", "the key", undefined, "Schlüssel"),
        vocab("die Tür", "the door"),
        vocab("das Handy", "the phone"),
        vocab("der Anruf", "the call", undefined, "Anrufe"),
        vocab("wichtig", "important"),
        vocab("seltsam", "strange"),
        vocab("endlich", "finally"),
        vocab("zum Glück", "fortunately"),
        vocab("leider", "unfortunately"),
        vocab("wahr", "true"),
        vocab("passieren", "to happen"),
        vocab("der Schluss", "the ending", undefined, "Schlüsse"),
      ],
      phrases: [
        phrase("Was ist passiert?", "What happened?"),
        phrase("Erzähl mir die Geschichte.", "Tell me the story."),
        phrase("Ich habe deine E-Mail gelesen.", "I have read your email."),
        phrase("Zum Glück war ein Nachbar da.", "Fortunately a neighbour was there."),
        phrase("Leider habe ich den Schlüssel vergessen.", "Unfortunately I forgot the key."),
        phrase("Deshalb bin ich zu spät gekommen.", "That is why I arrived too late."),
        phrase("Trotzdem hat alles gut geklappt.", "Nevertheless everything worked out."),
        phrase("Ich hoffe, du verstehst das.", "I hope you understand that."),
        phrase("Bitte antworte bald.", "Please reply soon."),
        phrase("Das Ende hat mich überrascht.", "The ending surprised me."),
        phrase("Ist die Geschichte wahr?", "Is the story true?"),
        phrase("Ich erinnere mich nicht genau.", "I don't remember exactly."),
      ],
      sentences: [
        sentence("Plötzlich hat das Handy geklingelt.", "Suddenly the phone rang."),
        sentence("Die Nachbarin hat die Tür geöffnet.", "The neighbour opened the door."),
        sentence("Ich habe die E-Mail zweimal gelesen.", "I read the email twice."),
        sentence("Er hat die Lösung schnell gefunden.", "He found the solution quickly."),
        sentence("Wir haben uns sehr gefreut.", "We were very glad."),
        sentence("Sie hat sich über den Lärm geärgert.", "She was annoyed about the noise."),
        sentence("Der Absender war unbekannt.", "The sender was unknown."),
        sentence("Das Problem war nicht so groß.", "The problem was not that big."),
        sentence("Endlich hat er den Schlüssel gefunden.", "Finally he found the key."),
        sentence("Die Geschichte ist kurz, aber spannend.", "The story is short but exciting."),
        sentence("Ich habe vergessen zu antworten.", "I forgot to reply."),
        sentence("Was du erzählst, klingt seltsam.", "What you are telling sounds strange."),
        sentence("Deshalb schreiben wir klar und kurz.", "That is why we write clearly and briefly."),
        sentence("Der Anruf war wichtig.", "The call was important."),
        sentence("Trotzdem bin ich ruhig geblieben.", "Nevertheless I stayed calm."),
        sentence("Am Schluss haben alle gelacht.", "In the end everyone laughed."),
        sentence("Ist das wirklich passiert?", "Did that really happen?"),
        sentence("Ich hoffe auf eine schnelle Antwort.", "I hope for a quick reply."),
      ],
      readings: [
        reading(
          "The missing key",
          "Der fehlende Schlüssel",
          "Gestern Abend wollte Mara nach Hause. An der Tür hat sie gemerkt, dass der Schlüssel nicht in der Tasche war. Sie hat die Nachbarin angerufen, aber niemand hat gehört. Plötzlich hat ihr Bruder geschrieben: Der Schlüssel liegt im Café. Mara ist zurückgerannt. Zum Glück war das Café noch auf. Sie hat den Schlüssel geholt und ist müde, aber froh nach Hause gegangen.",
          "Yesterday evening Mara wanted to go home. At the door she noticed the key was not in her bag. She called the neighbour, but nobody heard. Suddenly her brother wrote: The key is in the café. Mara ran back. Fortunately the café was still open. She got the key and went home tired but glad.",
          [
            q("Where was the key?", "In the café", ["At work", "In the café", "With the neighbour", "In the door"]),
            q("Who told Mara?", "Her brother", ["The boss", "Her brother", "A stranger", "The police"]),
            q("Was the café closed?", "No", ["Yes", "No", "Only on Sundays", "Unknown"]),
          ],
        ),
        reading(
          "An email from a landlord",
          "E-Mail vom Vermieter",
          "Betreff: Heizung. Liebe Frau Costa, die Heizung ist seit gestern kaputt. Ein Techniker kommt morgen zwischen 9 und 12. Bitte zu Hause bleiben oder einen Schlüssel hinterlegen. Wir haben das Problem schon gemeldet. Entschuldigung für den kalten Abend. Mit freundlichen Grüßen, J. Berg.",
          "Subject: Heating. Dear Ms Costa, the heating has been broken since yesterday. A technician is coming tomorrow between 9 and 12. Please stay at home or leave a key. We have already reported the problem. Sorry for the cold evening. Kind regards, J. Berg.",
          [
            q("What is broken?", "The heating", ["The door", "The heating", "The café", "The phone"]),
            q("When is the technician coming?", "Tomorrow 9–12", ["Today at 8", "Tomorrow 9–12", "Next month", "Never"]),
            q("What can she do if she is out?", "Leave a key", ["Call the police", "Leave a key", "Open a café", "Wait a year"]),
          ],
        ),
        reading(
          "A surprising ending",
          "Ein überraschendes Ende",
          "Tim hat eine seltsame E-Mail bekommen. Der Absender hat geschrieben, Tim hat im Lotto gewonnen. Tim hat sich erst gefreut, dann hat er den Text noch einmal gelesen. Es war Werbung. Deshalb hat er gelacht und die Mail gelöscht. Trotzdem hat er Freunden die Geschichte erzählt, weil sie lustig war.",
          "Tim received a strange email. The sender wrote that Tim had won the lottery. Tim was glad at first, then he read the text again. It was advertising. So he laughed and deleted the mail. Still he told friends the story because it was funny.",
          [
            q("Did Tim win the lottery?", "No, it was advertising", ["Yes", "No, it was advertising", "His neighbour did", "Unknown"]),
            q("What did he do with the email?", "Deleted it", ["Printed it", "Deleted it", "Paid money", "Called a lawyer"]),
            q("Why did he tell friends?", "Because it was funny", ["Because he was angry", "Because it was funny", "For work", "He didn't"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Retell Mara's key story in five sentences.",
          "Erzähl Maras Geschichte nach.",
          "Mara hat den Schlüssel vergessen. Sie hat die Nachbarin angerufen. Niemand war da. Ihr Bruder hat geschrieben. Das Café war noch offen.",
          ["Perfekt", "Keep the order of events"],
        ),
        writing(
          "Write a 4-sentence reply to the landlord.",
          "Schreib eine Antwort an den Vermieter.",
          "Guten Tag, danke für die Information. Ich bin morgen Vormittag zu Hause. Die Wohnung ist kalt, aber okay. Viele Grüße.",
          ["Thank + availability + a polite close"],
        ),
      ],
    },
  ),
  chapter(
    "emails-notes",
    "Writing Notes, Emails & Postcards",
    "Notizen, E-Mails und Postkarten schreiben",
    "Move from reading models to producing clear everyday writing.",
    "writing",
    [
      "Informal: Hallo / Liebe … Viele Grüße. Formal: Sehr geehrte … Mit freundlichen Grüßen.",
      "State the reason in sentence one. Details after. A question or request last.",
      "weil / dass / wenn: conjugated verb at the end of the clause.",
    ],
    {
      vocab: [
        vocab("die Anrede", "the salutation", undefined, "Anreden"),
        vocab("die Grußformel", "the closing formula", undefined, "Grußformeln"),
        vocab("formell", "formal"),
        vocab("informell", "informal"),
        vocab("der Betreff", "the subject line", undefined, "Betreffe"),
        vocab("die Bitte", "the request", undefined, "Bitten"),
        vocab("die Entschuldigung", "the apology", undefined, "Entschuldigungen"),
        vocab("die Einladung", "the invitation", undefined, "Einladungen"),
        vocab("die Bestätigung", "the confirmation", undefined, "Bestätigungen"),
        vocab("anhängen", "to attach"),
        vocab("der Anhang", "the attachment", undefined, "Anhänge"),
        vocab("beantworten", "to answer"),
        vocab("weiterleiten", "to forward"),
        vocab("löschen", "to delete"),
        vocab("dringend", "urgent"),
        vocab("bald", "soon"),
        vocab("sobald", "as soon as"),
        vocab("falls", "in case"),
        vocab("damit", "so that"),
        vocab("freundliche Grüße", "kind regards"),
        vocab("herzliche Grüße", "warm regards"),
        vocab("die Postkarte", "the postcard", undefined, "Postkarten"),
        vocab("die Notiz", "the note"),
        vocab("klar", "clear"),
        vocab("höflich", "polite"),
        vocab("der Ton", "the tone", undefined, "Töne"),
        vocab("der Fehler", "the mistake"),
        vocab("korrigieren", "to correct"),
        vocab("schicken", "to send"),
        vocab("bekommen", "to receive"),
        vocab("warten", "to wait"),
        vocab("besuchen", "to visit"),
      ],
      phrases: [
        phrase("Sehr geehrte Frau Lang,", "Dear Ms Lang,"),
        phrase("Hallo Markus,", "Hi Markus,"),
        phrase("vielen Dank für Ihre E-Mail.", "Thank you very much for your email."),
        phrase("ich schreibe, weil ich krank bin.", "I am writing because I am ill."),
        phrase("Könnten Sie mir bitte helfen?", "Could you please help me?"),
        phrase("Im Anhang finden Sie den Text.", "You will find the text attached."),
        phrase("Bitte um kurze Bestätigung.", "Please confirm briefly."),
        phrase("Ich freue mich auf deine Antwort.", "I look forward to your reply."),
        phrase("Mit freundlichen Grüßen", "Yours sincerely"),
        phrase("Liebe Grüße aus Wien", "Love from Vienna"),
        phrase("Falls du Zeit hast, ruf an.", "If you have time, call."),
        phrase("Entschuldigung für die späte Antwort.", "Sorry for the late reply."),
      ],
      sentences: [
        sentence("Ich schreibe eine formelle E-Mail an das Amt.", "I am writing a formal email to the office."),
        sentence("Der Betreff muss klar sein.", "The subject line must be clear."),
        sentence("Bitte hänge das Foto an.", "Please attach the photo."),
        sentence("Wir haben die Einladung bekommen.", "We received the invitation."),
        sentence("Ich beantworte die Mail heute Abend.", "I will answer the mail this evening."),
        sentence("Lösche die Nachricht nicht.", "Do not delete the message."),
        sentence("Die Bitte ist höflich und kurz.", "The request is polite and short."),
        sentence("Sobald ich Zeit habe, schreibe ich.", "As soon as I have time, I will write."),
        sentence("Damit du den Weg findest, schicke ich einen Plan.", "So that you find the way, I am sending a map."),
        sentence("Herzliche Grüße von deiner Schwester.", "Warm regards from your sister."),
        sentence("Die Postkarte ist klein, der Text auch.", "The postcard is small, the text too."),
        sentence("Korrigiere die Fehler vor dem Senden.", "Correct the mistakes before sending."),
        sentence("Wir warten auf eine Bestätigung.", "We are waiting for a confirmation."),
        sentence("Besucht uns am Wochenende!", "Visit us at the weekend!"),
        sentence("Der Ton in der Mail ist zu hart.", "The tone in the email is too harsh."),
        sentence("Eine Notiz am Kühlschrank reicht.", "A note on the fridge is enough."),
        sentence("Ich leite die Information weiter.", "I am forwarding the information."),
        sentence("Danke, dass du schnell geantwortet hast.", "Thanks for replying quickly."),
      ],
      readings: [
        reading(
          "Model formal email",
          "Formelle Modellmail",
          "Betreff: Terminverschiebung. Sehr geehrter Herr Otto, ich schreibe, weil ich den Termin am Freitag nicht wahrnehmen kann. Könnten wir auf Montag um 10 Uhr verschieben? Im Anhang ist mein Kalender. Vielen Dank und mit freundlichen Grüßen, N. Silva.",
          "Subject: Appointment change. Dear Mr Otto, I am writing because I cannot attend the appointment on Friday. Could we move it to Monday at 10 a.m.? My calendar is attached. Thank you and yours sincerely, N. Silva.",
          [
            q("Why is the writer emailing?", "To change an appointment", ["To buy bread", "To change an appointment", "To resign", "To book a flight"]),
            q("What new time is suggested?", "Monday 10:00", ["Friday 10:00", "Monday 10:00", "Sunday", "Never"]),
            q("What is attached?", "A calendar", ["A photo of a dog", "A calendar", "Money", "A ticket"]),
          ],
        ),
        reading(
          "Informal postcard",
          "Informelle Karte",
          "Hallo Kim! Hamburg ist windig, aber schön. Wir haben den Hafen besucht und Fischbrötchen gegessen. Heute Abend Kino, falls wir nicht zu müde sind. Liebe Grüße, Alex. P.S. Schreib bald!",
          "Hi Kim! Hamburg is windy but lovely. We visited the harbour and ate fish rolls. This evening cinema if we are not too tired. Love, Alex. P.S. Write soon!",
          [
            q("What did they eat?", "Fish rolls", ["Pizza", "Fish rolls", "Nothing", "Cake only"]),
            q("What might they do this evening?", "Cinema", ["Work", "Cinema", "A flight", "An exam"]),
            q("How is Hamburg described?", "Windy but lovely", ["Hot and quiet", "Windy but lovely", "Closed", "Boring"]),
          ],
        ),
        reading(
          "Fridge note",
          "Kühlschranknotiz",
          "Milch ist alle. Bitte kaufen! Ich komme spät, weil das Büro voll ist. Pizza ist im Ofen, 10 Minuten. Falls du Hunger hast, nicht warten. Danke, Sam.",
          "Milk is gone. Please buy some! I am coming home late because the office is full. Pizza is in the oven, 10 minutes. If you are hungry, don't wait. Thanks, Sam.",
          [
            q("What should be bought?", "Milk", ["Pizza", "Milk", "Tickets", "A fridge"]),
            q("Why is Sam late?", "The office is busy", ["A train strike only", "The office is busy", "Holiday", "Illness"]),
            q("How long for the pizza?", "10 minutes", ["1 hour", "10 minutes", "All night", "No pizza"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a formal 5-line email to move a meeting.",
          "Schreib eine formelle Mail.",
          "Sehr geehrte Frau Lang, ich schreibe, weil ich den Termin verschieben muss. Wäre Dienstag möglich? Vielen Dank. Mit freundlichen Grüßen, Ben Adler.",
          ["Sehr geehrte …", "weil-clause", "Mit freundlichen Grüßen"],
        ),
        writing(
          "Write an informal note of 4 sentences.",
          "Schreib eine informelle Notiz.",
          "Hallo Lea, ich bin später da, weil der Bus Verspätung hat. Iss ohne mich. Bis bald, Omar.",
          ["Hallo + reason + instruction + greeting"],
        ),
      ],
    },
  ),
  chapter(
    "modal-verbs",
    "Modal Verbs: Can, Must, Want, Should",
    "Modalverben: können, müssen, wollen, sollen",
    "Read rules and requests, then write what you can, must, and want to do.",
    "grammar",
    [
      "Modal + infinitive at the end: Ich muss morgen arbeiten.",
      "können = ability/permission, müssen = necessity, wollen = desire, sollen = ought to / is supposed to, dürfen = permission, mögen/möchte = like / would like.",
      "In questions the modal comes second: Kannst du mir helfen?",
    ],
    {
      vocab: [
        vocab("können", "can / to be able to"),
        vocab("müssen", "must / to have to"),
        vocab("wollen", "to want to"),
        vocab("sollen", "should / ought to"),
        vocab("dürfen", "may / to be allowed to"),
        vocab("mögen", "to like"),
        vocab("möchten", "would like"),
        vocab("die Regel", "the rule", undefined, "Regeln"),
        vocab("die Erlaubnis", "permission"),
        vocab("das Verbot", "the ban", undefined, "Verbote"),
        vocab("nötig", "necessary"),
        vocab("möglich", "possible"),
        vocab("unmöglich", "impossible"),
        vocab("helfen", "to help"),
        vocab("warten", "to wait"),
        vocab("bleiben", "to stay"),
        vocab("gehen", "to go"),
        vocab("sprechen", "to speak"),
        vocab("verstehen", "to understand"),
        vocab("lernen", "to learn"),
        vocab("arbeiten", "to work"),
        vocab("schlafen", "to sleep"),
        vocab("rauchen", "to smoke"),
        vocab("parken", "to park"),
        vocab("hier", "here"),
        vocab("jetzt", "now"),
        vocab("sofort", "immediately"),
        vocab("leider", "unfortunately"),
        vocab("vielleicht", "maybe"),
        vocab("unbedingt", "absolutely"),
        vocab("lieber", "rather"),
        vocab("die Pflicht", "the duty", undefined, "Pflichten"),
      ],
      phrases: [
        phrase("Kannst du das Fenster öffnen?", "Can you open the window?"),
        phrase("Ich muss jetzt gehen.", "I have to go now."),
        phrase("Wir wollen am Samstag schwimmen.", "We want to swim on Saturday."),
        phrase("Du sollst mehr Wasser trinken.", "You should drink more water."),
        phrase("Hier darf man nicht rauchen.", "You must not smoke here."),
        phrase("Ich möchte einen Termin.", "I would like an appointment."),
        phrase("Leider kann ich nicht kommen.", "Unfortunately I cannot come."),
        phrase("Müssen wir unbedingt heute fertig sein?", "Do we absolutely have to finish today?"),
        phrase("Kinder dürfen nicht allein bleiben.", "Children are not allowed to stay alone."),
        phrase("Ich mag diese Regel nicht.", "I don't like this rule."),
        phrase("Vielleicht können wir später reden.", "Maybe we can talk later."),
        phrase("Sie soll um drei anrufen.", "She is supposed to call at three."),
      ],
      sentences: [
        sentence("Ich kann ein bisschen Deutsch sprechen.", "I can speak a little German."),
        sentence("Er muss um sieben aufstehen.", "He has to get up at seven."),
        sentence("Wollt ihr mitkommen?", "Do you want to come along?"),
        sentence("Ihr sollt die Hausaufgaben machen.", "You should do the homework."),
        sentence("Man darf hier nicht parken.", "You are not allowed to park here."),
        sentence("Möchten Sie Tee oder Kaffee?", "Would you like tea or coffee?"),
        sentence("Wir können uns um vier treffen.", "We can meet at four."),
        sentence("Ich will nicht länger warten.", "I do not want to wait any longer."),
        sentence("Sie muss zum Arzt gehen.", "She has to go to the doctor."),
        sentence("Darf ich Sie etwas fragen?", "May I ask you something?"),
        sentence("Kinder sollen genug schlafen.", "Children should sleep enough."),
        sentence("Es ist unmöglich, heute noch zu fliegen.", "It is impossible to fly today still."),
        sentence("Ich möchte lieber zu Fuß gehen.", "I would rather walk."),
        sentence("Sofort müsst ihr die Tür schließen.", "You must close the door immediately."),
        sentence("Er mag keine Verbote.", "He does not like bans."),
        sentence("Können Sie langsamer sprechen?", "Can you speak more slowly?"),
        sentence("Wir dürfen das Büro nach 18 Uhr nicht betreten.", "We may not enter the office after 6 p.m."),
        sentence("Ich soll dir helfen, das hat Anna gesagt.", "I am supposed to help you, Anna said."),
      ],
      readings: [
        reading(
          "Hostel rules",
          "Hausregeln",
          "Gäste müssen bis 10 Uhr auschecken. Man darf in den Zimmern nicht rauchen. Nach 22 Uhr soll es ruhig sein. Ihr könnt das WLAN überall nutzen. Küche wollen viele teilen — bitte sofort spülen. Hunde dürfen nicht bleiben.",
          "Guests must check out by 10 a.m. You may not smoke in the rooms. After 10 p.m. it should be quiet. You can use the wifi everywhere. Many people want to share the kitchen — please wash up immediately. Dogs are not allowed to stay.",
          [
            q("Latest checkout?", "10:00", ["22:00", "10:00", "Noon", "Never"]),
            q("Are dogs allowed?", "No", ["Yes", "No", "Only small ones", "In the kitchen"]),
            q("What about 22:00?", "It should be quiet", ["Checkout", "It should be quiet", "Breakfast", "Smoking time"]),
          ],
        ),
        reading(
          "A cancelled plan",
          "Abgesagter Plan",
          "Wir wollten ins Schwimmbad, aber ich muss arbeiten. Kannst du nächste Woche? Ich möchte unbedingt schwimmen, nur nicht heute. Vielleicht können Mira und Jan mitkommen. Du sollst nicht allein fahren, wenn es regnet.",
          "We wanted to go to the pool, but I have to work. Can you do next week? I really want to swim, just not today. Maybe Mira and Jan can come. You should not go alone if it rains.",
          [
            q("Why not today?", "Work", ["Rain only", "Work", "No tickets", "Illness"]),
            q("Who might join?", "Mira and Jan", ["The boss", "Mira and Jan", "Nobody", "A dog"]),
            q("What if it rains?", "Don't go alone", ["Swim more", "Don't go alone", "Work later", "Smoke"]),
          ],
        ),
        reading(
          "Office permission",
          "Büro-Erlaubnis",
          "Homeoffice: Ihr dürft dienstags und donnerstags zu Hause arbeiten. Ihr müsst erreichbar sein. Dateien sollt ihr abends speichern. Kundenanrufe können ins Büro umgeleitet werden. Rauchen ist vor der Tür erlaubt, nicht im Flur.",
          "Home office: You may work from home on Tuesdays and Thursdays. You must be reachable. You should save files in the evening. Customer calls can be redirected to the office. Smoking is allowed in front of the door, not in the hallway.",
          [
            q("Which days is home office allowed?", "Tuesday and Thursday", ["Every day", "Tuesday and Thursday", "Never", "Weekends"]),
            q("What must staff be?", "Reachable", ["Silent", "Reachable", "In the pool", "Offline"]),
            q("Where is smoking allowed?", "In front of the door", ["In the hall", "In front of the door", "At desks", "Nowhere"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write five sentences, each with a different modal verb.",
          "Schreib fünf Modal-Sätze.",
          "Ich kann Deutsch lesen. Ich muss um acht anfangen. Ich will Pause machen. Ich soll Wasser trinken. Ich darf nicht rauchen.",
          ["können, müssen, wollen, sollen, dürfen"],
        ),
        writing(
          "Write a short rule list for a shared kitchen.",
          "Schreib Küchenregeln.",
          "Man muss spülen. Man darf nicht alles essen. Man soll den Tisch abwischen. Man kann Gewürze benutzen.",
          ["man + modal"],
        ),
      ],
    },
  ),
];
