import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const b1ChaptersPart2: ChapterSource[] = [
  chapter(
    "subordinate-clauses",
    "Subordinate Clauses: weil, dass, wenn, obwohl",
    "Nebensätze: weil, dass, wenn, obwohl",
    "Read arguments that hinge on clause order, then write complex but clear sentences.",
    "grammar",
    [
      "In a Nebensatz the conjugated verb moves to the end.",
      "wenn = if/when (future or repeated). als = when (once in the past). wann = when? (question).",
      "Comma before weil, dass, wenn, obwohl, damit, obwohl.",
    ],
    {
      vocab: [
        vocab("der Nebensatz", "the subordinate clause", undefined, "Nebensätze"),
        vocab("der Hauptsatz", "the main clause", undefined, "Hauptsätze"),
        vocab("weil", "because"),
        vocab("dass", "that"),
        vocab("wenn", "if / when"),
        vocab("als", "when (past, once)"),
        vocab("obwohl", "although"),
        vocab("damit", "so that"),
        vocab("während", "while / during"),
        vocab("bevor", "before"),
        vocab("nachdem", "after"),
        vocab("seit", "since"),
        vocab("bis", "until"),
        vocab("ob", "whether"),
        vocab("die Konjunktion", "the conjunction", undefined, "Konjunktionen"),
        vocab("die Wortstellung", "word order"),
        vocab("das Komma", "the comma", undefined, "Kommas"),
        vocab("deshalb", "therefore"),
        vocab("trotzdem", "nevertheless"),
        vocab("sonst", "otherwise"),
        vocab("falls", "in case"),
        vocab("sobald", "as soon as"),
        vocab("je ... desto", "the ... the"),
        vocab("nicht nur ... sondern auch", "not only ... but also"),
        vocab("entweder ... oder", "either ... or"),
        vocab("weder ... noch", "neither ... nor"),
        vocab("erklären", "to explain"),
        vocab("verstehen", "to understand"),
        vocab("passieren", "to happen"),
        vocab("wichtig", "important"),
        vocab("möglich", "possible"),
        vocab("nötig", "necessary"),
      ],
      phrases: [
        phrase("Ich bleibe zu Hause, weil ich krank bin.", "I am staying at home because I am ill."),
        phrase("Ich hoffe, dass du kommst.", "I hope that you are coming."),
        phrase("Wenn es regnet, nehmen wir den Bus.", "If it rains, we take the bus."),
        phrase("Als ich klein war, wohnte ich am Meer.", "When I was little I lived by the sea."),
        phrase("Obwohl der Test schwer war, habe ich ihn bestanden.", "Although the test was hard, I passed it."),
        phrase("Ruf an, bevor du kommst.", "Call before you come."),
        phrase("Nachdem wir gegessen hatten, gingen wir spazieren.", "After we had eaten, we went for a walk."),
        phrase("Ich weiß nicht, ob das stimmt.", "I don't know whether that is true."),
        phrase("Arbeite leise, während die anderen lesen.", "Work quietly while the others are reading."),
        phrase("Je mehr du übst, desto sicherer wirst du.", "The more you practice, the more confident you become."),
        phrase("Entweder wir fahren jetzt, oder wir verpassen den Zug.", "Either we leave now or we miss the train."),
        phrase("Weder Tee noch Kaffee ist da.", "There is neither tea nor coffee."),
      ],
      sentences: [
        sentence("Sie lernt Deutsch, damit sie in Wien arbeiten kann.", "She is learning German so that she can work in Vienna."),
        sentence("Falls der Zug ausfällt, nimm den Bus.", "If the train is cancelled, take the bus."),
        sentence("Sobald ich fertig bin, schreibe ich dir.", "As soon as I am finished, I will write to you."),
        sentence("Seit ich hier wohne, fahre ich Rad.", "Since I have lived here, I cycle."),
        sentence("Warte, bis die Ampel grün ist.", "Wait until the light is green."),
        sentence("Es ist wichtig, dass wir pünktlich sind.", "It is important that we are on time."),
        sentence("Ich frage mich, wann der Kurs beginnt.", "I wonder when the course starts."),
        sentence("Er kommt nicht, weil er keine Zeit hat.", "He is not coming because he has no time."),
        sentence("Wenn du willst, erkläre ich den Satz noch einmal.", "If you want, I will explain the sentence once more."),
        sentence("Nicht nur der Text, sondern auch die Fragen sind neu.", "Not only the text but also the questions are new."),
        sentence("Sonst verstehst du das Ende nicht.", "Otherwise you will not understand the ending."),
        sentence("Während des Films soll das Handy aus sein.", "During the film the phone should be off."),
        sentence("Ich bleibe, bis du anrufst.", "I will stay until you call."),
        sentence("Dass du das gesagt hast, hat mir geholfen.", "That you said that helped me."),
        sentence("Obwohl es spät ist, sind wir wach.", "Although it is late, we are awake."),
        sentence("Bevor du sendest, lies den Text.", "Before you send, read the text."),
        sentence("Nachdem sie angekommen war, wurde es ruhig.", "After she had arrived, it became quiet."),
        sentence("Ob das nötig ist, entscheiden wir morgen.", "Whether that is necessary we will decide tomorrow."),
      ],
      readings: [
        reading(
          "Advice column",
          "Ratgeber",
          "Viele schreiben, sie lernen nicht, weil sie keine Zeit haben. Ich glaube, dass kurze Blöcke helfen. Wenn du 15 Minuten täglich liest, wächst der Wortschatz. Obwohl das wenig klingt, ist es mehr als nichts. Sobald es zur Gewohnheit wird, fällt es leichter.",
          "Many write that they don't study because they have no time. I believe that short blocks help. If you read 15 minutes a day, vocabulary grows. Although that sounds like little, it is more than nothing. As soon as it becomes a habit, it gets easier.",
          [
            q("What reason do people give?", "No time", ["No books", "No time", "No teachers", "Too much money"]),
            q("How long should daily reading be?", "15 minutes", ["15 hours", "15 minutes", "One weekend", "Never"]),
            q("When does it get easier?", "When it becomes a habit", ["Never", "When it becomes a habit", "After one exam", "Only in summer"]),
          ],
        ),
        reading(
          "A travel condition",
          "Reisebedingung",
          "Wir fahren nur, wenn das Wetter mitspielt. Falls es stürmt, bleiben wir in der Jugendherberge. Bevor wir losgehen, prüfen wir die Bahn-App. Ich weiß nicht, ob die Seilbahn fährt. Damit niemand nass wird, packt Schirme ein.",
          "We only go if the weather plays along. If there is a storm we stay in the hostel. Before we leave we check the train app. I don't know whether the cable car is running. So that nobody gets wet, pack umbrellas.",
          [
            q("What if there is a storm?", "Stay in the hostel", ["Go anyway", "Stay in the hostel", "Fly home", "Swim"]),
            q("What is checked before leaving?", "The train app", ["Hotel stars", "The train app", "Hair", "Nothing"]),
            q("Why pack umbrellas?", "So nobody gets wet", ["For photos only", "So nobody gets wet", "It's a rule in exams", "No reason"]),
          ],
        ),
        reading(
          "Workplace email",
          "Dienstmail",
          "Bitte wartet, bis die Datei gespeichert ist, bevor ihr den Rechner ausmacht. Es ist möglich, dass ältere Versionen sonst verloren gehen. Wer unsicher ist, ob das Dokument aktuell ist, fragt im Chat. Damit alle dasselbe sehen, nutzen wir einen Ordner.",
          "Please wait until the file is saved before you switch the computer off. It is possible that older versions will otherwise be lost. Anyone unsure whether the document is current should ask in the chat. So that everyone sees the same thing, we use one folder.",
          [
            q("What must happen before shutdown?", "The file must be saved", ["A coffee", "The file must be saved", "A meeting", "Printing posters"]),
            q("Where should you ask if unsure?", "In the chat", ["Never", "In the chat", "At the airport", "In a newspaper"]),
            q("Why one folder?", "So everyone sees the same thing", ["Because it's pretty", "So everyone sees the same thing", "The law", "No wifi"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write five sentences, each with a different conjunction.",
          "Schreib fünf Nebensätze.",
          "Ich lerne, weil ich in Deutschland arbeiten will. Ich hoffe, dass der Kurs hilft. Wenn ich Zeit habe, lese ich. Obwohl ich müde bin, übe ich. Ich schreibe, damit du den Plan kennst.",
          ["Verb at the end of the Nebensatz", "Comma before the conjunction"],
        ),
        writing(
          "Combine two short sentences with weil and two with deshalb.",
          "Verbinde Sätze.",
          "Ich bleibe zu Hause, weil es regnet. Es regnet. Deshalb bleibe ich zu Hause.",
          ["weil = verb last; deshalb = new sentence, verb second"],
        ),
      ],
    },
  ),
  chapter(
    "narration",
    "Narrating Events & Travel Stories",
    "Ereignisse und Reisegeschichten erzählen",
    "Follow a story in Perfekt and Präteritum, then tell one of your own in order.",
    "writing",
    [
      "Spoken stories: Perfekt. Written reports and novels: often Präteritum (war, hatte, ging).",
      "Time chain: zuerst, dann, danach, plötzlich, am Ende, schließlich.",
      "sein + participle for movement: bin gefahren, ist gegangen, seid geflogen.",
    ],
    {
      vocab: [
        vocab("erzählen", "to tell"),
        vocab("berichten", "to report"),
        vocab("die Handlung", "the plot / action", undefined, "Handlungen"),
        vocab("der Anfang", "the beginning", undefined, "Anfänge"),
        vocab("das Ende", "the end", undefined, "Enden"),
        vocab("zuerst", "first"),
        vocab("dann", "then"),
        vocab("danach", "after that"),
        vocab("schließlich", "finally"),
        vocab("plötzlich", "suddenly"),
        vocab("inzwischen", "in the meantime"),
        vocab("vorher", "beforehand"),
        vocab("nachher", "afterwards"),
        vocab("damals", "at that time"),
        vocab("neulich", "recently"),
        vocab("die Erinnerung", "the memory", undefined, "Erinnerungen"),
        vocab("das Abenteuer", "the adventure", undefined, "Abenteuer"),
        vocab("die Panne", "the breakdown / mishap", undefined, "Pannen"),
        vocab("glücklicherweise", "fortunately"),
        vocab("leider", "unfortunately"),
        vocab("spannend", "exciting"),
        vocab("langweilig", "boring"),
        vocab("unvergesslich", "unforgettable"),
        vocab("sich verirren", "to get lost"),
        vocab("finden", "to find"),
        vocab("verlieren", "to lose"),
        vocab("ankommen", "to arrive"),
        vocab("losfahren", "to set off"),
        vocab("übernachten", "to spend the night"),
        vocab("die Aussicht", "the view", undefined, "Aussichten"),
        vocab("der Zufall", "chance / coincidence", undefined, "Zufälle"),
        vocab("die Pointe", "the punchline", undefined, "Pointen"),
      ],
      phrases: [
        phrase("Soll ich dir erzählen, was passiert ist?", "Shall I tell you what happened?"),
        phrase("Zuerst war alles ruhig.", "At first everything was calm."),
        phrase("Dann ist der Zug stehen geblieben.", "Then the train stopped."),
        phrase("Plötzlich hat jemand gelacht.", "Suddenly someone laughed."),
        phrase("Inzwischen war es dunkel geworden.", "In the meantime it had become dark."),
        phrase("Glücklicherweise hatten wir Wasser dabei.", "Fortunately we had water with us."),
        phrase("Am Ende sind wir doch angekommen.", "In the end we arrived after all."),
        phrase("Das war ein unvergesslicher Tag.", "That was an unforgettable day."),
        phrase("Damals wohnte ich noch in Lyon.", "At that time I still lived in Lyon."),
        phrase("Neulich bin ich fast zu spät gekommen.", "Recently I almost arrived too late."),
        phrase("Die Aussicht hat uns sprachlos gemacht.", "The view left us speechless."),
        phrase("Durch Zufall haben wir uns wiedergetroffen.", "By chance we met again."),
      ],
      sentences: [
        sentence("Wir sind früh losgefahren, weil der Stau vorhersehbar war.", "We set off early because the traffic jam was predictable."),
        sentence("Nachdem wir angekommen waren, haben wir zuerst Kaffee getrunken.", "After we had arrived, we first drank coffee."),
        sentence("Sie hat den Weg verloren und einen Bauern gefragt.", "She lost the way and asked a farmer."),
        sentence("Die Panne war klein, die Wartezeit lang.", "The mishap was small, the waiting time long."),
        sentence("Ich hatte Hunger, aber kein Bargeld.", "I was hungry but had no cash."),
        sentence("Er ging in die Pension und buchte ein Zimmer.", "He went into the guesthouse and booked a room."),
        sentence("Es war kalt, trotzdem sind wir draußen geblieben.", "It was cold; nevertheless we stayed outside."),
        sentence("Die Handlung klingt einfach, bis die Pointe kommt.", "The plot sounds simple until the punchline comes."),
        sentence("Wir haben in einer Hütte übernachtet.", "We spent the night in a hut."),
        sentence("Leider hat es den ganzen Tag geregnet.", "Unfortunately it rained all day."),
        sentence("Schließlich hat uns ein Taxi gefunden.", "Finally a taxi found us."),
        sentence("Die Erinnerung ist schöner als die Reise war.", "The memory is nicer than the trip was."),
        sentence("Vorher hatten wir keinen Plan, nachher zu viele Fotos.", "Beforehand we had no plan, afterwards too many photos."),
        sentence("Das Abenteuer begann an einer Tankstelle.", "The adventure began at a petrol station."),
        sentence("Ich berichte nur, was ich selbst gesehen habe.", "I am only reporting what I saw myself."),
        sentence("Der Anfang war langweilig, das Ende spannend.", "The beginning was boring, the ending exciting."),
        sentence("Wir haben uns im Wald verirrt.", "We got lost in the forest."),
        sentence("Dann haben wir die Markierung wiedergefunden.", "Then we found the trail marker again."),
      ],
      readings: [
        reading(
          "A delayed arrival",
          "Verspätete Ankunft",
          "Wir sind um sechs losgefahren. Zuerst lief alles glatt. Dann hat der Zug in Fulda gehalten und ist nicht weitergefahren. Inzwischen hatten wir nur noch einen Apfel. Plötzlich kam eine Durchsage: Ersatzbus in zwanzig Minuten. Schließlich sind wir um Mitternacht angekommen, müde und irgendwie stolz.",
          "We set off at six. At first everything went smoothly. Then the train stopped in Fulda and did not continue. In the meantime we only had one apple left. Suddenly there was an announcement: replacement bus in twenty minutes. Finally we arrived at midnight, tired and somehow proud.",
          [
            q("Where did the train stop?", "Fulda", ["Berlin", "Fulda", "A hut", "Lyon"]),
            q("What food was left?", "One apple", ["A feast", "One apple", "Nothing named", "Pizza"]),
            q("When did they arrive?", "At midnight", ["At six", "At midnight", "At noon", "Never"]),
          ],
        ),
        reading(
          "Postcard from the Alps",
          "Karte aus den Alpen",
          "Liebe Oma, gestern sind wir gewandert. Die Aussicht war unvergesslich. Leider hat Leo den Hut verloren. Glücklicherweise hat ihn ein Hund zurückgebracht — kein Witz. Heute bleiben wir im Tal, weil die Beine müde sind. Bis bald, Nora.",
          "Dear Grandma, yesterday we went hiking. The view was unforgettable. Unfortunately Leo lost the hat. Fortunately a dog brought it back — no joke. Today we are staying in the valley because our legs are tired. See you soon, Nora.",
          [
            q("What did Leo lose?", "A hat", ["A dog", "A hat", "A train", "A hut"]),
            q("Who brought it back?", "A dog", ["Grandma", "A dog", "A taxi", "Nobody"]),
            q("Why stay in the valley today?", "Tired legs", ["Rain only", "Tired legs", "A party", "Work"]),
          ],
        ),
        reading(
          "A coincidence",
          "Ein Zufall",
          "Neulich stand ich in einer langen Schlange. Vorher war ich schlecht gelaunt. Dann hat mich jemand an der Schulter berührt: meine alte Lehrerin aus Lyon. Wir hatten uns zehn Jahre nicht gesehen. Danach haben wir zwei Stunden geredet. Das Ende der Schlange habe ich völlig vergessen.",
          "Recently I was standing in a long queue. Beforehand I was in a bad mood. Then someone touched my shoulder: my old teacher from Lyon. We had not seen each other for ten years. After that we talked for two hours. I completely forgot the end of the queue.",
          [
            q("Who appeared?", "An old teacher", ["A dog", "An old teacher", "A conductor", "Leo"]),
            q("How long since they last met?", "Ten years", ["Two hours", "Ten years", "One day", "Never met"]),
            q("What did the writer forget?", "The end of the queue", ["Lyon", "The end of the queue", "German", "The hat"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Tell a short travel mishap in 8 sentences.",
          "Erzähl eine Reise-Panne.",
          "Zuerst war der Bahnhof voll. Dann haben wir den Zug verpasst. Plötzlich hat ein Mitarbeiter einen anderen Weg erklärt. Schließlich sind wir mit dem Bus angekommen. Es war stressig, aber spannend.",
          ["zuerst / dann / plötzlich / schließlich", "Perfekt"],
        ),
        writing(
          "Rewrite three Perfekt sentences in Präteritum (war/hatte/ging).",
          "Schreib drei Sätze im Präteritum.",
          "Es war kalt. Ich hatte keinen Schirm. Wir gingen trotzdem los.",
          ["war, hatte, ging are enough at B1"],
        ),
      ],
    },
  ),
  chapter(
    "work-applications",
    "Work Life, CVs & Applications",
    "Arbeitsleben, Lebenslauf und Bewerbung",
    "Read job ads closely, then write a structured application paragraph.",
    "writing",
    [
      "Lebenslauf: reverse chronological, facts not poetry.",
      "Anschreiben: Bezug zur Stelle, zwei Stärken mit Beispiel, höflicher Schluss.",
      "Konjunktiv II for polite requests: Könnten Sie …? Ich würde gern …",
    ],
    {
      vocab: [
        vocab("die Bewerbung", "the application"),
        vocab("das Anschreiben", "the cover letter", undefined, "Anschreiben"),
        vocab("der Lebenslauf", "the CV"),
        vocab("die Stelle", "the position"),
        vocab("die Anzeige", "the advert", undefined, "Anzeigen"),
        vocab("die Anforderung", "the requirement", undefined, "Anforderungen"),
        vocab("die Stärke", "the strength", undefined, "Stärken"),
        vocab("die Schwäche", "the weakness", undefined, "Schwächen"),
        vocab("die Erfahrung", "experience"),
        vocab("das Praktikum", "the internship", undefined, "Praktika"),
        vocab("die Referenz", "the reference", undefined, "Referenzen"),
        vocab("verfügbar", "available"),
        vocab("flexibel", "flexible"),
        vocab("zuverlässig", "reliable"),
        vocab("teamfähig", "a team player"),
        vocab("selbstständig", "independent"),
        vocab("belastbar", "resilient"),
        vocab("die Frist", "the deadline", undefined, "Fristen"),
        vocab("die Unterlagen", "the documents"),
        vocab("beilegen", "to enclose"),
        vocab("sich bewerben", "to apply"),
        vocab("einladen", "to invite"),
        vocab("absagen", "to decline / reject"),
        vocab("zusagen", "to accept"),
        vocab("das Gehalt", "the salary"),
        vocab("die Probezeit", "the probation period"),
        vocab("kündigen", "to resign / terminate"),
        vocab("übernehmen", "to take on"),
        vocab("verantwortlich", "responsible"),
        vocab("der Bereich", "the area / department", undefined, "Bereiche"),
        vocab("die Aufgabe", "the task"),
        vocab("erfolgreich", "successful"),
      ],
      phrases: [
        phrase("hiermit bewerbe ich mich um die Stelle als …", "I hereby apply for the position as …"),
        phrase("In der Anzeige suchen Sie jemand Zuverlässiges.", "In the advert you are looking for someone reliable."),
        phrase("Während meines Praktikums habe ich … übernommen.", "During my internship I took on …"),
        phrase("Zu meinen Stärken gehören Organisation und Ruhe.", "My strengths include organisation and calm."),
        phrase("Ich bin ab dem 1. März verfügbar.", "I am available from 1 March."),
        phrase("Im Anhang finden Sie Lebenslauf und Zeugnisse.", "Attached you will find CV and certificates."),
        phrase("Über eine Einladung zum Gespräch würde ich mich freuen.", "I would be pleased to be invited to an interview."),
        phrase("Könnten Sie mir die Probezeit nennen?", "Could you tell me the probation period?"),
        phrase("Leider muss ich absagen, weil ich schon zugesagt habe.", "Unfortunately I must decline because I have already accepted another offer."),
        phrase("Die Frist endet am Freitag.", "The deadline ends on Friday."),
        phrase("Ich arbeite gern im Team, aber auch selbstständig.", "I like working in a team, but also independently."),
        phrase("Verantwortlich war ich für den Empfang.", "I was responsible for reception."),
      ],
      sentences: [
        sentence("Die Anforderungen sind klar: Deutsch B1 und Schichtbereitschaft.", "The requirements are clear: German B1 and willingness to work shifts."),
        sentence("Ich lege Referenzen nur auf Wunsch bei.", "I only enclose references on request."),
        sentence("Flexible Arbeitszeiten sind für mich wichtig.", "Flexible hours are important to me."),
        sentence("In der Probezeit lernt man das Team kennen.", "During probation you get to know the team."),
        sentence("Sie hat erfolgreich Projekte im Bereich Logistik geleitet.", "She has successfully led projects in logistics."),
        sentence("Eine Schwäche offen zu nennen wirkt ehrlich, wenn ein Plan folgt.", "Naming a weakness openly seems honest if a plan follows."),
        sentence("Das Gehalt steht nicht in jeder Anzeige.", "The salary is not in every advert."),
        sentence("Bitte die Unterlagen als PDF senden.", "Please send the documents as PDF."),
        sentence("Er bewirbt sich nicht zum ersten Mal.", "He is not applying for the first time."),
        sentence("Wir laden drei Personen zum Gespräch ein.", "We invite three people to interview."),
        sentence("Die Aufgabe klingt stressig, aber lernreich.", "The task sounds stressful but educational."),
        sentence("Ich würde die Frühschicht übernehmen.", "I would take on the early shift."),
        sentence("Belastbar heißt nicht, alles ohne Pause zu machen.", "Resilient does not mean doing everything without a break."),
        sentence("Nach der Absage habe ich um Feedback gebeten.", "After the rejection I asked for feedback."),
        sentence("Teamfähig zu sein bedeutet zuzuhören.", "Being a team player means listening."),
        sentence("Die Stelle ist unbefristet nach der Probezeit.", "The position is permanent after probation."),
        sentence("Ich habe die Anzeige auf der Firmenwebseite gefunden.", "I found the advert on the company website."),
        sentence("Pünktlichkeit erwähne ich nicht als einzige Stärke.", "I do not mention punctuality as my only strength."),
      ],
      readings: [
        reading(
          "Job ad (B1)",
          "Stellenanzeige",
          "Empfangskraft (m/w/d), Hotel am Fluss. Anforderungen: freundliches Deutsch, Schicht, Zuverlässigkeit. Erfahrung im Empfang von Vorteil. Wir bieten Probezeit von drei Monaten und Fortbildung. Bewerbung bis 30.09. mit Lebenslauf an jobs@fluss.hotel. Gehalt nach Gespräch.",
          "Receptionist (all genders), hotel by the river. Requirements: friendly German, shifts, reliability. Reception experience an advantage. We offer three months’ probation and training. Apply by 30 Sept with CV to jobs@fluss.hotel. Salary to be discussed.",
          [
            q("Is experience required?", "It is an advantage, not required", ["Absolutely required", "It is an advantage, not required", "Forbidden", "Only in English"]),
            q("How long is probation?", "Three months", ["Three days", "Three months", "Three years", "None"]),
            q("When is the deadline?", "30 September", ["Immediately yesterday", "30 September", "January", "No date"]),
          ],
        ),
        reading(
          "Cover letter excerpt",
          "Anschreiben-Auszug",
          "sehr geehrte Frau Holm, hiermit bewerbe ich mich um die Stelle am Empfang. In meinem Praktikum im Stadt-Hotel habe ich Check-in und Reklamationen übernommen. Ich arbeite zuverlässig in Schichten. Im Anhang der Lebenslauf. Über ein Gespräch würde ich mich freuen.",
          "Dear Ms Holm, I hereby apply for the reception post. In my internship at Stadt-Hotel I took on check-in and complaints. I work reliably in shifts. CV attached. I would be pleased to be invited to an interview.",
          [
            q("Where did the intern work?", "Stadt-Hotel", ["Fluss-Hotel already", "Stadt-Hotel", "An airport kitchen", "A school"]),
            q("Which tasks are named?", "Check-in and complaints", ["Cooking only", "Check-in and complaints", "Driving buses", "IT security"]),
            q("What is attached?", "The CV", ["A novel", "The CV", "A gift", "Nothing"]),
          ],
        ),
        reading(
          "Interview reminder",
          "Erinnerung zum Gespräch",
          "Ihr Termin: Dienstag, 10:15, Eingang B. Bitte Ausweis und Zeugnisse mitbringen. Das Gespräch dauert ca. 30 Minuten. Fragen zum Gehalt sind am Ende möglich. Falls Sie absagen müssen, schreiben Sie bis Montag. Wir freuen uns auf Sie.",
          "Your appointment: Tuesday, 10:15, entrance B. Please bring ID and certificates. The interview lasts about 30 minutes. Questions about salary are possible at the end. If you have to cancel, write by Monday. We look forward to seeing you.",
          [
            q("Which entrance?", "B", ["A", "B", "C", "The kitchen"]),
            q("When may salary be discussed?", "At the end", ["Never", "At the end", "Before arriving", "By postcard"]),
            q("Cancel by when?", "Monday", ["After the interview", "Monday", "In a year", "Never contact them"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 8–10 line cover-letter body (not the address).",
          "Schreib den Kern eines Anschreibens.",
          "Hiermit bewerbe ich mich um die Stelle am Empfang. In meinem Praktikum habe ich Check-in übernommen. Ich bin zuverlässig und schichtbereit. Im Anhang finden Sie meinen Lebenslauf. Über eine Einladung würde ich mich freuen.",
          ["Name the job", "One example", "Availability or attachment", "Polite close"],
        ),
        writing(
          "List a mini CV in five dated lines.",
          "Schreib fünf Lebenslaufzeilen.",
          "2024–heute: Deutschkurs B1. 2023: Praktikum Empfang. 2022: Abitur. Sprachen: Englisch C1, Deutsch B1. IT: Word, Excel.",
          ["Newest first"],
        ),
      ],
    },
  ),
  chapter(
    "news-reading",
    "Reading News & Longer Reports",
    "Nachrichten und längere Berichte lesen",
    "Scan articles for who, what, where, why — then judge the tone.",
    "reading",
    [
      "First paragraph often answers wer, was, wo, wann. Later paragraphs add warum and wie.",
      "Passive and nominal style: Die Eröffnung findet statt. Es wird erwartet, dass …",
      "Distinguish report (facts) from comment (opinion).",
    ],
    {
      vocab: [
        vocab("der Bericht", "the report", undefined, "Berichte"),
        vocab("die Meldung", "the news item", undefined, "Meldungen"),
        vocab("die Zeitung", "the newspaper"),
        vocab("der Kommentar", "the comment / editorial", undefined, "Kommentare"),
        vocab("die Tatsache", "the fact", undefined, "Tatsachen"),
        vocab("die Meinung", "the opinion"),
        vocab("der Reporter", "the reporter", undefined, "Reporter"),
        vocab("die Agentur", "the agency", undefined, "Agenturen"),
        vocab("aktuell", "current"),
        vocab("geschehen", "to happen"),
        vocab("stattfinden", "to take place"),
        vocab("eröffnen", "to open"),
        vocab("schließen", "to close"),
        vocab("erhöhen", "to raise"),
        vocab("senken", "to lower"),
        vocab("die Zahl", "the number / figure"),
        vocab("prozent", "percent"),
        vocab("die Ursache", "the cause", undefined, "Ursachen"),
        vocab("die Folge", "the consequence", undefined, "Folgen"),
        vocab("betroffen", "affected"),
        vocab("offiziell", "official"),
        vocab("inoffiziell", "unofficial"),
        vocab("bestätigen", "to confirm"),
        vocab("dementieren", "to deny"),
        vocab("zitieren", "to quote"),
        vocab("die Überschrift", "the headline"),
        vocab("der Absatz", "the paragraph", undefined, "Absätze"),
        vocab("sachlich", "factual"),
        vocab("reißerisch", "sensational"),
        vocab("die Quelle", "the source"),
        vocab("unabhängig", "independent"),
        vocab("lokal", "local"),
      ],
      phrases: [
        phrase("Laut Polizei gab es keine Verletzten.", "According to police there were no injured people."),
        phrase("Die Stadt bestätigt die Zahlen nicht.", "The city is not confirming the figures."),
        phrase("Es wird erwartet, dass die Brücke im Mai öffnet.", "The bridge is expected to open in May."),
        phrase("Betroffen sind vor allem Anwohner.", "Residents in particular are affected."),
        phrase("Im zweiten Absatz steht die Ursache.", "The cause is in the second paragraph."),
        phrase("Die Überschrift ist reißerischer als der Text.", "The headline is more sensational than the text."),
        phrase("Ein Kommentar ist keine Nachricht.", "An editorial is not a news report."),
        phrase("Unabhängige Quellen fehlen noch.", "Independent sources are still missing."),
        phrase("Die Eröffnung findet am Samstag statt.", "The opening takes place on Saturday."),
        phrase("Offizielle Angaben liegen noch nicht vor.", "Official information is not yet available."),
        phrase("Die Meldung kam über eine Agentur.", "The item came via an agency."),
        phrase("Bitte den ganzen Artikel lesen, nicht nur die Zahl.", "Please read the whole article, not just the figure."),
      ],
      sentences: [
        sentence("Gestern Abend ist in der Altstadt ein Stromausfall geschehen.", "Yesterday evening a power cut happened in the old town."),
        sentence("Die Bahn erhöht die Preise um drei Prozent.", "The railway is raising prices by three percent."),
        sentence("Als Folge bleiben einige Läden montags zu.", "As a consequence some shops stay closed on Mondays."),
        sentence("Der Reporter zitiert eine Anwohnerin.", "The reporter quotes a resident."),
        sentence("Die Firma dementiert Gerüchte über Schließung.", "The company denies rumours of closure."),
        sentence("Lokalnachrichten erklären den Alltag besser als große Politik.", "Local news explains everyday life better than high politics."),
        sentence("Sachlich schreiben heißt, Adjektive zu sparen.", "Writing factually means sparing adjectives."),
        sentence("Die Ursache des Staus war eine Baustelle, nicht ein Unfall.", "The cause of the jam was roadworks, not an accident."),
        sentence("Inoffizielle Zahlen sind höher.", "Unofficial figures are higher."),
        sentence("Wer betroffen ist, soll sich beim Amt melden.", "Anyone affected should contact the office."),
        sentence("Der Kommentar kritisiert die Entscheidung scharf.", "The editorial criticises the decision sharply."),
        sentence("Eine Agenturmeldung ist oft sehr kurz.", "An agency item is often very short."),
        sentence("Die Brücke wird nächstes Jahr geschlossen.", "The bridge will be closed next year."),
        sentence("Aktuelle Zahlen stehen in einer Tabelle.", "Current figures are in a table."),
        sentence("Ohne Quelle glaube ich die Meldung nicht.", "Without a source I do not believe the item."),
        sentence("Der erste Absatz beantwortet wann und wo.", "The first paragraph answers when and where."),
        sentence("Unabhängige Kontrolle fehlt in dem Text.", "Independent scrutiny is missing in the text."),
        sentence("Die Folge für Pendler ist mehr Zeit im Bus.", "The consequence for commuters is more time on the bus."),
      ],
      readings: [
        reading(
          "Local news item",
          "Lokale Meldung",
          "Am Donnerstagabend ist in der Nordstadt der Strom für 40 Minuten ausgefallen. Betroffen waren etwa 2.000 Haushalte. Laut Stadtwerken war ein defekter Transformator die Ursache. Verletzte gab es nicht. Die Versorgung läuft wieder, eine Untersuchung läuft. Offizielle Entschädigung ist nicht geplant.",
          "On Thursday evening the power in Nordstadt was out for 40 minutes. About 2,000 households were affected. According to the utility a faulty transformer was the cause. There were no injuries. Supply is running again; an investigation is underway. Official compensation is not planned.",
          [
            q("How long was the outage?", "40 minutes", ["40 hours", "40 minutes", "A week", "Unknown"]),
            q("How many households?", "About 2,000", ["40", "About 2,000", "The whole country", "None"]),
            q("Is compensation planned?", "No", ["Yes, immediately", "No", "Only for shops", "Unclear in text"]),
          ],
        ),
        reading(
          "Headline vs text",
          "Überschrift gegen Text",
          "Überschrift: „Chaos auf der A3!“ Text: Zwischen 7 und 8 Uhr standen Autos wegen einer Baustelle. Der Stau war vier Kilometer lang. Um 8:20 war die Spur wieder frei. Niemand wurde verletzt. Reißerisch ist die Überschrift, sachlich der dritte Satz.",
          "Headline: “Chaos on the A3!” Text: Between 7 and 8 a.m. cars stood still because of roadworks. The jam was four kilometres long. At 8:20 the lane was clear again. Nobody was injured. The headline is sensational; the third sentence is factual.",
          [
            q("What caused the jam?", "Roadworks", ["An explosion", "Roadworks", "Snow in August", "A festival"]),
            q("When was the lane clear?", "8:20", ["Midnight", "8:20", "Thursday next year", "Never"]),
            q("How does the writer judge the headline?", "Sensational", ["Perfectly factual", "Sensational", "Too short", "In Latin"]),
          ],
        ),
        reading(
          "Short comment",
          "Kurzer Kommentar",
          "Die Stadt senkt die Bibliotheksgebühren. Das klingt klein, ist aber eine Tatsache mit Folgen: Mehr Jugendliche können drinnen lernen, wenn es draußen kalt ist. Wer das nur als Wahlkampf sieht, ignoriert die Zahlen der letzten Winter. Ein Bericht sollte beides trennen: die Gebühr und die Spekulation.",
          "The city is lowering library fees. That sounds small, but it is a fact with consequences: more young people can study indoors when it is cold outside. Anyone who sees this only as electioneering ignores last winter’s figures. A report should separate the two: the fee and the speculation.",
          [
            q("What is the city doing?", "Lowering library fees", ["Closing libraries", "Lowering library fees", "Banning youth", "Raising bus fares only"]),
            q("What consequence is named?", "More young people can study indoors", ["More chaos on the A3", "More young people can study indoors", "No winter", "Higher fees"]),
            q("What should a report separate?", "The fee and speculation", ["Facts and tables only", "The fee and speculation", "Headlines and photos", "Nothing"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 5-sentence factual local report.",
          "Schreib eine sachliche Meldung.",
          "Am Montag hat die Stadt eine neue Bushaltestelle eröffnet. Sie liegt am Markt. Etwa 200 Menschen waren da. Laut Bürgermeisterin soll die Linie pünktlicher werden. Verletzte oder Proteste gab es nicht.",
          ["wer was wo wann", "laut + source", "No drama adjectives"],
        ),
        writing(
          "Turn a sensational headline into a calm one.",
          "Mach aus einer reißerischen Überschrift eine sachliche.",
          "Statt „Chaos!“ besser: „Stau auf der A3 wegen Baustelle, 7–8 Uhr“.",
          ["Include cause and time"],
        ),
      ],
    },
  ),
  chapter(
    "formal-writing",
    "Formal Letters & Complaints",
    "Formelle Briefe und Reklamationen",
    "Read official letters, then write a complaint that stays firm and polite.",
    "writing",
    [
      "Structure: Absender, Datum, Empfänger, Betreff, Anrede, Anlass, Fakten, Forderung, Frist, Gruß.",
      "Konjunktiv II: Ich möchte Sie bitten … Könnten Sie … Ich wäre dankbar, wenn …",
      "Avoid slang. State dates, amounts, and reference numbers.",
    ],
    {
      vocab: [
        vocab("die Reklamation", "the complaint", undefined, "Reklamationen"),
        vocab("die Beschwerde", "the complaint", undefined, "Beschwerden"),
        vocab("der Absender", "the sender"),
        vocab("der Empfänger", "the recipient"),
        vocab("der Betreff", "the subject"),
        vocab("die Anrede", "the salutation"),
        vocab("die Forderung", "the demand / claim", undefined, "Forderungen"),
        vocab("die Frist", "the deadline"),
        vocab("die Rechnung", "the invoice / bill"),
        vocab("der Betrag", "the amount", undefined, "Beträge"),
        vocab("die Nummer", "the number"),
        vocab("fehlerhaft", "faulty"),
        vocab("beschädigt", "damaged"),
        vocab("verspätet", "delayed"),
        vocab("ersetzen", "to replace"),
        vocab("erstatten", "to refund"),
        vocab("stornieren", "to cancel"),
        vocab("mahnen", "to send a reminder"),
        vocab("die Mahnung", "the reminder / dunning letter"),
        vocab("höflich", "polite"),
        vocab("bestimmt", "firm"),
        vocab("sachlich", "factual"),
        vocab("belegen", "to document / prove"),
        vocab("der Nachweis", "the proof", undefined, "Nachweise"),
        vocab("das Foto", "the photo"),
        vocab("die Kopie", "the copy", undefined, "Kopien"),
        vocab("im Voraus", "in advance"),
        vocab("hochachtungsvoll", "respectfully (very formal)"),
        vocab("Mit freundlichen Grüßen", "yours sincerely"),
        vocab("die Lösung", "the solution"),
        vocab("unzufrieden", "dissatisfied"),
        vocab("akzeptieren", "to accept"),
      ],
      phrases: [
        phrase("hiermit reklamiere ich die Lieferung vom 12.03.", "I hereby complain about the delivery of 12 March."),
        phrase("Der Artikel ist beschädigt angekommen.", "The item arrived damaged."),
        phrase("Ich bitte um Ersatz oder Erstattung des Betrags.", "I request a replacement or a refund of the amount."),
        phrase("Als Nachweis lege ich Fotos bei.", "I enclose photos as proof."),
        phrase("Bitte teilen Sie mir bis zum 5. April mit, wie Sie vorgehen.", "Please let me know by 5 April how you will proceed."),
        phrase("Ich wäre dankbar für eine schnelle Lösung.", "I would be grateful for a quick solution."),
        phrase("Leider muss ich die Rechnung zurückweisen.", "Unfortunately I must reject the invoice."),
        phrase("Eine Mahnung ist in diesem Fall nicht berechtigt.", "A reminder is not justified in this case."),
        phrase("Könnten Sie den Fehler prüfen?", "Could you check the error?"),
        phrase("Ich akzeptiere die Verspätung nicht ohne Ausgleich.", "I do not accept the delay without compensation."),
        phrase("Im Voraus vielen Dank.", "Thank you in advance."),
        phrase("Mit freundlichen Grüßen", "Yours sincerely"),
      ],
      sentences: [
        sentence("Der Betreff nennt Datum und Bestellnummer.", "The subject line names the date and order number."),
        sentence("Ohne Nachweis glaubt die Firma oft nicht.", "Without proof the company often does not believe you."),
        sentence("Eine Kopie der Rechnung liegt bei.", "A copy of the invoice is enclosed."),
        sentence("Die Lieferung war drei Tage verspätet.", "The delivery was three days late."),
        sentence("Ich fordere die Erstattung von 49 Euro.", "I demand a refund of 49 euros."),
        sentence("Bitte stornieren Sie die zweite Bestellung.", "Please cancel the second order."),
        sentence("Sachlich bleiben spart Zeit.", "Staying factual saves time."),
        sentence("Bestimmt, aber nicht unhöflich — das ist der Ton.", "Firm but not impolite — that is the tone."),
        sentence("Die Frist sollte realistisch sein, zum Beispiel zehn Tage.", "The deadline should be realistic, for example ten days."),
        sentence("Hochachtungsvoll wirkt heute oft steif.", "Hochachtungsvoll often seems stiff today."),
        sentence("Unzufriedenheit allein ist kein Argument; Fakten sind es.", "Dissatisfaction alone is not an argument; facts are."),
        sentence("Ersetzen Sie bitte das fehlerhafte Gerät.", "Please replace the faulty device."),
        sentence("Die Mahnung kam, obwohl ich schon gezahlt hatte.", "The reminder came although I had already paid."),
        sentence("Ich lege den Chatverlauf als Nachweis bei.", "I enclose the chat history as proof."),
        sentence("Eine Lösung könnte ein Gutschein plus Ersatz sein.", "A solution could be a voucher plus replacement."),
        sentence("Der Empfänger steht links, nicht in der Anrede allein.", "The recipient is on the left, not only in the salutation."),
        sentence("Wir akzeptieren keine versteckten Gebühren.", "We do not accept hidden fees."),
        sentence("Schreiben Sie klar, was Sie wollen.", "Write clearly what you want."),
      ],
      readings: [
        reading(
          "Model complaint",
          "Musterreklamation",
          "Betreff: Reklamation Bestellung 4412, 03.08.2026. Sehr geehrte Damen und Herren, der Wasserkocher ist beschädigt angekommen. Foto im Anhang. Ich bitte um Ersatz oder Erstattung von 39,90 € bis zum 20.08. Eine Mahnung wäre nicht korrekt, da ich bereits gezahlt habe. Mit freundlichen Grüßen, A. Nguyen.",
          "Subject: Complaint order 4412, 3 Aug 2026. Dear Sir or Madam, the kettle arrived damaged. Photo attached. I request replacement or a refund of €39.90 by 20 Aug. A reminder would not be correct as I have already paid. Yours sincerely, A. Nguyen.",
          [
            q("What is wrong?", "The kettle is damaged", ["Wrong colour only", "The kettle is damaged", "No order", "Late email"]),
            q("How much is claimed?", "€39.90", ["€4412", "€39.90", "Nothing", "€20.08"]),
            q("Why would a reminder be wrong?", "The customer has already paid", ["No photo", "The customer has already paid", "It's a gift", "Sunday"]),
          ],
        ),
        reading(
          "Company reply",
          "Firmenantwort",
          "Vielen Dank für Ihre Nachricht. Wir ersetzen das Gerät und holen das alte nächste Woche ab. Eine Erstattung ist dann nicht nötig. Bitte halten Sie die Originalverpackung bereit. Sollten Sie unzufrieden bleiben, schreiben Sie uns erneut. Mit freundlichen Grüßen, Kundenservice.",
          "Thank you for your message. We will replace the device and collect the old one next week. A refund will then not be necessary. Please have the original packaging ready. If you remain dissatisfied, write to us again. Kind regards, customer service.",
          [
            q("What will the company do?", "Replace the device", ["Refund only", "Replace the device", "Ignore the mail", "Send a bill"]),
            q("When is collection?", "Next week", ["Today", "Next week", "Never", "In a year"]),
            q("What should the customer keep ready?", "Original packaging", ["A lawyer", "Original packaging", "A new kettle", "Cash"]),
          ],
        ),
        reading(
          "Official dunning letter",
          "Mahnung",
          "Trotz Rechnung vom 01.07. fehlt der Betrag von 120 €. Bitte überweisen Sie innerhalb von 14 Tagen. Bei Fragen nennen Sie die Kundennummer 8801. Sollten Sie bereits gezahlt haben, betrachten Sie dieses Schreiben als gegenstandslos. Mit freundlichen Grüßen, Buchhaltung.",
          "Despite the invoice of 1 July the amount of €120 is missing. Please transfer within 14 days. If you have questions, quote customer number 8801. If you have already paid, regard this letter as void. Yours sincerely, accounts.",
          [
            q("How much is claimed?", "€120", ["€14", "€120", "€8801", "€1.07"]),
            q("What number should you quote?", "8801", ["120", "8801", "14", "01.07"]),
            q("What if you already paid?", "Ignore the letter as void", ["Pay twice", "Ignore the letter as void", "Call the police", "Wait a year"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a full short complaint (address omitted).",
          "Schreib eine kurze Reklamation.",
          "Betreff: Reklamation Bestellung 12. Sehr geehrte Damen und Herren, die Lampe ist beschädigt. Foto im Anhang. Ich bitte um Ersatz bis zum 30. des Monats. Mit freundlichen Grüßen.",
          ["Betreff, facts, demand, deadline, greeting"],
        ),
        writing(
          "Write a polite follow-up after no reply.",
          "Schreib eine höfliche Nachfrage.",
          "Sehr geehrte Damen und Herren, am 12. habe ich reklamiert und bisher keine Antwort erhalten. Könnten Sie den Status mitteilen? Vielen Dank im Voraus.",
          ["Reference the first mail", "Konjunktiv II request"],
        ),
      ],
    },
  ),
  chapter(
    "conversation-register",
    "Conversation, Register & Everyday Diplomacy",
    "Gespräch, Register und Alltagsdiplomatie",
    "Hear the difference between du and Sie in context, then choose the right tone.",
    "mixed",
    [
      "Register: slang with friends, clear standard at work, formal in letters.",
      "Softening: irgendwie, ein bisschen, vielleicht, ich würde sagen.",
      "Repair: Entschuldigung, ich meinte … Kannst du das nochmal sagen?",
    ],
    {
      vocab: [
        vocab("das Register", "the register (language)"),
        vocab("die Umgangssprache", "colloquial language"),
        vocab("die Standardsprache", "standard language"),
        vocab("formell", "formal"),
        vocab("informell", "informal"),
        vocab("duzen", "to use du"),
        vocab("siezen", "to use Sie"),
        vocab("das Smalltalk", "small talk"),
        vocab("das Missverständnis", "the misunderstanding", undefined, "Missverständnisse"),
        vocab("klären", "to clarify"),
        vocab("unterbrechen", "to interrupt"),
        vocab("ausreden lassen", "to let someone finish"),
        vocab("höflich", "polite"),
        vocab("grob", "rude"),
        vocab("direkt", "direct"),
        vocab("weich", "soft / mild"),
        vocab("der Ton", "the tone"),
        vocab("die Ironie", "irony"),
        vocab("ernst", "serious"),
        vocab("scherzen", "to joke"),
        vocab("das Kompliment", "the compliment", undefined, "Komplimente"),
        vocab("kritisieren", "to criticise"),
        vocab("loben", "to praise"),
        vocab("die Pause", "the pause"),
        vocab("nachfragen", "to ask a follow-up"),
        vocab("zusammenfassen", "to summarise"),
        vocab("einverstanden", "agreed"),
        vocab("unsicher", "unsure"),
        vocab("das Gespräch", "the conversation"),
        vocab("der Smalltalk", "small talk"),
        vocab("die Beziehung", "the relationship", undefined, "Beziehungen"),
        vocab("angemessen", "appropriate"),
      ],
      phrases: [
        phrase("Haben Sie einen Moment?", "Do you have a moment? (formal)"),
        phrase("Hast du kurz Zeit?", "Have you got a sec? (informal)"),
        phrase("Wenn ich kurz einhaken darf …", "If I may just jump in …"),
        phrase("Lass uns das nochmal klären.", "Let's clarify that again."),
        phrase("So habe ich das nicht gemeint.", "I didn't mean it that way."),
        phrase("Könnten Sie das bitte wiederholen?", "Could you please repeat that?"),
        phrase("Ich würde sagen, wir warten noch.", "I would say we wait a bit more."),
        phrase("Darf ich dich duzen?", "May I use du with you?"),
        phrase("Ein Kompliment zur Präsentation: klar und kurz.", "A compliment on the presentation: clear and short."),
        phrase("Das war ein Scherz, sorry.", "That was a joke, sorry."),
        phrase("Bist du einverstanden, wenn wir das so machen?", "Are you okay if we do it this way?"),
        phrase("Kurz zusammengefasst: wir treffen uns um vier.", "To summarise: we meet at four."),
      ],
      sentences: [
        sentence("Im Amt siezt man, im Sportverein oft nicht.", "At the office one uses Sie; at the sports club often not."),
        sentence("Umgangssprache spart Wörter, aber nicht immer Respekt.", "Colloquial language saves words, but not always respect."),
        sentence("Ein grober Ton macht das Problem größer.", "A rude tone makes the problem bigger."),
        sentence("Ironie versteht nicht jeder, besonders am Telefon.", "Not everyone understands irony, especially on the phone."),
        sentence("Nachfragen ist besser als raten.", "Asking a follow-up is better than guessing."),
        sentence("Unterbrich nicht, wenn jemand unsicher spricht.", "Do not interrupt when someone is speaking uncertainly."),
        sentence("Ein weicher Satz kann dieselbe Kritik tragen.", "A softer sentence can carry the same criticism."),
        sentence("Smalltalk über Wetter ist nicht dumm, sondern sozial.", "Small talk about weather is not stupid but social."),
        sentence("Die Beziehung entscheidet über du oder Sie.", "The relationship decides du or Sie."),
        sentence("Angemessen heißt: zur Situation passend.", "Appropriate means matching the situation."),
        sentence("Er hat ernst gesprochen, sie hat gescherzt.", "He spoke seriously, she was joking."),
        sentence("Loben Sie konkret, nicht nur „super“.", "Praise specifically, not just “great”."),
        sentence("Eine Pause im Gespräch gibt dem anderen Raum.", "A pause in conversation gives the other person space."),
        sentence("Wir klären das Missverständnis morgen in Ruhe.", "We will clarify the misunderstanding tomorrow calmly."),
        sentence("Standardsprache hilft in Prüfungen und E-Mails.", "Standard language helps in exams and emails."),
        sentence("Direkt und höflich schließen sich nicht aus.", "Direct and polite are not mutually exclusive."),
        sentence("Ich bin unsicher, ob der Scherz okay war.", "I am unsure whether the joke was okay."),
        sentence("Fassen Sie am Ende die nächsten Schritte zusammen.", "At the end, summarise the next steps."),
      ],
      readings: [
        reading(
          "Two versions of the same request",
          "Zwei Versionen",
          "Informell: Hey, hast du das File? Brauch’s bis vier. Formell: Guten Tag Frau Berg, hätten Sie das Dokument bis 16 Uhr? Danke und viele Grüße. Beide bitten um dasselbe. Der Ton ändert die Beziehung, nicht den Inhalt.",
          "Informal: Hey, have you got the file? Need it by four. Formal: Good day Ms Berg, would you have the document by 4 p.m.? Thanks and best wishes. Both ask for the same thing. Tone changes the relationship, not the content.",
          [
            q("Is the content different?", "No", ["Yes, completely", "No", "Only the time", "One is a joke"]),
            q("What does tone change?", "The relationship", ["The file format", "The relationship", "The clock", "German grammar rules"]),
            q("Formal time mentioned?", "16:00", ["04:00", "16:00", "Midnight", "None"]),
          ],
        ),
        reading(
          "A repair after a joke",
          "Reparatur nach einem Scherz",
          "Im Meeting hat Jan gesagt: „Wie immer zu spät.“ Es war als Scherz gemeint. Leila hat ernst geguckt. Jan hat später geschrieben: So habe ich das nicht gemeint. Nächstes Mal lobe ich pünktliche Leute und scherze nicht über Unpünktlichkeit. Leila hat geantwortet: Okay, geklärt.",
          "In the meeting Jan said: “Late as always.” It was meant as a joke. Leila looked serious. Jan later wrote: I didn’t mean it that way. Next time I will praise punctual people and not joke about lateness. Leila replied: Okay, clarified.",
          [
            q("How was the joke received?", "Badly / seriously", ["With loud laughter only", "Badly / seriously", "Ignored", "As a compliment"]),
            q("What will Jan do next time?", "Praise punctuality instead", ["Joke more", "Praise punctuality instead", "Quit", "Use only Sie"]),
            q("Is it resolved?", "Yes", ["No, they fight", "Yes", "Unknown", "The boss decided"]),
          ],
        ),
        reading(
          "Office guideline",
          "Bürohinweis",
          "Kundinnen siezen, bis sie das Du anbieten. Kollegen im Team duzen sich, die Geschäftsführung nicht automatisch. Kritik zuerst unter vier Augen. Komplimente gern öffentlich, wenn sie konkret sind. Smalltalk vor Meetings ist erwünscht, Ironie in E-Mails nicht.",
          "Address customers with Sie until they offer du. Colleagues in the team use du; management is not automatic. Criticism first in private. Compliments welcome in public if they are specific. Small talk before meetings is welcome; irony in emails is not.",
          [
            q("When do you du customers?", "When they offer it", ["Always day one", "When they offer it", "Never", "Only on Friday"]),
            q("Where should criticism happen first?", "In private", ["On the intranet", "In private", "In a newspaper", "Never"]),
            q("Irony in emails?", "No", ["Yes, always", "No", "Required", "Only in Latin"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Rewrite an informal request as a formal email body.",
          "Mach aus einer informellen Bitte eine formelle.",
          "Guten Tag Frau Berg, könnten Sie mir das Dokument bitte bis 16 Uhr senden? Vielen Dank und mit freundlichen Grüßen.",
          ["Sie-form", "Könnten Sie", "Clear deadline"],
        ),
        writing(
          "Write a 4-line repair message after a misunderstanding.",
          "Schreib eine Reparatur-Nachricht.",
          "Hallo, so habe ich das nicht gemeint. Entschuldigung, wenn der Ton hart war. Lass uns das morgen klären. Danke.",
          ["Acknowledge + apology + next step"],
        ),
      ],
    },
  ),
];
