import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const b1ChaptersPart1: ChapterSource[] = [
  chapter(
    "opinions",
    "Opinions, Reasons & Agreement",
    "Meinungen, Gründe und Zustimmung",
    "Read forum threads, then argue with weil, deshalb, and ich finde, dass.",
    "mixed",
    [
      "ich finde, dass / ich glaube, dass — verb to the end in the dass-clause.",
      "weil gives a reason (verb last). deshalb / darum start a new sentence.",
      "Softening: irgendwie, eigentlich, nicht wirklich. Agreement: das stimmt, genau, na ja.",
    ],
    {
      vocab: [
        vocab("die Meinung", "the opinion", undefined, "Meinungen"),
        vocab("der Grund", "the reason", undefined, "Gründe"),
        vocab("das Argument", "the argument", undefined, "Argumente"),
        vocab("zustimmen", "to agree"),
        vocab("widersprechen", "to disagree / contradict"),
        vocab("überzeugen", "to convince"),
        vocab("behaupten", "to claim"),
        vocab("vermuten", "to assume"),
        vocab("bezweifeln", "to doubt"),
        vocab("fair", "fair"),
        vocab("unfair", "unfair"),
        vocab("sinnvoll", "sensible"),
        vocab("unsinnig", "nonsensical"),
        vocab("wichtig", "important"),
        vocab("egal", "all the same / whatever"),
        vocab("eigentlich", "actually"),
        vocab("irgendwie", "somehow"),
        vocab("definitiv", "definitely"),
        vocab("vielleicht", "maybe"),
        vocab("meiner Meinung nach", "in my opinion"),
        vocab("im Gegensatz zu", "in contrast to"),
        vocab("einerseits", "on the one hand"),
        vocab("andererseits", "on the other hand"),
        vocab("deshalb", "therefore"),
        vocab("trotzdem", "nevertheless"),
        vocab("obwohl", "although"),
        vocab("die Diskussion", "the discussion", undefined, "Diskussionen"),
        vocab("das Thema", "the topic", undefined, "Themen"),
        vocab("offen", "open-minded / open"),
        vocab("respektvoll", "respectful"),
        vocab("klar", "clear"),
        vocab("unklar", "unclear"),
      ],
      phrases: [
        phrase("Ich finde, dass das unfair ist.", "I think that is unfair."),
        phrase("Meiner Meinung nach sollten wir warten.", "In my opinion we should wait."),
        phrase("Das stimmt nur teilweise.", "That is only partly true."),
        phrase("Da muss ich widersprechen.", "I have to disagree there."),
        phrase("Einerseits ist es praktisch, andererseits teuer.", "On the one hand it is practical, on the other expensive."),
        phrase("Obwohl ich müde bin, will ich mitreden.", "Although I am tired, I want to join in."),
        phrase("Kannst du das genauer erklären?", "Can you explain that more precisely?"),
        phrase("Ich bezweifle, dass das klappt.", "I doubt that will work."),
        phrase("Lass uns beim Thema bleiben.", "Let's stay on topic."),
        phrase("Dein Argument überzeugt mich.", "Your argument convinces me."),
        phrase("Es ist mir nicht egal.", "It is not all the same to me."),
        phrase("Wir sollten respektvoll diskutieren.", "We should discuss respectfully."),
      ],
      sentences: [
        sentence("Ich glaube, dass öffentliche Parks wichtig sind.", "I believe that public parks are important."),
        sentence("Sie behauptet, die Regel sei klar.", "She claims the rule is clear."),
        sentence("Wir stimmen dir zu, weil die Idee sinnvoll ist.", "We agree with you because the idea is sensible."),
        sentence("Er widerspricht, obwohl er keine Beweise hat.", "He disagrees although he has no evidence."),
        sentence("Deshalb bleibe ich bei meiner Meinung.", "That is why I stick to my opinion."),
        sentence("Trotzdem können wir einen Kompromiss finden.", "Nevertheless we can find a compromise."),
        sentence("Das Thema ist irgendwie unklar.", "The topic is somehow unclear."),
        sentence("Eigentlich wollte ich nichts sagen.", "I didn't actually want to say anything."),
        sentence("Im Gegensatz zu dir arbeite ich nachts.", "In contrast to you I work at night."),
        sentence("Definitiv brauchen wir mehr Zeit.", "We definitely need more time."),
        sentence("Vielleicht hast du recht.", "Maybe you are right."),
        sentence("Die Diskussion wird zu laut.", "The discussion is getting too loud."),
        sentence("Ich vermute, dass viele so denken.", "I assume that many people think that way."),
        sentence("Es ist unsinnig, ohne Plan zu starten.", "It is nonsensical to start without a plan."),
        sentence("Bitte sei offen für andere Ideen.", "Please be open to other ideas."),
        sentence("Das Argument ist schwach.", "The argument is weak."),
        sentence("Wir haben gute Gründe.", "We have good reasons."),
        sentence("Klarheit hilft mehr als Lautstärke.", "Clarity helps more than volume."),
      ],
      readings: [
        reading(
          "Forum: late buses",
          "Forum: späte Busse",
          "Viele schreiben, der Bus um 22 Uhr sei unnötig. Ich finde, dass das unfair gegenüber Schichtarbeitern ist. Einerseits sparen die Stadtwerke Geld, andererseits kommen Leute nicht nach Hause. Meiner Meinung nach sollte die Linie bleiben, obwohl sie nicht immer voll ist. Was meint ihr?",
          "Many write that the 10 p.m. bus is unnecessary. I think that is unfair to shift workers. On the one hand the utility saves money, on the other people cannot get home. In my opinion the line should stay, although it is not always full. What do you think?",
          [
            q("Who would suffer without the late bus?", "Shift workers", ["Tourists only", "Shift workers", "The mayor", "Children at school"]),
            q("What is the money argument?", "The utility would save money", ["Buses are free", "The utility would save money", "Drivers earn more", "Nobody pays"]),
            q("Does the writer want to keep the line?", "Yes", ["No", "Yes", "Only on Sundays", "Unclear"]),
          ],
        ),
        reading(
          "Class debate note",
          "Debattennotiz",
          "Thema: Handyverbot in der Schule. Team A behauptet, Konzentration steige. Team B widerspricht, weil Schüler den Fahrplan brauchen. Die Lehrerin sagt, respektvoll bleiben. Ein Kompromiss: Handys in der Tasche, außer in Pausen. Die Klasse stimmt mehrheitlich zu.",
          "Topic: phone ban at school. Team A claims concentration rises. Team B disagrees because students need the timetable. The teacher says stay respectful. A compromise: phones in bags except during breaks. The class mostly agrees.",
          [
            q("What is Team A's claim?", "Concentration rises", ["More money", "Concentration rises", "No teachers", "Free phones"]),
            q("Why does Team B disagree?", "Students need the timetable", ["They hate bags", "Students need the timetable", "No buses", "Homework"]),
            q("What is the compromise?", "Phones in bags except at break", ["Total ban", "Phones in bags except at break", "Phones on desks", "No compromise"]),
          ],
        ),
        reading(
          "A polite disagreement",
          "Höflicher Widerspruch",
          "Liebe Redaktion, Sie schreiben, Homeoffice sei immer besser. Das stimmt nur teilweise. Manche brauchen das Büro, weil sie allein nicht gut arbeiten. Trotzdem sollten Firmen Wahl lassen. Ich bezweifle pauschale Lösungen. Mit freundlichen Grüßen, T. Krüger.",
          "Dear editors, you write that home office is always better. That is only partly true. Some people need the office because they do not work well alone. Still, companies should leave a choice. I doubt one-size-fits-all solutions. Yours sincerely, T. Krüger.",
          [
            q("What does the writer doubt?", "One-size-fits-all solutions", ["Grammar", "One-size-fits-all solutions", "The newspaper itself", "Salaries"]),
            q("Why do some need the office?", "They work poorly alone", ["No wifi at home", "They work poorly alone", "They hate choice", "The law"]),
            q("Tone of the letter?", "Polite but critical", ["Angry insults", "Polite but critical", "A joke only", "An advert"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Give your opinion on late public transport in 6 sentences.",
          "Schreib deine Meinung.",
          "Ich finde, dass späte Busse wichtig sind. Viele arbeiten in Schichten. Deshalb sollte die Linie bleiben. Einerseits kostet das Geld, andererseits ist es fair. Trotzdem kann man den Takt reduzieren. Was meinst du?",
          ["dass-clause", "deshalb or trotzdem", "einerseits/andererseits if you can"],
        ),
        writing(
          "Write three phrases to agree and three to disagree politely.",
          "Schreib Zustimmung und Widerspruch.",
          "Das stimmt. Genau. Guter Punkt. Da muss ich widersprechen. Das stimmt nur teilweise. Ich bezweifle das.",
          ["Keep them short and usable in speech"],
        ),
      ],
    },
  ),
  chapter(
    "education",
    "Education & Learning Paths",
    "Bildung und Lernwege",
    "Read school and course texts, then describe your learning biography.",
    "mixed",
    [
      "School types: Grundschule, Realschule, Gymnasium, Studium, Ausbildung.",
      "um ... zu for purpose: Ich lerne, um den Test zu bestehen.",
      "Comparative: besser als, so ... wie. Superlative: am besten.",
    ],
    {
      vocab: [
        vocab("die Bildung", "education"),
        vocab("die Schule", "the school", undefined, "Schulen"),
        vocab("das Studium", "university studies"),
        vocab("die Ausbildung", "vocational training", undefined, "Ausbildungen"),
        vocab("der Abschluss", "the qualification", undefined, "Abschlüsse"),
        vocab("die Prüfung", "the exam", undefined, "Prüfungen"),
        vocab("bestehen", "to pass"),
        vocab("durchfallen", "to fail"),
        vocab("der Lehrer", "the teacher (m)", undefined, "Lehrer"),
        vocab("die Lehrerin", "the teacher (f)", undefined, "Lehrerinnen"),
        vocab("der Kurs", "the course", undefined, "Kurse"),
        vocab("die Note", "the grade", undefined, "Noten"),
        vocab("die Hausaufgabe", "the homework", undefined, "Hausaufgaben"),
        vocab("das Zeugnis", "the report / certificate", undefined, "Zeugnisse"),
        vocab("die Universität", "the university", undefined, "Universitäten"),
        vocab("die Berufsschule", "the vocational school"),
        vocab("der Stundenplan", "the timetable", undefined, "Stundenpläne"),
        vocab("die Pause", "the break"),
        vocab("streng", "strict"),
        vocab("locker", "relaxed"),
        vocab("motiviert", "motivated"),
        vocab("faul", "lazy"),
        vocab("fleißig", "hard-working"),
        vocab("sich vorbereiten", "to prepare"),
        vocab("wiederholen", "to revise"),
        vocab("verstehen", "to understand"),
        vocab("erklären", "to explain"),
        vocab("die Chance", "the chance", undefined, "Chancen"),
        vocab("das Ziel", "the goal", undefined, "Ziele"),
        vocab("der Druck", "the pressure"),
        vocab("die Zukunft", "the future"),
        vocab("das Stipendium", "the scholarship", undefined, "Stipendien"),
      ],
      phrases: [
        phrase("Ich mache eine Ausbildung zur Elektrikerin.", "I am doing vocational training as an electrician."),
        phrase("Er hat das Abitur bestanden.", "He passed the Abitur."),
        phrase("Sie ist durch die Prüfung durchgefallen.", "She failed the exam."),
        phrase("Ich lerne, um später zu studieren.", "I am studying in order to go to university later."),
        phrase("Der Druck in der Schule ist hoch.", "The pressure at school is high."),
        phrase("Mein Ziel ist ein guter Abschluss.", "My goal is a good qualification."),
        phrase("Die Lehrerin erklärt geduldig.", "The teacher explains patiently."),
        phrase("Ohne Hausaufgaben versteht man weniger.", "Without homework you understand less."),
        phrase("Welche Note hast du bekommen?", "What grade did you get?"),
        phrase("Das Stipendium würde mir helfen.", "The scholarship would help me."),
        phrase("Die Uni ist größer als meine alte Schule.", "The uni is bigger than my old school."),
        phrase("Ich bereite mich jeden Abend vor.", "I prepare every evening."),
      ],
      sentences: [
        sentence("Nach der Grundschule kam ich aufs Gymnasium.", "After primary school I went to grammar school."),
        sentence("Die Ausbildung dauert drei Jahre.", "The training lasts three years."),
        sentence("Wir haben morgen eine schwere Prüfung.", "We have a difficult exam tomorrow."),
        sentence("Fleißige Schüler wiederholen den Stoff.", "Hard-working pupils revise the material."),
        sentence("Der Stundenplan ändert sich nächste Woche.", "The timetable changes next week."),
        sentence("Locker unterrichten heißt nicht, nichts zu lernen.", "Teaching in a relaxed way does not mean learning nothing."),
        sentence("Ich bin motiviert, obwohl ich müde bin.", "I am motivated although I am tired."),
        sentence("Das Zeugnis kommt im Juli.", "The report comes in July."),
        sentence("An der Uni muss man selbstständig arbeiten.", "At university you have to work independently."),
        sentence("Die Berufsschule ist praxisnah.", "Vocational school is close to practice."),
        sentence("Ohne Abschluss sind die Chancen kleiner.", "Without a qualification the chances are smaller."),
        sentence("Sie fällt nicht durch, wenn sie übt.", "She will not fail if she practices."),
        sentence("Er ist nicht faul, nur unsicher.", "He is not lazy, just unsure."),
        sentence("Die Zukunft braucht mehr als Noten.", "The future needs more than grades."),
        sentence("Wir verstehen den Text besser nach der Erklärung.", "We understand the text better after the explanation."),
        sentence("Strenge Regeln helfen nicht jedem.", "Strict rules do not help everyone."),
        sentence("Ich habe ein klares Ziel.", "I have a clear goal."),
        sentence("Bildung sollte für alle offen sein.", "Education should be open to everyone."),
      ],
      readings: [
        reading(
          "Course description",
          "Kursbeschreibung",
          "Der B1-Kurs trifft sich dreimal die Woche. Ziel: Alltagstexte verstehen und eigene Meinungen schreiben. Hausaufgaben sind Pflicht, aber nicht endlos. Wer die Prüfung bestehen will, sollte den Wortschatz wiederholen. Ein Einstufungstest entscheidet über die Gruppe. Stipendieninfos hängen im Flur.",
          "The B1 course meets three times a week. Goal: understand everyday texts and write your own opinions. Homework is required but not endless. Anyone who wants to pass the exam should revise vocabulary. A placement test decides the group. Scholarship info is in the hallway.",
          [
            q("How often does the course meet?", "Three times a week", ["Once", "Three times a week", "Daily", "Never"]),
            q("Is homework required?", "Yes", ["No", "Yes", "Only for teachers", "Optional always"]),
            q("What decides the group?", "A placement test", ["Age", "A placement test", "Hair color", "Salary"]),
          ],
        ),
        reading(
          "A report comment",
          "Zeugniskommentar",
          "Leila ist fleißig und stellt kluge Fragen. In Mathe ist sie unsicher, in Deutsch stark. Der Druck vor Prüfungen ist bei ihr hoch. Wir empfehlen, früher anzufangen und Pausen ernst zu nehmen. Mit diesem Plan kann sie das Ziel erreichen.",
          "Leila is hard-working and asks smart questions. She is unsure in maths, strong in German. Exam pressure is high for her. We recommend starting earlier and taking breaks seriously. With this plan she can reach the goal.",
          [
            q("Where is Leila strong?", "German", ["Maths", "German", "Sport only", "Nowhere"]),
            q("What is recommended?", "Start earlier and take breaks", ["Quit school", "Start earlier and take breaks", "No homework", "A new teacher every day"]),
            q("How is exam pressure?", "High", ["Zero", "High", "Funny", "Unknown"]),
          ],
        ),
        reading(
          "Forum: uni or training?",
          "Forum: Uni oder Ausbildung?",
          "Ich weiß nicht, ob ich studieren oder eine Ausbildung machen soll. Das Studium dauert länger, die Ausbildung zahlt schon Gehalt. Meine Eltern wollen Uni, ich will Praxis. Eigentlich sind beide Wege okay. Wer hat Erfahrung?",
          "I don't know whether I should study at university or do vocational training. University takes longer, training already pays a salary. My parents want uni, I want practice. Actually both paths are okay. Who has experience?",
          [
            q("What do the parents want?", "University", ["A gap year", "University", "No school", "Football"]),
            q("What advantage of training is named?", "A salary already", ["A longer holiday", "A salary already", "No work", "A famous name"]),
            q("Is the writer sure?", "No", ["Yes, 100%", "No", "They already finished", "They are a teacher"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Describe your learning path in 6–8 sentences.",
          "Beschreib deinen Bildungsweg.",
          "Ich habe die Schule in Lyon gemacht. Danach bin ich nach Deutschland gekommen, um Deutsch zu lernen. Mein Ziel ist eine Ausbildung. Die Prüfung macht Druck, aber ich bin motiviert.",
          ["Past + present + goal", "um ... zu"],
        ),
        writing(
          "Give advice to someone before an exam.",
          "Gib Prüfungstipps.",
          "Du solltest früh wiederholen. Pausen sind wichtig. Am Abend vorher nicht zu lange lernen. Du kannst das schaffen.",
          ["sollen / können", "Practical tips"],
        ),
      ],
    },
  ),
  chapter(
    "media-tech",
    "Media, News & Technology",
    "Medien, Nachrichten und Technik",
    "Read headlines and app settings, then discuss what you trust online.",
    "mixed",
    [
      "Passive preview: Es wird berichtet, dass …",
      "Nouns from verbs: die Nachricht, die Meldung, die Einstellung.",
      "Relative start: eine App, die viel Daten sammelt.",
    ],
    {
      vocab: [
        vocab("die Medien", "the media"),
        vocab("die Nachricht", "the piece of news", undefined, "Nachrichten"),
        vocab("die Überschrift", "the headline", undefined, "Überschriften"),
        vocab("die Quelle", "the source", undefined, "Quellen"),
        vocab("glaubwürdig", "credible"),
        vocab("falsch", "false"),
        vocab("teilen", "to share"),
        vocab("liken", "to like (social media)"),
        vocab("kommentieren", "to comment"),
        vocab("die Werbung", "advertising"),
        vocab("die Privatsphäre", "privacy"),
        vocab("die Daten", "the data"),
        vocab("das Passwort", "the password", undefined, "Passwörter"),
        vocab("herunterladen", "to download"),
        vocab("hochladen", "to upload"),
        vocab("das Gerät", "the device", undefined, "Geräte"),
        vocab("das Netz", "the network / net", undefined, "Netze"),
        vocab("offline", "offline"),
        vocab("online", "online"),
        vocab("süchtig", "addicted"),
        vocab("nützlich", "useful"),
        vocab("gefährlich", "dangerous"),
        vocab("der Algorithmus", "the algorithm", undefined, "Algorithmen"),
        vocab("die Einstellung", "the setting", undefined, "Einstellungen"),
        vocab("löschen", "to delete"),
        vocab("speichern", "to save"),
        vocab("das Video", "the video", undefined, "Videos"),
        vocab("der Podcast", "the podcast", undefined, "Podcasts"),
        vocab("die Zeitung", "the newspaper"),
        vocab("das Radio", "the radio"),
        vocab("überprüfen", "to check"),
        vocab("verbreiten", "to spread"),
      ],
      phrases: [
        phrase("Hast du die Nachrichten gesehen?", "Have you seen the news?"),
        phrase("Die Quelle ist nicht klar.", "The source is not clear."),
        phrase("Bitte teile das nicht, bevor du es prüfst.", "Please don't share that before you check it."),
        phrase("Die App sammelt zu viele Daten.", "The app collects too much data."),
        phrase("Ich stelle Benachrichtigungen aus.", "I turn notifications off."),
        phrase("Ohne Passwort kommst du nicht weiter.", "Without a password you cannot continue."),
        phrase("Das Video ist nützlich, die Kommentare nicht.", "The video is useful, the comments are not."),
        phrase("Manche werden süchtig nach Likes.", "Some people become addicted to likes."),
        phrase("Es wird berichtet, dass die App verkauft wird.", "It is reported that the app is being sold."),
        phrase("Ich höre lieber Podcasts als Radio.", "I prefer podcasts to radio."),
        phrase("Die Werbung ist zu laut.", "The advertising is too loud."),
        phrase("Schütze deine Privatsphäre.", "Protect your privacy."),
      ],
      sentences: [
        sentence("Ich überprüfe immer die Überschrift und das Datum.", "I always check the headline and the date."),
        sentence("Falsche Nachrichten verbreiten sich schnell.", "False news spreads quickly."),
        sentence("Das Gerät speichert Fotos in der Cloud.", "The device saves photos in the cloud."),
        sentence("Wir laden die Datei herunter.", "We download the file."),
        sentence("Online zu sein heißt nicht, alles zu glauben.", "Being online does not mean believing everything."),
        sentence("Der Algorithmus zeigt immer ähnliche Videos.", "The algorithm always shows similar videos."),
        sentence("Lösche alte Konten, die du nicht brauchst.", "Delete old accounts you don't need."),
        sentence("Ein Podcast erklärt das Thema besser.", "A podcast explains the topic better."),
        sentence("Die Zeitung bleibt für mich glaubwürdig.", "The newspaper remains credible for me."),
        sentence("Kinder sollten nicht allein im Netz sein.", "Children should not be alone on the net."),
        sentence("Ich gehe abends offline.", "I go offline in the evening."),
        sentence("Kommentare können verletzen.", "Comments can hurt."),
        sentence("Nützliche Technik spart Zeit.", "Useful technology saves time."),
        sentence("Gefährliche Links siehst du oft in Werbung.", "You often see dangerous links in ads."),
        sentence("Wir haben das Video hochgeladen.", "We uploaded the video."),
        sentence("Die Einstellungen sind schwer zu finden.", "The settings are hard to find."),
        sentence("Er hat das Passwort vergessen.", "He forgot the password."),
        sentence("Teilen ist keine Pflicht.", "Sharing is not a duty."),
      ],
      readings: [
        reading(
          "A misleading headline",
          "Eine irreführende Überschrift",
          "„Stadt verbietet Fahrräder“ stand gestern überall. Im Text steht nur, eine Straße wird für drei Tage gesperrt. Viele haben den Post geteilt, ohne zu lesen. Die Quelle war ein anonymes Profil. Deshalb prüfe ich jetzt immer den zweiten Absatz.",
          "“City bans bicycles” was everywhere yesterday. In the text it only says one street is closed for three days. Many shared the post without reading. The source was an anonymous profile. That is why I now always check the second paragraph.",
          [
            q("What did the city actually do?", "Close one street for three days", ["Ban all bikes forever", "Close one street for three days", "Sell the city", "Build a port"]),
            q("What was wrong with the source?", "It was anonymous", ["It was the government", "It was anonymous", "It was a book", "It was radio"]),
            q("What will the writer check now?", "The second paragraph", ["Only likes", "The second paragraph", "The weather", "Nothing"]),
          ],
        ),
        reading(
          "Privacy settings",
          "Datenschutz",
          "In den Einstellungen kannst du Standort, Mikrofon und Fotos abschalten. Die App funktioniert dann teilweise. Werbung wird weniger genau. Dafür bleiben mehr Daten bei dir. Ein langes Passwort ist nützlicher als zehn Likes.",
          "In settings you can switch off location, microphone and photos. The app then works only partly. Advertising becomes less precise. In return more data stays with you. A long password is more useful than ten likes.",
          [
            q("What can you switch off?", "Location, microphone, photos", ["The whole internet", "Location, microphone, photos", "The battery forever", "Friends"]),
            q("What happens to ads?", "They become less precise", ["They get louder", "They become less precise", "They disappear by law", "They cost more likes"]),
            q("What is more useful than likes?", "A long password", ["A new phone", "A long password", "More comments", "Sharing everything"]),
          ],
        ),
        reading(
          "Family chat about screens",
          "Familienchat",
          "Papa will, dass wir ab 21 Uhr offline sind. Maya findet das unfair, weil sie für die Schule Videos braucht. Kompromiss: Hausaufgaben ja, Social Media nein. Der Podcast über Nachrichten bleibt erlaubt. Alle speichern den Plan im Kalender.",
          "Dad wants us offline from 9 p.m. Maya thinks that is unfair because she needs videos for school. Compromise: homework yes, social media no. The news podcast stays allowed. Everyone saves the plan in the calendar.",
          [
            q("From when should they be offline?", "21:00", ["12:00", "21:00", "Sunrise", "Never"]),
            q("What is still allowed?", "Homework videos and the news podcast", ["Only likes", "Homework videos and the news podcast", "All apps", "Nothing at all"]),
            q("Where is the plan saved?", "In the calendar", ["On paper only", "In the calendar", "Deleted", "At school"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a comment on a fake headline (6 sentences).",
          "Kommentiere eine Falschmeldung.",
          "Die Überschrift ist zu hart. Im Text steht etwas anderes. Bitte prüft die Quelle. Teilen ohne Lesen ist gefährlich. Ich lösche solche Posts. Glaubwürdige Medien brauchen Zeit.",
          ["Name the problem", "Give advice"],
        ),
        writing(
          "Explain two privacy settings you use.",
          "Erklär zwei Einstellungen.",
          "Ich schalte den Standort aus. Benachrichtigungen sind leise. So bleibt meine Privatsphäre größer.",
          ["Concrete settings", "A reason"],
        ),
      ],
    },
  ),
  chapter(
    "environment",
    "Environment & Everyday Choices",
    "Umwelt und Alltag",
    "Read local campaigns, then write what you can change at home.",
    "mixed",
    [
      "um ... zu / damit for purpose. wenn for conditions.",
      "man sollte / man könnte for suggestions without preaching too hard.",
      "Nouns: die Umwelt, der Müll, die Energie, der Verbrauch.",
    ],
    {
      vocab: [
        vocab("die Umwelt", "the environment"),
        vocab("das Klima", "the climate"),
        vocab("der Müll", "the rubbish"),
        vocab("trennen", "to separate (waste)"),
        vocab("recyclen", "to recycle"),
        vocab("die Energie", "energy"),
        vocab("sparen", "to save"),
        vocab("der Verbrauch", "consumption"),
        vocab("plastikfrei", "plastic-free"),
        vocab("die Verpackung", "the packaging", undefined, "Verpackungen"),
        vocab("das Fahrrad", "the bicycle"),
        vocab("öffentlichen Nahverkehr", "public transport"),
        vocab("das Auto", "the car"),
        vocab("die Heizung", "the heating"),
        vocab("abstellen", "to switch off / turn down"),
        vocab("die Pfandflasche", "the bottle with deposit", undefined, "Pfandflaschen"),
        vocab("der Markt", "the market"),
        vocab("regional", "regional"),
        vocab("bio", "organic"),
        vocab("verschwenden", "to waste"),
        vocab("schützen", "to protect"),
        vocab("die Natur", "nature"),
        vocab("der Wald", "the forest", undefined, "Wälder"),
        vocab("die Luft", "the air"),
        vocab("sauber", "clean"),
        vocab("schmutzig", "dirty"),
        vocab("die Kampagne", "the campaign", undefined, "Kampagnen"),
        vocab("mitmachen", "to take part"),
        vocab("verboten", "forbidden"),
        vocab("sinnvoll", "sensible"),
        vocab("bequem", "convenient"),
        vocab("die Zukunft", "the future"),
      ],
      phrases: [
        phrase("Wir sollten weniger Plastik kaufen.", "We should buy less plastic."),
        phrase("Wenn alle das Licht ausmachen, spart das Strom.", "If everyone turns the light off, that saves electricity."),
        phrase("Ich fahre mit dem Rad, um Geld und CO2 zu sparen.", "I cycle in order to save money and CO2."),
        phrase("Mülltrennung ist in Deutschland normal.", "Separating rubbish is normal in Germany."),
        phrase("Die Heizung muss nicht auf 24 Grad.", "The heating does not have to be at 24 degrees."),
        phrase("Pfandflaschen gehören nicht in den Restmüll.", "Deposit bottles do not belong in general waste."),
        phrase("Regional einkaufen schützt Bauern und Klima.", "Buying regional products protects farmers and the climate."),
        phrase("Die Luft in der Stadt ist oft schmutzig.", "The air in the city is often dirty."),
        phrase("Mach bei der Kampagne mit!", "Join the campaign!"),
        phrase("Bequem ist das Auto, sinnvoller der Bus.", "The car is convenient, the bus more sensible."),
        phrase("Wir dürfen den Wald nicht vergessen.", "We must not forget the forest."),
        phrase("Kleine Schritte zählen trotzdem.", "Small steps still count."),
      ],
      sentences: [
        sentence("Ich trenne Glas, Papier und Bioabfall.", "I separate glass, paper and organic waste."),
        sentence("Die Verpackung ist oft größer als das Produkt.", "The packaging is often bigger than the product."),
        sentence("Wir verschwenden zu viel Essen.", "We waste too much food."),
        sentence("Öffentliche Bahnen sind voll, aber nützlich.", "Public trains are full but useful."),
        sentence("Im Winter stelle ich die Heizung nachts ab.", "In winter I turn the heating down at night."),
        sentence("Ein plastikfreier Einkauf braucht Planung.", "A plastic-free shop needs planning."),
        sentence("Die Natur in den Alpen ist empfindlich.", "Nature in the Alps is fragile."),
        sentence("Saubere Flüsse sind ein Ziel der Stadt.", "Clean rivers are a goal of the city."),
        sentence("Man könnte öfter zu Fuß gehen.", "One could walk more often."),
        sentence("Bio ist teurer, aber nicht immer nötig.", "Organic is more expensive but not always necessary."),
        sentence("Der Verbrauch von Strom steigt im Sommer.", "Electricity consumption rises in summer."),
        sentence("Kinder lernen Mülltrennung schon in der Kita.", "Children already learn waste separation at preschool."),
        sentence("Ein Waldspaziergang kostet nichts.", "A walk in the forest costs nothing."),
        sentence("Die Kampagne erklärt Pfand klar.", "The campaign explains the deposit clearly."),
        sentence("Ohne Auto lebe ich nicht schlechter.", "I do not live worse without a car."),
        sentence("Schmutzige Luft macht krank.", "Dirty air makes people ill."),
        sentence("Wir schützen die Umwelt nicht mit Worten allein.", "We do not protect the environment with words alone."),
        sentence("Die Zukunft beginnt im Supermarkt.", "The future starts in the supermarket."),
      ],
      readings: [
        reading(
          "City campaign",
          "Stadtkampagne",
          "„Vier Wochen ohne Auto.“ Bus und Bahn sind in dieser Zeit günstiger. Wer mitmacht, bekommt eine Karte für den Nahverkehr. Ziel: weniger Stau, bessere Luft. Manche finden es unbequem, andere sinnvoll. Die Stadt misst danach die Luftwerte.",
          "“Four weeks without a car.” Buses and trains are cheaper during this time. Anyone who joins gets a public-transport card. Goal: less congestion, better air. Some find it inconvenient, others sensible. Afterwards the city measures air quality.",
          [
            q("What do participants get?", "A public-transport card", ["A new car", "A public-transport card", "A forest", "Nothing"]),
            q("What is measured afterwards?", "Air quality", ["Happiness only", "Air quality", "Rain", "Exam grades"]),
            q("How long is the campaign?", "Four weeks", ["Four days", "Four weeks", "A year", "Forever"]),
          ],
        ),
        reading(
          "WG kitchen rules",
          "WG-Küche",
          "Bitte Müll trennen. Pfand neben die Tür. Reste nicht einfach wegwerfen — es gibt eine Box im Kühlschrank. Die Spülmaschine nur starten, wenn sie voll ist, um Energie zu sparen. Plastiktüten brauchen wir nicht. Danke!",
          "Please separate rubbish. Deposit bottles by the door. Don't just throw leftovers away — there is a box in the fridge. Only start the dishwasher when it is full, to save energy. We don't need plastic bags. Thanks!",
          [
            q("Where do deposit bottles go?", "By the door", ["In residual waste", "By the door", "In the dishwasher", "Outside the city"]),
            q("When should the dishwasher run?", "When it is full", ["After every cup", "When it is full", "Never", "At noon only"]),
            q("What about leftovers?", "Keep them in a fridge box", ["Always bin them", "Keep them in a fridge box", "Give to the car", "Burn them"]),
          ],
        ),
        reading(
          "A sceptical letter",
          "Skeptischer Brief",
          "Ich finde Kampagnen gut, aber sie ersetzen keine Politik. Wenn Flüge billiger sind als Züge, ändern Einzelne wenig. Trotzdem kaufe ich regional, weil es schmeckt und kürzere Wege hat. Bequemlichkeit gewinnt oft. Deshalb brauchen wir klare Regeln, nicht nur Tipps.",
          "I think campaigns are good, but they do not replace politics. If flights are cheaper than trains, individuals change little. Still I buy regional products because they taste good and have shorter journeys. Convenience often wins. That is why we need clear rules, not just tips.",
          [
            q("Why do individuals change little, according to the writer?", "Flights can be cheaper than trains", ["Nobody shops", "Flights can be cheaper than trains", "Forests are illegal", "No campaigns exist"]),
            q("Why buy regional?", "Taste and shorter journeys", ["It's always cheaper", "Taste and shorter journeys", "The law", "Advertising"]),
            q("What does the writer want besides tips?", "Clear rules", ["More plastic", "Clear rules", "Louder ads", "No trains"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Propose three everyday environmental changes.",
          "Schlag drei Alltagsänderungen vor.",
          "Ich fahre öfter mit dem Rad. Wir trennen den Müll. Die Heizung ist nachts leiser. So sparen wir Energie, ohne perfekt zu sein.",
          ["Concrete actions", "One reason"],
        ),
        writing(
          "Reply to the sceptical letter in 5 sentences.",
          "Antworte auf den skeptischen Brief.",
          "Du hast recht, dass Preise zählen. Trotzdem helfen kleine Schritte. Regeln und Alltag müssen zusammenkommen. Ich mache bei der Kampagne mit. Was schlägst du vor?",
          ["Agree partly", "Add your view"],
        ),
      ],
    },
  ),
  chapter(
    "culture",
    "Culture, Traditions & Everyday Life",
    "Kultur, Traditionen und Alltag",
    "Read festival notes and invitations, then compare customs without clichés.",
    "reading",
    [
      "Festivals: Weihnachten, Ostern, Karneval, Oktoberfest — but also local Kirchweih, Schützenfest.",
      "man vs wir when describing customs: In Deutschland sagt man du später als in Spanien.",
      "Comparisons: anders als, ähnlich wie, im Vergleich zu.",
    ],
    {
      vocab: [
        vocab("die Kultur", "culture", undefined, "Kulturen"),
        vocab("die Tradition", "the tradition", undefined, "Traditionen"),
        vocab("das Fest", "the festival / party", undefined, "Feste"),
        vocab("feiern", "to celebrate"),
        vocab("einladen", "to invite"),
        vocab("die Einladung", "the invitation"),
        vocab("das Geschenk", "the present", undefined, "Geschenke"),
        vocab("die Feiertage", "the public holidays"),
        vocab("Weihnachten", "Christmas"),
        vocab("Ostern", "Easter"),
        vocab("Karneval", "carnival"),
        vocab("das Feuerwerk", "the fireworks"),
        vocab("die Tracht", "traditional costume", undefined, "Trachten"),
        vocab("das Lied", "the song", undefined, "Lieder"),
        vocab("die Küche", "the cuisine / kitchen"),
        vocab("typisch", "typical"),
        vocab("ungewöhnlich", "unusual"),
        vocab("höflich", "polite"),
        vocab("direkt", "direct"),
        vocab("pünktlich", "punctual"),
        vocab("die Gastfreundschaft", "hospitality"),
        vocab("der Brauch", "the custom", undefined, "Bräuche"),
        vocab("sich begrüßen", "to greet each other"),
        vocab("duzen", "to use du"),
        vocab("siezen", "to use Sie"),
        vocab("das Museum", "the museum"),
        vocab("das Theater", "the theatre"),
        vocab("die Religion", "religion", undefined, "Religionen"),
        vocab("respektieren", "to respect"),
        vocab("anders", "different"),
        vocab("gemeinsam", "together / in common"),
        vocab("die Vielfalt", "diversity"),
      ],
      phrases: [
        phrase("Bei uns feiert man Silvester mit Feuerwerk.", "Where I am from, New Year’s Eve is celebrated with fireworks."),
        phrase("Im Vergleich zu zu Hause ist man hier pünktlicher.", "Compared with home, people here are more punctual."),
        phrase("Darf ich duzen oder lieber siezen?", "May I use du or rather Sie?"),
        phrase("Typisch ist nicht immer wahr.", "Typical is not always true."),
        phrase("Wir sind zu einem Fest eingeladen.", "We are invited to a festival."),
        phrase("Bringt man ein Geschenk mit?", "Do you bring a present?"),
        phrase("Die Küche ist anders als in meiner Stadt.", "The food is different from in my city."),
        phrase("Ich respektiere eure Tradition, auch wenn ich nicht mitfeiere.", "I respect your tradition even if I do not join the celebration."),
        phrase("Karneval ist laut, Weihnachten eher still.", "Carnival is loud, Christmas rather quiet."),
        phrase("Gemeinsam essen ist bei uns wichtig.", "Eating together is important for us."),
        phrase("Das Museum erklärt die Geschichte der Stadt.", "The museum explains the city’s history."),
        phrase("Vielfalt macht den Alltag interessanter.", "Diversity makes everyday life more interesting."),
      ],
      sentences: [
        sentence("Ostern fällt jedes Jahr auf ein anderes Datum.", "Easter falls on a different date each year."),
        sentence("Manche Läden sind an Feiertagen geschlossen.", "Some shops are closed on public holidays."),
        sentence("Die Tracht trägt man nicht jeden Tag.", "You do not wear traditional costume every day."),
        sentence("Ein ungewöhnliches Geschenk ist oft besser als teurer Wein.", "An unusual present is often better than expensive wine."),
        sentence("Direkt zu sein heißt nicht unhöflich zu sein.", "Being direct does not mean being impolite."),
        sentence("Wir begrüßen uns mit Handschlag, nicht immer mit Umarmung.", "We greet each other with a handshake, not always with a hug."),
        sentence("Im Theater sollte das Handy aus sein.", "In the theatre the phone should be off."),
        sentence("Religion ist privat, Respekt ist öffentlich.", "Religion is private, respect is public."),
        sentence("Der Brauch kommt aus dem 19. Jahrhundert.", "The custom comes from the 19th century."),
        sentence("Gastfreundschaft sieht in jedem Land anders aus.", "Hospitality looks different in every country."),
        sentence("Sie singen ein altes Lied am Lagerfeuer.", "They sing an old song at the campfire."),
        sentence("Pünktlichkeit wird hier erwartet.", "Punctuality is expected here."),
        sentence("Das Fest dauert drei Tage.", "The festival lasts three days."),
        sentence("Ich finde Feuerwerk schön und problematisch.", "I find fireworks beautiful and problematic."),
        sentence("Anders essen erweitert den Geschmack.", "Eating differently expands your taste."),
        sentence("Wir haben mehr gemeinsam, als man denkt.", "We have more in common than people think."),
        sentence("Die Einladung kam per Karte, nicht per Chat.", "The invitation came by card, not by chat."),
        sentence("Kultur ändert sich, auch wenn Lieder alt bleiben.", "Culture changes even if songs stay old."),
      ],
      readings: [
        reading(
          "Invitation to a street festival",
          "Einladung zum Straßenfest",
          "Liebe Nachbarinnen und Nachbarn, am Samstag feiert unsere Straße Kirchweih. Ab 16 Uhr gibt es Musik, ab 18 Uhr Essen vom Grill. Bitte keine lauten Böller, Kinder sind da. Wer ein Salat mitbringt, ist willkommen. Bei Regen treffen wir uns in der Turnhalle. Bis bald!",
          "Dear neighbours, on Saturday our street celebrates the church fair. From 4 p.m. there is music, from 6 p.m. food from the grill. Please no loud fireworks, children will be there. Anyone who brings a salad is welcome. If it rains we meet in the gym. See you soon!",
          [
            q("When does the food start?", "18:00", ["16:00", "18:00", "Midnight", "Sunday"]),
            q("Why no loud fireworks?", "Children will be there", ["It is illegal always", "Children will be there", "No grill", "Rain"]),
            q("Rain plan?", "Meet in the gym", ["Cancel forever", "Meet in the gym", "Go to the Alps", "Online only"]),
          ],
        ),
        reading(
          "A comparison essay opening",
          "Vergleichsanfang",
          "In Spanien isst man oft spät, in Deutschland eher um sechs. Das klingt wie ein Klischee, ist aber in meiner WG spürbar. Anders als zu Hause duzen wir die Nachbarn nicht sofort. Ähnlich wie zu Hause ist das gemeinsame Essen am Sonntag. Vielfalt heißt, beides zu kennen und nichts für dumm zu erklären.",
          "In Spain people often eat late, in Germany more around six. That sounds like a cliché, but it is noticeable in my flatshare. Unlike at home we do not switch to du with neighbours immediately. Similar to home is Sunday lunch together. Diversity means knowing both and not calling either stupid.",
          [
            q("When do people tend to eat in Germany, according to the text?", "Around six", ["At midnight", "Around six", "Never", "Only at Christmas"]),
            q("What is similar to home?", "Sunday lunch together", ["Always using du", "Sunday lunch together", "No neighbours", "Fireworks daily"]),
            q("What does diversity mean here?", "Knowing both without insulting either", ["Choosing one country", "Knowing both without insulting either", "Ignoring food", "Only museums"]),
          ],
        ),
        reading(
          "Museum caption",
          "Museumstext",
          "Dieser Brauch entstand, als die Stadt noch klein war. Heute tragen nur Vereine die Tracht. Das Lied kennt fast jedes Kind, den Text verstehen wenige. Das Fest ist laut, die Kirche daneben still. Respekt heißt, beides zu lassen. Die Vitrine erklärt mehr als jedes Souvenir.",
          "This custom began when the town was still small. Today only clubs wear the costume. Almost every child knows the song, few understand the lyrics. The festival is loud, the church next to it quiet. Respect means allowing both. The display case explains more than any souvenir.",
          [
            q("Who wears the costume today?", "Clubs / associations", ["Every child", "Clubs / associations", "Only tourists", "Nobody"]),
            q("Do most people understand the song lyrics?", "No", ["Yes, perfectly", "No", "Only in English", "There is no song"]),
            q("What explains more than a souvenir?", "The display case", ["A postcard", "The display case", "A hat", "Fireworks"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Compare a custom from your country with one in Germany.",
          "Vergleiche einen Brauch.",
          "Bei uns isst man später. Hier ist man pünktlicher zum Essen. Anders als zu Hause bringt man oft eine Kleinigkeit mit. Beides finde ich höflich, nur anders.",
          ["anders als / im Vergleich zu", "Avoid cheap clichés"],
        ),
        writing(
          "Write a 5-line invitation to a small celebration.",
          "Schreib eine Einladung.",
          "Hallo Freunde, am Freitag feiern wir in der Wohnung. Ab 19 Uhr, bitte pünktlich. Ein Salat oder Getränk mitbringen. Bis dann!",
          ["When, where, what to bring"],
        ),
      ],
    },
  ),
  chapter(
    "cases-review",
    "Accusative, Dative & Two-Way Prepositions",
    "Akkusativ, Dativ und Wechselpräpositionen",
    "Read signs and messages where case actually changes meaning, then write them correctly.",
    "grammar",
    [
      "Accusative: den/einen, die/eine, das/ein — direct objects and many time expressions.",
      "Dative: dem/einem, der/einer, dem/einem — indirect objects; mit, nach, bei, von, zu.",
      "Two-way: in, an, auf, über, unter, vor, hinter, neben, zwischen — accusative = movement, dative = location.",
    ],
    {
      vocab: [
        vocab("der Fall", "the case", undefined, "Fälle"),
        vocab("der Akkusativ", "the accusative"),
        vocab("der Dativ", "the dative"),
        vocab("die Präposition", "the preposition", undefined, "Präpositionen"),
        vocab("legen", "to lay (flat)"),
        vocab("liegen", "to lie (be lying)"),
        vocab("stellen", "to put (upright)"),
        vocab("stehen", "to stand"),
        vocab("hängen", "to hang"),
        vocab("setzen", "to set / sit someone"),
        vocab("sitzen", "to sit"),
        vocab("in", "in / into"),
        vocab("an", "at / on (vertical)"),
        vocab("auf", "on (horizontal)"),
        vocab("über", "over / above"),
        vocab("unter", "under"),
        vocab("vor", "in front of / before"),
        vocab("hinter", "behind"),
        vocab("neben", "next to"),
        vocab("zwischen", "between"),
        vocab("mit", "with"),
        vocab("nach", "to / after"),
        vocab("bei", "at / near"),
        vocab("von", "from / of"),
        vocab("zu", "to"),
        vocab("ohne", "without"),
        vocab("für", "for"),
        vocab("durch", "through"),
        vocab("gegen", "against"),
        vocab("um", "around / at (time)"),
        vocab("der Tisch", "the table"),
        vocab("die Wand", "the wall"),
      ],
      phrases: [
        phrase("Ich stelle die Lampe auf den Tisch.", "I put the lamp on the table. (movement)"),
        phrase("Die Lampe steht auf dem Tisch.", "The lamp is standing on the table. (location)"),
        phrase("Wir gehen in die Küche.", "We are going into the kitchen."),
        phrase("Wir sitzen in der Küche.", "We are sitting in the kitchen."),
        phrase("Das Bild hängt an der Wand.", "The picture is hanging on the wall."),
        phrase("Ich hänge das Bild an die Wand.", "I am hanging the picture on the wall."),
        phrase("Ich gebe dem Kind einen Apfel.", "I give the child an apple."),
        phrase("Ohne den Schlüssel kommst du nicht rein.", "Without the key you cannot get in."),
        phrase("Wir fahren mit dem Bus zur Arbeit.", "We take the bus to work."),
        phrase("Das Café ist neben der Bank.", "The café is next to the bank."),
        phrase("Leg das Buch nicht unter den Stuhl.", "Don't put the book under the chair."),
        phrase("Der Hund liegt unter dem Tisch.", "The dog is lying under the table."),
      ],
      sentences: [
        sentence("Ich sehe den Mann vor dem Bahnhof.", "I see the man in front of the station."),
        sentence("Sie schreibt einen Brief an ihre Tante.", "She is writing a letter to her aunt."),
        sentence("Er hilft der Nachbarin mit den Tüten.", "He helps the neighbour with the bags."),
        sentence("Wir laufen durch den Park.", "We are walking through the park."),
        sentence("Das Auto steht hinter dem Haus.", "The car is standing behind the house."),
        sentence("Stell den Stuhl neben das Sofa.", "Put the chair next to the sofa."),
        sentence("Der Stuhl steht neben dem Sofa.", "The chair is standing next to the sofa."),
        sentence("Ich warte auf den Bus.", "I am waiting for the bus."),
        sentence("Bei schlechtem Wetter bleiben wir zu Hause.", "In bad weather we stay at home."),
        sentence("Von meinem Fenster sehe ich die Brücke.", "From my window I see the bridge."),
        sentence("Für den Kurs brauchst du ein Buch.", "For the course you need a book."),
        sentence("Gegen Abend wird es kühl.", "Towards evening it gets cool."),
        sentence("Um die Ecke ist eine Apotheke.", "Around the corner is a pharmacy."),
        sentence("Nach dem Essen gehen wir spazieren.", "After the meal we go for a walk."),
        sentence("Ich lege das Handy auf den Schrank.", "I put the phone on the cupboard."),
        sentence("Das Handy liegt auf dem Schrank.", "The phone is lying on the cupboard."),
        sentence("Zwischen den Häusern ist ein Hof.", "Between the houses there is a courtyard."),
        sentence("Ohne einen Plan verlieren wir Zeit.", "Without a plan we lose time."),
      ],
      readings: [
        reading(
          "Moving-day note",
          "Umzugszettel",
          "Bitte die Kisten in das Wohnzimmer stellen, nicht in den Flur. Die Lampe gehört auf den Tisch, die Bilder an die Wand. Der Hund darf nicht auf das Sofa. Schlüssel liegen in der Küche neben der Kaffeemaschine. Danke!",
          "Please put the boxes into the living room, not into the hallway. The lamp belongs on the table, the pictures on the wall. The dog is not allowed onto the sofa. Keys are in the kitchen next to the coffee machine. Thanks!",
          [
            q("Where should the boxes go?", "Into the living room", ["Into the hallway", "Into the living room", "Onto the sofa", "Under the table"]),
            q("Where are the keys?", "In the kitchen next to the coffee machine", ["On the sofa", "In the kitchen next to the coffee machine", "In the car", "On the wall"]),
            q("Is the dog allowed on the sofa?", "No", ["Yes", "No", "Only at night", "If it rains"]),
          ],
        ),
        reading(
          "A grammar comic caption",
          "Grammatik-Comic",
          "Linkes Bild: Mia legt das Buch auf den Tisch. Rechtes Bild: Das Buch liegt auf dem Tisch. Der Unterschied ist klein und riesig. Bewegung braucht Akkusativ, Ort Dativ. Übung macht den Fall sichtbar.",
          "Left picture: Mia puts the book on the table. Right picture: The book is lying on the table. The difference is small and huge. Movement needs accusative, place dative. Practice makes the case visible.",
          [
            q("Which case for movement onto the table?", "Accusative", ["Dative", "Accusative", "Genitive", "None"]),
            q("Which case when the book is already there?", "Dative", ["Accusative", "Dative", "Nominative only", "English"]),
            q("What makes case visible?", "Practice", ["A bigger table", "Practice", "Shouting", "No prepositions"]),
          ],
        ),
        reading(
          "Invitation with cases",
          "Einladung",
          "Komm um sieben zu uns. Wir sitzen in der Küche, später gehen wir in den Garten. Bring etwas für den Salat mit. Ohne dich ist die Party kleiner. Der Weg führt durch den Hof hinter dem Haus.",
          "Come to us at seven. We sit in the kitchen, later we go into the garden. Bring something for the salad. Without you the party is smaller. The way leads through the courtyard behind the house.",
          [
            q("Where do they sit first?", "In the kitchen", ["In the garden", "In the kitchen", "In the courtyard", "On a bus"]),
            q("Where do they go later?", "Into the garden", ["Home", "Into the garden", "To school", "To the bank"]),
            q("How do you reach them?", "Through the courtyard behind the house", ["Over the roof", "Through the courtyard behind the house", "By plane", "You cannot"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write four pairs: movement vs location.",
          "Schreib vier Paare Bewegung/Ort.",
          "Ich gehe in die Küche. Ich bin in der Küche. Ich lege das Buch auf den Tisch. Das Buch liegt auf dem Tisch.",
          ["Accusative vs dative", "Same preposition twice"],
        ),
        writing(
          "Describe a room using at least five prepositions.",
          "Beschreib ein Zimmer.",
          "Das Sofa steht an der Wand. Ein Teppich liegt auf dem Boden. Die Lampe hängt über dem Tisch. Der Hund liegt unter dem Stuhl. Neben der Tür ist ein Schrank.",
          ["Dative for location"],
        ),
      ],
    },
  ),
];
