import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const b2ChaptersPart2: ChapterSource[] = [
  chapter(
    "literature",
    "Literature: Reading Between the Lines",
    "Literatur: Zwischen den Zeilen lesen",
    "Read short literary extracts, then describe tone, image, and what is not said.",
    "reading",
    [
      "Erzählperspektive: ich, er/sie, wir. Zeit: Präteritum vs historisches Präsens.",
      "Bilder und Wiederholungen tragen oft mehr als die Handlung.",
      "Interpretation belegen: Zitat + Deutung, nicht nur Gefühl.",
    ],
    {
      vocab: [
        vocab("die Literatur", "literature"),
        vocab("die Erzählung", "the narrative / story", undefined, "Erzählungen"),
        vocab("das Gedicht", "the poem", undefined, "Gedichte"),
        vocab("die Strophe", "the stanza", undefined, "Strophen"),
        vocab("die Metapher", "the metaphor", undefined, "Metaphern"),
        vocab("das Bild", "the image", undefined, "Bilder"),
        vocab("der Ton", "the tone"),
        vocab("die Stimmung", "the mood", undefined, "Stimmungen"),
        vocab("die Ironie", "irony"),
        vocab("der Erzähler", "the narrator (m)"),
        vocab("die Erzählerin", "the narrator (f)"),
        vocab("die Perspektive", "the perspective", undefined, "Perspektiven"),
        vocab("andeuten", "to hint"),
        vocab("verschweigen", "to leave unsaid"),
        vocab("wiederholen", "to repeat"),
        vocab("der Kontrast", "the contrast", undefined, "Kontraste"),
        vocab("alltäglich", "everyday"),
        vocab("seltsam", "strange"),
        vocab("dicht", "dense (style)"),
        vocab("knapp", "sparse / terse"),
        vocab("ausschmücken", "to embellish"),
        vocab("das Motiv", "the motif", undefined, "Motive"),
        vocab("das Thema", "the theme"),
        vocab("deuten", "to interpret"),
        vocab("belegen", "to evidence"),
        vocab("das Zitat", "the quotation", undefined, "Zitate"),
        vocab("zwischen den Zeilen", "between the lines"),
        vocab("offen", "open-ended"),
        vocab("eindeutig", "unambiguous"),
        vocab("mehrdeutig", "ambiguous"),
        vocab("der Schluss", "the ending"),
        vocab("unzuverlässig", "unreliable"),
      ],
      phrases: [
        phrase("Der Ton ist kühl, die Bilder sind warm.", "The tone is cool, the images are warm."),
        phrase("Was verschwiegen wird, zählt mit.", "What is left unsaid also counts."),
        phrase("Die Wiederholung von „noch“ macht die Zeit schwer.", "The repetition of “noch” makes time heavy."),
        phrase("Ich-Erzähler heißt nicht autobiografisch.", "First person does not mean autobiographical."),
        phrase("Zwischen den Zeilen steht Angst, nicht die Handlung.", "Between the lines there is fear, not the plot."),
        phrase("Ein knapper Satz kann härter sein als eine Seite Schmuck.", "A terse sentence can be harder than a page of ornament."),
        phrase("Das Motiv der Tür kehrt dreimal wieder.", "The door motif returns three times."),
        phrase("Deute nur, was du zitieren kannst.", "Interpret only what you can quote."),
        phrase("Der Schluss bleibt offen, nicht unfertig.", "The ending stays open, not unfinished."),
        phrase("Ironie erkennt man am Missverhältnis von Anspruch und Detail.", "You recognise irony in the mismatch of claim and detail."),
        phrase("Alltägliche Dinge wirken seltsam, wenn der Rhythmus stockt.", "Everyday things seem strange when the rhythm stalls."),
        phrase("Eine unzuverlässige Stimme verrät sich durch Widersprüche.", "An unreliable voice gives itself away through contradictions."),
      ],
      sentences: [
        sentence("Das Gedicht hat drei Strophen und keinen Reim.", "The poem has three stanzas and no rhyme."),
        sentence("Die Metapher vom Eis erklärt die Beziehung besser als jedes Adjektiv.", "The ice metaphor explains the relationship better than any adjective."),
        sentence("Wir sehen die Stadt nur durch ein Fenster, also begrenzt.", "We see the city only through a window, hence limited."),
        sentence("Der Kontrast zwischen Fest und Stille trägt die Szene.", "The contrast between feast and silence carries the scene."),
        sentence("Mehrdeutigkeit ist hier Absicht, nicht Schwäche.", "Ambiguity is intentional here, not a weakness."),
        sentence("Eindeutige Moral hätte den Text verkleinert.", "An unambiguous moral would have shrunk the text."),
        sentence("Die Erzählerin andeutet mehr, als sie sagt.", "The narrator hints at more than she says."),
        sentence("Im historischen Präsens wirkt die Panik gegenwärtig.", "In the historical present the panic feels present."),
        sentence("Ein dichtes Bild braucht keine Erklärung im nächsten Satz.", "A dense image needs no explanation in the next sentence."),
        sentence("Ausschmücken würde die Angst weichspülen.", "Embellishing would soften the fear."),
        sentence("Das Thema ist Einsamkeit, das Motiv der leere Tisch.", "The theme is loneliness, the motif the empty table."),
        sentence("Belege deine Deutung mit drei Wörtern aus Zeile zwei.", "Evidence your reading with three words from line two."),
        sentence("Der unzuverlässige Erzähler rühmt sich, während Details ihn widerlegen.", "The unreliable narrator boasts while details refute him."),
        sentence("Stimmung entsteht aus Rhythmus, nicht aus dem Wort „traurig“.", "Mood comes from rhythm, not from the word “sad”."),
        sentence("Eine seltsame Alltäglichkeit ist oft der Einstieg in moderne Texte.", "A strange everyday quality is often the entry into modern texts."),
        sentence("Perspektive wechseln heißt Macht verschieben.", "Changing perspective means shifting power."),
        sentence("Was nicht gesagt wird über die Mutter, füllt den Raum.", "What is not said about the mother fills the room."),
        sentence("Literatur trainiert genaues Lesen — nützlich auch außerhalb von Gedichten.", "Literature trains close reading — useful outside poems too."),
      ],
      readings: [
        reading(
          "Microfiction",
          "Mikronarrativ",
          "Die Tür war zu. Nicht abgeschlossen, nur zu. Draußen lachte jemand, als gäbe es kein Zimmer. Im Zimmer stand ein Tisch ohne Stuhl. Sie zählte bis zwölf, wie früher, und öffnete nicht. Noch war Zeit. Noch. Das Wort wurde schwerer als die Tür.",
          "The door was shut. Not locked, only shut. Outside someone laughed as if there were no room. In the room stood a table without a chair. She counted to twelve, as she used to, and did not open. There was still time. Still. The word grew heavier than the door.",
          [
            q("Is the door locked?", "No, only shut", ["Yes, with a key", "No, only shut", "There is no door", "Open"]),
            q("What is missing at the table?", "A chair", ["A lamp", "A chair", "Food named", "A window"]),
            q("Which word grows heavy?", "Noch", ["Tür", "Noch", "Zwölf", "Lachen"]),
          ],
        ),
        reading(
          "Student interpretation",
          "Schülerdeutung",
          "Ich deute „noch“ als Aufschub, nicht als Hoffnung. Beleg: Sie öffnet nicht, obwohl sie zählt. Die lachende Stimme draußen steht im Kontrast zur Stille innen. Ob die Figur Angst hat, sagt der Text nicht eindeutig. Gerade deshalb bleibt er offen. Ein Satz Moral würde ihn schließen.",
          "I read “noch” as postponement, not hope. Evidence: she does not open although she counts. The laughing voice outside contrasts with the silence inside. Whether the figure is afraid the text does not say unambiguously. That is exactly why it stays open. A moral sentence would close it.",
          [
            q("How is “noch” interpreted?", "As postponement, not hope", ["As a joke", "As postponement, not hope", "As a tram stop", "As a name"]),
            q("What contrast is named?", "Outside laughter vs inside silence", ["Hot vs cold tea", "Outside laughter vs inside silence", "Rhyme vs no rhyme", "City vs forest"]),
            q("Why keep it open?", "The text does not state fear unambiguously", ["The teacher said so", "The text does not state fear unambiguously", "There are no words", "It's a law"]),
          ],
        ),
        reading(
          "Poem fragment",
          "Gedichtfragment",
          "Nacht ohne Mond. / Die Straße atmet aus. / Ein Fenster, das nicht antwortet. / Wir gehen weiter, / als wäre Gehen eine Antwort.",
          "Night without moon. / The street breathes out. / A window that does not answer. / We walk on, / as if walking were an answer.",
          [
            q("What does the window do?", "Not answer", ["Shine brightly", "Not answer", "Open wide", "Speak Latin"]),
            q("What is walking compared to?", "An answer", ["A door", "An answer", "A chair", "A train"]),
            q("Is there a moon?", "No", ["Yes, full", "No", "Two moons", "Unclear / the word Mond appears as absence"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Interpret the microfiction in 6 sentences with one quotation.",
          "Deute die Miniatur mit einem Zitat.",
          "Die Figur öffnet nicht. Das Zitat „Noch war Zeit“ klingt nach Aufschub. Draußen gibt es Lachen, innen einen Tisch ohne Stuhl. Der Kontrast macht das Zimmer enger. Der Text sagt „Angst“ nicht. Gerade deshalb wirkt er dichter.",
          ["Quote + interpretation", "Name a contrast"],
        ),
        writing(
          "Write 8 lines of sparse prose in German (no “traurig”).",
          "Schreib knappe Prosa ohne das Wort traurig.",
          "Die Küche war hell. Niemand saß. Draußen ein Bus, der nicht hielt. Sie spülte eine Tasse, die schon sauber war.",
          ["Images, not labels", "Präteritum or present"],
        ),
      ],
    },
  ),
  chapter(
    "business",
    "Business German: Meetings, Offers & Tone",
    "Wirtschaftsdeutsch: Meetings, Angebote, Ton",
    "Read offers and minutes, then write a follow-up that is clear under pressure.",
    "writing",
    [
      "Nominalisierungen in Mails entpacken: nach erfolgter Prüfung → nachdem wir geprüft haben.",
      "Offers: Leistung, Preis, Gültigkeit, nächster Schritt.",
      "Meeting: Ziel, Beschluss, Verantwortliche, Frist — not atmosphere.",
    ],
    {
      vocab: [
        vocab("das Angebot", "the offer", undefined, "Angebote"),
        vocab("die Anfrage", "the enquiry", undefined, "Anfragen"),
        vocab("die Verhandlung", "the negotiation", undefined, "Verhandlungen"),
        vocab("der Vertrag", "the contract", undefined, "Verträge"),
        vocab("die Frist", "the deadline"),
        vocab("gültig", "valid"),
        vocab("der Preis", "the price"),
        vocab("die Leistung", "the service / deliverable", undefined, "Leistungen"),
        vocab("die Rechnung", "the invoice"),
        vocab("zahlbar", "payable"),
        vocab("das Meeting", "the meeting", undefined, "Meetings"),
        vocab("das Protokoll", "the minutes", undefined, "Protokolle"),
        vocab("der Beschluss", "the decision", undefined, "Beschlüsse"),
        vocab("zuständig", "responsible"),
        vocab("die Agenda", "the agenda", undefined, "Agenden"),
        vocab("der Stakeholder", "the stakeholder", undefined, "Stakeholder"),
        vocab("der Umsatz", "the turnover", undefined, "Umsätze"),
        vocab("die Marge", "the margin", undefined, "Margen"),
        vocab("lieferbar", "available / deliverable"),
        vocab("verzögern", "to delay"),
        vocab("eskalieren", "to escalate"),
        vocab("nachfassen", "to follow up"),
        vocab("knapp", "tight / brief"),
        vocab("verbindlich", "binding"),
        vocab("unverbindlich", "non-binding"),
        vocab("die NDA", "the non-disclosure agreement"),
        vocab("die Kapazität", "capacity"),
        vocab("skalieren", "to scale"),
        vocab("der Engpass", "the bottleneck", undefined, "Engpässe"),
        vocab("priorisieren", "to prioritise"),
        vocab("der Kunde", "the client"),
        vocab("die Kundin", "the client (f)"),
      ],
      phrases: [
        phrase("Vielen Dank für Ihre Anfrage vom 3. März.", "Thank you for your enquiry of 3 March."),
        phrase("Anbei unser Angebot, gültig bis 31.03.", "Attached our offer, valid until 31 March."),
        phrase("Die Leistung umfasst Installation und zwei Schulungen.", "The service includes installation and two training sessions."),
        phrase("Zahlbar innerhalb von 14 Tagen ohne Abzug.", "Payable within 14 days with no deduction."),
        phrase("Im Protokoll halten wir fest: …", "In the minutes we record: …"),
        phrase("Zuständig ist Frau Kehl, Frist Freitag.", "Ms Kehl is responsible, deadline Friday."),
        phrase("Könnten Sie die Kapazität im Mai bestätigen?", "Could you confirm capacity in May?"),
        phrase("Das Angebot ist noch unverbindlich.", "The offer is still non-binding."),
        phrase("Wir müssen priorisieren, sonst eskaliert der Engpass.", "We have to prioritise, otherwise the bottleneck will escalate."),
        phrase("Ich fasse nach, weil die Frist morgen endet.", "I am following up because the deadline ends tomorrow."),
        phrase("Bitte um verbindliche Zusage bis Mittwoch.", "Please send a binding confirmation by Wednesday."),
        phrase("Der Umsatz steigt, die Marge nicht automatisch.", "Turnover is rising, the margin is not automatically."),
      ],
      sentences: [
        sentence("Nach erfolgter Prüfung senden wir die Verträge.", "After review we will send the contracts."),
        sentence("Die Agenda hat drei Punkte, nicht dreißig.", "The agenda has three items, not thirty."),
        sentence("Ein Stakeholder ohne Frist ist nur ein Kommentar.", "A stakeholder without a deadline is only a comment."),
        sentence("Lieferbar ab KW 18, falls der Engpass bleibt.", "Deliverable from week 18 if the bottleneck remains."),
        sentence("Die Verzögerung müssen wir dem Kunden klar nennen, nicht schönreden.", "We must name the delay clearly to the client, not spin it."),
        sentence("Skalieren ohne Leute ist eine Illusion.", "Scaling without people is an illusion."),
        sentence("NDA unterschreiben wir, bevor Daten fließen.", "We sign the NDA before data flows."),
        sentence("Knapp schreiben spart Meetings.", "Writing briefly saves meetings."),
        sentence("Unverbindliche Preise gehören nicht in den Vertrag.", "Non-binding prices do not belong in the contract."),
        sentence("Das Protokoll geht am selben Tag raus.", "The minutes go out the same day."),
        sentence("Wer zuständig ist, steht in Fettdruck.", "Who is responsible is in bold."),
        sentence("Die Kundin hat nachgefasst — zu Recht.", "The client followed up — rightly."),
        sentence("Eskalieren heißt die Chefin informieren, nicht den Chat sprengen.", "To escalate means informing the boss, not blowing up the chat."),
        sentence("Priorisieren wir nach Risiko, nicht nach Lautstärke.", "Let us prioritise by risk, not volume."),
        sentence("Ein Beschluss ohne nächste Aktion ist Dekoration.", "A decision without a next action is decoration."),
        sentence("Die Marge sinkt, wenn wir Rabatt ohne Gegenleistung geben.", "The margin falls if we discount without anything in return."),
        sentence("Bitte die Rechnung an buchhaltung@, nicht an mich privat.", "Please send the invoice to accounts@, not to me privately."),
        sentence("Wirtschaftsdeutsch darf menschlich bleiben, nur nicht vage.", "Business German may stay human, just not vague."),
      ],
      readings: [
        reading(
          "Offer email",
          "Angebotsmail",
          "Betreff: Angebot 24-118, gültig bis 12.04. Sehr geehrte Frau Holm, anbei Leistung, Preis und Zeitplan. Installation KW 19, zwei Schulungen vor Ort. Zahlbar 14 Tage. Das Angebot ist verbindlich, sobald Sie schriftlich zusagen. Rückfragen gerne bis Freitag. Mit freundlichen Grüßen, R. Stein.",
          "Subject: Offer 24-118, valid until 12 April. Dear Ms Holm, attached service, price and schedule. Installation week 19, two on-site trainings. Payable in 14 days. The offer becomes binding once you confirm in writing. Questions welcome until Friday. Kind regards, R. Stein.",
          [
            q("Until when is the offer valid?", "12 April", ["KW 19", "12 April", "Friday only", "No date"]),
            q("When does it become binding?", "On written confirmation", ["When the email is opened", "On written confirmation", "Never", "After a call only"]),
            q("Payment term?", "14 days", ["Immediately cash", "14 days", "A year", "Unstated"]),
          ],
        ),
        reading(
          "Meeting minutes",
          "Kurzprotokoll",
          "Ziel: Lieferverzug klären. Beschluss 1: Kunde heute informieren (Kehl, 16 Uhr). Beschluss 2: alternative Spedition prüfen (Nour, Mittwoch). Kein Beschluss zu Preisnachlass. Nächstes Meeting Donnerstag 9 Uhr, Agenda folgt. Ton im Raum war angespannt, zählt nicht ins Protokoll — außer jemand fordert es.",
          "Goal: clarify delivery delay. Decision 1: inform client today (Kehl, 4 p.m.). Decision 2: check alternative haulier (Nour, Wednesday). No decision on a discount. Next meeting Thursday 9 a.m., agenda to follow. The mood in the room was tense; that does not go in the minutes unless someone demands it.",
          [
            q("Who informs the client?", "Kehl", ["Nour", "Kehl", "Holm", "Nobody"]),
            q("Was a discount decided?", "No", ["Yes, 50%", "No", "Yes, tomorrow", "Only in the mood note"]),
            q("When is the next meeting?", "Thursday 9:00", ["Today 16:00", "Thursday 9:00", "Wednesday all day", "Never"]),
          ],
        ),
        reading(
          "Follow-up that works",
          "Nachfassen",
          "Guten Tag Herr Stein, unsere Frist endet morgen. Ohne Zusage können wir die KW-19-Kapazität nicht halten. Bitte um verbindliche Rückmeldung heute, auch wenn sie negativ ist. Ein Nein jetzt ist besser als ein stilles Ja. Danke und Gruß, Kehl.",
          "Good day Mr Stein, our deadline ends tomorrow. Without confirmation we cannot hold week-19 capacity. Please send a binding reply today, even if it is negative. A no now is better than a silent yes. Thanks and regards, Kehl.",
          [
            q("What cannot be held without a yes?", "Week-19 capacity", ["The whole company", "Week-19 capacity", "The NDA", "The minutes"]),
            q("Is a negative answer acceptable?", "Yes, even preferred to silence", ["No, only yes", "Yes, even preferred to silence", "Only after a year", "Never"]),
            q("When is a reply needed?", "Today", ["Next quarter", "Today", "KW 19 itself", "Never named"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 7-line offer email body.",
          "Schreib eine Angebot-Mail.",
          "Vielen Dank für die Anfrage. Anbei unser Angebot, gültig bis 30.09. Die Leistung umfasst Lieferung und Installation. Zahlbar in 14 Tagen. Bitte um Zusage bis Freitag. Rückfragen gerne. Mit freundlichen Grüßen.",
          ["Validity, service, payment, next step"],
        ),
        writing(
          "Write minutes with two decisions, owners, deadlines.",
          "Schreib ein Mini-Protokoll.",
          "Ziel: Verzug. Beschluss: Kunde informieren (Kehl, heute). Alternative prüfen (Nour, Mittwoch). Nächster Termin: Donnerstag 9 Uhr.",
          ["No mood poetry"],
        ),
      ],
    },
  ),
  chapter(
    "idioms",
    "Idioms, Collocations & Natural Phrasing",
    "Redewendungen, Kollokationen, natürlicher Stil",
    "Spot word partnerships that dictionaries list separately, then use them in context.",
    "vocab",
    [
      "Collocations: eine Entscheidung treffen, nicht *machen. Kritik üben, nicht *tun.",
      "Idioms: learn with a situation, not word by word.",
      "False friends: aktuell ≠ actual, bekommen ≠ become, eventuell ≠ eventually.",
    ],
    {
      vocab: [
        vocab("die Redewendung", "the idiom", undefined, "Redewendungen"),
        vocab("die Kollokation", "the collocation", undefined, "Kollokationen"),
        vocab("eine Entscheidung treffen", "to make a decision"),
        vocab("Kritik üben", "to criticise"),
        vocab("in Betracht ziehen", "to consider"),
        vocab("zur Verfügung stehen", "to be available"),
        vocab("in Frage kommen", "to be an option"),
        vocab("auf etwas ankommen", "to depend on / matter"),
        vocab("den Nagel auf den Kopf treffen", "to hit the nail on the head"),
        vocab("um den heißen Brei reden", "to beat about the bush"),
        vocab("ins kalte Wasser springen", "to jump in at the deep end"),
        vocab("die Kirche im Dorf lassen", "to not overdo it / keep perspective"),
        vocab("zwei Fliegen mit einer Klappe schlagen", "to kill two birds with one stone"),
        vocab("auf der Hand liegen", "to be obvious"),
        vocab("Hand und Fuß haben", "to make sense / be sound"),
        vocab("nicht die hellste Kerze", "not the brightest spark (rude)"),
        vocab("aktuell", "current (false friend of actual)"),
        vocab("eventuell", "possibly (false friend of eventually)"),
        vocab("bekommen", "to get (false friend of become)"),
        vocab("sensibel", "sensitive"),
        vocab("das Fazit", "the conclusion"),
        vocab("im Großen und Ganzen", "on the whole"),
        vocab("Schritt für Schritt", "step by step"),
        vocab("auf lange Sicht", "in the long run"),
        vocab("kurzfristig", "in the short term"),
        vocab("den Faden verlieren", "to lose the thread"),
        vocab("zur Sache kommen", "to get to the point"),
        vocab("das Eis brechen", "to break the ice"),
        vocab("unter vier Augen", "in private"),
        vocab("reinen Tisch machen", "to wipe the slate clean"),
        vocab("über den Tellerrand schauen", "to think outside the box"),
        vocab("die Daumen drücken", "to keep one's fingers crossed"),
      ],
      phrases: [
        phrase("Lass uns zur Sache kommen.", "Let's get to the point."),
        phrase("Im Großen und Ganzen klappt der Plan.", "On the whole the plan works."),
        phrase("Es liegt auf der Hand, dass wir Personal brauchen.", "It is obvious that we need staff."),
        phrase("Dein Vorschlag hat Hand und Fuß.", "Your proposal makes sense."),
        phrase("Wir sollten die Kirche im Dorf lassen.", "We shouldn't overdo it."),
        phrase("Damit schlagen wir zwei Fliegen mit einer Klappe.", "That way we kill two birds with one stone."),
        phrase("Ich will nicht um den heißen Brei reden.", "I don't want to beat about the bush."),
        phrase("Eventuell schaffen wir es morgen — nicht: eventually.", "We might manage tomorrow — not “eventually”."),
        phrase("Aktuell fehlen Daten, nicht „actual data“ als Übersetzung.", "Currently data are missing, not “actual” as a translation."),
        phrase("Unter vier Augen: der Ton war zu hart.", "In private: the tone was too harsh."),
        phrase("Ich drücke dir die Daumen für die Prüfung.", "I'll keep my fingers crossed for the exam."),
        phrase("Komm zum Punkt, sonst verlieren wir den Faden.", "Get to the point or we'll lose the thread."),
      ],
      sentences: [
        sentence("Wir müssen eine Entscheidung treffen, nicht nur diskutieren.", "We have to make a decision, not only discuss."),
        sentence("Kritik üben Sie bitte konkret.", "Please criticise specifically."),
        sentence("Kommt ein späterer Termin in Frage?", "Is a later appointment an option?"),
        sentence("Es kommt darauf an, wie viel Zeit wir haben.", "It depends how much time we have."),
        sentence("Du hast den Nagel auf den Kopf getroffen.", "You hit the nail on the head."),
        sentence("Manchmal muss man ins kalte Wasser springen.", "Sometimes you have to jump in at the deep end."),
        sentence("Auf lange Sicht lohnt sich die Bahnkarte.", "In the long run the railcard pays off."),
        sentence("Kurzfristig ist das Auto bequemer.", "In the short term the car is more convenient."),
        sentence("Schritt für Schritt wird der Text klarer.", "Step by step the text becomes clearer."),
        sentence("Ein Fazit ohne Beleg ist nur Stimmung.", "A conclusion without evidence is only mood."),
        sentence("Über den Tellerrand schauen heißt andere Abteilungen fragen.", "Thinking outside the box means asking other departments."),
        sentence("Wir machen reinen Tisch und listen die Fehler.", "We wipe the slate clean and list the errors."),
        sentence("Smalltalk bricht das Eis, dann kommt die Agenda.", "Small talk breaks the ice, then comes the agenda."),
        sentence("Ich habe den Job bekommen, ich bin nicht „become“ den Job.", "I got the job; I did not “become” the job."),
        sentence("Sensibel auf Kritik reagieren ist menschlich.", "Reacting sensitively to criticism is human."),
        sentence("Zur Verfügung stehen zwei Räume.", "Two rooms are available."),
        sentence("Ziehen Sie einen Plan B in Betracht.", "Consider a plan B."),
        sentence("Natürliches Deutsch klingt nach Kollokation, nicht nach Wort-für-Wort.", "Natural German sounds like collocation, not word-for-word."),
      ],
      readings: [
        reading(
          "False-friend trap",
          "False-Friend-Falle",
          "Ein Praktikant schrieb: „Eventuell we will finish eventually.“ Gemeint war: Wir schaffen es möglicherweise morgen. „Eventually“ heißt schließlich, nicht eventuell. „Aktuell“ ist current. „Bekommen“ ist get. Wer Kollokationen lernt, fällt seltener in solche Löcher. Fazit: Kontexte sammeln, nicht Einzelwörter.",
          "An intern wrote a mix-up of eventuell and eventually. What was meant: we might manage tomorrow. Eventually means finally, not possibly. Aktuell is current. Bekommen is get. Anyone who learns collocations falls into such holes less often. Conclusion: collect contexts, not isolated words.",
          [
            q("What does German eventuell mean?", "Possibly", ["Finally", "Possibly", "Never", "Actually"]),
            q("What does bekommen mean here?", "To get", ["To become", "To get", "To begin", "To bake"]),
            q("What should learners collect?", "Contexts", ["Only gender tables", "Contexts", "English calques", "No verbs"]),
          ],
        ),
        reading(
          "Meeting, natural tone",
          "Meeting, natürlicher Ton",
          "„Lasst uns nicht um den heißen Brei reden. Es liegt auf der Hand: ohne Budget kein Start. Dein Plan hat Hand und Fuß, aber wir sollten die Kirche im Dorf lassen. Zwei Fliegen: wir kürzen das Nice-to-have und halten den Termin. Einverstanden?“ So klingt gesprochenes B2, nicht Lehrbuchglätte.",
          "“Let's not beat about the bush. It's obvious: no budget, no start. Your plan makes sense, but let's not overdo it. Two birds: we cut the nice-to-have and keep the date. Agreed?” That is spoken B2, not textbook smoothness.",
          [
            q("What is obvious?", "No budget, no start", ["The weather", "No budget, no start", "A party", "A poem"]),
            q("What two things are combined?", "Cut extras and keep the date", ["Two lunches", "Cut extras and keep the date", "Two languages", "Two bosses"]),
            q("Should they overdo the plan?", "No", ["Yes, double it", "No", "Only at night", "The text is silent"]),
          ],
        ),
        reading(
          "Idiom warning",
          "Redewendungs-Warnung",
          "„Nicht die hellste Kerze“ ist verletzend. Im Berufsleben lieber: Der Vorschlag ist noch unklar. Idiome sind Werkzeuge, keine Waffen. Unter vier Augen darf Humor wärmer sein. Öffentlich bleibt man bei Kollokationen, die Hand und Fuß haben. Wer den Faden verliert, fasst zusammen statt zu beleidigen.",
          "“Not the brightest spark” is hurtful. At work better: the proposal is still unclear. Idioms are tools, not weapons. In private humour may be warmer. In public you stay with collocations that make sense. Anyone who loses the thread summarises instead of insulting.",
          [
            q("Is the candle idiom appropriate at work?", "No, it is insulting", ["Yes, always funny", "No, it is insulting", "Required in C1", "Only in emails"]),
            q("What to do if you lose the thread?", "Summarise", ["Insult", "Summarise", "Leave forever", "Switch to English"]),
            q("Where may humour be warmer?", "In private", ["In the press release", "In private", "In the contract", "Never"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Use five collocations in a short paragraph.",
          "Schreib einen Absatz mit fünf Kollokationen.",
          "Wir müssen eine Entscheidung treffen. Ein späterer Start kommt in Frage. Es kommt darauf an, ob Kapazität zur Verfügung steht. Kritik üben wir konkret. Im Großen und Ganzen hält der Plan.",
          ["No word-for-word English"],
        ),
        writing(
          "Replace three false friends in a messy sentence.",
          "Korrigiere False Friends.",
          "Eventuell schaffen wir es später. Aktuell fehlen Daten. Ich habe die Mail bekommen.",
          ["eventuell / aktuell / bekommen"],
        ),
      ],
    },
  ),
  chapter(
    "editorials",
    "Reading Editorials & Argument Structure",
    "Leitartikel und Argumentstruktur lesen",
    "Map claim, evidence, counterargument, and punchline in opinion pieces.",
    "reading",
    [
      "Typical arc: scene → thesis → evidence → concession → punch.",
      "Watch loaded adjectives; ask what would change if they vanished.",
      "Separate the author's demand from the examples.",
    ],
    {
      vocab: [
        vocab("der Leitartikel", "the editorial", undefined, "Leitartikel"),
        vocab("die These", "the thesis", undefined, "Thesen"),
        vocab("das Argument", "the argument"),
        vocab("das Gegenargument", "the counterargument", undefined, "Gegenargumente"),
        vocab("das Zugeständnis", "the concession", undefined, "Zugeständnisse"),
        vocab("die Pointe", "the punchline"),
        vocab("die Forderung", "the demand"),
        vocab("das Beispiel", "the example"),
        vocab("die Evidenz", "the evidence"),
        vocab("polemisch", "polemical"),
        vocab("sachlich", "sober / factual"),
        vocab("suggestiv", "leading / suggestive"),
        vocab("die Metapher", "the metaphor"),
        vocab("der Rahmen", "the frame", undefined, "Rahmen"),
        vocab("framen", "to frame"),
        vocab("zuspitzen", "to sharpen / polarise"),
        vocab("relativieren", "to qualify"),
        vocab("die Leserschaft", "the readership"),
        vocab("der Appell", "the appeal", undefined, "Appelle"),
        vocab("implizit", "implicit"),
        vocab("explizit", "explicit"),
        vocab("widersprüchlich", "contradictory"),
        vocab("schlüssig", "coherent"),
        vocab("die Prämisse", "the premise", undefined, "Prämissen"),
        vocab("folgen", "to follow (logically)"),
        vocab("nicht folgen", "not to follow"),
        vocab("die Analogie", "the analogy", undefined, "Analogien"),
        vocab("hinken", "to limp (of analogies)"),
        vocab("die Schlusspointe", "the closing barb"),
        vocab("unterkomplex", "oversimplified"),
        vocab("überzeugend", "convincing"),
        vocab("ärgerlich", "annoying"),
      ],
      phrases: [
        phrase("Die These steht erst im dritten Absatz.", "The thesis only appears in the third paragraph."),
        phrase("Das Zugeständnis kommt, damit die Forderung härter wirkt.", "The concession comes so the demand hits harder."),
        phrase("Ohne Evidenz bleibt der Appell Moral.", "Without evidence the appeal remains moralising."),
        phrase("Die Analogie hinkt, weil Städte keine Familien sind.", "The analogy limps because cities are not families."),
        phrase("Suggestive Fragen sind keine Belege.", "Leading questions are not evidence."),
        phrase("Was explizit gefordert wird, ist ein Tempolimit — implizit eine Haltung.", "What is explicitly demanded is a speed limit — implicitly an attitude."),
        phrase("Polemik unterhält, überzeugt selten Unentschlossene.", "Polemic entertains, rarely convinces the undecided."),
        phrase("Schlüssig ist der Text nur, wenn die Prämisse stimmt.", "The text is only coherent if the premise holds."),
        phrase("Der Rahmen „Wir gegen die da oben“ vereinfacht unterkomplex.", "The frame “us versus those at the top” oversimplifies."),
        phrase("Die Pointe wiederholt die These in einem Bild.", "The punchline repeats the thesis in an image."),
        phrase("Ein Gegenargument ernst zu nehmen, stärkt den Text.", "Taking a counterargument seriously strengthens the text."),
        phrase("Ärgerlich, aber ehrlich: der Schluss predigen, die Mitte schweigt.", "Annoying but honest: the ending preaches, the middle stays silent."),
      ],
      sentences: [
        sentence("Zuerst kommt eine Szene im Bahnhof, dann die These zur Pünktlichkeit.", "First a station scene, then the thesis on punctuality."),
        sentence("Die Evidenz besteht aus einer Zahl und einer Anekdote.", "The evidence consists of one figure and one anecdote."),
        sentence("Das Gegenargument wird genannt und sofort entkräftet.", "The counterargument is named and immediately defused."),
        sentence("Relativieren in Satz zwei, zuspitzen in Satz zehn.", "Qualify in sentence two, sharpen in sentence ten."),
        sentence("Die Leserschaft wird als „wir“ angesprochen, Gegner als „man“.", "The readership is addressed as “we”, opponents as “one”."),
        sentence("Eine hinkende Analogie erkennt man, wenn man sie wörtlich nimmt.", "You spot a limping analogy when you take it literally."),
        sentence("Implizite Werte stecken in den Adjektiven „reif“ und „naiv“.", "Implicit values sit in the adjectives “mature” and “naive”."),
        sentence("Folgt aus höheren Preisen wirklich weniger Verkehr? Nicht automatisch.", "Do higher prices really mean less traffic? Not automatically."),
        sentence("Ein überzeugender Leitartikel zeigt die Kosten der eigenen Forderung.", "A convincing editorial shows the cost of its own demand."),
        sentence("Widersprüchlich ist, Freiheit zu fordern und Kritik zu scheuen.", "It is contradictory to demand freedom and shun criticism."),
        sentence("Der Rahmen bestimmt, welche Beispiele überhaupt erscheinen.", "The frame decides which examples appear at all."),
        sentence("Sachlich heißt nicht langweilig, nur ohne Gift.", "Sober does not mean boring, only without venom."),
        sentence("Die Pointe darf überraschen, nicht die Fakten ersetzen.", "The punchline may surprise, not replace the facts."),
        sentence("Unterkomplexe Sätze gewinnen Klicks und verlieren Leser von morgen.", "Oversimplified sentences win clicks and lose tomorrow's readers."),
        sentence("Wer die Prämisse angreift, trifft den Text tiefer als wer an Stil nörgelt.", "Anyone who attacks the premise hits the text deeper than anyone who niggles at style."),
        sentence("Ein Appell ohne Adressat verpufft.", "An appeal without an addressee fizzles out."),
        sentence("Explizit steht wenig über Geld, implizit sehr viel.", "Explicitly little is said about money, implicitly a great deal."),
        sentence("Gute Leser notieren These, Beleg, Lücke.", "Good readers note thesis, evidence, gap."),
      ],
      readings: [
        reading(
          "Editorial skeleton",
          "Leitartikel-Gerüst",
          "Szene: Ein Kind wartet im Regen auf den Bus. These: Abendlinien sind Daseinsvorsorge, kein Luxus. Zahl: 12 Prozent der Schicht beginnen nach 21 Uhr. Zugeständnis: Leere Busse kosten. Trotzdem: Teilhabe. Pointe: Wer den letzten Bus streicht, löscht keine Linie, sondern Feierabend. Die Forderung: Takt halten, nicht Moral predigen.",
          "Scene: A child waits in the rain for the bus. Thesis: Evening lines are basic public service, not luxury. Figure: 12 percent of shifts start after 9 p.m. Concession: Empty buses cost money. Still: participation. Punchline: Anyone who cuts the last bus does not delete a line but an evening off. Demand: keep the frequency, don't preach morals.",
          [
            q("What is the thesis?", "Evening buses are basic public service", ["Buses are luxury", "Evening buses are basic public service", "Children should walk", "Rain is good"]),
            q("What figure is used?", "12% of shifts after 21:00", ["12 buses", "12% of shifts after 21:00", "21 percent empty", "No figure"]),
            q("What is demanded?", "Keep the frequency", ["Preach more", "Keep the frequency", "Cancel all buses", "Higher ticket art"]),
          ],
        ),
        reading(
          "A weak counter",
          "Schwaches Gegenargument",
          "„Wer will, kauft ein Auto.“ Das entkräftet die These nicht, weil ein Auto Geld, Führerschein und Parkraum voraussetzt. Die Analogie „Bus wie Taxi“ hinkt. Ein besseres Gegenargument wäre: Nachtarbeit nehmen wir ernst, aber der Takt um 3 Uhr überfordert die Kommune. Dann müsste der Text die Grenze nennen.",
          "“Anyone who wants to can buy a car.” That does not defuse the thesis, because a car presupposes money, a licence and parking. The analogy “bus like taxi” limps. A better counter would be: we take night work seriously, but a 3 a.m. service overstretches the municipality. Then the text would have to name the limit.",
          [
            q("Why does “buy a car” fail?", "It assumes money, licence, parking", ["Cars are illegal", "It assumes money, licence, parking", "Nobody works nights", "Buses are free"]),
            q("What better counter is suggested?", "3 a.m. service overstretches the town", ["Ban night work", "3 a.m. service overstretches the town", "Delete the thesis", "Only taxis"]),
            q("Does “bus like taxi” work?", "No, it limps", ["Yes, perfectly", "No, it limps", "It's a law", "Unmentioned"]),
          ],
        ),
        reading(
          "Loaded adjectives",
          "Geladene Adjektive",
          "Streiche „naiv“, „reif“, „endlich“. Bleibt der Satz stehen? Oft ja, und er wird ehrlicher. Suggestive Wörter framens die Gegner als Kinder. Das unterhält die eigene Leserschaft. Unentschlossene merken das und gehen. Überzeugend ist, Kosten der eigenen Seite zu zeigen.",
          "Delete “naive”, “mature”, “at last”. Does the sentence still stand? Often yes, and it becomes more honest. Suggestive words frame opponents as children. That entertains one's own readership. The undecided notice and leave. What convinces is showing the costs on one's own side.",
          [
            q("What happens if you drop loaded adjectives?", "The sentence often still stands and is more honest", ["The text dies", "The sentence often still stands and is more honest", "Grammar breaks", "It's illegal"]),
            q("Whom do such words entertain?", "The existing readership", ["Opponents", "The existing readership", "Children only", "Nobody"]),
            q("What actually convinces?", "Showing one's own costs", ["More insults", "Showing one's own costs", "Longer headlines", "No figures"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Outline an editorial in five labelled parts.",
          "Skizziere einen Leitartikel in fünf Teilen.",
          "Szene: … These: … Beleg: … Zugeständnis: … Forderung: …",
          ["One sentence each", "Name a cost of your demand"],
        ),
        writing(
          "Rewrite a polemical sentence as a sober one.",
          "Mach einen polemischen Satz sachlich.",
          "Statt „naive Stadträte töten den Abend“: „Wenn die letzte Linie entfällt, kommen Schichtarbeiter schlechter nach Hause.“",
          ["Keep the claim", "Drop the insult"],
        ),
      ],
    },
  ),
  chapter(
    "essay-writing",
    "Writing Argumentative Essays",
    "Erörterungen und Essays schreiben",
    "Plan, paragraph, and conclude without repeating the introduction.",
    "writing",
    [
      "Einleitung: Kontext + These. Hauptteil: Argument, Beispiel, Mini-Schluss. Ende: Weitung oder Grenze, keine Kopie.",
      "Connectors: darüber hinaus, im Gegensatz dazu, folglich, gleichwohl.",
      "One idea per paragraph. Topic sentence first.",
    ],
    {
      vocab: [
        vocab("die Erörterung", "the discursive essay", undefined, "Erörterungen"),
        vocab("der Essay", "the essay", undefined, "Essays"),
        vocab("die Gliederung", "the outline", undefined, "Gliederungen"),
        vocab("die Einleitung", "the introduction"),
        vocab("der Hauptteil", "the main part"),
        vocab("der Schluss", "the conclusion"),
        vocab("die These", "the thesis"),
        vocab("das Themawort", "the topic sentence", undefined, "Themawörter"),
        vocab("der Absatz", "the paragraph"),
        vocab("überleiten", "to transition"),
        vocab("darüber hinaus", "furthermore"),
        vocab("im Gegensatz dazu", "in contrast"),
        vocab("folglich", "consequently"),
        vocab("gleichwohl", "nevertheless"),
        vocab("einerseits", "on the one hand"),
        vocab("andererseits", "on the other hand"),
        vocab("zusammenfassend", "in summary"),
        vocab("abschließend", "in closing"),
        vocab("vertiefen", "to go deeper"),
        vocab("abschweifen", "to digress"),
        vocab("die Redundanz", "redundancy"),
        vocab("präzise", "precise"),
        vocab("vage", "vague"),
        vocab("der Leserleitfaden", "signposting for the reader"),
        vocab("die Weitung", "the widening (of the ending)"),
        vocab("die Grenze", "the limit"),
        vocab("das Stilmittel", "the stylistic device", undefined, "Stilmittel"),
        vocab("sachlich", "sober"),
        vocab("lebendig", "lively"),
        vocab("belegen", "to evidence"),
        vocab("gewichten", "to weigh"),
        vocab("die Fragestellung", "the question posed"),
      ],
      phrases: [
        phrase("Im Folgenden zeige ich, warum der Takt wichtiger ist als die Linie auf der Karte.", "In what follows I show why frequency matters more than the line on the map."),
        phrase("Ein erster Einwand lautet, leere Busse seien Verschwendung.", "A first objection is that empty buses are waste."),
        phrase("Dagegen spricht die Schichtarbeit in der Industriezone.", "Against that speaks shift work in the industrial zone."),
        phrase("Darüber hinaus sinkt ohne Abendbus die Teilhabe.", "Furthermore, without an evening bus participation falls."),
        phrase("Im Gegensatz zu Taxi-Apps ist der Bus kalkulierbar.", "In contrast to taxi apps the bus is calculable."),
        phrase("Folglich sollte die Kommune den Takt halten.", "Consequently the municipality should keep the frequency."),
        phrase("Gleichwohl braucht jede Forderung eine Kostengrenze.", "Nevertheless every demand needs a cost limit."),
        phrase("Abschließend: nicht Moral, sondern Minuten.", "In closing: not morals but minutes."),
        phrase("Die Fragestellung ist nicht „Bus ja/nein“, sondern „wann“.", "The question is not bus yes/no but when."),
        phrase("Zusammenfassend gewichte ich Teilhabe höher als maximale Auslastung.", "In summary I weigh participation higher than maximum occupancy."),
        phrase("Ein lebendiges Beispiel öffnet den Absatz, eine Zahl schließt ihn.", "A lively example opens the paragraph, a figure closes it."),
        phrase("Vage Wörter wie „manche“ ersetze ich durch Gruppen.", "I replace vague words like “some” with groups."),
      ],
      sentences: [
        sentence("Die Gliederung steht, bevor der erste schöne Satz kommt.", "The outline exists before the first pretty sentence."),
        sentence("Wer abschweift, streicht den Absatz oder hängt ihn an den Schluss.", "Anyone who digresses either cuts the paragraph or moves it to the end."),
        sentence("Redundanz entsteht, wenn Einleitung und Schluss dieselben drei Wörter tragen.", "Redundancy appears when intro and ending carry the same three words."),
        sentence("Präzise Verben ersetzen Ketten aus ist und hat.", "Precise verbs replace chains of is and has."),
        sentence("Ein Leserleitfaden darf trocken sein: erst Kosten, dann Nutzen.", "Signposting may be dry: first costs, then benefits."),
        sentence("Die Weitung am Ende öffnet eine neue Frage, löst sie aber nicht.", "The widening at the end opens a new question but does not solve it."),
        sentence("Grenzen nennen macht den Essay erwachsen.", "Naming limits makes the essay mature."),
        sentence("Stilmittel sparsam: eine Metapher trägt mehr als fünf.", "Stylistic devices sparingly: one metaphor carries more than five."),
        sentence("Sachlich und lebendig schließen sich nicht aus.", "Sober and lively are not opposites."),
        sentence("Gewichten heißt, ein Argument länger zu machen als das andere.", "To weigh means making one argument longer than the other."),
        sentence("Belegen Sie Zahlen mit Jahr und Quelle in Klammern, wenn möglich.", "Evidence figures with year and source in brackets if possible."),
        sentence("Themawort zuerst: „Leere Busse sind ein Kostenproblem.“ Dann das Beispiel.", "Topic sentence first: “Empty buses are a cost problem.” Then the example."),
        sentence("Überleiten mit einem Wort aus dem vorigen Absatz.", "Transition with a word from the previous paragraph."),
        sentence("Vertiefen statt wiederholen: dieselbe These, neue Ebene.", "Go deeper rather than repeat: same thesis, new layer."),
        sentence("Ein Essay ohne Fragestellung ist ein Tagebuch.", "An essay without a posed question is a diary."),
        sentence("Andererseits-Absätze brauchen ein ebenso starkes Einerseits.", "On-the-other-hand paragraphs need an equally strong on-the-one-hand."),
        sentence("Der Hauptteil hat drei Absätze, nicht dreizehn Mini-Meinungen.", "The main part has three paragraphs, not thirteen mini-opinions."),
        sentence("Schluss ohne Kopie: eine Grenze, eine offene Frage, ein konkreter nächster Schritt.", "Ending without copy: a limit, an open question, a concrete next step."),
      ],
      readings: [
        reading(
          "Model paragraph",
          "Musterabsatz",
          "Leere Busse sind ein Kostenproblem, kein Beweis gegen Abendlinien. In der Industriezone beginnen 12 Prozent der Schichten nach 21 Uhr. Ein Taxi ersetzt den Takt nicht, weil der Preis schwankt. Folglich ist Auslastung um 22 Uhr die falsche Messlatte. Gleichwohl sollte die Kommune nach 0 Uhr den Takt strecken, nicht streichen.",
          "Empty buses are a cost problem, not proof against evening lines. In the industrial zone 12 percent of shifts start after 9 p.m. A taxi does not replace the frequency because the price fluctuates. Consequently occupancy at 10 p.m. is the wrong yardstick. Nevertheless the municipality should stretch the frequency after midnight, not scrap it.",
          [
            q("What is empty occupancy NOT proof of?", "That evening lines are useless", ["That costs exist", "That evening lines are useless", "That taxis are free", "That nobody works"]),
            q("What happens after midnight in the model?", "Stretch frequency, don't scrap", ["More buses than at noon", "Stretch frequency, don't scrap", "Only taxis legally", "No comment"]),
            q("Why not taxis as a full replacement?", "Price fluctuates", ["No cars exist", "Price fluctuates", "They are slower always", "Illegal"]),
          ],
        ),
        reading(
          "Bad ending vs better ending",
          "Schlechter vs besserer Schluss",
          "Schlecht: „Also sind Busse wichtig, wie schon gesagt.“ Besser: „Die Grenze meiner These ist die Zeit nach Mitternacht. Offen bleibt, wie man Schichtpläne und Takt gemeinsam plant. Nächster Schritt: eine Zahl der Industrie, nicht nur ein Kind im Regen.“ Der zweite Schluss weitet und begrenzt.",
          "Bad: “So buses are important, as already said.” Better: “The limit of my thesis is the time after midnight. What remains open is how to plan shift rotas and frequency together. Next step: a figure from industry, not only a child in the rain.” The second ending widens and limits.",
          [
            q("What is wrong with the first ending?", "It only copies the intro", ["Too many figures", "It only copies the intro", "It's in English", "No verbs"]),
            q("What limit is named?", "After midnight", ["Morning peak", "After midnight", "Weekends only", "No limit"]),
            q("What next step is proposed?", "An industry figure", ["Another rain scene", "An industry figure", "Delete buses", "A poem"]),
          ],
        ),
        reading(
          "Signposting",
          "Leserleitfaden",
          "Einleitung: Kontext Regen, These Takt. Absatz 1 Kosten. Absatz 2 Schichtarbeit. Absatz 3 Grenze Mitternacht. Schluss: gemeinsame Planung. Wer das oben in drei Zeilen skizziert, schreibt unten weniger durcheinander. Gliederung ist Freundlichkeit gegenüber der Leserin.",
          "Intro: rain context, frequency thesis. Paragraph 1 costs. Paragraph 2 shift work. Paragraph 3 midnight limit. Ending: joint planning. Anyone who sketches that in three lines at the top writes less messily below. An outline is kindness to the reader.",
          [
            q("What is paragraph 2 about?", "Shift work", ["Rain only", "Shift work", "Poetry", "Taxis exclusively"]),
            q("What is an outline called here?", "Kindness to the reader", ["A waste of time", "Kindness to the reader", "A legal duty", "Decoration"]),
            q("Where is the midnight limit?", "Paragraph 3", ["Intro only", "Paragraph 3", "Never", "The title"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a full mini-essay (intro, 3 short paragraphs, ending) on evening buses.",
          "Schreib eine Mini-Erörterung.",
          "Kontext + These. Absatz Kosten. Absatz Schicht. Absatz Grenze. Schluss mit nächstem Schritt, ohne die Einleitung zu kopieren.",
          ["Topic sentences", "One concession", "No copied ending"],
        ),
        writing(
          "Write three transition sentences using darüber hinaus / im Gegensatz dazu / gleichwohl.",
          "Schreib drei Überleitungen.",
          "Darüber hinaus sinkt die Teilhabe. Im Gegensatz dazu ist das Taxi unkalkulierbar. Gleichwohl braucht jede Linie eine Nachtgrenze.",
          ["Do not start all three with und"],
        ),
      ],
    },
  ),
  chapter(
    "debate",
    "Debating & Persuasion under Time Pressure",
    "Debattieren und Überzeugen unter Zeitdruck",
    "Listen for the clash, concede fast, and strike with one example.",
    "mixed",
    [
      "Clash: where exactly do you disagree? Definition, cause, or solution?",
      "Rebuttal: repeat their point fairly, then limit it.",
      "Time pressure: one example beats three adjectives.",
    ],
    {
      vocab: [
        vocab("die Debatte", "the debate"),
        vocab("die Definition", "the definition", undefined, "Definitionen"),
        vocab("der Clash", "the clash / point of collision"),
        vocab("entkräften", "to rebut / defuse"),
        vocab("zugestehen", "to concede"),
        vocab("zuspitzen", "to sharpen"),
        vocab("die Redezeit", "speaking time"),
        vocab("das Beispiel", "the example"),
        vocab("die Zahl", "the figure"),
        vocab("der Vergleich", "the comparison"),
        vocab("unfair", "unfair"),
        vocab("Strohmann", "straw man"),
        vocab("die Evidenz", "evidence"),
        vocab("die Lösung", "the solution"),
        vocab("die Ursache", "the cause"),
        vocab("priorisieren", "to prioritise"),
        vocab("die Jury", "the jury", undefined, "Jurys"),
        vocab("überzeugen", "to persuade"),
        vocab("gewinnen", "to win"),
        vocab("verlieren", "to lose"),
        vocab("fair", "fair"),
        vocab("knapp", "concise"),
        vocab("wiederholen", "to repeat"),
        vocab("zusammenfassen", "to summarise"),
        vocab("die Schlussrede", "the closing speech", undefined, "Schlussreden"),
        vocab("der Punkt", "the point", undefined, "Punkte"),
        vocab("treffen", "to hit (the point)"),
        vocab("ausweichen", "to dodge"),
        vocab("nachhaken", "to follow up / press"),
        vocab("die Regel", "the rule"),
        vocab("respektvoll", "respectful"),
        vocab("bestimmt", "firm"),
      ],
      phrases: [
        phrase("Unser Dissens liegt nicht bei den Kosten, sondern bei der Messung.", "Our disagreement is not about costs but about the metric."),
        phrase("Ich gestehe die leeren Sitze zu — sie beweisen nicht die Nutzlosigkeit.", "I concede the empty seats — they do not prove uselessness."),
        phrase("Wenn wir „nötig“ als „volle Busse“ definieren, haben Sie schon gewonnen. Das tun wir nicht.", "If we define “necessary” as “full buses”, you have already won. We do not."),
        phrase("Ein Beispiel: die Schicht um 21:30 in der Industriezone.", "One example: the 9:30 p.m. shift in the industrial zone."),
        phrase("Bitte kein Strohmann: niemand fordert Busse im Minutentakt um 3 Uhr.", "No straw man: nobody is demanding buses every minute at 3 a.m."),
        phrase("In 30 Sekunden: Takt halten, nach Mitternacht strecken.", "In 30 seconds: keep the frequency, stretch it after midnight."),
        phrase("Sie weichen auf Moral aus; ich bleibe bei Minuten.", "You dodge into morals; I stay with minutes."),
        phrase("Nachhaken: Welche Zahl genau macht eine Linie „leer“?", "Press: which exact figure makes a line “empty”?"),
        phrase("Fair wiederholt: Sie sagen, Geld sei knapp. Einverstanden. Priorisieren wir Teilhabe.", "Fair repeat: you say money is tight. Agreed. Let us prioritise participation."),
        phrase("Die Schlussrede nennt Clash, Zugeständnis, Forderung.", "The closing speech names clash, concession, demand."),
        phrase("Bestimmt, nicht laut.", "Firm, not loud."),
        phrase("Wer gewinnt, ist weniger wichtig als wer klarer misst.", "Who wins matters less than who measures more clearly."),
      ],
      sentences: [
        sentence("Definitionen entscheiden Debatten, bevor Beispiele kommen.", "Definitions decide debates before examples arrive."),
        sentence("Ein Strohmann macht das Publikum misstrauisch.", "A straw man makes the audience suspicious."),
        sentence("Redezeit spart, wer nicht die Einleitung noch einmal liest.", "Anyone who does not reread the introduction saves speaking time."),
        sentence("Zahlen ohne Quelle sind in einer Jury-Debatte schwach.", "Figures without source are weak in a judged debate."),
        sentence("Vergleiche müssen die gleiche Einheit nutzen: Minuten, nicht Stimmungen.", "Comparisons must use the same unit: minutes, not moods."),
        sentence("Entkräften heißt nicht beleidigen.", "To rebut is not to insult."),
        sentence("Zugestehen macht die eigene Grenze sichtbar und stark.", "Conceding makes your own limit visible and strong."),
        sentence("Zuspitzen ohne Beispiel ist nur Adrenalin.", "Sharpening without an example is only adrenaline."),
        sentence("Respektvoll bleiben schützt die eigene Glaubwürdigkeit.", "Staying respectful protects your own credibility."),
        sentence("Ausweichen erkennt man an neuen Themen statt Antworten.", "Dodging is visible in new topics instead of answers."),
        sentence("Nachhaken Sie einmal, nicht fünfmal dasselbe.", "Press once, not the same thing five times."),
        sentence("Die Regel „eine Idee, ein Beleg“ gilt auch mündlich.", "The rule “one idea, one piece of evidence” holds in speech too."),
        sentence("Knappheit ist eine Tugend, wenn der Clash klar ist.", "Concision is a virtue when the clash is clear."),
        sentence("Lösungen ohne Ursachenanalyse kommen zurück als dasselbe Problem.", "Solutions without cause analysis return as the same problem."),
        sentence("Priorisieren Sie drei Punkte; der vierte fällt.", "Prioritise three points; the fourth drops."),
        sentence("Gewinnen ohne Fairness ist ein teurer Sieg.", "Winning without fairness is an expensive victory."),
        sentence("Verlieren mit einem klaren Clash ist besser als Nebel.", "Losing with a clear clash is better than fog."),
        sentence("Überzeugen heißt, der anderen Seite einen Satz zu leihen, der stimmt.", "To persuade is to lend the other side a sentence that is true."),
      ],
      readings: [
        reading(
          "Opening 45 seconds",
          "Einstieg 45 Sekunden",
          "Clash: nicht ob Busse Geld kosten — das tun sie — sondern ob Auslastung um 22 Uhr die richtige Messlatte ist. Zugeständnis: nach Mitternacht darf der Takt sinken. Beispiel: Schicht 21:30, Industriezone, 12 Prozent. Forderung: Abendlinie halten. Rest der Redezeit für Zahlen der Gegenseite, nicht für Wetter.",
          "Clash: not whether buses cost money — they do — but whether occupancy at 10 p.m. is the right yardstick. Concession: after midnight frequency may fall. Example: 9:30 p.m. shift, industrial zone, 12 percent. Demand: keep the evening line. Remaining time for the other side's figures, not weather.",
          [
            q("What is NOT the clash?", "Whether buses cost money", ["The metric at 22:00", "Whether buses cost money", "The 21:30 shift", "The demand to keep the line"]),
            q("What may fall after midnight?", "Frequency", ["All democracy", "Frequency", "The example", "Honesty"]),
            q("What should remaining time be for?", "The other side's figures", ["Weather talk", "The other side's figures", "Insults", "A poem"]),
          ],
        ),
        reading(
          "Rebuttal",
          "Entkräftung",
          "Sie sagen, wer will, kauft ein Auto. Fair wiederholt: individuelle Mobilität als Ersatz. Grenze: Führerschein, Geld, Parken, Schichtbeginn. Strohmann wäre: wir wollten Limousinen für alle. Tun wir nicht. Nachhaken: Welche Auslastung genau ist Ihr Cut-off — 10 Prozent, 30, 50? Ohne Zahl bleibt „leer“ ein Gefühl.",
          "You say anyone who wants to can buy a car. Fair repeat: individual mobility as a substitute. Limit: licence, money, parking, shift start. A straw man would be: we wanted limousines for all. We do not. Press: which occupancy exactly is your cut-off — 10 percent, 30, 50? Without a figure, “empty” remains a feeling.",
          [
            q("What limit is put on the car argument?", "Licence, money, parking, shift start", ["No cars exist", "Licence, money, parking, shift start", "Buses are free", "Night is illegal"]),
            q("What would be a straw man?", "Claiming they want limousines for all", ["Asking for a figure", "Claiming they want limousines for all", "Conceding costs", "Keeping the evening line"]),
            q("What is “empty” without a number?", "A feeling", ["A law", "A feeling", "A bus type", "A victory"]),
          ],
        ),
        reading(
          "Closing",
          "Schlussrede",
          "Clash gehalten: Messlatte. Zugeständnis gehalten: nach 0 Uhr strecken. Ein Beispiel gehalten: 21:30. Bitte nicht gewinnen mit Lautstärke. Gewinnen mit einer Zahl, die beide Seiten teilen können. Wenn die Jury nur Stimmung hört, haben wir beide verloren — auch wer „siegt“.",
          "Clash held: yardstick. Concession held: stretch after midnight. One example held: 9:30 p.m. Please do not win on volume. Win with a figure both sides can share. If the jury only hears mood, we have both lost — including the “winner”.",
          [
            q("What three things were “held”?", "Clash, concession, example", ["Weather, jokes, insults", "Clash, concession, example", "Only volume", "A car"]),
            q("How should one win?", "With a shared figure", ["By shouting", "With a shared figure", "By dodging", "By never conceding"]),
            q("What if the jury only hears mood?", "Both sides lose", ["The louder side wins fairly", "Both sides lose", "Buses vanish", "The debate is illegal"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 45-second opening (about 80 words) with clash, concession, example, demand.",
          "Schreib einen 45-Sekunden-Einstieg.",
          "Clash / Zugeständnis / ein Beispiel / eine Forderung. Keine Wetter-Szene.",
          ["Name the metric you reject"],
        ),
        writing(
          "Write a 4-sentence fair rebuttal of “just buy a car”.",
          "Entkräfte „kauf ein Auto“ fair.",
          "Fair wiederholen. Grenze nennen. Strohmann verneinen. Nachhaken mit einer Zahl.",
          ["Stay respectful", "Stay firm"],
        ),
      ],
    },
  ),
];
