import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const b2ChaptersPart1: ChapterSource[] = [
  chapter(
    "nuance-abstract",
    "Abstract Topics & Precise Nuance",
    "Abstrakte Themen und präzise Nuancen",
    "Read essays that hedge and qualify, then write with almost, rather, and insofar as.",
    "mixed",
    [
      "Hedges: eher, weitgehend, im Wesentlichen, nicht unbedingt, sozusagen.",
      "Nominal style vs verbal: die Entscheidung treffen vs entscheiden — mix them.",
      "Abstract nouns: die Freiheit, die Verantwortung, die Gerechtigkeit, die Unsicherheit.",
    ],
    {
      vocab: [
        vocab("die Nuance", "the nuance", undefined, "Nuancen"),
        vocab("abstrakt", "abstract"),
        vocab("konkret", "concrete"),
        vocab("die Freiheit", "freedom"),
        vocab("die Verantwortung", "responsibility"),
        vocab("die Gerechtigkeit", "justice"),
        vocab("die Unsicherheit", "uncertainty"),
        vocab("die Tendenz", "the tendency", undefined, "Tendenzen"),
        vocab("eher", "rather / more likely"),
        vocab("weitgehend", "largely"),
        vocab("im Wesentlichen", "essentially"),
        vocab("nicht unbedingt", "not necessarily"),
        vocab("sozusagen", "so to speak"),
        vocab("gewissermaßen", "in a sense"),
        vocab("insofern", "insofar"),
        vocab("hinsichtlich", "with regard to"),
        vocab("angesichts", "in view of"),
        vocab("die Voraussetzung", "the prerequisite", undefined, "Voraussetzungen"),
        vocab("die Folge", "the consequence"),
        vocab("der Widerspruch", "the contradiction", undefined, "Widersprüche"),
        vocab("die Ambivalenz", "ambivalence"),
        vocab("differenzieren", "to differentiate"),
        vocab("verallgemeinern", "to generalise"),
        vocab("relativieren", "to qualify / relativise"),
        vocab("betonen", "to emphasise"),
        vocab("unterschätzen", "to underestimate"),
        vocab("überschätzen", "to overestimate"),
        vocab("plausibel", "plausible"),
        vocab("fragwürdig", "questionable"),
        vocab("nachvollziehbar", "understandable / traceable"),
        vocab("komplex", "complex"),
        vocab("vereinfacht", "simplified"),
      ],
      phrases: [
        phrase("Das ist weitgehend richtig, aber nicht unbedingt fair.", "That is largely right, but not necessarily fair."),
        phrase("Insofern stimme ich zu, als die Zahlen stimmen.", "I agree insofar as the figures are correct."),
        phrase("Angesichts der Unsicherheit sollten wir langsam entscheiden.", "In view of the uncertainty we should decide slowly."),
        phrase("Man darf nicht verallgemeinern.", "One must not generalise."),
        phrase("Die Freiheit endet, wo die Verantwortung beginnt — sozusagen.", "Freedom ends where responsibility begins — so to speak."),
        phrase("Hinsichtlich der Kosten ist der Plan fragwürdig.", "With regard to cost the plan is questionable."),
        phrase("Es gibt einen Widerspruch zwischen Anspruch und Alltag.", "There is a contradiction between the claim and everyday life."),
        phrase("Die Tendenz geht eher zu mehr Kontrolle.", "The tendency is rather towards more control."),
        phrase("Im Wesentlichen geht es um Gerechtigkeit.", "Essentially it is about justice."),
        phrase("Ein vereinfachtes Bild unterschätzt die Komplexität.", "A simplified picture underestimates the complexity."),
        phrase("Das Argument ist plausibel, die Belege dünn.", "The argument is plausible, the evidence thin."),
        phrase("Ambivalenz ist kein Fehler, sondern oft realistisch.", "Ambivalence is not a fault but often realistic."),
      ],
      sentences: [
        sentence("Konkrete Beispiele machen abstrakte Begriffe greifbar.", "Concrete examples make abstract concepts tangible."),
        sentence("Wir überschätzen schnelle Lösungen.", "We overestimate quick solutions."),
        sentence("Die Voraussetzung für Vertrauen ist Transparenz.", "The prerequisite for trust is transparency."),
        sentence("Gewissermaßen leben wir in zwei Öffentlichkeiten: analog und digital.", "In a sense we live in two public spheres: analogue and digital."),
        sentence("Nicht jede Unsicherheit ist gefährlich.", "Not every uncertainty is dangerous."),
        sentence("Differenzieren heißt, Grautöne zu benennen.", "To differentiate means naming shades of grey."),
        sentence("Die Folge einer falschen Nuance kann ein Missverständnis sein.", "The consequence of a wrong nuance can be a misunderstanding."),
        sentence("Eher vorsichtig als laut — das ist mein Stil.", "Rather cautious than loud — that is my style."),
        sentence("Gerechtigkeit ohne Freiheit bleibt leer.", "Justice without freedom remains empty."),
        sentence("Verantwortung lässt sich nicht vollständig outsourcen.", "Responsibility cannot be fully outsourced."),
        sentence("Ein nachvollziehbarer Gedanke braucht Schritte, nicht nur Thesen.", "A traceable thought needs steps, not only theses."),
        sentence("Komplexe Probleme vertragen keine Ein-Wort-Antworten.", "Complex problems cannot take one-word answers."),
        sentence("Relativieren ist nicht dasselbe wie ausweichen.", "Qualifying is not the same as dodging."),
        sentence("Betonen Sie, was belegt ist, nicht was klingt.", "Emphasise what is evidenced, not what sounds good."),
        sentence("Die Ambivalenz der Technik liegt in Nutzen und Abhängigkeit.", "The ambivalence of technology lies in benefit and dependence."),
        sentence("Fragwürdige Vereinfachungen verkaufen sich gut.", "Questionable simplifications sell well."),
        sentence("Im Wesentlichen bleibt die Frage offen.", "Essentially the question remains open."),
        sentence("Plausible Prognosen sind trotzdem nur Prognosen.", "Plausible forecasts are still only forecasts."),
      ],
      readings: [
        reading(
          "Essay excerpt",
          "Essay-Auszug",
          "Freiheit wird oft als das Recht verstanden, unbeobachtet zu bleiben. Insofern ist Überwachung ein Eingriff. Andererseits entsteht Sicherheit manchmal erst durch Regeln, die alle sehen. Die Ambivalenz ist nicht auflösbar durch ein Schlagwort. Wer differenziert, wirkt langsamer — und meist gerechter.",
          "Freedom is often understood as the right to remain unobserved. Insofar, surveillance is an intrusion. On the other hand, security sometimes only arises through rules that everyone can see. The ambivalence cannot be dissolved by a slogan. Anyone who differentiates seems slower — and usually fairer.",
          [
            q("How is freedom often understood here?", "The right to remain unobserved", ["Loud speech", "The right to remain unobserved", "Cheap travel", "No rules ever"]),
            q("What cannot slogans dissolve?", "Ambivalence", ["Grammar", "Ambivalence", "The weather", "Prices"]),
            q("How do differentiators appear?", "Slower, usually fairer", ["Louder", "Slower, usually fairer", "Richer", "Always wrong"]),
          ],
        ),
        reading(
          "Meeting minutes",
          "Protokoll",
          "Hinsichtlich des Budgets ist der Vorschlag weitgehend tragfähig. Nicht unbedingt nötig ist die teure Kampagne. Im Wesentlichen fehlt eine Voraussetzung: klare Zuständigkeit. Angesichts der Unsicherheit verschieben wir die Entscheidung. Widerspruch kam vor allem zur Zeitplanung, nicht zum Ziel.",
          "With regard to the budget the proposal is largely viable. The expensive campaign is not necessarily needed. Essentially one prerequisite is missing: clear responsibility. In view of the uncertainty we postpone the decision. Objection was mainly to the timetable, not the goal.",
          [
            q("What is missing?", "Clear responsibility", ["Money entirely", "Clear responsibility", "A slogan", "Coffee"]),
            q("What is postponed?", "The decision", ["The goal forever", "The decision", "Lunch", "The company"]),
            q("Where was the objection?", "The timetable", ["The goal", "The timetable", "The grammar", "The building"]),
          ],
        ),
        reading(
          "A cautious comment",
          "Ein vorsichtiger Kommentar",
          "Es ist nachvollziehbar, dass viele schnelle Antworten wollen. Trotzdem unterschätzt eine vereinfachte Debatte die Komplexität. Eher sollten wir fragen, welche Folgen konkret sind. Plausibel klingt vieles. Belegt ist weniger. Das ist keine Schwäche der Sprache, sondern ihre Aufgabe.",
          "It is understandable that many want quick answers. Still, a simplified debate underestimates the complexity. We should rather ask which consequences are concrete. Much sounds plausible. Less is evidenced. That is not a weakness of language but its task.",
          [
            q("What do many people want?", "Quick answers", ["More ambivalence", "Quick answers", "No debate", "Latin texts"]),
            q("What should we ask about?", "Concrete consequences", ["Slogans only", "Concrete consequences", "The weather", "Salaries of journalists"]),
            q("Is lack of evidence framed as a language failure?", "No, as language's task", ["Yes", "No, as language's task", "Unclear", "Only in English"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Take a position with at least three hedges.",
          "Beziehe Stellung mit drei Absicherungen.",
          "Homeoffice ist weitgehend nützlich, aber nicht unbedingt für alle. Insofern brauchen wir Wahl. Im Wesentlichen zählt die konkrete Aufgabe, nicht das Schlagwort.",
          ["eher / weitgehend / nicht unbedingt / insofern"],
        ),
        writing(
          "Qualify a strong claim in four sentences.",
          "Relativiere eine starke These.",
          "„Technik macht frei“ ist vereinfacht. Sie schafft Möglichkeiten und Abhängigkeiten. Die Ambivalenz bleibt. Deshalb sollten wir differenzieren, nicht jubeln.",
          ["Name a contradiction", "Avoid slogans"],
        ),
      ],
    },
  ),
  chapter(
    "passive",
    "The Passive Voice",
    "Das Passiv",
    "Read notices and reports that hide the agent, then choose active or passive on purpose.",
    "grammar",
    [
      "Vorgangspassiv: werden + Partizip II. Zustandspassiv: sein + Partizip II.",
      "von + agent when needed. Often the agent is omitted because it is unknown or obvious.",
      "Modal + passive: Das muss repariert werden. Impersonal: Es wird getanzt.",
    ],
    {
      vocab: [
        vocab("das Passiv", "the passive"),
        vocab("das Aktiv", "the active"),
        vocab("werden", "to become / passive auxiliary"),
        vocab("der Vorgang", "the process", undefined, "Vorgänge"),
        vocab("der Zustand", "the state", undefined, "Zustände"),
        vocab("der Täter", "the agent / perpetrator", undefined, "Täter"),
        vocab("unbekannt", "unknown"),
        vocab("reparieren", "to repair"),
        vocab("gebaut", "built"),
        vocab("geöffnet", "opened / open"),
        vocab("geschlossen", "closed"),
        vocab("erwartet", "expected"),
        vocab("beschlossen", "decided"),
        vocab("verboten", "forbidden"),
        vocab("erlaubt", "allowed"),
        vocab("geliefert", "delivered"),
        vocab("geprüft", "checked"),
        vocab("informiert", "informed"),
        vocab("behandelt", "treated"),
        vocab("gedruckt", "printed"),
        vocab("übersetzt", "translated"),
        vocab("organisiert", "organised"),
        vocab("verschoben", "postponed"),
        vocab("abgesagt", "cancelled"),
        vocab("durchgeführt", "carried out"),
        vocab("festgestellt", "established / found"),
        vocab("angenommen", "accepted / assumed"),
        vocab("abgelehnt", "rejected"),
        vocab("die Baustelle", "the building site"),
        vocab("die Behörde", "the authority", undefined, "Behörden"),
        vocab("automatisch", "automatically"),
        vocab("absichtlich", "on purpose"),
      ],
      phrases: [
        phrase("Hier wird gebaut.", "Construction is going on here."),
        phrase("Die Brücke wird nächstes Jahr eröffnet.", "The bridge will be opened next year."),
        phrase("Der Fehler ist bereits behoben.", "The error has already been fixed. (state)"),
        phrase("Es darf nicht geraucht werden.", "Smoking is not allowed."),
        phrase("Die Sendung wurde von der Post zugestellt.", "The parcel was delivered by the post."),
        phrase("Es wird empfohlen, früh zu kommen.", "It is recommended to arrive early."),
        phrase("Der Termin musste verschoben werden.", "The appointment had to be postponed."),
        phrase("Die Tür ist geschlossen.", "The door is closed. (state)"),
        phrase("Die Tür wird um acht geschlossen.", "The door is closed at eight. (process)"),
        phrase("Von wem wurde das beschlossen?", "By whom was that decided?"),
        phrase("Es ist noch nichts entschieden.", "Nothing has been decided yet."),
        phrase("Die Daten werden automatisch gespeichert.", "The data are saved automatically."),
      ],
      sentences: [
        sentence("In diesem Labor werden Proben geprüft.", "In this lab samples are checked."),
        sentence("Die Ausstellung ist bis Oktober verlängert worden.", "The exhibition has been extended until October."),
        sentence("Ein Ersatzteil muss bestellt werden.", "A spare part has to be ordered."),
        sentence("Die Nachricht wurde absichtlich ungenau formuliert.", "The message was deliberately worded vaguely."),
        sentence("Es wurde getanzt, bis der Strom ausfiel.", "People danced until the power failed."),
        sentence("Anträge werden von der Behörde bearbeitet.", "Applications are processed by the authority."),
        sentence("Die Straße ist gesperrt.", "The road is closed. (state)"),
        sentence("Die Straße wird morgen gesperrt.", "The road will be closed tomorrow."),
        sentence("Das Buch ist ins Deutsche übersetzt worden.", "The book has been translated into German."),
        sentence("Fehler wurden festgestellt, aber nicht öffentlich genannt.", "Errors were found but not named publicly."),
        sentence("Die Konferenz ist abgesagt.", "The conference is cancelled. (state)"),
        sentence("Die Konferenz wird abgesagt.", "The conference is being cancelled."),
        sentence("Patienten werden hier respektvoll behandelt.", "Patients are treated respectfully here."),
        sentence("Es kann nicht ausgeschlossen werden, dass es regnet.", "It cannot be ruled out that it will rain."),
        sentence("Die Entscheidung ist angenommen worden.", "The decision has been accepted."),
        sentence("Zwei Angebote wurden abgelehnt.", "Two offers were rejected."),
        sentence("Das Formular muss online ausgefüllt werden.", "The form has to be filled in online."),
        sentence("Von unbekannten Tätern wurde ein Fahrrad gestohlen.", "A bicycle was stolen by unknown perpetrators."),
      ],
      readings: [
        reading(
          "Building-site sign",
          "Baustellenschild",
          "Die Fahrbahn wird bis Freitag verengt. Fußgänger werden umgeleitet. Lärm ist zwischen 7 und 18 Uhr zu erwarten. Es wird gebeten, den Anweisungen des Personals zu folgen. Bei Fragen kann das Büro kontaktiert werden. Die Maßnahme wurde von der Stadt beschlossen.",
          "The carriageway will be narrowed until Friday. Pedestrians are being diverted. Noise is to be expected between 7 a.m. and 6 p.m. You are requested to follow staff instructions. If you have questions the office can be contacted. The measure was decided by the city.",
          [
            q("Until when is the road narrowed?", "Friday", ["Monday", "Friday", "Forever", "Never named"]),
            q("Who decided the measure?", "The city", ["Unknown thieves", "The city", "Pedestrians", "A shop"]),
            q("Noise hours?", "7–18", ["All night", "7–18", "Only Sundays", "Never"]),
          ],
        ),
        reading(
          "Lab report line",
          "Laborbericht",
          "Die Probe wurde zweimal geprüft. Eine Verunreinigung ist festgestellt worden. Weitere Tests müssen durchgeführt werden, bevor Ergebnisse veröffentlicht werden. Es wird angenommen, dass der Fehler bei der Entnahme lag, nicht im Labor. Eine endgültige Aussage ist noch nicht erlaubt.",
          "The sample was checked twice. Contamination has been found. Further tests must be carried out before results are published. It is assumed the error lay in the sampling, not in the lab. A final statement is not yet permitted.",
          [
            q("How often was the sample checked?", "Twice", ["Once", "Twice", "Never", "Ten times"]),
            q("Where is the error assumed to be?", "In the sampling", ["In the published paper", "In the sampling", "In the city council", "Nowhere"]),
            q("Can they make a final statement?", "Not yet", ["Yes, today", "Not yet", "Only in English", "The text forbids tests"]),
          ],
        ),
        reading(
          "Why passive here?",
          "Warum Passiv?",
          "„Jemand hat das Fenster repariert“ nennt einen Täter, den niemand kennt. „Das Fenster ist repariert“ beschreibt den Zustand. „Das Fenster wird repariert“ beschreibt den Vorgang. Wer bewusst wählt, steuert den Blick. Passiv ist kein Fehler, sondern ein Werkzeug.",
          "“Someone repaired the window” names an agent nobody knows. “The window is repaired” describes the state. “The window is being repaired” describes the process. Anyone who chooses consciously steers the gaze. Passive is not a mistake but a tool.",
          [
            q("What does Zustandspassiv describe?", "The state", ["The thief", "The state", "The future only", "A joke"]),
            q("Is passive a mistake?", "No, a tool", ["Always", "No, a tool", "Only in signs", "Yes in B2"]),
            q("What does a conscious choice do?", "Steer the reader's focus", ["Delete the verb", "Steer the reader's focus", "Ban agents", "Translate to English"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Rewrite five active sentences as passive.",
          "Schreib fünf Passivsätze.",
          "Die Stadt repariert die Brücke. → Die Brücke wird von der Stadt repariert. Jemand hat den Termin verschoben. → Der Termin ist verschoben worden.",
          ["werden + participle", "Optional von-agent"],
        ),
        writing(
          "Write a notice using only passive (4 sentences).",
          "Schreib einen Aushang im Passiv.",
          "Die Bibliothek wird umgebaut. Bücher können online bestellt werden. Lärm ist zu erwarten. Es wird um Verständnis gebeten.",
          ["No named agent needed"],
        ),
      ],
    },
  ),
  chapter(
    "konjunktiv-ii",
    "Konjunktiv II: Hypotheticals & Politeness",
    "Konjunktiv II: Hypothesen und Höflichkeit",
    "Read wishes and polite emails, then produce würde, hätte, wäre, könnte.",
    "grammar",
    [
      "würde + infinitive is the default for most verbs. sein → wäre, haben → hätte, können → könnte, müssen → müsste.",
      "Irreal conditions: Wenn ich Zeit hätte, käme ich. Or: Hätte ich Zeit, würde ich kommen.",
      "Politeness: Könnten Sie …? Ich hätte gern … Würden Sie so freundlich sein …?",
    ],
    {
      vocab: [
        vocab("der Konjunktiv", "the subjunctive"),
        vocab("hypothetisch", "hypothetical"),
        vocab("unreal", "unreal / counterfactual"),
        vocab("der Wunsch", "the wish", undefined, "Wünsche"),
        vocab("die Bedingung", "the condition", undefined, "Bedingungen"),
        vocab("würde", "would"),
        vocab("wäre", "would be / were"),
        vocab("hätte", "would have / had"),
        vocab("könnte", "could"),
        vocab("müsste", "would have to"),
        vocab("sollte", "should"),
        vocab("dürfte", "might / would be allowed"),
        vocab("wollte", "would want"),
        vocab("gern", "gladly"),
        vocab("lieber", "rather"),
        vocab("am liebsten", "most of all"),
        vocab("falls", "in case"),
        vocab("angenommen", "assuming"),
        vocab("theoretisch", "in theory"),
        vocab("praktisch", "in practice"),
        vocab("höflich", "polite"),
        vocab("direkt", "direct"),
        vocab("vorschlagen", "to suggest"),
        vocab("ablehnen", "to decline"),
        vocab("die Alternative", "the alternative", undefined, "Alternativen"),
        vocab("der Rat", "the advice"),
        vocab("an deiner Stelle", "in your place"),
        vocab("wenn schon", "if at all / if that's the case"),
        vocab("beinahe", "almost"),
        vocab("fast", "almost"),
        vocab("ohne", "without"),
        vocab("die Fantasie", "imagination"),
      ],
      phrases: [
        phrase("Ich würde gern später anfangen.", "I would like to start later."),
        phrase("Könnten Sie das Fenster schließen?", "Could you close the window?"),
        phrase("Wenn ich du wäre, würde ich absagen.", "If I were you, I would cancel."),
        phrase("Hätte ich das gewusst, wäre ich früher gekommen.", "If I had known that, I would have come earlier."),
        phrase("Das dürfte schwierig werden.", "That might turn out difficult."),
        phrase("An deiner Stelle würde ich nachfragen.", "In your place I would ask."),
        phrase("Würden Sie so freundlich sein, den Vertrag zu prüfen?", "Would you be so kind as to check the contract?"),
        phrase("Ich hätte lieber Tee.", "I would rather have tea."),
        phrase("Ohne dich wäre die Feier langweilig.", "Without you the party would be boring."),
        phrase("Falls der Zug ausfiele, müssten wir übernachten.", "If the train were cancelled, we would have to stay overnight."),
        phrase("Theoretisch ginge das, praktisch fehlt das Geld.", "In theory that would work; in practice the money is missing."),
        phrase("Beinahe hätten wir uns verpasst.", "We almost missed each other."),
      ],
      sentences: [
        sentence("Wenn das Wetter besser wäre, würden wir wandern.", "If the weather were better, we would hike."),
        sentence("Ich müsste mehr schlafen, aber die Schicht erlaubt das nicht.", "I would have to sleep more, but the shift does not allow it."),
        sentence("Sie sollte den Text noch einmal lesen.", "She should read the text once more."),
        sentence("Wir könnten uns um drei treffen, falls dir das passt.", "We could meet at three if that suits you."),
        sentence("Er wollte eigentlich bleiben, musste aber gehen.", "He actually wanted to stay but had to leave."),
        sentence("Angenommen, die Firma sagte zu — was wäre dein Plan?", "Assuming the company said yes — what would your plan be?"),
        sentence("Ein klarer Rat wäre: nicht unterschreiben ohne Pause.", "Clear advice would be: don't sign without a break."),
        sentence("Ich lehne höflich ab: Das würde ich eher nicht machen.", "I decline politely: I would rather not do that."),
        sentence("Die Alternative wäre ein kleinerer Saal.", "The alternative would be a smaller hall."),
        sentence("Wenn schon Kritik, dann konkret.", "If criticism at all, then specific."),
        sentence("Praktisch wäre ein Bus in der Nacht.", "A night bus would be practical."),
        sentence("Fantasie hilft, Konjunktiv zu üben: Wenn ich Bürgermeisterin wäre …", "Imagination helps practise Konjunktiv: If I were mayor …"),
        sentence("Dürfte ich Sie morgen anrufen?", "Might I call you tomorrow?"),
        sentence("Wir hätten fast den Anschluss verloren.", "We almost missed the connection."),
        sentence("Ohne Internet wäre der Alltag anders, nicht unbedingt schlechter.", "Without the internet everyday life would be different, not necessarily worse."),
        sentence("Ich schlage vor, wir würden den Entwurf teilen.", "I suggest we would share the draft."),
        sentence("Wäre ich früher losgegangen, stünde ich jetzt nicht im Regen.", "If I had left earlier, I would not be standing in the rain now."),
        sentence("Das sollte man nicht so direkt sagen — oder doch, je nach Register.", "One should not say that so directly — or should one, depending on register."),
      ],
      readings: [
        reading(
          "Polite email",
          "Höfliche Mail",
          "Sehr geehrte Frau Lang, könnten wir den Termin auf Donnerstag legen? Mittwoch wäre ungünstig, weil ich prüfen müsste. Ich hätte auch Freitag frei, falls das besser passt. Für eine kurze Rückmeldung wäre ich dankbar. Mit freundlichen Grüßen, I. Costa.",
          "Dear Ms Lang, could we move the appointment to Thursday? Wednesday would be inconvenient because I would have to sit an exam. I would also be free on Friday if that suits better. I would be grateful for a brief reply. Yours sincerely, I. Costa.",
          [
            q("Preferred new day first mentioned?", "Thursday", ["Wednesday", "Thursday", "Sunday", "Never"]),
            q("Why not Wednesday?", "An exam", ["Holiday", "An exam", "No tram", "A joke"]),
            q("What would Costa be grateful for?", "A brief reply", ["A gift", "A brief reply", "Silence", "A contract today"]),
          ],
        ),
        reading(
          "Advice to a friend",
          "Rat an eine Freundin",
          "Wenn ich du wäre, würde ich die Wohnung nicht nehmen. Der Lärm wäre abends schlimm, und du müsstest früh aufstehen. Eine Alternative wäre die kleinere Wohnung näher an der Bahn. Theoretisch ist die große schöner. Praktisch würdest du dich ärgern. Frag nochmal nach der Heizung.",
          "If I were you I would not take the flat. The noise would be bad in the evening and you would have to get up early. An alternative would be the smaller flat closer to the train. In theory the big one is nicer. In practice you would get annoyed. Ask again about the heating.",
          [
            q("Is the big flat recommended?", "No", ["Yes, definitely", "No", "Only in winter", "The text is unclear"]),
            q("What is the alternative?", "A smaller flat near the train", ["A hotel", "A smaller flat near the train", "No housing", "A house in the Alps"]),
            q("What should she ask about?", "The heating", ["The colour", "The heating", "The landlord's dog", "Konjunktiv"]),
          ],
        ),
        reading(
          "Counterfactual news comment",
          "Irrealer Kommentar",
          "Hätte die Stadt früher gebaut, stünden wir jetzt nicht im Stau. Das klingt leicht. Ohne Geld wäre der Bau aber auch nicht schneller gewesen. Beinahe hätte ein Kompromiss gereicht: eine Spur plus Bus. Wenn Wähler Geduld hätten, gäbe es weniger Show. Hätte, wäre, würde — Politik lebt davon.",
          "If the city had built earlier, we would not be in the jam now. That sounds easy. Without money the construction would not have been faster either. A compromise would almost have been enough: one lane plus a bus. If voters had patience, there would be less show. Had, were, would — politics lives on that.",
          [
            q("What almost would have been enough?", "One lane plus a bus", ["A plane", "One lane plus a bus", "No roads", "A slogan"]),
            q("Would no money have made building faster?", "No", ["Yes", "No", "Only at night", "The text says yes"]),
            q("What does politics live on, jokingly?", "Hätte, wäre, würde", ["Only facts", "Hätte, wäre, würde", "Weather", "Latin"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write six hypothetical sentences with different auxiliaries.",
          "Schreib sechs irreale Sätze.",
          "Wenn ich Zeit hätte, würde ich lesen. Wäre das Wetter besser, gingen wir raus. Ich könnte früher kommen. Ich müsste schlafen. Das dürfte klappen. An deiner Stelle würde ich anrufen.",
          ["hätte / wäre / würde / könnte / müsste"],
        ),
        writing(
          "Turn three direct requests into polite Konjunktiv II.",
          "Mach drei Bitten höflich.",
          "Schließen Sie das Fenster. → Könnten Sie das Fenster schließen? Gib mir die Datei. → Würdest du mir die Datei schicken?",
          ["Könnten Sie / Würdest du / Ich hätte gern"],
        ),
      ],
    },
  ),
  chapter(
    "relative-clauses",
    "Relative Clauses & Precise Description",
    "Relativsätze und genaue Beschreibung",
    "Attach extra information without starting a new sentence every time.",
    "grammar",
    [
      "der/die/das/die as relative pronouns agree with the noun, case with the role in the clause.",
      "Preposition + relative: das Haus, in dem ich wohne. wo after places is common in speech.",
      "was after das, alles, nichts, etwas. wer for people in free relatives: Wer wartet, gewinnt.",
    ],
    {
      vocab: [
        vocab("der Relativsatz", "the relative clause", undefined, "Relativsätze"),
        vocab("das Pronomen", "the pronoun", undefined, "Pronomen"),
        vocab("der Bezug", "the reference"),
        vocab("einschränken", "to restrict"),
        vocab("hinzufügen", "to add"),
        vocab("dessen", "whose (m/n genitive)"),
        vocab("deren", "whose (f/pl genitive)"),
        vocab("welcher", "which (formal)"),
        vocab("wo", "where"),
        vocab("wohin", "where to"),
        vocab("woher", "where from"),
        vocab("was", "what / which"),
        vocab("wer", "who"),
        vocab("genau", "precise"),
        vocab("überflüssig", "superfluous"),
        vocab("die Angabe", "the piece of information", undefined, "Angaben"),
        vocab("identifizieren", "to identify"),
        vocab("beschreiben", "to describe"),
        vocab("der Kommasetzung", "comma placement"),
        vocab("notwendig", "necessary"),
        vocab("zusätzlich", "additional"),
        vocab("der Satzbau", "sentence structure"),
        vocab("verschachtelt", "nested"),
        vocab("klar", "clear"),
        vocab("der Leser", "the reader (m)"),
        vocab("die Leserin", "the reader (f)"),
        vocab("verweisen", "to refer"),
        vocab("andernfalls", "otherwise"),
        vocab("nämlich", "namely"),
        vocab("und zwar", "namely / that is"),
        vocab("insbesondere", "especially"),
        vocab("unter anderem", "among other things"),
      ],
      phrases: [
        phrase("Das ist die Kollegin, die den Kurs leitet.", "That is the colleague who runs the course."),
        phrase("Das Büro, in dem wir sitzen, ist zu klein.", "The office in which we sit is too small."),
        phrase("Alles, was du gesagt hast, habe ich notiert.", "Everything you said I have noted."),
        phrase("Wer zu spät kommt, findet keinen Platz.", "Whoever comes too late finds no seat."),
        phrase("Die Stadt, aus der ich komme, liegt am Rhein.", "The city I come from is on the Rhine."),
        phrase("Ein Plan, dessen Ziel unklar ist, hilft nicht.", "A plan whose goal is unclear does not help."),
        phrase("Die Firma, deren Chef heute spricht, sucht Leute.", "The company whose boss is speaking today is hiring."),
        phrase("Das, was fehlt, ist Zeit.", "What is missing is time."),
        phrase("Ein Satz, der zu lang ist, verliert Leser.", "A sentence that is too long loses readers."),
        phrase("Die Idee, über die wir reden, ist alt.", "The idea we are talking about is old."),
        phrase("Nichts, was er verspricht, ist belegt.", "Nothing he promises is evidenced."),
        phrase("Der Ort, wohin wir ziehen, ist ruhiger.", "The place we are moving to is quieter."),
      ],
      sentences: [
        sentence("Ich suche das Buch, das du empfohlen hast.", "I am looking for the book you recommended."),
        sentence("Die Leute, mit denen ich wohne, kochen gern.", "The people I live with like cooking."),
        sentence("Ein Fehler, den man früh findet, spart Geld.", "A mistake you find early saves money."),
        sentence("Die Regel, an die wir uns halten, steht im Intranet.", "The rule we follow is on the intranet."),
        sentence("Etwas, was mich stört, ist Lärm nach zehn.", "Something that bothers me is noise after ten."),
        sentence("Die Brücke, über die wir fahren, wird saniert.", "The bridge we are driving over is being refurbished."),
        sentence("Kinder, deren Eltern Schicht arbeiten, brauchen späte Busse.", "Children whose parents work shifts need late buses."),
        sentence("Der Film, den wir gesehen haben, war zu lang.", "The film we watched was too long."),
        sentence("Eine E-Mail, in der der Betreff fehlt, geht unter.", "An email in which the subject is missing gets lost."),
        sentence("Wer zuhört, stellt bessere Fragen.", "Whoever listens asks better questions."),
        sentence("Das Haus, hinter dem ein Garten liegt, ist teurer.", "The house behind which there is a garden is more expensive."),
        sentence("Angaben, die du nicht belegen kannst, streichst du.", "Information you cannot evidence you delete."),
        sentence("Insbesondere Sätze, die drei Relativsätze stapeln, werden unklar.", "Especially sentences that stack three relative clauses become unclear."),
        sentence("Der Zug, mit dem sie kommt, hat Verspätung.", "The train she is coming on is delayed."),
        sentence("Eine Lösung, die alle akzeptieren, dauert länger.", "A solution that everyone accepts takes longer."),
        sentence("Andernfalls bleibt der Bezug unklar.", "Otherwise the reference remains unclear."),
        sentence("Nämlich der Punkt, den wir vergessen haben, war das Datum.", "Namely the point we forgot was the date."),
        sentence("Unter anderem die Beispiele, die du nennst, überzeugen.", "Among other things the examples you mention are convincing."),
      ],
      readings: [
        reading(
          "A nested problem",
          "Ein Verschachtelungsproblem",
          "Der Bericht, den die Behörde, die für Verkehr zuständig ist, gestern veröffentlicht hat, ist zu lang. Leserinnen, deren Zeit knapp ist, hören nach dem ersten Relativsatz auf. Was hilft, ist ein Satz, der eine Information trägt. Wer klar schreiben will, trennt lieber.",
          "The report that the authority that is responsible for transport published yesterday is too long. Readers whose time is short stop after the first relative clause. What helps is a sentence that carries one piece of information. Anyone who wants to write clearly would rather split.",
          [
            q("Why do some readers stop?", "The sentence is too nested / their time is short", ["The font", "The sentence is too nested / their time is short", "No verbs", "It's in French"]),
            q("What helps?", "A sentence with one piece of information", ["More nesting", "A sentence with one piece of information", "No commas", "ALL CAPS"]),
            q("What should clear writers do?", "Split sentences", ["Stack more clauses", "Split sentences", "Delete nouns", "Only use wo"]),
          ],
        ),
        reading(
          "Housing advert with relatives",
          "Wohnungsanzeige",
          "Gesucht wird eine Person, die ruhig ist und gern kocht. Die Wohnung, in der ein Zimmer frei wird, liegt nah an der Bahn, mit der man in 15 Minuten in der Stadt ist. Ein Garten, dessen Pflege wir teilen, gehört dazu. Was wir nicht wollen, ist Lärm nach 22 Uhr.",
          "Wanted is a person who is quiet and likes cooking. The flat in which a room is becoming free is close to the train with which you are in the city in 15 minutes. A garden whose upkeep we share comes with it. What we do not want is noise after 10 p.m.",
          [
            q("What kind of person is wanted?", "Quiet and likes cooking", ["Loud musicians", "Quiet and likes cooking", "Only cats", "Night-shift DJs"]),
            q("How long to the city by train?", "15 minutes", ["15 hours", "15 minutes", "Unknown", "No train"]),
            q("What is not wanted?", "Noise after 22:00", ["Cooking", "Noise after 22:00", "A garden", "Trains"]),
          ],
        ),
        reading(
          "Legal-ish sentence, then a rewrite",
          "Juristendeutsch, dann Klartext",
          "Ursprung: „Die Regelung, hinsichtlich derer Einwände, die von Bürgern, deren Grundstücke betroffen sind, erhoben wurden, geprüft werden.“ Klartext: Bürger mit betroffenen Grundstücken haben Einwände erhoben. Die Einwände werden geprüft. Relativsätze, die man stapelt, sind selten nötig.",
          "Original: a stacked legal sentence about objections from citizens whose plots are affected being examined. Plain text: Citizens with affected plots raised objections. The objections are being examined. Relative clauses that you stack are rarely necessary.",
          [
            q("What is being examined?", "The objections", ["The weather", "The objections", "A recipe", "Train times"]),
            q("Who raised objections?", "Citizens with affected plots", ["Tourists", "Citizens with affected plots", "Only lawyers", "Nobody"]),
            q("Are stacked relatives usually needed?", "Rarely", ["Always in B2", "Rarely", "Never in German", "Only in songs"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write six sentences each with a relative clause in a different case/preposition.",
          "Schreib sechs Relativsätze.",
          "Das ist der Kurs, den ich mache. Die Stadt, in der ich wohne, ist klein. Alles, was zählt, ist Übung. Wer liest, lernt. Die Frau, mit der ich arbeite, ist geduldig. Ein Plan, dessen Ziel klar ist, hilft.",
          ["der/die/das + case", "One wo or was"],
        ),
        writing(
          "Split one overloaded sentence into three.",
          "Zerlege einen überladenen Satz.",
          "Statt eines Monster-Satzes: Die Behörde hat den Bericht veröffentlicht. Der Bericht ist zu lang. Leser hören früh auf.",
          ["Keep the information", "Kill nested relatives"],
        ),
      ],
    },
  ),
  chapter(
    "politics-society",
    "Politics, Society & Civic Life",
    "Politik, Gesellschaft und Bürgerleben",
    "Read civic texts without jargon panic, then take a measured position.",
    "mixed",
    [
      "Unions, parties, federal states: Bund, Land, Kommune.",
      "Passive and nominal style in official German — unpack into verbs when you write.",
      "Fair argument: concede a point, then limit it.",
    ],
    {
      vocab: [
        vocab("die Politik", "politics / policy"),
        vocab("die Gesellschaft", "society"),
        vocab("der Staat", "the state", undefined, "Staaten"),
        vocab("die Regierung", "the government", undefined, "Regierungen"),
        vocab("die Opposition", "the opposition"),
        vocab("die Wahl", "the election", undefined, "Wahlen"),
        vocab("wählen", "to vote / choose"),
        vocab("das Gesetz", "the law", undefined, "Gesetze"),
        vocab("das Recht", "the right / law"),
        vocab("die Pflicht", "the duty"),
        vocab("die Demokratie", "democracy"),
        vocab("die Meinungshoheit", "dominance of opinion"),
        vocab("die Debatte", "the debate", undefined, "Debatten"),
        vocab("der Kompromiss", "the compromise", undefined, "Kompromisse"),
        vocab("die Bürgerin", "the citizen (f)", undefined, "Bürgerinnen"),
        vocab("der Bürger", "the citizen (m)", undefined, "Bürger"),
        vocab("die Kommune", "the municipality", undefined, "Kommunen"),
        vocab("das Bundesland", "the federal state", undefined, "Bundesländer"),
        vocab("die Steuer", "the tax", undefined, "Steuern"),
        vocab("die Rente", "the pension", undefined, "Renten"),
        vocab("die Migration", "migration"),
        vocab("die Integration", "integration"),
        vocab("die Ungleichheit", "inequality"),
        vocab("die Teilhabe", "participation"),
        vocab("öffentlich", "public"),
        vocab("privat", "private"),
        vocab("legitim", "legitimate"),
        vocab("umstritten", "controversial"),
        vocab("gewählt", "elected"),
        vocab("abstimmen", "to vote (on something)"),
        vocab("protestieren", "to protest"),
        vocab("die Petition", "the petition", undefined, "Petitionen"),
      ],
      phrases: [
        phrase("Bei der Wahl geht es nicht nur um Parteien.", "An election is not only about parties."),
        phrase("Ein Kompromiss ist kein Verrat.", "A compromise is not a betrayal."),
        phrase("Die Kommune entscheidet über den Bus, nicht der Bund.", "The municipality decides on the bus, not the federal level."),
        phrase("Teilhaben heißt mehr als wählen alle vier Jahre.", "Participation means more than voting every four years."),
        phrase("Das Gesetz gilt, auch wenn es umstritten ist.", "The law applies even when it is controversial."),
        phrase("Steuern finanzieren Rente, Schulen und Straßen.", "Taxes fund pensions, schools and roads."),
        phrase("Ich räume ein, dass Kosten steigen — trotzdem ist die Linie nötig.", "I concede that costs are rising — still the line is needed."),
        phrase("Öffentliche Debatte braucht Regeln gegen Hetze.", "Public debate needs rules against hate speech."),
        phrase("Eine Petition ändert selten alles, aber sie sammelt Stimmen.", "A petition rarely changes everything, but it gathers voices."),
        phrase("Integration ist keine Einbahnstraße.", "Integration is not a one-way street."),
        phrase("Ungleichheit wird sichtbar, wenn man Zahlen liest, nicht Slogans.", "Inequality becomes visible when you read figures, not slogans."),
        phrase("Wer protestiert, nutzt ein demokratisches Recht.", "Anyone who protests is using a democratic right."),
      ],
      sentences: [
        sentence("Die Opposition kontrolliert die Regierung, zumindest in der Theorie.", "The opposition scrutinises the government, at least in theory."),
        sentence("Bundesländer haben eigene Schulsysteme.", "Federal states have their own school systems."),
        sentence("Ein legitimes Interesse der Anwohner ist Ruhe in der Nacht.", "A legitimate interest of residents is quiet at night."),
        sentence("Privatheit endet nicht an der Wohnungstür, wenn Kameras überall sind.", "Privacy does not end at the front door when cameras are everywhere."),
        sentence("Gewählte Gremien sollen transparent tagen.", "Elected bodies should meet transparently."),
        sentence("Wir stimmen am Sonntag über den Haushalt ab.", "We vote on the budget on Sunday."),
        sentence("Pflichten ohne Rechte sind nur Zwang.", "Duties without rights are only coercion."),
        sentence("Die Debatte ist laut, die Fakten leise.", "The debate is loud, the facts quiet."),
        sentence("Migration prägt Städte anders als Dörfer.", "Migration shapes cities differently from villages."),
        sentence("Teilhabe braucht Sprache, Zeit und oft Geld für den Bus.", "Participation needs language, time and often money for the bus."),
        sentence("Umstrittene Gesetze brauchen besonders klare Begründung.", "Controversial laws need especially clear justification."),
        sentence("Bürgerinnen können im Gemeinderat zuhören.", "Citizens can listen in the local council."),
        sentence("Eine Demokratie lebt von langweiligen Verfahren.", "A democracy lives on boring procedures."),
        sentence("Meinungshoheit in sozialen Netzen ist keine Wahl.", "Dominance of opinion on social networks is not an election."),
        sentence("Rente und Pflege sind Zukunftsthemen, keine Randnotizen.", "Pensions and care are future topics, not footnotes."),
        sentence("Der Staat ist kein Verein, aber auch kein Feind.", "The state is not a club, but neither is it an enemy."),
        sentence("Kompromisse machen niemand völlig glücklich — das ist ihr Job.", "Compromises make nobody completely happy — that is their job."),
        sentence("Wer nur protestiert und nie liest, bleibt leicht zu steuern.", "Anyone who only protests and never reads remains easy to steer."),
      ],
      readings: [
        reading(
          "Local council note",
          "Gemeinderat",
          "Der Gemeinderat stimmt über eine neue Buslinie ab. Die Opposition fordert eine Prüfung der Kosten. Anwohner protestieren gegen Lärm am Endhalt. Ein Kompromiss wäre ein kürzerer Takt am Abend, nicht die ganze Nacht. Die Abstimmung ist öffentlich. Eine Petition mit 400 Stimmen liegt vor.",
          "The local council is voting on a new bus line. The opposition demands a review of costs. Residents protest against noise at the terminus. A compromise would be a denser evening service, not all night. The vote is public. A petition with 400 signatures is on the table.",
          [
            q("What is being voted on?", "A new bus line", ["A national election", "A new bus line", "A tax on books", "Nothing"]),
            q("How many petition signatures?", "400", ["40", "400", "4000 named", "None"]),
            q("What compromise is suggested?", "Denser evenings, not all night", ["No buses", "Denser evenings, not all night", "Only taxis", "A motorway"]),
          ],
        ),
        reading(
          "Op-ed opening",
          "Kommentar-Einstieg",
          "Ungleichheit beginnt nicht erst beim Gehalt. Wer drei Busse braucht, um zur Wahl zu kommen, hat weniger Teilhabe. Das ist keine Moralpredigt, sondern ein Fahrplanproblem. Der Bund setzt Rahmen, die Kommune den Takt. Wer nur auf Berlin schimpft, entlastet das Rathaus zu Unrecht.",
          "Inequality does not begin with salary. Anyone who needs three buses to get to the vote has less participation. That is not a sermon but a timetable problem. The federal level sets the framework, the municipality the frequency. Anyone who only rails at Berlin lets the town hall off too lightly.",
          [
            q("What kind of problem is named first?", "A timetable / transport problem", ["Only morality", "A timetable / transport problem", "A sports score", "A recipe"]),
            q("Who sets the bus frequency?", "The municipality", ["Only the EU", "The municipality", "A newspaper", "Nobody"]),
            q("What happens if you only blame Berlin?", "The town hall is let off", ["Buses improve automatically", "The town hall is let off", "Elections stop", "Taxes vanish"]),
          ],
        ),
        reading(
          "Rights and duties box",
          "Kasten Rechte/Pflichten",
          "Recht: wählen, demonstrieren, petitionieren, eine Meinung äußern. Pflicht: Gesetze achten, Steuern zahlen, andere nicht bedrohen. Beides gehört zur Demokratie. Umstritten bleibt, wie laut Protest sein darf. Legitim ist Streit; Hetze gegen Minderheiten nicht. Verfahren schützen auch die, die man nicht mag.",
          "Right: to vote, demonstrate, petition, express an opinion. Duty: respect laws, pay taxes, not threaten others. Both belong to democracy. What remains controversial is how loud protest may be. Dispute is legitimate; hate against minorities is not. Procedures also protect those you dislike.",
          [
            q("Is paying tax listed as a duty?", "Yes", ["No", "Yes", "Only for parties", "Unclear"]),
            q("What is not legitimate?", "Hate against minorities", ["Disagreement", "Hate against minorities", "Petitions", "Quiet protest"]),
            q("Whom do procedures also protect?", "People you dislike", ["Only winners", "People you dislike", "Only journalists", "Nobody"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 8-sentence civic opinion with a concession.",
          "Schreib eine Meinung mit Zugeständnis.",
          "Ich räume ein, dass neue Busse Geld kosten. Trotzdem ist Teilhabe ohne Takt unmöglich. Die Kommune sollte den Abend stärken. Der Bund kann den Rahmen setzen. Ein Kompromiss ist kein Verrat. Zahlen helfen mehr als Slogans. Protest bleibt legitim. Hetze nicht.",
          ["Concede + limit", "Name a level: Kommune/Bund"],
        ),
        writing(
          "Unpack one official sentence into two plain ones.",
          "Mach Amtssatz klar.",
          "„Eine Prüfung der Kosten wird vorgenommen.“ → Die Opposition will die Kosten prüfen. Das Rathaus soll die Zahlen liefern.",
          ["Named agent", "Plain verb"],
        ),
      ],
    },
  ),
  chapter(
    "science",
    "Science, Health Claims & Innovation",
    "Wissenschaft, Gesundheitsclaims und Innovation",
    "Read popular-science paragraphs sceptically, then report findings without hype.",
    "reading",
    [
      "Hedging in science German: deuten darauf hin, nahelegen, nicht belegt, unter Vorbehalt.",
      "Passive for methods: Es wurden 200 Personen befragt.",
      "Korrelation ist nicht Kausalität — say that in German too.",
    ],
    {
      vocab: [
        vocab("die Wissenschaft", "science"),
        vocab("die Studie", "the study", undefined, "Studien"),
        vocab("die Hypothese", "the hypothesis", undefined, "Hypothesen"),
        vocab("das Experiment", "the experiment", undefined, "Experimente"),
        vocab("die Methode", "the method", undefined, "Methoden"),
        vocab("das Ergebnis", "the result", undefined, "Ergebnisse"),
        vocab("die Stichprobe", "the sample", undefined, "Stichproben"),
        vocab("signifikant", "significant"),
        vocab("zufällig", "random / by chance"),
        vocab("die Korrelation", "correlation"),
        vocab("die Ursache", "the cause"),
        vocab("belegen", "to evidence"),
        vocab("widerlegen", "to refute"),
        vocab("nahelegen", "to suggest (evidence)"),
        vocab("hinweisen", "to indicate"),
        vocab("der Vorbehalt", "the reservation", undefined, "Vorbehalte"),
        vocab("peer-reviewed", "peer-reviewed"),
        vocab("die Innovation", "innovation", undefined, "Innovationen"),
        vocab("die Technologie", "technology"),
        vocab("die Nebenwirkung", "the side effect", undefined, "Nebenwirkungen"),
        vocab("dosieren", "to dose"),
        vocab("impfen", "to vaccinate"),
        vocab("die Zelle", "the cell", undefined, "Zellen"),
        vocab("das Virus", "the virus", undefined, "Viren"),
        vocab("nachhaltig", "sustainable / lasting"),
        vocab("reproduzierbar", "reproducible"),
        vocab("die Messung", "the measurement", undefined, "Messungen"),
        vocab("der Durchschnitt", "the average"),
        vocab("abweichen", "to deviate"),
        vocab("vorsichtig", "cautious"),
        vocab("sensational", "sensational"),
        vocab("der Labor", "the lab", undefined, "Labore"),
      ],
      phrases: [
        phrase("Die Studie deutet darauf hin, dass der Schlaf wichtiger ist als gedacht.", "The study indicates that sleep is more important than thought."),
        phrase("Damit ist keine Ursache bewiesen.", "That does not prove a cause."),
        phrase("Die Stichprobe war klein, die Ergebnisse unter Vorbehalt.", "The sample was small; results are provisional."),
        phrase("Es wurden 180 Personen zufällig ausgewählt.", "180 people were selected at random."),
        phrase("Eine Korrelation ist keine Kausalität.", "A correlation is not causation."),
        phrase("Nebenwirkungen müssen klar genannt werden.", "Side effects must be named clearly."),
        phrase("Peer-reviewed heißt geprüft, nicht unfehlbar.", "Peer-reviewed means checked, not infallible."),
        phrase("Die Messung weicht vom Durchschnitt ab.", "The measurement deviates from the average."),
        phrase("Innovation ohne Ethik ist nur Tempo.", "Innovation without ethics is only speed."),
        phrase("Das Experiment ließ sich nicht reproduzieren.", "The experiment could not be reproduced."),
        phrase("Unter Vorbehalt empfehlen die Autoren mehr Wasser, nicht Wunderpillen.", "With reservations the authors recommend more water, not miracle pills."),
        phrase("Hype verkauft, Methode überzeugt.", "Hype sells, method convinces."),
      ],
      sentences: [
        sentence("Eine Hypothese muss man widerlegen können, sonst ist sie keine.", "A hypothesis must be refutable, otherwise it is not one."),
        sentence("Die Methode stand im Anhang, nicht in der Überschrift.", "The method was in the appendix, not in the headline."),
        sentence("Signifikant heißt nicht automatisch wichtig für den Alltag.", "Significant does not automatically mean important in everyday life."),
        sentence("Zufällige Schwankungen werden oft als Trend verkauft.", "Random fluctuations are often sold as a trend."),
        sentence("Das Labor hat die Proben doppelt gemessen.", "The lab measured the samples twice."),
        sentence("Nachhaltige Wirkung zeigte sich erst nach zwölf Wochen.", "A lasting effect only appeared after twelve weeks."),
        sentence("Dosieren Sie nicht nach Forenrat.", "Do not dose according to forum advice."),
        sentence("Viren sind keine Bakterien; die Therapie unterscheidet sich.", "Viruses are not bacteria; the therapy differs."),
        sentence("Zellen im Reagenzglas sind nicht der ganze Mensch.", "Cells in a test tube are not the whole person."),
        sentence("Vorsichtige Sprache ist kein Schwächezeichen.", "Cautious language is not a sign of weakness."),
        sentence("Sensational Headlines verderben gute Daten.", "Sensational headlines spoil good data."),
        sentence("Die Technologie ist neu, die Belege dünn.", "The technology is new, the evidence thin."),
        sentence("Autoren räumen Einschränkungen ein — das ist Stärke.", "Authors admit limitations — that is a strength."),
        sentence("Eine zweite Studie sollte denselben Effekt finden.", "A second study should find the same effect."),
        sentence("Der Durchschnitt versteckt Extreme.", "The average hides extremes."),
        sentence("Wer impft, reduziert Risiko, löscht es nicht immer.", "Anyone who vaccinates reduces risk, does not always erase it."),
        sentence("Innovation braucht Kritik so nötig wie Geld.", "Innovation needs criticism as much as money."),
        sentence("Ohne nachvollziehbare Methode bleibt das Ergebnis eine Geschichte.", "Without a transparent method the result remains a story."),
      ],
      readings: [
        reading(
          "Press release vs paper",
          "Presse vs Paper",
          "Die Pressemitteilung schreibt: „Wundertee heilt Müdigkeit.“ Das Paper sagt: 40 Studentinnen, zwei Wochen, selbsteingeschätzte Müdigkeit, kein Placeboarm. Die Korrelation ist schwach. Eine Ursache ist nicht belegt. Unter Vorbehalt: mehr Schlaf bleibt die bessere Hypothese. Reproduzierbar ist die Studie bisher nicht.",
          "The press release writes: “Miracle tea cures tiredness.” The paper says: 40 female students, two weeks, self-rated tiredness, no placebo arm. The correlation is weak. A cause is not evidenced. With reservations: more sleep remains the better hypothesis. The study is not yet reproducible.",
          [
            q("How many participants?", "40", ["4000", "40", "Unknown", "Two"]),
            q("Is causation proven?", "No", ["Yes", "No", "Only for men", "The tea company says yes so it is true"]),
            q("Better hypothesis named?", "More sleep", ["More tea", "More sleep", "No rest", "A new phone"]),
          ],
        ),
        reading(
          "Methods paragraph",
          "Methodenabsatz",
          "Es wurden 200 Erwachsene zufällig in zwei Gruppen geteilt. Gruppe A trainierte dreimal die Woche, Gruppe B nicht. Gemessen wurde der Ruhepuls. Abweichungen über fünf Schläge galten als auffällig. Die Autorinnen weisen darauf hin, dass Sportliche sich eher gemeldet haben könnten. Ergebnisse gelten unter diesem Vorbehalt.",
          "200 adults were randomly split into two groups. Group A trained three times a week, group B did not. Resting pulse was measured. Deviations over five beats were considered striking. The authors point out that athletic people may have been more likely to volunteer. Results apply under this reservation.",
          [
            q("What was measured?", "Resting pulse", ["Happiness", "Resting pulse", "Income", "Tea cups"]),
            q("How often did group A train?", "Three times a week", ["Never", "Three times a week", "Daily marathon", "Once a year"]),
            q("What bias is admitted?", "Athletic people may have volunteered more", ["No bias", "Athletic people may have volunteered more", "Only children", "Broken watches"]),
          ],
        ),
        reading(
          "Innovation ethics note",
          "Ethiknotiz",
          "Eine App erkennt Hautveränderungen. Das klingt nach Fortschritt. Nebenwirkungen der Angst: unnötige Arztbesuche. Die Studie ist peer-reviewed, die Stichprobe aber klinisch, nicht hausärztlich. Innovation sollte Nutzen belegen, bevor sie Angst verkauft. Vorsichtige Sprache schützt Patienten mehr als Tempo.",
          "An app detects skin changes. That sounds like progress. Side effects of fear: unnecessary doctor visits. The study is peer-reviewed, but the sample is clinical, not from GP practices. Innovation should evidence benefit before it sells fear. Cautious language protects patients more than speed.",
          [
            q("What side effect of fear is named?", "Unnecessary doctor visits", ["Better sleep", "Unnecessary doctor visits", "Free tea", "No apps"]),
            q("What is limited about the sample?", "It is clinical, not GP-based", ["It is huge and general", "It is clinical, not GP-based", "Only animals", "No people"]),
            q("What protects patients more than speed?", "Cautious language", ["Louder ads", "Cautious language", "Ignoring studies", "Hype"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Rewrite a hyped claim as a scientific German sentence.",
          "Mach aus Hype Wissenschaftsdeutsch.",
          "Statt „Wundertee heilt“: Eine kleine Studie legt nahe, dass die Müdigkeit leicht sank; eine Ursache ist nicht belegt.",
          ["deutet hin / nahelegen", "nicht belegt"],
        ),
        writing(
          "Write a 6-sentence summary of an imaginary study with a limitation.",
          "Fasse eine Studie mit Einschränkung zusammen.",
          "Es wurden 80 Personen befragt. Die Stichprobe war jung. Ergebnisse deuten auf weniger Stress durch Spaziergänge hin. Korrelation ist keine Ursache. Unter Vorbehalt empfehlen die Autoren Bewegung. Weitere Studien sind nötig.",
          ["Method + result + limitation"],
        ),
      ],
    },
  ),
];
