import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const c1ChaptersPart1: ChapterSource[] = [
  chapter(
    "academic-language",
    "Academic German: Stance, Caution, Precision",
    "Wissenschaftsdeutsch: Haltung, Vorsicht, Präzision",
    "Read papers like a reviewer, then write with hedges that still take a position.",
    "mixed",
    [
      "Stance: der Beitrag zeigt, legt nahe, stellt in Frage — not „beweist“ unless it does.",
      "Nominal style is common; unpack it when clarity suffers.",
      "Signalling: im Folgenden, dabei, gleichwohl, insofern.",
    ],
    {
      vocab: [
        vocab("der Beitrag", "the paper / contribution", undefined, "Beiträge"),
        vocab("die Untersuchung", "the study", undefined, "Untersuchungen"),
        vocab("die Fragestellung", "the research question"),
        vocab("der Forschungsstand", "the state of research"),
        vocab("die Lücke", "the gap", undefined, "Lücken"),
        vocab("heranziehen", "to draw on"),
        vocab("zugrunde liegen", "to underlie"),
        vocab("darlegen", "to set out"),
        vocab("herausarbeiten", "to work out / show"),
        vocab("in den Blick nehmen", "to bring into view"),
        vocab("problematisieren", "to problematise"),
        vocab("differenzieren", "to differentiate"),
        vocab("konzedieren", "to concede"),
        vocab("einräumen", "to admit"),
        vocab("nahelegen", "to suggest"),
        vocab("hinweisen auf", "to point to"),
        vocab("in Frage stellen", "to call into question"),
        vocab("geltend machen", "to claim / assert"),
        vocab("implizieren", "to imply"),
        vocab("explizieren", "to make explicit"),
        vocab("der Vorbehalt", "the reservation"),
        vocab("die Reichweite", "the scope / reach"),
        vocab("übertragbar", "transferable"),
        vocab("fallspezifisch", "case-specific"),
        vocab("heuristisch", "heuristic"),
        vocab("deskriptiv", "descriptive"),
        vocab("normativ", "normative"),
        vocab("die Operationalisierung", "operationalisation"),
        vocab("das Sample", "the sample"),
        vocab("die Güte", "quality (of a measure)"),
        vocab("anschlussfähig", "connectable (to further research)"),
        vocab("desiderat", "a desideratum / research need"),
      ],
      phrases: [
        phrase("Im Folgenden wird dargelegt, inwiefern die Operationalisierung zu eng ist.", "In what follows it is set out to what extent the operationalisation is too narrow."),
        phrase("Der Forschungsstand lässt eine Lücke hinsichtlich prekärer Arbeit erkennen.", "The state of research reveals a gap regarding precarious work."),
        phrase("Die Ergebnisse legen nahe, nicht: sie beweisen kausal.", "The results suggest; they do not prove causally."),
        phrase("Gleichwohl ist die Reichweite fallspezifisch.", "Nevertheless the scope is case-specific."),
        phrase("Es sei konzediert, dass das Sample urban lastig ist.", "It should be conceded that the sample is urban-heavy."),
        phrase("Damit wird implizit ein normativer Maßstab gesetzt.", "In doing so a normative yardstick is implicitly set."),
        phrase("Anschlussfähig wäre eine Replikation außerhalb der Großstadt.", "A replication outside the city would be connectable research."),
        phrase("Die Güte des Indikators bleibt diskussionswürdig.", "The quality of the indicator remains open to discussion."),
        phrase("Heuristisch nützlich, empirisch vorläufig.", "Heuristically useful, empirically provisional."),
        phrase("Deskriptiv gehaltvoll, normativ unterbestimmt.", "Descriptively rich, normatively underdetermined."),
        phrase("Insofern stellt der Beitrag eher Fragen, als dass er schließt.", "In that sense the paper poses questions rather than closing them."),
        phrase("Ein Desiderat bleibt die Längsschnittperspektive.", "A longitudinal perspective remains a desideratum."),
      ],
      sentences: [
        sentence("Der Untersuchung liegt ein praxeologisches Verständnis von Arbeit zugrunde.", "The study is based on a praxeological understanding of work."),
        sentence("Herangezogen werden amtliche Statistiken und 24 Interviews.", "Official statistics and 24 interviews are drawn on."),
        sentence("Herauszuarbeiten ist die Differenz von formaler und gelebter Flexibilität.", "What must be worked out is the difference between formal and lived flexibility."),
        sentence("Die Autorinnen nehmen prekäre Zeitregime in den Blick.", "The authors bring precarious time regimes into view."),
        sentence("Problematisiert wird die Gleichsetzung von Teilzeit und Wahlfreiheit.", "The equation of part-time work with freedom of choice is problematised."),
        sentence("Geltend gemacht wird ein Recht auf planbare Abende.", "A right to predictable evenings is asserted."),
        sentence("Expliziert man den Maßstab, wird die Norm sichtbar.", "If one makes the yardstick explicit, the norm becomes visible."),
        sentence("Übertragbar sind die Mechanismen, nicht die Prozentwerte.", "The mechanisms are transferable, not the percentages."),
        sentence("Fallspezifisch bleibt die Rolle des Betriebsrats.", "The role of the works council remains case-specific."),
        sentence("Die Fragestellung ist bewusst eng, um Tiefe zu gewinnen.", "The question is deliberately narrow in order to gain depth."),
        sentence("Einräumen muss man die soziale Erwünschtheit in Interviews.", "One must admit social desirability in interviews."),
        sentence("Damit wird nicht die Methode verworfen, sondern ihre Grenze markiert.", "This does not reject the method but marks its limit."),
        sentence("Differenzieren statt moralisieren — das ist akademische Höflichkeit.", "Differentiate rather than moralise — that is academic politeness."),
        sentence("Die Vorbehalte stehen nicht in der Fußnote, um sie zu verstecken, sondern um sie zu stärken.", "The reservations are not in the footnote to hide them but to strengthen them."),
        sentence("In den Blick gerät, wer den letzten Bus braucht, nicht wer ihn nie sieht.", "Into view comes whoever needs the last bus, not whoever never sees it."),
        sentence("Eine deskriptive Dichte ersetzt keine kausale Identifikation.", "Descriptive density does not replace causal identification."),
        sentence("Normative Sätze gehören kenntlich gemacht, nicht geschmuggelt.", "Normative sentences should be marked, not smuggled."),
        sentence("Der Beitrag ist anschlussfähig, weil er Operationalisierungen offenlegt.", "The paper is connectable because it discloses operationalisations."),
      ],
      readings: [
        reading(
          "Abstract",
          "Abstract",
          "Der Beitrag untersucht Abendmobilität als Infrastruktur der Teilhabe. Zugrunde liegt eine Mixed-Methods-Erhebung in zwei Großstädten. Die Ergebnisse legen nahe, dass Auslastungskennziffern Schichtarbeit unsichtbar machen. Gleichwohl ist die Reichweite urban begrenzt. Ein Desiderat bleibt der ländliche Vergleich. Der Text stellt in Frage, ob „leere Busse“ ein neutrales Maß sind.",
          "The paper examines evening mobility as infrastructure of participation. It is based on a mixed-methods survey in two large cities. The results suggest that occupancy metrics render shift work invisible. Nevertheless the scope is urban-limited. A rural comparison remains a desideratum. The text questions whether “empty buses” are a neutral measure.",
          [
            q("What do occupancy metrics do, according to the abstract?", "Make shift work invisible", ["Prove causation", "Make shift work invisible", "Raise salaries", "Delete rural areas"]),
            q("What remains a desideratum?", "A rural comparison", ["More slogans", "A rural comparison", "No methods", "A poem"]),
            q("Is “empty buses” treated as neutral?", "It is questioned", ["Yes, fully", "It is questioned", "Not mentioned", "Only in footnotes as true"]),
          ],
        ),
        reading(
          "Limitations paragraph",
          "Limitationen",
          "Einzuräumen ist die urbane Schlagseite des Samples. Übertragbar erscheinen gleichwohl die zeitpolitischen Mechanismen. Die Operationalisierung von „Teilhabe“ über Fahrten nach 21 Uhr ist heuristisch nützlich und normativ voraussetzungsreich. Eine alternative Operationalisierung über verpasste Schichten wäre anschlussfähig. Die Güte unseres Indikators bleibt damit diskussionswürdig, nicht wertlos.",
          "The urban bias of the sample must be admitted. Nevertheless the time-political mechanisms appear transferable. Operationalising “participation” via trips after 9 p.m. is heuristically useful and normatively loaded. An alternative via missed shifts would be connectable. The quality of our indicator thus remains open to discussion, not worthless.",
          [
            q("What bias is admitted?", "Urban sample", ["No interviews", "Urban sample", "Too many villages", "No buses"]),
            q("What is called heuristically useful?", "Trips after 21:00 as participation", ["A slogan", "Trips after 21:00 as participation", "Deleting numbers", "Moralising"]),
            q("Is the indicator called worthless?", "No", ["Yes", "No", "Only in English", "The authors refuse to say"]),
          ],
        ),
        reading(
          "Reviewer comment",
          "Gutachten",
          "Der Beitrag strotzt vor Nominalstil, wo Verben präziser wären. Die These ist tragfähig, die kausale Sprache an drei Stellen zu stark („führt zu“ statt „geht einher mit“). Bitte Forschungsstand um die Pendelstudien 2022 ergänzen. Gleichwohl: die Lücke wird klar markiert. Annahme nach Revision.",
          "The paper is stiff with nominal style where verbs would be more precise. The thesis is viable; the causal language is too strong in three places (“leads to” instead of “goes along with”). Please add the 2022 commuting studies to the literature. Nevertheless: the gap is clearly marked. Accept after revision.",
          [
            q("What stylistic problem is named?", "Too much nominal style", ["No thesis", "Too much nominal style", "Wrong language", "No abstract"]),
            q("What causal wording is too strong?", "führt zu", ["geht einher mit", "führt zu", "legt nahe", "einräumen"]),
            q("Decision?", "Accept after revision", ["Reject", "Accept after revision", "Ignore", "Publish as a poem"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write an academic abstract (5 sentences) with one hedge and one limitation.",
          "Schreib ein Abstract.",
          "Gegenstand, Methode, Ergebnis mit „legen nahe“, Reichweite, Desiderat.",
          ["No „beweist“ unless earned", "Name scope"],
        ),
        writing(
          "Turn three causal overclaims into cautious German.",
          "Mach Kausal-Überclaims vorsichtig.",
          "führt zu → geht einher mit / legt nahe / steht in Zusammenhang mit",
          ["Keep the finding", "Drop proof theatre"],
        ),
      ],
    },
  ),
  chapter(
    "advanced-syntax",
    "Advanced Syntax: Fields, Insertion, Emphasis",
    "Fortgeschrittene Syntax: Felder, Einschub, Hervorhebung",
    "Control German sentence topology so emphasis lands where you intend.",
    "grammar",
    [
      "Nachfeld for heavy infinitives and um-zu. Mittelfeld order: time, cause, manner, place — tendency, not law.",
      "Einschübe mit Gedankenstrich oder Klammern. Linksversetzung zur Betonung.",
      "Je-desto, nicht nur-sondern auch, sowohl-als auch without losing the finite verb.",
    ],
    {
      vocab: [
        vocab("das Vorfeld", "the prefield"),
        vocab("das Mittelfeld", "the middle field"),
        vocab("das Nachfeld", "the postfield"),
        vocab("die Topologie", "topology (sentence)"),
        vocab("die Linksversetzung", "left dislocation"),
        vocab("die Rechtsversetzung", "right dislocation"),
        vocab("der Einschub", "the insertion", undefined, "Einschübe"),
        vocab("die Ausklammerung", "exbraciation / afterthought placement"),
        vocab("betonen", "to emphasise"),
        vocab("nachstellen", "to postpose"),
        vocab("voranstellen", "to prepose"),
        vocab("schwer", "heavy (constituent)"),
        vocab("leicht", "light (constituent)"),
        vocab("die Infinitivgruppe", "the infinitive clause"),
        vocab("der Relativsatz", "the relative clause"),
        vocab("verschachtelt", "nested"),
        vocab("entflechten", "to disentangle"),
        vocab("der Rhythmus", "the rhythm"),
        vocab("die Pause", "the pause"),
        vocab("der Gedankenstrich", "the dash"),
        vocab("sowohl … als auch", "both … and"),
        vocab("weder … noch", "neither … nor"),
        vocab("je … desto", "the … the"),
        vocab("nicht nur … sondern auch", "not only … but also"),
        vocab("um … zu", "in order to"),
        vocab("ohne … zu", "without …-ing"),
        vocab("anstatt … zu", "instead of …-ing"),
        vocab("die Kohärenz", "coherence"),
        vocab("die Kohäsion", "cohesion"),
        vocab("der Anschluss", "the connection"),
        vocab("markiert", "marked (word order)"),
        vocab("unmarkiert", "unmarked"),
      ],
      phrases: [
        phrase("Den letzten Bus — den brauchen Schichtarbeiter, nicht Touristen.", "The last bus — that is what shift workers need, not tourists."),
        phrase("Es kommt darauf an, den Takt zu halten, nicht die Karte zu bemalen.", "What matters is keeping the frequency, not colouring the map."),
        phrase("Je genauer wir messen, desto politischer wird die Kennzahl.", "The more precisely we measure, the more political the metric becomes."),
        phrase("Sowohl Kosten als auch Teilhabe gehören in denselben Satz, nicht in zwei Kriege.", "Both costs and participation belong in the same sentence, not in two wars."),
        phrase("Weder Moral noch Spott ersetzen eine Zahl.", "Neither morals nor mockery replace a figure."),
        phrase("Wir kürzen, ohne den Abend zu streichen.", "We cut without deleting the evening."),
        phrase("Anstatt zu predigen, legen wir die Operationalisierung offen.", "Instead of preaching we disclose the operationalisation."),
        phrase("Um Leser zu halten, gehört Schweres ins Nachfeld.", "To keep readers, heavy material belongs in the postfield."),
        phrase("Unmarkiert: Ich habe gestern im Büro den Bericht gelesen.", "Unmarked: I read the report in the office yesterday."),
        phrase("Markiert: Gestern habe ich im Büro den Bericht gelesen.", "Marked: Yesterday I read the report in the office."),
        phrase("Ein Einschub — und das ist entscheidend — rettet den Satz nicht, wenn das Verb fehlt.", "An insertion — and this is decisive — does not save the sentence if the verb is missing."),
        phrase("Entflechte, bevor du schmückst.", "Disentangle before you decorate."),
      ],
      sentences: [
        sentence("Nachfeld: Sie hat versucht, den Fahrplan so zu lesen, dass Schicht und Takt zusammenpassen.", "Postfield: She tried to read the timetable so that shift and frequency fit."),
        sentence("Ausklammerung ist höflich zum Ohr, nicht faul zum Geist.", "Exbraciation is polite to the ear, not lazy to the mind."),
        sentence("Linksversetzung macht das Thema zum Rahmen: Die Linie 8, die lassen wir.", "Left dislocation makes the topic a frame: line 8, that we keep."),
        sentence("Rechtsversetzung klingt gesprochen: Die lassen wir, die Linie 8.", "Right dislocation sounds spoken: that we keep, line 8."),
        sentence("Leichte Pronomen stehen früh, schwere Präpositionalgruppen später.", "Light pronouns come early, heavy prepositional phrases later."),
        sentence("Verschachtelte Relativsätze entflechtet man in zwei Sätze, nicht in mehr Kommas.", "Nested relatives are disentangled into two sentences, not more commas."),
        sentence("Kohäsion entsteht durch Wiederaufnahme, nicht durch Synonymakrobatik.", "Cohesion comes from pickup, not synonym acrobatics."),
        sentence("Kohärenz ist die unsichtbare These zwischen den Absätzen.", "Coherence is the invisible thesis between paragraphs."),
        sentence("Der Anschluss „dabei“ rettet einen Absatz, der sonst kippt.", "The connective “dabei” saves a paragraph that would otherwise tip."),
        sentence("Je mehr Einschübe, desto weniger Atem.", "The more insertions, the less breath."),
        sentence("Nicht nur der Takt, sondern auch die Umsteigezeit entscheidet über den Feierabend.", "Not only frequency but also transfer time decides the evening off."),
        sentence("Ohne zu übertreiben: Topologie ist Stilpolitik.", "Without exaggerating: topology is style politics."),
        sentence("Um zu betonen, stellen wir Zeit nach vorn — und zahlen mit Überraschung.", "To emphasise, we put time first — and pay with surprise."),
        sentence("Anstatt alles ins Vorfeld zu stopfen, opfern wir ein Adverb.", "Instead of stuffing everything into the prefield, we sacrifice an adverb."),
        sentence("Sowohl das Ohr als auch das Auge wollen Pausen.", "Both ear and eye want pauses."),
        sentence("Weder Vorfeld-Chaos noch Mittelfeld-Stau ist C1.", "Neither prefield chaos nor middle-field congestion is C1."),
        sentence("Markierte Stellung braucht einen Grund, sonst wirkt sie nervös.", "Marked order needs a reason, otherwise it seems nervous."),
        sentence("Rhythmus merkt man, wenn man den Satz laut liest — bitte tun.", "You notice rhythm when you read the sentence aloud — please do."),
      ],
      readings: [
        reading(
          "Same content, three topologies",
          "Gleicher Inhalt, drei Topologien",
          "A unmarkiert: Die Stadt hat gestern den Abendtakt gekürzt. B betont Zeit: Gestern hat die Stadt den Abendtakt gekürzt. C Nachfeld-schwer: Die Stadt hat gekürzt, und zwar den Abendtakt in der Industriezone nach 21 Uhr. C trägt die Information, die A versteckt. Wer C immer schreibt, ermüdet. Wer nie C schreibt, versteckt Politik im Mittelfeld.",
          "A unmarked: The city cut evening frequency yesterday. B time-fronted: Yesterday the city cut evening frequency. C heavy postfield: The city cut — namely evening frequency in the industrial zone after 9 p.m. C carries information A hides. Anyone who always writes C tires readers. Anyone who never writes C hides politics in the middle field.",
          [
            q("What does version C add?", "Industrial zone after 21:00", ["A joke", "Industrial zone after 21:00", "A new city", "Nothing"]),
            q("What is the risk of always using C?", "Reader fatigue", ["Illegal German", "Reader fatigue", "No verbs", "Automatic truth"]),
            q("What does never using C do?", "Hide politics in the middle field", ["Win prizes", "Hide politics in the middle field", "Delete buses", "Fix grammar"]),
          ],
        ),
        reading(
          "Insertion abuse",
          "Einschub-Missbrauch",
          "„Die Linie — und das hat, wie Kolleginnen, deren Kinder Schicht arbeiten, längst, ohne dass jemand zuhörte, gesagt — bleibt.“ Der Satz atmet nicht. Entflechtung: Kolleginnen mit Kindern in Schicht haben das gesagt. Niemand hörte zu. Die Linie bleibt. Gedankenstriche sind Pausen, keine Müllhalden.",
          "A sentence stuffed with dashes and relatives does not breathe. Disentangling: colleagues with children on shifts said so. Nobody listened. The line stays. Dashes are pauses, not dumps.",
          [
            q("What are dashes for?", "Pauses", ["Dumping clauses", "Pauses", "Hiding verbs", "Legal codes"]),
            q("How many sentences after disentangling?", "Three", ["Still one", "Three", "Ten", "Zero"]),
            q("Did anyone listen, in the rewrite?", "No", ["Yes, the mayor", "No", "The children", "Unstated"]),
          ],
        ),
        reading(
          "je desto under control",
          "je-desto",
          "Je unsichtbarer die Schicht, desto politischer die scheinbar neutrale Auslastung. Der Satz trägt zwei Komparative und ein finites Verb am Ende des zweiten Teils. Fehler: „Je unsichtbarer die Schicht, die Auslastung politischer.“ Ohne desto kippt die Konstruktion. C1 heißt: die Form halten, wenn der Inhalt scharf wird.",
          "The more invisible the shift, the more political the seemingly neutral occupancy. The sentence carries two comparatives and a finite verb at the end of the second part. Error: dropping desto. Without it the construction collapses. C1 means holding the form when the content gets sharp.",
          [
            q("What happens without desto?", "The construction collapses", ["It sounds more poetic", "The construction collapses", "It's more C2", "Nothing"]),
            q("Where is the finite verb in the second part?", "At the end", ["At the front always", "At the end", "Deleted", "In English"]),
            q("What should you hold when content is sharp?", "The form", ["Your breath only", "The form", "A grudge", "The microphone"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write four versions of one proposition with different fields emphasised.",
          "Schreib vier Topologie-Varianten.",
          "Unmarkiert / Zeit vorne / Objekt vorne / Nachfeld-schwer. Dieselbe Proposition.",
          ["Read them aloud"],
        ),
        writing(
          "Disentangle one overloaded sentence into three.",
          "Entflechte einen Satz.",
          "Einschübe raus, Relativsätze zu Hauptsätzen, ein Nachfeld behalten.",
          ["Keep all information"],
        ),
      ],
    },
  ),
  chapter(
    "registers-style",
    "Register, Style & Audience Design",
    "Register, Stil und Adressatendesign",
    "Shift the same content across colloquial, press, academic, and administrative German.",
    "writing",
    [
      "Audience design: who can punish you for the wrong tone?",
      "Features: address, modality, nominalisation, loanwords, humour.",
      "Ethics: translating down should not mean translating away the conflict.",
    ],
    {
      vocab: [
        vocab("das Register", "register"),
        vocab("der Stil", "style"),
        vocab("die Adressatin", "the addressee (f)"),
        vocab("die Distanz", "distance"),
        vocab("die Nähe", "closeness"),
        vocab("das Prestige", "prestige"),
        vocab("umgangssprachlich", "colloquial"),
        vocab("bildungssprachlich", "educated standard"),
        vocab("fachsprachlich", "technical"),
        vocab("verwaltungssprachlich", "administrative"),
        vocab("die Nominalisierung", "nominalisation"),
        vocab("verbalisieren", "to verbalise"),
        vocab("das Lehnwort", "the loanword", undefined, "Lehnwörter"),
        vocab("eindeutschen", "to germanise"),
        vocab("der Jargon", "jargon"),
        vocab("die Verständlichkeit", "comprehensibility"),
        vocab("die Genauigkeit", "precision"),
        vocab("der Humor", "humour"),
        vocab("die Ironie", "irony"),
        vocab("riskant", "risky"),
        vocab("angemessen", "appropriate"),
        vocab("unangemessen", "inappropriate"),
        vocab("herablassend", "condescending"),
        vocab("einschließen", "to include"),
        vocab("ausschließen", "to exclude"),
        vocab("die Übersetzung", "the translation / transfer"),
        vocab("die Zielgruppe", "the target group"),
        vocab("sanktionieren", "to sanction"),
        vocab("das Gesicht wahren", "to save face"),
        vocab("die Höflichkeitsstufe", "the politeness level"),
        vocab("tonal", "tonal"),
        vocab("stilistisch markiert", "stylistically marked"),
      ],
      phrases: [
        phrase("Umgangssprachlich: Der letzte Bus fällt oft aus, das nervt.", "Colloquial: The last bus often doesn’t run, it’s annoying."),
        phrase("Pressesprache: Der Abendtakt gilt als unzuverlässig.", "Press: Evening frequency is considered unreliable."),
        phrase("Akademisch: Die Ausfallwahrscheinlichkeit des Abendtakts ist erhöht.", "Academic: The probability of evening-service cancellation is elevated."),
        phrase("Amtlich: Es wird darauf hingewiesen, dass Abweichungen möglich sind.", "Official: It is pointed out that deviations are possible."),
        phrase("Herablassend wäre: „Das versteht ihr schon, wenn ihr größer seid.“", "Condescending would be: “You’ll understand when you’re older.”"),
        phrase("Einschließen heißt, Jargon zu erklären, nicht zu streichen, was weh tut.", "Including means explaining jargon, not deleting what hurts."),
        phrase("Ironie sanktioniert das Publikum, das sie nicht teilt.", "Irony sanctions the audience that does not share it."),
        phrase("Genauigkeit und Verständlichkeit sind ein Zielkonflikt, kein Moralduell.", "Precision and comprehensibility are a trade-off, not a moral duel."),
        phrase("Lehnwörter tragen Prestige und schließen aus.", "Loanwords carry prestige and exclude."),
        phrase("Gesicht wahren: Kritik an der Kennzahl, nicht an der Person.", "Saving face: criticise the metric, not the person."),
        phrase("Die Höflichkeitsstufe wechselt mit der Machtasymmetrie.", "Politeness level shifts with the power asymmetry."),
        phrase("Stilistisch markiert darf sein, was bewusst sitzt.", "Stylistically marked may be what sits there on purpose."),
      ],
      sentences: [
        sentence("Wer das Register verfehlt, wird nicht immer korrigiert, sondern übergangen.", "Anyone who misses the register is not always corrected but passed over."),
        sentence("Verwaltungssprache schützt die Behörde und ermüdet die Bürgerin.", "Administrative language protects the authority and tires the citizen."),
        sentence("Verbalisieren Sie Amtsnominalstil, wenn Sie überzeugen wollen, nicht wenn Sie haften.", "Verbalise official nominal style when you want to persuade, not when you are liable."),
        sentence("Fachsprache ist präzise unter Eingeweihten und roh außerhalb.", "Technical language is precise among insiders and raw outside."),
        sentence("Bildungssprache erlaubt Schachtelsätze; sie verpflichtet nicht dazu.", "Educated standard allows nested sentences; it does not oblige you to them."),
        sentence("Umgangssprache im Protokoll ist ein Stilbruch mit Folgen.", "Colloquial language in minutes is a style break with consequences."),
        sentence("Humor in der Krisenmail ist tonal riskant.", "Humour in a crisis email is tonally risky."),
        sentence("Eine Übersetzung nach „einfach“ darf den Konflikt nicht entsorgen.", "A translation into “simple” must not dispose of the conflict."),
        sentence("Zielgruppe „alle“ ist oft die Zielgruppe „niemand Konkretes“.", "Target group “everyone” is often target group “no one in particular”."),
        sentence("Sanktionen für falschen Ton sind informell: Einladungen bleiben aus.", "Sanctions for wrong tone are informal: invitations stop."),
        sentence("Nähe simulieren, wo Distanz geboten ist, wirkt übergriffig.", "Simulating closeness where distance is required feels invasive."),
        sentence("Distanz, wo Nähe erwartet wird, wirkt kalt, nicht professionell.", "Distance where closeness is expected feels cold, not professional."),
        sentence("Jargon zu eindeutschen hilft, wenn das deutsche Wort trägt.", "Germanising jargon helps when the German word carries the load."),
        sentence("Angemessenheit misst man an Macht, Zeit und Medium.", "Appropriateness is measured by power, time and medium."),
        sentence("Unangemessen ist nicht dasselbe wie unhöflich — manchmal ist es nur falsch informiert.", "Inappropriate is not the same as impolite — sometimes it is only misinformed."),
        sentence("Adressatendesign beginnt vor dem ersten Satz: Wer liest unter Zeitdruck?", "Audience design starts before the first sentence: who reads under time pressure?"),
        sentence("Tonal halten heißt, nicht in Absatz drei plötzlich zu spotten.", "Keeping tone means not suddenly mocking in paragraph three."),
        sentence("C1 zeigt sich, wenn Sie dieselbe These viermal anders tragen.", "C1 shows when you carry the same thesis four different ways."),
      ],
      readings: [
        reading(
          "Four registers, one fact",
          "Vier Register, ein Fakt",
          "Fakt: Die Linie 8 fällt donnerstags oft nach 21 Uhr aus. Freund: „8er ist donnerstags abends ein Lotteriespiel.“ Zeitung: „Der Abendverkehr der Linie 8 gilt als störanfällig.“ Paper: „Die Ausfallhäufigkeit der Linie 8 nach 21 Uhr ist donnerstags erhöht.“ Amt: „Auf witterungs- und personalbedingte Abweichungen im Abendverkehr wird hingewiesen.“ Der Konflikt bleibt in 1–3, in 4 verschwindet er hinter „Abweichungen“.",
          "Fact: line 8 often fails after 9 p.m. on Thursdays. Friend / paper / academic / official versions. The conflict remains in 1–3; in 4 it disappears behind “deviations”.",
          [
            q("Where does the conflict disappear?", "In the official version", ["In the friend's version", "In the official version", "In the newspaper", "In the paper"]),
            q("Which version uses “Lotteriespiel”?", "The friend's", ["The authority", "The friend's", "The abstract", "None"]),
            q("What word hides cancellations in Amtsdeutsch?", "Abweichungen", ["Lotteriespiel", "Abweichungen", "Linie 8", "Donnerstag"]),
          ],
        ),
        reading(
          "Easy language ethics",
          "Leichte Sprache, Ethik",
          "Leichte Sprache: „Der Bus fährt abends oft nicht. Das ist schlecht für Menschen, die nachts arbeiten.“ Das ist klar. Unethisch wäre: „Der Bus fährt nicht. Such dir ein Auto.“ Verständlichkeit ohne Handlungsoption für Menschen ohne Auto ist keine Inklusion. Erklären, nicht entsorgen.",
          "Easy language: “The bus often does not run in the evening. That is bad for people who work at night.” That is clear. Unethical would be: “The bus does not run. Get a car.” Comprehensibility without an option for people without a car is not inclusion. Explain, don’t dispose.",
          [
            q("What would be unethical?", "Telling people to just get a car", ["Using short sentences", "Telling people to just get a car", "Naming night work", "Explaining cancellations"]),
            q("What is inclusion here?", "Explain without deleting the conflict", ["Delete night workers", "Explain without deleting the conflict", "Only use English", "Jargon for all"]),
            q("Is the easy-language version called clear?", "Yes", ["No, illegal", "Yes", "Only for children", "The text forbids it"]),
          ],
        ),
        reading(
          "Face and critique",
          "Gesicht und Kritik",
          "In der Abteilungsmail: „Die Kennzahl Auslastung 22 Uhr ist ungeeignet, Schicht abzubilden.“ Nicht: „Ihr habt das wieder nicht kapiert.“ Erster Satz sanktioniert eine Methode. Zweiter Satz sanktioniert Personen. Prestige rettet man, indem man die Klügeren ins Wir holt: „Lasst uns die Kennzahl um Schichtanteile ergänzen.“",
          "In the department email: criticise the 10 p.m. occupancy metric, not the people. The first sentence sanctions a method. The second sanctions persons. You save prestige by bringing the smarter move into a we: let’s add shift shares to the metric.",
          [
            q("What should you criticise?", "The metric", ["The people", "The metric", "The font", "Night itself"]),
            q("What does the we-move do?", "Save face / include", ["Hide the problem", "Save face / include", "Fire staff", "Delete numbers"]),
            q("What does “Ihr habt das nicht kapiert” sanction?", "Persons", ["Only methods", "Persons", "Buses", "Grammar"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Rewrite one fact in four registers (2 sentences each).",
          "Schreib einen Fakt in vier Registern.",
          "Umgang, Presse, akademisch, amtlich. Denselben Konflikt nicht im Amtssatz löschen.",
          ["Mark each register"],
        ),
        writing(
          "Rewrite a condescending sentence so it keeps the demand.",
          "Schreib herablassend um, Forderung bleibt.",
          "Nicht: „Das merkt ihr schon.“ Sondern: konkrete Zahl + nächster Schritt + Angebot zur Erklärung.",
          ["No fake closeness"],
        ),
      ],
    },
  ),
  chapter(
    "philosophy",
    "Philosophy & Conceptual Distinctions",
    "Philosophie und begriffliche Unterscheidungen",
    "Read short argumentative passages, then draw distinctions that do work.",
    "reading",
    [
      "Unterscheide deskriptiv/normativ, Ursache/Grund, Freiheit von/zu.",
      "Begriffsarbeit: nicht Synonyme stapeln, sondern Gebrauch zeigen.",
      "Ein Einwand vorwegnehmen ist stärker als ein Beleidigen der Gegenseite.",
    ],
    {
      vocab: [
        vocab("der Begriff", "the concept", undefined, "Begriffe"),
        vocab("die Unterscheidung", "the distinction", undefined, "Unterscheidungen"),
        vocab("deskriptiv", "descriptive"),
        vocab("normativ", "normative"),
        vocab("der Grund", "the reason", undefined, "Gründe"),
        vocab("die Ursache", "the cause"),
        vocab("die Freiheit", "freedom"),
        vocab("die Autonomie", "autonomy"),
        vocab("die Verantwortung", "responsibility"),
        vocab("die Gerechtigkeit", "justice"),
        vocab("die Fairness", "fairness"),
        vocab("das Recht", "the right"),
        vocab("die Pflicht", "the duty"),
        vocab("der Anspruch", "the claim", undefined, "Ansprüche"),
        vocab("widerspruchsfrei", "consistent"),
        vocab("zirkulär", "circular"),
        vocab("voraussetzen", "to presuppose"),
        vocab("ableiten", "to derive"),
        vocab("rechtfertigen", "to justify"),
        vocab("einwenden", "to object"),
        vocab("entgegnen", "to reply"),
        vocab("die Prämisse", "the premise"),
        vocab("die Konklusion", "the conclusion"),
        vocab("gültig", "valid (argument)"),
        vocab("schlüssig", "sound / conclusive"),
        vocab("die Intuition", "intuition"),
        vocab("das Gedankenexperiment", "the thought experiment"),
        vocab("die Grenze", "the limit / boundary"),
        vocab("anerkennen", "to recognise / acknowledge"),
        vocab("zuschreiben", "to ascribe"),
        vocab("der Gebrauch", "the use (of a word)"),
        vocab("leer", "empty (of a formula)"),
      ],
      phrases: [
        phrase("Freiheit von Zwang ist nicht schon Freiheit zur Teilhabe.", "Freedom from coercion is not yet freedom to participate."),
        phrase("Ein Grund rechtfertigt; eine Ursache erklärt.", "A reason justifies; a cause explains."),
        phrase("Der Schluss ist gültig, die Prämissen sind bestreitbar.", "The inference is valid, the premises are contestable."),
        phrase("Zirkulär wird es, wenn Teilhabe durch Busfahrten definiert und dann „bewiesen“ wird.", "It becomes circular if participation is defined as bus rides and then “proved”."),
        phrase("Intuitionen sind Daten, keine Urteile letzter Instanz.", "Intuitions are data, not judgements of last resort."),
        phrase("Ein Gedankenexperiment testet Begriffe, nicht die Fahrpläne.", "A thought experiment tests concepts, not timetables."),
        phrase("Wer Verantwortung zuschreibt, muss Zurechnungsfähigkeit klären.", "Anyone who ascribes responsibility must clarify imputability."),
        phrase("Leere Formeln: „Die Würde gebietet, dass …“ — gebietet was genau?", "Empty formulae: “Dignity requires that …” — requires what exactly?"),
        phrase("Ich wende ein, dass Kostenfolgen moralische Ansprüche nicht auslöschen.", "I object that cost consequences do not erase moral claims."),
        phrase("Entgegnung: Ansprüche ohne Adressaten sind Appelle an den Nebel.", "Reply: claims without addressees are appeals to fog."),
        phrase("Anerkennen heißt nicht, jeden Wunsch zu erfüllen.", "To acknowledge is not to fulfil every wish."),
        phrase("Der Gebrauch von „Gerechtigkeit“ schwankt zwischen Fairness und Gleichheit.", "The use of “justice” oscillates between fairness and equality."),
      ],
      sentences: [
        sentence("Deskriptiv ist die Auslastung um 22 Uhr niedrig; normativ folgt daraus nichts ohne Prämisse.", "Descriptively occupancy at 10 p.m. is low; normatively nothing follows without a premise."),
        sentence("Autonomie ohne Optionen ist ein Titel ohne Amt.", "Autonomy without options is a title without an office."),
        sentence("Fairness kann Ungleichheit erlauben, die Gerechtigkeit im engeren Sinn nicht.", "Fairness can allow inequality that justice in the strict sense cannot."),
        sentence("Ein Recht ohne durchsetzbare Pflicht bleibt rhetorisch.", "A right without an enforceable duty remains rhetorical."),
        sentence("Ansprüche richten sich an Institutionen, nicht an das Wetter.", "Claims are addressed to institutions, not to the weather."),
        sentence("Widerspruchsfrei ist eine Position, die Kosten und Nutzen derselben Gruppe zuordnet.", "A position is consistent if it assigns costs and benefits to the same group."),
        sentence("Vorausgesetzt wird oft, Zeit sei beliebig teilbar — Schicht widerlegt das.", "It is often presupposed that time is arbitrarily divisible — shifts refute that."),
        sentence("Ableiten darf man nur, was in den Prämissen schon schlummert.", "One may derive only what already slumbers in the premises."),
        sentence("Rechtfertigen ist öffentlicher als Erklären.", "Justifying is more public than explaining."),
        sentence("Die Konklusion „also streichen“ folgt nicht aus „also teuer“.", "The conclusion “so scrap it” does not follow from “so expensive”."),
        sentence("Gültig und unwahr vertragen sich; schlüssig verlangt wahre Prämissen.", "Valid and untrue can coexist; soundness requires true premises."),
        sentence("Grenzen der Analogie Stadt/Familie: man kündigt Bürgerinnen nicht.", "Limits of the city/family analogy: one does not dismiss citizens."),
        sentence("Wer Freiheit nur negativ denkt, hält den leeren Bahnsteig für Neutralität.", "Anyone who thinks freedom only negatively treats the empty platform as neutrality."),
        sentence("Positive Freiheit braucht Infrastruktur — das ist eine These, kein Gefühl.", "Positive freedom needs infrastructure — that is a thesis, not a feeling."),
        sentence("Begriffe schärfen heißt Gebrauchsfälle sammeln, nicht Etymologie beten.", "Sharpening concepts means collecting use-cases, not praying etymology."),
        sentence("Ein leerer Begriff erklärt jeden Ausgang und deshalb keinen.", "An empty concept explains every outcome and therefore none."),
        sentence("Philosophie auf C1: langsam werden, wo andere beschleunigen.", "Philosophy at C1: slow down where others speed up."),
        sentence("Unterscheidungen, die keine Entscheidung ändern, sind Ornament.", "Distinctions that change no decision are ornament."),
      ],
      readings: [
        reading(
          "Freedom from / freedom to",
          "Freiheit von / Freiheit zu",
          "Man kann frei von Fahrverboten sein und unfrei zur Schicht, weil kein Bus fährt. Negative Freiheit zählt Eingriffe; positive Freiheit zählt gangbare Wege. Wer nur die erste kennt, hält Streichung für Neutralität. Wer nur die zweite kennt, ignoriert Kosten. Die Unterscheidung ändert die Last der Begründung: Neutralität muss man verdienen, nicht behaupten.",
          "One can be free from driving bans and unfree to reach a shift because no bus runs. Negative freedom counts interferences; positive freedom counts practicable paths. Anyone who knows only the first treats cancellation as neutrality. Anyone who knows only the second ignores costs. The distinction changes the burden of justification: neutrality must be earned, not asserted.",
          [
            q("What does negative freedom count?", "Interferences", ["Practicable paths", "Interferences", "Ticket prices only", "Happiness"]),
            q("What does treating cancellation as neutrality assume?", "Only negative freedom", ["Only positive freedom", "Only negative freedom", "No philosophy", "Free taxis"]),
            q("What must be earned?", "Neutrality", ["A bus company", "Neutrality", "A poem", "A ban on shifts"]),
          ],
        ),
        reading(
          "Circular participation",
          "Zirkuläre Teilhabe",
          "Wenn Teilhabe als „Busfahrten nach 21 Uhr“ definiert wird, „beweist“ jede Fahrt Teilhabe. Das ist zirkulär. Besser: Teilhabe als Möglichkeit, zugesagte Arbeit zu erreichen, ohne unverhältnismäßige Kosten. Dann sind Fahrten Indikator, nicht Definition. Einwände gegen den Indikator bleiben möglich, ohne den Wert zu leugnen.",
          "If participation is defined as “bus trips after 9 p.m.”, every trip “proves” participation. That is circular. Better: participation as the possibility of reaching agreed work without disproportionate cost. Then trips are an indicator, not the definition. Objections to the indicator remain possible without denying the value.",
          [
            q("Why is the first definition circular?", "Trips define and then prove participation", ["No buses exist", "Trips define and then prove participation", "It's in English", "Philosophy forbids buses"]),
            q("What should trips be?", "An indicator", ["The definition", "An indicator", "A duty", "A tax"]),
            q("Can you object to the indicator without denying the value?", "Yes", ["No", "Yes", "Only on Sundays", "The text forbids objections"]),
          ],
        ),
        reading(
          "Valid vs sound",
          "Gültig vs schlüssig",
          "Prämisse 1: Was nicht voll ist, ist überflüssig. Prämisse 2: Der 22-Uhr-Bus ist nicht voll. Konklusion: Er ist überflüssig. Gültig. Unschlüssig, weil Prämisse 1 falsch ist: Feuerwehren sind selten „voll“ im Sinne von Dauerauslastung. Die Form trägt; die Welt nicht. C1 heißt, beides zu prüfen.",
          "Premise 1: what is not full is superfluous. Premise 2: the 10 p.m. bus is not full. Conclusion: it is superfluous. Valid. Unsound because premise 1 is false: fire brigades are rarely “full” in the sense of constant occupancy. The form holds; the world does not. C1 means checking both.",
          [
            q("Is the argument valid?", "Yes", ["No", "Yes", "Only in Latin", "Invalid because of buses"]),
            q("Why is it unsound?", "Premise 1 is false", ["There is no conclusion", "Premise 1 is false", "Fire brigades are buses", "Grammar"]),
            q("What analogy is used?", "Fire brigades", ["Airlines only", "Fire brigades", "Restaurants", "Poems"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Draw three distinctions and show each with a bus example.",
          "Zieh drei Unterscheidungen.",
          "deskriptiv/normativ; Ursache/Grund; Freiheit von/zu. Je ein Satz Beispiel.",
          ["No synonym stacks"],
        ),
        writing(
          "Write a 6-sentence objection to a circular definition.",
          "Schreib einen Einwand gegen Zirkularität.",
          "Nenne die Definition. Zeige den Zirkel. Biete eine bessere Definition. Halte den Wert fest.",
          ["Calm tone"],
        ),
      ],
    },
  ),
  chapter(
    "history",
    "History, Memory & How the Past Is Told",
    "Geschichte, Erinnerung und Erzählungen der Vergangenheit",
    "Read commemorative and critical texts, then separate event, source, and narrative.",
    "reading",
    [
      "Quelle vs Darstellung. Zeitgenössisch vs rückblickend.",
      "Passive and nominal style in memorial German; ask who is missing.",
      "Erinnerungspolitik: was wird gefeiert, was wird gerahmt, was bleibt Rand?",
    ],
    {
      vocab: [
        vocab("die Quelle", "the source", undefined, "Quellen"),
        vocab("die Darstellung", "the account / portrayal"),
        vocab("zeitgenössisch", "contemporary (to the event)"),
        vocab("rückblickend", "retrospective"),
        vocab("die Erinnerung", "memory", undefined, "Erinnerungen"),
        vocab("das Gedenken", "commemoration"),
        vocab("die Erinnerungspolitik", "politics of memory"),
        vocab("das Narrativ", "the narrative", undefined, "Narrative"),
        vocab("die Meistererzählung", "the master narrative"),
        vocab("brechen", "to break (a narrative)"),
        vocab("die Lücke", "the gap"),
        vocab("überliefern", "to hand down"),
        vocab("verfälschen", "to distort"),
        vocab("kontextualisieren", "to contextualise"),
        vocab("anachronistisch", "anachronistic"),
        vocab("die Epoche", "the epoch", undefined, "Epochen"),
        vocab("die Zäsur", "the caesura / turning point"),
        vocab("kontinuierlich", "continuous"),
        vocab("bruchstückhaft", "fragmentary"),
        vocab("die Zeugenschaft", "testimony / witnessing"),
        vocab("mündlich", "oral"),
        vocab("schriftlich", "written"),
        vocab("das Archiv", "the archive", undefined, "Archive"),
        vocab("die Lücke im Bestand", "the gap in the holdings"),
        vocab("sichtbar machen", "to make visible"),
        vocab("unsichtbar", "invisible"),
        vocab("das Opfer", "the victim", undefined, "Opfer"),
        vocab("der Täter", "the perpetrator"),
        vocab("die Mitläuferin", "the fellow traveller (f)"),
        vocab("verharmlosen", "to play down"),
        vocab("heroisieren", "to heroise"),
        vocab("nüchtern", "sober"),
      ],
      phrases: [
        phrase("Die Quelle sagt weniger, als die Gedenkrede behauptet.", "The source says less than the commemorative speech claims."),
        phrase("Rückblickend ordnen wir Zäsuren, die Zeitgenossen als Alltag erlebten.", "Retrospectively we order caesuras that contemporaries lived as everyday life."),
        phrase("Eine Meistererzählung bricht man mit Randfiguren, nicht mit Lautstärke.", "You break a master narrative with marginal figures, not volume."),
        phrase("Lücken im Archiv sind Befunde, keine Entschuldigungen.", "Gaps in the archive are findings, not excuses."),
        phrase("Zeugenschaft ist situiert: wer durfte sprechen, wer nicht?", "Testimony is situated: who was allowed to speak, who not?"),
        phrase("Anachronistisch ist, heutige Begriffe ungeprüft in die Epoche zu tragen.", "It is anachronistic to carry today’s concepts into the epoch unchecked."),
        phrase("Verharmlosen und Heroisieren sind Geschwister.", "Playing down and heroising are siblings."),
        phrase("Nüchternes Gedenken braucht Namen, Daten, Unsicherheiten.", "Sober commemoration needs names, dates, uncertainties."),
        phrase("Was unsichtbar bleibt, ist oft organisiert unsichtbar.", "What remains invisible is often organised as invisible."),
        phrase("Kontextualisieren heißt nicht entschuldigen.", "To contextualise is not to excuse."),
        phrase("Mündliche Überlieferung trägt Rhythmus; Schrift trägt Datum.", "Oral tradition carries rhythm; writing carries a date."),
        phrase("Die Darstellung wählt einen Rahmen; die Quelle widerspricht manchmal.", "The account chooses a frame; the source sometimes contradicts it."),
      ],
      sentences: [
        sentence("Kontinuität zu behaupten ist selbst eine Erzählentscheidung.", "To claim continuity is itself a narrative decision."),
        sentence("Bruchstückhafte Akten zwingen zur Bescheidenheit der These.", "Fragmentary files force modesty of thesis."),
        sentence("Opfer namentlich nennen, Täter nicht hinter „man“ verstecken.", "Name victims; do not hide perpetrators behind “one”."),
        sentence("Mitläuferinnen verschwinden leicht in der Grammatik des Passivs.", "Fellow travellers disappear easily in the grammar of the passive."),
        sentence("Eine Zäsur ist analytisch nützlich und politisch umkämpft.", "A caesura is analytically useful and politically contested."),
        sentence("Gedenken ohne Konflikt ist Dekoration.", "Commemoration without conflict is decoration."),
        sentence("Erinnerungspolitik zeigt sich an Denkmälern und an Lehrplänen.", "Memory politics shows itself in monuments and in curricula."),
        sentence("Wer überliefert, filtert; das ist kein Skandal, sondern Methode.", "Anyone who hands down filters; that is not a scandal but a method."),
        sentence("Verfälschen beginnt, wo Unsicherheit als Gewissheit verkauft wird.", "Distortion begins where uncertainty is sold as certainty."),
        sentence("Sichtbar machen verpflichtet, die eigene Position zu markieren.", "Making visible obliges you to mark your own position."),
        sentence("Zeitgenössische Zeitungen irren; sie bleiben trotzdem Quellen.", "Contemporary newspapers err; they remain sources nonetheless."),
        sentence("Heroisierte Biografien brauchen Gegenlicht aus dem Archiv.", "Heroised biographies need backlight from the archive."),
        sentence("Nüchtern schreiben schützt vor Kitsch und vor Zynismus.", "Writing soberly protects from kitsch and from cynicism."),
        sentence("Die Lücke im Bestand betrifft oft gerade die, die nicht schreiben durften.", "The gap in the holdings often concerns precisely those who were not allowed to write."),
        sentence("Narrative der „Stunde null“ verdecken Kontinuitäten des Personals.", "Narratives of “zero hour” conceal continuities of personnel."),
        sentence("Geschichte auf C1: langsam datieren, schnell misstrauen.", "History at C1: date slowly, distrust quickly."),
        sentence("Ein Denkmal erklärt selten; es rahmt.", "A monument rarely explains; it frames."),
        sentence("Wer fragt „für wen gilt diese Erinnerung?“, treibt Analyse, nicht Pietätlosigkeit.", "Anyone who asks “for whom does this memory hold?” is doing analysis, not impiety."),
      ],
      readings: [
        reading(
          "Plaque vs file",
          "Tafel vs Akte",
          "Die Tafel sagt: „Hier wirkten mutige Bürger.“ Die Akte nennt drei Namen, zwei davon mit Parteibuch, eines mit Lücke. Mut ist nicht widerlegt. Die Meistererzählung der mutigen Stadt ist zu glatt. Gedenken, das die Lücke mitliest, bleibt nüchterner und genauer. Heroisieren würde die zwei Parteibücher streichen.",
          "The plaque says: “Courageous citizens worked here.” The file names three names, two with party cards, one with a gap. Courage is not refuted. The master narrative of the courageous city is too smooth. Commemoration that reads the gap stays soberer and more precise. Heroising would delete the two party cards.",
          [
            q("How many names does the file give?", "Three", ["None", "Three", "A hundred", "Only the plaque"]),
            q("Does the file refute courage?", "No", ["Yes, totally", "No", "Only on Tuesdays", "The text is silent"]),
            q("What would heroising delete?", "The two party cards", ["The plaque", "The two party cards", "The gap as a finding", "The city"]),
          ],
        ),
        reading(
          "Zero hour",
          "Stunde null",
          "1945 als Stunde null ist ein Narrativ des Neuanfangs. Personalakten zeigen Kontinuitäten in Verwaltungen. Beides kann wahr sein: Zäsur der Gewalt, Kontinuität der Büros. Wer nur das erste feiert, verharmlost das zweite. Wer nur das zweite kennt, sieht keinen Bruch. Quellen zwingen zur Doppelblende.",
          "1945 as zero hour is a narrative of new beginning. Personnel files show continuities in administrations. Both can be true: caesura of violence, continuity of offices. Anyone who only celebrates the first plays down the second. Anyone who only knows the second sees no rupture. Sources force a double exposure.",
          [
            q("What do personnel files show?", "Continuities in administrations", ["No history", "Continuities in administrations", "Only heroes", "Empty cities"]),
            q("What is the recommended view?", "Double exposure of caesura and continuity", ["Only celebration", "Double exposure of caesura and continuity", "Only cynicism", "Delete 1945"]),
            q("What does celebrating only the new beginning do?", "Play down continuity", ["Fix the archive", "Play down continuity", "Name all victims", "End memory politics"]),
          ],
        ),
        reading(
          "Who is missing",
          "Wer fehlt",
          "Im Passiv der Gedenkrede werden Häuser „zerstört“. Täter verschwinden. Opfer werden zu Kollateralsubstantiven. Eine nüchterne Umformulierung setzt Subjekte: Wer befahl, wer schwieg, wer floh, wer blieb. Erinnerungspolitik beginnt bei der Grammatik. Pietät ohne Namen ist bequem.",
          "In the passive of the commemorative speech, houses “are destroyed”. Perpetrators vanish. Victims become collateral nouns. A sober reformulation sets subjects: who ordered, who stayed silent, who fled, who remained. Memory politics begins with grammar. Piety without names is convenient.",
          [
            q("What happens to perpetrators in the passive plaque style?", "They vanish", ["They are listed fully", "They vanish", "They become heroes", "They write the speech"]),
            q("Where does memory politics begin here?", "With grammar", ["With fireworks", "With grammar", "With tourism", "With silence only"]),
            q("What is piety without names called?", "Convenient", ["The only ethical option", "Convenient", "Illegal", "A source"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Rewrite a passive commemorative sentence with agents.",
          "Schreib einen Gedenksatz mit Handelnden.",
          "Nicht: „Es wurde zerstört.“ Sondern: wer, wen, wann, unsicher wo nötig.",
          ["Keep respect", "No hero polish"],
        ),
        writing(
          "Write 8 sentences distinguishing source and narrative on a local memorial.",
          "Trenn Quelle und Narrativ.",
          "Was steht auf der Tafel, was in einer Akte, was ist Rahmen, was ist Lücke.",
          ["Mark uncertainties"],
        ),
      ],
    },
  ),
  chapter(
    "economy",
    "Economy, Globalisation & Distribution",
    "Wirtschaft, Globalisierung und Verteilung",
    "Read economic commentary without swallowing metaphors whole, then argue with units.",
    "mixed",
    [
      "Unterscheide Preis, Kosten, Wert, Schulden, Defizit.",
      "ceteris paribus und externe Effekte auf Deutsch benennen.",
      "Metaphern (Haushalt der schwäbischen Hausfrau) prüfen, nicht nachbeten.",
    ],
    {
      vocab: [
        vocab("die Wirtschaft", "the economy"),
        vocab("die Globalisierung", "globalisation"),
        vocab("die Verteilung", "distribution"),
        vocab("der Preis", "the price"),
        vocab("die Kosten", "the costs"),
        vocab("der Wert", "the value"),
        vocab("die Schulden", "the debt"),
        vocab("das Defizit", "the deficit"),
        vocab("die Inflation", "inflation"),
        vocab("die Produktivität", "productivity"),
        vocab("der Handel", "trade"),
        vocab("der Zoll", "the tariff", undefined, "Zölle"),
        vocab("die Lieferkette", "the supply chain", undefined, "Lieferketten"),
        vocab("der externe Effekt", "the externality", undefined, "externe Effekte"),
        vocab("ceteris paribus", "other things equal"),
        vocab("die Nachfrage", "demand"),
        vocab("das Angebot", "supply"),
        vocab("knapp", "scarce"),
        vocab("die Ungleichheit", "inequality"),
        vocab("das Median", "the median"),
        vocab("das Mittel", "the mean / average"),
        vocab("regressiv", "regressive"),
        vocab("progressiv", "progressive"),
        vocab("subventionieren", "to subsidise"),
        vocab("privatisieren", "to privatise"),
        vocab("die Daseinsvorsorge", "basic public services"),
        vocab("der Haushalt", "the budget / household"),
        vocab("die Metapher", "the metaphor"),
        vocab("hinken", "to limp"),
        vocab("umverteilen", "to redistribute"),
        vocab("der Wohlstand", "prosperity"),
        vocab("prekäre Arbeit", "precarious work"),
      ],
      phrases: [
        phrase("Preis ist nicht Wert; Kosten sind nicht Schulden.", "Price is not value; costs are not debt."),
        phrase("Ein Defizit ist eine Stromgröße, Schulden ein Bestand.", "A deficit is a flow, debt a stock."),
        phrase("Ceteris paribus hält selten, wenn Schichten und Busse zusammenhängen.", "Ceteris paribus rarely holds when shifts and buses are linked."),
        phrase("Externe Effekte der Autofahrt trägt die Lunge der Nebenstraße.", "The externality of driving is borne by the lung of the side street."),
        phrase("Die Metapher vom schwäbischen Haushalt hinkt: Staaten sind keine Küchen.", "The Swabian-housewife metaphor limps: states are not kitchens."),
        phrase("Regressive Tickets treffen Pendlerinnen härter als progressive Steuern.", "Regressive tickets hit commuters harder than progressive taxes."),
        phrase("Subventionen sind politisch; ihre Abwesenheit auch.", "Subsidies are political; their absence is too."),
        phrase("Daseinsvorsorge misst man nicht nur an der Marge.", "Basic public services are not measured only by margin."),
        phrase("Median und Mittel erzählen zwei Städte.", "Median and mean tell two cities."),
        phrase("Lieferketten sind verletzlich, nicht magisch.", "Supply chains are vulnerable, not magical."),
        phrase("Ungleichheit kann steigen, während der Durchschnitt feiert.", "Inequality can rise while the average celebrates."),
        phrase("Prekäre Arbeit exportiert Risiko auf Privatleben und Fahrpläne.", "Precarious work exports risk onto private life and timetables."),
      ],
      sentences: [
        sentence("Globalisierung verdichtet Lieferketten und verlängert politische Verantwortungsketten.", "Globalisation densifies supply chains and lengthens chains of political responsibility."),
        sentence("Zölle sind Preise mit Flagge.", "Tariffs are prices with a flag."),
        sentence("Nachfrage nach Abendbussen ist unsichtbar, wenn man nur Kassenquerschnitte um 22 Uhr liest.", "Demand for evening buses is invisible if one only reads till snapshots at 10 p.m."),
        sentence("Angebot ohne Takt ist ein Linienstrich auf Papier.", "Supply without frequency is a line on paper."),
        sentence("Knappheit von Fahrerinnen ist kein Naturgesetz.", "Scarcity of drivers is not a law of nature."),
        sentence("Umverteilung geschieht auch über Fahrpläne, nicht nur über Steuersätze.", "Redistribution also happens via timetables, not only tax rates."),
        sentence("Wohlstand ohne Zeitwohlstand ist eine halbe Bilanz.", "Prosperity without time prosperity is a half balance sheet."),
        sentence("Privatisieren verschiebt Risiken, löscht sie nicht.", "Privatising shifts risks, does not erase them."),
        sentence("Inflation frisst Tickets anders als Mieten — Einheiten nennen.", "Inflation eats tickets differently from rents — name units."),
        sentence("Produktivität der Pflege lässt sich nicht wie Stückzahlen zählen.", "Care productivity cannot be counted like units of output."),
        sentence("Handel erklärt Preise, nicht Würde.", "Trade explains prices, not dignity."),
        sentence("Ein hinkender Haushaltsvergleich rechtfertigt Kürzungen nicht.", "A limping household comparison does not justify cuts."),
        sentence("Progressive Finanzierung kann regressive Nutzung ausgleichen — oder nicht; das ist empirisch.", "Progressive funding can offset regressive use — or not; that is empirical."),
        sentence("Externe Effekte internalisieren heißt, sie auf Rechnungen setzen, die bisher andere zahlen.", "Internalising externalities means putting them on bills others have paid so far."),
        sentence("Ceteris paribus in der Abendlinie: wenn Schichten wandern, wandert die Nachfrage.", "Ceteris paribus on the evening line: if shifts move, demand moves."),
        sentence("Schulden von Staaten sind nicht die Dispo der WG.", "Government debt is not the overdraft of a flatshare."),
        sentence("Wert der Pünktlichkeit erscheint nicht in der Auslastungs-Excel.", "The value of punctuality does not appear in the occupancy spreadsheet."),
        sentence("Wirtschaftstexte auf C1: Metapher prüfen, Einheit halten, Verlierer benennen.", "Economic texts at C1: check the metaphor, hold the unit, name the losers."),
      ],
      readings: [
        reading(
          "Stock and flow",
          "Bestand und Strom",
          "„Die Stadt ist verschuldet, also darf kein Bus fahren.“ Vermengt Bestand und Strom. Ein Defizit in diesem Jahr sagt wenig über die Linie 8. Investition in Takt kann künftige Kosten der Autofahrt (extern, gesundheitlich) senken. Wer nur den Bestand skandalisiert, spart die Verteilung. Einheiten: Euro pro Jahr, nicht Moral pro Schlagzeile.",
          "“The city is in debt, so no bus may run.” Mixes stock and flow. A deficit this year says little about line 8. Investing in frequency can lower future costs of driving (external, health). Anyone who only scandalises the stock skips distribution. Units: euros per year, not morals per headline.",
          [
            q("What does the slogan mix up?", "Stock and flow", ["Buses and trams", "Stock and flow", "Left and right", "German and English"]),
            q("What unit is recommended?", "Euros per year", ["Morals per headline", "Euros per year", "Empty seats as ethics", "No units"]),
            q("What can frequency investment lower?", "Future external costs of driving", ["The past", "Future external costs of driving", "Gravity", "Memory"]),
          ],
        ),
        reading(
          "The household metaphor",
          "Die Haushaltsmetapher",
          "Die schwäbische Hausfrau kann nicht in eigener Währung Schulden machen und Infrastruktur über Jahrzehnte bauen. Der Vergleich hinkt systematisch. Das heißt nicht, Beliebigkeit sei klug. Es heißt, die Metapher darf die Analyse nicht ersetzen. Daseinsvorsorge ist kein Sonntagsbraten, den man „sich nicht leistet“.",
          "The Swabian housewife cannot issue debt in her own currency and build infrastructure over decades. The comparison limps systematically. That does not mean arbitrariness is wise. It means the metaphor must not replace analysis. Basic public services are not a Sunday roast one “cannot afford”.",
          [
            q("Does the metaphor limp?", "Yes, systematically", ["No, it's perfect", "Yes, systematically", "Only in Swabia", "Unknown"]),
            q("Does rejecting the metaphor mean anything goes?", "No", ["Yes", "No", "The text says spend infinitely", "Only for buses"]),
            q("What are basic public services not?", "A Sunday roast one cannot afford", ["Infrastructure", "A Sunday roast one cannot afford", "Politics", "A tariff"]),
          ],
        ),
        reading(
          "Mean vs median city",
          "Mittel vs Median",
          "Der durchschnittliche Pendler gewinnt zwei Minuten. Der Median verliert den Anschluss. So entstehen zwei Städte in einer Statistik. Ungleichheit der Zeit ist Verteilungspolitik. Wer nur das Mittel feiert, hat die Verliererinnen nicht gezählt. Prekäre Schichten stehen im unteren Quantil, nicht in der Pressemitteilung.",
          "The average commuter gains two minutes. The median loses the connection. Thus two cities appear in one statistic. Inequality of time is distributional politics. Anyone who only celebrates the mean has not counted the losers. Precarious shifts sit in the lower quantile, not in the press release.",
          [
            q("Who gains two minutes?", "The average commuter", ["The median", "The average commuter", "Nobody", "The mayor only"]),
            q("Who loses the connection?", "The median", ["The mean always", "The median", "Tourists", "Excel"]),
            q("Where do precarious shifts sit?", "In the lower quantile", ["In the press release", "In the lower quantile", "In the mean only", "Nowhere"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write 8 sentences on evening buses using stock/flow and one externality.",
          "Schreib mit Bestand/Strom und einem externen Effekt.",
          "Keine Haushaltsmetapher ungeprüft. Eine Einheit durchhalten.",
          ["Name who pays the externality"],
        ),
        writing(
          "Destroy a limping metaphor in four sentences without sneering.",
          "Zerlege eine Metapher ohne Spott.",
          "Wo hinkt sie, was bleibt als echte Frage, welche Einheit stattdessen.",
          ["Calm, precise"],
        ),
      ],
    },
  ),
];
