import { chapter, phrase, q, reading, sentence, vocab, writing } from "@/content/helpers";
import type { ChapterSource } from "@/content/types";

export const c1ChaptersPart2: ChapterSource[] = [
  chapter(
    "arts-criticism",
    "Arts Criticism: Seeing, Hearing, Judging",
    "Kunstkritik: Sehen, Hören, Urteilen",
    "Describe form before verdict, then judge without inflating adjectives.",
    "writing",
    [
      "Erst beobachten, dann werten. Medium nennen: Bühne, Leinwand, Raumklang, Pinselduktus.",
      "Urteil an Kriterien binden, die der Text selbst einführt.",
      "Vermeide Tourismusprosa („einzigartig“, „magisch“) ohne Nachweis am Werk.",
    ],
    {
      vocab: [
        vocab("die Kritik", "criticism / the review"),
        vocab("die Inszenierung", "the production / staging"),
        vocab("der Duktus", "the ductus / stroke"),
        vocab("die Komposition", "the composition"),
        vocab("der Rhythmus", "the rhythm"),
        vocab("die Spannung", "tension"),
        vocab("die Leere", "emptiness"),
        vocab("das Pathos", "pathos"),
        vocab("nüchtern", "sober"),
        vocab("manieriert", "mannered"),
        vocab("präzise", "precise"),
        vocab("ungefähr", "vague / approximate"),
        vocab("das Kriterium", "the criterion", undefined, "Kriterien"),
        vocab("widersprüchlich", "contradictory"),
        vocab("stimmig", "coherent (aesthetically)"),
        vocab("das Register", "register (also musical)"),
        vocab("die Dynamik", "dynamics"),
        vocab("der Raum", "space"),
        vocab("die Fraktion", "the fraction / split (of audience)"),
        vocab("befremden", "to unsettle"),
        vocab("rühren", "to move (emotionally)"),
        vocab("langweilen", "to bore"),
        vocab("überzeugen", "to convince"),
        vocab("das Klischee", "the cliché"),
        vocab("originell", "original"),
        vocab("epigonal", "derivative"),
        vocab("die Pointe", "the punch / point"),
        vocab("zurückhaltend", "restrained"),
        vocab("aufdringlich", "intrusive"),
        vocab("das Werk", "the work", undefined, "Werke"),
        vocab("die Rezeption", "reception"),
        vocab("der Kanon", "the canon"),
      ],
      phrases: [
        phrase("Die Inszenierung hält Distanz, wo das Stück Nähe verlangt — das ist eine These, kein Schimpf.", "The production keeps distance where the play asks for closeness — that is a thesis, not abuse."),
        phrase("Pathos ohne Gegenlicht wird Kitsch.", "Pathos without backlight becomes kitsch."),
        phrase("Nüchternheit kann Härte sein, nicht nur Stilaskese.", "Sobriety can be hardness, not only stylistic asceticism."),
        phrase("Manieriert wirkt, was Geste ohne Notwendigkeit stapelt.", "Mannered is what stacks gesture without necessity."),
        phrase("Ein Kriterium: Bleibt die Spannung in der Leere, oder nur im Lärm?", "One criterion: does tension remain in the emptiness, or only in the noise?"),
        phrase("Die Dynamik ist klein, der Raum groß — das Ohr muss arbeiten.", "The dynamics are small, the space large — the ear must work."),
        phrase("Befremden ist ein Effekt, kein automatischer Wert.", "Alienation is an effect, not an automatic value."),
        phrase("Rühren ohne Erkenntnis ist Werbung.", "Moving without insight is advertising."),
        phrase("Epigonal ist nicht peinlich, wenn der Text es weiß.", "Being derivative is not embarrassing if the text knows it."),
        phrase("Aufdringliche Musik erklärt, was die Szene schon trägt.", "Intrusive music explains what the scene already carries."),
        phrase("Rezeption spaltet sich: die eine Fraktion hört Konzept, die andere Langeweile.", "Reception splits: one faction hears concept, the other boredom."),
        phrase("Kanonkritik beginnt beim eigenen Beifall.", "Canon critique begins with one's own applause."),
      ],
      sentences: [
        sentence("Bevor Sie „schwach“ schreiben, beschreiben Sie drei sichtbare Entscheidungen.", "Before you write “weak”, describe three visible choices."),
        sentence("Komposition meint hier die Ordnung von Licht, nicht nur von Farben.", "Composition here means the order of light, not only of colours."),
        sentence("Der Duktus zittert in den Rändern, nicht in der Mitte — das trägt die Figur.", "The stroke trembles at the edges, not in the centre — that carries the figure."),
        sentence("Ungefähre Adjektive („spannend“, „intensiv“) sind Platzhalter.", "Vague adjectives (“exciting”, “intense”) are placeholders."),
        sentence("Stimmig ist eine Inszenierung, deren Mittel denselben Konflikt dienen.", "A production is coherent if its means serve the same conflict."),
        sentence("Widersprüchlich darf ein Werk sein; unklar über seine Mittel nicht die Kritik.", "A work may be contradictory; criticism may not be unclear about its means."),
        sentence("Langeweile kann das Thema sein; dann muss die Kritik das aushalten, nicht den Abend retten.", "Boredom can be the subject; then criticism must endure it, not rescue the evening."),
        sentence("Überzeugen heißt hier: eine Beobachtung zwingt zur Revision des Vorurteils.", "To convince here means: an observation forces a revision of prejudice."),
        sentence("Klischees der Trauer (Regen, Geige) brauchen Gegengewicht oder Ironie.", "Clichés of mourning (rain, violin) need counterweight or irony."),
        sentence("Originell ist oft die Lücke, nicht der Effekt.", "What is original is often the gap, not the effect."),
        sentence("Die Pointe sitzt spät; wer früher klatscht, hat ein anderes Stück gesehen.", "The point lands late; anyone who claps earlier has seen another play."),
        sentence("Zurückhaltende Regie kann präziser sein als Bewegungsrausch.", "Restrained direction can be more precise than a frenzy of movement."),
        sentence("Das Werk ist nicht die Intention; die Kritik fragt nach dem Gemachten.", "The work is not the intention; criticism asks about what was made."),
        sentence("Kanon ist eine Machtordnung mit Spielplan.", "Canon is an order of power with a season brochure."),
        sentence("Eine Rezension ohne Zitat aus dem Abend ist ein Stimmungstagebuch.", "A review without a citation from the evening is a mood diary."),
        sentence("Registerwechsel auf der Bühne müssen hörbar motiviert sein.", "Register shifts on stage must be audibly motivated."),
        sentence("Leere, die arbeitet, ist nicht dieselbe Leere, die aufgibt.", "Emptiness that works is not the same emptiness that gives up."),
        sentence("C1-Kritik: langsam sehen, knapp urteilen, Kriterien halten.", "C1 criticism: see slowly, judge briefly, hold criteria."),
      ],
      readings: [
        reading(
          "Review excerpt",
          "Rezensionsauszug",
          "Licht bleibt in der ersten Stunde auf den Händen. Gesichter kommen spät. Das ist keine Sparregie, sondern eine Behauptung: Arbeit sieht man am Griff, nicht am Pathos des Blicks. Die Musik hält sich zurück, bis eine einzige Geige das Klischee riskiert — und durch Ironie im Text gebrochen wird. Wer „magisch“ schreibt, hat die Hände nicht beschrieben.",
          "Light stays on the hands in the first hour. Faces come late. That is not cheap direction but a claim: work is seen in the grip, not in the pathos of the gaze. The music holds back until a single violin risks the cliché — and is broken by irony in the text. Anyone who writes “magical” has not described the hands.",
          [
            q("Where does the light stay at first?", "On the hands", ["On faces", "On the hands", "On the violin only", "In the foyer"]),
            q("How is the violin cliché handled?", "Broken by irony in the text", ["Played straight as magic", "Broken by irony in the text", "Cut entirely", "Replaced by rain"]),
            q("What has a writer of “magical” failed to do?", "Describe the hands", ["Buy a ticket", "Describe the hands", "Name the composer", "Clap"]),
          ],
        ),
        reading(
          "Split reception",
          "Geteilte Rezeption",
          "Eine Fraktion hört Konzept in der Langeweile. Die andere hört Unvermögen. Beide können denselben Abend meinen. Kritik muss sagen, welches Kriterium sie anlegt: Stringenz der Leere oder Versorgung des Publikums. Ohne dieses Offenlegen wird aus Geschmack Politik gegen die jeweils andere Fraktion.",
          "One faction hears concept in the boredom. The other hears inability. Both can mean the same evening. Criticism must say which criterion it applies: stringency of emptiness or looking after the audience. Without that disclosure, taste becomes politics against the other faction.",
          [
            q("What must criticism disclose?", "Its criterion", ["The ticket price", "Its criterion", "The actors' salaries", "Nothing"]),
            q("Can both factions mean the same evening?", "Yes", ["No", "Yes", "Only on tour", "The text forbids it"]),
            q("What happens without disclosing criteria?", "Taste becomes factional politics", ["Better art", "Taste becomes factional politics", "Canon ends", "Boredom vanishes"]),
          ],
        ),
        reading(
          "Against tourism prose",
          "Gegen Tourismusprosa",
          "„Einzigartige Reise ins Innere.“ Kein Ort, kein Mittel, kein Risiko. Ersetzen durch: 70 Minuten, ein Raum, drei Stühle, Stimmen aus dem Off, die nie den Raum betreten. Dann darf ein Urteil kommen. Vorher ist die Sprache Souvenir.",
          "“Unique journey into the interior.” No place, no means, no risk. Replace with: 70 minutes, one room, three chairs, offstage voices that never enter. Then a judgement may come. Before that the language is a souvenir.",
          [
            q("What is missing in the tourism sentence?", "Place, means, risk", ["Adjectives", "Place, means, risk", "A star rating", "English"]),
            q("What concrete facts are suggested?", "70 minutes, one room, three chairs, offstage voices", ["A journey to Rome", "70 minutes, one room, three chairs, offstage voices", "Rain and violin", "A buffet"]),
            q("What is the language before a real judgement?", "A souvenir", ["A theorem", "A souvenir", "A law", "A score"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 10-line review: 6 lines observation, 4 lines judgement with one criterion.",
          "Schreib eine Mini-Kritik.",
          "Keine Wörter magisch/einzigartig. Ein Zitat aus dem gedachten Abend.",
          ["Form first", "Named criterion"],
        ),
        writing(
          "Replace five empty adjectives with observations.",
          "Ersetze fünf leere Adjektive.",
          "spannend → was genau knappt die Zeit; intensiv → welche Dynamik, welcher Raum.",
          ["Show, don’t stamp"],
        ),
      ],
    },
  ),
  chapter(
    "admin-legal",
    "Administrative & Legal Language",
    "Verwaltungs- und Rechtssprache",
    "Unpack Amtsdeutsch, then write a letter that would survive an office.",
    "writing",
    [
      "Nominalstil, Passiv, Funktionsverbgefüge (zur Anwendung kommen).",
      "Fristen, Rechtsgrundlagen, Zuständigkeit — ohne sie keine wirksame Bitte.",
      "Höflich bleiben, unbestimmt vermeiden: „zeitnah“ ist kein Datum.",
    ],
    {
      vocab: [
        vocab("die Behörde", "the authority"),
        vocab("der Bescheid", "the official notice", undefined, "Bescheide"),
        vocab("der Widerspruch", "the objection (legal)", undefined, "Widersprüche"),
        vocab("die Frist", "the deadline"),
        vocab("die Rechtsgrundlage", "the legal basis"),
        vocab("zuständig", "competent / responsible"),
        vocab("die Zuständigkeit", "jurisdiction / competence"),
        vocab("der Antrag", "the application", undefined, "Anträge"),
        vocab("bewilligen", "to approve / grant"),
        vocab("ablehnen", "to refuse"),
        vocab("die Begründung", "the statement of reasons"),
        vocab("anhören", "to hear (legally)"),
        vocab("aktenkundig", "on file"),
        vocab("hiermit", "hereby"),
        vocab("in der Anlage", "enclosed"),
        vocab("unbeschadet", "without prejudice to"),
        vocab("soweit", "insofar as"),
        vocab("sofern", "provided that"),
        vocab("unverzüglich", "without delay"),
        vocab("zeitnah", "in a timely manner (vague)"),
        vocab("die Ermessensentscheidung", "the discretionary decision"),
        vocab("gebunden", "bound (by law)"),
        vocab("die Satzung", "the by-law / statute"),
        vocab("das Gesetz", "the statute"),
        vocab("die Verordnung", "the ordinance"),
        vocab("das Funktionsverbgefüge", "light-verb construction"),
        vocab("zur Anwendung kommen", "to be applied"),
        vocab("in Aussicht stellen", "to hold out / indicate"),
        vocab("anheimstellen", "to leave to (stiff)"),
        vocab("die Rechtsbehelfsbelehrung", "information on legal remedies"),
        vocab("förmlich", "formal"),
        vocab("wirksam", "effective / valid"),
      ],
      phrases: [
        phrase("Hiermit lege ich Widerspruch gegen den Bescheid vom 12.03. ein.", "I hereby lodge an objection against the notice of 12 March."),
        phrase("Die Frist endet am 26.03.; bitte den Eingang zu bestätigen.", "The deadline ends on 26 March; please confirm receipt."),
        phrase("Zuständig sein dürfte das Amt für Mobilität, nicht das Ordnungsamt.", "The mobility office is likely competent, not public order."),
        phrase("Als Rechtsgrundlage nennen Sie § … der Satzung; diese Stelle trägt die Ablehnung nicht.", "You cite § … of the by-law as legal basis; that provision does not support the refusal."),
        phrase("Ich bitte um Anhörung, bevor eine Ermessensentscheidung ergeht.", "I request a hearing before a discretionary decision is issued."),
        phrase("In der Anlage: Fahrtennachweis, Schichtplan, ärztliche Bescheinigung.", "Enclosed: travel record, shift plan, medical certificate."),
        phrase("„Zeitnah“ ersetze ich durch den 15. April.", "I replace “in a timely manner” with 15 April."),
        phrase("Unverzüglich bedeutet ohne schuldhaftes Zögern, nicht „irgendwann“.", "Unverzüglich means without culpable delay, not “sometime”."),
        phrase("Soweit die Linie als Daseinsvorsorge gilt, kommt eine reine Margenprüfung nicht zur Anwendung.", "Insofar as the line counts as basic public service, a pure margin test does not apply."),
        phrase("Sofern Unterlagen fehlen, bitte ich um eine konkrete Nachfrist.", "If documents are missing, I request a specific additional deadline."),
        phrase("Die Rechtsbehelfsbelehrung fehlt; der Bescheid ist in diesem Punkt unvollständig.", "The information on remedies is missing; the notice is incomplete on this point."),
        phrase("Förmlich und klar: keine Ironie im Widerspruch.", "Formal and clear: no irony in an objection."),
      ],
      sentences: [
        sentence("Funktionsverbgefüge aufbrechen: zur Durchführung bringen → durchführen.", "Break light-verb constructions: bring to implementation → implement."),
        sentence("Ein Bescheid ohne Begründung ist angreifbar, auch wenn der Ton höflich ist.", "A notice without reasons is challengeable even if the tone is polite."),
        sentence("Aktenkundig machen Sie bitte das Telefongespräch vom Dienstag.", "Please put Tuesday’s phone call on file."),
        sentence("Bewilligung und Ablehnung brauchen dieselbe Sorgfalt in der Sprache.", "Grant and refusal need the same care in language."),
        sentence("Gebundenes Handeln lässt weniger Spiel als Ermessen; das muss der Text zeigen.", "Bound action leaves less room than discretion; the text must show that."),
        sentence("Verordnungen konkretisieren Gesetze; Satzungen die Kommune.", "Ordinances specify statutes; by-laws specify the municipality."),
        sentence("Unbeschadet anderer Ansprüche bleibt der Widerspruch zulässig.", "Without prejudice to other claims the objection remains admissible."),
        sentence("Anheimstellen Sie uns keine Wahl, die keine ist.", "Do not “leave to us” a choice that is not one."),
        sentence("In Aussicht gestellt wurde ein Gespräch, kein Rechtsanspruch.", "A meeting was held out, not a legal entitlement."),
        sentence("Wirksam wird der Widerspruch mit Eingang, nicht mit Stimmung.", "The objection becomes effective on receipt, not on mood."),
        sentence("Förmliche Anrede und konkrete Bitte gehören zusammen.", "Formal address and a concrete request belong together."),
        sentence("„Man sollte prüfen“ ist kein Antrag.", "“One should examine” is not an application."),
        sentence("Die Zuständigkeitsrüge kommt früh, nicht im letzten Satz.", "The objection to jurisdiction comes early, not in the last sentence."),
        sentence("Eine Nachfrist datieren: 14 Tage ab Zugang dieses Schreibens.", "Date an additional deadline: 14 days from receipt of this letter."),
        sentence("Passiv schützt Täter in der Geschichte und Zuständige im Amt — beides markieren.", "Passive protects perpetrators in history and competent officers in offices — mark both."),
        sentence("C1-Amtsdeutsch: entpacken, wenn Sie schreiben; erkennen, wenn Sie lesen.", "C1 official German: unpack when you write; recognise when you read."),
        sentence("Höflichkeit ohne Datum ist Dampf.", "Politeness without a date is steam."),
        sentence("Der letzte Satz nennt die erbetene Handlung in einem Verb.", "The last sentence names the requested action in one verb."),
      ],
      readings: [
        reading(
          "Notice excerpt",
          "Bescheid-Auszug",
          "Ihr Antrag auf Erhalt der Abendlinie wird abgelehnt. Zur Begründung wird auf die unzureichende Auslastung verwiesen. Eine Anhörung ist nicht erfolgt. Rechtsbehelfsbelehrung: Widerspruch innerhalb eines Monats. Zuständig: Amt für Mobilität. Der Bescheid nennt keine Zahl und kein Datum der Messung.",
          "Your application to keep the evening line is refused. The reason given is insufficient occupancy. No hearing took place. Remedies: objection within one month. Competent: mobility office. The notice names no figure and no date of measurement.",
          [
            q("Was a hearing held?", "No", ["Yes", "No", "Only by phone", "The text is silent"]),
            q("What is missing in the reasons?", "A figure and date of measurement", ["The office name", "A figure and date of measurement", "A joke", "English"]),
            q("How long to object?", "One month", ["14 days always", "One month", "A year", "No deadline"]),
          ],
        ),
        reading(
          "Model objection core",
          "Widerspruchskern",
          "Hiermit Widerspruch. Die Auslastungskennziffer nach 21 Uhr bildet Schichtarbeit nicht ab. In der Anlage Schichtpläne. Ich beantrage Anhörung und Auskunft zur Messmethode, Messzeitraum, Zuständigkeit der Erhebung. Fristende bitte bestätigen. Eine Ermessensentscheidung ohne diese Tatsachen ist fehlerhaft.",
          "Objection hereby. The occupancy metric after 9 p.m. does not capture shift work. Shift plans enclosed. I request a hearing and information on method, period, and who collected the data. Please confirm the end of the deadline. A discretionary decision without these facts is flawed.",
          [
            q("What is enclosed?", "Shift plans", ["A poem", "Shift plans", "Cash", "A ticket stub only"]),
            q("What information is requested?", "Method, period, who collected data", ["The mayor's hobby", "Method, period, who collected data", "Bus colour", "Nothing"]),
            q("Why is discretion called flawed?", "Missing facts", ["Rude tone", "Missing facts", "No stamp", "Wrong font"]),
          ],
        ),
        reading(
          "Unpacking a light verb",
          "Funktionsverb entpackt",
          "Amt: „Eine Prüfung der Angelegenheit wird zeitnah zur Durchführung gebracht.“ Klartext: Wir prüfen den Fall. Datum fehlt. C1-Antwort: Bitte teilen Sie bis zum 15.04. das Ergebnis mit. Wer entpackt, macht Macht sichtbar, die im Nominalstil dämpft.",
          "Official: “An examination of the matter will be brought to implementation in a timely manner.” Plain: We will examine the case. Date missing. C1 reply: Please communicate the result by 15 April. Anyone who unpacks makes visible power that nominal style muffles.",
          [
            q("What is missing in the official sentence?", "A date", ["A verb", "A date", "The word Prüfung", "German"]),
            q("What does unpacking do?", "Make power visible", ["Delete the office", "Make power visible", "Win a prize", "End the case"]),
            q("What deadline does the C1 reply set?", "15 April", ["Zeitnah", "15 April", "Never", "One month always"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a one-page objection (short) with legal basis placeholder, facts, request, date.",
          "Schreib einen knappen Widerspruch.",
          "Hiermit, Bescheiddatum, warum die Begründung trägt nicht, Anlage, Anhörung, Fristbestätigung, ein Verb als Bitte.",
          ["No irony", "No zeitnah"],
        ),
        writing(
          "Unpack five Amtsdeutsch sentences into verbs and dates.",
          "Entpacke fünf Amtssätze.",
          "zur Anwendung kommen, in Aussicht stellen, zeitnah, unbeschadet, aktenkundig — je ein Klartextsatz.",
          ["Keep the legal force"],
        ),
      ],
    },
  ),
  chapter(
    "journalism",
    "Journalism & Rhetoric in the News",
    "Journalismus und Rhetorik der Nachrichten",
    "Separate report, analysis, and comment; then write a lead that does not shout.",
    "writing",
    [
      "Lead: wer, was, wann, wo; warum oft später. Keine Pointe vor den Fakten.",
      "Rhetorik: Wiederholung, Dreierfigur, Scheinfrage, Rahmen.",
      "Transparenz: kenntlich machen, was Schätzung, was Beleg, was Meinung ist.",
    ],
    {
      vocab: [
        vocab("die Meldung", "the news item"),
        vocab("die Analyse", "the analysis"),
        vocab("der Kommentar", "the comment"),
        vocab("der Lead", "the lead"),
        vocab("die Pointe", "the kicker"),
        vocab("die Dreierfigur", "the triad / tricolon"),
        vocab("die Scheinfrage", "the rhetorical question"),
        vocab("der Rahmen", "the frame"),
        vocab("die Schätzung", "the estimate"),
        vocab("belegt", "evidenced"),
        vocab("unbelegt", "unevidenced"),
        vocab("die Gegendarstellung", "the counterstatement"),
        vocab("gegenchecken", "to double-check"),
        vocab("die Sperrfrist", "the embargo"),
        vocab("off the record", "off the record"),
        vocab("die Quelle", "the source"),
        vocab("anonym", "anonymous"),
        vocab("die Einordnung", "the contextualisation"),
        vocab("zuspitzen", "to sharpen"),
        vocab("glätten", "to smooth"),
        vocab("die Schlagzeile", "the headline"),
        vocab("clickbait", "clickbait"),
        vocab("sachlich", "sober"),
        vocab("reißerisch", "sensational"),
        vocab("die Distanz", "distance"),
        vocab("nähe", "closeness (to sources)"),
        vocab("die Korrektur", "the correction"),
        vocab("sichtbar korrigieren", "to correct visibly"),
        vocab("die Verantwortung", "responsibility"),
        vocab("das Publikum", "the audience"),
        vocab("die Öffentlichkeit", "the public"),
        vocab("rhetorisch", "rhetorical"),
      ],
      phrases: [
        phrase("Lead ohne Adjektivtheater: Am Donnerstag entfiel die Linie 8 nach 21 Uhr dreimal.", "Lead without adjective theatre: On Thursday line 8 after 9 p.m. was cancelled three times."),
        phrase("Die Schätzung der Auslastung stammt vom Amt, nicht von uns; das gehört in den Satz.", "The occupancy estimate comes from the office, not from us; that belongs in the sentence."),
        phrase("Anonyme Quelle nur, wenn das öffentliche Interesse das Risiko überwiegt — und erklärt.", "Anonymous source only if public interest outweighs the risk — and is explained."),
        phrase("Einordnung ist keine Meinung: Schichtanteil 12 Prozent, Quelle Industrieverband 2024.", "Contextualisation is not opinion: shift share 12 percent, source industry association 2024."),
        phrase("Schlagzeile reißerisch, Text glatt — das ist ein Vertragsbruch mit Leserinnen.", "Sensational headline, smooth text — that is a breach of contract with readers."),
        phrase("Sichtbar korrigieren schützt Glaubwürdigkeit mehr als Schweigen.", "Correcting visibly protects credibility more than silence."),
        phrase("Off the record ist kein Freibrief für Ungeprüftes im Lead.", "Off the record is no licence for unchecked claims in the lead."),
        phrase("Die Dreierfigur „leer, teuer, überflüssig“ ist Rhetorik, keine Beweiskette.", "The triad “empty, expensive, superfluous” is rhetoric, not a chain of proof."),
        phrase("Scheinfragen ersetzen keine Interviews.", "Rhetorical questions do not replace interviews."),
        phrase("Nähe zur Quelle verpflichtet zum Gegencheck, nicht zur Treue.", "Closeness to the source obliges double-checking, not loyalty."),
        phrase("Kommentar kenntlich, Analyse kenntlich, Meldung kenntlich.", "Mark comment, mark analysis, mark news."),
        phrase("Das Publikum verdient Einheiten, nicht Stimmung.", "The audience deserves units, not mood."),
      ],
      sentences: [
        sentence("Warum kommt nach dem Was, sonst wird aus Nachricht ein Krimiaufbau.", "Why comes after what, otherwise news becomes crime-plot structure."),
        sentence("Zuspitzen darf der Kommentar; die Meldung nicht.", "The comment may sharpen; the news item may not."),
        sentence("Glätten im Amtstext ist Politik; Glätten in der Meldung ist Fehler.", "Smoothing in official text is politics; smoothing in the news item is error."),
        sentence("Clickbait stiehlt Zeit und gibt selten die Einheit zurück.", "Clickbait steals time and rarely returns the unit."),
        sentence("Eine Gegendarstellung gehört nicht in den siebten Absatz als Fußnote des Stolzes.", "A counterstatement does not belong in paragraph seven as a footnote of pride."),
        sentence("Sperrfrist brechen zerstört den nächsten Zugang.", "Breaking an embargo destroys the next access."),
        sentence("Rhetorik in der Analyse muss als Rhetorik lesbar bleiben.", "Rhetoric in analysis must remain readable as rhetoric."),
        sentence("Verantwortung heißt, die schwächste Leserin nicht mit Jargon abspeisen und die stärkste nicht mit Kinderton.", "Responsibility means not fobbing off the weakest reader with jargon nor the strongest with a childish tone."),
        sentence("Öffentlichkeit ist kein Chat; Sätze müssen allein stehen können.", "The public is not a chat; sentences must be able to stand alone."),
        sentence("Distanz ist Methode, nicht Kälte zum Leid.", "Distance is method, not coldness toward suffering."),
        sentence("Unbelegte Zahlen in der Schlagzeile sind keine Eile, sondern Entscheidung.", "Unevidenced figures in the headline are not haste but a decision."),
        sentence("Der Rahmen „Chaos“ macht aus drei Ausfällen eine Epoche.", "The frame “chaos” turns three cancellations into an epoch."),
        sentence("Korrekturen oben, nicht im Keller des CMS.", "Corrections at the top, not in the CMS basement."),
        sentence("Wer Quelle und Interesse in einem Satz nennt, nimmt dem Spin die Luft.", "Anyone who names source and interest in one sentence takes the air out of spin."),
        sentence("Analyse erklärt Mechanismen; Kommentar fordert; Meldung zählt.", "Analysis explains mechanisms; comment demands; news counts."),
        sentence("C1-Journalismus: langsam die ersten 40 Wörter, schnell der Gegencheck.", "C1 journalism: slow the first 40 words, fast the double-check."),
        sentence("Pointe am Ende der Analyse, nicht als Ersatz für das Wann.", "A kicker at the end of analysis, not as a substitute for when."),
        sentence("Sachlich schreiben ist eine ethische, nicht nur eine stilistische Wahl.", "Writing soberly is an ethical choice, not only a stylistic one."),
      ],
      readings: [
        reading(
          "Three labels",
          "Drei Kennzeichnungen",
          "Meldung: Linie 8 entfiel am Donnerstag nach 21 Uhr dreimal. Analyse: Die Kennzahl Auslastung 22 Uhr erfasst Schichtwechsel um 21:30 nicht. Kommentar: Der Rat sollte die Messlatte wechseln. Drei Textsorten, eine Redaktion, drei Pflichten. Wer sie mischt, ohne zu markieren, macht Rhetorik aus Zählen.",
          "News: line 8 was cancelled three times after 9 p.m. on Thursday. Analysis: the 10 p.m. occupancy metric does not capture the 9:30 p.m. shift change. Comment: the council should change the yardstick. Three genres, one newsroom, three duties. Anyone who mixes them unmarked turns counting into rhetoric.",
          [
            q("How many cancellations in the news sentence?", "Three", ["Epochal chaos", "Three", "None", "12 percent"]),
            q("What does mixing genres unmarked do?", "Turn counting into rhetoric", ["Improve SEO only", "Turn counting into rhetoric", "Satisfy the embargo", "Fix the bus"]),
            q("What should the council do, in the comment?", "Change the yardstick", ["Fire drivers", "Change the yardstick", "Ban shifts", "Print clickbait"]),
          ],
        ),
        reading(
          "Headline vs lead",
          "Schlagzeile vs Lead",
          "Schlagzeile: „Chaos auf Linie 8.“ Lead: drei Ausfälle, ein Donnerstag, nach 21 Uhr. Der Rahmen Chaos ist ungedeckt. C1-Korrektur: „Linie 8: drei Abendausfälle am Donnerstag.“ Weniger Klicks, mehr Vertrag. Rhetorik darf in den Kommentar, nicht in die Zahl.",
          "Headline: “Chaos on line 8.” Lead: three cancellations, one Thursday, after 9 p.m. The chaos frame is unevidenced. C1 correction: “Line 8: three evening cancellations on Thursday.” Fewer clicks, more contract. Rhetoric may go in the comment, not in the figure.",
          [
            q("Is the chaos frame evidenced by the lead?", "No", ["Yes, fully", "No", "Only legally", "The office confirmed chaos"]),
            q("What does the C1 headline keep?", "Three evening cancellations on Thursday", ["Chaos", "Three evening cancellations on Thursday", "A triad of insults", "No facts"]),
            q("Where may rhetoric go?", "In the comment", ["In the figure", "In the comment", "In the embargo", "Nowhere in German"]),
          ],
        ),
        reading(
          "Anonymous source",
          "Anonyme Quelle",
          "„Aus Verwaltungskreisen heißt es, die Linie sei politisch.“ Ohne Erklärung, warum Anonymität nötig ist, und ohne Gegencheck beim Amt, ist das Stimmung. Entweder zwei unabhängige Quellen oder runter von der ersten Seite. Nähe zu Kreisen verpflichtet nicht zur Treue gegenüber dem Spin.",
          "“Administrative circles say the line is political.” Without explaining why anonymity is needed, and without checking with the office, that is mood. Either two independent sources or off the front page. Closeness to circles does not oblige loyalty to the spin.",
          [
            q("What is missing?", "Why anonymity and a check with the office", ["A headline", "Why anonymity and a check with the office", "A triad", "A kicker"]),
            q("What is the alternative to two sources?", "Off the front page", ["Print anyway", "Off the front page", "More adjectives", "A rhetorical question"]),
            q("Does closeness oblige loyalty to spin?", "No", ["Yes", "No", "Only off the record", "Always in analysis"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 4-sentence lead, a 6-sentence analysis, and a 4-sentence comment — labelled.",
          "Schreib Meldung, Analyse, Kommentar.",
          "Nicht mischen. Eine Zahl mit Quelle in der Analyse. Forderung nur im Kommentar.",
          ["No chaos without evidence"],
        ),
        writing(
          "Rewrite a clickbait headline into a contract-keeping one.",
          "Schreib eine vertragstreue Überschrift.",
          "Einheit, Zeit, Ort. Kein unbelegtes Substantiv wie Chaos.",
          ["Countable claim"],
        ),
      ],
    },
  ),
  chapter(
    "literary-analysis",
    "Literary Analysis at C1",
    "Literaturanalyse auf C1",
    "Close-read a passage: form, figure, ideology — then write without plot summary padding.",
    "reading",
    [
      "Close reading: Tempus, Pronomen, Wiederholung, Lücke.",
      "Figurenrede vs Erzählerkommentar. Unzuverlässigkeit belegen.",
      "Ideologiekritik: welches Wissen gilt als selbstverständlich?",
    ],
    {
      vocab: [
        vocab("die Analyse", "analysis"),
        vocab("die Figurenrede", "character speech"),
        vocab("der Erzählerkommentar", "narrator commentary"),
        vocab("das Tempus", "tense"),
        vocab("das Pronomen", "pronoun"),
        vocab("die Lücke", "the gap"),
        vocab("die Wiederholung", "repetition"),
        vocab("unzuverlässig", "unreliable"),
        vocab("fokalisiert", "focalised"),
        vocab("auktorial", "authorial (narration)"),
        vocab("personal", "figural (narration)"),
        vocab("das Motiv", "motif"),
        vocab("das Thema", "theme"),
        vocab("die Ideologie", "ideology"),
        vocab("selbstverständlich", "taken for granted"),
        vocab("naturalisieren", "to naturalise (ideology)"),
        vocab("denaturalisieren", "to denaturalise"),
        vocab("das Subtext", "subtext"),
        vocab("implizit", "implicit"),
        vocab("die Ambiguität", "ambiguity"),
        vocab("reduzieren", "to reduce (a reading)"),
        vocab("überlesen", "to skim past"),
        vocab("wörtlich", "literal"),
        vocab("figürlich", "figurative"),
        vocab("die Prosodie", "prosody"),
        vocab("der Absatz", "the paragraph"),
        vocab("die Zäsur", "the caesura"),
        vocab("belegen", "to evidence"),
        vocab("überinterpretieren", "to over-read"),
        vocab("unterinterpretieren", "to under-read"),
        vocab("die Lektüre", "the reading"),
        vocab("gegen den Strich", "against the grain"),
      ],
      phrases: [
        phrase("Nicht die Handlung nacherzählen: den Tempuswechsel in Zeile vier.", "Do not retell the plot: the tense shift in line four."),
        phrase("Wir ist ein Pronomen der Macht, wenn niemand ins Wir darf.", "We is a pronoun of power when nobody is allowed into the we."),
        phrase("Die Lücke nach dem Gedankenstrich ist ein Ereignis.", "The gap after the dash is an event."),
        phrase("Unzuverlässigkeit zeigt sich im Widerspruch von Ruhm und Detail.", "Unreliability shows in the contradiction of boast and detail."),
        phrase("Fokalisiert auf die Hände, nicht auf das Gewissen — das ist Politik der Sicht.", "Focalised on the hands, not the conscience — that is politics of seeing."),
        phrase("Was als selbstverständlich gilt (der letzte Bus sei Luxus), naturalisiert eine Verteilung.", "What is taken for granted (the last bus as luxury) naturalises a distribution."),
        phrase("Gegen den Strich lesen heißt, die Selbstverständlichkeit stören.", "Reading against the grain means disturbing what is taken for granted."),
        phrase("Ambiguität aushalten ist nicht Unentschiedenheit der Analytikerin.", "Tolerating ambiguity is not indecision on the analyst’s part."),
        phrase("Überinterpretieren beginnt, wo kein sprachlicher Halt mehr ist.", "Over-reading begins where there is no linguistic hold left."),
        phrase("Unterinterpretieren ist oft Höflichkeit gegenüber dem Kanon.", "Under-reading is often politeness toward the canon."),
        phrase("Subtext ist nicht Geheimnis, sondern Gebrauch unterhalb der These.", "Subtext is not a secret but use beneath the thesis."),
        phrase("Wörtlich und figürlich gleichzeitig: die Tür ist zu, und der Zugang auch.", "Literal and figurative at once: the door is shut, and access too."),
      ],
      sentences: [
        sentence("Auktoriale Übersicht erklärt; personale Enge zwingt uns in ein Wissen.", "Authorial overview explains; figural tightness forces us into a knowledge."),
        sentence("Figurenrede im Dialekt kann Nähe oder Karikatur sein — der Rest des Registers entscheidet.", "Character speech in dialect can be closeness or caricature — the rest of the register decides."),
        sentence("Erzählerkommentar, der wertet, ist ein Angebot, kein Gesetz.", "Narrator commentary that judges is an offer, not a law."),
        sentence("Wiederholung von noch macht Zeit zu Gewicht.", "Repetition of noch makes time into weight."),
        sentence("Prosodie in Prosa: kurze Sätze nach einer Periode sind Zäsuren.", "Prosody in prose: short sentences after a period are caesuras."),
        sentence("Motivreime (Tür, Tisch, Stuhl) binden, was die Handlung trennt.", "Motif rhymes (door, table, chair) bind what the plot separates."),
        sentence("Thema ist Einsamkeit; Motiv ist der fehlende Stuhl — nicht verwechseln.", "Theme is loneliness; motif is the missing chair — do not confuse them."),
        sentence("Ideologie sitzt in den Selbstverständlichkeiten des Wir.", "Ideology sits in the taken-for-granteds of we."),
        sentence("Denaturalisieren: Luxus umdrehen, bis Infrastruktur sichtbar wird.", "Denaturalise: invert luxury until infrastructure becomes visible."),
        sentence("Eine Lektüre, die alles erklärt, hat den Text unterworfen.", "A reading that explains everything has subjected the text."),
        sentence("Überlesen wird oft das Kleine: ein Artikel, ein Tempus, ein nicht.", "What is often skimmed is the small: an article, a tense, a nicht."),
        sentence("Belege drei Wörter; dann darfst du groß deuten.", "Evidence three words; then you may interpret large."),
        sentence("Implizite Leserlenkung merkt man, wenn man das Gegenteil einsetzt.", "Implicit reader guidance shows when you insert the opposite."),
        sentence("Gegen den Strich: wessen Feierabend wird als Restzeit gedacht?", "Against the grain: whose evening off is thought as leftover time?"),
        sentence("C1-Analyse ist langsam am Satz, mutig an der These, ehrlich an der Lücke.", "C1 analysis is slow at the sentence, bold at the thesis, honest at the gap."),
        sentence("Reduzieren auf Biografie ist eine Flucht vor der Form.", "Reducing to biography is a flight from form."),
        sentence("Figürlich lesen ohne wörtlich zu können ist Ornament.", "Reading figuratively without being able to read literally is ornament."),
        sentence("Der Absatz bricht, wo das Wissen der Figur endet — das ist Fokalisierung.", "The paragraph breaks where the character’s knowledge ends — that is focalisation."),
      ],
      readings: [
        reading(
          "Passage",
          "Passage",
          "Wir sagten, der letzte Wagen sei überflüssig. Wir, die wir um acht zu Hause sind. Sie zählte bis zwölf und öffnete nicht. Draußen lachte jemand, als gäbe es kein Zimmer. Noch war Zeit. Noch.",
          "We said the last carriage was superfluous. We who are home by eight. She counted to twelve and did not open. Outside someone laughed as if there were no room. There was still time. Still.",
          [
            q("Whose we is marked as home by eight?", "Those already home", ["Night-shift workers", "Those already home", "Children only", "The laughing person"]),
            q("What word is repeated as weight?", "Noch", ["Wir", "Noch", "Wagen", "Zwölf"]),
            q("Does she open the door?", "No", ["Yes", "No", "The text is unclear", "In the next chapter only"]),
          ],
        ),
        reading(
          "Student close reading",
          "Close Reading",
          "Das Wir naturalisiert einen Feierabend um acht als Norm. Die Figur im Zimmer fällt aus dem Wir. Unzuverlässig ist nicht sie, sondern das Wir, das Überfluss behauptet, ohne den Raum zu kennen. Die Wiederholung von noch hält auf, was das Wir schon entschieden hat. Gegen den Strich: überflüssig für wen?",
          "The we naturalises being home by eight as a norm. The figure in the room falls out of the we. Unreliable is not she but the we that asserts surplus without knowing the room. The repetition of noch holds up what the we has already decided. Against the grain: superfluous for whom?",
          [
            q("Who is called unreliable?", "The we", ["She", "The we", "The laugh", "The chair"]),
            q("What does noch do?", "Hold up a decision already made", ["Open the door", "Hold up a decision already made", "Join the we", "End the story"]),
            q("Against-the-grain question?", "Superfluous for whom?", ["How many pages?", "Superfluous for whom?", "Who laughs louder?", "What is the genre?"]),
          ],
        ),
        reading(
          "Over-reading warning",
          "Warnung vor Überinterpretation",
          "„Zwölf“ als Apostelallegorie ohne weiteren Halt im Text ist Überinterpretation. Halt wäre: zählen als Kindheitsritual (wie früher). Das reicht für Angst und Aufschub. Nicht jede Zahl ist Symbol. C1 weiß, wann zu stoppen ist.",
          "“Twelve” as an allegory of the apostles without further hold in the text is over-reading. Hold would be: counting as a childhood ritual (as she used to). That is enough for fear and postponement. Not every number is a symbol. C1 knows when to stop.",
          [
            q("What would count as linguistic hold for twelve?", "Childhood counting ritual", ["Apostles only", "Childhood counting ritual", "Bus line 12", "A rhyme scheme"]),
            q("Is every number a symbol?", "No", ["Yes", "No", "Only even ones", "In C2 yes"]),
            q("What does C1 know?", "When to stop", ["Only biography", "When to stop", "Never to interpret", "Always apostles"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Close-read the passage in 12 sentences: pronouns, tense, gap, ideology — with quotations.",
          "Close Reading der Passage.",
          "Keine Handlungspolster. Drei Zitate. Eine gegen-den-Strich-Frage.",
          ["Mark the we", "Do not over-read twelve"],
        ),
        writing(
          "Write a thesis of one sentence and three linguistic evidences.",
          "These plus drei Belege.",
          "These: Das Wir naturalisiert … Beleg 1–3 aus dem Wortlaut.",
          ["No plot summary"],
        ),
      ],
    },
  ),
  chapter(
    "academic-writing",
    "Academic Writing: From Outline to Submission",
    "Wissenschaftliches Schreiben: von der Gliederung zur Abgabe",
    "Build a paper that a supervisor can mark: question, structure, citation, limit.",
    "writing",
    [
      "IMRaD is not mandatory in the humanities; a recognizable arc is.",
      "Zitation: indirekt vor häufigem Zitatblock. Page numbers for close claims.",
      "Schluss: Beitrag + Grenze + Anschluss, keine Moralpredigt.",
    ],
    {
      vocab: [
        vocab("die Gliederung", "the outline"),
        vocab("die Abgabe", "the submission"),
        vocab("die Betreuung", "supervision"),
        vocab("das Exposé", "the proposal"),
        vocab("die Fragestellung", "the question"),
        vocab("der Beitrag", "the contribution"),
        vocab("die Zitation", "citation"),
        vocab("indirekt", "indirect (speech/citation)"),
        vocab("der Beleg", "the reference"),
        vocab("die Seitenzahl", "the page number"),
        vocab("plagiieren", "to plagiarise"),
        vocab("paraphrasieren", "to paraphrase"),
        vocab("übernehmen", "to take over (text)"),
        vocab("kennzeichnen", "to mark"),
        vocab("der Fußnotenapparat", "the footnote apparatus"),
        vocab("der Anhang", "the appendix"),
        vocab("die Redundanz", "redundancy"),
        vocab("streichen", "to cut"),
        vocab("die Kohärenz", "coherence"),
        vocab("der Rotstift", "the red pen"),
        vocab("überarbeiten", "to revise"),
        vocab("die Fassung", "the version", undefined, "Fassungen"),
        vocab("einreichen", "to submit"),
        vocab("die Bewertung", "the assessment"),
        vocab("formale Mängel", "formal shortcomings"),
        vocab("inhaltliche Mängel", "content shortcomings"),
        vocab("die Originalität", "originality"),
        vocab("anschlussfähig", "connectable"),
        vocab("die Grenze", "the limitation"),
        vocab("das Fazit", "the conclusion"),
        vocab("unbelegt", "unevidenced"),
        vocab("tragfähig", "viable / robust"),
      ],
      phrases: [
        phrase("Das Exposé nennt Frage, Stand, Methode, Zeitplan — nicht das fertige Fazit.", "The proposal names question, state of research, method, timetable — not the finished conclusion."),
        phrase("Paraphrasieren ohne Kennzeichnung ist Plagiat in Zeitlupe.", "Paraphrasing without marking is plagiarism in slow motion."),
        phrase("Indirekte Rede spart Zitatblöcke und zeigt, dass Sie verdaut haben.", "Indirect speech saves block quotes and shows you have digested."),
        phrase("Seitenzahlen bei engen Claims; sonst wird aus Nähe zur Quelle Theater.", "Page numbers for close claims; otherwise closeness to the source becomes theatre."),
        phrase("Formale Mängel sind keine Pedanterie der Betreuung, sondern Lesbarkeit.", "Formal shortcomings are not the supervisor’s pedantry but readability."),
        phrase("Streichen ist Denken.", "Cutting is thinking."),
        phrase("Die dritte Fassung ist oft die erste ehrliche.", "The third version is often the first honest one."),
        phrase("Originalität auf C1: eine kleine, belegte Verschiebung, kein Weltentwurf.", "Originality at C1: a small, evidenced shift, not a world-system."),
        phrase("Das Fazit weitet nicht in Moral, sondern in eine prüfbare nächste Frage.", "The conclusion does not widen into morals but into a testable next question."),
        phrase("Unbelegte Sätze gehören in den Papierkorb oder ins Interview — nicht ins Kapitel.", "Unevidenced sentences belong in the bin or in an interview — not in the chapter."),
        phrase("Tragfähig ist eine These, die ihre stärkste Gegnerin selbst formuliert.", "A thesis is robust if it formulates its strongest opponent itself."),
        phrase("Einreichen ohne Checkliste ist Mut, der teuer wird.", "Submitting without a checklist is courage that gets expensive."),
      ],
      sentences: [
        sentence("Die Gliederung ist ein Vertrag mit der künftigen Leserin.", "The outline is a contract with the future reader."),
        sentence("Betreuung braucht rechtzeitig Text, nicht Stimmung am Ende.", "Supervision needs text in time, not mood at the end."),
        sentence("Der Beitrag muss in einem Satz sagbar sein, bevor er 20 Seiten wird.", "The contribution must be sayable in one sentence before it becomes 20 pages."),
        sentence("Zitation ist Ethik der Herkunft.", "Citation is the ethics of provenance."),
        sentence("Übernehmen Sie Strukturideen kenntlich, nicht nur Wörter.", "Mark borrowed structural ideas, not only words."),
        sentence("Der Fußnotenapparat ist kein Friedhof für Zweifel; Zweifel gehören in den Haupttext, wenn sie die These treffen.", "The footnote apparatus is not a cemetery for doubts; doubts belong in the main text if they hit the thesis."),
        sentence("Anhänge für Tabellen, nicht für Argumente, die man scheut.", "Appendices for tables, not for arguments you shy away from."),
        sentence("Redundanz zwischen Einleitung und Schluss ist die häufigste C1-Krankheit.", "Redundancy between introduction and conclusion is the most common C1 illness."),
        sentence("Kohärenz prüft man, indem man Themawörter der Absätze hintereinander liest.", "You check coherence by reading the paragraphs’ topic sentences in a row."),
        sentence("Rotstift zuerst an Verben, dann an Adjektiven.", "Red pen first on verbs, then on adjectives."),
        sentence("Überarbeiten heißt die Fragestellung erneut gegen den Text halten.", "To revise is to hold the question against the text again."),
        sentence("Bewertung trennt oft Form und Inhalt — Sie müssen beides liefern.", "Assessment often separates form and content — you must deliver both."),
        sentence("Anschlussfähig schreiben heißt, Operationalisierungen zu zeigen, nicht nur Ergebnisse.", "Writing in a connectable way means showing operationalisations, not only results."),
        sentence("Grenzen im Fazit sind Stärke, wenn sie spezifisch sind.", "Limitations in the conclusion are a strength when they are specific."),
        sentence("Einreichen Sie PDF und das, was die Ordnung verlangt, nicht Ihre Lieblingsdatei.", "Submit the PDF and what the rules require, not your favourite file."),
        sentence("C1-Abgabe: langsam die Frage, schnell die Checkliste, ehrlich die Grenze.", "C1 submission: slow the question, fast the checklist, honest the limit."),
        sentence("Plagiieren zerstört das Vertrauensverhältnis dauerhafter als eine schwache Note.", "Plagiarism destroys the trust relationship more lastingly than a weak grade."),
        sentence("Die Betreuung ist kein Co-Autorat; offene Fragen gehören in Mails mit Seitenangabe.", "Supervision is not co-authorship; open questions belong in emails with page numbers."),
      ],
      readings: [
        reading(
          "Supervisor comment",
          "Betreuungskommentar",
          "Die Fragestellung ist tragfähig, das Kapitel 2 referiert zu lang. Bitte indirekt zitieren und den Beitrag schon in 2.3 sichtbar machen. Unbelegt bleibt der Satz zur „Neutralität“ der Auslastung. Grenze im Fazit ist zu allgemein („mehr Forschung“). Nennen Sie: ländliches Sample, Längsschnitt. Form: einheitliche Zitation, Seitenzahlen bei engen Claims. Dritte Fassung bis 3.5.",
          "The question is viable; chapter 2 recounts for too long. Please cite indirectly and make the contribution visible already in 2.3. The sentence on occupancy’s “neutrality” remains unevidenced. The limitation in the conclusion is too general (“more research”). Name: rural sample, longitudinal. Form: consistent citation, page numbers for close claims. Third version by 3 May.",
          [
            q("What is too long?", "Chapter 2’s recounting", ["The question", "Chapter 2’s recounting", "The deadline", "The PDF"]),
            q("What limitation should be named?", "Rural sample and longitudinal", ["More research only", "Rural sample and longitudinal", "A new title", "No buses"]),
            q("When is the third version due?", "3 May", ["Tomorrow", "3 May", "Never", "After graduation"]),
          ],
        ),
        reading(
          "Bad vs better ending",
          "Fazit schlecht/besser",
          "Schlecht: „Busse sind wichtig für die Gesellschaft.“ Besser: „Der Beitrag zeigt, dass Auslastung 22 Uhr Schicht unsichtbar macht. Grenze: zwei Großstädte. Anschluss: Operationalisierung über verpasste Schichten in einem Längsschnitt.“ Moral ist kein Fazit.",
          "Bad: “Buses are important for society.” Better: “The paper shows that 10 p.m. occupancy makes shifts invisible. Limit: two large cities. Next: operationalise via missed shifts in a longitudinal design.” Morals are not a conclusion.",
          [
            q("What is wrong with the bad ending?", "It is a moral, not a contribution", ["Too many numbers", "It is a moral, not a contribution", "Wrong language", "No verbs"]),
            q("What limit is named in the better ending?", "Two large cities", ["The world", "Two large cities", "No method", "A slogan"]),
            q("What is the connectable next step?", "Missed shifts in a longitudinal design", ["More morals", "Missed shifts in a longitudinal design", "Delete occupancy", "A novel"]),
          ],
        ),
        reading(
          "Citation ethics",
          "Zitationsethik",
          "Drei Sätze umgestellt, Quelle in der Bibliografie, nicht am Satz: das ist Plagiat. Paraphrase plus (Name Jahr: Seite) ist Arbeit. Zitatblock nur, wo der Wortlaut selbst Befund ist. Wer Herkunft kennzeichnet, darf radikal umbauen. Wer das nicht tut, baut auf Sand, der andere geschaufelt haben.",
          "Three sentences rearranged, source in the bibliography but not at the sentence: that is plagiarism. Paraphrase plus (Name Year: page) is work. Block quote only where the wording itself is the finding. Anyone who marks provenance may rebuild radically. Anyone who does not builds on sand others shovelled.",
          [
            q("Is rearranging three sentences without in-text source plagiarism?", "Yes", ["No, it's clever", "Yes", "Only in STEM", "Only if German"]),
            q("When is a block quote justified?", "When the wording itself is the finding", ["Always for prestige", "When the wording itself is the finding", "Never at C1", "To hide paraphrase"]),
            q("What may you do if you mark provenance?", "Rebuild radically", ["Nothing", "Rebuild radically", "Skip page numbers forever", "Invent quotes"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a one-page exposé: question, gap, method, timetable, one limitation.",
          "Schreib ein einseitiges Exposé.",
          "Kein fertiges Fazit. Eine sagbare Beitragsformel.",
          ["Dates in the timetable"],
        ),
        writing(
          "Rewrite a moralising conclusion into contribution / limit / next step.",
          "Schreib ein C1-Fazit.",
          "Drei Sätze. Keine Gesellschaftspredigt.",
          ["Specific limitation"],
        ),
      ],
    },
  ),
  chapter(
    "presentations",
    "Presenting, Q&A & Professional Performance",
    "Präsentieren, Rückfragen, professioneller Auftritt",
    "Talk so the slide is a map, not a script — then handle questions without collapsing.",
    "mixed",
    [
      "Eine Idee pro Folie. Vorlesen ist keine Präsentation.",
      "Signposting mündlich: erst, dann, die Grenze, die Bitte an Sie.",
      "Fragen: wiederholen, klären, begrenzen, ehrlich „weiß ich nicht“ plus Angebot.",
    ],
    {
      vocab: [
        vocab("die Präsentation", "the presentation"),
        vocab("die Folie", "the slide", undefined, "Folien"),
        vocab("das Handout", "the handout"),
        vocab("der Laserpointer", "the laser pointer"),
        vocab("der Blickkontakt", "eye contact"),
        vocab("das Tempo", "pace"),
        vocab("die Pause", "the pause"),
        vocab("das Signposting", "signposting"),
        vocab("die Kernbotschaft", "the take-home message"),
        vocab("überladen", "overloaded"),
        vocab("ablesen", "to read off"),
        vocab("frei sprechen", "to speak freely"),
        vocab("die Rückfrage", "the question from the audience"),
        vocab("nachhaken", "to follow up"),
        vocab("ausweichen", "to dodge"),
        vocab("eingestehen", "to admit"),
        vocab("die Zeitüberziehung", "overrunning"),
        vocab("moderieren", "to chair / moderate"),
        vocab("die Diskussion", "the discussion"),
        vocab("das Mikrofon", "the microphone"),
        vocab("die Hybridrunde", "the hybrid session"),
        vocab("verständlich", "comprehensible"),
        vocab("die Grafik", "the figure / chart"),
        vocab("die Achse", "the axis", undefined, "Achsen"),
        vocab("die Einheit", "the unit"),
        vocab("die Take-home-Folie", "the take-home slide"),
        vocab("lampenfieber", "stage fright"),
        vocab("die Haltung", "posture / stance"),
        vocab("die Stimme", "the voice"),
        vocab("betonen", "to stress"),
        vocab("zusammenfassen", "to summarise"),
        vocab("die Abschlussfolie", "the closing slide"),
      ],
      phrases: [
        phrase("In den nächsten zwölf Minuten: Messlatte, Befund, Grenze.", "In the next twelve minutes: yardstick, finding, limit."),
        phrase("Was Sie mitnehmen sollen: Auslastung 22 Uhr ist kein neutrales Maß.", "What you should take away: 10 p.m. occupancy is not a neutral measure."),
        phrase("Die Grafik: x Zeit, y Fahrten, Einheit Personen, Quelle Amt 2024.", "The chart: x time, y trips, unit persons, source office 2024."),
        phrase("Ich lese das nicht vor; die Folie ist die Karte.", "I am not reading this out; the slide is the map."),
        phrase("Ihre Frage zielt auf Kausalität; ich habe Korrelation. Das will ich trennen.", "Your question aims at causation; I have correlation. I want to separate those."),
        phrase("Das weiß ich nicht. Ich kann die Operationalisierung nachreichen.", "I don’t know. I can send the operationalisation afterwards."),
        phrase("Lassen Sie uns die Zeit halten; eine Frage noch, dann Schlussfolie.", "Let us keep to time; one more question, then the closing slide."),
        phrase("Hybrid: bitte ins Mikro, sonst verlieren wir den Stream.", "Hybrid: please use the mic, otherwise we lose the stream."),
        phrase("Ich fasse zusammen: drei Punkte, eine Grenze, ein Wunsch an Sie.", "I summarise: three points, one limit, one request of you."),
        phrase("Lampenfieber darf da sein; Tempo darf es nicht fressen.", "Stage fright may be there; it must not eat the pace."),
        phrase("Pause nach der Kernbotschaft — sonst überhört sie der Saal.", "Pause after the take-home — otherwise the room misses it."),
        phrase("Nachhaken Sie, wenn ich ausweiche — das hilft mir.", "Follow up if I dodge — that helps me."),
      ],
      sentences: [
        sentence("Überladene Folien sind ungelesene Papiere an der Wand.", "Overloaded slides are unread papers on the wall."),
        sentence("Frei sprechen heißt strukturiert sprechen, nicht assoziativ.", "Speaking freely means speaking in structure, not associatively."),
        sentence("Blickkontakt verteilt man, statt eine Person zu hypnotisieren.", "You distribute eye contact rather than hypnotising one person."),
        sentence("Die Stimme fällt am Satzende, wenn die These unsicher ist — das hört man.", "The voice drops at the end of the sentence when the thesis is unsure — you can hear it."),
        sentence("Haltung ist kein Theaterkurs; es ist Luft für die Stimme.", "Posture is not drama school; it is air for the voice."),
        sentence("Zeitüberziehung stiehlt der Diskussion das Beste.", "Overrunning steals the best from the discussion."),
        sentence("Moderieren heißt Fragen bündeln, nicht selber glänzen.", "Chairing means bundling questions, not shining oneself."),
        sentence("Achsen ohne Einheit sind Ornament.", "Axes without units are ornament."),
        sentence("Die Abschlussfolie wiederholt nicht die Agenda, sondern die Bitte.", "The closing slide does not repeat the agenda but the request."),
        sentence("Handouts nach der Rede, sonst liest niemand zu.", "Handouts after the talk, otherwise nobody listens."),
        sentence("Laserpointer zittern; ein Wort auf der Folie reicht oft.", "Laser pointers tremble; a word on the slide often suffices."),
        sentence("Eingestehen von Grenzen erhöht Glaubwürdigkeit mehr als drei Extra-Grafiken.", "Admitting limits raises credibility more than three extra charts."),
        sentence("Ausweichen erkennt das Publikum an neuen Folien statt Antworten.", "The audience spots dodging in new slides instead of answers."),
        sentence("Verständlich auf C1 heißt: Fachwort erklären, nicht streichen.", "Comprehensible at C1 means explaining the technical term, not deleting it."),
        sentence("Hybridrunden brauchen Wiederholung der Frage für den Stream.", "Hybrid sessions need the question repeated for the stream."),
        sentence("Betonen Sie Verben der These, nicht Schmuckadjektive.", "Stress the verbs of the thesis, not ornamental adjectives."),
        sentence("Zusammenfassen vor der Q&A rettet Unaufmerksame, ohne zu beleidigen.", "Summarising before Q&A saves the inattentive without insulting them."),
        sentence("C1-Auftritt: Karte zeigen, Grenze nennen, Frage aushalten.", "C1 performance: show the map, name the limit, endure the question."),
      ],
      readings: [
        reading(
          "A good opening",
          "Ein guter Einstieg",
          "„Zwölf Minuten. Erst die Messlatte, dann der Befund aus zwei Städten, dann die Grenze ländlich. Take-home: leer um 22 Uhr heißt nicht unnötig. Fragen bitte nach der Grenze, nicht mittendrin — außer ich werde unklar.“ Der Saal weiß, woran er ist. Kein Witz über das Wetter.",
          "“Twelve minutes. First the yardstick, then the finding from two cities, then the rural limit. Take-home: empty at 10 p.m. does not mean unnecessary. Please questions after the limit, not in the middle — unless I become unclear.” The room knows where it stands. No joke about the weather.",
          [
            q("When should questions come?", "After the limit, unless unclear", ["Anytime over the talk", "After the limit, unless unclear", "Never", "Only as heckling"]),
            q("What is the take-home?", "Empty at 22:00 ≠ unnecessary", ["Weather", "Empty at 22:00 ≠ unnecessary", "Twelve jokes", "No rural limit"]),
            q("Is there a weather joke?", "No", ["Yes, required", "No", "Only hybrid", "On the handout"]),
          ],
        ),
        reading(
          "Q&A crash and recovery",
          "Q&A Absturz und Bergung",
          "Frage nach Kausalität. Antwort begann mit einer neuen Folie. Das Publikum hörte Ausweichen. Bergung: „Ihre Frage zielt auf Ursache. Ich habe Korrelation. Das trenne ich. Was ich nachreichen kann, ist die Operationalisierung.“ Ehrlichkeit plus Angebot schlägt Theater.",
          "Question about causation. The answer began with a new slide. The audience heard dodging. Recovery: “Your question aims at cause. I have correlation. I separate those. What I can send on is the operationalisation.” Honesty plus an offer beats theatre.",
          [
            q("What did the audience hear at first?", "Dodging", ["A perfect causal proof", "Dodging", "A weather joke", "Silence"]),
            q("What does the speaker actually have?", "Correlation", ["Causation", "Correlation", "No data", "Only jokes"]),
            q("What is offered afterwards?", "The operationalisation", ["A new city", "The operationalisation", "A longer talk", "Nothing"]),
          ],
        ),
        reading(
          "Slide ethics",
          "Folienethik",
          "Eine Grafik ohne Einheit und Quelle ist keine Visualisierung, sondern Stimmung. C1 löscht 40 Wörter von der Folie und sagt sie. Take-home-Folie am Ende, nicht Agenda-Wiederholung. Wer abliest, hat die Karte mit der Landschaft verwechselt.",
          "A chart without unit and source is not visualisation but mood. C1 deletes 40 words from the slide and says them. Take-home slide at the end, not agenda repeat. Anyone who reads off has confused the map with the landscape.",
          [
            q("What is a chart without unit and source?", "Mood, not visualisation", ["Better science", "Mood, not visualisation", "Required by hybrid", "A handout"]),
            q("What belongs at the end?", "Take-home, not agenda repeat", ["Forty more words", "Take-home, not agenda repeat", "A laser show", "The exposé"]),
            q("What has someone who reads off confused?", "Map and landscape", ["Mic and camera", "Map and landscape", "Q&A and lunch", "German and English"]),
          ],
        ),
      ],
      writings: [
        writing(
          "Write a 12-minute talk outline with timings and one take-home sentence.",
          "Schreib ein 12-Minuten-Gerüst.",
          "Einstieg 1 min, Messlatte 3, Befund 5, Grenze 2, Take-home + Überleitung Q&A 1.",
          ["No weather", "Named unit on the imagined chart"],
        ),
        writing(
          "Write three Q&A answers: one clarification, one limit (“I don’t know”), one boundary of the claim.",
          "Schreib drei Q&A-Antworten.",
          "Wiederholen der Frage. Keine neue Folie als Flucht. Ein Angebot zum Nachreichen.",
          ["Firm and honest"],
        ),
      ],
    },
  ),
];
