import type { GrammarConcept, LevelId } from "@/content/types";
import { A2_CONCEPTS, B1_CONCEPTS, B2_CONCEPTS, C1_CONCEPTS } from "@/content/concepts-plus";

const A1_CONCEPTS: GrammarConcept[] = [
  {
    id: "first-words",
    title: "First words and sounds",
    titleDe: "Erste Wörter",
    level: "a1",
    chapterSlug: "alphabet-sounds",
    summary: "Greet, say yes/no, and read a few classroom words before you write.",
    prerequisites: [],
    commonMistakes: [
      "Skipping umlauts: ä, ö, ü and ß are different sounds, not decoration.",
      "Forgetting that German nouns are always capitalised.",
    ],
    vocabDependencies: ["Hallo", "ja", "nein", "danke", "bitte", "ich", "du"],
    forms: [
      { de: "Hallo", en: "hello" },
      { de: "ja", en: "yes" },
      { de: "nein", en: "no" },
      { de: "danke", en: "thank you" },
      { de: "bitte", en: "please / you're welcome" },
    ],
    examples: [
      { de: "Hallo, ich heiße Ben.", en: "Hello, my name is Ben." },
      { de: "Danke, das ist gut.", en: "Thanks, that is good." },
      { de: "Bitte langsam.", en: "Please (speak) slowly." },
    ],
    applicationPrompt: "Greet someone and say your name in two short German sentences.",
    applicationPromptDe: "Begrüße jemand und sage deinen Namen.",
    applicationSample: "Hallo, ich heiße Luca. Danke!",
    applicationKeywords: ["Hallo", "ich", "heiße"],
  },
  {
    id: "sein-present",
    title: "sein (to be)",
    titleDe: "sein",
    level: "a1",
    chapterSlug: "pronouns-sein",
    summary: "Use ich bin, du bist, er/sie ist, wir sind, ihr seid and sie/Sie sind.",
    prerequisites: ["first-words"],
    commonMistakes: [
      "Mixing the forms: ich bin, never ich bist or ich ist.",
      "Using sein for a name when heißen is clearer: Ich heiße Luca.",
      "Forgetting that sie ist is she is, while sie sind is they are.",
    ],
    vocabDependencies: ["ich", "du", "er", "sie", "wir", "ihr", "Student", "Studentin"],
    forms: [
      { de: "ich bin", en: "I am" },
      { de: "du bist", en: "you are (informal)" },
      { de: "er/sie/es ist", en: "he/she/it is" },
      { de: "wir sind", en: "we are" },
      { de: "ihr seid", en: "you are (plural informal)" },
      { de: "sie/Sie sind", en: "they are / you are (formal)" },
    ],
    examples: [
      { de: "Ich bin Luca.", en: "I am Luca." },
      { de: "Du bist Student.", en: "You are a student." },
      { de: "Sie ist Lehrerin.", en: "She is a teacher." },
      { de: "Wir sind hier.", en: "We are here." },
    ],
    applicationPrompt: "Write four short German sentences with different forms of sein.",
    applicationPromptDe: "Schreib vier kurze Sätze mit sein.",
    applicationSample: "Ich bin Luca. Du bist hier. Sie ist Lehrerin. Wir sind neu.",
    applicationKeywords: ["bin", "bist", "ist", "sind"],
  },
  {
    id: "du-vs-sie",
    title: "du, ihr and Sie",
    titleDe: "du, ihr und Sie",
    level: "a1",
    chapterSlug: "pronouns-sein",
    summary: "Informal du/ihr vs formal Sie. The verb has to match: du bist, ihr seid, Sie sind.",
    prerequisites: ["first-words"],
    commonMistakes: [
      "Writing sie when you mean Sie — the capital letter is the formal you.",
      "Using du with a teacher or a stranger, or mixing the verbs: du bist, never du sind.",
    ],
    vocabDependencies: ["du", "ihr", "Sie"],
    forms: [
      { de: "du bist", en: "you are (informal singular)" },
      { de: "ihr seid", en: "you are (informal plural)" },
      { de: "Sie sind", en: "you are (formal)" },
    ],
    examples: [
      { de: "Bist du Lea?", en: "Are you Lea?" },
      { de: "Seid ihr neu?", en: "Are you (plural) new?" },
      { de: "Sind Sie Herr Braun?", en: "Are you Mr. Braun?" },
    ],
    applicationPrompt: "Write one informal sentence to a friend and one formal sentence to a teacher.",
    applicationPromptDe: "Schreib einen du-Satz und einen Sie-Satz.",
    applicationSample: "Du bist hier. Sie sind Frau Klein.",
    applicationKeywords: ["bist", "sind"],
  },
  {
    id: "numbers-time",
    title: "Numbers and clock time",
    titleDe: "Zahlen und Uhrzeit",
    level: "a1",
    chapterSlug: "numbers-time",
    summary: "Count past twenty with ones-before-tens, then say the time with Uhr.",
    prerequisites: ["first-words"],
    commonMistakes: [
      "Saying twenty-one as zwanzig-eins instead of einundzwanzig.",
      "Dropping Uhr: Es ist drei Uhr, not Es ist drei for clock time.",
    ],
    vocabDependencies: ["Uhr", "heute", "morgen"],
    examples: [
      { de: "Es ist drei Uhr.", en: "It is three o'clock." },
      { de: "Heute ist Montag.", en: "Today is Monday." },
      { de: "Ich komme um acht Uhr.", en: "I am coming at eight o'clock." },
    ],
    applicationPrompt: "Say what time it is and name today in two German sentences.",
    applicationPromptDe: "Sag die Uhrzeit und den Tag.",
    applicationSample: "Es ist acht Uhr. Heute ist Montag.",
    applicationKeywords: ["Uhr", "Heute"],
  },
  {
    id: "kommen-wohnen",
    title: "kommen aus and wohnen in",
    titleDe: "kommen und wohnen",
    level: "a1",
    chapterSlug: "personal-info",
    summary: "Say where you are from and where you live.",
    prerequisites: ["sein-present"],
    commonMistakes: [
      "Swapping the prepositions: kommen aus + country, wohnen in + city.",
      "Leaving out aus: Ich komme Italien is not German.",
    ],
    vocabDependencies: ["kommen", "aus", "wohnen", "in", "Deutschland"],
    forms: [
      { de: "ich komme aus", en: "I come from" },
      { de: "ich wohne in", en: "I live in" },
    ],
    examples: [
      { de: "Ich komme aus Italien.", en: "I come from Italy." },
      { de: "Ich wohne in München.", en: "I live in Munich." },
      { de: "Sie kommt aus Österreich.", en: "She comes from Austria." },
    ],
    applicationPrompt: "Say your name, where you are from, and where you live.",
    applicationPromptDe: "Name, Herkunft und Wohnort.",
    applicationSample: "Ich heiße Luca. Ich komme aus Italien. Ich wohne in Berlin.",
    applicationKeywords: ["komme", "wohne"],
  },
  {
    id: "possessives-family",
    title: "mein/meine and family",
    titleDe: "Familie und Possessivartikel",
    level: "a1",
    chapterSlug: "family",
    summary: "Name a few family members and match mein or meine to the noun.",
    prerequisites: ["sein-present"],
    commonMistakes: [
      "mein Vater but meine Mutter — the ending follows the noun’s gender.",
      "Learning ten family words in one sitting and keeping none of them.",
    ],
    vocabDependencies: ["der Vater", "die Mutter", "der Bruder", "die Schwester", "mein", "meine"],
    forms: [
      { de: "mein Vater", en: "my father" },
      { de: "meine Mutter", en: "my mother" },
      { de: "mein Bruder", en: "my brother" },
      { de: "meine Schwester", en: "my sister" },
    ],
    examples: [
      { de: "Das ist mein Vater.", en: "That is my father." },
      { de: "Meine Mutter heißt Anna.", en: "My mother is called Anna." },
      { de: "Ich habe eine Schwester.", en: "I have a sister." },
    ],
    applicationPrompt: "Name two people in your family in short German sentences.",
    applicationPromptDe: "Nenne zwei Personen in deiner Familie.",
    applicationSample: "Das ist mein Vater. Meine Schwester heißt Mia.",
    applicationKeywords: ["mein", "Vater"],
  },
  {
    id: "articles-gender",
    title: "der, die, das",
    titleDe: "Artikel und Genus",
    level: "a1",
    chapterSlug: "articles-nouns",
    summary: "Learn every noun with its article. Gender is part of the word.",
    prerequisites: ["first-words"],
    commonMistakes: [
      "Learning Tisch without der Tisch.",
      "Guessing gender from English: die Katze is feminine, not masculine.",
      "Using der for every noun because it feels like “the”.",
    ],
    vocabDependencies: ["der", "die", "das"],
    forms: [
      { de: "der", en: "the (masculine)" },
      { de: "die", en: "the (feminine / plural)" },
      { de: "das", en: "the (neuter)" },
    ],
    examples: [
      { de: "der Tisch", en: "the table" },
      { de: "die Lampe", en: "the lamp" },
      { de: "das Fenster", en: "the window" },
    ],
    applicationPrompt: "Write three nouns from this chapter, each with der, die or das.",
    applicationPromptDe: "Schreib drei Nomen mit Artikel.",
    applicationSample: "der Tisch, die Lampe, das Fenster",
    applicationKeywords: ["der", "die", "das"],
  },
  {
    id: "predicative-adjectives",
    title: "Simple adjectives",
    titleDe: "Einfache Adjektive",
    level: "a1",
    chapterSlug: "colors-adjectives",
    summary: "After sein, adjectives keep a bare form: Der Hund ist groß.",
    prerequisites: ["sein-present", "articles-gender"],
    commonMistakes: [
      "Adding an ending after sein: Der Hund ist groß, not großer.",
      "Putting nicht after the adjective: Das Auto ist nicht teuer.",
    ],
    vocabDependencies: ["groß", "klein", "rot", "gut"],
    examples: [
      { de: "Der Hund ist groß.", en: "The dog is big." },
      { de: "Das Auto ist nicht teuer.", en: "The car is not expensive." },
      { de: "Die Tasche ist rot.", en: "The bag is red." },
    ],
    applicationPrompt: "Describe two things with a colour or size.",
    applicationPromptDe: "Beschreibe zwei Dinge.",
    applicationSample: "Der Hund ist groß. Die Tasche ist rot.",
    applicationKeywords: ["ist"],
  },
  {
    id: "food-requests",
    title: "Food and simple requests",
    titleDe: "Essen und Bitten",
    level: "a1",
    chapterSlug: "food-drinks",
    summary: "Name a few drinks and meals, then ask for them politely.",
    prerequisites: ["articles-gender", "du-vs-sie"],
    commonMistakes: [
      "Cramming a whole menu into one lesson — keep a handful of words and reuse them.",
      "Forgetting bitte when you order.",
    ],
    vocabDependencies: ["das Wasser", "der Kaffee", "bitte", "danke"],
    examples: [
      { de: "Ich möchte einen Kaffee, bitte.", en: "I would like a coffee, please." },
      { de: "Das Wasser ist gut.", en: "The water is good." },
      { de: "Haben Sie Brot?", en: "Do you have bread?" },
    ],
    applicationPrompt: "Order a drink and say thank you in two sentences.",
    applicationPromptDe: "Bestelle ein Getränk.",
    applicationSample: "Ich möchte einen Kaffee, bitte. Danke!",
    applicationKeywords: ["bitte", "Kaffee"],
  },
  {
    id: "reading-signs",
    title: "Reading signs and short notes",
    titleDe: "Schilder lesen",
    level: "a1",
    chapterSlug: "first-reading",
    summary: "Understand a short sign or message before you try to write one.",
    prerequisites: ["first-words", "articles-gender"],
    commonMistakes: [
      "Translating every word instead of reading for the main idea.",
      "Skipping the listen-once step — seeing and hearing together helps A1 stick.",
    ],
    vocabDependencies: ["Eingang", "Ausgang", "geöffnet", "geschlossen"],
    examples: [
      { de: "Bitte warten.", en: "Please wait." },
      { de: "Heute geschlossen.", en: "Closed today." },
    ],
    applicationPrompt: "Write a two-line note like a café sign.",
    applicationPromptDe: "Schreib eine Mini-Notiz.",
    applicationSample: "Heute geöffnet. Bitte warten.",
    applicationKeywords: ["Bitte"],
  },
  {
    id: "mini-writing",
    title: "Mini sentences",
    titleDe: "Minisätze",
    level: "a1",
    chapterSlug: "first-writing",
    summary: "Write short, correct sentences from models you have already read.",
    prerequisites: ["sein-present", "kommen-wohnen"],
    commonMistakes: [
      "Writing long English-shaped sentences before the German word order is solid.",
      "Leaving nouns uncapitalised.",
    ],
    vocabDependencies: ["ich", "bin", "heiße"],
    examples: [
      { de: "Ich heiße Ben.", en: "My name is Ben." },
      { de: "Ich bin 22 Jahre alt.", en: "I am 22 years old." },
    ],
    applicationPrompt: "Fill a mini form about yourself in three German sentences.",
    applicationPromptDe: "Fülle ein Mini-Formular aus.",
    applicationSample: "Ich heiße Anna. Ich wohne in Berlin. Ich komme aus Schweden.",
    applicationKeywords: ["Ich", "heiße"],
  },
  {
    id: "home-nouns",
    title: "Rooms and objects at home",
    titleDe: "Zuhause",
    level: "a1",
    chapterSlug: "home",
    summary: "A small set of home nouns, each with its article, recycled across the chapter.",
    prerequisites: ["articles-gender"],
    commonMistakes: [
      "Memorising room, table, lamp, window, door all at once and mixing the articles.",
      "Forgetting das for many household objects: das Fenster, das Bett.",
    ],
    vocabDependencies: ["das Haus", "die Küche", "das Zimmer", "der Tisch"],
    examples: [
      { de: "Das Haus ist klein.", en: "The house is small." },
      { de: "Die Küche ist groß.", en: "The kitchen is big." },
      { de: "Der Tisch steht in der Küche.", en: "The table is in the kitchen." },
    ],
    applicationPrompt: "Name two rooms or objects at home, with articles.",
    applicationPromptDe: "Nenne zwei Dinge zu Hause.",
    applicationSample: "Die Küche ist groß. Das Bett ist im Zimmer.",
    applicationKeywords: ["Küche"],
  },
  {
    id: "verb-second",
    title: "Present tense and verb-second",
    titleDe: "Präsens und Verbzweit",
    level: "a1",
    chapterSlug: "daily-routine",
    summary: "In a main clause the conjugated verb stays in position two.",
    prerequisites: ["sein-present"],
    commonMistakes: [
      "Putting the verb at the end in a main clause: Ich frühstücke um acht, not Ich um acht frühstücke.",
      "Forgetting the -st ending: du gehst, du kommst.",
    ],
    vocabDependencies: ["ich", "du", "gehen", "kommen", "heute"],
    forms: [
      { de: "ich gehe", en: "I go" },
      { de: "du gehst", en: "you go" },
      { de: "er/sie geht", en: "he/she goes" },
    ],
    examples: [
      { de: "Ich gehe um acht Uhr.", en: "I go at eight o'clock." },
      { de: "Heute bleibe ich zu Hause.", en: "Today I stay at home." },
      { de: "Du kommst um neun Uhr.", en: "You come at nine o'clock." },
    ],
    applicationPrompt: "Write two sentences about your morning. Keep the verb in position two.",
    applicationPromptDe: "Schreib zwei Sätze über deinen Morgen.",
    applicationSample: "Ich stehe um sieben Uhr auf. Dann trinke ich Kaffee.",
    applicationKeywords: ["Ich", "Uhr"],
  },
];

const CONCEPTS: GrammarConcept[] = [
  ...A1_CONCEPTS,
  ...A2_CONCEPTS,
  ...B1_CONCEPTS,
  ...B2_CONCEPTS,
  ...C1_CONCEPTS,
];

export function getConcept(id: string): GrammarConcept | undefined {
  return CONCEPTS.find((item) => item.id === id);
}

export function conceptsForChapter(level: LevelId, slug: string): GrammarConcept[] {
  return CONCEPTS.filter((item) => item.level === level && item.chapterSlug === slug).map(
    (item) => ({ ...item }),
  );
}

export function allConcepts(): GrammarConcept[] {
  return CONCEPTS.map((item) => ({ ...item }));
}

export function fallbackConcept(
  level: LevelId,
  slug: string,
  title: string,
  grammar: string[],
): GrammarConcept {
  return {
    id: `${level}-${slug}`,
    title,
    titleDe: title,
    level,
    chapterSlug: slug,
    summary: grammar[0] ?? title,
    prerequisites: [],
    commonMistakes: grammar.slice(0, 3),
    vocabDependencies: [],
  };
}
