import type { GrammarConcept } from "@/content/types";

export const A2_CONCEPTS: GrammarConcept[] = [
  {
    id: "perfekt-haben-sein",
    title: "Perfekt with haben and sein",
    titleDe: "Perfekt mit haben und sein",
    level: "a2",
    chapterSlug: "perfect-tense",
    summary: "Spoken past: ich habe … gemacht, ich bin … gegangen. Movement and change often take sein.",
    prerequisites: ["verb-second"],
    commonMistakes: [
      "Ich bin Pizza gegessen — food takes haben.",
      "Participle at the end: Ich habe gestern gearbeitet, not Ich habe gearbeitet gestern as the only pattern drill — time can move, the participle stays last.",
    ],
    vocabDependencies: ["haben", "sein", "gemacht", "gegangen"],
    forms: [
      { de: "ich habe … gemacht", en: "I did / made (Perfekt)" },
      { de: "ich bin … gegangen", en: "I went (Perfekt)" },
      { de: "wir sind … gefahren", en: "we travelled / drove" },
    ],
    examples: [
      { de: "Gestern habe ich Pizza gegessen.", en: "Yesterday I ate pizza." },
      { de: "Wir sind um acht angekommen.", en: "We arrived at eight." },
    ],
    applicationPrompt: "Tell yesterday in four Perfekt sentences. Mix haben and sein.",
    applicationPromptDe: "Erzähl gestern in vier Sätzen im Perfekt.",
    applicationSample: "Ich bin früh aufgestanden. Dann habe ich Kaffee getrunken. Wir sind in die Stadt gefahren. Am Abend habe ich einen Film gesehen.",
    applicationKeywords: ["habe", "bin", "gestern"],
  },
  {
    id: "modal-verbs-a2",
    title: "Modal verbs: können, müssen, wollen, sollen, dürfen",
    titleDe: "Modalverben",
    level: "a2",
    chapterSlug: "modal-verbs",
    summary: "Modal in position two, infinitive at the end. möchten for polite wishes.",
    prerequisites: ["verb-second"],
    commonMistakes: [
      "Ich muss zu arbeiten — drop zu with modals: Ich muss arbeiten.",
      "dürfen is permission, not müssen.",
    ],
    vocabDependencies: ["können", "müssen", "wollen", "sollen", "dürfen", "möchten"],
    forms: [
      { de: "ich kann", en: "I can" },
      { de: "ich muss", en: "I must" },
      { de: "ich möchte", en: "I would like" },
    ],
    examples: [
      { de: "Ich muss morgen arbeiten.", en: "I have to work tomorrow." },
      { de: "Hier darf man nicht rauchen.", en: "You are not allowed to smoke here." },
    ],
    applicationPrompt: "Write three sentences: one müssen, one können, one möchten.",
    applicationPromptDe: "Schreib drei Sätze mit Modalverben.",
    applicationSample: "Ich muss um sieben aufstehen. Ich kann gut kochen. Ich möchte einen Termin.",
    applicationKeywords: ["muss", "kann", "möchte"],
  },
  {
    id: "accusative-a2",
    title: "Accusative after ich möchte / ich kaufe",
    titleDe: "Akkusativ",
    level: "a2",
    chapterSlug: "shopping",
    summary: "Direct objects take den/einen, die/eine, das/ein. Learn the article with the noun.",
    prerequisites: ["articles-gender"],
    commonMistakes: [
      "Ich kaufe der Pullover — after kaufen you need den Pullover.",
      "eine is feminine accusative as well as nominative — masculine is the one that changes: einen.",
    ],
    vocabDependencies: ["den", "einen", "kaufen", "möchten"],
    forms: [
      { de: "den / einen", en: "masculine accusative" },
      { de: "die / eine", en: "feminine accusative" },
      { de: "das / ein", en: "neuter accusative" },
    ],
    examples: [
      { de: "Ich möchte einen Kaffee.", en: "I would like a coffee." },
      { de: "Ich kaufe den Pullover.", en: "I am buying the jumper." },
    ],
    applicationPrompt: "Order two things with the right accusative article.",
    applicationPromptDe: "Bestelle zwei Dinge im Akkusativ.",
    applicationSample: "Ich möchte einen Kaffee und eine Tüte, bitte.",
    applicationKeywords: ["einen", "eine", "möchte"],
  },
  {
    id: "separable-verbs-a2",
    title: "Separable verbs",
    titleDe: "Trennbare Verben",
    level: "a2",
    chapterSlug: "travel",
    summary: "In a main clause the prefix goes to the end: Ich stehe um sieben auf.",
    prerequisites: ["verb-second"],
    commonMistakes: [
      "Ich aufstehe um sieben — the prefix splits in the present main clause.",
      "In Perfekt the ge- sits in the middle: aufgestanden.",
    ],
    vocabDependencies: ["aufstehen", "ankommen", "einkaufen"],
    examples: [
      { de: "Ich stehe um sieben auf.", en: "I get up at seven." },
      { de: "Der Zug kommt um zehn an.", en: "The train arrives at ten." },
    ],
    applicationPrompt: "Write two morning sentences with a separable verb.",
    applicationPromptDe: "Zwei Sätze mit trennbarem Verb.",
    applicationSample: "Ich stehe um sechs auf. Dann kaufe ich Brot ein.",
    applicationKeywords: ["auf", "ein"],
  },
  {
    id: "weil-a2",
    title: "weil sends the verb last",
    titleDe: "weil + Verb am Ende",
    level: "a2",
    chapterSlug: "emails-notes",
    summary: "Comma before weil. Conjugated verb at the end of the clause.",
    prerequisites: ["verb-second"],
    commonMistakes: [
      "Ich bleibe, weil ich bin krank — verb last: weil ich krank bin.",
      "deshalb starts a new main clause; weil does not.",
    ],
    vocabDependencies: ["weil", "deshalb"],
    examples: [
      { de: "Ich bleibe zu Hause, weil ich krank bin.", en: "I am staying home because I am ill." },
      { de: "Es regnet. Deshalb bleibe ich zu Hause.", en: "It is raining. That is why I am staying home." },
    ],
    applicationPrompt: "Write one weil sentence and one deshalb pair.",
    applicationPromptDe: "Ein weil-Satz und ein deshalb-Paar.",
    applicationSample: "Ich schreibe, weil der Kurs wichtig ist. Der Kurs ist wichtig. Deshalb schreibe ich.",
    applicationKeywords: ["weil", "deshalb"],
  },
];

export const B1_CONCEPTS: GrammarConcept[] = [
  {
    id: "subclauses-b1",
    title: "weil, dass, wenn, obwohl",
    titleDe: "Nebensätze",
    level: "b1",
    chapterSlug: "subordinate-clauses",
    summary: "Subordinate clauses park the conjugated verb at the end. Comma before the conjunction.",
    prerequisites: ["weil-a2"],
    commonMistakes: [
      "wenn vs als: als for a single past event, wenn for whenever / if.",
      "dass is not das. Ich hoffe, dass du kommst.",
    ],
    vocabDependencies: ["weil", "dass", "wenn", "obwohl"],
    forms: [
      { de: "…, weil … Verb.", en: "because + verb last" },
      { de: "…, dass … Verb.", en: "that + verb last" },
      { de: "Wenn … Verb, …", en: "if/when + verb last" },
    ],
    examples: [
      { de: "Ich lerne, weil ich in Deutschland arbeiten will.", en: "I am learning because I want to work in Germany." },
      { de: "Ich hoffe, dass der Termin klappt.", en: "I hope that the appointment works." },
    ],
    applicationPrompt: "Write five sentences, each with a different conjunction.",
    applicationPromptDe: "Fünf Sätze mit verschiedenen Konjunktionen.",
    applicationSample: "Ich bleibe, weil es regnet. Ich hoffe, dass du kommst. Wenn ich Zeit habe, lese ich. Obwohl ich müde bin, übe ich. Ich schreibe, damit du den Plan kennst.",
    applicationKeywords: ["weil", "dass", "wenn", "obwohl"],
  },
  {
    id: "two-way-prepositions-b1",
    title: "Two-way prepositions: an, auf, in, über…",
    titleDe: "Wechselpräpositionen",
    level: "b1",
    chapterSlug: "cases-review",
    summary: "Accusative for movement onto/into a place; dative for location.",
    prerequisites: ["accusative-a2"],
    commonMistakes: [
      "Ich stelle die Lampe auf dem Tisch — movement needs auf den Tisch.",
      "mit, nach, bei, von, zu are dative only — not two-way.",
    ],
    vocabDependencies: ["in", "an", "auf", "dem", "den"],
    examples: [
      { de: "Wir gehen in die Küche.", en: "We go into the kitchen." },
      { de: "Wir sitzen in der Küche.", en: "We are sitting in the kitchen." },
    ],
    applicationPrompt: "One movement sentence and one location sentence with in or auf.",
    applicationPromptDe: "Ein Satz Bewegung, ein Satz Ort.",
    applicationSample: "Ich hänge das Bild an die Wand. Das Bild hängt an der Wand.",
    applicationKeywords: ["in", "an", "auf"],
  },
  {
    id: "formal-letter-b1",
    title: "Formal email: Betreff, Anrede, Frist",
    titleDe: "Formelle Mail",
    level: "b1",
    chapterSlug: "formal-writing",
    summary: "Facts, demand, deadline. Konjunktiv II for politeness: Könnten Sie…",
    prerequisites: ["subclauses-b1"],
    commonMistakes: [
      "Hochachtungsvoll is often too stiff; Mit freundlichen Grüßen is the default.",
      "A feeling without a date or amount is not a complaint.",
    ],
    vocabDependencies: ["Betreff", "Sehr geehrte", "Mit freundlichen Grüßen", "Frist"],
    examples: [
      { de: "Könnten Sie den Fehler prüfen?", en: "Could you check the error?" },
      { de: "Bitte antworten Sie bis zum 20. März.", en: "Please reply by 20 March." },
    ],
    applicationPrompt: "Write a short complaint with subject, facts, demand, deadline.",
    applicationPromptDe: "Schreib eine kurze Reklamation.",
    applicationSample: "Betreff: Reklamation Bestellung 12. Sehr geehrte Damen und Herren, die Lampe ist beschädigt. Ich bitte um Ersatz bis zum 30. Mit freundlichen Grüßen.",
    applicationKeywords: ["Betreff", "bitte", "Grüßen"],
  },
];

export const B2_CONCEPTS: GrammarConcept[] = [
  {
    id: "passive-b2",
    title: "Vorgangspassiv with werden",
    titleDe: "Passiv",
    level: "b2",
    chapterSlug: "passive",
    summary: "werden + participle for a process. von + agent only when needed.",
    prerequisites: ["perfekt-haben-sein"],
    commonMistakes: [
      "Die Tür wird geschlossen vs Die Tür ist geschlossen — process vs resulting state.",
      "Do not name an agent if it is obvious or unknown.",
    ],
    vocabDependencies: ["werden", "worden"],
    forms: [
      { de: "wird + Partizip", en: "present passive" },
      { de: "wurde + Partizip", en: "past passive" },
      { de: "ist + Partizip worden", en: "Perfekt passive" },
    ],
    examples: [
      { de: "Hier wird gebaut.", en: "Construction is going on here." },
      { de: "Der Termin musste verschoben werden.", en: "The appointment had to be postponed." },
    ],
    applicationPrompt: "Rewrite two active sentences as passive. Drop the agent once.",
    applicationPromptDe: "Zwei Passivsätze.",
    applicationSample: "Die Brücke wird eröffnet. Die Einwände werden geprüft.",
    applicationKeywords: ["wird", "werden"],
  },
  {
    id: "konjunktiv-ii-b2",
    title: "Konjunktiv II: wäre, hätte, würde, könnte",
    titleDe: "Konjunktiv II",
    level: "b2",
    chapterSlug: "konjunktiv-ii",
    summary: "Wishes, hypotheticals, politeness. würde + infinitive for most verbs.",
    prerequisites: ["modal-verbs-a2"],
    commonMistakes: [
      "würde sein is clumsy — use wäre.",
      "Politeness: Könnten Sie… is softer than Können Sie…",
    ],
    vocabDependencies: ["wäre", "hätte", "würde", "könnte"],
    forms: [
      { de: "ich wäre", en: "I would be" },
      { de: "ich hätte", en: "I would have" },
      { de: "ich würde + Infinitiv", en: "I would + verb" },
    ],
    examples: [
      { de: "Wenn ich Zeit hätte, käme ich.", en: "If I had time, I would come." },
      { de: "Könnten Sie das Fenster schließen?", en: "Could you close the window?" },
    ],
    applicationPrompt: "One wish, one polite request, one unreal condition.",
    applicationPromptDe: "Wunsch, Bitte, irreale Bedingung.",
    applicationSample: "Ich hätte gern Tee. Könnten Sie warten? Wenn das Wetter besser wäre, würden wir wandern.",
    applicationKeywords: ["hätte", "Könnten", "wäre"],
  },
  {
    id: "relatives-b2",
    title: "Relative clauses: der, die, das, dessen, deren",
    titleDe: "Relativsätze",
    level: "b2",
    chapterSlug: "relative-clauses",
    summary: "The relative pronoun agrees with the noun; case follows the role inside the clause.",
    prerequisites: ["two-way-prepositions-b1"],
    commonMistakes: [
      "Das Büro, dass wir sitzen — use in dem for location.",
      "Do not stack three relatives; split the sentence.",
    ],
    vocabDependencies: ["der", "die", "das", "dessen", "deren"],
    examples: [
      { de: "Das ist die Kollegin, die den Kurs leitet.", en: "That is the colleague who runs the course." },
      { de: "Das Büro, in dem wir sitzen, ist hell.", en: "The office in which we sit is bright." },
    ],
    applicationPrompt: "Describe two people or places with a relative clause each.",
    applicationPromptDe: "Zwei Relativsätze.",
    applicationSample: "Das ist die Firma, deren Chef heute spricht. Das ist der Kurs, den ich brauche.",
    applicationKeywords: ["die", "den", "deren"],
  },
];

export const C1_CONCEPTS: GrammarConcept[] = [
  {
    id: "academic-hedge-c1",
    title: "Stance: legen nahe, not beweisen",
    titleDe: "Haltung und Absicherung",
    level: "c1",
    chapterSlug: "academic-language",
    summary: "Name scope and hedges. Causal verbs must be earned.",
    prerequisites: ["konjunktiv-ii-b2"],
    commonMistakes: [
      "Die Ergebnisse beweisen kausal — usually they do not.",
      "Hiding the limit in a footnote instead of the abstract.",
    ],
    vocabDependencies: ["nahelegen", "Reichweite", "Desiderat"],
    examples: [
      { de: "Die Ergebnisse legen nahe, dass die Quote sinkt.", en: "The results suggest that the rate is falling." },
      { de: "Gleichwohl ist die Reichweite urban begrenzt.", en: "Nevertheless the scope is urban-limited." },
    ],
    applicationPrompt: "Write a five-sentence abstract with one hedge and one limitation.",
    applicationPromptDe: "Ein Abstract mit Absicherung und Grenze.",
    applicationSample: "Der Beitrag untersucht Weiterbildung in drei Betrieben. Die Ergebnisse legen nahe, dass Teilnahme mit Hierarchie korreliert. Gleichwohl ist die Reichweite mittelständisch. Ein Desiderat bleibt der Vergleich mit Konzernen.",
    applicationKeywords: ["legen nahe", "Reichweite", "Desiderat"],
  },
  {
    id: "nominal-style-c1",
    title: "Unpack nominal style",
    titleDe: "Nominalstil entpacken",
    level: "c1",
    chapterSlug: "admin-legal",
    summary: "Official German hides agents in nouns. Put the verb and the date back.",
    prerequisites: ["academic-hedge-c1"],
    commonMistakes: [
      "Es erfolgt eine Prüfung zeitnah — who, by when?",
      "Unpacking into slang instead of into a clear verb + date.",
    ],
    vocabDependencies: ["erfolgen", "Durchführung", "zeitnah"],
    examples: [
      { de: "Eine Prüfung wird zeitnah durchgeführt. → Wir prüfen bis zum 15.04.", en: "We will examine by 15 April." },
    ],
    applicationPrompt: "Rewrite two Amtsdeutsch sentences with agent and date.",
    applicationPromptDe: "Zwei Amtssätze entpacken.",
    applicationSample: "Wir prüfen den Fall. Das Ergebnis teilen wir bis zum 15. April mit.",
    applicationKeywords: ["wir", "bis"],
  },
];
