import type { DialogueTurn, LevelId } from "@/content/types";

export type ConversationMission = {
  id: string;
  level: LevelId;
  title: string;
  titleDe: string;
  setting: string;
  settingDe: string;
  minutes: number;
  goal: string;
  goalDe: string;
  turns: DialogueTurn[];
};

export const CONVERSATIONS: ConversationMission[] = [
  {
    id: "a1-cafe",
    level: "a1",
    title: "Order at the café",
    titleDe: "Im Café bestellen",
    setting: "You are at the counter. Order a drink and say thank you.",
    settingDe: "Du stehst an der Theke. Bestelle ein Getränk und sag danke.",
    minutes: 6,
    goal: "Survive a two-minute café order without English.",
    goalDe: "Eine kurze Bestellung auf Deutsch schaffen.",
    turns: [
      { speaker: "npc", de: "Guten Tag! Was möchten Sie?", en: "Good day! What would you like?" },
      {
        speaker: "you",
        de: "Einen Kaffee, bitte.",
        en: "A coffee, please.",
        keywords: ["Kaffee", "bitte", "Tee", "Wasser", "möchte"],
      },
      { speaker: "npc", de: "Mit Milch?", en: "With milk?" },
      {
        speaker: "you",
        de: "Ja, mit Milch. Danke!",
        en: "Yes, with milk. Thanks!",
        keywords: ["Ja", "Nein", "Milch", "Danke"],
      },
      { speaker: "npc", de: "Das macht 2,80 Euro.", en: "That is 2.80 euros." },
      {
        speaker: "you",
        de: "Bitte schön. Danke!",
        en: "Here you are. Thanks!",
        keywords: ["Danke", "Bitte", "Euro"],
      },
    ],
  },
  {
    id: "a1-name",
    level: "a1",
    title: "Introduce yourself",
    titleDe: "Sich vorstellen",
    setting: "A new classmate greets you. Say your name and where you are from.",
    settingDe: "Eine neue Person begrüßt dich. Sag Namen und Herkunft.",
    minutes: 5,
    goal: "Get through a first-meeting chat.",
    goalDe: "Ein erstes Gespräch bestehen.",
    turns: [
      { speaker: "npc", de: "Hallo! Wie heißt du?", en: "Hi! What is your name?" },
      {
        speaker: "you",
        de: "Ich heiße Alex.",
        en: "My name is Alex.",
        keywords: ["heiße", "Ich", "Name"],
      },
      { speaker: "npc", de: "Woher kommst du?", en: "Where are you from?" },
      {
        speaker: "you",
        de: "Ich komme aus Italien.",
        en: "I come from Italy.",
        keywords: ["komme", "aus"],
      },
      { speaker: "npc", de: "Schön! Bis morgen.", en: "Nice! See you tomorrow." },
      {
        speaker: "you",
        de: "Bis morgen!",
        en: "See you tomorrow!",
        keywords: ["Bis", "Tschüss", "morgen"],
      },
    ],
  },
  {
    id: "a1-shop",
    level: "a1",
    title: "Ask in a shop",
    titleDe: "Im Geschäft fragen",
    setting: "You need bread. Ask and pay.",
    settingDe: "Du brauchst Brot. Frag und bezahle.",
    minutes: 6,
    goal: "Ask for an item and understand the price.",
    goalDe: "Nach Ware fragen und den Preis verstehen.",
    turns: [
      { speaker: "npc", de: "Kann ich Ihnen helfen?", en: "Can I help you?" },
      {
        speaker: "you",
        de: "Ja. Haben Sie Brot?",
        en: "Yes. Do you have bread?",
        keywords: ["Haben", "Brot", "bitte"],
      },
      { speaker: "npc", de: "Ja. Das Brot kostet 2 Euro.", en: "Yes. The bread costs 2 euros." },
      {
        speaker: "you",
        de: "Gut, ich nehme das. Danke.",
        en: "Good, I'll take that. Thanks.",
        keywords: ["nehme", "Danke", "bitte", "Euro"],
      },
    ],
  },
  {
    id: "a1-phone",
    level: "a1",
    title: "A short phone call",
    titleDe: "Ein kurzes Telefonat",
    setting: "Someone calls. Say who you are and that you will pass the message.",
    settingDe: "Jemand ruft an. Sag, wer du bist, und dass du Bescheid sagst.",
    minutes: 5,
    goal: "Survive a 30-second phone call.",
    goalDe: "Ein kurzes Telefonat schaffen.",
    turns: [
      { speaker: "npc", de: "Hallo, ist da Anna?", en: "Hi, is Anna there?" },
      {
        speaker: "you",
        de: "Nein, hier ist Alex. Wer ist da bitte?",
        en: "No, this is Alex. Who is calling please?",
        keywords: ["Nein", "hier", "Wer", "bitte"],
      },
      { speaker: "npc", de: "Hier ist Ben, ein Freund. Kann Anna später anrufen?", en: "This is Ben, a friend. Can Anna call later?" },
      {
        speaker: "you",
        de: "Ja. Ich sage es ihr. Tschüss!",
        en: "Yes. I will tell her. Bye!",
        keywords: ["Ja", "sage", "Tschüss", "Danke"],
      },
    ],
  },
  {
    id: "a1-neighbor",
    level: "a1",
    title: "Ask a neighbour",
    titleDe: "Den Nachbarn fragen",
    setting: "You need sugar. Knock and ask politely.",
    settingDe: "Du brauchst Zucker. Klingle und frag höflich.",
    minutes: 5,
    goal: "Borrow one thing without switching to English.",
    goalDe: "Eine Sache ausleihen, ohne Englisch.",
    turns: [
      { speaker: "npc", de: "Ja bitte?", en: "Yes?" },
      {
        speaker: "you",
        de: "Guten Tag. Haben Sie Zucker, bitte?",
        en: "Good day. Do you have sugar, please?",
        keywords: ["Haben", "Zucker", "bitte", "Guten"],
      },
      { speaker: "npc", de: "Ja, einen Moment. Hier, bitte.", en: "Yes, one moment. Here you are." },
      {
        speaker: "you",
        de: "Vielen Dank! Bis bald.",
        en: "Many thanks! See you soon.",
        keywords: ["Dank", "bald", "Tschüss"],
      },
    ],
  },
  {
    id: "a2-train",
    level: "a2",
    title: "At the ticket machine",
    titleDe: "Am Fahrkartenautomaten",
    setting: "The machine is confusing. Ask a person for the platform.",
    settingDe: "Der Automat ist unklar. Frag nach dem Gleis.",
    minutes: 7,
    goal: "Get a ticket and the right platform.",
    goalDe: "Fahrkarte und Gleis klären.",
    turns: [
      { speaker: "npc", de: "Entschuldigung, brauchen Sie Hilfe?", en: "Excuse me, do you need help?" },
      {
        speaker: "you",
        de: "Ja. Ich möchte nach Leipzig, bitte.",
        en: "Yes. I would like to go to Leipzig, please.",
        keywords: ["möchte", "Leipzig", "Fahrkarte", "bitte"],
      },
      { speaker: "npc", de: "Einfache Fahrt oder hin und zurück?", en: "Single or return?" },
      {
        speaker: "you",
        de: "Einfache Fahrt. Welches Gleis?",
        en: "Single. Which platform?",
        keywords: ["Einfach", "Gleis", "zurück"],
      },
      { speaker: "npc", de: "Gleis 4, in zehn Minuten.", en: "Platform 4, in ten minutes." },
      {
        speaker: "you",
        de: "Danke, das hilft.",
        en: "Thanks, that helps.",
        keywords: ["Danke", "Gleis"],
      },
    ],
  },
  {
    id: "a2-doctor",
    level: "a2",
    title: "At the doctor's",
    titleDe: "Beim Arzt",
    setting: "You feel ill. Describe symptoms and ask what to do.",
    settingDe: "Dir geht es schlecht. Beschreibe Symptome.",
    minutes: 7,
    goal: "Explain that you are ill and understand simple advice.",
    goalDe: "Krankheit erklären und einen Rat verstehen.",
    turns: [
      { speaker: "npc", de: "Was fehlt Ihnen?", en: "What is the matter?" },
      {
        speaker: "you",
        de: "Ich habe Husten und der Kopf tut weh.",
        en: "I have a cough and my head hurts.",
        keywords: ["Husten", "Kopf", "weh", "krank"],
      },
      { speaker: "npc", de: "Seit wann?", en: "Since when?" },
      {
        speaker: "you",
        de: "Seit gestern. Ich muss arbeiten.",
        en: "Since yesterday. I have to work.",
        keywords: ["gestern", "muss", "arbeiten", "Tage"],
      },
      { speaker: "npc", de: "Bleiben Sie morgen zu Hause und trinken Sie Tee.", en: "Stay home tomorrow and drink tea." },
      {
        speaker: "you",
        de: "Gut. Brauche ich eine Krankmeldung?",
        en: "Okay. Do I need a sick note?",
        keywords: ["Krankmeldung", "Tee", "Danke", "Haus"],
      },
    ],
  },
  {
    id: "a2-landlord",
    level: "a2",
    title: "Call the landlord",
    titleDe: "Den Vermieter anrufen",
    setting: "Something is dripping. Leave a clear message.",
    settingDe: "Etwas tropft. Hinterlasse eine klare Nachricht.",
    minutes: 6,
    goal: "Report a problem with time and place.",
    goalDe: "Einen Schaden mit Ort und Zeit melden.",
    turns: [
      { speaker: "npc", de: "Berger, hallo?", en: "Berger, hello?" },
      {
        speaker: "you",
        de: "Guten Tag, hier ist Frau Hofmann aus Wohnung 12.",
        en: "Good day, this is Ms Hofmann from flat 12.",
        keywords: ["Wohnung", "Hofmann", "Guten", "Tag"],
      },
      { speaker: "npc", de: "Was gibt's?", en: "What's up?" },
      {
        speaker: "you",
        de: "Der Wasserhahn in der Küche tropft seit Dienstag.",
        en: "The kitchen tap has been dripping since Tuesday.",
        keywords: ["Wasserhahn", "Küche", "tropft", "Dienstag"],
      },
      { speaker: "npc", de: "Ich schicke morgen jemanden. Sind Sie nach 17 Uhr da?", en: "I'll send someone tomorrow. Are you in after 5?" },
      {
        speaker: "you",
        de: "Ja, nach 17 Uhr bin ich da. Danke.",
        en: "Yes, I am in after 5. Thanks.",
        keywords: ["Ja", "17", "Danke", "da"],
      },
    ],
  },
  {
    id: "a2-pharmacy",
    level: "a2",
    title: "At the pharmacy",
    titleDe: "In der Apotheke",
    setting: "You have a cold. Ask for something and how to take it.",
    settingDe: "Du bist erkältet. Frag nach einem Mittel und der Einnahme.",
    minutes: 6,
    goal: "Name a symptom and understand simple instructions.",
    goalDe: "Ein Symptom nennen und eine Anweisung verstehen.",
    turns: [
      { speaker: "npc", de: "Guten Tag. Was kann ich für Sie tun?", en: "Good day. How can I help?" },
      {
        speaker: "you",
        de: "Ich habe Husten. Haben Sie etwas dagegen?",
        en: "I have a cough. Do you have something for it?",
        keywords: ["Husten", "Haben", "etwas", "bitte"],
      },
      { speaker: "npc", de: "Ja. Nehmen Sie dreimal täglich einen Löffel, nach dem Essen.", en: "Yes. Take one spoon three times a day, after food." },
      {
        speaker: "you",
        de: "Nach dem Essen, dreimal. Danke.",
        en: "After food, three times. Thanks.",
        keywords: ["Essen", "dreimal", "Danke"],
      },
    ],
  },
  {
    id: "a2-weekend",
    level: "a2",
    title: "Weekend small talk",
    titleDe: "Smalltalk übers Wochenende",
    setting: "A colleague asks about Saturday. Suggest a plan.",
    settingDe: "Eine Kollegin fragt nach Samstag. Schlage etwas vor.",
    minutes: 6,
    goal: "Talk about plans with weil or deshalb.",
    goalDe: "Pläne mit weil oder deshalb sagen.",
    turns: [
      { speaker: "npc", de: "Was machst du am Wochenende?", en: "What are you doing at the weekend?" },
      {
        speaker: "you",
        de: "Ich gehe in die Stadt, weil das Wetter gut ist.",
        en: "I am going into town because the weather is good.",
        keywords: ["weil", "Stadt", "Wetter", "gehe"],
      },
      { speaker: "npc", de: "Kommst du mit zum Kaffee um drei?", en: "Will you come for coffee at three?" },
      {
        speaker: "you",
        de: "Ja, gerne. Bis dann!",
        en: "Yes, gladly. See you then!",
        keywords: ["Ja", "gerne", "dann", "drei"],
      },
    ],
  },
  {
    id: "a2-appointment",
    level: "a2",
    title: "Book an appointment",
    titleDe: "Einen Termin machen",
    setting: "You call a salon. Give a day and a time.",
    settingDe: "Du rufst beim Friseur an. Sag Tag und Uhrzeit.",
    minutes: 6,
    goal: "Make a simple appointment and repeat the time.",
    goalDe: "Einen einfachen Termin festmachen.",
    turns: [
      { speaker: "npc", de: "Friseursalon Berger, hallo?", en: "Berger salon, hello?" },
      {
        speaker: "you",
        de: "Guten Tag. Ich möchte einen Termin, bitte. Geht Donnerstag?",
        en: "Good day. I would like an appointment, please. Is Thursday possible?",
        keywords: ["Termin", "Donnerstag", "möchte", "bitte"],
      },
      { speaker: "npc", de: "Donnerstag um 16 Uhr ist frei. Name bitte?", en: "Thursday at 4 p.m. is free. Name please?" },
      {
        speaker: "you",
        de: "Lea Hofmann. 16 Uhr, Donnerstag. Danke.",
        en: "Lea Hofmann. 4 p.m., Thursday. Thanks.",
        keywords: ["Uhr", "Donnerstag", "Danke", "Hofmann"],
      },
    ],
  },
  {
    id: "b1-meeting",
    level: "b1",
    title: "Shift a meeting",
    titleDe: "Einen Termin verschieben",
    setting: "You cannot make Wednesday. Propose a new time politely.",
    settingDe: "Mittwoch geht nicht. Schlage höflich eine neue Zeit vor.",
    minutes: 8,
    goal: "Reschedule without sounding rude.",
    goalDe: "Höflich umlegen.",
    turns: [
      { speaker: "npc", de: "Passt Mittwoch um zehn immer noch?", en: "Is Wednesday at ten still okay?" },
      {
        speaker: "you",
        de: "Leider nicht. Könnten wir auf Donnerstag verschieben?",
        en: "Unfortunately not. Could we move it to Thursday?",
        keywords: ["Leider", "Donnerstag", "verschieben", "Könnten"],
      },
      { speaker: "npc", de: "Donnerstag früh ist voll. Nachmittag?", en: "Thursday morning is full. Afternoon?" },
      {
        speaker: "you",
        de: "Ja, um 14 Uhr geht. Danke für die Flexibilität.",
        en: "Yes, 2 p.m. works. Thanks for the flexibility.",
        keywords: ["14", "Ja", "Danke", "Uhr"],
      },
    ],
  },
  {
    id: "b1-opinion",
    level: "b1",
    title: "Agree, then disagree",
    titleDe: "Zustimmen, dann widersprechen",
    setting: "A colleague wants open-plan desks only. Keep it civil.",
    settingDe: "Eine Kollegin will nur Großraum. Bleib sachlich.",
    minutes: 8,
    goal: "Use weil / aber / ich finde, dass.",
    goalDe: "Mit weil und aber argumentieren.",
    turns: [
      { speaker: "npc", de: "Ich finde, alle sollten im Büro sitzen. Homeoffice ist unproduktiv.", en: "I think everyone should sit in the office. Home office is unproductive." },
      {
        speaker: "you",
        de: "Ich verstehe den Punkt, aber das stimmt nur teilweise.",
        en: "I see the point, but that is only partly true.",
        keywords: ["aber", "teilweise", "verstehe", "finde"],
      },
      { speaker: "npc", de: "Warum?", en: "Why?" },
      {
        speaker: "you",
        de: "Weil stilles Schreiben zu Hause besser klappt. Meetings gehören ins Büro.",
        en: "Because quiet writing works better at home. Meetings belong in the office.",
        keywords: ["weil", "Büro", "Hause", "Meetings"],
      },
    ],
  },
  {
    id: "b1-restaurant",
    level: "b1",
    title: "Allergy at the restaurant",
    titleDe: "Allergie im Restaurant",
    setting: "You have a nut allergy. Check the dish and split the bill.",
    settingDe: "Du hast eine Nussallergie. Prüfe das Gericht und teile die Rechnung.",
    minutes: 7,
    goal: "State a constraint clearly and close the situation.",
    goalDe: "Eine Einschränkung klar sagen und die Situation schließen.",
    turns: [
      { speaker: "npc", de: "Haben Sie schon gewählt?", en: "Have you chosen already?" },
      {
        speaker: "you",
        de: "Fast. Ich habe eine Nussallergie. Ist die Soße ohne Nüsse?",
        en: "Almost. I have a nut allergy. Is the sauce without nuts?",
        keywords: ["Allergie", "Nuss", "ohne", "Soße"],
      },
      { speaker: "npc", de: "Die Soße ist ohne Nüsse. Die Beilage nicht — ich lasse sie weg.", en: "The sauce is nut-free. The side is not — I will leave it off." },
      {
        speaker: "you",
        de: "Perfekt, dann das. Könnten wir die Rechnung später teilen?",
        en: "Perfect, then that. Could we split the bill later?",
        keywords: ["Rechnung", "teilen", "Könnten", "dann"],
      },
    ],
  },
  {
    id: "b1-voicemail",
    level: "b1",
    title: "Leave a voicemail",
    titleDe: "Auf den Anrufbeantworter sprechen",
    setting: "Nobody picks up. Leave name, reason, and a callback time.",
    settingDe: "Niemand geht ran. Hinterlasse Name, Grund und Rückrufzeit.",
    minutes: 6,
    goal: "A complete spoken message in 20 seconds.",
    goalDe: "Eine vollständige Nachricht in 20 Sekunden.",
    turns: [
      { speaker: "npc", de: "Sie haben den Anrufbeantworter von Frau Berger erreicht. Bitte sprechen Sie nach dem Ton.", en: "You have reached Ms Berger's voicemail. Please speak after the tone." },
      {
        speaker: "you",
        de: "Guten Tag, hier ist Lea Hofmann. Ich rufe wegen des Termins am Donnerstag an.",
        en: "Good day, this is Lea Hofmann. I am calling about Thursday's appointment.",
        keywords: ["Hofmann", "Termin", "Donnerstag", "Guten"],
      },
      { speaker: "npc", de: "Ton.", en: "Beep." },
      {
        speaker: "you",
        de: "Bitte rufen Sie mich nach 17 Uhr zurück. Meine Nummer kennen Sie. Danke und auf Wiederhören.",
        en: "Please call me back after 5 p.m. You have my number. Thanks and goodbye.",
        keywords: ["zurück", "17", "Danke", "Wiederhören"],
      },
    ],
  },
  {
    id: "b2-interview",
    level: "b2",
    title: "A tough interview question",
    titleDe: "Eine harte Interviewfrage",
    setting: "They ask about a conflict at work. Stay precise.",
    settingDe: "Frage nach einem Konflikt. Bleib präzise.",
    minutes: 8,
    goal: "Answer with situation, action, result — no rant.",
    goalDe: "Situation, Handlung, Ergebnis — ohne Schimpfen.",
    turns: [
      { speaker: "npc", de: "Schildern Sie einen Konflikt im Team. Was haben Sie getan?", en: "Describe a team conflict. What did you do?" },
      {
        speaker: "you",
        de: "Zwei Kolleginnen stritten um die Deadline. Ich habe die Aufgaben getrennt und eine gemeinsame Frist gesetzt.",
        en: "Two colleagues argued about the deadline. I split the tasks and set a shared deadline.",
        keywords: ["Deadline", "Frist", "Team", "Aufgaben", "Konflikt"],
      },
      { speaker: "npc", de: "Und das Ergebnis?", en: "And the result?" },
      {
        speaker: "you",
        de: "Die Lieferung kam, und das Gespräch blieb sachlich. Ich würde heute früher klären, wer entscheidet.",
        en: "The delivery arrived and the talk stayed factual. Today I would clarify earlier who decides.",
        keywords: ["sachlich", "Ergebnis", "würde", "gekommen", "Lieferung"],
      },
    ],
  },
  {
    id: "c1-qna",
    level: "c1",
    title: "Q&A after a short talk",
    titleDe: "Fragen nach dem Kurzvortrag",
    setting: "Someone challenges your evidence. Concede a limit, keep the claim.",
    settingDe: "Jemand greift deine Evidenz an. Räum eine Grenze ein, halte die These.",
    minutes: 8,
    goal: "Handle a critical question without collapsing.",
    goalDe: "Eine kritische Frage halten.",
    turns: [
      { speaker: "npc", de: "Ihre Stichprobe ist urban. Übertragen Sie das auf das Land?", en: "Your sample is urban. Do you transfer it to rural areas?" },
      {
        speaker: "you",
        de: "Nein. Übertragbar sind die Mechanismen, nicht die Prozentwerte. Ein ländlicher Vergleich bleibt ein Desiderat.",
        en: "No. The mechanisms transfer, not the percentages. A rural comparison remains a gap.",
        keywords: ["übertragbar", "Mechanismen", "Desiderat", "ländlich", "Prozent"],
      },
      { speaker: "npc", de: "Dann ist die These doch schwach.", en: "Then the thesis is weak." },
      {
        speaker: "you",
        de: "Die These ist begrenzt, nicht schwach. Wir legen nahe, nicht: wir beweisen kausal.",
        en: "The thesis is limited, not weak. We suggest; we do not prove causation.",
        keywords: ["begrenzt", "legen nahe", "beweisen", "These"],
      },
    ],
  },
];

export function conversationsFor(level: LevelId): ConversationMission[] {
  return CONVERSATIONS.filter((item) => item.level === level);
}

export function getConversation(id: string): ConversationMission | undefined {
  return CONVERSATIONS.find((item) => item.id === id);
}
